function motion = resolveMotion(motionInput)
%RESOLVEMOTION Return parsed MOT structure.

    if ischar(motionInput) || ...
            (isstring(motionInput) && isscalar(motionInput))
        motion = opensimio.readMot(motionInput);
    elseif isstruct(motionInput) && ...
            all(isfield(motionInput, ...
            ["Labels", "Data", "Time", "InDegrees"]))
        motion = motionInput;
    else
        error("hsf:InvalidMotionInput", ...
            ["motionInput must be a .mot path or a structure returned " ...
             "by opensimio.readMot()."]);
    end
end
