function cfg = load_project_config(varargin)
%LOAD_PROJECT_CONFIG Load shared and machine-specific project settings.
%
% cfg = load_project_config()
%
% Name-value options:
%   RequireLocalConfig  true
%   ValidatePaths       true
%
% Configuration order:
%   1. Repository root is detected automatically.
%   2. config/project_defaults.m is executed.
%   3. config/project_local.m overrides machine-specific fields.
%   4. Legacy runtime fields are migrated to the canonical namespace.
%   5. Optional machine-specific defaults are supplied.
%   6. Configuration schema and required paths are validated.
%
% Canonical configuration contract:
%
%   cfg.conditions
%   cfg.trials
%       Version-controlled study design. Local/process scripts may
%       intentionally override these to run subsets.
%
%   cfg.overwriteExisting
%       Shared overwrite behavior used by single-trial and batch workflows.
%
%   cfg.batchProcessing.enableParallel
%   cfg.batchProcessing.maxWorkers
%       Batch-only parallel execution settings.
%
% Deprecated legacy fields:
%   cfg.enableParallel
%   cfg.maxWorkers
%
% Legacy fields are migrated with a warning so existing project_local.m
% files continue to work while they are updated.

    parser = inputParser;
    parser.FunctionName = "load_project_config";

    addParameter(parser, ...
        "RequireLocalConfig", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "ValidatePaths", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, varargin{:});

    %% Locate repository

    loaderFile = string(mfilename("fullpath"));
    projectRoot = string(fileparts(loaderFile));

    defaultsFile = fullfile( ...
        projectRoot, ...
        "config", ...
        "project_defaults.m");

    localFile = fullfile( ...
        projectRoot, ...
        "config", ...
        "project_local.m");

    exampleFile = fullfile( ...
        projectRoot, ...
        "config", ...
        "project_local_example.m");

    assert(isfile(defaultsFile), ...
        "ProjectConfig:DefaultsMissing", ...
        "Shared defaults file was not found:\n%s", ...
        defaultsFile);

    %% Load shared defaults

    cfg = struct();
    cfg.projectRoot = projectRoot;

    run(defaultsFile);

    %% Load machine-specific overrides

    if isfile(localFile)

        run(localFile);

    elseif parser.Results.RequireLocalConfig

        error( ...
            "ProjectConfig:LocalConfigMissing", ...
            "Machine-specific configuration was not found:\n%s\n\n" + ...
            "Copy:\n%s\n\nto:\n%s\n\nand edit the local paths.", ...
            localFile, ...
            exampleFile, ...
            localFile);
    end

    cfg.configDirectory = fullfile(projectRoot, "config");
    cfg.defaultsFile = string(defaultsFile);
    cfg.localFile = string(localFile);

    %% Normalize legacy configuration fields

    cfg = migrateLegacyRuntimeFields(cfg);

    %% Supply optional machine-specific defaults

    cfg = setDefault(cfg, "machineName", "");
    cfg = setDefault(cfg, "rawDataRoot", "");
    cfg = setDefault(cfg, "opensimRoot", "");
    cfg = setDefault(cfg, "openSimJavaJar", "");
    cfg = setDefault(cfg, "openSimBinDirectory", "");

    % Defensive defaults for repositories/configurations predating the
    % canonical batchProcessing namespace.
    if ~isfield(cfg, "batchProcessing") || ...
            ~isstruct(cfg.batchProcessing)

        cfg.batchProcessing = struct;
    end

    cfg.batchProcessing = setStructDefault( ...
        cfg.batchProcessing, ...
        "enableParallel", ...
        false);

    cfg.batchProcessing = setStructDefault( ...
        cfg.batchProcessing, ...
        "maxWorkers", ...
        1);

    %% Validate

    validateConfigurationSchema(cfg);

    if parser.Results.ValidatePaths
        validateConfigurationPaths(cfg);
    end
end


function cfg = migrateLegacyRuntimeFields(cfg)
%MIGRATELEGACYRUNTIMEFIELDS Move deprecated fields into canonical nesting.
%
% This compatibility layer is intentionally temporary. The canonical
% fields are cfg.batchProcessing.enableParallel and
% cfg.batchProcessing.maxWorkers.

    if ~isfield(cfg, "batchProcessing") || ...
            ~isstruct(cfg.batchProcessing)

        cfg.batchProcessing = struct;
    end

    if isfield(cfg, "enableParallel")

        warning( ...
            "ProjectConfig:DeprecatedEnableParallel", ...
            "cfg.enableParallel is deprecated. " + ...
            "Use cfg.batchProcessing.enableParallel instead.");

        cfg.batchProcessing.enableParallel = ...
            cfg.enableParallel;

        cfg = rmfield(cfg, "enableParallel");
    end

    if isfield(cfg, "maxWorkers")

        warning( ...
            "ProjectConfig:DeprecatedMaxWorkers", ...
            "cfg.maxWorkers is deprecated. " + ...
            "Use cfg.batchProcessing.maxWorkers instead.");

        cfg.batchProcessing.maxWorkers = ...
            cfg.maxWorkers;

        cfg = rmfield(cfg, "maxWorkers");
    end
end


function cfg = setDefault(cfg, fieldName, defaultValue)

    if ~isfield(cfg, fieldName)
        cfg.(fieldName) = defaultValue;
    end
end


function s = setStructDefault(s, fieldName, defaultValue)

    if ~isfield(s, fieldName)
        s.(fieldName) = defaultValue;
    end
end


function validateConfigurationSchema(cfg)
%VALIDATECONFIGURATIONSCHEMA Validate types and canonical configuration.
%
% This validation is intentionally independent of filesystem existence so
% malformed configuration fails even when ValidatePaths=false.

    %% Study design

    assert(isnumeric(cfg.conditions) && ...
        isvector(cfg.conditions) && ...
        ~isempty(cfg.conditions) && ...
        all(isfinite(cfg.conditions)), ...
        "ProjectConfig:InvalidConditions", ...
        "cfg.conditions must be a nonempty finite numeric vector.");

    assert(numel(unique(cfg.conditions)) == numel(cfg.conditions), ...
        "ProjectConfig:DuplicateConditions", ...
        "cfg.conditions must not contain duplicate values.");

    assert(isnumeric(cfg.trials) && ...
        isvector(cfg.trials) && ...
        ~isempty(cfg.trials) && ...
        all(isfinite(cfg.trials)) && ...
        all(cfg.trials >= 1) && ...
        all(mod(cfg.trials, 1) == 0), ...
        "ProjectConfig:InvalidTrials", ...
        "cfg.trials must be a nonempty vector of positive integers.");

    assert(numel(unique(cfg.trials)) == numel(cfg.trials), ...
        "ProjectConfig:DuplicateTrials", ...
        "cfg.trials must not contain duplicate values.");

    %% Shared runtime behavior

    assert(islogical(cfg.overwriteExisting) && ...
        isscalar(cfg.overwriteExisting), ...
        "ProjectConfig:InvalidOverwriteExisting", ...
        "cfg.overwriteExisting must be a logical scalar.");

    %% Batch processing

    assert(isfield(cfg, "batchProcessing") && ...
        isstruct(cfg.batchProcessing), ...
        "ProjectConfig:BatchProcessingMissing", ...
        "cfg.batchProcessing must be a struct.");

    assert(isfield(cfg.batchProcessing, "enableParallel") && ...
        islogical(cfg.batchProcessing.enableParallel) && ...
        isscalar(cfg.batchProcessing.enableParallel), ...
        "ProjectConfig:InvalidEnableParallel", ...
        "cfg.batchProcessing.enableParallel must be a logical scalar.");

    assert(isfield(cfg.batchProcessing, "maxWorkers") && ...
        isnumeric(cfg.batchProcessing.maxWorkers) && ...
        isscalar(cfg.batchProcessing.maxWorkers) && ...
        isfinite(cfg.batchProcessing.maxWorkers) && ...
        cfg.batchProcessing.maxWorkers >= 1 && ...
        mod(cfg.batchProcessing.maxWorkers, 1) == 0, ...
        "ProjectConfig:InvalidMaxWorkerCount", ...
        "cfg.batchProcessing.maxWorkers must be a positive integer.");

    %% Force-capacity configuration

    assert(isfield(cfg, "forceCapacity") && ...
        isstruct(cfg.forceCapacity), ...
        "ProjectConfig:ForceCapacityMissing", ...
        "cfg.forceCapacity must be a struct.");

    assert(islogical(cfg.forceCapacity.enabled) && ...
        isscalar(cfg.forceCapacity.enabled), ...
        "ProjectConfig:InvalidForceCapacityEnabled", ...
        "cfg.forceCapacity.enabled must be a logical scalar.");

    assert(any(strcmpi( ...
        string(cfg.forceCapacity.applyMode), ...
        ["target","scale"])), ...
        "ProjectConfig:InvalidForceCapacityApplyMode", ...
        "cfg.forceCapacity.applyMode must be 'target' or 'scale'.");

    assert(islogical(cfg.forceCapacity.requireAllEntries) && ...
        isscalar(cfg.forceCapacity.requireAllEntries), ...
        "ProjectConfig:InvalidForceCapacityRequireAllEntries", ...
        "cfg.forceCapacity.requireAllEntries must be a logical scalar.");

    if cfg.forceCapacity.enabled

        assert(strlength( ...
            string(cfg.forceCapacity.configFile)) > 0, ...
            "ProjectConfig:ForceCapacityConfigMissing", ...
            "forceCapacity.configFile is required when forceCapacity.enabled=true.");
    end

    %% Reject stale duplicate namespaces

    assert(~isfield(cfg, "enableParallel"), ...
        "ProjectConfig:LegacyEnableParallelPersisted", ...
        "Deprecated cfg.enableParallel persisted after migration.");

    assert(~isfield(cfg, "maxWorkers"), ...
        "ProjectConfig:LegacyMaxWorkersPersisted", ...
        "Deprecated cfg.maxWorkers persisted after migration.");
end


function validateConfigurationPaths(cfg)
%VALIDATECONFIGURATIONPATHS Validate required directories/files.

    assert(isfolder(cfg.projectRoot), ...
        "ProjectConfig:ProjectRootMissing", ...
        "Project root was not found:\n%s", ...
        cfg.projectRoot);

    assert(isfolder(cfg.modelsDirectory), ...
        "ProjectConfig:ModelsDirectoryMissing", ...
        "Models directory was not found:\n%s", ...
        cfg.modelsDirectory);

    assert(isfolder(cfg.inputDirectory), ...
        "ProjectConfig:InputDirectoryMissing", ...
        "Input directory was not found:\n%s", ...
        cfg.inputDirectory);

    if ~isfolder(cfg.outputRoot)
        mkdir(cfg.outputRoot);
    end

    if cfg.requireKinematicBaseModel

        assert(isfile(cfg.kinematicBaseModel), ...
            "ProjectConfig:KinematicModelMissing", ...
            "Kinematic base model was not found:\n%s", ...
            cfg.kinematicBaseModel);
    end

    if cfg.requireScalingBaseModel

        assert(isfile(cfg.scalingBaseModel), ...
            "ProjectConfig:ScalingModelMissing", ...
            "Scaling base model was not found:\n%s", ...
            cfg.scalingBaseModel);
    end

    if cfg.requireInitializationIkTemplate

        assert(isfile(cfg.initializationIkTemplate), ...
            "ProjectConfig:IkTemplateMissing", ...
            "Initialization IK template was not found:\n%s", ...
            cfg.initializationIkTemplate);
    end

    if cfg.requireExternalLoadsTemplate

        assert(isfile(cfg.externalLoadsTemplate), ...
            "ProjectConfig:ExternalLoadsTemplateMissing", ...
            "ExternalLoads template was not found:\n%s", ...
            cfg.externalLoadsTemplate);
    end

    if cfg.requireStaticOptimizationTemplate

        assert(isfile(cfg.staticOptimizationTemplate), ...
            "ProjectConfig:StaticOptimizationTemplateMissing", ...
            "Static Optimization template was not found:\n%s", ...
            cfg.staticOptimizationTemplate);
    end

    if strlength(string(cfg.rawDataRoot)) > 0

        assert(isfolder(cfg.rawDataRoot), ...
            "ProjectConfig:RawDataRootMissing", ...
            "Raw-data directory was not found:\n%s", ...
            cfg.rawDataRoot);
    end

    if cfg.forceCapacity.enabled

        assert(isfile(cfg.forceCapacity.configFile), ...
            "ProjectConfig:ForceCapacityConfigNotFound", ...
            "Force-capacity configuration was not found:\n%s", ...
            cfg.forceCapacity.configFile);
    end
end
