function cfg = load_project_config(varargin)
%LOAD_PROJECT_CONFIG Load and validate project configuration.
%
% cfg = load_project_config()
%
% Name-value options:
%   RequireLocalConfig  true
%   ValidatePaths       true
%
% Configuration order:
%   1. Detect repository root.
%   2. Execute config/project_defaults.m.
%   3. Execute config/project_local.m as machine-specific overrides.
%   4. Migrate deprecated legacy runtime fields.
%   5. Supply defensive optional defaults.
%   6. Validate configuration schema.
%   7. Optionally validate required files/directories.
%
% Canonical configuration namespaces:
%   cfg.conditions / cfg.trials
%   cfg.overwriteExisting
%   cfg.modelValidation
%   cfg.pipeline
%   cfg.qc
%   cfg.hsf
%   cfg.forceCapacity
%   cfg.analysis
%   cfg.batchProcessing
%
% Deprecated legacy fields:
%   cfg.enableParallel
%   cfg.maxWorkers

    parser = inputParser;
    parser.FunctionName = "load_project_config";

    addParameter(parser, ...
        "RequireLocalConfig", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "ValidatePaths", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, varargin{:});

    %% Locate repository

    loaderFile = string(mfilename("fullpath"));
    projectRoot = string(fileparts(loaderFile));

    defaultsFile = fullfile( ...
        projectRoot, ...
        "config", ...
        "project_defaults.m");

    localFile = fullfile( ...
        projectRoot, ...
        "config", ...
        "project_local.m");

    exampleFile = fullfile( ...
        projectRoot, ...
        "config", ...
        "project_local_example.m");

    assert(isfile(defaultsFile), ...
        "ProjectConfig:DefaultsMissing", ...
        "Shared defaults file was not found:\n%s", ...
        defaultsFile);

    %% Load version-controlled defaults

    cfg = struct;
    cfg.projectRoot = projectRoot;

    run(defaultsFile);

    %% Load machine-specific overrides

    if isfile(localFile)

        run(localFile);

    elseif parser.Results.RequireLocalConfig

        error( ...
            "ProjectConfig:LocalConfigMissing", ...
            "Machine-specific configuration was not found:\n%s\n\n" + ...
            "Copy:\n%s\n\nto:\n%s\n\nand edit the local paths.", ...
            localFile, ...
            exampleFile, ...
            localFile);
    end

    cfg.configDirectory = fullfile(projectRoot, "config");
    cfg.defaultsFile = string(defaultsFile);
    cfg.localFile = string(localFile);

    %% Migrate legacy fields

    cfg = migrateLegacyRuntimeFields(cfg);

    %% Defensive optional machine defaults

    cfg = setDefault(cfg, "machineName", "");
    cfg = setDefault(cfg, "rawDataRoot", "");
    cfg = setDefault(cfg, "opensimRoot", "");
    cfg = setDefault(cfg, "openSimJavaJar", "");
    cfg = setDefault(cfg, "openSimBinDirectory", "");

    %% Validate schema before touching the filesystem

    validateConfigurationSchema(cfg);

    %% Validate files/directories

    if parser.Results.ValidatePaths
        validateConfigurationPaths(cfg);
    end
end


function cfg = migrateLegacyRuntimeFields(cfg)
%MIGRATELEGACYRUNTIMEFIELDS Preserve old local configs during transition.

    if ~isfield(cfg, "batchProcessing") || ...
            ~isstruct(cfg.batchProcessing)

        cfg.batchProcessing = struct;
    end

    if isfield(cfg, "enableParallel")

        warning( ...
            "ProjectConfig:DeprecatedEnableParallel", ...
            "cfg.enableParallel is deprecated. " + ...
            "Use cfg.batchProcessing.enableParallel.");

        cfg.batchProcessing.enableParallel = ...
            cfg.enableParallel;

        cfg = rmfield(cfg, "enableParallel");
    end

    if isfield(cfg, "maxWorkers")

        warning( ...
            "ProjectConfig:DeprecatedMaxWorkers", ...
            "cfg.maxWorkers is deprecated. " + ...
            "Use cfg.batchProcessing.maxWorkers.");

        cfg.batchProcessing.maxWorkers = ...
            cfg.maxWorkers;

        cfg = rmfield(cfg, "maxWorkers");
    end
end


function cfg = setDefault(cfg, fieldName, defaultValue)

    if ~isfield(cfg, fieldName)
        cfg.(fieldName) = defaultValue;
    end
end


function validateConfigurationSchema(cfg)

    %% Metadata

    assert(isnumeric(cfg.configSchemaVersion) && ...
        isscalar(cfg.configSchemaVersion) && ...
        isfinite(cfg.configSchemaVersion) && ...
        cfg.configSchemaVersion == 4, ...
        "ProjectConfig:UnsupportedSchemaVersion", ...
        "Expected configSchemaVersion=4.");

    %% Study design

    validateFiniteUniqueVector( ...
        cfg.conditions, ...
        "cfg.conditions");

    assert(isnumeric(cfg.trials) && ...
        isvector(cfg.trials) && ...
        ~isempty(cfg.trials) && ...
        all(isfinite(cfg.trials)) && ...
        all(cfg.trials >= 1) && ...
        all(mod(cfg.trials,1) == 0) && ...
        numel(unique(cfg.trials)) == numel(cfg.trials), ...
        "ProjectConfig:InvalidTrials", ...
        "cfg.trials must be unique positive integers.");

    %% Shared execution

    validateLogicalScalar( ...
        cfg.overwriteExisting, ...
        "cfg.overwriteExisting");

    %% Model validation

    validatePositiveInteger( ...
        cfg.modelValidation.expectedCoordinateCount, ...
        "cfg.modelValidation.expectedCoordinateCount");

    validateNonnegativeInteger( ...
        cfg.modelValidation.expectedConstraintCount, ...
        "cfg.modelValidation.expectedConstraintCount");

    %% Pipeline stage policy

    validateTimeRange( ...
        cfg.pipeline.initializationIk.timeRangeSec, ...
        false, ...
        "cfg.pipeline.initializationIk.timeRangeSec");

    assert(isfield( ...
        cfg.pipeline.initializationIk, ...
        "reviewCoordinates"), ...
        "ProjectConfig:InitializationReviewCoordinatesMissing", ...
        "cfg.pipeline.initializationIk.reviewCoordinates " + ...
        "is required.");

    reviewCoordinates = string( ...
        cfg.pipeline.initializationIk.reviewCoordinates(:));

    assert(~isempty(reviewCoordinates) && ...
        all(strlength(reviewCoordinates) > 0) && ...
        numel(unique(reviewCoordinates)) == ...
        numel(reviewCoordinates), ...
        "ProjectConfig:InvalidInitializationReviewCoordinates", ...
        "initializationIk.reviewCoordinates must contain " + ...
        "unique nonempty coordinate names.");

    validateTimeRange( ...
        cfg.pipeline.modelB.lockWindowSec, ...
        false, ...
        "cfg.pipeline.modelB.lockWindowSec");
        
    assert(isfield( ...
            cfg.pipeline, ...
            "staticOptimization") && ...
        isstruct( ...
            cfg.pipeline.staticOptimization), ...
        "ProjectConfig:StaticOptimizationConfigMissing", ...
        "cfg.pipeline.staticOptimization must be a struct.");

    soCfg = ...
        cfg.pipeline.staticOptimization;

    validateLogicalScalar( ...
        soCfg.requireForceOutput, ...
        "pipeline.staticOptimization.requireForceOutput");

    validateLogicalScalar( ...
        soCfg.requireActivationOutput, ...
        "pipeline.staticOptimization.requireActivationOutput");

    assert(isfield(soCfg, "activationSaturationThreshold"), ...
        "ProjectConfig:ActivationSaturationThresholdMissing", ...
        "pipeline.staticOptimization.activationSaturationThreshold " + ...
        "is required.");

    activationSaturationThreshold = ...
        soCfg.activationSaturationThreshold;

    assert(isnumeric(activationSaturationThreshold) && ...
            isscalar(activationSaturationThreshold) && ...
            isfinite(activationSaturationThreshold) && ...
            activationSaturationThreshold > 0 && ...
            activationSaturationThreshold <= 1, ...
        "ProjectConfig:InvalidActivationSaturationThreshold", ...
        "pipeline.staticOptimization.activationSaturationThreshold " + ...
        "must be greater than zero and no greater than one.");

    validatePositiveScalar( ...
        soCfg.timeToleranceSec, ...
        "pipeline.staticOptimization.timeToleranceSec", ...
        true);

        cutoff = ...
        cfg.pipeline.staticOptimizationPrep. ...
        bodyKinematicsLowpassCutoffHz;

    assert(isnumeric(cutoff) && ...
        isscalar(cutoff) && ...
        isfinite(cutoff), ...
        "ProjectConfig:InvalidBodyKinematicsCutoff", ...
        "bodyKinematicsLowpassCutoffHz must be a finite scalar.");

    validateTimeRange( ...
        cfg.pipeline.staticOptimizationPrep.timeRangeSec, ...
        true, ...
        "cfg.pipeline.staticOptimizationPrep.timeRangeSec");

    %% Lock audit / extraction

    assert(any(strcmpi( ...
        string(cfg.qc.lockAudit.statistic), ...
        ["median","mean"])), ...
        "ProjectConfig:InvalidLockAuditStatistic", ...
        "cfg.qc.lockAudit.statistic must be median or mean.");

    validatePositiveScalar( ...
        cfg.qc.lockAudit.rotationRangeToleranceDeg, ...
        "lockAudit.rotationRangeToleranceDeg", ...
        true);

    validatePositiveScalar( ...
        cfg.qc.lockAudit.translationRangeToleranceM, ...
        "lockAudit.translationRangeToleranceM", ...
        true);

    validatePositiveScalar( ...
        cfg.qc.lockAudit.otherRangeToleranceSI, ...
        "lockAudit.otherRangeToleranceSI", ...
        true);

    validatePositiveScalar( ...
        cfg.qc.lockAudit.rotationMatchToleranceDeg, ...
        "lockAudit.rotationMatchToleranceDeg", ...
        true);

    validatePositiveScalar( ...
        cfg.qc.lockAudit.translationMatchToleranceM, ...
        "lockAudit.translationMatchToleranceM", ...
        true);

    validatePositiveScalar( ...
        cfg.qc.lockAudit.otherMatchToleranceSI, ...
        "lockAudit.otherMatchToleranceSI", ...
        true);

    validatePositiveInteger( ...
        cfg.qc.lockAudit.minimumSamples, ...
        "lockAudit.minimumSamples");

    validateLogicalScalar( ...
        cfg.qc.lockAudit.requirePass, ...
        "lockAudit.requirePass");

    assert(any(strcmpi( ...
        string(cfg.qc.lockExtraction.statistic), ...
        ["median","mean"])), ...
        "ProjectConfig:InvalidLockExtractionStatistic", ...
        "cfg.qc.lockExtraction.statistic must be median or mean.");

    validatePositiveScalar( ...
        cfg.qc.lockExtraction.rotationToleranceDeg, ...
        "lockExtraction.rotationToleranceDeg", ...
        true);

    validatePositiveScalar( ...
        cfg.qc.lockExtraction.translationToleranceM, ...
        "lockExtraction.translationToleranceM", ...
        true);

    validatePositiveScalar( ...
        cfg.qc.lockExtraction.otherToleranceSI, ...
        "lockExtraction.otherToleranceSI", ...
        true);

    validatePositiveInteger( ...
        cfg.qc.lockExtraction.minimumSamples, ...
        "lockExtraction.minimumSamples");

    validateLogicalScalar( ...
        cfg.qc.lockExtraction.requireStable, ...
        "lockExtraction.requireStable");

    %% Lock-extraction filter

    filterCfg = cfg.qc.lockExtractionFilter;

    validateLogicalScalar( ...
        filterCfg.enabled, ...
        "lockExtractionFilter.enabled");

    assert(isstring(filterCfg.assessmentCoordinates) && ...
        ~isempty(filterCfg.assessmentCoordinates), ...
        "ProjectConfig:InvalidAssessmentCoordinates", ...
        "assessmentCoordinates must be a nonempty string array.");

    assert(isstring(filterCfg.filterCoordinates) && ...
        ~isempty(filterCfg.filterCoordinates), ...
        "ProjectConfig:InvalidFilterCoordinates", ...
        "filterCoordinates must be a nonempty string array.");

    assert(all(ismember( ...
        filterCfg.filterCoordinates, ...
        filterCfg.assessmentCoordinates)), ...
        "ProjectConfig:FilterCoordinatesNotAssessed", ...
        "Every filter coordinate must also be an assessment coordinate.");

    assert(isnumeric(filterCfg.candidateCutoffsHz) && ...
        isvector(filterCfg.candidateCutoffsHz) && ...
        ~isempty(filterCfg.candidateCutoffsHz) && ...
        all(isfinite(filterCfg.candidateCutoffsHz)) && ...
        all(filterCfg.candidateCutoffsHz > 0), ...
        "ProjectConfig:InvalidCandidateCutoffs", ...
        "candidateCutoffsHz must contain positive finite values.");

    validatePositiveInteger( ...
        filterCfg.prototypeOrder, ...
        "lockExtractionFilter.prototypeOrder");

    validateTimeRange( ...
        filterCfg.plotWindow, ...
        false, ...
        "lockExtractionFilter.plotWindow");

    validatePositiveScalar( ...
        filterCfg.selectedCutoffHz, ...
        "lockExtractionFilter.selectedCutoffHz", ...
        false);

    %% HSF contact-event detection

    eventCfg = cfg.qc.hsfEventDetection;

    validateTimeRange( ...
        eventCfg.baselineWindow, ...
        true, ...
        "hsfEventDetection.baselineWindow");

    validatePositiveScalar( ...
        eventCfg.liftOffThresholdM, ...
        "hsfEventDetection.liftOffThresholdM", ...
        false);

    validatePositiveScalar( ...
        eventCfg.recontactThresholdM, ...
        "hsfEventDetection.recontactThresholdM", ...
        true);

    assert(eventCfg.recontactThresholdM < ...
        eventCfg.liftOffThresholdM, ...
        "ProjectConfig:InvalidHsfHysteresis", ...
        "Recontact threshold must be lower than lift-off threshold.");

    validatePositiveScalar( ...
        eventCfg.minimumAboveDurationSec, ...
        "hsfEventDetection.minimumAboveDurationSec", ...
        true);

    validatePositiveScalar( ...
        eventCfg.minimumBelowDurationSec, ...
        "hsfEventDetection.minimumBelowDurationSec", ...
        true);

    validatePositiveScalar( ...
        eventCfg.smoothingWindowSec, ...
        "hsfEventDetection.smoothingWindowSec", ...
        true);

    validateTimeRange( ...
        eventCfg.searchWindow, ...
        true, ...
        "hsfEventDetection.searchWindow");

    %% HSF formulation

    validateLogicalScalar( ...
        cfg.hsf.useModelBodyMass, ...
        "cfg.hsf.useModelBodyMass");

    p = cfg.hsf.Parameters;

    requiredHsfFields = [
        "BodyName"
        "SkullMassKg"
        "GravityY"
        "TargetRateHz"
        "RampDuration"
        "RampShape"
        "RadialSign"
        "AzimuthConvention"
        "InterpolationMethod"
        "ForcePrefix"
        "PointPrefix"
    ];

    assert(all(isfield(p, cellstr(requiredHsfFields))), ...
        "ProjectConfig:HsfParameterFieldsMissing", ...
        "cfg.hsf.Parameters is missing required fields.");

    assert(strlength(string(p.BodyName)) > 0, ...
        "ProjectConfig:InvalidHsfBodyName", ...
        "HSF BodyName must be nonempty.");

    validatePositiveScalar( ...
        p.SkullMassKg, ...
        "HSF SkullMassKg", ...
        false);

    assert(isnumeric(p.GravityY) && ...
        isscalar(p.GravityY) && ...
        isfinite(p.GravityY) && ...
        p.GravityY < 0, ...
        "ProjectConfig:InvalidGravity", ...
        "HSF GravityY must be a finite negative scalar.");

    validatePositiveScalar( ...
        p.TargetRateHz, ...
        "HSF TargetRateHz", ...
        false);

    validatePositiveScalar( ...
        p.RampDuration, ...
        "HSF RampDuration", ...
        true);

    assert(string(p.RampShape) == "halfcosine", ...
        "ProjectConfig:UnsupportedRampShape", ...
        "Current HSF workflow requires RampShape='halfcosine'.");

    assert(isnumeric(p.RadialSign) && ...
        isscalar(p.RadialSign) && ...
        isfinite(p.RadialSign) && ...
        abs(p.RadialSign) == 1, ...
        "ProjectConfig:InvalidRadialSign", ...
        "HSF RadialSign must be +1 or -1.");

    assert(string(p.AzimuthConvention) == "x_cos_z_sin", ...
        "ProjectConfig:UnsupportedAzimuthConvention", ...
        "Current HSF workflow requires x_cos_z_sin.");

    assert(strlength(string(p.InterpolationMethod)) > 0 && ...
        strlength(string(p.ForcePrefix)) > 0 && ...
        strlength(string(p.PointPrefix)) > 0, ...
        "ProjectConfig:InvalidHsfTextParameter", ...
        "HSF interpolation/prefix fields must be nonempty.");

    %% Force capacity

    validateLogicalScalar( ...
        cfg.forceCapacity.enabled, ...
        "cfg.forceCapacity.enabled");

    assert(any(strcmpi( ...
        string(cfg.forceCapacity.applyMode), ...
        ["target","scale"])), ...
        "ProjectConfig:InvalidForceCapacityApplyMode", ...
        "forceCapacity.applyMode must be target or scale.");

    validateLogicalScalar( ...
        cfg.forceCapacity.requireAllEntries, ...
        "forceCapacity.requireAllEntries");

    validStages = ["modelA","modelB","modelC"];

    stages = string(cfg.forceCapacity.applyStages);

    assert(~isempty(stages) && ...
        all(ismember(stages, validStages)), ...
        "ProjectConfig:InvalidForceCapacityStages", ...
        "forceCapacity.applyStages contains an unsupported stage.");

    if cfg.forceCapacity.enabled

        assert(strlength(string( ...
            cfg.forceCapacity.configFile)) > 0, ...
            "ProjectConfig:ForceCapacityConfigMissing", ...
            "configFile is required when forceCapacity.enabled=true.");
    end

    %% Analysis

    a = cfg.analysis.staticOptimization;

    assert(isnumeric(a.excludedTrials) && ...
        size(a.excludedTrials,2) == 2, ...
        "ProjectConfig:InvalidExcludedTrials", ...
        "excludedTrials must be N-by-2 [condition trial].");

    breaks = double(a.normalizedBreaksPercent(:).');
    points = double(a.pointsPerPhase(:).');

    assert(numel(breaks) >= 2 && ...
        all(isfinite(breaks)) && ...
        all(diff(breaks) > 0), ...
        "ProjectConfig:InvalidNormalizedBreaks", ...
        "normalizedBreaksPercent must be strictly increasing.");

    assert(numel(points) == numel(breaks)-1 && ...
        all(isfinite(points)) && ...
        all(points >= 1) && ...
        all(mod(points,1) == 0), ...
        "ProjectConfig:InvalidPointsPerPhase", ...
        "pointsPerPhase must contain one positive integer per phase.");

    roi = double(a.statisticsWindowPercent(:).');

    assert(numel(roi) == 2 && ...
        all(isfinite(roi)) && ...
        roi(2) > roi(1) && ...
        roi(1) >= breaks(1) && ...
        roi(2) <= breaks(end), ...
        "ProjectConfig:InvalidStatisticsWindow", ...
        "statisticsWindowPercent must lie inside normalized breaks.");

    assert(strlength(string(a.flexionGroupName)) > 0 && ...
        strlength(string(a.extensionGroupName)) > 0, ...
        "ProjectConfig:InvalidFunctionalGroupName", ...
        "Functional group names must be nonempty.");

    validatePositiveInteger( ...
        a.expectedFlexorCount, ...
        "analysis.expectedFlexorCount");

    validatePositiveInteger( ...
        a.expectedExtensorCount, ...
        "analysis.expectedExtensorCount");

    validatePositiveInteger( ...
        a.topReserveCount, ...
        "analysis.topReserveCount");

    validateFiniteUniqueVector( ...
        a.conditionLegendOrderDeg, ...
        "analysis.conditionLegendOrderDeg");

    assert(all(ismember( ...
        a.conditionLegendOrderDeg, ...
        cfg.conditions)), ...
        "ProjectConfig:LegendConditionMismatch", ...
        "Legend order may only contain configured study conditions.");

    assert(isnumeric(a.yAxisLowerLimit) && ...
        isscalar(a.yAxisLowerLimit) && ...
        isfinite(a.yAxisLowerLimit), ...
        "ProjectConfig:InvalidYAxisLowerLimit", ...
        "yAxisLowerLimit must be finite.");

    validatePositiveScalar( ...
        a.yAxisHeadroomFraction, ...
        "analysis.yAxisHeadroomFraction", ...
        true);

    %% Batch processing

    b = cfg.batchProcessing;

    validateLogicalScalar( ...
        b.enableParallel, ...
        "batchProcessing.enableParallel");

    validatePositiveInteger( ...
        b.maxWorkers, ...
        "batchProcessing.maxWorkers");

    validateLogicalScalar( ...
        b.continueOnError, ...
        "batchProcessing.continueOnError");

    assert(strlength(string(b.poolProfile)) > 0, ...
        "ProjectConfig:InvalidPoolProfile", ...
        "batchProcessing.poolProfile must be nonempty.");

    validateLogicalScalar( ...
        b.closePoolWhenFinished, ...
        "batchProcessing.closePoolWhenFinished");

    %% Reject stale duplicate namespaces

    assert(~isfield(cfg, "enableParallel"), ...
        "ProjectConfig:LegacyEnableParallelPersisted", ...
        "Deprecated cfg.enableParallel persisted after migration.");

    assert(~isfield(cfg, "maxWorkers"), ...
        "ProjectConfig:LegacyMaxWorkersPersisted", ...
        "Deprecated cfg.maxWorkers persisted after migration.");
end


function validateConfigurationPaths(cfg)

    assert(isfolder(cfg.projectRoot), ...
        "ProjectConfig:ProjectRootMissing", ...
        "Project root was not found:\n%s", ...
        cfg.projectRoot);

    requiredDirectories = [
        string(cfg.modelsDirectory)
        string(cfg.inputDirectory)
        string(cfg.templatesDirectory)
        string(cfg.examplesDirectory)
        string(cfg.batchDirectory)
        string(cfg.testsDirectory)
    ];

    for directory = requiredDirectories.'

        assert(isfolder(directory), ...
            "ProjectConfig:RequiredDirectoryMissing", ...
            "Required project directory was not found:\n%s", ...
            directory);
    end

    if ~isfolder(cfg.outputRoot)
        mkdir(cfg.outputRoot);
    end

    if cfg.requireKinematicBaseModel

        assert(isfile(cfg.kinematicBaseModel), ...
            "ProjectConfig:KinematicModelMissing", ...
            "Kinematic base model was not found:\n%s", ...
            cfg.kinematicBaseModel);
    end

    if cfg.requireScalingBaseModel

        assert(isfile(cfg.scalingBaseModel), ...
            "ProjectConfig:ScalingModelMissing", ...
            "Scaling base model was not found:\n%s", ...
            cfg.scalingBaseModel);
    end

    if cfg.requireInitializationIkTemplate

        assert(isfile(cfg.initializationIkTemplate), ...
            "ProjectConfig:IkTemplateMissing", ...
            "Initialization IK template was not found:\n%s", ...
            cfg.initializationIkTemplate);
    end

    if cfg.requireExternalLoadsTemplate

        assert(isfile(cfg.externalLoadsTemplate), ...
            "ProjectConfig:ExternalLoadsTemplateMissing", ...
            "ExternalLoads template was not found:\n%s", ...
            cfg.externalLoadsTemplate);
    end

    if cfg.requireStaticOptimizationTemplate

        assert(isfile(cfg.staticOptimizationTemplate), ...
            "ProjectConfig:StaticOptimizationTemplateMissing", ...
            "Static Optimization template was not found:\n%s", ...
            cfg.staticOptimizationTemplate);
    end

    if strlength(string(cfg.rawDataRoot)) > 0

        assert(isfolder(cfg.rawDataRoot), ...
            "ProjectConfig:RawDataRootMissing", ...
            "Raw-data directory was not found:\n%s", ...
            cfg.rawDataRoot);
    end

    if cfg.forceCapacity.enabled

        assert(isfile(cfg.forceCapacity.configFile), ...
            "ProjectConfig:ForceCapacityConfigNotFound", ...
            "Force-capacity configuration was not found:\n%s", ...
            cfg.forceCapacity.configFile);
    end
end


function validateFiniteUniqueVector(value, label)

    assert(isnumeric(value) && ...
        isvector(value) && ...
        ~isempty(value) && ...
        all(isfinite(value)) && ...
        numel(unique(value)) == numel(value), ...
        "ProjectConfig:InvalidFiniteUniqueVector", ...
        "%s must be a nonempty finite unique numeric vector.", ...
        label);
end


function validatePositiveInteger(value, label)

    assert(isnumeric(value) && ...
        isscalar(value) && ...
        isfinite(value) && ...
        value >= 1 && ...
        mod(value,1) == 0, ...
        "ProjectConfig:InvalidPositiveInteger", ...
        "%s must be a positive integer.", ...
        label);
end


function validateNonnegativeInteger(value, label)

    assert(isnumeric(value) && ...
        isscalar(value) && ...
        isfinite(value) && ...
        value >= 0 && ...
        mod(value,1) == 0, ...
        "ProjectConfig:InvalidNonnegativeInteger", ...
        "%s must be a nonnegative integer.", ...
        label);
end


function validateLogicalScalar(value, label)

    assert(islogical(value) && ...
        isscalar(value), ...
        "ProjectConfig:InvalidLogicalScalar", ...
        "%s must be a logical scalar.", ...
        label);
end


function validatePositiveScalar(value, label, allowZero)

    if allowZero
        valid = isnumeric(value) && ...
            isscalar(value) && ...
            isfinite(value) && ...
            value >= 0;
    else
        valid = isnumeric(value) && ...
            isscalar(value) && ...
            isfinite(value) && ...
            value > 0;
    end

    assert(valid, ...
        "ProjectConfig:InvalidPositiveScalar", ...
        "%s has an invalid scalar value.", ...
        label);
end


function validateTimeRange(value, allowEmpty, label)

    if allowEmpty && isempty(value)
        return;
    end

    assert(isnumeric(value) && ...
        numel(value) == 2 && ...
        all(isfinite(value)) && ...
        value(2) > value(1), ...
        "ProjectConfig:InvalidTimeRange", ...
        "%s must be [start end] with end > start.", ...
        label);
end
