%% run_static_optimization_analysis.m
% Study-level Static Optimization QC and optional pooled analysis wrapper.
%
% USER-FACING FINAL PIPELINE STAGE
%
% This script is intentionally located at the repository root rather than
% under examples/. It discovers completed Static Optimization results from
% projectCfg.outputRoot and operates on the results that actually exist.
%
% Workflow:
%   1. Search recursively for *StaticOptimization_force.sto files.
%   2. Build and write an auditable discovery manifest.
%   3. Generate per-trial QC plots for every complete detected result.
%   4. Prompt the user whether to perform pooled/condition-level analysis
%      on the detected QC-complete result set.
%
% IMPORTANT:
%   Pooled analysis assumes the detected results belong to the same
%   scientific batch/model configuration. The script reports the inferred
%   BatchRoot values and warns before combining results, but folder layout
%   alone cannot prove that all scientific settings were identical.
%
% Per-trial QC outputs:
%   <trial>/04_static_optimization/qc/plots/
%
% Study-level outputs:
%   <outputRoot>/static_optimization_analysis/
%
% The existing event-based normalization and 20-80% statistical ROI are
% retained. Project-wide analysis settings come from:
%
%   projectCfg.analysis.staticOptimization

clear;
clc;
dbstop if error

%% SECTION 0 — PROJECT AND ANALYSIS CONFIGURATION

scriptFile = ...
    string(mfilename("fullpath"));

assert(strlength(scriptFile) > 0, ...
    "SOAnalysis:ScriptLocationUnknown", ...
    "MATLAB could not resolve the running script location.");

projectRoot = ...
    string(fileparts(scriptFile));

assert(isfile(fullfile( ...
        projectRoot, ...
        "load_project_config.m")), ...
    "SOAnalysis:RepositoryRootMismatch", ...
    "run_static_optimization_analysis.m must be stored at the " + ...
    "repository root beside load_project_config.m.");

addpath(projectRoot);

projectCfg = ...
    load_project_config();

assert(isfield(projectCfg, "analysis") && ...
    isfield( ...
        projectCfg.analysis, ...
        "staticOptimization"), ...
    "SOAnalysis:AnalysisConfigMissing", ...
    "projectCfg.analysis.staticOptimization is required.");

analysisCfg = ...
    projectCfg.analysis.staticOptimization;

plotCfg = struct;

plotCfg.excludedTrials = ...
    analysisCfg.excludedTrials;

plotCfg.normalizedBreaks = ...
    analysisCfg.normalizedBreaksPercent;

plotCfg.pointsPerPhase = ...
    analysisCfg.pointsPerPhase;

plotCfg.statisticsWindowPercent = ...
    analysisCfg.statisticsWindowPercent;

plotCfg.flexionGroupName = ...
    analysisCfg.flexionGroupName;

plotCfg.extensionGroupName = ...
    analysisCfg.extensionGroupName;

plotCfg.expectedFlexorCount = ...
    analysisCfg.expectedFlexorCount;

plotCfg.expectedExtensorCount = ...
    analysisCfg.expectedExtensorCount;

plotCfg.topReserveCount = ...
    analysisCfg.topReserveCount;

plotCfg.conditionLegendOrderDeg = ...
    analysisCfg.conditionLegendOrderDeg;

analysisDirectory = ...
    string(fullfile( ...
        projectCfg.outputRoot, ...
        "static_optimization_analysis"));

if ~isfolder(analysisDirectory)
    mkdir(analysisDirectory);
end

%% SECTION 1 — DISCOVER EXISTING STATIC OPTIMIZATION RESULTS

discovery = ...
    pipeline.discoverStaticOptimizationResults( ...
        projectCfg, ...
        "ExcludedTrials", ...
            plotCfg.excludedTrials);

assert(~isempty(discovery), ...
    "SOAnalysis:NoForceResultsFound", ...
    "No Static Optimization force result files were found under:\n%s", ...
    projectCfg.outputRoot);

manifestFile = ...
    string(fullfile( ...
        analysisDirectory, ...
        "detected_static_optimization_results.csv"));

writetable( ...
    discovery, ...
    manifestFile);

fprintf( ...
    "\nDetected %d Static Optimization result location(s).\n", ...
    height(discovery));

fprintf( ...
    "Discovery manifest:\n%s\n", ...
    manifestFile);

disp(discovery(:, [ ...
    "ConditionDeg"
    "TrialNumber"
    "TrialStem"
    "BatchRoot"
    "ForceFileCount"
    "ActivationFileCount"
    "ReadyForQc"
    "ExcludedByConfig"
    "Status"
]));

eligibleMask = ...
    discovery.ReadyForQc & ...
    ~discovery.ExcludedByConfig;

eligible = ...
    discovery(eligibleMask, :);

assert(~isempty(eligible), ...
    "SOAnalysis:NoQcEligibleTrials", ...
    "Force results were detected, but none have the complete companion " + ...
    "artifacts required for per-trial QC.");

incomplete = ...
    discovery(~discovery.ReadyForQc, :);

if ~isempty(incomplete)

    warning( ...
        "SOAnalysis:IncompleteDetectedResults", ...
        "%d detected result location(s) are incomplete or ambiguous " + ...
        "and will not be processed. Review the discovery manifest.", ...
        height(incomplete));
end

if any(discovery.ExcludedByConfig)

    fprintf( ...
        "%d detected trial(s) are excluded by the configured " + ...
        "analysis exclusion list.\n", ...
        nnz(discovery.ExcludedByConfig));
end

%% SECTION 2 — GENERATE PER-TRIAL QC FOR ALL ELIGIBLE RESULTS

allNormalized = table;
allStatsWindowNormalized = table;
allMetrics = table;
allReserveAudit = table;
allMuscleAudit = table;

processedTrials = strings(0,1);
processedBatchRoots = strings(0,1);

for iTrial = 1:height(eligible)

    conditionDeg = ...
        eligible.ConditionDeg(iTrial);

    trialNumber = ...
        eligible.TrialNumber(iTrial);

    trialName = ...
        eligible.TrialStem(iTrial);

    trialRoot = ...
        eligible.TrialRoot(iTrial);

    resultsDirectory = ...
        eligible.ResultsDirectory(iTrial);

    qcDirectory = ...
        eligible.QcDirectory(iTrial);

    plotDirectory = ...
        eligible.PlotDirectory(iTrial);

    modelFile = ...
        eligible.ModelFile(iTrial);

    eventSummaryFile = ...
        eligible.EventSummaryFile(iTrial);

    forceFile = ...
        eligible.ForceFile(iTrial);

    activationFile = ...
        eligible.ActivationFile(iTrial);

    if ~isfolder(qcDirectory)
        mkdir(qcDirectory);
    end

    if ~isfolder(plotDirectory)
        mkdir(plotDirectory);
    end

%% Load detected contact events

eventSummary = readtable(eventSummaryFile);

requiredEventColumns = [ ...
    "LiftOffTime"
    "RecontactTime"
];

assert(all(ismember( ...
    requiredEventColumns, ...
    string(eventSummary.Properties.VariableNames))), ...
    "SOPlotting:EventColumnsMissing", ...
    "Event summary for %s must contain " + ...
    "LiftOffTime and RecontactTime.", ...
    trialName);

assert(height(eventSummary) == 1, ...
    "SOPlotting:UnexpectedEventRows", ...
    "Expected one event-summary row for %s.", ...
    trialName);

eventTimes = [ ...
    eventSummary.LiftOffTime, ...
    eventSummary.RecontactTime];

fprintf("\nAnalyzing %s\n", trialName);

%% Read SO outputs

forceSto = opensimio.readSto(forceFile);
activationSto = opensimio.readSto(activationFile);

forceLabels = reshape( ...
    string(forceSto.Labels), 1, []);

activationLabels = reshape( ...
    string(activationSto.Labels), 1, []);

forceTimeColumn = ...
    localFindTimeColumn(forceLabels);

activationTimeColumn = ...
    localFindTimeColumn(activationLabels);

forceTime = ...
    forceSto.Data(:, forceTimeColumn);

activationTime = ...
    activationSto.Data(:, activationTimeColumn);

assert(all(diff(forceTime) > 0), ...
    "SOPlotting:NonmonotonicForceTime", ...
    "Force time is not strictly increasing for %s.", ...
    trialName);

assert(all(diff(activationTime) > 0), ...
    "SOPlotting:NonmonotonicActivationTime", ...
    "Activation time is not strictly increasing for %s.", ...
    trialName);

rawForceBreaks = [ ...
    forceTime(1), ...
    eventTimes(1), ...
    eventTimes(2), ...
    forceTime(end)];

rawActivationBreaks = [ ...
    activationTime(1), ...
    eventTimes(1), ...
    eventTimes(2), ...
    activationTime(end)];

localValidateBreaks( ...
    rawForceBreaks, trialName);

localValidateBreaks( ...
    rawActivationBreaks, trialName);

%% Read model muscle names

import org.opensim.modeling.*

model = Model(char(modelFile));
model.finalizeConnections();

muscleSet = model.getMuscles();
numMuscles = muscleSet.getSize();

modelMuscleNames = strings(numMuscles,1);

for iMuscle = 0:(numMuscles-1)
    modelMuscleNames(iMuscle+1) = ...
        string(char( ...
            muscleSet.get(iMuscle).getName()));
end

%% Verify SO muscle columns against Model C

missingForceMuscles = setdiff( ...
    modelMuscleNames, ...
    forceLabels, ...
    "stable");

missingActivationMuscles = setdiff( ...
    modelMuscleNames, ...
    activationLabels, ...
    "stable");

assert(isempty(missingForceMuscles), ...
    "SOPlotting:MissingForceMuscles", ...
    "Force STO is missing model muscles for %s: %s", ...
    trialName, ...
    strjoin(missingForceMuscles, ", "));

assert(isempty(missingActivationMuscles), ...
    "SOPlotting:MissingActivationMuscles", ...
    "Activation STO is missing model muscles for %s: %s", ...
    trialName, ...
    strjoin(missingActivationMuscles, ", "));

%% Resolve authoritative flexion / extension ObjectGroups

flexionGroup = ...
    modelprep.getBilateralMuscleGroupMembers( ...
        modelFile, ...
        plotCfg.flexionGroupName, ...
        "RequireBilateral", ...
            true, ...
        "ExpectedResolvedCount", ...
            plotCfg.expectedFlexorCount);

extensionGroup = ...
    modelprep.getBilateralMuscleGroupMembers( ...
        modelFile, ...
        plotCfg.extensionGroupName, ...
        "RequireBilateral", ...
            true, ...
        "ExpectedResolvedCount", ...
            plotCfg.expectedExtensorCount);

flexorNames = ...
    flexionGroup.ResolvedMembers;

extensorNames = ...
    extensionGroup.ResolvedMembers;

overlapMuscles = intersect( ...
    flexorNames, ...
    extensorNames, ...
    "stable");

assert(isempty(overlapMuscles), ...
    "SOPlotting:FunctionalGroupOverlap", ...
    "One or more muscles occur in both flexion and extension " + ...
    "ObjectGroups for %s: %s", ...
    trialName, ...
    strjoin(overlapMuscles, ", "));

excludedMuscleNames = setdiff( ...
    modelMuscleNames, ...
    [flexorNames; extensorNames], ...
    "stable");

fprintf("  Flexion group:  %d muscles\n", ...
    numel(flexorNames));

fprintf("  Extension group: %d muscles\n", ...
    numel(extensorNames));

fprintf("  Excluded/other:  %d muscles\n", ...
    numel(excludedMuscleNames));

% Only explicit flexion/extension group members contribute to these
% sums. Hyoid-associated muscles, digastrics, and other unrelated
% muscles remain model muscles but are excluded from both groups.
flexorColumns = ...
    localFindColumns( ...
        forceLabels, ...
        flexorNames);

extensorColumns = ...
    localFindColumns( ...
        forceLabels, ...
        extensorNames);

flexorForce = sum( ...
    forceSto.Data(:, flexorColumns), ...
    2, ...
    "omitnan");

extensorForce = sum( ...
    forceSto.Data(:, extensorColumns), ...
    2, ...
    "omitnan");

netForce = ...
    flexorForce - extensorForce;

%% Identify non-muscle / reserve activation columns

activationNonTimeMask = ...
    true(size(activationLabels));

activationNonTimeMask( ...
    activationTimeColumn) = false;

reserveMask = ...
    activationNonTimeMask & ...
    ~ismember( ...
        activationLabels, ...
        modelMuscleNames);

reserveLabels = ...
    activationLabels(reserveMask);

reserveData = ...
    activationSto.Data(:, reserveMask);

assert(~isempty(reserveLabels), ...
    "SOPlotting:NoReserveActivations", ...
    "No non-muscle activation columns were found for %s. " + ...
    "Inspect the activation STO labels.", ...
    trialName);

maxAbsReserveByTime = ...
    max(abs(reserveData), [], 2);

rmsReserveByTime = ...
    sqrt(mean( ...
        reserveData.^2, ...
        2, ...
        "omitnan"));

peakAbsByReserve = ...
    max(abs(reserveData), [], 1);

[sortedPeakReserve, reserveOrder] = ...
    sort(peakAbsByReserve, "descend");

sortedReserveLabels = ...
    reserveLabels(reserveOrder);

reserveAudit = table( ...
    repmat(trialName, numel(reserveLabels),1), ...
    repmat(conditionDeg, numel(reserveLabels),1), ...
    repmat(trialNumber, numel(reserveLabels),1), ...
    sortedReserveLabels(:), ...
    sortedPeakReserve(:), ...
    'VariableNames', { ...
        'trial', ...
        'condition_deg', ...
        'trial_num', ...
        'reserve_label', ...
        'peak_absolute_activation'});

allReserveAudit = [ ...
    allReserveAudit
    reserveAudit]; %#ok<AGROW>

%% Muscle-group audit table

muscleGroupLabels = ...
    repmat("Excluded/other", numMuscles,1);

muscleGroupLabels( ...
    ismember(modelMuscleNames, flexorNames)) = ...
    "Flexor";

muscleGroupLabels( ...
    ismember(modelMuscleNames, extensorNames)) = ...
    "Extensor";

muscleAudit = table( ...
    repmat(trialName, numMuscles,1), ...
    repmat(conditionDeg, numMuscles,1), ...
    modelMuscleNames, ...
    muscleGroupLabels, ...
    'VariableNames', { ...
        'trial', ...
        'condition_deg', ...
        'muscle_name', ...
        'group'});

allMuscleAudit = [ ...
    allMuscleAudit
    muscleAudit]; %#ok<AGROW>

% Per-trial source-to-bilateral expansion audit. This makes it
% explicit which left-side muscle was inferred from each group
% member stored in the .osim file.
groupExpansionAudit = [ ...
    addvars( ...
        flexionGroup.Audit, ...
        repmat("Flexor", ...
            height(flexionGroup.Audit),1), ...
        'Before', 1, ...
        'NewVariableNames', "FunctionalGroup")
    addvars( ...
        extensionGroup.Audit, ...
        repmat("Extensor", ...
            height(extensionGroup.Audit),1), ...
        'Before', 1, ...
        'NewVariableNames', "FunctionalGroup")
];

writetable( ...
    groupExpansionAudit, ...
    fullfile( ...
        qcDirectory, ...
        "muscle_group_bilateral_expansion_audit.csv"));

%% Piecewise time normalization

normPercent = ...
    localMakePiecewisePercentGrid( ...
        plotCfg.normalizedBreaks, ...
        plotCfg.pointsPerPhase);

flexorNorm = ...
    localPiecewiseTimeNormalize( ...
        forceTime, ...
        flexorForce, ...
        rawForceBreaks, ...
        plotCfg.normalizedBreaks, ...
        normPercent);

extensorNorm = ...
    localPiecewiseTimeNormalize( ...
        forceTime, ...
        extensorForce, ...
        rawForceBreaks, ...
        plotCfg.normalizedBreaks, ...
        normPercent);

maxReserveNorm = ...
    localPiecewiseTimeNormalize( ...
        activationTime, ...
        maxAbsReserveByTime, ...
        rawActivationBreaks, ...
        plotCfg.normalizedBreaks, ...
        normPercent);

rmsReserveNorm = ...
    localPiecewiseTimeNormalize( ...
        activationTime, ...
        rmsReserveByTime, ...
        rawActivationBreaks, ...
        plotCfg.normalizedBreaks, ...
        normPercent);

normalizedTrial = table;
normalizedTrial.trial = ...
    repmat(trialName, numel(normPercent),1);
normalizedTrial.condition_deg = ...
    repmat(conditionDeg, numel(normPercent),1);
normalizedTrial.trial_num = ...
    repmat(trialNumber, numel(normPercent),1);
normalizedTrial.norm_percent = ...
    normPercent(:);

normalizedTrial.flexor_force_N = ...
    flexorNorm(:);

normalizedTrial.extensor_force_N = ...
    extensorNorm(:);

normalizedTrial.net_flexor_minus_extensor_N = ...
    flexorNorm(:) - extensorNorm(:);

normalizedTrial.max_abs_reserve_activation = ...
    maxReserveNorm(:);

normalizedTrial.rms_reserve_activation = ...
    rmsReserveNorm(:);

allNormalized = [ ...
    allNormalized
    normalizedTrial]; %#ok<AGROW>

%% Statistical ROI and trial metrics
%
% The complete normalized waveform remains in allNormalized for
% plotting/QC. Statistical reporting uses ONLY the configured
% normalized ROI (default 20-80%), corresponding to lift-off
% through re-contact.

np = normalizedTrial.norm_percent;

statsStartPercent = ...
    plotCfg.statisticsWindowPercent(1);

statsEndPercent = ...
    plotCfg.statisticsWindowPercent(2);

assert( ...
    statsStartPercent >= min(plotCfg.normalizedBreaks) && ...
    statsEndPercent <= max(plotCfg.normalizedBreaks) && ...
    statsEndPercent > statsStartPercent, ...
    "SOPlotting:InvalidStatisticsWindow", ...
    "Statistics window must be ordered and inside normalized range.");

idxStats = ...
    np >= statsStartPercent & ...
    np <= statsEndPercent;

assert(any(idxStats), ...
    "SOPlotting:EmptyStatisticsWindow", ...
    "Statistics ROI contains no normalized samples for %s.", ...
    trialName);

statsWindowTrial = ...
    normalizedTrial(idxStats, :);

allStatsWindowNormalized = [ ...
    allStatsWindowNormalized
    statsWindowTrial]; %#ok<AGROW>

metrics = table;
metrics.trial = trialName;
metrics.condition_deg = conditionDeg;
metrics.trial_num = trialNumber;

metrics.statistics_window_start_percent = ...
    statsStartPercent;

metrics.statistics_window_end_percent = ...
    statsEndPercent;

metrics.lift_off_time_s = ...
    eventTimes(1);

metrics.recontact_time_s = ...
    eventTimes(2);

metrics.off_support_duration_s = ...
    eventTimes(2) - eventTimes(1);

% -------------------------------------------------------------
% Muscle-force metrics: STATISTICS ROI ONLY
% -------------------------------------------------------------

[metrics.peak_flexor_N, peakFlexorIndex] = ...
    max( ...
        normalizedTrial.flexor_force_N(idxStats), ...
        [], ...
        "omitnan");

[metrics.peak_extensor_N, peakExtensorIndex] = ...
    max( ...
        normalizedTrial.extensor_force_N(idxStats), ...
        [], ...
        "omitnan");

statsNormPercent = ...
    normalizedTrial.norm_percent(idxStats);

metrics.peak_flexor_norm_percent = ...
    statsNormPercent(peakFlexorIndex);

metrics.peak_extensor_norm_percent = ...
    statsNormPercent(peakExtensorIndex);

metrics.mean_flexor_N = ...
    mean( ...
        normalizedTrial.flexor_force_N(idxStats), ...
        "omitnan");

metrics.mean_extensor_N = ...
    mean( ...
        normalizedTrial.extensor_force_N(idxStats), ...
        "omitnan");

metrics.mean_net_flexor_minus_extensor_N = ...
    mean( ...
        normalizedTrial. ...
        net_flexor_minus_extensor_N(idxStats), ...
        "omitnan");

metrics.peak_net_flexor_minus_extensor_N = ...
    max( ...
        normalizedTrial. ...
        net_flexor_minus_extensor_N(idxStats), ...
        [], ...
        "omitnan");

% -------------------------------------------------------------
% Reserve metrics: STATISTICS ROI ONLY
% -------------------------------------------------------------

metrics.peak_abs_reserve_activation = ...
    max( ...
        normalizedTrial. ...
        max_abs_reserve_activation(idxStats), ...
        [], ...
        "omitnan");

metrics.mean_max_abs_reserve_activation = ...
    mean( ...
        normalizedTrial. ...
        max_abs_reserve_activation(idxStats), ...
        "omitnan");

metrics.mean_rms_reserve_activation = ...
    mean( ...
        normalizedTrial. ...
        rms_reserve_activation(idxStats), ...
        "omitnan");

allMetrics = [ ...
    allMetrics
    metrics]; %#ok<AGROW>

%% Per-trial plot A — raw summed muscle forces

rawForceFile = string(fullfile( ...
    plotDirectory, ...
    "raw_force_diagnostics.png"));

localPlotRawForces( ...
    forceTime, ...
    flexorForce, ...
    extensorForce, ...
    netForce, ...
    rawForceBreaks, ...
    trialName, ...
    rawForceFile);

%% Per-trial plot B — reserve actuator activations

reservePlotFile = string(fullfile( ...
    plotDirectory, ...
    "reserve_activation_diagnostics.png"));

localPlotReserveActivations( ...
    activationTime, ...
    reserveData, ...
    reserveLabels, ...
    sortedReserveLabels, ...
    rawActivationBreaks, ...
    trialName, ...
    plotCfg.topReserveCount, ...
    metrics.peak_abs_reserve_activation, ...
    reservePlotFile);

%% Per-trial plot C — normalized forces

normalizedPlotFile = string(fullfile( ...
    plotDirectory, ...
    "normalized_force_diagnostics.png"));

localPlotNormalizedTrial( ...
    normalizedTrial, ...
    trialName, ...
    normalizedPlotFile);

fprintf("  Peak flexor force (%.0f-%.0f%% ROI): %.3f N\n", ...
    plotCfg.statisticsWindowPercent(1), ...
    plotCfg.statisticsWindowPercent(2), ...
    metrics.peak_flexor_N);

fprintf("  Peak extensor force (%.0f-%.0f%% ROI): %.3f N\n", ...
    plotCfg.statisticsWindowPercent(1), ...
    plotCfg.statisticsWindowPercent(2), ...
    metrics.peak_extensor_N);

fprintf("  Peak |reserve activation| (%.0f-%.0f%% ROI): %.6f\n", ...
    plotCfg.statisticsWindowPercent(1), ...
    plotCfg.statisticsWindowPercent(2), ...
    metrics.peak_abs_reserve_activation);

processedTrials(end+1,1) = trialName; %#ok<SAGROW>

    processedBatchRoots(end+1,1) = ...
        eligible.BatchRoot(iTrial); %#ok<SAGROW>
end

%% SECTION 3 — REQUIRE AT LEAST ONE QC-COMPLETE TRIAL

assert(~isempty(allNormalized), ...
    "SOAnalysis:NoTrialsProcessed", ...
    "No detected Static Optimization trials completed per-trial QC.");

fprintf( ...
    "\nPer-trial QC completed for %d trial(s):\n", ...
    numel(processedTrials));

disp(processedTrials);

uniqueBatchRoots = ...
    unique( ...
        processedBatchRoots, ...
        "stable");

fprintf( ...
    "\nDetected source batch root(s):\n");

disp(uniqueBatchRoots);

%% SECTION 4 — OPTIONAL POOLED / CONDITION-LEVEL ANALYSIS

fprintf( ...
    "\nOPTIONAL POOLED STATIC OPTIMIZATION ANALYSIS\n");

fprintf( ...
    "Per-trial QC plots have already been generated for all detected " + ...
    "eligible trials.\n");

fprintf( ...
    "\nWARNING:\n" + ...
    "Pooled statistics and condition-level plots assume that all detected " + ...
    "results belong to the same scientific batch and were generated with " + ...
    "compatible model, force-capacity, and analysis settings.\n");

if numel(uniqueBatchRoots) > 1

    warning( ...
        "SOAnalysis:MultipleBatchRootsDetected", ...
        "Detected QC-complete results span %d different BatchRoot values. " + ...
        "Review the manifest carefully before pooling these results.", ...
        numel(uniqueBatchRoots));
end

fprintf( ...
    "\n  [1] Perform pooled/condition-level analysis on these %d trial(s)\n", ...
    numel(processedTrials));

fprintf( ...
    "  [2] Finish after per-trial QC only\n");

analysisChoice = ...
    localPromptForChoice( ...
        "Selection [1/2]: ", ...
        ["1","2"]);

if analysisChoice == "2"

    fprintf( ...
        "\nPer-trial Static Optimization QC complete. " + ...
        "Pooled analysis was not requested.\n");

    return;
end

if numel(uniqueBatchRoots) > 1

    fprintf( ...
        "\nMULTIPLE BATCH ROOTS WERE DETECTED.\n");

    fprintf( ...
        "  [1] I have reviewed the manifest and want to continue anyway\n");

    fprintf( ...
        "  [2] Cancel pooled analysis\n");

    mixedBatchChoice = ...
        localPromptForChoice( ...
            "Selection [1/2]: ", ...
            ["1","2"]);

    if mixedBatchChoice == "2"

        fprintf( ...
            "\nPooled analysis cancelled. Per-trial QC outputs remain available.\n");

        return;
    end
end

%% SECTION 5 — WRITE COMBINED ANALYSIS TABLES

normalizedFile = ...
    string(fullfile( ...
        analysisDirectory, ...
        "all_trials_time_normalized_so.csv"));

statsWindowNormalizedFile = ...
    string(fullfile( ...
        analysisDirectory, ...
        "all_trials_stats_window_so.csv"));

metricsFile = ...
    string(fullfile( ...
        analysisDirectory, ...
        "all_trials_so_metrics.csv"));

reserveAuditFile = ...
    string(fullfile( ...
        analysisDirectory, ...
        "all_trials_reserve_audit.csv"));

muscleAuditFile = ...
    string(fullfile( ...
        analysisDirectory, ...
        "muscle_group_audit.csv"));

writetable( ...
    allNormalized, ...
    normalizedFile);

writetable( ...
    allStatsWindowNormalized, ...
    statsWindowNormalizedFile);

writetable( ...
    allMetrics, ...
    metricsFile);

writetable( ...
    allReserveAudit, ...
    reserveAuditFile);

writetable( ...
    allMuscleAudit, ...
    muscleAuditFile);

fprintf( ...
    "\nWrote full normalized waveform table:\n%s\n", ...
    normalizedFile);

fprintf( ...
    "Wrote statistics-window normalized table (%.0f-%.0f%%):\n%s\n", ...
    plotCfg.statisticsWindowPercent(1), ...
    plotCfg.statisticsWindowPercent(2), ...
    statsWindowNormalizedFile);

fprintf( ...
    "%s\n", ...
    metricsFile);

fprintf( ...
    "%s\n", ...
    reserveAuditFile);

fprintf( ...
    "%s\n", ...
    muscleAuditFile);

%% SECTION 6 — CONDITION-LEVEL SUMMARY STATISTICS

% Every variable summarized here was calculated exclusively from the
% configured statistical ROI. Support-phase values do not contribute.

summaryVariables = [
    "peak_flexor_N"
    "peak_extensor_N"
    "mean_flexor_N"
    "mean_extensor_N"
    "mean_net_flexor_minus_extensor_N"
    "peak_net_flexor_minus_extensor_N"
    "peak_abs_reserve_activation"
    "mean_max_abs_reserve_activation"
    "mean_rms_reserve_activation"
];

conditionSummary = ...
    groupsummary( ...
        allMetrics, ...
        "condition_deg", ...
        ["mean","std"], ...
        summaryVariables);

conditionSummaryFile = ...
    string(fullfile( ...
        analysisDirectory, ...
        "so_metrics_by_condition.csv"));

writetable( ...
    conditionSummary, ...
    conditionSummaryFile);

disp(conditionSummary);

%% SECTION 7 — CONDITION MEAN +/- SD PLOTS

localPlotConditionBands( ...
    allNormalized, ...
    "flexor_force_N", ...
    "Flexor force (N)", ...
    "Summed flexor force", ...
    fullfile( ...
        analysisDirectory, ...
        "flexor_force_time_normalized.png"), ...
    plotCfg.conditionLegendOrderDeg);

localPlotConditionBands( ...
    allNormalized, ...
    "extensor_force_N", ...
    "Extensor force (N)", ...
    "Summed extensor force", ...
    fullfile( ...
        analysisDirectory, ...
        "extensor_force_time_normalized.png"), ...
    plotCfg.conditionLegendOrderDeg);

localPlotConditionBands( ...
    allNormalized, ...
    "max_abs_reserve_activation", ...
    "Maximum absolute reserve activation", ...
    "Reserve actuator demand", ...
    fullfile( ...
        analysisDirectory, ...
        "reserve_activation_time_normalized.png"), ...
    plotCfg.conditionLegendOrderDeg);

fprintf( ...
    "\nStatic Optimization pooled analysis complete.\n");

%% LOCAL FUNCTIONS
%% ========================================================================


function choice = localPromptForChoice(promptText, validChoices)
%LOCALPROMPTFORCHOICE Wait for a valid command-line selection.

    validChoices = ...
        string(validChoices(:));

    while true

        rawChoice = ...
            input( ...
                char(promptText), ...
                "s");

        choice = ...
            strtrim(string(rawChoice));

        if any(choice == validChoices)
            return;
        end

        fprintf( ...
            "Invalid selection. Enter one of: %s\n", ...
            strjoin(validChoices, ", "));
    end
end



function index = localFindTimeColumn(labels)

    index = find(strcmpi(labels, "time"));

    assert(numel(index) == 1, ...
        "SOPlotting:TimeLookupFailed", ...
        "Could not uniquely identify the time column.");
end


function columns = localFindColumns(labels, requestedNames)

    columns = zeros(numel(requestedNames),1);

    for iName = 1:numel(requestedNames)

        match = find( ...
            labels == requestedNames(iName));

        assert(numel(match) == 1, ...
            "SOPlotting:ColumnLookupFailed", ...
            "Could not uniquely locate '%s'.", ...
            requestedNames(iName));

        columns(iName) = match;
    end
end


function localValidateBreaks(breaks, trialName)

    assert(all(isfinite(breaks)), ...
        "SOPlotting:NonfiniteEvents", ...
        "Nonfinite event time found for %s.", ...
        trialName);

    assert(all(diff(breaks) > 0), ...
        "SOPlotting:InvalidEventOrder", ...
        "Event times are not strictly increasing for %s.", ...
        trialName);
end


function grid = localMakePiecewisePercentGrid( ...
        normBreaks, pointsPerPhase)

    assert(numel(pointsPerPhase) == ...
        numel(normBreaks)-1, ...
        "SOPlotting:NormalizationDefinitionMismatch", ...
        "pointsPerPhase must have one fewer element " + ...
        "than normBreaks.");

    grid = [];

    for iPhase = 1:numel(pointsPerPhase)

        thisGrid = linspace( ...
            normBreaks(iPhase), ...
            normBreaks(iPhase+1), ...
            pointsPerPhase(iPhase)+1);

        if iPhase > 1
            thisGrid = thisGrid(2:end);
        end

        grid = [grid, thisGrid]; %#ok<AGROW>
    end

    grid = grid(:);
end


function yNorm = localPiecewiseTimeNormalize( ...
        time, y, rawBreaks, normBreaks, normPercent)

    yNorm = nan(size(normPercent));

    for iPhase = 1:(numel(rawBreaks)-1)

        rawStart = rawBreaks(iPhase);
        rawEnd = rawBreaks(iPhase+1);

        normStart = normBreaks(iPhase);
        normEnd = normBreaks(iPhase+1);

        idxNorm = ...
            normPercent >= normStart & ...
            normPercent <= normEnd;

        if iPhase > 1
            idxNorm = ...
                normPercent > normStart & ...
                normPercent <= normEnd;
        end

        phaseFraction = ...
            (normPercent(idxNorm) - normStart) ./ ...
            (normEnd - normStart);

        queryTime = ...
            rawStart + ...
            phaseFraction .* ...
            (rawEnd - rawStart);

        yNorm(idxNorm) = interp1( ...
            time, ...
            y, ...
            queryTime, ...
            "linear");
    end
end


function localPlotRawForces( ...
        time, flexorForce, extensorForce, netForce, ...
        breaks, trialName, outFile)

    fig = figure( ...
        "Color", "w", ...
        "Name", trialName + " raw SO forces");

    ax = axes(fig);
    hold(ax, "on");

    hFlex = plot(ax, ...
        time, flexorForce, ...
        "LineWidth", 1.8, ...
        "DisplayName", "Flexors");

    hExt = plot(ax, ...
        time, extensorForce, ...
        "LineWidth", 1.8, ...
        "DisplayName", "Extensors");

    hNet = plot(ax, ...
        time, netForce, ...
        "LineWidth", 1.2, ...
        "LineStyle", "--", ...
        "DisplayName", "Flexor - extensor");

    localAddRawPhasePatches(ax, breaks);

    uistack([hFlex hExt hNet], "top");

    xline(ax, breaks(2), "--", ...
        "Lift-off", ...
        "HandleVisibility", "off");

    xline(ax, breaks(3), "--", ...
        "Re-contact", ...
        "HandleVisibility", "off");

    xlabel(ax, "Time (s)");
    ylabel(ax, "Summed muscle force (N)");

    title(ax, ...
        trialName + " — Static Optimization forces", ...
        "Interpreter", "none");

    legend(ax, "Location", "best");
    grid(ax, "on");
    box(ax, "on");

    ylim(ax, [ ...
        0, ...
        localUpperYLimit([ ...
            flexorForce(:); ...
            extensorForce(:); ...
            netForce(:)])]);

    exportgraphics(fig, outFile, ...
        "Resolution", 300);

    close(fig);
end


function localPlotReserveActivations( ...
        time, reserveData, reserveLabels, ...
        sortedReserveLabels, breaks, ...
        trialName, topCount, peakAbsoluteActivation, outFile)

    topCount = min( ...
        topCount, ...
        numel(sortedReserveLabels));

    topLabels = ...
        sortedReserveLabels(1:topCount);

    columns = zeros(topCount,1);

    for iLabel = 1:topCount

        match = find( ...
            reserveLabels == topLabels(iLabel));

        assert(numel(match) == 1, ...
            "SOPlotting:ReserveLookupFailed", ...
            "Could not locate reserve '%s'.", ...
            topLabels(iLabel));

        columns(iLabel) = match;
    end

    fig = figure( ...
        "Color", "w", ...
        "Name", trialName + " reserve activations");

    ax = axes(fig);
    hold(ax, "on");

    lineHandles = gobjects(topCount,1);

    for iColumn = 1:topCount

        lineHandles(iColumn) = plot(ax, ...
            time, ...
            reserveData(:, columns(iColumn)), ...
            "LineWidth", 1.1, ...
            "DisplayName", topLabels(iColumn));
    end

    localAddRawPhasePatches(ax, breaks);

    uistack(lineHandles, "top");

    xline(ax, breaks(2), "--", ...
        "Lift-off", ...
        "HandleVisibility", "off");

    xline(ax, breaks(3), "--", ...
        "Re-contact", ...
        "HandleVisibility", "off");

    yline(ax, 0, ":", ...
        "HandleVisibility", "off");

    xlabel(ax, "Time (s)");
    ylabel(ax, "Activation");

    title(ax, ...
        sprintf( ...
            "%s — top reserve actuators | peak |a| = %.5f", ...
            trialName, ...
            peakAbsoluteActivation), ...
        "Interpreter", "none");

    legend(ax, ...
        "Location", "eastoutside", ...
        "Interpreter", "none");

    grid(ax, "on");
    box(ax, "on");

    ylim(ax, [ ...
        0, ...
        localUpperYLimit( ...
            reserveData(:, columns))]);

    exportgraphics(fig, outFile, ...
        "Resolution", 300);

    close(fig);
end


function localPlotNormalizedTrial( ...
        normalizedTrial, trialName, outFile)

    fig = figure( ...
        "Color", "w", ...
        "Name", trialName + " normalized SO forces");

    ax = axes(fig);
    hold(ax, "on");

    hFlex = plot(ax, ...
        normalizedTrial.norm_percent, ...
        normalizedTrial.flexor_force_N, ...
        "LineWidth", 1.8, ...
        "DisplayName", "Flexors");

    hExt = plot(ax, ...
        normalizedTrial.norm_percent, ...
        normalizedTrial.extensor_force_N, ...
        "LineWidth", 1.8, ...
        "DisplayName", "Extensors");

    hNet = plot(ax, ...
        normalizedTrial.norm_percent, ...
        normalizedTrial.net_flexor_minus_extensor_N, ...
        "LineWidth", 1.2, ...
        "LineStyle", "--", ...
        "DisplayName", "Flexor - extensor");

    localAddNormalizedPhasePatches(ax);

    uistack([hFlex hExt hNet], "top");

    xline(ax, 20, "--", ...
        "Lift-off", ...
        "HandleVisibility", "off");

    xline(ax, 80, "--", ...
        "Re-contact", ...
        "HandleVisibility", "off");

    xlabel(ax, "Normalized task time (%)");
    ylabel(ax, "Summed muscle force (N)");

    title(ax, ...
        trialName + " — event-normalized SO forces", ...
        "Interpreter", "none");

    legend(ax, "Location", "best");
    grid(ax, "on");
    box(ax, "on");

    ylim(ax, [ ...
        0, ...
        localUpperYLimit([ ...
            normalizedTrial.flexor_force_N(:); ...
            normalizedTrial.extensor_force_N(:); ...
            normalizedTrial.net_flexor_minus_extensor_N(:)])]);

    exportgraphics(fig, outFile, ...
        "Resolution", 300);

    close(fig);
end


function localPlotConditionBands( ...
        T, valueVariable, yLabelText, ...
        figureTitle, outFile, legendConditionOrder)

    if nargin < 6
        legendConditionOrder = [];
    end

    conditions = unique(T.condition_deg);
    conditions = conditions(isfinite(conditions));

    fig = figure( ...
        "Color", "w", ...
        "Name", figureTitle);

    ax = axes(fig);
    hold(ax, "on");

    allLineHandles = gobjects(numel(conditions),1);
    maxPlottedValue = 0;

    for iCondition = 1:numel(conditions)

        conditionDeg = ...
            conditions(iCondition);

        thisT = T( ...
            T.condition_deg == conditionDeg, ...
            :);

        [groupIndex, normValues] = ...
            findgroups(thisT.norm_percent);

        meanValue = splitapply( ...
            @(x) mean(x, "omitnan"), ...
            thisT.(valueVariable), ...
            groupIndex);

        sdValue = splitapply( ...
            @(x) std(x, "omitnan"), ...
            thisT.(valueVariable), ...
            groupIndex);

        upperBand = meanValue + sdValue;
        finiteUpperBand = upperBand(isfinite(upperBand));

        if ~isempty(finiteUpperBand)
            maxPlottedValue = max( ...
                maxPlottedValue, ...
                max(finiteUpperBand));
        end

        allLineHandles(iCondition) = plot(ax, ...
            normValues, ...
            meanValue, ...
            "LineWidth", 2, ...
            "DisplayName", ...
            sprintf("%g°", conditionDeg));

        lineColor = ...
            allLineHandles(iCondition).Color;

        fill(ax, ...
            [normValues; flipud(normValues)], ...
            [ ...
                meanValue - sdValue
                flipud(meanValue + sdValue)
            ], ...
            lineColor, ...
            "FaceAlpha", 0.18, ...
            "EdgeColor", "none", ...
            "HandleVisibility", "off");
    end

    localAddNormalizedPhasePatches(ax);

    uistack(allLineHandles, "top");

    xline(ax, 20, "--", ...
        "Lift-off", ...
        "HandleVisibility", "off");

    xline(ax, 80, "--", ...
        "Re-contact", ...
        "HandleVisibility", "off");

    xlabel(ax, "Normalized task time (%)");
    ylabel(ax, yLabelText);
    title(ax, figureTitle);

    if isempty(legendConditionOrder)

        legend(ax, ...
            allLineHandles, ...
            arrayfun( ...
                @(x) sprintf("%g°", x), ...
                conditions, ...
                "UniformOutput", false), ...
            "Location", "best");

    else

        legendHandles = gobjects(0,1);
        legendLabels = strings(0,1);

        for requestedCondition = legendConditionOrder(:).'

            match = find( ...
                conditions == requestedCondition, ...
                1, ...
                "first");

            if isempty(match)
                continue;
            end

            legendHandles(end+1,1) = ...
                allLineHandles(match); %#ok<AGROW>

            legendLabels(end+1,1) = ...
                sprintf("%g°", requestedCondition); %#ok<AGROW>
        end

        legend(ax, ...
            legendHandles, ...
            cellstr(legendLabels), ...
            "Location", "best");
    end

    grid(ax, "on");
    box(ax, "on");

    ylim(ax, [ ...
        0, ...
        localUpperYLimit(maxPlottedValue)]);

    exportgraphics(fig, outFile, ...
        "Resolution", 300);

    close(fig);
end


function upperLimit = localUpperYLimit(values)
%LOCALUPPERYLIMIT Return an automatic positive y-axis ceiling.
%
% The caller fixes the lower limit at zero. The upper limit is 5% above
% the largest finite plotted value. If the plotted data contain no
% positive finite values, use 1 as a safe fallback.

    values = double(values(:));
    values = values(isfinite(values));

    if isempty(values)
        maximumValue = 0;
    else
        maximumValue = max(values);
    end

    if maximumValue > 0
        upperLimit = 1.05 * maximumValue;
    else
        upperLimit = 1;
    end
end


function localAddRawPhasePatches(ax, breaks)

    yLimits = ylim(ax);

    ranges = [ ...
        breaks(1) breaks(2)
        breaks(2) breaks(3)
        breaks(3) breaks(4)
    ];

    colors = [ ...
        0.88 0.93 1.00
        0.94 0.94 0.94
        1.00 0.93 0.88
    ];

    for iPhase = 1:3

        h = patch(ax, ...
            [ ...
                ranges(iPhase,1)
                ranges(iPhase,2)
                ranges(iPhase,2)
                ranges(iPhase,1)
            ], ...
            [ ...
                yLimits(1)
                yLimits(1)
                yLimits(2)
                yLimits(2)
            ], ...
            colors(iPhase,:), ...
            "FaceAlpha", 0.16, ...
            "EdgeColor", "none", ...
            "HandleVisibility", "off");

        uistack(h, "bottom");
    end

    ylim(ax, yLimits);
end


function localAddNormalizedPhasePatches(ax)

    yLimits = ylim(ax);

    ranges = [ ...
        0 20
        20 80
        80 100
    ];

    colors = [ ...
        0.88 0.93 1.00
        0.94 0.94 0.94
        1.00 0.93 0.88
    ];

    for iPhase = 1:3

        h = patch(ax, ...
            [ ...
                ranges(iPhase,1)
                ranges(iPhase,2)
                ranges(iPhase,2)
                ranges(iPhase,1)
            ], ...
            [ ...
                yLimits(1)
                yLimits(1)
                yLimits(2)
                yLimits(2)
            ], ...
            colors(iPhase,:), ...
            "FaceAlpha", 0.16, ...
            "EdgeColor", "none", ...
            "HandleVisibility", "off");

        uistack(h, "bottom");
    end

    ylim(ax, yLimits);
end