function report = run_hsf_sanity_checks()
%RUN_HSF_SANITY_CHECKS Run HSF checks without matlab.unittest discovery.
%
% report = run_hsf_sanity_checks()
%
% This direct runner is useful when diagnosing MATLAB test-discovery
% problems. It throws an error immediately when a check fails.

    toolkitRoot = fileparts(mfilename("fullpath"));
    addpath(toolkitRoot);

    checks = strings(0,1);

    %% Force decomposition: 0 degrees
    zeroDeg = hsf.computeForceComponents( ...
        1.1704014720812095, ...
        -9.80665, ...
        0, ...
        37);

    assertNear(zeroDeg.ForceX, 0, 1e-12, ...
        "0-degree Fx");
    assertNear(zeroDeg.ForceZ, 0, 1e-12, ...
        "0-degree Fz");
    assertNear(zeroDeg.ForceY, ...
        zeroDeg.WeightMagnitudeN, ...
        1e-12, ...
        "0-degree Fy");
    assert(zeroDeg.ComponentCheckPassed, ...
        "0-degree component check failed.");

    checks(end+1,1) = "zero_degree_force";

    %% Force decomposition: 45 degrees
    fortyFive = hsf.computeForceComponents( ...
        1.1704014720812095, ...
        -9.80665, ...
        45, ...
        0);

    assertNear( ...
        fortyFive.ForceX, ...
        fortyFive.WeightMagnitudeN, ...
        1e-10, ...
        "45-degree Fx");

    assertNear( ...
        fortyFive.ForceMagnitudeN, ...
        fortyFive.WeightMagnitudeN / cosd(45), ...
        1e-10, ...
        "45-degree magnitude");

    checks(end+1,1) = "forty_five_degree_force";

    %% Support envelope
    time = (0:0.001:2).';

    envelope = hsf.makeSupportEnvelope( ...
        time, ...
        'OffIntervals', [0.8, 1.2], ...
        'RampDuration', 0.1, ...
        'RampShape', 'linear');

    assertNear( ...
        valueAt(time, envelope.Envelope, 0.75), ...
        0.5, ...
        1e-12, ...
        "ramp-down midpoint");

    assertNear( ...
        valueAt(time, envelope.Envelope, 1.0), ...
        0, ...
        1e-12, ...
        "off interval");

    assertNear( ...
        valueAt(time, envelope.Envelope, 1.25), ...
        0.5, ...
        1e-12, ...
        "ramp-up midpoint");

    checks(end+1,1) = "support_envelope";

    %% CoM resampling
    com = struct;
    com.Time = (0:0.01:0.1).';
    com.X = com.Time;
    com.Y = 2 * com.Time;
    com.Z = -com.Time;

    resampled = hsf.resampleCom( ...
        com, ...
        1000, ...
        'InterpolationMethod', 'linear');

    assert(numel(resampled.Time) == 101, ...
        "Resampled CoM should contain 101 rows.");

    assertNear( ...
        resampled.Time(2) - resampled.Time(1), ...
        0.001, ...
        1e-14, ...
        "resampled time step");

    checks(end+1,1) = "com_resampling";

    %% MOT construction and validation
    force = hsf.computeForceComponents( ...
        1, -9.80665, 0, 0);

    built = hsf.buildMotion( ...
        resampled, ...
        force, ...
        ones(size(resampled.Time)));

    validation = hsf.validateMotion( ...
        built.Motion, ...
        'ExpectedRateHz', 1000);

    assert(validation.Passed, ...
        "Generated HSF motion did not pass validation.");

    checks(end+1,1) = "motion_construction";

    report = table( ...
        checks, ...
        true(numel(checks),1), ...
        'VariableNames', ...
        {'Check', 'Passed'});

    disp(report);

    fprintf( ...
        "All %d direct HSF sanity checks passed.\n", ...
        height(report));
end

function assertNear(actual, expected, tolerance, label)

    if abs(actual - expected) > tolerance
        error("hsf:SanityCheckFailed", ...
            ["%s failed: actual %.15g, expected %.15g, " ...
             "tolerance %.15g."], ...
            label, actual, expected, tolerance);
    end
end

function value = valueAt(time, values, targetTime)

    [~, index] = min(abs(time - targetTime));
    value = values(index);
end
