function result = smoke_test_body_kinematics( ...
        modelFile, ikMotionFile, outputDirectory)
%SMOKE_TEST_BODY_KINEMATICS Run a real OpenSim BodyKinematics analysis.
%
% result = smoke_test_body_kinematics( ...
%     modelFile, ikMotionFile, outputDirectory)
%
% This is intentionally separate from the unit-test suite because it
% requires OpenSim, a project model, and a matching IK file.

    toolkitRoot = fileparts(mfilename("fullpath"));
    addpath(toolkitRoot);

    result = opensimrun.runBodyKinematics( ...
        modelFile, ikMotionFile, outputDirectory, ...
        "BodyNames", "skull", ...
        "ToolName", "smoke_skull_com", ...
        "SetupFile", fullfile( ...
            outputDirectory, "smoke_body_kinematics.xml"), ...
        "Overwrite", true);

    fprintf("Position output: %s\n", result.PositionFile);

    if strlength(result.PositionFile) == 0 || ...
            ~isfile(result.PositionFile)
        error("opensimrun:SmokeTestPositionMissing", ...
            "BodyKinematics position output was not created.");
    end

    com = hsf.readBodyCom(result.PositionFile, "skull");

    fprintf("Read %d skull CoM samples.\n", numel(com.Time));
end
