function audit = auditStaticOptimizationActivations(activationFile, varargin)
%AUDITSTATICOPTIMIZATIONACTIVATIONS Detect saturated SO activation outputs.
%
% audit = opensimrun.auditStaticOptimizationActivations(activationFile)
%
% The activation STO is read with opensimio.readSto. All non-time columns
% are treated as optimization activation/control channels.
%
% A sample is considered saturated when:
%
%   abs(value) >= SaturationLimit - SaturationTolerance
%
% Defaults:
%
%   SaturationLimit      = 1.0
%   SaturationTolerance  = 1e-6
%
% Saturation is reported as audit.Passed == false. Saturation itself does
% NOT throw an exception so batch orchestration can preserve diagnostics
% and continue running other trials.
%
% Structural input problems still throw errors.
%
% RETURN STRUCT
%
%   SchemaVersion
%   ActivationFile
%   SaturationLimit
%   SaturationTolerance
%   SaturationThreshold
%   Passed
%   PeakAbsoluteActivation
%   PeakActivationValue
%   PeakLabel
%   PeakTime
%   SaturatedValueCount
%   SaturatedChannelCount
%   SaturatedLabels
%   FirstSaturationTime
%   LastSaturationTime
%   ChannelSummary
%
% ChannelSummary contains one row per non-time channel:
%
%   Label
%   PeakAbsoluteActivation
%   PeakActivationValue
%   PeakTime
%   SaturatedSampleCount
%   FirstSaturationTime
%   LastSaturationTime
%   Saturated
%
% Negative reserve-actuator saturation is detected through absolute value.

    %% Parse inputs

    parser = ...
        inputParser;

    parser.FunctionName = ...
        "opensimrun.auditStaticOptimizationActivations";

    addRequired(parser, ...
        "activationFile", ...
        @(x) ...
            ischar(x) || ...
            (isstring(x) && isscalar(x) && ~ismissing(x)));

    addParameter(parser, ...
        "SaturationLimit", ...
        1.0, ...
        @(x) ...
            isnumeric(x) && ...
            isscalar(x) && ...
            isfinite(x) && ...
            x > 0);

    addParameter(parser, ...
        "SaturationTolerance", ...
        1e-6, ...
        @(x) ...
            isnumeric(x) && ...
            isscalar(x) && ...
            isfinite(x) && ...
            x >= 0);

    parse(parser, ...
        activationFile, ...
        varargin{:});

    activationFile = ...
        string(parser.Results.activationFile);

    saturationLimit = ...
        double(parser.Results.SaturationLimit);

    saturationTolerance = ...
        double(parser.Results.SaturationTolerance);

    saturationThreshold = ...
        saturationLimit - ...
        saturationTolerance;

    assert(saturationThreshold > 0, ...
        "StaticOptimizationActivationAudit:InvalidThreshold", ...
        "SaturationLimit - SaturationTolerance must be greater than zero.");

    %% Read activation STO

    sto = ...
        opensimio.readSto( ...
            activationFile);

    assert(sto.NumRows >= 1, ...
        "StaticOptimizationActivationAudit:NoRows", ...
        "Activation STO contains no data rows:\n%s", ...
        activationFile);

    assert(sto.NumColumns >= 2, ...
        "StaticOptimizationActivationAudit:NoActivationChannels", ...
        "Activation STO must contain time plus at least one " + ...
        "activation/control channel:\n%s", ...
        activationFile);

    labels = ...
        string(sto.Labels(:));

    assert(numel(labels) == sto.NumColumns, ...
        "StaticOptimizationActivationAudit:LabelCountMismatch", ...
        "Activation STO label count does not match its data columns:\n%s", ...
        activationFile);

    assert(lower(labels(1)) == "time", ...
        "StaticOptimizationActivationAudit:TimeColumnMissing", ...
        "The first activation STO column must be time:\n%s", ...
        activationFile);

    data = ...
        double(sto.Data);

    assert(all(isfinite(data), "all"), ...
        "StaticOptimizationActivationAudit:NonfiniteData", ...
        "Activation STO contains nonfinite values:\n%s", ...
        activationFile);

    time = ...
        double(sto.Time(:));

    channelLabels = ...
        labels(2:end);

    channelData = ...
        data(:,2:end);

    nChannels = ...
        numel(channelLabels);

    %% Per-channel audit

    Label = ...
        channelLabels;

    PeakAbsoluteActivation = ...
        zeros(nChannels,1);

    PeakActivationValue = ...
        zeros(nChannels,1);

    PeakTime = ...
        zeros(nChannels,1);

    SaturatedSampleCount = ...
        zeros(nChannels,1);

    FirstSaturationTime = ...
        nan(nChannels,1);

    LastSaturationTime = ...
        nan(nChannels,1);

    Saturated = ...
        false(nChannels,1);

    for iChannel = 1:nChannels

        values = ...
            channelData(:,iChannel);

        absoluteValues = ...
            abs(values);

        [peakAbsolute, peakIndex] = ...
            max(absoluteValues);

        PeakAbsoluteActivation(iChannel) = ...
            peakAbsolute;

        PeakActivationValue(iChannel) = ...
            values(peakIndex);

        PeakTime(iChannel) = ...
            time(peakIndex);

        saturatedSamples = ...
            absoluteValues >= ...
            saturationThreshold;

        SaturatedSampleCount(iChannel) = ...
            nnz(saturatedSamples);

        Saturated(iChannel) = ...
            any(saturatedSamples);

        if Saturated(iChannel)

            saturatedIndices = ...
                find(saturatedSamples);

            FirstSaturationTime(iChannel) = ...
                time(saturatedIndices(1));

            LastSaturationTime(iChannel) = ...
                time(saturatedIndices(end));
        end
    end

    channelSummary = ...
        table( ...
            Label, ...
            PeakAbsoluteActivation, ...
            PeakActivationValue, ...
            PeakTime, ...
            SaturatedSampleCount, ...
            FirstSaturationTime, ...
            LastSaturationTime, ...
            Saturated);

    %% Trial-level summary

    [trialPeakAbsolute, trialPeakLinearIndex] = ...
        max( ...
            abs(channelData), ...
            [], ...
            "all", ...
            "linear");

    [trialPeakRow, trialPeakColumn] = ...
        ind2sub( ...
            size(channelData), ...
            trialPeakLinearIndex);

    saturationMask = ...
        abs(channelData) >= ...
        saturationThreshold;

    saturatedRows = ...
        find(any(saturationMask, 2));

    audit = struct;

    audit.SchemaVersion = ...
        1;

    audit.ActivationFile = ...
        activationFile;

    audit.SaturationLimit = ...
        saturationLimit;

    audit.SaturationTolerance = ...
        saturationTolerance;

    audit.SaturationThreshold = ...
        saturationThreshold;

    audit.Passed = ...
        ~any(saturationMask, "all");

    audit.PeakAbsoluteActivation = ...
        trialPeakAbsolute;

    audit.PeakActivationValue = ...
        channelData( ...
            trialPeakRow, ...
            trialPeakColumn);

    audit.PeakLabel = ...
        channelLabels(trialPeakColumn);

    audit.PeakTime = ...
        time(trialPeakRow);

    audit.SaturatedValueCount = ...
        nnz(saturationMask);

    audit.SaturatedChannelCount = ...
        nnz(any(saturationMask, 1));

    audit.SaturatedLabels = ...
        channelLabels(any(saturationMask, 1));

    if isempty(saturatedRows)

        audit.FirstSaturationTime = ...
            NaN;

        audit.LastSaturationTime = ...
            NaN;

    else

        audit.FirstSaturationTime = ...
            time(saturatedRows(1));

        audit.LastSaturationTime = ...
            time(saturatedRows(end));
    end

    audit.ChannelSummary = ...
        channelSummary;
end
