function result = prepareStaticOptimizationSetup( ...
        templateFile, outputFile, varargin)
%PREPARESTATICOPTIMIZATIONSETUP Create a trial-specific SO AnalyzeTool XML.
%
% result = opensimrun.prepareStaticOptimizationSetup( ...
%     templateFile, outputFile, ...
%     "ModelFile", modelFile, ...
%     "CoordinatesFile", coordinatesFile, ...
%     "ExternalLoadsFile", externalLoadsFile, ...
%     "ResultsDirectory", resultsDirectory, ...
%     "TimeRange", [startTime endTime])
%
% The shared SO template controls optimizer/scientific settings. This
% function patches only trial-specific paths, time bounds, and optionally
% the AnalyzeTool name / coordinate low-pass cutoff.
%
% REQUIRED NAME-VALUE INPUTS
%   ModelFile
%   CoordinatesFile
%   ExternalLoadsFile
%   ResultsDirectory
%
% NAME-VALUE OPTIONS
%   TimeRange
%       [start end]. Default: full coordinates-file range.
%
%   ToolName
%       Optional AnalyzeTool name. Default: preserve template.
%
%   LowpassCutoffHz
%       Optional override of
%       <lowpass_cutoff_frequency_for_coordinates>.
%       Default: [] (preserve template value).
%
%   Overwrite
%       Replace existing output XML. Default: false.
%
%   CreateFolder
%       Create output/results folders. Default: true.
%
%   RequireInputFiles
%       Require model, coordinates, and ExternalLoads files to exist.
%       Default: true.
%
%   NormalizePaths
%       Write paths with forward slashes. Default: true.
%
% OUTPUT
%   result.OutputFile
%   result.TemplateFile
%   result.ModelFile
%   result.CoordinatesFile
%   result.ExternalLoadsFile
%   result.ResultsDirectory
%   result.TimeRange
%   result.ToolName
%   result.PatchReport
%   result.TemplateValidation
%   result.VerificationPassed

    parser = inputParser;
    parser.FunctionName = ...
        "opensimrun.prepareStaticOptimizationSetup";

    addRequired(parser, "templateFile", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    addRequired(parser, "outputFile", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    addParameter(parser, "ModelFile", "", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    addParameter(parser, "CoordinatesFile", "", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    addParameter(parser, "ExternalLoadsFile", "", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    addParameter(parser, "ResultsDirectory", "", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    addParameter(parser, "TimeRange", [], ...
        @(x) isempty(x) || ...
        (isnumeric(x) && numel(x) == 2 && ...
         all(isfinite(x)) && x(2) > x(1)));

    addParameter(parser, "ToolName", "", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    addParameter(parser, "LowpassCutoffHz", [], ...
        @(x) isempty(x) || ...
        (isnumeric(x) && isscalar(x) && isfinite(x)));

    addParameter(parser, "Overwrite", false, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, "CreateFolder", true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, "RequireInputFiles", true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, "NormalizePaths", true, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, templateFile, outputFile, varargin{:});

    templateFile = string(parser.Results.templateFile);
    outputFile = string(parser.Results.outputFile);

    modelFile = string(parser.Results.ModelFile);
    coordinatesFile = string(parser.Results.CoordinatesFile);
    externalLoadsFile = string(parser.Results.ExternalLoadsFile);
    resultsDirectory = string(parser.Results.ResultsDirectory);

    toolName = string(parser.Results.ToolName);
    lowpassCutoffHz = parser.Results.LowpassCutoffHz;

    overwrite = parser.Results.Overwrite;
    createFolder = parser.Results.CreateFolder;
    requireInputFiles = parser.Results.RequireInputFiles;
    normalizePaths = parser.Results.NormalizePaths;

    %% Validate paths

    assert(isfile(templateFile), ...
        "StaticOptimizationSetup:TemplateMissing", ...
        "SO template was not found:\n%s", ...
        templateFile);

    assert(strlength(modelFile) > 0, ...
        "StaticOptimizationSetup:ModelFileRequired", ...
        "ModelFile is required.");

    assert(strlength(coordinatesFile) > 0, ...
        "StaticOptimizationSetup:CoordinatesFileRequired", ...
        "CoordinatesFile is required.");

    assert(strlength(externalLoadsFile) > 0, ...
        "StaticOptimizationSetup:ExternalLoadsFileRequired", ...
        "ExternalLoadsFile is required.");

    assert(strlength(resultsDirectory) > 0, ...
        "StaticOptimizationSetup:ResultsDirectoryRequired", ...
        "ResultsDirectory is required.");

    if requireInputFiles
        assert(isfile(modelFile), ...
            "StaticOptimizationSetup:ModelMissing", ...
            "SO model was not found:\n%s", ...
            modelFile);

        assert(isfile(coordinatesFile), ...
            "StaticOptimizationSetup:CoordinatesMissing", ...
            "SO coordinates file was not found:\n%s", ...
            coordinatesFile);

        assert(isfile(externalLoadsFile), ...
            "StaticOptimizationSetup:ExternalLoadsMissing", ...
            "ExternalLoads XML was not found:\n%s", ...
            externalLoadsFile);
    end

    [~, ~, templateExtension] = fileparts(templateFile);

    assert(strcmpi(templateExtension, ".xml"), ...
        "StaticOptimizationSetup:InvalidTemplateExtension", ...
        "SO template must use the .xml extension.");

    [outputParent, ~, outputExtension] = ...
        fileparts(outputFile);

    assert(strcmpi(outputExtension, ".xml"), ...
        "StaticOptimizationSetup:InvalidOutputExtension", ...
        "SO setup output must use the .xml extension.");

    if isfile(outputFile) && ~overwrite
        error( ...
            "StaticOptimizationSetup:OutputExists", ...
            ["SO setup already exists:\n%s\n" ...
             "Set Overwrite=true to replace it."], ...
            outputFile);
    end

    if createFolder
        if strlength(string(outputParent)) > 0 && ...
                ~isfolder(outputParent)
            mkdir(outputParent);
        end

        if ~isfolder(resultsDirectory)
            mkdir(resultsDirectory);
        end
    end

    %% Determine time range

    coordinateMotion = ...
        opensimio.readMot(coordinatesFile);

    if isempty(parser.Results.TimeRange)
        timeRange = [ ...
            coordinateMotion.Time(1), ...
            coordinateMotion.Time(end)];
    else
        timeRange = ...
            double(parser.Results.TimeRange(:).');
    end

    tolerance = ...
        max(1e-12, ...
        1e-9 * max(abs(coordinateMotion.Time)));

    assert( ...
        timeRange(1) >= coordinateMotion.Time(1) - tolerance && ...
        timeRange(2) <= coordinateMotion.Time(end) + tolerance, ...
        "StaticOptimizationSetup:TimeRangeOutsideCoordinates", ...
        ["Requested SO range [%.9g %.9g] is outside coordinates range " ...
         "[%.9g %.9g]."], ...
        timeRange(1), timeRange(2), ...
        coordinateMotion.Time(1), ...
        coordinateMotion.Time(end));

    %% Read and validate template

    xmlData = ...
        opensimio.readXml(templateFile);

    assert(isstruct(xmlData) && ...
        isfield(xmlData, "Document"), ...
        "StaticOptimizationSetup:InvalidXmlReaderOutput", ...
        "opensimio.readXml did not return a Document.");

    document = xmlData.Document;

    analyzeToolNodes = ...
        document.getElementsByTagName("AnalyzeTool");

    assert(analyzeToolNodes.getLength() == 1, ...
        "StaticOptimizationSetup:AnalyzeToolCount", ...
        "Expected exactly one <AnalyzeTool>; found %d.", ...
        analyzeToolNodes.getLength());

    staticOptimizationNodes = ...
        document.getElementsByTagName("StaticOptimization");

    assert(staticOptimizationNodes.getLength() == 1, ...
        "StaticOptimizationSetup:StaticOptimizationCount", ...
        "Expected exactly one <StaticOptimization>; found %d.", ...
        staticOptimizationNodes.getLength());

    analyzeToolNode = ...
        analyzeToolNodes.item(0);

    templateValidation = table( ...
        [ ...
            "replace_force_set"
            "use_model_force_set"
            "states_file"
        ], ...
        [ ...
            "false"
            "true"
            ""
        ], ...
        [ ...
            localGetUniqueTagText(document, "replace_force_set")
            localGetUniqueTagText(document, "use_model_force_set")
            localGetUniqueTagText(document, "states_file")
        ], ...
        'VariableNames', { ...
            'Element', ...
            'ExpectedValue', ...
            'ObservedValue'});

    templateValidation.Passed = ...
        templateValidation.ExpectedValue == ...
        templateValidation.ObservedValue;

    assert(all(templateValidation.Passed), ...
        "StaticOptimizationSetup:TemplateValidationFailed", ...
        ["SO template does not match the expected workflow. " ...
         "Review replace_force_set, use_model_force_set, and states_file."]);

    %% Normalize paths

    modelFileXml = localNormalizePath( ...
        modelFile, normalizePaths);

    coordinatesFileXml = localNormalizePath( ...
        coordinatesFile, normalizePaths);

    externalLoadsFileXml = localNormalizePath( ...
        externalLoadsFile, normalizePaths);

    resultsDirectoryXml = localNormalizePath( ...
        resultsDirectory, normalizePaths);

    %% Patch trial-specific fields

    patchElement = strings(0,1);
    oldValue = strings(0,1);
    newValue = strings(0,1);

    oldToolName = string(char( ...
        analyzeToolNode.getAttribute("name")));

    if strlength(toolName) > 0
        analyzeToolNode.setAttribute( ...
            "name", char(toolName));

        patchElement(end+1,1) = "AnalyzeTool@name";
        oldValue(end+1,1) = oldToolName;
        newValue(end+1,1) = toolName;
    else
        toolName = oldToolName;
    end

    [patchElement, oldValue, newValue] = ...
        localPatchTag(document, "model_file", modelFileXml, ...
        patchElement, oldValue, newValue);

    [patchElement, oldValue, newValue] = ...
        localPatchTag(document, "results_directory", ...
        resultsDirectoryXml, patchElement, oldValue, newValue);

    [patchElement, oldValue, newValue] = ...
        localPatchTag(document, "initial_time", ...
        string(sprintf("%.15g", timeRange(1))), ...
        patchElement, oldValue, newValue);

    [patchElement, oldValue, newValue] = ...
        localPatchTag(document, "final_time", ...
        string(sprintf("%.15g", timeRange(2))), ...
        patchElement, oldValue, newValue);

    [patchElement, oldValue, newValue] = ...
        localPatchTag(document, "start_time", ...
        string(sprintf("%.15g", timeRange(1))), ...
        patchElement, oldValue, newValue);

    [patchElement, oldValue, newValue] = ...
        localPatchTag(document, "end_time", ...
        string(sprintf("%.15g", timeRange(2))), ...
        patchElement, oldValue, newValue);

    [patchElement, oldValue, newValue] = ...
        localPatchTag(document, "external_loads_file", ...
        externalLoadsFileXml, patchElement, oldValue, newValue);

    [patchElement, oldValue, newValue] = ...
        localPatchTag(document, "coordinates_file", ...
        coordinatesFileXml, patchElement, oldValue, newValue);

    if ~isempty(lowpassCutoffHz)
        [patchElement, oldValue, newValue] = ...
            localPatchTag( ...
                document, ...
                "lowpass_cutoff_frequency_for_coordinates", ...
                string(sprintf("%.15g", lowpassCutoffHz)), ...
                patchElement, oldValue, newValue);
    end

    patchReport = table( ...
        patchElement, ...
        oldValue, ...
        newValue, ...
        oldValue ~= newValue, ...
        'VariableNames', { ...
            'Element', ...
            'OldValue', ...
            'NewValue', ...
            'Changed'});

    %% Write and verify

    opensimio.writeXml( ...
        outputFile, ...
        xmlData);

    assert(isfile(outputFile), ...
        "StaticOptimizationSetup:WriteFailed", ...
        "SO setup XML was not written:\n%s", ...
        outputFile);

    verifyXml = ...
        opensimio.readXml(outputFile);

    verifyDocument = ...
        verifyXml.Document;

    verificationElements = [ ...
        "model_file"
        "results_directory"
        "external_loads_file"
        "coordinates_file"
        "initial_time"
        "final_time"
        "start_time"
        "end_time"
    ];

    expectedValues = [ ...
        modelFileXml
        resultsDirectoryXml
        externalLoadsFileXml
        coordinatesFileXml
        string(sprintf("%.15g", timeRange(1)))
        string(sprintf("%.15g", timeRange(2)))
        string(sprintf("%.15g", timeRange(1)))
        string(sprintf("%.15g", timeRange(2)))
    ];

    observedValues = strings(size(expectedValues));

    for iElement = 1:numel(verificationElements)
        observedValues(iElement) = ...
            localGetUniqueTagText( ...
                verifyDocument, ...
                verificationElements(iElement));
    end

    verificationChecks = table( ...
        verificationElements, ...
        expectedValues, ...
        observedValues, ...
        expectedValues == observedValues, ...
        'VariableNames', { ...
            'Element', ...
            'ExpectedValue', ...
            'ObservedValue', ...
            'Passed'});

    verifyAnalyzeToolNode = ...
        verifyDocument.getElementsByTagName( ...
            "AnalyzeTool").item(0);

    verifiedToolName = ...
        string(char( ...
            verifyAnalyzeToolNode.getAttribute("name")));

    namePassed = ...
        verifiedToolName == toolName;

    lowpassPassed = true;

    if ~isempty(lowpassCutoffHz)
        observedLowpass = str2double( ...
            localGetUniqueTagText( ...
                verifyDocument, ...
                "lowpass_cutoff_frequency_for_coordinates"));

        lowpassPassed = ...
            isfinite(observedLowpass) && ...
            abs(observedLowpass - lowpassCutoffHz) < 1e-12;
    end

    verificationPassed = ...
        all(verificationChecks.Passed) && ...
        namePassed && ...
        lowpassPassed;

    assert(verificationPassed, ...
        "StaticOptimizationSetup:VerificationFailed", ...
        "Written SO setup XML failed verification.");

    result = struct;
    result.TemplateFile = templateFile;
    result.OutputFile = outputFile;
    result.ModelFile = modelFile;
    result.CoordinatesFile = coordinatesFile;
    result.ExternalLoadsFile = externalLoadsFile;
    result.ResultsDirectory = resultsDirectory;
    result.TimeRange = timeRange;
    result.ToolName = toolName;
    result.PatchReport = patchReport;
    result.TemplateValidation = templateValidation;
    result.VerificationChecks = verificationChecks;
    result.VerificationPassed = verificationPassed;
end


function [elements, oldValues, newValues] = localPatchTag( ...
        document, tagName, replacementValue, ...
        elements, oldValues, newValues)

    node = ...
        localGetUniqueTagNode(document, tagName);

    oldText = ...
        strtrim(string(char( ...
            node.getTextContent())));

    node.setTextContent( ...
        char(replacementValue));

    elements(end+1,1) = string(tagName);
    oldValues(end+1,1) = oldText;
    newValues(end+1,1) = string(replacementValue);
end


function value = localNormalizePath(value, normalizePaths)

    value = string(value);

    if normalizePaths
        value = replace(value, "\", "/");
    end
end


function node = localGetUniqueTagNode(document, tagName)

    nodes = ...
        document.getElementsByTagName( ...
            char(string(tagName)));

    assert(nodes.getLength() == 1, ...
        "StaticOptimizationSetup:UnexpectedTagCount", ...
        "Expected exactly one <%s>; found %d.", ...
        string(tagName), ...
        nodes.getLength());

    node = nodes.item(0);
end


function value = localGetUniqueTagText(document, tagName)

    node = ...
        localGetUniqueTagNode(document, tagName);

    value = ...
        strtrim(string(char( ...
            node.getTextContent())));
end
