function result = runStaticOptimizationSetup(setupFile, varargin)
%RUNSTATICOPTIMIZATIONSETUP Run and audit one OpenSim Static Optimization setup.
%
% result = opensimrun.runStaticOptimizationSetup(setupFile)
%
% The setup XML is assumed to have already been generated and validated by
% opensimrun.prepareStaticOptimizationSetup. This function deliberately does
% not modify the setup. It:
%
%   1) reads key paths/settings from the XML;
%   2) constructs OpenSim AnalyzeTool directly from the setup file;
%   3) runs Static Optimization;
%   4) locates the generated force and activation STO files;
%   5) performs structural/time-range QC on those outputs.
%
% NAME-VALUE OPTIONS
%   Overwrite
%       Delete existing StaticOptimization force/activation outputs before
%       running. Default: false.
%
%   RequireForceOutput
%       Require exactly one *StaticOptimization_force.sto. Default: true.
%
%   RequireActivationOutput
%       Require exactly one *StaticOptimization_activation.sto.
%       Default: true.
%
%   TimeToleranceSec
%       Allowed difference between requested and written output endpoints.
%       Default: 1e-6 s.
%
% OUTPUT
%   result.SetupFile
%   result.ToolName
%   result.ModelFile
%   result.CoordinatesFile
%   result.ExternalLoadsFile
%   result.ResultsDirectory
%   result.RequestedTimeRange
%   result.RunSucceeded
%   result.DurationSeconds
%   result.ForceFile
%   result.ActivationFile
%   result.OutputAudit
%
% OpenSim API note:
%   AnalyzeTool(setupFile, true) loads the model and input files specified
%   by the XML. This is preferable here to rebuilding the tool
%   programmatically because the setup XML is the artifact under test.

    parser = inputParser;
    parser.FunctionName = ...
        "opensimrun.runStaticOptimizationSetup";

    addRequired(parser, "setupFile", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    addParameter(parser, "Overwrite", false, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, "RequireForceOutput", true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, "RequireActivationOutput", true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, "TimeToleranceSec", 1e-6, ...
        @(x) isnumeric(x) && isscalar(x) && ...
        isfinite(x) && x >= 0);

    parse(parser, setupFile, varargin{:});

    setupFile = string(parser.Results.setupFile);
    overwrite = parser.Results.Overwrite;
    requireForceOutput = parser.Results.RequireForceOutput;
    requireActivationOutput = parser.Results.RequireActivationOutput;
    timeToleranceSec = parser.Results.TimeToleranceSec;

    assert(isfile(setupFile), ...
        "StaticOptimizationRun:SetupMissing", ...
        "SO setup file was not found:\n%s", ...
        setupFile);

    %% Read setup XML

    xmlData = ...
        opensimio.readXml(setupFile);

    document = ...
        xmlData.Document;

    analyzeToolNodes = ...
        document.getElementsByTagName("AnalyzeTool");

    assert(analyzeToolNodes.getLength() == 1, ...
        "StaticOptimizationRun:AnalyzeToolCount", ...
        "Expected exactly one AnalyzeTool; found %d.", ...
        analyzeToolNodes.getLength());

    staticOptimizationNodes = ...
        document.getElementsByTagName("StaticOptimization");

    assert(staticOptimizationNodes.getLength() == 1, ...
        "StaticOptimizationRun:StaticOptimizationCount", ...
        "Expected exactly one StaticOptimization analysis; found %d.", ...
        staticOptimizationNodes.getLength());

    analyzeToolNode = ...
        analyzeToolNodes.item(0);

    toolName = ...
        string(char( ...
            analyzeToolNode.getAttribute("name")));

    modelFile = ...
        localResolveSetupPath( ...
            localGetUniqueTagText( ...
                document, "model_file"), ...
            setupFile);

    coordinatesFile = ...
        localResolveSetupPath( ...
            localGetUniqueTagText( ...
                document, "coordinates_file"), ...
            setupFile);

    externalLoadsFile = ...
        localResolveSetupPath( ...
            localGetUniqueTagText( ...
                document, "external_loads_file"), ...
            setupFile);

    resultsDirectory = ...
        localResolveSetupPath( ...
            localGetUniqueTagText( ...
                document, "results_directory"), ...
            setupFile);

    initialTime = str2double( ...
        localGetUniqueTagText( ...
            document, "initial_time"));

    finalTime = str2double( ...
        localGetUniqueTagText( ...
            document, "final_time"));

    startTime = str2double( ...
        localGetUniqueTagText( ...
            document, "start_time"));

    endTime = str2double( ...
        localGetUniqueTagText( ...
            document, "end_time"));

    assert(isfinite(initialTime) && isfinite(finalTime) && ...
           finalTime > initialTime, ...
        "StaticOptimizationRun:InvalidAnalyzeTimeRange", ...
        "AnalyzeTool initial/final time is invalid.");

    assert(isfinite(startTime) && isfinite(endTime) && ...
           endTime > startTime, ...
        "StaticOptimizationRun:InvalidStaticOptimizationTimeRange", ...
        "StaticOptimization start/end time is invalid.");

    assert(abs(initialTime - startTime) <= timeToleranceSec && ...
           abs(finalTime - endTime) <= timeToleranceSec, ...
        "StaticOptimizationRun:TimeRangeMismatch", ...
        "AnalyzeTool and StaticOptimization time ranges do not match.\nAnalyzeTool: [%.9g %.9g]\nStaticOptimization: [%.9g %.9g]", ...
        initialTime, finalTime, startTime, endTime);

    assert(isfile(modelFile), ...
        "StaticOptimizationRun:ModelMissing", ...
        "Model file referenced by setup does not exist:\n%s", ...
        modelFile);

    assert(isfile(coordinatesFile), ...
        "StaticOptimizationRun:CoordinatesMissing", ...
        "Coordinates file referenced by setup does not exist:\n%s", ...
        coordinatesFile);

    assert(isfile(externalLoadsFile), ...
        "StaticOptimizationRun:ExternalLoadsMissing", ...
        "ExternalLoads file referenced by setup does not exist:\n%s", ...
        externalLoadsFile);

    if ~isfolder(resultsDirectory)
        mkdir(resultsDirectory);
    end

    %% Protect / clear prior SO outputs

    existingForceFiles = ...
        localFindMatchingFiles( ...
            resultsDirectory, ...
            "*StaticOptimization_force.sto");

    existingActivationFiles = ...
        localFindMatchingFiles( ...
            resultsDirectory, ...
            "*StaticOptimization_activation.sto");

    if (~isempty(existingForceFiles) || ...
            ~isempty(existingActivationFiles)) && ...
            ~overwrite

        error( ...
            "StaticOptimizationRun:OutputsExist", ...
            "Static Optimization outputs already exist under:\n%s\nSet Overwrite=true to replace the force/activation outputs.", ...
            resultsDirectory);
    end

    if overwrite

        for filePath = [ ...
                existingForceFiles(:)
                existingActivationFiles(:)].'

            if isfile(filePath)
                delete(filePath);
            end
        end
    end

    %% Run setup exactly as written

    import org.opensim.modeling.*

    fprintf("\nRunning Static Optimization\n");
    fprintf("  Setup:       %s\n", setupFile);
    fprintf("  Tool name:   %s\n", toolName);
    fprintf("  Model:       %s\n", modelFile);
    fprintf("  Coordinates: %s\n", coordinatesFile);
    fprintf("  Loads:       %s\n", externalLoadsFile);
    fprintf("  Results:     %s\n", resultsDirectory);
    fprintf("  Time range:  %.9g to %.9g s\n", ...
        initialTime, finalTime);

    % Constructing from the XML with aLoadModelAndInput=true makes the
    % generated setup file itself the source of truth for execution.
    tool = AnalyzeTool( ...
        char(setupFile), ...
        true);

    tic;
    runSucceeded = ...
        logical(tool.run());
    durationSeconds = toc;

    assert(runSucceeded, ...
        "StaticOptimizationRun:RunFailed", ...
        "OpenSim AnalyzeTool reported Static Optimization failure.");

    %% Locate expected outputs

    forceFiles = ...
        localFindMatchingFiles( ...
            resultsDirectory, ...
            "*StaticOptimization_force.sto");

    activationFiles = ...
        localFindMatchingFiles( ...
            resultsDirectory, ...
            "*StaticOptimization_activation.sto");

    if requireForceOutput
        assert(numel(forceFiles) == 1, ...
            "StaticOptimizationRun:ForceOutputCount", ...
            "Expected exactly one StaticOptimization force STO under:\n" + ...
             "%s\nFound %d.", ...
            resultsDirectory, ...
            numel(forceFiles)); %#ok<*ISCL>
    end

    if requireActivationOutput
        assert(numel(activationFiles) == 1, ...
            "StaticOptimizationRun:ActivationOutputCount", ...
            "Expected exactly one StaticOptimization activation STO under:\n" + ...
             "%s\nFound %d.", ...
            resultsDirectory, ...
            numel(activationFiles));
    end

    if isempty(forceFiles)
        forceFile = "";
    else
        forceFile = forceFiles(1);
    end

    if isempty(activationFiles)
        activationFile = "";
    else
        activationFile = activationFiles(1);
    end

    %% Audit outputs

    auditRows = table();

    if strlength(forceFile) > 0
        forceAudit = ...
            localAuditSto( ...
                forceFile, ...
                "force", ...
                [initialTime finalTime], ...
                timeToleranceSec);

        auditRows = [ ...
            auditRows
            forceAudit];
    end

    if strlength(activationFile) > 0
        activationAudit = ...
            localAuditSto( ...
                activationFile, ...
                "activation", ...
                [initialTime finalTime], ...
                timeToleranceSec);

        auditRows = [ ...
            auditRows
            activationAudit];
    end

    assert(~isempty(auditRows), ...
        "StaticOptimizationRun:NoAuditableOutputs", ...
        "Static Optimization produced no auditable output files.");

    assert(all(auditRows.Passed), ...
        "StaticOptimizationRun:OutputAuditFailed", ...
        "One or more Static Optimization outputs failed structural QC.");

    %% Return

    result = struct;

    result.SetupFile = setupFile;
    result.ToolName = toolName;

    result.ModelFile = modelFile;
    result.CoordinatesFile = coordinatesFile;
    result.ExternalLoadsFile = externalLoadsFile;
    result.ResultsDirectory = resultsDirectory;

    result.RequestedTimeRange = ...
        [initialTime finalTime];

    result.RunSucceeded = ...
        runSucceeded;

    result.DurationSeconds = ...
        durationSeconds;

    result.ForceFile = forceFile;
    result.ActivationFile = activationFile;

    result.OutputAudit = ...
        auditRows;

    fprintf("\nStatic Optimization completed successfully.\n");
    fprintf("  Duration: %.3f s\n", durationSeconds);

    if strlength(forceFile) > 0
        fprintf("  Force output:      %s\n", forceFile);
    end

    if strlength(activationFile) > 0
        fprintf("  Activation output: %s\n", activationFile);
    end

    fprintf("\nOutput audit:\n");
    disp(auditRows);
end


function audit = localAuditSto( ...
        filePath, outputType, requestedRange, tolerance)

    sto = ...
        opensimio.readSto(filePath);

    assert(sto.NumRows >= 2, ...
        "StaticOptimizationRun:TooFewOutputRows", ...
        "%s STO contains fewer than two rows:\n%s", ...
        outputType, filePath);

    assert(sto.NumColumns >= 2, ...
        "StaticOptimizationRun:TooFewOutputColumns", ...
        "%s STO contains fewer than two columns:\n%s", ...
        outputType, filePath);

    assert(all(isfinite(sto.Data), "all"), ...
        "StaticOptimizationRun:NonfiniteOutput", ...
        "%s STO contains nonfinite values:\n%s", ...
        outputType, filePath);

    time = ...
        double(sto.Time(:));

    strictlyIncreasing = ...
        all(diff(time) > 0);

    if numel(time) >= 2
        medianDt = ...
            median(diff(time));
    else
        medianDt = NaN;
    end

    % StaticOptimization step_interval can decimate the stored results.
    % Therefore the last written row may occur up to approximately one
    % output interval before the requested final time even when the
    % analysis completed normally.
    if isfinite(medianDt)
        coverageTolerance = ...
            max(tolerance, 1.5 * medianDt);
    else
        coverageTolerance = tolerance;
    end

    startMatches = ...
        abs(time(1) - requestedRange(1)) <= ...
        coverageTolerance;

    endMatches = ...
        abs(time(end) - requestedRange(2)) <= ...
        coverageTolerance;

    outputWithinRequestedRange = ...
        time(1) >= requestedRange(1) - coverageTolerance && ...
        time(end) <= requestedRange(2) + coverageTolerance;

    passed = ...
        strictlyIncreasing && ...
        startMatches && ...
        endMatches && ...
        outputWithinRequestedRange;

    audit = table( ...
        string(outputType), ...
        string(filePath), ...
        sto.NumRows, ...
        sto.NumColumns, ...
        time(1), ...
        time(end), ...
        medianDt, ...
        coverageTolerance, ...
        strictlyIncreasing, ...
        startMatches, ...
        endMatches, ...
        outputWithinRequestedRange, ...
        passed, ...
        'VariableNames', { ...
            'OutputType', ...
            'File', ...
            'NumRows', ...
            'NumColumns', ...
            'StartTime', ...
            'EndTime', ...
            'MedianDt', ...
            'CoverageToleranceSec', ...
            'TimeStrictlyIncreasing', ...
            'StartTimeMatches', ...
            'EndTimeMatches', ...
            'OutputWithinRequestedRange', ...
            'Passed'});
end


function paths = localFindMatchingFiles(directory, pattern)

    listing = ...
        dir(fullfile(directory, pattern));

    paths = strings(numel(listing),1);

    for iFile = 1:numel(listing)
        paths(iFile) = string(fullfile( ...
            listing(iFile).folder, ...
            listing(iFile).name));
    end
end


function pathValue = localResolveSetupPath( ...
        pathValue, setupFile)

    pathValue = ...
        string(pathValue);

    assert(strlength(pathValue) > 0, ...
        "StaticOptimizationRun:EmptySetupPath", ...
        "A required setup path is empty.");

    % Java/OpenSim XML commonly uses forward slashes even on Windows.
    pathValue = ...
        replace(pathValue, "/", filesep);

    if ~localIsAbsolutePath(pathValue)

        setupDirectory = ...
            string(fileparts(setupFile));

        pathValue = string(fullfile( ...
            setupDirectory, ...
            pathValue));
    end
end


function tf = localIsAbsolutePath(pathValue)

    pathValue = char(pathValue);

    if ispc
        tf = ...
            (~isempty(regexp( ...
                pathValue, ...
                '^[A-Za-z]:[\\/]', ...
                'once'))) || ...
            startsWith(pathValue, "\\");
    else
        tf = startsWith(pathValue, "/");
    end
end


function value = localGetUniqueTagText( ...
        document, tagName)

    nodes = ...
        document.getElementsByTagName( ...
            char(string(tagName)));

    assert(nodes.getLength() == 1, ...
        "StaticOptimizationRun:UnexpectedTagCount", ...
        "Expected exactly one <%s>; found %d.", ...
        string(tagName), ...
        nodes.getLength());

    value = ...
        strtrim(string(char( ...
            nodes.item(0).getTextContent())));
end
