function result = buildMotion( ...
        resampledCom, forceComponents, envelopeInput, varargin)
%BUILDMOTION Construct a seven-column OpenSim-compatible HSF motion.
%
% result = hsf.buildMotion( ...
%     resampledCom, forceComponents, envelopeInput)
%
% REQUIRED INPUTS
%   resampledCom
%       Struct containing:
%           Time
%           X
%           Y
%           Z
%
%   forceComponents
%       Struct containing the supported force components:
%           ForceX
%           ForceY
%           ForceZ
%
%   envelopeInput
%       Either:
%           - numeric support-envelope vector, or
%           - struct containing field Envelope
%
% NAME-VALUE OPTIONS
%   ForcePrefix
%       Force-column prefix.
%       Default: hsf.defaultParameters().ForcePrefix
%
%   PointPrefix
%       Force-application-point column prefix.
%       Default: hsf.defaultParameters().PointPrefix
%
%   Name
%       Motion/storage name retained in the returned result.
%       Default: "head_support_force"
%
% OUTPUT
%   result.Motion
%       Seven-column OpenSim motion structure:
%           time
%           <ForcePrefix>x
%           <ForcePrefix>y
%           <ForcePrefix>z
%           <PointPrefix>x
%           <PointPrefix>y
%           <PointPrefix>z
%
%   result.Name
%   result.Envelope
%   result.ForceComponents
%   result.ResampledCom
%
% Force values are multiplied by the support envelope. The force
% application point follows the skull center of mass even while the force
% is zero.
%
% Torque columns are intentionally not supported by the current HSF
% formulation.

    defaults = ...
        hsf.defaultParameters();

    parser = ...
        inputParser;

    parser.FunctionName = ...
        "hsf.buildMotion";

    addRequired( ...
        parser, ...
        "resampledCom", ...
        @isstruct);

    addRequired( ...
        parser, ...
        "forceComponents", ...
        @isstruct);

    addRequired( ...
        parser, ...
        "envelopeInput");

    addParameter( ...
        parser, ...
        "ForcePrefix", ...
        defaults.ForcePrefix, ...
        @(x) ischar(x) || ...
            (isstring(x) && isscalar(x)));

    addParameter( ...
        parser, ...
        "PointPrefix", ...
        defaults.PointPrefix, ...
        @(x) ischar(x) || ...
            (isstring(x) && isscalar(x)));

    addParameter( ...
        parser, ...
        "Name", ...
        "head_support_force", ...
        @(x) ischar(x) || ...
            (isstring(x) && isscalar(x)));

    parse( ...
        parser, ...
        resampledCom, ...
        forceComponents, ...
        envelopeInput, ...
        varargin{:});

    %% Validate CoM input

    requiredComFields = [
        "Time"
        "X"
        "Y"
        "Z"
    ];

    assert(all(isfield( ...
            resampledCom, ...
            requiredComFields)), ...
        "hsf:InvalidResampledCom", ...
        "resampledCom must contain Time, X, Y, and Z.");

    time = ...
        double(resampledCom.Time(:));

    x = ...
        double(resampledCom.X(:));

    y = ...
        double(resampledCom.Y(:));

    z = ...
        double(resampledCom.Z(:));

    numRows = ...
        numel(time);

    assert(numRows >= 1, ...
        "hsf:EmptyResampledCom", ...
        "resampledCom must contain at least one sample.");

    assert(all([ ...
            numel(x), ...
            numel(y), ...
            numel(z)] == numRows), ...
        "hsf:ResampledComLengthMismatch", ...
        "Time, X, Y, and Z must contain the same number of samples.");

    assert(all(isfinite([ ...
            time, ...
            x, ...
            y, ...
            z]), ...
        "all"), ...
        "hsf:NonfiniteResampledCom", ...
        "resampledCom contains nonfinite values.");

    if numRows > 1

        assert(all(diff(time) > 0), ...
            "hsf:NonmonotonicResampledComTime", ...
            "resampledCom.Time must be strictly increasing.");
    end

    %% Validate force components

    requiredForceFields = [
        "ForceX"
        "ForceY"
        "ForceZ"
    ];

    assert(all(isfield( ...
            forceComponents, ...
            requiredForceFields)), ...
        "hsf:InvalidForceComponents", ...
        "forceComponents must contain ForceX, ForceY, and ForceZ.");

    supportedForce = [
        double(forceComponents.ForceX)
        double(forceComponents.ForceY)
        double(forceComponents.ForceZ)
    ].';

    assert(isequal( ...
            size(supportedForce), ...
            [1, 3]), ...
        "hsf:InvalidForceComponentShape", ...
        "ForceX, ForceY, and ForceZ must each be numeric scalars.");

    assert(all(isfinite(supportedForce)), ...
        "hsf:NonfiniteForceComponents", ...
        "ForceX, ForceY, and ForceZ must be finite.");

    %% Resolve support envelope

    if isstruct(envelopeInput) && ...
            isfield(envelopeInput, "Envelope")

        envelope = ...
            double( ...
                envelopeInput.Envelope(:));

    elseif isnumeric(envelopeInput) && ...
            isvector(envelopeInput)

        envelope = ...
            double( ...
                envelopeInput(:));

    else

        error( ...
            "hsf:InvalidEnvelope", ...
            "envelopeInput must be a numeric vector or " + ...
            "a struct containing field Envelope.");
    end

    assert(numel(envelope) == numRows, ...
        "hsf:EnvelopeLengthMismatch", ...
        "Envelope length (%d) does not match CoM time length (%d).", ...
        numel(envelope), ...
        numRows);

    assert(all(isfinite(envelope)), ...
        "hsf:NonfiniteEnvelope", ...
        "Support envelope contains nonfinite values.");

    assert(all( ...
            envelope >= -1e-12 & ...
            envelope <= 1 + 1e-12), ...
        "hsf:EnvelopeBounds", ...
        "Support envelope must remain within the expected [0,1] range.");

    envelope = ...
        min( ...
            max(envelope, 0), ...
            1);

    %% Build seven-column HSF motion

    forceData = ...
        envelope .* ...
        supportedForce;

    pointData = [
        x
        y
        z
    ];

    forcePrefix = ...
        string( ...
            parser.Results.ForcePrefix);

    pointPrefix = ...
        string( ...
            parser.Results.PointPrefix);

    labels = [ ...
        "time", ...
        forcePrefix + "x", ...
        forcePrefix + "y", ...
        forcePrefix + "z", ...
        pointPrefix + "x", ...
        pointPrefix + "y", ...
        pointPrefix + "z" ...
    ];

    data = [ ...
        time, ...
        forceData, ...
        pointData ...
    ];

    assert(size(data, 2) == 7, ...
        "hsf:UnexpectedColumnCount", ...
        "HSF motion must contain exactly seven columns.");

    assert(all(isfinite(data), "all"), ...
        "hsf:NonfiniteMotion", ...
        "Generated HSF motion contains nonfinite values.");

    %% Build OpenSim motion structure

    motion = ...
        struct;

    motion.FilePath = ...
        "";

    motion.Extension = ...
        ".mot";

    motion.HeaderLines = ...
        strings(0, 1);

    motion.Metadata = ...
        table( ...
            'Size', ...
                [0, 4], ...
            'VariableTypes', ...
                { ...
                    'string', ...
                    'string', ...
                    'string', ...
                    'double'}, ...
            'VariableNames', ...
                { ...
                    'Key', ...
                    'Value', ...
                    'RawLine', ...
                    'LineNumber'});

    motion.Labels = ...
        labels;

    motion.Data = ...
        data;

    motion.Time = ...
        time;

    motion.InDegrees = ...
        false;

    motion.NumRows = ...
        size(data, 1);

    motion.NumColumns = ...
        size(data, 2);

    motion.LabelLineIndex = ...
        NaN;

    %% Return result

    result = ...
        struct;

    result.Motion = ...
        motion;

    result.Name = ...
        string( ...
            parser.Results.Name);

    result.Envelope = ...
        envelope;

    result.ForceComponents = ...
        forceComponents;

    result.ResampledCom = ...
        resampledCom;
end
