function result = generateFromResampledCom( ...
        comInput, conditionDeg, gndrollDeg, liftOffWindow, ...
        outputFile, varargin)
%GENERATEFROMRESAMPLEDCOM Generate a seven-column head-support-force MOT.
%
% result = hsf.generateFromResampledCom( ...
%     comInput, conditionDeg, gndrollDeg, liftOffWindow, outputFile)
%
% This function begins from an already validated/resampled skull CoM
% trajectory and generates the HSF data required by OpenSim ExternalLoads.
%
% REQUIRED INPUTS
%   comInput
%       Struct containing:
%           Time
%           X
%           Y
%           Z
%
%       The CoM should already be expressed in ground and sampled at the
%       desired HSF output rate.
%
%   conditionDeg
%       Incline condition in degrees.
%
%   gndrollDeg
%       Ground-roll coordinate in degrees. Used to resolve the radial
%       support-force component into ground X/Z.
%
%   liftOffWindow
%       [liftOffTime recontactTime], seconds.
%       Support force is zero between these times.
%
%   outputFile
%       Destination .mot file.
%
% NAME-VALUE OPTIONS
%   Parameters
%       HSF parameter struct. Default: hsf.defaultParameters().
%
%   Overwrite
%       Replace an existing output file. Default: false.
%
%   MotionName
%       OpenSim storage name. Default: "head_support_force".
%
% OUTPUT
%   result.OutputFile
%   result.Motion
%   result.Parameters
%   result.ForceComponents
%   result.SupportEnvelope
%   result.LiftOffWindow
%   result.Summary
%   result.Validation
%
% FORCE CONVENTION
%   W  = SkullMassKg * abs(GravityY)
%   Fr = W * tand(conditionDeg)
%
%   Fy = W
%   Fx = RadialSign * Fr * cosd(gndrollDeg)
%   Fz = RadialSign * Fr * sind(gndrollDeg)
%
%   During support, each force component is multiplied by the support
%   envelope. The force application point always follows skull CoM.
%
% SUPPORT ENVELOPE
%   - 1 during supported periods
%   - half-cosine ramp from 1 -> 0 before lift-off
%   - 0 during lift-off
%   - half-cosine ramp from 0 -> 1 after re-contact
%
% No torque columns are generated.

    parser = inputParser;
    parser.FunctionName = "hsf.generateFromResampledCom";

    addRequired(parser, "comInput", @isstruct);

    addRequired(parser, "conditionDeg", ...
        @(x) isnumeric(x) && isscalar(x) && isfinite(x));

    addRequired(parser, "gndrollDeg", ...
        @(x) isnumeric(x) && isscalar(x) && isfinite(x));

    addRequired(parser, "liftOffWindow", ...
        @(x) isnumeric(x) && numel(x) == 2 && ...
        all(isfinite(x)) && x(2) > x(1));

    addRequired(parser, "outputFile", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    addParameter(parser, "Parameters", [], ...
        @(x) isempty(x) || isstruct(x));

    addParameter(parser, "Overwrite", false, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, "MotionName", "head_support_force", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    parse(parser, ...
        comInput, conditionDeg, gndrollDeg, ...
        liftOffWindow, outputFile, varargin{:});

    outputFile = string(outputFile);
    motionName = string(parser.Results.MotionName);
    overwrite = parser.Results.Overwrite;

    if isempty(parser.Results.Parameters)
        parameters = hsf.defaultParameters();
    else
        parameters = parser.Results.Parameters;
    end

    requiredParameterFields = [ ...
        "SkullMassKg"
        "GravityY"
        "TargetRateHz"
        "RampDuration"
        "RampShape"
        "RadialSign"
        "AzimuthConvention"
        "ForcePrefix"
        "PointPrefix"
    ];

    for iField = 1:numel(requiredParameterFields)
        fieldName = requiredParameterFields(iField);

        assert(isfield(parameters, fieldName), ...
            "hsf:MissingParameter", ...
            "HSF parameter struct is missing '%s'.", ...
            fieldName);
    end

    requiredComFields = ["Time", "X", "Y", "Z"];

    assert(all(isfield(comInput, requiredComFields)), ...
        "hsf:InvalidComStructure", ...
        "comInput must contain Time, X, Y, and Z.");

    time = double(comInput.Time(:));
    x = double(comInput.X(:));
    y = double(comInput.Y(:));
    z = double(comInput.Z(:));

    numSamples = numel(time);

    assert(numSamples >= 2, ...
        "hsf:InsufficientComSamples", ...
        "At least two CoM samples are required.");

    assert(all([numel(x), numel(y), numel(z)] == numSamples), ...
        "hsf:ComLengthMismatch", ...
        "Time, X, Y, and Z must have equal lengths.");

    assert(all(isfinite([time, x, y, z]), "all"), ...
        "hsf:NonfiniteCom", ...
        "CoM input contains nonfinite values.");

    assert(all(diff(time) > 0), ...
        "hsf:NonmonotonicComTime", ...
        "CoM time must be strictly increasing.");

    dt = diff(time);
    estimatedRateHz = 1 / median(dt);

    expectedRateHz = double(parameters.TargetRateHz);

    assert(max(abs(dt - 1/expectedRateHz)) < 1e-8, ...
        "hsf:UnexpectedComSampleRate", ...
        ["CoM trajectory is not uniformly sampled at TargetRateHz=%g. " ...
         "Estimated rate is %.9g Hz."], ...
        expectedRateHz, estimatedRateHz);

    liftOffWindow = double(liftOffWindow(:).');

    assert(liftOffWindow(1) >= time(1), ...
        "hsf:LiftOffBeforeData", ...
        "Lift-off occurs before the CoM trajectory begins.");

    assert(liftOffWindow(2) <= time(end), ...
        "hsf:RecontactAfterData", ...
        "Re-contact occurs after the CoM trajectory ends.");

    if isfile(outputFile) && ~overwrite
        error( ...
            "hsf:OutputExists", ...
            ["HSF output already exists:\n%s\n" ...
             "Set Overwrite=true to replace it."], ...
            outputFile);
    end

    [outputParent, ~, extension] = fileparts(outputFile);

    assert(strcmpi(extension, ".mot"), ...
        "hsf:InvalidOutputExtension", ...
        "HSF output must use the .mot extension.");

    if strlength(string(outputParent)) > 0 && ...
            ~isfolder(outputParent)
        mkdir(outputParent);
    end

    %% Compute supported force components

    skullWeightN = ...
        double(parameters.SkullMassKg) * ...
        abs(double(parameters.GravityY));

    radialMagnitudeN = ...
        skullWeightN * tand(double(conditionDeg));

    azimuthConvention = ...
        string(parameters.AzimuthConvention);

    switch azimuthConvention

        case "x_cos_z_sin"

            supportedFxN = ...
                double(parameters.RadialSign) * ...
                radialMagnitudeN * ...
                cosd(double(gndrollDeg));

            supportedFzN = ...
                double(parameters.RadialSign) * ...
                radialMagnitudeN * ...
                sind(double(gndrollDeg));

        otherwise

            error( ...
                "hsf:UnsupportedAzimuthConvention", ...
                "Unsupported AzimuthConvention '%s'.", ...
                azimuthConvention);
    end

    supportedFyN = skullWeightN;

    supportedForceMagnitudeN = ...
        norm([ ...
            supportedFxN, ...
            supportedFyN, ...
            supportedFzN]);

    expectedForceMagnitudeN = ...
        skullWeightN / cosd(double(conditionDeg));

    assert(abs( ...
        supportedForceMagnitudeN - ...
        expectedForceMagnitudeN) < 1e-9, ...
        "hsf:ForceMagnitudeMismatch", ...
        ["Resolved support-force magnitude %.12g N does not match " ...
         "expected %.12g N."], ...
        supportedForceMagnitudeN, ...
        expectedForceMagnitudeN);

    %% Build support envelope

    rampDuration = ...
        double(parameters.RampDuration);

    assert(rampDuration >= 0, ...
        "hsf:InvalidRampDuration", ...
        "RampDuration must be nonnegative.");

    rampShape = ...
        string(parameters.RampShape);

    assert(rampShape == "halfcosine", ...
        "hsf:UnsupportedRampShape", ...
        "Only RampShape='halfcosine' is currently supported.");

    liftStart = liftOffWindow(1);
    liftEnd = liftOffWindow(2);

    envelope = ones(numSamples, 1);

    % Lift-off plateau.
    liftMask = ...
        time >= liftStart & ...
        time <= liftEnd;

    envelope(liftMask) = 0;

    if rampDuration > 0

        % Supported -> zero immediately before lift-off.
        preRampStart = ...
            max(time(1), liftStart - rampDuration);

        preRampDuration = ...
            liftStart - preRampStart;

        preRampMask = ...
            time >= preRampStart & ...
            time < liftStart;

        if preRampDuration > 0 && any(preRampMask)

            alpha = ...
                (time(preRampMask) - preRampStart) / ...
                preRampDuration;

            envelope(preRampMask) = ...
                0.5 * (1 + cos(pi * alpha));
        end

        % Zero -> supported immediately after re-contact.
        postRampEnd = ...
            min(time(end), liftEnd + rampDuration);

        postRampDuration = ...
            postRampEnd - liftEnd;

        postRampMask = ...
            time > liftEnd & ...
            time <= postRampEnd;

        if postRampDuration > 0 && any(postRampMask)

            alpha = ...
                (time(postRampMask) - liftEnd) / ...
                postRampDuration;

            envelope(postRampMask) = ...
                0.5 * (1 - cos(pi * alpha));
        end
    end

    assert(all(envelope >= -1e-12 & envelope <= 1 + 1e-12), ...
        "hsf:EnvelopeBounds", ...
        "Support envelope left the expected [0,1] range.");

    envelope = min(max(envelope, 0), 1);

    %% Build force and point columns

    forceX = supportedFxN .* envelope;
    forceY = supportedFyN .* envelope;
    forceZ = supportedFzN .* envelope;

    forcePrefix = string(parameters.ForcePrefix);
    pointPrefix = string(parameters.PointPrefix);

    labels = [ ...
        "time", ...
        forcePrefix + "x", ...
        forcePrefix + "y", ...
        forcePrefix + "z", ...
        pointPrefix + "x", ...
        pointPrefix + "y", ...
        pointPrefix + "z" ...
    ];

    data = [ ...
        time, ...
        forceX, ...
        forceY, ...
        forceZ, ...
        x, ...
        y, ...
        z ...
    ];

    assert(size(data, 2) == 7, ...
        "hsf:UnexpectedColumnCount", ...
        "HSF motion must contain exactly seven columns.");

    assert(all(isfinite(data), "all"), ...
        "hsf:NonfiniteMotion", ...
        "Generated HSF motion contains nonfinite values.");

    motion = struct;
    motion.Labels = labels;
    motion.Data = data;
    motion.InDegrees = false;

    %% Write and verify MOT

    opensimio.writeOpenSimTable( ...
        outputFile, ...
        motion, ...
        "Name", motionName, ...
        "InDegrees", false);

    assert(isfile(outputFile), ...
        "hsf:WriteFailed", ...
        "HSF MOT was not written:\n%s", ...
        outputFile);

    writtenMotion = ...
        opensimio.readMot(outputFile);

    assert(writtenMotion.NumRows == numSamples, ...
        "hsf:WrittenRowMismatch", ...
        ["Written HSF has %d rows; expected %d."], ...
        writtenMotion.NumRows, numSamples);

    assert(writtenMotion.NumColumns == 7, ...
        "hsf:WrittenColumnMismatch", ...
        "Written HSF does not contain seven columns.");

    assert(isequal( ...
        reshape(string(writtenMotion.Labels), 1, []), ...
        reshape(labels, 1, [])), ...
        "hsf:WrittenLabelMismatch", ...
        "Written HSF labels do not match the expected schema.");

    %% Validation/QC

    forceMagnitude = ...
        sqrt(forceX.^2 + forceY.^2 + forceZ.^2);

    zeroForceMask = ...
        envelope == 0;

    fullSupportMask = ...
        envelope == 1;

    validation = struct;

    validation.AllFinite = ...
        all(isfinite(data), "all");

    validation.TimeStrictlyIncreasing = ...
        all(diff(time) > 0);

    validation.UniformTargetRate = ...
        max(abs(dt - 1/expectedRateHz)) < 1e-8;

    validation.ZeroDuringLiftOff = ...
        all(abs(forceMagnitude(liftMask)) < 1e-10);

    validation.FullSupportMagnitudeCorrect = ...
        isempty(forceMagnitude(fullSupportMask)) || ...
        max(abs( ...
            forceMagnitude(fullSupportMask) - ...
            expectedForceMagnitudeN)) < 1e-9;

    validation.PointMatchesCom = ...
        isequaln(data(:,5:7), [x,y,z]);

    validation.Passed = ...
        validation.AllFinite && ...
        validation.TimeStrictlyIncreasing && ...
        validation.UniformTargetRate && ...
        validation.ZeroDuringLiftOff && ...
        validation.FullSupportMagnitudeCorrect && ...
        validation.PointMatchesCom;

    assert(validation.Passed, ...
        "hsf:ValidationFailed", ...
        "Generated HSF failed one or more internal validation checks.");

    summary = table( ...
        double(conditionDeg), ...
        double(gndrollDeg), ...
        double(parameters.SkullMassKg), ...
        double(parameters.GravityY), ...
        expectedRateHz, ...
        liftStart, ...
        liftEnd, ...
        rampDuration, ...
        skullWeightN, ...
        radialMagnitudeN, ...
        supportedFxN, ...
        supportedFyN, ...
        supportedFzN, ...
        expectedForceMagnitudeN, ...
        min(forceMagnitude), ...
        max(forceMagnitude), ...
        nnz(zeroForceMask), ...
        nnz(fullSupportMask), ...
        'VariableNames', { ...
            'ConditionDeg', ...
            'GndRollDeg', ...
            'SkullMassKg', ...
            'GravityY', ...
            'TargetRateHz', ...
            'LiftOffTime', ...
            'RecontactTime', ...
            'RampDurationSec', ...
            'SkullWeightN', ...
            'RadialMagnitudeN', ...
            'SupportedFxN', ...
            'SupportedFyN', ...
            'SupportedFzN', ...
            'ExpectedSupportMagnitudeN', ...
            'MinimumForceMagnitudeN', ...
            'MaximumForceMagnitudeN', ...
            'NumZeroForceSamples', ...
            'NumFullSupportSamples'});

    result = struct;

    result.OutputFile = outputFile;
    result.Motion = writtenMotion;
    result.Parameters = parameters;
    result.ForceComponents = struct( ...
        "SupportedFxN", supportedFxN, ...
        "SupportedFyN", supportedFyN, ...
        "SupportedFzN", supportedFzN, ...
        "RadialMagnitudeN", radialMagnitudeN, ...
        "SupportedMagnitudeN", supportedForceMagnitudeN);
    result.SupportEnvelope = envelope;
    result.LiftOffWindow = liftOffWindow;
    result.Summary = summary;
    result.Validation = validation;
end
