function tableOut = addStaticOptimizationAnalysisIdentityColumns( ...
        tableIn, analysisContext, enabled)
%ADDSTATICOPTIMIZATIONANALYSISIDENTITYCOLUMNS Add config provenance columns.
%
% tableOut = pipeline.addStaticOptimizationAnalysisIdentityColumns( ...
%     tableIn, analysisContext, enabled)
%
% Prepends these columns to a study-level analysis export:
%   config_id
%   muscle_percent
%   actuator_percent
%
% Configured analyses receive their selected ConfigId and strength
% percentages. Legacy analyses receive config_id="" and NaN percentages.
%
% If enabled=false, tableIn is returned unchanged.

    assert(istable(tableIn), ...
        "SOAnalysisIdentity:InvalidInputTable", ...
        "tableIn must be a MATLAB table.");

    assert(isstruct(analysisContext) && isscalar(analysisContext), ...
        "SOAnalysisIdentity:InvalidAnalysisContext", ...
        "analysisContext must be a scalar struct.");

    assert(islogical(enabled) && isscalar(enabled), ...
        "SOAnalysisIdentity:InvalidEnabledFlag", ...
        "enabled must be a logical scalar.");

    tableOut = ...
        tableIn;

    if ~enabled
        return;
    end

    requiredFields = [
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
    ];

    missingFields = ...
        requiredFields( ...
            ~isfield( ...
                analysisContext, ...
                cellstr(requiredFields)));

    assert(isempty(missingFields), ...
        "SOAnalysisIdentity:ContextFieldsMissing", ...
        "analysisContext is missing required fields: %s", ...
        strjoin(missingFields, ", "));

    provenanceNames = [
        "config_id"
        "muscle_percent"
        "actuator_percent"
    ];

    existingNames = ...
        string(tableOut.Properties.VariableNames);

    duplicateNames = ...
        intersect( ...
            provenanceNames, ...
            existingNames, ...
            "stable");

    assert(isempty(duplicateNames), ...
        "SOAnalysisIdentity:ColumnsAlreadyPresent", ...
        "Input table already contains provenance column(s): %s", ...
        strjoin(duplicateNames, ", "));

    nRows = ...
        height(tableOut);

    configId = ...
        repmat( ...
            string(analysisContext.ConfigId), ...
            nRows, ...
            1);

    musclePercent = ...
        repmat( ...
            double(analysisContext.MusclePercent), ...
            nRows, ...
            1);

    actuatorPercent = ...
        repmat( ...
            double(analysisContext.ActuatorPercent), ...
            nRows, ...
            1);

    tableOut = ...
        addvars( ...
            tableOut, ...
            configId, ...
            musclePercent, ...
            actuatorPercent, ...
            'Before', ...
                1, ...
            'NewVariableNames', ...
                { ...
                    'config_id', ...
                    'muscle_percent', ...
                    'actuator_percent' ...
                });
end
