function [runResultOut, activationAuditOut] = ...
        compactStaticOptimizationCheckpointData( ...
            runResultIn, activationAuditIn)
%COMPACTSTATICOPTIMIZATIONCHECKPOINTDATA Remove duplicated heavy P4 payloads.
%
% [runResultOut, activationAuditOut] = ...
%     pipeline.compactStaticOptimizationCheckpointData( ...
%         runResultIn, activationAuditIn)
%
% Produces compact checkpoint-safe copies of the detailed Process-4 result
% structures while preserving the fields most likely to be useful for
% provenance, restart diagnostics, and compatibility.
%
% Removed from runResult:
%   Tool
%   Model
%   OutputAudit
%
% OutputAudit is already stored separately in the Process-4 checkpoint and,
% when QC writing is enabled, in the canonical output-audit CSV.
%
% Removed from activationAudit:
%   ChannelSummary
%
% ChannelSummary is already persisted to the canonical activation-audit CSV.
%
% All other fields are retained unchanged. Inputs are not modified.

    assert(isstruct(runResultIn) && isscalar(runResultIn), ...
        "SOCheckpointCompact:InvalidRunResult", ...
        "runResultIn must be a scalar struct.");

    assert(isstruct(activationAuditIn) && isscalar(activationAuditIn), ...
        "SOCheckpointCompact:InvalidActivationAudit", ...
        "activationAuditIn must be a scalar struct.");

    runResultOut = ...
        runResultIn;

    removableRunFields = ...
        intersect( ...
            string(fieldnames(runResultOut)), ...
            [ ...
                "Tool"
                "Model"
                "OutputAudit"
            ], ...
            "stable");

    if ~isempty(removableRunFields)

        runResultOut = ...
            rmfield( ...
                runResultOut, ...
                cellstr(removableRunFields));
    end

    activationAuditOut = ...
        activationAuditIn;

    if isfield( ...
            activationAuditOut, ...
            "ChannelSummary")

        activationAuditOut = ...
            rmfield( ...
                activationAuditOut, ...
                "ChannelSummary");
    end
end
