function discovery = discoverStaticOptimizationResults( ...
        projectCfg, varargin)
%DISCOVERSTATICOPTIMIZATIONRESULTS Discover existing SO force results.
%
% discovery = pipeline.discoverStaticOptimizationResults(projectCfg)
%
% Discovery is driven by files that actually exist rather than by
% projectCfg.conditions/projectCfg.trials. By default, the function
% searches recursively beneath projectCfg.outputRoot for:
%
%   *StaticOptimization_force.sto
%
% under projectCfg.outputRoot, groups results by canonical
% 04_static_optimization/results directories, infers condition/trial
% identity from the surrounding directory names, and audits the companion
% artifacts required by the final QC/analysis wrapper.
%
% This function is SIDE-EFFECT FREE.
%
% NAME-VALUE OPTIONS
%
%   ExcludedTrials
%       N-by-2 [condition_deg trial_num] numeric array. Default zeros(0,2).
%
% RETURN TABLE
%
%   ConditionDeg
%   TrialNumber
%   TrialStem
%   BatchRoot
%   TrialRoot
%   ResultsDirectory
%   QcDirectory
%   PlotDirectory
%   ForceFile
%   ActivationFile
%   ModelFile
%   EventSummaryFile
%   ForceFileCount
%   ActivationFileCount
%   ReadyForQc
%   ExcludedByConfig
%   Status
%
% BatchRoot is inferred as the directory immediately above the condition
% directory. In the canonical layout this is projectCfg.outputRoot. If
% multiple nested result batches exist beneath outputRoot, different
% BatchRoot values allow the user-facing analysis wrapper to warn before
% pooling them.

    assert(isstruct(projectCfg), ...
        "SOResultDiscovery:InvalidProjectConfig", ...
        "projectCfg must be a struct.");

    assert(isfield(projectCfg, "outputRoot"), ...
        "SOResultDiscovery:OutputRootMissing", ...
        "projectCfg.outputRoot is required.");

    parser = inputParser;
    parser.FunctionName = ...
        "pipeline.discoverStaticOptimizationResults";

    addRequired(parser, ...
        "projectCfg", ...
        @isstruct);

    addParameter(parser, ...
        "ExcludedTrials", ...
        zeros(0,2), ...
        @(x) isnumeric(x) && ...
        (isempty(x) || size(x,2) == 2));

    parse(parser, ...
        projectCfg, varargin{:});

    excludedTrials = ...
        double(parser.Results.ExcludedTrials);

    outputRoot = ...
        string(projectCfg.outputRoot);

    assert(isfolder(outputRoot), ...
        "SOResultDiscovery:OutputRootNotFound", ...
        "Project output root was not found:\n%s", ...
        outputRoot);

    %% Find all force STOs recursively

    forceListing = ...
        dir(fullfile( ...
            outputRoot, ...
            "**", ...
            "*StaticOptimization_force.sto"));

    if isempty(forceListing)

        discovery = ...
            localEmptyDiscoveryTable();

        return;
    end

    forceFiles = strings(numel(forceListing),1);
    resultsDirectories = strings(numel(forceListing),1);

    validCanonical = false(numel(forceListing),1);

    for iFile = 1:numel(forceListing)

        forceFiles(iFile) = ...
            string(fullfile( ...
                forceListing(iFile).folder, ...
                forceListing(iFile).name));

        resultsDirectories(iFile) = ...
            string(forceListing(iFile).folder);

        [soDirectory, resultsName] = ...
            fileparts( ...
                resultsDirectories(iFile));

        [~, soDirectoryName] = ...
            fileparts( ...
                soDirectory);

        validCanonical(iFile) = ...
            string(resultsName) == "results" && ...
            string(soDirectoryName) == ...
                "04_static_optimization";
    end

    % Ignore force files outside the canonical Process-4 result tree.
    forceFiles = ...
        forceFiles(validCanonical);

    resultsDirectories = ...
        resultsDirectories(validCanonical);

    if isempty(forceFiles)

        discovery = ...
            localEmptyDiscoveryTable();

        return;
    end

    uniqueResultsDirectories = ...
        unique( ...
            resultsDirectories, ...
            "stable");

    nLocations = ...
        numel(uniqueResultsDirectories);

    ConditionDeg = nan(nLocations,1);
    TrialNumber = nan(nLocations,1);

    TrialStem = strings(nLocations,1);
    BatchRoot = strings(nLocations,1);
    TrialRoot = strings(nLocations,1);
    ResultsDirectory = strings(nLocations,1);
    QcDirectory = strings(nLocations,1);
    PlotDirectory = strings(nLocations,1);

    ForceFile = strings(nLocations,1);
    ActivationFile = strings(nLocations,1);
    ModelFile = strings(nLocations,1);
    EventSummaryFile = strings(nLocations,1);

    ForceFileCount = zeros(nLocations,1);
    ActivationFileCount = zeros(nLocations,1);

    ReadyForQc = false(nLocations,1);
    ExcludedByConfig = false(nLocations,1);
    Status = strings(nLocations,1);

    keepLocation = false(nLocations,1);

    %% Audit each canonical results directory

    for iLocation = 1:nLocations

        resultsDirectory = ...
            uniqueResultsDirectories(iLocation);

        [soDirectory, ~] = ...
            fileparts( ...
                resultsDirectory);

        [trialRoot, soDirectoryName] = ...
            fileparts( ...
                soDirectory);

        [conditionDirectory, trialTag] = ...
            fileparts( ...
                trialRoot);

        [batchRoot, conditionTag] = ...
            fileparts( ...
                conditionDirectory);

        trialMatch = ...
            regexp( ...
                char(trialTag), ...
                '^trial(?<trial>\d+)$', ...
                'names', ...
                'once');

        conditionMatch = ...
            regexp( ...
                char(conditionTag), ...
                '^(?<condition>-?\d+)deg$', ...
                'names', ...
                'once');

        if isempty(trialMatch) || ...
                isempty(conditionMatch) || ...
                string(soDirectoryName) ~= ...
                    "04_static_optimization"

            continue;
        end

        conditionDeg = ...
            str2double( ...
                conditionMatch.condition);

        trialNumber = ...
            str2double( ...
                trialMatch.trial);

        if ~isfinite(conditionDeg) || ...
                ~isfinite(trialNumber)

            continue;
        end

        keepLocation(iLocation) = ...
            true;

        conditionFolderName = ...
            string(conditionTag);

        trialFolderName = ...
            string(trialTag);

        trialStem = ...
            conditionFolderName + ...
            "_" + ...
            trialFolderName;

        prepDirectory = ...
            string(fullfile( ...
                trialRoot, ...
                "03_static_optimization_prep"));

        modelFile = ...
            string(fullfile( ...
                prepDirectory, ...
                trialStem + ...
                "_modelC_static_optimization.osim"));

        eventSummaryFile = ...
            string(fullfile( ...
                prepDirectory, ...
                "head_support_force", ...
                "qc", ...
                "contact_event_detection_summary.csv"));

        thisForceListing = ...
            dir(fullfile( ...
                resultsDirectory, ...
                "*StaticOptimization_force.sto"));

        thisActivationListing = ...
            dir(fullfile( ...
                resultsDirectory, ...
                "*StaticOptimization_activation.sto"));

        forceFileCount = ...
            numel(thisForceListing);

        activationFileCount = ...
            numel(thisActivationListing);

        forceFile = "";
        activationFile = "";

        if forceFileCount == 1

            forceFile = ...
                string(fullfile( ...
                    thisForceListing(1).folder, ...
                    thisForceListing(1).name));
        end

        if activationFileCount == 1

            activationFile = ...
                string(fullfile( ...
                    thisActivationListing(1).folder, ...
                    thisActivationListing(1).name));
        end

        modelExists = ...
            isfile(modelFile);

        eventSummaryExists = ...
            isfile(eventSummaryFile);

        readyForQc = ...
            forceFileCount == 1 && ...
            activationFileCount == 1 && ...
            modelExists && ...
            eventSummaryExists;

        excluded = false;

        if ~isempty(excludedTrials)

            excluded = ...
                any( ...
                    excludedTrials(:,1) == ...
                        conditionDeg & ...
                    excludedTrials(:,2) == ...
                        trialNumber);
        end

        issues = strings(0,1);

        if forceFileCount ~= 1

            issues(end+1,1) = ...
                "force_file_count=" + ...
                string(forceFileCount); %#ok<AGROW>
        end

        if activationFileCount ~= 1

            issues(end+1,1) = ...
                "activation_file_count=" + ...
                string(activationFileCount); %#ok<AGROW>
        end

        if ~modelExists

            issues(end+1,1) = ...
                "model_c_missing"; %#ok<AGROW>
        end

        if ~eventSummaryExists

            issues(end+1,1) = ...
                "event_summary_missing"; %#ok<AGROW>
        end

        if excluded

            issues(end+1,1) = ...
                "excluded_by_config"; %#ok<AGROW>
        end

        if isempty(issues)

            status = ...
                "ready";

        else

            status = ...
                strjoin( ...
                    issues, ...
                    "; ");
        end

        ConditionDeg(iLocation) = ...
            conditionDeg;

        TrialNumber(iLocation) = ...
            trialNumber;

        TrialStem(iLocation) = ...
            trialStem;

        BatchRoot(iLocation) = ...
            string(batchRoot);

        TrialRoot(iLocation) = ...
            string(trialRoot);

        ResultsDirectory(iLocation) = ...
            resultsDirectory;

        QcDirectory(iLocation) = ...
            string(fullfile( ...
                soDirectory, ...
                "qc"));

        PlotDirectory(iLocation) = ...
            string(fullfile( ...
                soDirectory, ...
                "qc", ...
                "plots"));

        ForceFile(iLocation) = ...
            forceFile;

        ActivationFile(iLocation) = ...
            activationFile;

        ModelFile(iLocation) = ...
            modelFile;

        EventSummaryFile(iLocation) = ...
            eventSummaryFile;

        ForceFileCount(iLocation) = ...
            forceFileCount;

        ActivationFileCount(iLocation) = ...
            activationFileCount;

        ReadyForQc(iLocation) = ...
            readyForQc;

        ExcludedByConfig(iLocation) = ...
            excluded;

        Status(iLocation) = ...
            status;
    end

    %% Remove noncanonical condition/trial trees

    ConditionDeg = ConditionDeg(keepLocation);
    TrialNumber = TrialNumber(keepLocation);
    TrialStem = TrialStem(keepLocation);
    BatchRoot = BatchRoot(keepLocation);
    TrialRoot = TrialRoot(keepLocation);
    ResultsDirectory = ResultsDirectory(keepLocation);
    QcDirectory = QcDirectory(keepLocation);
    PlotDirectory = PlotDirectory(keepLocation);
    ForceFile = ForceFile(keepLocation);
    ActivationFile = ActivationFile(keepLocation);
    ModelFile = ModelFile(keepLocation);
    EventSummaryFile = EventSummaryFile(keepLocation);
    ForceFileCount = ForceFileCount(keepLocation);
    ActivationFileCount = ActivationFileCount(keepLocation);
    ReadyForQc = ReadyForQc(keepLocation);
    ExcludedByConfig = ExcludedByConfig(keepLocation);
    Status = Status(keepLocation);

    discovery = table( ...
        ConditionDeg, ...
        TrialNumber, ...
        TrialStem, ...
        BatchRoot, ...
        TrialRoot, ...
        ResultsDirectory, ...
        QcDirectory, ...
        PlotDirectory, ...
        ForceFile, ...
        ActivationFile, ...
        ModelFile, ...
        EventSummaryFile, ...
        ForceFileCount, ...
        ActivationFileCount, ...
        ReadyForQc, ...
        ExcludedByConfig, ...
        Status);

    if ~isempty(discovery)

        discovery = ...
            sortrows( ...
                discovery, ...
                { ...
                    'BatchRoot', ...
                    'ConditionDeg', ...
                    'TrialNumber'});
    end
end


function T = localEmptyDiscoveryTable()

    T = table( ...
        zeros(0,1), ...
        zeros(0,1), ...
        strings(0,1), ...
        strings(0,1), ...
        strings(0,1), ...
        strings(0,1), ...
        strings(0,1), ...
        strings(0,1), ...
        strings(0,1), ...
        strings(0,1), ...
        strings(0,1), ...
        strings(0,1), ...
        zeros(0,1), ...
        zeros(0,1), ...
        false(0,1), ...
        false(0,1), ...
        strings(0,1), ...
        'VariableNames', { ...
            'ConditionDeg', ...
            'TrialNumber', ...
            'TrialStem', ...
            'BatchRoot', ...
            'TrialRoot', ...
            'ResultsDirectory', ...
            'QcDirectory', ...
            'PlotDirectory', ...
            'ForceFile', ...
            'ActivationFile', ...
            'ModelFile', ...
            'EventSummaryFile', ...
            'ForceFileCount', ...
            'ActivationFileCount', ...
            'ReadyForQc', ...
            'ExcludedByConfig', ...
            'Status'});
end
