function result = prepareStaticOptimizationTrial( ...
        projectCfg, trial, varargin)
%PREPARESTATICOPTIMIZATIONTRIAL Run Process 3 for one resolved trial.
%
% result = pipeline.prepareStaticOptimizationTrial(projectCfg, trial)
%
% The trial input must be created by:
%
%   trial = pipeline.resolveTrialContext( ...
%       projectCfg, conditionDeg, trialNumber);
%
% This worker is the canonical implementation for:
%   1. validating the completed Process-2 checkpoint;
%   2. building and validating Model C;
%   3. optionally applying the saved force-capacity configuration;
%   4. running Body Kinematics for skull CoM;
%   5. extracting and resampling skull CoM;
%   6. detecting lift-off and re-contact;
%   7. generating the head-support-force MOT;
%   8. generating the trial-specific ExternalLoads XML;
%   9. generating the trial-specific Static Optimization setup XML;
%  10. writing Process-3 QC outputs and checkpoint.
%
% Both the single-trial example and Batch Process 3 should call this
% function. Neither orchestration layer should reimplement these steps.
%
% NAME-VALUE OPTIONS
%
%   ExecuteBodyKinematics
%       true (default). When false, the worker stops after Model C
%       construction/validation and optional force-capacity application.
%
%   Overwrite
%       Defaults to projectCfg.overwriteExisting.
%
%   WriteQc
%       true (default).
%
%   SaveCheckpoint
%       true (default). A completed Process-3 checkpoint is saved only when
%       the complete SO-preparation chain succeeds.
%
%   EventFigureVisible
%       "on" (default) or "off". Batch execution should use "off".
%
%   PrintProgress
%       true (default).
%
% RETURN
%
%   result.Stage
%   result.Trial
%   result.Paths
%   result.TrialTimeRangeSec
%   result.ModelCResult
%   result.ModelCValidation
%   result.SagittalState
%   result.ForceCapacityConfigResult
%   result.BodyKinematicsResult
%   result.ComSummary
%   result.EventDetectionResult
%   result.HsfParameters
%   result.GndrollResult
%   result.HsfResult
%   result.ExternalLoadsResult
%   result.StaticOptimizationSetupResult
%   result.CheckpointFile
%   result.Completed
%   result.DurationSeconds

    assert(isstruct(projectCfg), ...
        "PipelineSOPrep:InvalidProjectConfig", ...
        "projectCfg must be a struct.");

    localValidateTrialContext(trial);

    defaultOverwrite = false;

    if isfield(projectCfg, "overwriteExisting")
        defaultOverwrite = projectCfg.overwriteExisting;
    end

    parser = inputParser;
    parser.FunctionName = ...
        "pipeline.prepareStaticOptimizationTrial";

    addRequired(parser, ...
        "projectCfg", ...
        @isstruct);

    addRequired(parser, ...
        "trial", ...
        @isstruct);

    addParameter(parser, ...
        "ExecuteBodyKinematics", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "Overwrite", ...
        defaultOverwrite, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "WriteQc", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "SaveCheckpoint", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "EventFigureVisible", ...
        "on", ...
        @(x) any(strcmpi(string(x), ["on","off"])));

    addParameter(parser, ...
        "PrintProgress", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, ...
        projectCfg, trial, varargin{:});

    executeBodyKinematics = ...
        parser.Results.ExecuteBodyKinematics;

    overwrite = ...
        parser.Results.Overwrite;

    writeQc = ...
        parser.Results.WriteQc;

    saveCheckpoint = ...
        parser.Results.SaveCheckpoint;

    eventFigureVisible = ...
        lower(string(parser.Results.EventFigureVisible));

    printProgress = ...
        parser.Results.PrintProgress;

    stageStart = tic;

    %% Resolve configuration

    localRequireField( ...
        projectCfg, ...
        "pipeline", ...
        "projectCfg.pipeline");

    localRequireField( ...
        projectCfg.pipeline, ...
        "staticOptimizationPrep", ...
        "projectCfg.pipeline.staticOptimizationPrep");

    prepCfg = ...
        projectCfg.pipeline.staticOptimizationPrep;

    localRequireField( ...
        prepCfg, ...
        "bodyKinematicsLowpassCutoffHz", ...
        "projectCfg.pipeline.staticOptimizationPrep." + ...
        "bodyKinematicsLowpassCutoffHz");

    localRequireField( ...
        prepCfg, ...
        "timeRangeSec", ...
        "projectCfg.pipeline.staticOptimizationPrep.timeRangeSec");

    localRequireField( ...
        projectCfg, ...
        "qc", ...
        "projectCfg.qc");

    localRequireField( ...
        projectCfg.qc, ...
        "lockAudit", ...
        "projectCfg.qc.lockAudit");

    localRequireField( ...
        projectCfg.qc, ...
        "hsfEventDetection", ...
        "projectCfg.qc.hsfEventDetection");

    auditQc = ...
        projectCfg.qc.lockAudit;

    eventCfg = ...
        projectCfg.qc.hsfEventDetection;

    localRequireField( ...
        projectCfg, ...
        "hsf", ...
        "projectCfg.hsf");

    localRequireField( ...
        projectCfg.hsf, ...
        "Parameters", ...
        "projectCfg.hsf.Parameters");

    localRequireField( ...
        projectCfg.hsf, ...
        "useModelBodyMass", ...
        "projectCfg.hsf.useModelBodyMass");

    hsfParameters = ...
        projectCfg.hsf.Parameters;

    %% Resolve paths and prerequisites

    modelBPaths = ...
        trial.Paths.ModelB;

    paths = ...
        trial.Paths.StaticOptimizationPrep;

    soPaths = ...
        trial.Paths.StaticOptimization;

    localEnsureDirectory(paths.Directory);
    localEnsureDirectory(paths.QcDirectory);

    localEnsureDirectory( ...
        paths.BodyKinematics.Directory);

    localEnsureDirectory( ...
        paths.BodyKinematics.ResultsDirectory);

    localEnsureDirectory( ...
        paths.BodyKinematics.QcDirectory);

    localEnsureDirectory( ...
        paths.HeadSupportForce.Directory);

    localEnsureDirectory( ...
        paths.HeadSupportForce.QcDirectory);

    localEnsureDirectory( ...
        soPaths.Directory);

    localEnsureDirectory( ...
        soPaths.ResultsDirectory);

    localEnsureDirectory( ...
        soPaths.QcDirectory);

    requiredInputs = [
        string(modelBPaths.CheckpointFile)
        string(modelBPaths.ModelBFile)
        string(modelBPaths.FinalIkMotionFile)
        string(trial.Inputs.ExternalLoadsTemplate)
        string(trial.Inputs.StaticOptimizationTemplate)
    ];

    requiredLabels = [
        "Process-2 checkpoint"
        "Model B"
        "Final IK motion"
        "ExternalLoads template"
        "Static Optimization template"
    ];

    for inputIndex = 1:numel(requiredInputs)

        assert(isfile(requiredInputs(inputIndex)), ...
            "PipelineSOPrep:InputNotFound", ...
            "%s was not found:\n%s", ...
            requiredLabels(inputIndex), ...
            requiredInputs(inputIndex));
    end

    forceConfigWillApply = ...
        localShouldApplyForceConfig( ...
            projectCfg, ...
            "modelC");

    if ~overwrite

        localAssertOutputsAbsent( ...
            paths, ...
            soPaths, ...
            executeBodyKinematics, ...
            writeQc, ...
            saveCheckpoint, ...
            forceConfigWillApply);
    end

    if printProgress

        fprintf( ...
            "\n=== Process 3: %s ===\n", ...
            trial.DisplayName);

        fprintf( ...
            "Process-2 checkpoint:\n%s\n", ...
            modelBPaths.CheckpointFile);

        fprintf( ...
            "Process-3 output directory:\n%s\n", ...
            paths.Directory);
    end

    %% Load and validate canonical Process-2 checkpoint

    checkpointB = ...
        localLoadProcess2Checkpoint( ...
            modelBPaths.CheckpointFile);

    assert(checkpointB.Completed, ...
        "PipelineSOPrep:Process2Incomplete", ...
        "The Process-2 checkpoint is not marked complete.");

    assert(string(checkpointB.Stage) == ...
            "model_b_final_ik", ...
        "PipelineSOPrep:UnexpectedProcess2Stage", ...
        "Expected Process-2 stage 'model_b_final_ik' but found '%s'.", ...
        string(checkpointB.Stage));

    assert(checkpointB.Trial.ConditionDeg == ...
            trial.ConditionDeg, ...
        "PipelineSOPrep:ConditionMismatch", ...
        "Resolved condition is %g deg, but Process 2 contains %g deg.", ...
        trial.ConditionDeg, ...
        checkpointB.Trial.ConditionDeg);

    assert(checkpointB.Trial.TrialNumber == ...
            trial.TrialNumber, ...
        "PipelineSOPrep:TrialMismatch", ...
        "Resolved trial is %d, but Process 2 contains trial %d.", ...
        trial.TrialNumber, ...
        checkpointB.Trial.TrialNumber);

    assert(logical(checkpointB.ModelBValidation.Passed), ...
        "PipelineSOPrep:ModelBWasInvalid", ...
        "The Process-2 checkpoint reports that Model B failed validation.");

    assert(isfield( ...
            checkpointB.FinalIkRunResult, ...
            "RunSucceeded") && ...
        logical( ...
            checkpointB.FinalIkRunResult.RunSucceeded), ...
        "PipelineSOPrep:FinalIkFailed", ...
        "The Process-2 checkpoint reports that final IK failed.");

    assert(logical( ...
            checkpointB.LockedCoordinateAudit.Passed), ...
        "PipelineSOPrep:LockedAuditFailed", ...
        "The Process-2 locked-coordinate audit did not pass.");

    %% Determine trial time range from final IK

    finalIkMotion = ...
        opensimio.readMot( ...
            modelBPaths.FinalIkMotionFile);

    configuredTimeRange = ...
        prepCfg.timeRangeSec;

    if isempty(configuredTimeRange)

        trialTimeRangeSec = [
            finalIkMotion.Time(1)
            finalIkMotion.Time(end)
        ].';

    else

        trialTimeRangeSec = ...
            double(configuredTimeRange(:)).';
    end

    tolerance = max( ...
        1e-12, ...
        1e-9 * ...
        max(abs(finalIkMotion.Time)));

    assert( ...
        trialTimeRangeSec(1) >= ...
            finalIkMotion.Time(1) - tolerance && ...
        trialTimeRangeSec(2) <= ...
            finalIkMotion.Time(end) + tolerance, ...
        "PipelineSOPrep:TimeRangeOutsideFinalIk", ...
        "Requested trial range [%.9g, %.9g] is outside final IK range " + ...
        "[%.9g, %.9g].", ...
        trialTimeRangeSec(1), ...
        trialTimeRangeSec(2), ...
        finalIkMotion.Time(1), ...
        finalIkMotion.Time(end));

    if printProgress

        fprintf( ...
            "Process-2 checkpoint validated. Trial range: " + ...
            "%.5f to %.5f s.\n", ...
            trialTimeRangeSec(1), ...
            trialTimeRangeSec(2));
    end

    %% Build Model C

    groups = ...
        modelprep.coordinateGroups();

    requiredGroupFields = [
        "StaticOptimizationLocked"
        "Sagittal"
    ];

    missingGroupFields = ...
        requiredGroupFields( ...
            ~isfield( ...
                groups, ...
                cellstr(requiredGroupFields)));

    assert(isempty(missingGroupFields), ...
        "PipelineSOPrep:CoordinateGroupsMissing", ...
        "modelprep.coordinateGroups is missing: %s", ...
        strjoin(missingGroupFields, ", "));

    modelCResult = ...
        modelprep.buildStaticOptimizationModel( ...
            modelBPaths.ModelBFile, ...
            modelBPaths.FinalIkMotionFile, ...
            paths.ModelCFile, ...
            "TimeWindow", ...
                trialTimeRangeSec, ...
            "RotationToleranceDeg", ...
                auditQc.rotationRangeToleranceDeg, ...
            "TranslationToleranceM", ...
                auditQc.translationRangeToleranceM, ...
            "RequireStable", ...
                true);

    assert(isfile(paths.ModelCFile), ...
        "PipelineSOPrep:ModelCWriteFailed", ...
        "Model C was not written:\n%s", ...
        paths.ModelCFile);

    if writeQc

        writetable( ...
            modelCResult.Inspection.Coordinates, ...
            paths.CoordinateConfigurationCsv);

        writetable( ...
            modelCResult.Inspection.Constraints, ...
            paths.ConstraintConfigurationCsv);
    end

    %% Validate Model C

    modelCInspection = ...
        modelprep.inspectModel( ...
            paths.ModelCFile);

    allCoordinateNames = ...
        string( ...
            modelCInspection.Coordinates.Coordinate);

    expectedLocked = ...
        string(groups.StaticOptimizationLocked);

    expectedUnlocked = ...
        setdiff( ...
            allCoordinateNames, ...
            expectedLocked, ...
            "stable");

    modelCValidation = ...
        modelprep.validateModelConfiguration( ...
            paths.ModelCFile, ...
            "ExpectedLocked", ...
                expectedLocked, ...
            "ExpectedUnlocked", ...
                expectedUnlocked, ...
            "ExpectedConstraintsEnforced", ...
                false, ...
            "ThrowOnFailure", ...
                true);

    assert(modelCValidation.Passed, ...
        "PipelineSOPrep:ModelCValidationFailed", ...
        "Model C configuration validation failed.");

    sagittalRows = ...
        ismember( ...
            allCoordinateNames, ...
            string(groups.Sagittal));

    sagittalState = ...
        modelCInspection.Coordinates( ...
            sagittalRows, ...
            { ...
                'Coordinate'
                'DefaultLocked'
                'StateLocked'
                'StateDependent'
                'StateConstrained'
            });

    assert(height(sagittalState) == ...
        numel(groups.Sagittal), ...
        "PipelineSOPrep:SagittalCoordinateCountMismatch", ...
        "Expected %d sagittal coordinates but found %d.", ...
        numel(groups.Sagittal), ...
        height(sagittalState));

    assert(all(~sagittalState.StateLocked), ...
        "PipelineSOPrep:SagittalCoordinateLocked", ...
        "One or more sagittal coordinates are locked in Model C.");

    if printProgress

        fprintf( ...
            "Model C validation passed: root/out-of-plane coordinates " + ...
            "locked, sagittal coordinates unlocked, constraints disabled.\n");
    end

    %% Optionally apply saved force-capacity configuration

    forceCapacityConfigResult = ...
        localMakeSkippedForceConfigResult( ...
            paths.ModelCFile, ...
            "Model C");

    if forceConfigWillApply

        forceCapacityConfigResult = ...
            modelprep.applyConfiguredForceCapacitiesIfEnabled( ...
                paths.ModelCFile, ...
                projectCfg, ...
                "StageName", ...
                    "Model C", ...
                "AuditFile", ...
                    paths.ForceConfigAuditCsv);

        assert(forceCapacityConfigResult.Applied, ...
            "PipelineSOPrep:ForceConfigNotApplied", ...
            "Force-capacity configuration is enabled for Model C but " + ...
            "was not applied.");

        assert(forceCapacityConfigResult.VerificationPassed, ...
            "PipelineSOPrep:ForceConfigVerificationFailed", ...
            "Applied Model C force-capacity configuration failed " + ...
            "verification.");

        if printProgress

            fprintf( ...
                "Force-capacity configuration applied to Model C.\n");

            fprintf( ...
                "Config:\n%s\n", ...
                forceCapacityConfigResult.ConfigFile);

            fprintf( ...
                "Apply mode: %s\n", ...
                forceCapacityConfigResult.ApplyMode);
        end
    elseif printProgress

        fprintf( ...
            "No force-capacity configuration is configured for Model C.\n");
    end

    %% Return early when Model-C-only preparation was requested

    if ~executeBodyKinematics

        result = localMakeResult( ...
            trial, ...
            paths, ...
            soPaths, ...
            trialTimeRangeSec, ...
            modelCResult, ...
            modelCValidation, ...
            sagittalState, ...
            forceCapacityConfigResult, ...
            struct, ...
            table, ...
            struct, ...
            hsfParameters, ...
            struct, ...
            struct, ...
            struct, ...
            struct, ...
            "", ...
            false, ...
            toc(stageStart));

        if printProgress

            fprintf( ...
                "Body Kinematics execution is disabled. " + ...
                "Model C is ready for review.\n");
        end

        return;
    end

    %% Run Body Kinematics for skull CoM

    bodyName = ...
        string(hsfParameters.BodyName);

    bodyKinematicsResult = ...
        opensimrun.runBodyKinematicsForCom( ...
            paths.ModelCFile, ...
            modelBPaths.FinalIkMotionFile, ...
            paths.BodyKinematics.ResultsDirectory, ...
            "BodyName", ...
                bodyName, ...
            "TimeRange", ...
                trialTimeRangeSec, ...
            "ToolName", ...
                trial.TrialStem + ...
                "_body_kinematics", ...
            "SetupFile", ...
                paths.BodyKinematics.SetupFile, ...
            "LowpassCutoffHz", ...
                prepCfg.bodyKinematicsLowpassCutoffHz, ...
            "Overwrite", ...
                overwrite);

    assert(bodyKinematicsResult.RunSucceeded, ...
        "PipelineSOPrep:BodyKinematicsFailed", ...
        "Body Kinematics did not report success.");

    assert(isfile(bodyKinematicsResult.PositionFile), ...
        "PipelineSOPrep:BodyKinematicsOutputMissing", ...
        "Body Kinematics position output was not found:\n%s", ...
        bodyKinematicsResult.PositionFile);

    if printProgress

        fprintf( ...
            "Body Kinematics completed in %.3f seconds.\n", ...
            bodyKinematicsResult.DurationSeconds);
    end

    %% Read and QC raw skull CoM

    rawCom = ...
        hsf.readBodyCom( ...
            bodyKinematicsResult.PositionFile, ...
            bodyName);

    rawComTable = ...
        localComToTable( ...
            rawCom);

    localValidateComTable( ...
        rawComTable, ...
        "raw Body Kinematics skull CoM");

    rawSummary = ...
        localSummarizeCom( ...
            rawComTable, ...
            "raw");

    if writeQc

        writetable( ...
            rawComTable, ...
            paths.BodyKinematics.RawComCsv);
    end

    %% Resolve project HSF parameters from actual Model C

    if logical(projectCfg.hsf.useModelBodyMass)

        hsfParameters.SkullMassKg = ...
            hsf.getBodyMass( ...
                paths.ModelCFile, ...
                bodyName);
    end

    targetRateHz = ...
        double( ...
            hsfParameters.TargetRateHz);

    interpolationMethod = ...
        string( ...
            hsfParameters.InterpolationMethod);

    %% Resample skull CoM

    resampledCom = ...
        hsf.resampleCom( ...
            rawCom, ...
            targetRateHz, ...
            "TimeRange", ...
                trialTimeRangeSec, ...
            "InterpolationMethod", ...
                interpolationMethod);

    resampledComTable = ...
        localComToTable( ...
            resampledCom);

    localValidateComTable( ...
        resampledComTable, ...
        "resampled skull CoM");

    dt = ...
        diff(resampledComTable.time);

    expectedDt = ...
        1 / targetRateHz;

    assert(max(abs(dt - expectedDt)) < 1e-9, ...
        "PipelineSOPrep:ResampledRateMismatch", ...
        "Resampled CoM spacing does not match TargetRateHz=%g. " + ...
        "Maximum |dt - 1/Fs| = %.9g s.", ...
        targetRateHz, ...
        max(abs(dt - expectedDt)));

    resampledSummary = ...
        localSummarizeCom( ...
            resampledComTable, ...
            "resampled");

    comSummary = [
        rawSummary
        resampledSummary
    ];

    if writeQc

        writetable( ...
            resampledComTable, ...
            paths.BodyKinematics.ResampledComCsv);

        writetable( ...
            comSummary, ...
            paths.BodyKinematics.ComSummaryCsv);
    end

    %% Detect lift-off and re-contact from RAW skull CoM

    eventDetectionResult = ...
        hsf.detectContactEventsFromCom( ...
            rawCom, ...
            "BaselineWindow", ...
                eventCfg.baselineWindow, ...
            "LiftOffThresholdM", ...
                eventCfg.liftOffThresholdM, ...
            "RecontactThresholdM", ...
                eventCfg.recontactThresholdM, ...
            "MinimumAboveDurationSec", ...
                eventCfg.minimumAboveDurationSec, ...
            "MinimumBelowDurationSec", ...
                eventCfg.minimumBelowDurationSec, ...
            "SmoothingWindowSec", ...
                eventCfg.smoothingWindowSec, ...
            "SearchWindow", ...
                eventCfg.searchWindow, ...
            "Plot", ...
                writeQc, ...
            "PlotFile", ...
                paths.HeadSupportForce.EventDetectionPlot, ...
            "FigureVisible", ...
                eventFigureVisible);

    liftOffWindowSec = [
        eventDetectionResult.LiftOffTime
        eventDetectionResult.RecontactTime
    ].';

    assert(all(isfinite(liftOffWindowSec)) && ...
        liftOffWindowSec(2) > ...
        liftOffWindowSec(1), ...
        "PipelineSOPrep:InvalidLiftOffWindow", ...
        "Detected lift-off window must be [lift_off recontact].");

    if writeQc

        writetable( ...
            eventDetectionResult.Summary, ...
            paths.HeadSupportForce. ...
                EventDetectionSummaryCsv);
    end

    % Batch execution uses invisible figures. Close them after export so
    % parallel workers do not accumulate graphics objects.
    if eventFigureVisible == "off" && ...
            isfield(eventDetectionResult, "Figure") && ...
            ~isempty(eventDetectionResult.Figure) && ...
            isgraphics(eventDetectionResult.Figure)

        close(eventDetectionResult.Figure);
        eventDetectionResult.Figure = [];
    end

    %% Extract constant gndroll from final IK

    gndrollResult = ...
        hsf.extractCoordinateValue( ...
            modelBPaths.FinalIkMotionFile, ...
            "gndroll", ...
            "TimeWindow", ...
                trialTimeRangeSec, ...
            "Method", ...
                "median", ...
            "RequireConstant", ...
                true, ...
            "Tolerance", ...
                auditQc.rotationRangeToleranceDeg);

    gndrollDeg = ...
        double(gndrollResult.Value);

    %% Generate head-support-force MOT

    hsfResult = ...
        hsf.generateFromResampledCom( ...
            resampledCom, ...
            trial.ConditionDeg, ...
            gndrollDeg, ...
            liftOffWindowSec, ...
            paths.HeadSupportForce.MotionFile, ...
            "Parameters", ...
                hsfParameters, ...
            "Overwrite", ...
                overwrite, ...
            "MotionName", ...
                trial.TrialStem + ...
                "_head_support_force");

    assert(hsfResult.Validation.Passed, ...
        "PipelineSOPrep:HsfValidationFailed", ...
        "Generated HSF failed validation.");

    if writeQc

        writetable( ...
            hsfResult.Summary, ...
            paths.HeadSupportForce.SummaryCsv);

        envelopeTable = table( ...
            hsfResult.Motion.Time(:), ...
            hsfResult.SupportEnvelope(:), ...
            'VariableNames', { ...
                'time', ...
                'support_envelope'});

        writetable( ...
            envelopeTable, ...
            paths.HeadSupportForce. ...
                SupportEnvelopeCsv);
    end

    %% Generate trial-specific ExternalLoads XML

    externalLoadsResult = ...
        opensimrun.prepareExternalLoadsSetup( ...
            trial.Inputs.ExternalLoadsTemplate, ...
            paths.HeadSupportForce.ExternalLoadsFile, ...
            "DataFile", ...
                paths.HeadSupportForce.MotionFile, ...
            "ExternalLoadsName", ...
                trial.TrialStem + ...
                "_external_loads", ...
            "ExpectedAppliedBody", ...
                bodyName, ...
            "ExpectedForceIdentifier", ...
                string(hsfParameters.ForcePrefix), ...
            "ExpectedPointIdentifier", ...
                string(hsfParameters.PointPrefix), ...
            "Overwrite", ...
                overwrite);

    assert(externalLoadsResult.VerificationPassed, ...
        "PipelineSOPrep:ExternalLoadsVerificationFailed", ...
        "Generated ExternalLoads XML failed verification.");

    %% Generate trial-specific Static Optimization setup

    staticOptimizationSetupResult = ...
        opensimrun.prepareStaticOptimizationSetup( ...
            trial.Inputs.StaticOptimizationTemplate, ...
            soPaths.SetupFile, ...
            "ModelFile", ...
                paths.ModelCFile, ...
            "CoordinatesFile", ...
                modelBPaths.FinalIkMotionFile, ...
            "ExternalLoadsFile", ...
                paths.HeadSupportForce.ExternalLoadsFile, ...
            "ResultsDirectory", ...
                soPaths.ResultsDirectory, ...
            "TimeRange", ...
                trialTimeRangeSec, ...
            "ToolName", ...
                "SO_" + trial.TrialStem, ...
            "Overwrite", ...
                overwrite);

    assert( ...
        staticOptimizationSetupResult.VerificationPassed, ...
        "PipelineSOPrep:StaticOptimizationSetupVerificationFailed", ...
        "Generated Static Optimization setup failed verification.");

    %% Save canonical Process-3 checkpoint

    checkpointFile = "";

    if saveCheckpoint

        checkpoint = struct;

        checkpoint.SchemaVersion = 1;
        checkpoint.Stage = ...
            "static_optimization_prep";

        checkpoint.Trial = ...
            trial;

        checkpoint.Configuration = struct( ...
            "TrialTimeRangeSec", ...
                trialTimeRangeSec, ...
            "BodyKinematicsLowpassCutoffHz", ...
                prepCfg.bodyKinematicsLowpassCutoffHz, ...
            "HsfEventDetection", ...
                eventCfg, ...
            "HsfParameters", ...
                hsfParameters, ...
            "Overwrite", ...
                overwrite);

        checkpoint.Paths = ...
            paths;

        checkpoint.StaticOptimizationPaths = ...
            soPaths;

        checkpoint.ModelBCheckpointFile = ...
            modelBPaths.CheckpointFile;

        checkpoint.ModelCResult = ...
            modelCResult;

        checkpoint.ModelCValidation = ...
            modelCValidation;

        checkpoint.SagittalState = ...
            sagittalState;

        checkpoint.ForceCapacityConfigResult = ...
            forceCapacityConfigResult;

        checkpoint.BodyKinematicsResult = ...
            bodyKinematicsResult;

        checkpoint.ComSummary = ...
            comSummary;

        checkpoint.EventDetectionResult = ...
            localCompactEventDetectionResult( ...
                eventDetectionResult);

        checkpoint.GndrollResult = ...
            gndrollResult;

        checkpoint.HsfResult = ...
            localCompactHsfResult( ...
                hsfResult);

        checkpoint.ExternalLoadsResult = ...
            externalLoadsResult;

        checkpoint.StaticOptimizationSetupResult = ...
            staticOptimizationSetupResult;

        checkpoint.Completed = ...
            true;

        checkpoint.CompletedAt = ...
            string(datetime("now"));

        % Temporary compatibility alias for any remaining pre-refactor code.
        modelCCheckpoint = checkpoint; %#ok<NASGU>

        save( ...
            paths.CheckpointFile, ...
            "checkpoint", ...
            "modelCCheckpoint", ...
            "-v7.3");

        checkpointFile = ...
            paths.CheckpointFile;
    end

    %% Return

    result = localMakeResult( ...
        trial, ...
        paths, ...
        soPaths, ...
        trialTimeRangeSec, ...
        modelCResult, ...
        modelCValidation, ...
        sagittalState, ...
        forceCapacityConfigResult, ...
        bodyKinematicsResult, ...
        comSummary, ...
        eventDetectionResult, ...
        hsfParameters, ...
        gndrollResult, ...
        hsfResult, ...
        externalLoadsResult, ...
        staticOptimizationSetupResult, ...
        checkpointFile, ...
        true, ...
        toc(stageStart));

    if printProgress

        fprintf( ...
            "Detected lift-off: %.6f s; re-contact: %.6f s.\n", ...
            liftOffWindowSec(1), ...
            liftOffWindowSec(2));

        fprintf( ...
            "HSF skull mass: %.9g kg.\n", ...
            hsfParameters.SkullMassKg);

        fprintf( ...
            "Process 3 completed in %.3f s.\n", ...
            result.DurationSeconds);

        fprintf( ...
            "Model C:\n%s\n", ...
            paths.ModelCFile);

        fprintf( ...
            "HSF MOT:\n%s\n", ...
            paths.HeadSupportForce.MotionFile);

        fprintf( ...
            "Static Optimization setup:\n%s\n", ...
            soPaths.SetupFile);

        if strlength(checkpointFile) > 0

            fprintf( ...
                "Checkpoint:\n%s\n", ...
                checkpointFile);
        end
    end
end


function checkpoint = localLoadProcess2Checkpoint(checkpointFile)

    loaded = ...
        load( ...
            checkpointFile, ...
            "checkpoint");

    assert(isfield(loaded, "checkpoint"), ...
        "PipelineSOPrep:Process2CheckpointVariableMissing", ...
        "Expected variable 'checkpoint' was not found in:\n%s", ...
        checkpointFile);

    checkpoint = ...
        loaded.checkpoint;

    requiredFields = [
        "SchemaVersion"
        "Stage"
        "Trial"
        "ModelBValidation"
        "FinalIkRunResult"
        "LockedCoordinateAudit"
        "Completed"
    ];

    missingFields = ...
        requiredFields( ...
            ~isfield( ...
                checkpoint, ...
                cellstr(requiredFields)));

    assert(isempty(missingFields), ...
        "PipelineSOPrep:Process2CheckpointIncomplete", ...
        "Process-2 checkpoint is missing fields: %s", ...
        strjoin(missingFields, ", "));
end


function localValidateTrialContext(trial)

    requiredFields = [
        "SchemaVersion"
        "ConditionDeg"
        "TrialNumber"
        "TrialStem"
        "DisplayName"
        "Inputs"
        "Paths"
    ];

    missingFields = ...
        requiredFields( ...
            ~isfield( ...
                trial, ...
                cellstr(requiredFields)));

    assert(isempty(missingFields), ...
        "PipelineSOPrep:TrialContextIncomplete", ...
        "Trial context is missing fields: %s", ...
        strjoin(missingFields, ", "));

    assert(isfield(trial.Paths, "ModelB") && ...
        isfield( ...
            trial.Paths, ...
            "StaticOptimizationPrep") && ...
        isfield( ...
            trial.Paths, ...
            "StaticOptimization"), ...
        "PipelineSOPrep:TrialPathsIncomplete", ...
        "Process-2, Process-3, and Process-4 trial paths are required.");
end


function localRequireField(s, fieldName, label)

    assert(isfield(s, fieldName), ...
        "PipelineSOPrep:ConfigurationFieldMissing", ...
        "Required configuration field is missing: %s", ...
        label);
end


function localEnsureDirectory(directory)

    directory = ...
        string(directory);

    if ~isfolder(directory)
        mkdir(directory);
    end
end


function apply = ...
        localShouldApplyForceConfig( ...
            projectCfg, stageName)

    apply = false;

    if ~isfield(projectCfg, "forceCapacity") || ...
            ~isstruct(projectCfg.forceCapacity)
        return;
    end

    cfg = ...
        projectCfg.forceCapacity;

    if ~isfield(cfg, "enabled") || ...
            ~logical(cfg.enabled)
        return;
    end

    if ~isfield(cfg, "applyStages")

        apply = true;
        return;
    end

    stages = ...
        lower(string(cfg.applyStages(:)));

    apply = ...
        any(stages == lower(string(stageName)));
end


function result = ...
        localMakeSkippedForceConfigResult( ...
            modelFile, stageName)

    result = struct;

    result.ModelFile = ...
        string(modelFile);

    result.StageName = ...
        string(stageName);

    result.Enabled = ...
        false;

    result.Applied = ...
        false;

    result.ConfigFile = ...
        "";

    result.ApplyMode = ...
        "";

    result.AuditFile = ...
        "";

    result.VerificationPassed = ...
        true;

    result.ApplicationResult = ...
        [];
end


function localAssertOutputsAbsent( ...
        paths, soPaths, executeBodyKinematics, ...
        writeQc, saveCheckpoint, forceConfigWillApply)

    outputFiles = [
        string(paths.ModelCFile)
    ];

    if writeQc

        outputFiles = [
            outputFiles
            string(paths.CoordinateConfigurationCsv)
            string(paths.ConstraintConfigurationCsv)
        ];

        if forceConfigWillApply

            outputFiles(end+1,1) = ...
                string(paths.ForceConfigAuditCsv);
        end
    end

    if executeBodyKinematics

        outputFiles = [
            outputFiles
            string(paths.BodyKinematics.SetupFile)
            string(paths.HeadSupportForce.MotionFile)
            string(paths.HeadSupportForce.ExternalLoadsFile)
            string(soPaths.SetupFile)
        ];

        if writeQc

            outputFiles = [
                outputFiles
                string(paths.BodyKinematics.RawComCsv)
                string(paths.BodyKinematics.ResampledComCsv)
                string(paths.BodyKinematics.ComSummaryCsv)
                string(paths.HeadSupportForce.EventDetectionSummaryCsv)
                string(paths.HeadSupportForce.EventDetectionPlot)
                string(paths.HeadSupportForce.SummaryCsv)
                string(paths.HeadSupportForce.SupportEnvelopeCsv)
            ];
        end

        if saveCheckpoint

            outputFiles(end+1,1) = ...
                string(paths.CheckpointFile);
        end
    end

    existingFiles = ...
        outputFiles(isfile(outputFiles));

    if ~isempty(existingFiles)

        error( ...
            "PipelineSOPrep:OutputExists", ...
            "Process-3 output already exists and Overwrite=false:\n%s", ...
            strjoin(existingFiles, newline));
    end
end


function comTable = localComToTable(com)

    requiredFields = [
        "Time"
        "X"
        "Y"
        "Z"
    ];

    assert(all(isfield( ...
            com, ...
            cellstr(requiredFields))), ...
        "PipelineSOPrep:InvalidComStructure", ...
        "CoM structure must contain Time, X, Y, and Z.");

    comTable = table( ...
        double(com.Time(:)), ...
        double(com.X(:)), ...
        double(com.Y(:)), ...
        double(com.Z(:)), ...
        'VariableNames', { ...
            'time', ...
            'x', ...
            'y', ...
            'z'});
end


function localValidateComTable(comTable, label)

    assert(height(comTable) >= 2, ...
        "PipelineSOPrep:ComTooShort", ...
        "%s contains fewer than two samples.", ...
        label);

    values = [
        comTable.time
        comTable.x
        comTable.y
        comTable.z
    ];

    assert(all(isfinite(values), "all"), ...
        "PipelineSOPrep:ComNonfinite", ...
        "%s contains nonfinite values.", ...
        label);

    assert(all(diff(comTable.time) > 0), ...
        "PipelineSOPrep:ComTimeNotIncreasing", ...
        "%s time is not strictly increasing.", ...
        label);
end


function summary = ...
        localSummarizeCom( ...
            comTable, stage)

    dt = ...
        diff(comTable.time);

    if isempty(dt)

        estimatedRateHz = ...
            NaN;

    else

        estimatedRateHz = ...
            1 / median(dt);
    end

    summary = table( ...
        string(stage), ...
        height(comTable), ...
        comTable.time(1), ...
        comTable.time(end), ...
        estimatedRateHz, ...
        min(comTable.x), ...
        max(comTable.x), ...
        min(comTable.y), ...
        max(comTable.y), ...
        min(comTable.z), ...
        max(comTable.z), ...
        'VariableNames', { ...
            'Stage', ...
            'NumSamples', ...
            'StartTime', ...
            'EndTime', ...
            'EstimatedRateHz', ...
            'XMin', ...
            'XMax', ...
            'YMin', ...
            'YMax', ...
            'ZMin', ...
            'ZMax'});
end


function compact = ...
        localCompactEventDetectionResult(eventResult)
%LOCALCOMPACTEVENTDETECTIONRESULT Remove graphics handles from checkpoint.

    compact = ...
        eventResult;

    if isfield(compact, "Figure")
        compact.Figure = [];
    end
end


function compact = ...
        localCompactHsfResult(hsfResult)
%LOCALCOMPACTHSFRESULT Avoid duplicating the full 1000-Hz motion in MAT QC.
%
% The HSF MOT is already written as the authoritative trajectory. The
% checkpoint retains the parameters, summary, validation, force components,
% envelope, and lift-off window needed for traceability.

    compact = ...
        hsfResult;

    if isfield(compact, "Motion")
        compact = ...
            rmfield( ...
                compact, ...
                "Motion");
    end
end


function result = localMakeResult( ...
        trial, ...
        paths, ...
        soPaths, ...
        trialTimeRangeSec, ...
        modelCResult, ...
        modelCValidation, ...
        sagittalState, ...
        forceCapacityConfigResult, ...
        bodyKinematicsResult, ...
        comSummary, ...
        eventDetectionResult, ...
        hsfParameters, ...
        gndrollResult, ...
        hsfResult, ...
        externalLoadsResult, ...
        staticOptimizationSetupResult, ...
        checkpointFile, ...
        completed, ...
        durationSeconds)

    result = struct;

    result.Stage = ...
        "static_optimization_prep";

    result.Trial = ...
        trial;

    result.Paths = ...
        paths;

    result.StaticOptimizationPaths = ...
        soPaths;

    result.TrialTimeRangeSec = ...
        trialTimeRangeSec;

    result.ModelCResult = ...
        modelCResult;

    result.ModelCValidation = ...
        modelCValidation;

    result.SagittalState = ...
        sagittalState;

    result.ForceCapacityConfigResult = ...
        forceCapacityConfigResult;

    result.BodyKinematicsResult = ...
        bodyKinematicsResult;

    result.ComSummary = ...
        comSummary;

    result.EventDetectionResult = ...
        eventDetectionResult;

    result.HsfParameters = ...
        hsfParameters;

    result.GndrollResult = ...
        gndrollResult;

    result.HsfResult = ...
        hsfResult;

    result.ExternalLoadsResult = ...
        externalLoadsResult;

    result.StaticOptimizationSetupResult = ...
        staticOptimizationSetupResult;

    result.CheckpointFile = ...
        string(checkpointFile);

    result.Completed = ...
        logical(completed);

    result.DurationSeconds = ...
        double(durationSeconds);
end
