function result = prepareStaticOptimizationSharedTrial( ...
        projectCfg, trial, varargin)
%PREPARESTATICOPTIMIZATIONSHAREDTRIAL Prepare/reuse strength-neutral SO inputs.
%
% result = pipeline.prepareStaticOptimizationSharedTrial(projectCfg, trial)
%
% This worker owns the expensive Process-3 computations that depend only on
% Process-2 kinematics and shared project settings:
%
%   * neutral Model C construction/validation
%   * Body Kinematics
%   * raw/resampled skull CoM
%   * lift-off and re-contact detection
%   * gndroll extraction
%   * head-support-force generation
%   * ExternalLoads generation
%
% The existing canonical Process-3 worker is used to populate the shared
% cache so that this refactor preserves the established numerical path.
%
% A valid existing cache is reused automatically. The cache is rebuilt when:
%   * ForceRebuild is true;
%   * required shared outputs are missing;
%   * a Process-2/model/IK/ExternalLoads input is newer than the cache; or
%   * key Body-Kinematics/event/HSF configuration differs.
%
% NAME-VALUE OPTIONS
%
%   ForceRebuild
%       false (default). Force regeneration of the shared cache.
%
%   WriteQc
%       true (default).
%
%   EventFigureVisible
%       "off" (default) or "on".
%
%   PrintProgress
%       true (default).

    assert(isstruct(projectCfg) && isscalar(projectCfg), ...
        "SharedSOPrep:InvalidProjectConfig", ...
        "projectCfg must be a scalar struct.");

    localValidateTrial(trial);

    parser = ...
        inputParser;

    parser.FunctionName = ...
        "pipeline.prepareStaticOptimizationSharedTrial";

    addParameter(parser, ...
        "ForceRebuild", ...
        false, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "WriteQc", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "EventFigureVisible", ...
        "off", ...
        @(x) any(strcmpi(string(x), ["on","off"])));

    addParameter(parser, ...
        "PrintProgress", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, varargin{:});

    forceRebuild = ...
        logical(parser.Results.ForceRebuild);

    writeQc = ...
        logical(parser.Results.WriteQc);

    eventFigureVisible = ...
        lower(string(parser.Results.EventFigureVisible));

    printProgress = ...
        logical(parser.Results.PrintProgress);

    [sharedTrial, sharedCfg] = ...
        pipeline.resolveStaticOptimizationSharedTrialContext( ...
            projectCfg, ...
            trial.ConditionDeg, ...
            trial.TrialNumber);

    checkpointFile = ...
        string( ...
            sharedTrial.Paths.StaticOptimizationPrep.CheckpointFile);

    if ~forceRebuild && ...
            isfile(checkpointFile)

        [cacheValid, cacheReason, checkpoint] = ...
            localValidateExistingCache( ...
                projectCfg, ...
                sharedTrial, ...
                checkpointFile);

        if cacheValid

            result = ...
                localResultFromCheckpoint( ...
                    sharedTrial, ...
                    sharedCfg, ...
                    checkpoint);

            result.ReusedExisting = ...
                true;

            result.CacheValidationReason = ...
                cacheReason;

            if printProgress

                fprintf( ...
                    "Shared SO preparation reused for %s.\n" + ...
                    "Checkpoint:\n%s\n", ...
                    trial.DisplayName, ...
                    checkpointFile);
            end

            return;
        end

        if printProgress

            fprintf( ...
                "Shared SO preparation cache is stale for %s: %s\n" + ...
                "Rebuilding shared preprocessing.\n", ...
                trial.DisplayName, ...
                cacheReason);
        end
    end

    if printProgress

        fprintf( ...
            "\n=== Shared SO preparation: %s ===\n", ...
            trial.DisplayName);

        fprintf( ...
            "Shared output directory:\n%s\n", ...
            sharedTrial.Paths.StaticOptimizationPrep.Directory);
    end

    heavyResult = ...
        pipeline.prepareStaticOptimizationTrial( ...
            sharedCfg, ...
            sharedTrial, ...
            "ExecuteBodyKinematics", ...
                true, ...
            "Overwrite", ...
                true, ...
            "WriteQc", ...
                writeQc, ...
            "SaveCheckpoint", ...
                true, ...
            "EventFigureVisible", ...
                eventFigureVisible, ...
            "PrintProgress", ...
                printProgress);

    assert(heavyResult.Completed, ...
        "SharedSOPrep:HeavyPreparationIncomplete", ...
        "Strength-neutral shared SO preparation did not complete.");

    result = ...
        heavyResult;

    result.Stage = ...
        "static_optimization_shared_prep";

    result.SharedCfg = ...
        sharedCfg;

    result.SharedTrial = ...
        sharedTrial;

    result.ReusedExisting = ...
        false;

    result.CacheValidationReason = ...
        "rebuilt";
end


function [valid, reason, checkpoint] = ...
        localValidateExistingCache( ...
            projectCfg, sharedTrial, checkpointFile)

    valid = ...
        false;

    reason = ...
        ""; %#ok<*NASGU>

    checkpoint = ...
        struct;

    try

        loaded = ...
            load( ...
                checkpointFile, ...
                "checkpoint");

        if ~isfield(loaded, "checkpoint")

            reason = ...
                "checkpoint variable missing";

            return;
        end

        checkpoint = ...
            loaded.checkpoint;

        requiredFields = [
            "Stage"
            "Trial"
            "Configuration"
            "ModelCValidation"
            "ForceCapacityConfigResult"
            "HsfResult"
            "ExternalLoadsResult"
            "Completed"
        ];

        if ~all(isfield( ...
                checkpoint, ...
                cellstr(requiredFields)))

            reason = ...
                "checkpoint schema incomplete";

            return;
        end

        if ~logical(checkpoint.Completed)

            reason = ...
                "checkpoint is incomplete";

            return;
        end

        if string(checkpoint.Stage) ~= ...
                "static_optimization_prep"

            reason = ...
                "unexpected checkpoint stage";

            return;
        end

        if checkpoint.Trial.ConditionDeg ~= ...
                sharedTrial.ConditionDeg || ...
                checkpoint.Trial.TrialNumber ~= ...
                sharedTrial.TrialNumber

            reason = ...
                "trial identity changed";

            return;
        end

        if isfield( ...
                checkpoint.ForceCapacityConfigResult, ...
                "Applied") && ...
                logical( ...
                    checkpoint.ForceCapacityConfigResult.Applied)

            reason = ...
                "cached Model C is not strength-neutral";

            return;
        end

        if ~logical(checkpoint.ModelCValidation.Passed)

            reason = ...
                "cached Model C validation failed";

            return;
        end

        if ~isfield(checkpoint.HsfResult, "Validation") || ...
                ~logical(checkpoint.HsfResult.Validation.Passed)

            reason = ...
                "cached HSF validation failed";

            return;
        end

        if ~logical( ...
                checkpoint.ExternalLoadsResult.VerificationPassed)

            reason = ...
                "cached ExternalLoads verification failed";

            return;
        end

        requiredFiles = [
            string(sharedTrial.Paths.StaticOptimizationPrep.ModelCFile)
            string(sharedTrial.Paths.StaticOptimizationPrep.CheckpointFile)
            string(sharedTrial.Paths.StaticOptimizationPrep. ...
                BodyKinematics.RawComCsv)
            string(sharedTrial.Paths.StaticOptimizationPrep. ...
                BodyKinematics.ResampledComCsv)
            string(sharedTrial.Paths.StaticOptimizationPrep. ...
                HeadSupportForce.MotionFile)
            string(sharedTrial.Paths.StaticOptimizationPrep. ...
                HeadSupportForce.ExternalLoadsFile)
        ];

        if any(~isfile(requiredFiles))

            reason = ...
                "one or more shared artifacts are missing";

            return;
        end

        sourceFiles = [
            string(sharedTrial.Paths.ModelB.CheckpointFile)
            string(sharedTrial.Paths.ModelB.ModelBFile)
            string(sharedTrial.Paths.ModelB.FinalIkMotionFile)
            string(sharedTrial.Inputs.ExternalLoadsTemplate)
        ];

        if any(~isfile(sourceFiles))

            reason = ...
                "one or more shared source inputs are missing";

            return;
        end

        checkpointInfo = ...
            dir(checkpointFile);

        checkpointDatenum = ...
            checkpointInfo.datenum;

        for iFile = 1:numel(sourceFiles)

            sourceInfo = ...
                dir(sourceFiles(iFile));

            if sourceInfo.datenum > ...
                    checkpointDatenum

                reason = ...
                    "Process-2 or ExternalLoads input is newer than cache";

                return;
            end
        end

        prepCfg = ...
            projectCfg.pipeline.staticOptimizationPrep;

        if ~isequaln( ...
                double(checkpoint.Configuration. ...
                    BodyKinematicsLowpassCutoffHz), ...
                double(prepCfg.bodyKinematicsLowpassCutoffHz))

            reason = ...
                "Body Kinematics cutoff changed";

            return;
        end

        if ~isequaln( ...
                checkpoint.Configuration.HsfEventDetection, ...
                projectCfg.qc.hsfEventDetection)

            reason = ...
                "event-detection configuration changed";

            return;
        end

        cachedHsf = ...
            checkpoint.Configuration.HsfParameters;

        currentHsf = ...
            projectCfg.hsf.Parameters;

        if logical(projectCfg.hsf.useModelBodyMass)

            if isfield(cachedHsf, "SkullMassKg")
                cachedHsf = rmfield(cachedHsf, "SkullMassKg");
            end

            if isfield(currentHsf, "SkullMassKg")
                currentHsf = rmfield(currentHsf, "SkullMassKg");
            end
        end

        if ~isequaln(cachedHsf, currentHsf)

            reason = ...
                "HSF parameter configuration changed";

            return;
        end

        valid = ...
            true;

        reason = ...
            "valid existing shared cache";

    catch exception

        valid = ...
            false;

        reason = ...
            "cache validation error: " + ...
            string(exception.message);
    end
end


function result = ...
        localResultFromCheckpoint( ...
            sharedTrial, sharedCfg, checkpoint)

    result = ...
        struct;

    result.Stage = ...
        "static_optimization_shared_prep";

    result.Trial = ...
        sharedTrial;

    result.Paths = ...
        sharedTrial.Paths.StaticOptimizationPrep;

    result.StaticOptimizationPaths = ...
        sharedTrial.Paths.StaticOptimization;

    result.TrialTimeRangeSec = ...
        checkpoint.Configuration.TrialTimeRangeSec;

    result.ModelCResult = ...
        localFieldOrDefault( ...
            checkpoint, ...
            "ModelCResult", ...
            struct);

    result.ModelCValidation = ...
        checkpoint.ModelCValidation;

    result.SagittalState = ...
        localFieldOrDefault( ...
            checkpoint, ...
            "SagittalState", ...
            table);

    result.ForceCapacityConfigResult = ...
        checkpoint.ForceCapacityConfigResult;

    result.BodyKinematicsResult = ...
        localFieldOrDefault( ...
            checkpoint, ...
            "BodyKinematicsResult", ...
            struct);

    result.ComSummary = ...
        localFieldOrDefault( ...
            checkpoint, ...
            "ComSummary", ...
            table);

    result.EventDetectionResult = ...
        localFieldOrDefault( ...
            checkpoint, ...
            "EventDetectionResult", ...
            struct);

    result.HsfParameters = ...
        checkpoint.Configuration.HsfParameters;

    result.GndrollResult = ...
        localFieldOrDefault( ...
            checkpoint, ...
            "GndrollResult", ...
            struct);

    result.HsfResult = ...
        checkpoint.HsfResult;

    result.ExternalLoadsResult = ...
        checkpoint.ExternalLoadsResult;

    result.StaticOptimizationSetupResult = ...
        localFieldOrDefault( ...
            checkpoint, ...
            "StaticOptimizationSetupResult", ...
            struct);

    result.CheckpointFile = ...
        sharedTrial.Paths.StaticOptimizationPrep.CheckpointFile;

    result.Completed = ...
        true;

    result.DurationSeconds = ...
        0;

    result.SharedCfg = ...
        sharedCfg;

    result.SharedTrial = ...
        sharedTrial;
end


function value = ...
        localFieldOrDefault(s, fieldName, defaultValue)

    if isfield(s, fieldName)

        value = ...
            s.(fieldName);

    else

        value = ...
            defaultValue;
    end
end


function localValidateTrial(trial)

    requiredFields = [
        "ConditionDeg"
        "TrialNumber"
        "DisplayName"
    ];

    assert(isstruct(trial) && ...
        all(isfield(trial, cellstr(requiredFields))), ...
        "SharedSOPrep:InvalidTrialContext", ...
        "trial must contain ConditionDeg, TrialNumber, and DisplayName.");
end
