function result = prepareStaticOptimizationConfigurationTrial( ...
        projectCfg, trial, varargin)
%PREPARESTATICOPTIMIZATIONCONFIGURATIONTRIAL Lightweight strength-specific P3.
%
% result = pipeline.prepareStaticOptimizationConfigurationTrial( ...
%     projectCfg, trial)
%
% Uses a shared strength-neutral SO-preparation cache and performs only the
% operations that truly depend on the selected force-capacity configuration:
%
%   1. copy the shared neutral Model C;
%   2. apply the selected muscle/actuator capacities;
%   3. generate the configuration-specific SO setup XML;
%   4. write a compact Process-3 checkpoint.
%
% Body Kinematics, skull CoM, event detection, HSF, and ExternalLoads are
% reused from pipeline.prepareStaticOptimizationSharedTrial.
%
% The compact checkpoint intentionally preserves the fields currently
% required by pipeline.runStaticOptimizationTrial.
%
% NAME-VALUE OPTIONS
%
%   Overwrite
%       Defaults to projectCfg.overwriteExisting.
%
%   ForceRebuildShared
%       false (default).
%
%   WriteQc
%       true (default).
%
%   SaveCheckpoint
%       true (default).
%
%   EventFigureVisible
%       "off" (default). Used only if the shared cache must be built.
%
%   PrintProgress
%       true (default).

    assert(isstruct(projectCfg) && isscalar(projectCfg), ...
        "PipelineSOConfigPrep:InvalidProjectConfig", ...
        "projectCfg must be a scalar struct.");

    localValidateTrial(trial);

    assert(isfield(projectCfg, "forceCapacity") && ...
        isstruct(projectCfg.forceCapacity) && ...
        isfield(projectCfg.forceCapacity, "enabled") && ...
        logical(projectCfg.forceCapacity.enabled), ...
        "PipelineSOConfigPrep:ForceCapacityDisabled", ...
        "Configuration-specific SO preparation requires forceCapacity.enabled=true.");

    assert(localShouldApplyForceConfig( ...
            projectCfg, ...
            "modelC"), ...
        "PipelineSOConfigPrep:ModelCForceConfigDisabled", ...
        "The enabled force-capacity configuration is not configured to " + ...
        "apply at Model C.");

    defaultOverwrite = ...
        false;

    if isfield(projectCfg, "overwriteExisting")

        defaultOverwrite = ...
            logical(projectCfg.overwriteExisting);
    end

    parser = ...
        inputParser;

    parser.FunctionName = ...
        "pipeline.prepareStaticOptimizationConfigurationTrial";

    addParameter(parser, ...
        "Overwrite", ...
        defaultOverwrite, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "ForceRebuildShared", ...
        false, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "WriteQc", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "SaveCheckpoint", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "EventFigureVisible", ...
        "off", ...
        @(x) any(strcmpi(string(x), ["on","off"])));

    addParameter(parser, ...
        "PrintProgress", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, varargin{:});

    overwrite = ...
        logical(parser.Results.Overwrite);

    forceRebuildShared = ...
        logical(parser.Results.ForceRebuildShared);

    writeQc = ...
        logical(parser.Results.WriteQc);

    saveCheckpoint = ...
        logical(parser.Results.SaveCheckpoint);

    eventFigureVisible = ...
        lower(string(parser.Results.EventFigureVisible));

    printProgress = ...
        logical(parser.Results.PrintProgress);

    stageStart = ...
        tic;

    paths = ...
        trial.Paths.StaticOptimizationPrep;

    soPaths = ...
        trial.Paths.StaticOptimization;

    modelBPaths = ...
        trial.Paths.ModelB;

    localEnsureDirectory(paths.Directory);
    localEnsureDirectory(paths.QcDirectory);
    localEnsureDirectory(soPaths.Directory);
    localEnsureDirectory(soPaths.ResultsDirectory);
    localEnsureDirectory(soPaths.QcDirectory);

    if ~overwrite

        outputFiles = [
            string(paths.ModelCFile)
            string(paths.CheckpointFile)
            string(soPaths.SetupFile)
        ];

        if writeQc

            outputFiles(end+1,1) = ...
                string(paths.ForceConfigAuditCsv);
        end

        existingFiles = ...
            outputFiles(isfile(outputFiles));

        if ~isempty(existingFiles)

            error( ...
                "PipelineSOConfigPrep:OutputExists", ...
                "Configuration-specific Process-3 output already exists " + ...
                "and Overwrite=false:\n%s", ...
                strjoin(existingFiles, newline));
        end
    end

    if printProgress

        fprintf( ...
            "\n=== Configuration-specific Process 3: %s ===\n", ...
            trial.DisplayName);

        fprintf( ...
            "Strength configuration: %s\n", ...
            string(trial.StrengthConfigId));
    end

    %% Ensure/reuse shared kinematic preparation

    sharedResult = ...
        pipeline.prepareStaticOptimizationSharedTrial( ...
            projectCfg, ...
            trial, ...
            "ForceRebuild", ...
                forceRebuildShared, ...
            "WriteQc", ...
                writeQc, ...
            "EventFigureVisible", ...
                eventFigureVisible, ...
            "PrintProgress", ...
                printProgress);

    assert(sharedResult.Completed, ...
        "PipelineSOConfigPrep:SharedPreparationIncomplete", ...
        "Shared SO preparation is incomplete.");

    sharedPaths = ...
        sharedResult.Trial.Paths.StaticOptimizationPrep;

    assert(isfile(sharedPaths.ModelCFile), ...
        "PipelineSOConfigPrep:SharedModelMissing", ...
        "Shared neutral Model C was not found:\n%s", ...
        sharedPaths.ModelCFile);

    assert(isfile( ...
            sharedPaths.HeadSupportForce.ExternalLoadsFile), ...
        "PipelineSOConfigPrep:SharedExternalLoadsMissing", ...
        "Shared ExternalLoads XML was not found:\n%s", ...
        sharedPaths.HeadSupportForce.ExternalLoadsFile);

    %% Copy neutral Model C into configuration-specific directory

    if overwrite && ...
            isfile(paths.ModelCFile)

        delete(paths.ModelCFile);
    end

    [copyPassed, copyMessage] = ...
        copyfile( ...
            sharedPaths.ModelCFile, ...
            paths.ModelCFile);

    assert(copyPassed, ...
        "PipelineSOConfigPrep:ModelCopyFailed", ...
        "Could not copy shared Model C into the configuration directory:\n%s", ...
        string(copyMessage));

    %% Apply selected force capacities

    forceCapacityConfigResult = ...
        modelprep.applyConfiguredForceCapacitiesIfEnabled( ...
            paths.ModelCFile, ...
            projectCfg, ...
            "StageName", ...
                "Model C", ...
            "AuditFile", ...
                paths.ForceConfigAuditCsv);

    assert(forceCapacityConfigResult.Applied, ...
        "PipelineSOConfigPrep:ForceConfigNotApplied", ...
        "The selected force-capacity configuration was not applied.");

    assert(forceCapacityConfigResult.VerificationPassed, ...
        "PipelineSOConfigPrep:ForceConfigVerificationFailed", ...
        "Applied force-capacity configuration failed verification.");

    %% Generate configuration-specific SO setup using shared ExternalLoads

    staticOptimizationSetupResult = ...
        opensimrun.prepareStaticOptimizationSetup( ...
            trial.Inputs.StaticOptimizationTemplate, ...
            soPaths.SetupFile, ...
            "ModelFile", ...
                paths.ModelCFile, ...
            "CoordinatesFile", ...
                modelBPaths.FinalIkMotionFile, ...
            "ExternalLoadsFile", ...
                sharedPaths.HeadSupportForce.ExternalLoadsFile, ...
            "ResultsDirectory", ...
                soPaths.ResultsDirectory, ...
            "TimeRange", ...
                sharedResult.TrialTimeRangeSec, ...
            "ToolName", ...
                "SO_" + trial.TrialStem, ...
            "Overwrite", ...
                overwrite);

    assert( ...
        staticOptimizationSetupResult.VerificationPassed, ...
        "PipelineSOConfigPrep:StaticOptimizationSetupVerificationFailed", ...
        "Generated Static Optimization setup failed verification.");

    %% Save compact configuration-specific Process-3 checkpoint

    checkpointFile = ...
        "";

    if saveCheckpoint

        checkpoint = ...
            struct;

        checkpoint.SchemaVersion = ...
            2;

        checkpoint.Stage = ...
            "static_optimization_prep";

        checkpoint.Trial = ...
            trial;

        checkpoint.Configuration = ...
            struct( ...
                "TrialTimeRangeSec", ...
                    sharedResult.TrialTimeRangeSec, ...
                "UsesSharedPreparation", ...
                    true, ...
                "SharedPreparationCheckpointFile", ...
                    string(sharedResult.CheckpointFile));

        checkpoint.Paths = ...
            paths;

        checkpoint.StaticOptimizationPaths = ...
            soPaths;

        checkpoint.ModelBCheckpointFile = ...
            modelBPaths.CheckpointFile;

        checkpoint.SharedPreparationCheckpointFile = ...
            string(sharedResult.CheckpointFile);

        checkpoint.ModelCValidation = ...
            sharedResult.ModelCValidation;

        checkpoint.ForceCapacityConfigResult = ...
            forceCapacityConfigResult;

        checkpoint.HsfResult = ...
            localCompactHsfValidation( ...
                sharedResult.HsfResult);

        checkpoint.ExternalLoadsResult = ...
            localCompactExternalLoadsResult( ...
                sharedResult.ExternalLoadsResult, ...
                sharedPaths.HeadSupportForce.ExternalLoadsFile);

        checkpoint.StaticOptimizationSetupResult = ...
            localCompactSetupResult( ...
                staticOptimizationSetupResult, ...
                soPaths.SetupFile);

        checkpoint.Completed = ...
            true;

        checkpoint.CompletedAt = ...
            string(datetime("now"));

        save( ...
            paths.CheckpointFile, ...
            "checkpoint");

        checkpointFile = ...
            paths.CheckpointFile;
    end

    %% Return compatibility result

    result = ...
        struct;

    result.Stage = ...
        "static_optimization_prep";

    result.Trial = ...
        trial;

    result.Paths = ...
        paths;

    result.StaticOptimizationPaths = ...
        soPaths;

    result.SharedPaths = ...
        sharedPaths;

    result.SharedPreparationCheckpointFile = ...
        string(sharedResult.CheckpointFile);

    result.SharedPreparationReused = ...
        logical(sharedResult.ReusedExisting);

    result.TrialTimeRangeSec = ...
        sharedResult.TrialTimeRangeSec;

    result.ModelCResult = ...
        sharedResult.ModelCResult;

    result.ModelCValidation = ...
        sharedResult.ModelCValidation;

    result.SagittalState = ...
        sharedResult.SagittalState;

    result.ForceCapacityConfigResult = ...
        forceCapacityConfigResult;

    result.BodyKinematicsResult = ...
        sharedResult.BodyKinematicsResult;

    result.ComSummary = ...
        sharedResult.ComSummary;

    result.EventDetectionResult = ...
        sharedResult.EventDetectionResult;

    result.HsfParameters = ...
        sharedResult.HsfParameters;

    result.GndrollResult = ...
        sharedResult.GndrollResult;

    result.HsfResult = ...
        sharedResult.HsfResult;

    result.ExternalLoadsResult = ...
        sharedResult.ExternalLoadsResult;

    result.StaticOptimizationSetupResult = ...
        staticOptimizationSetupResult;

    result.CheckpointFile = ...
        checkpointFile;

    result.Completed = ...
        true;

    result.DurationSeconds = ...
        toc(stageStart);

    if printProgress

        fprintf( ...
            "Configuration-specific Process 3 completed in %.3f s.\n" + ...
            "Shared preparation reused: %d\n" + ...
            "Model C:\n%s\n" + ...
            "Shared HSF:\n%s\n" + ...
            "SO setup:\n%s\n", ...
            result.DurationSeconds, ...
            result.SharedPreparationReused, ...
            paths.ModelCFile, ...
            sharedPaths.HeadSupportForce.MotionFile, ...
            soPaths.SetupFile);
    end
end


function compact = ...
        localCompactHsfValidation(hsfResult)

    compact = ...
        struct;

    compact.Validation = ...
        hsfResult.Validation;
end


function compact = ...
        localCompactExternalLoadsResult( ...
            externalLoadsResult, externalLoadsFile)

    compact = ...
        struct;

    compact.VerificationPassed = ...
        logical(externalLoadsResult.VerificationPassed);

    compact.OutputFile = ...
        string(externalLoadsFile);
end


function compact = ...
        localCompactSetupResult(setupResult, setupFile)

    compact = ...
        struct;

    compact.VerificationPassed = ...
        logical(setupResult.VerificationPassed);

    compact.OutputFile = ...
        string(setupFile);
end


function apply = ...
        localShouldApplyForceConfig( ...
            projectCfg, stageName)

    apply = ...
        false;

    cfg = ...
        projectCfg.forceCapacity;

    if ~logical(cfg.enabled)

        return;
    end

    if ~isfield(cfg, "applyStages")

        apply = ...
            true;

        return;
    end

    stages = ...
        lower(string(cfg.applyStages(:)));

    apply = ...
        any(stages == lower(string(stageName)));
end


function localEnsureDirectory(directory)

    directory = ...
        string(directory);

    if ~isfolder(directory)

        mkdir(directory);
    end
end


function localValidateTrial(trial)

    requiredFields = [
        "ConditionDeg"
        "TrialNumber"
        "TrialStem"
        "DisplayName"
        "Inputs"
        "Paths"
        "StrengthConfigEnabled"
        "StrengthConfigId"
    ];

    assert(isstruct(trial) && ...
        all(isfield(trial, cellstr(requiredFields))), ...
        "PipelineSOConfigPrep:InvalidTrialContext", ...
        "trial is missing required configuration-specific fields.");

    assert(logical(trial.StrengthConfigEnabled), ...
        "PipelineSOConfigPrep:StrengthTrialRequired", ...
        "A strength-configuration trial context is required.");
end
