function context = resolveStaticOptimizationAnalysisContext( ...
        projectCfg, varargin)
%RESOLVESTATICOPTIMIZATIONANALYSISCONTEXT Resolve one SO analysis dataset.
%
% context = pipeline.resolveStaticOptimizationAnalysisContext(projectCfg)
%
% Resolves the user-selected Static Optimization result namespace
% independently of projectCfg.forceCapacity. This function does not create
% directories or modify projectCfg.
%
% Selection settings:
%   projectCfg.analysis.staticOptimization.selection
%
% Modes:
%   "prompt" - discover eligible configurations and show a sortable table UI.
%   "config" - resolve selection.configId exactly.
%   "legacy" - resolve the historical unconfigured output tree.
%
% Optional name-value inputs:
%   "ConfigurationSummary" - precomputed summary table equivalent to
%       soopt.summarizeStrengthConfigurations(projectCfg).
%   "PromptSelectionIndex" - deterministic prompt choice for tests/headless
%       regression. Normal interactive use leaves this empty.

    %% Validate project configuration

    assert(isstruct(projectCfg) && isscalar(projectCfg), ...
        "SOAnalysisContext:InvalidProjectConfig", ...
        "projectCfg must be a scalar struct.");

    requiredTopFields = ["outputRoot"; "analysis"];

    missingTopFields = requiredTopFields( ...
        ~isfield(projectCfg, cellstr(requiredTopFields)));

    assert(isempty(missingTopFields), ...
        "SOAnalysisContext:ProjectConfigFieldsMissing", ...
        "projectCfg is missing required fields: %s", ...
        strjoin(missingTopFields, ", "));

    outputRoot = string(projectCfg.outputRoot);

    assert(isscalar(outputRoot) && ~ismissing(outputRoot) && ...
            strlength(outputRoot) > 0, ...
        "SOAnalysisContext:InvalidOutputRoot", ...
        "projectCfg.outputRoot must be a nonempty scalar path.");

    assert(isfolder(outputRoot), ...
        "SOAnalysisContext:OutputRootNotFound", ...
        "Project output root was not found:\n%s", ...
        outputRoot);

    assert(isstruct(projectCfg.analysis) && ...
            isscalar(projectCfg.analysis) && ...
            isfield(projectCfg.analysis, "staticOptimization"), ...
        "SOAnalysisContext:StaticOptimizationConfigMissing", ...
        "projectCfg.analysis.staticOptimization is required.");

    analysisCfg = projectCfg.analysis.staticOptimization;

    assert(isstruct(analysisCfg) && isscalar(analysisCfg) && ...
            isfield(analysisCfg, "selection"), ...
        "SOAnalysisContext:SelectionConfigMissing", ...
        "projectCfg.analysis.staticOptimization.selection is required.");

    selection = localValidateSelectionConfig(analysisCfg.selection);

    %% Parse optional controls

    parser = inputParser;
    parser.FunctionName = ...
        "pipeline.resolveStaticOptimizationAnalysisContext";

    addParameter(parser, ...
        "ConfigurationSummary", ...
        [], ...
        @(x) isempty(x) || istable(x));

    addParameter(parser, ...
        "PromptSelectionIndex", ...
        [], ...
        @(x) isempty(x) || ...
            (isnumeric(x) && isscalar(x) && isfinite(x) && ...
            x >= 1 && mod(x,1) == 0));

    parse(parser, varargin{:});

    suppliedSummary = parser.Results.ConfigurationSummary;
    promptSelectionIndex = parser.Results.PromptSelectionIndex;

    requestedMode = selection.Mode;

    legacyAvailable = localLegacyResultsExist(outputRoot);

    eligibleConfigurations = table;

    if requestedMode == "legacy"

        assert(legacyAvailable, ...
            "SOAnalysisContext:LegacyResultsNotFound", ...
            "Legacy Static Optimization results were not found directly " + ...
            "beneath projectCfg.outputRoot:\n%s", ...
            outputRoot);

        context = localLegacyContext( ...
            outputRoot, ...
            requestedMode, ...
            legacyAvailable, ...
            eligibleConfigurations, ...
            selection);

        return;
    end

    %% Obtain configuration-level feasibility summary

    if istable(suppliedSummary)
        summary = suppliedSummary;
    else
        summary = soopt.summarizeStrengthConfigurations(projectCfg);
    end

    localValidateConfigurationSummary(summary);

    %% Explicit config mode

    if requestedMode == "config"

        match = string(summary.ConfigId) == selection.ConfigId;

        assert(nnz(match) == 1, ...
            "SOAnalysisContext:ConfigNotFound", ...
            "Static Optimization analysis configuration '%s' was not " + ...
            "found beneath:\n%s", ...
            selection.ConfigId, ...
            fullfile(outputRoot, "static_optimization_configs"));

        selectedRow = summary(match,:);

        localRequireEligibleConfiguration(selectedRow, selection);

        context = localConfigurationContext( ...
            selectedRow, ...
            requestedMode, ...
            "config", ...
            legacyAvailable, ...
            selectedRow, ...
            selection);

        return;
    end

    assert(requestedMode == "prompt", ...
        "SOAnalysisContext:UnsupportedSelectionMode", ...
        "Unsupported Static Optimization analysis selection mode: %s", ...
        requestedMode);

    %% Prompt mode eligibility

    eligibleMask = true(height(summary),1);

    if selection.RequireAssessmentComplete
        eligibleMask = ...
            eligibleMask & logical(summary.AssessmentComplete);
    end

    if selection.RequireFeasible
        eligibleMask = ...
            eligibleMask & logical(summary.IsFeasible);
    end

    eligibleConfigurations = summary(eligibleMask,:);

    if ~isempty(eligibleConfigurations)
        eligibleConfigurations = sortrows( ...
            eligibleConfigurations, ...
            {'MusclePercent','ActuatorPercent','ConfigId'});
    end

    choiceKinds = repmat( ...
        "config", ...
        height(eligibleConfigurations), ...
        1);

    choiceTable = localConfigurationChoiceTable( ...
        eligibleConfigurations);

    if selection.IncludeLegacyInPrompt && legacyAvailable
        choiceKinds(end+1,1) = "legacy";

        choiceTable(end+1,:) = { ...
            "LEGACY", ...
            NaN, ...
            NaN, ...
            "LEGACY" ...
        };
    end

    assert(height(choiceTable) > 0, ...
        "SOAnalysisContext:NoEligibleConfigurations", ...
        "No Static Optimization result sets satisfy the current selection " + ...
        "policy. requireAssessmentComplete=%d, requireFeasible=%d, " + ...
        "includeLegacyInPrompt=%d.", ...
        selection.RequireAssessmentComplete, ...
        selection.RequireFeasible, ...
        selection.IncludeLegacyInPrompt);

    %% Resolve prompt choice

    if height(choiceTable) == 1 && ...
            selection.AutoSelectSingleCandidate

        selectedIndex = 1;

    elseif ~isempty(promptSelectionIndex)

        assert(promptSelectionIndex <= height(choiceTable), ...
            "SOAnalysisContext:PromptSelectionIndexOutOfRange", ...
            "PromptSelectionIndex=%d exceeds the %d available choices.", ...
            promptSelectionIndex, ...
            height(choiceTable));

        selectedIndex = promptSelectionIndex;

    else

        assert(usejava("awt"), ...
            "SOAnalysisContext:InteractiveSelectionUnavailable", ...
            "Interactive prompt mode requires MATLAB graphical UI support. " + ...
            "Use selection.mode='config' for noninteractive analysis.");

        selectedIndex = localPromptConfigurationSelection( ...
            choiceTable);
    end

    if choiceKinds(selectedIndex) == "legacy"

        context = localLegacyContext( ...
            outputRoot, ...
            requestedMode, ...
            legacyAvailable, ...
            eligibleConfigurations, ...
            selection);

        return;
    end

    selectedRow = eligibleConfigurations(selectedIndex,:);

    context = localConfigurationContext( ...
        selectedRow, ...
        requestedMode, ...
        "config", ...
        legacyAvailable, ...
        eligibleConfigurations, ...
        selection);
end


function selection = localValidateSelectionConfig(selectionCfg)

    assert(isstruct(selectionCfg) && isscalar(selectionCfg), ...
        "SOAnalysisContext:InvalidSelectionConfig", ...
        "projectCfg.analysis.staticOptimization.selection must be a " + ...
        "scalar struct.");

    requiredFields = [ ...
        "mode"
        "configId"
        "requireAssessmentComplete"
        "requireFeasible"
        "includeLegacyInPrompt"
        "autoSelectSingleCandidate"
    ];

    missingFields = requiredFields( ...
        ~isfield(selectionCfg, cellstr(requiredFields)));

    assert(isempty(missingFields), ...
        "SOAnalysisContext:SelectionFieldsMissing", ...
        "Static Optimization analysis selection config is missing: %s", ...
        strjoin(missingFields, ", "));

    mode = lower(strtrim(string(selectionCfg.mode)));

    assert(isscalar(mode) && ~ismissing(mode) && ...
            ismember(mode, ["prompt","config","legacy"]), ...
        "SOAnalysisContext:InvalidSelectionMode", ...
        "selection.mode must be 'prompt', 'config', or 'legacy'.");

    configId = strtrim(string(selectionCfg.configId));

    assert(isscalar(configId) && ~ismissing(configId), ...
        "SOAnalysisContext:InvalidConfigId", ...
        "selection.configId must be a scalar string.");

    if mode == "config"
        assert(strlength(configId) > 0, ...
            "SOAnalysisContext:ConfigIdRequired", ...
            "selection.configId must be nonempty when selection.mode='config'.");

        info = pipeline.parseStrengthConfigName(configId + ".json");
        configId = info.ConfigId;
    end

    logicalFields = [ ...
        "requireAssessmentComplete"
        "requireFeasible"
        "includeLegacyInPrompt"
        "autoSelectSingleCandidate"
    ];

    for fieldName = logicalFields.'
        value = selectionCfg.(fieldName);

        assert(islogical(value) && isscalar(value), ...
            "SOAnalysisContext:InvalidLogicalSetting", ...
            "selection.%s must be a logical scalar.", ...
            fieldName);
    end

    selection = struct;
    selection.Mode = mode;
    selection.ConfigId = configId;
    selection.RequireAssessmentComplete = ...
        logical(selectionCfg.requireAssessmentComplete);
    selection.RequireFeasible = ...
        logical(selectionCfg.requireFeasible);
    selection.IncludeLegacyInPrompt = ...
        logical(selectionCfg.includeLegacyInPrompt);
    selection.AutoSelectSingleCandidate = ...
        logical(selectionCfg.autoSelectSingleCandidate);
end


function localValidateConfigurationSummary(summary)

    assert(istable(summary), ...
        "SOAnalysisContext:InvalidConfigurationSummary", ...
        "Configuration summary must be a table.");

    requiredVariables = [ ...
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
        "ConfigRoot"
        "AnalysisDirectory"
        "AssessmentComplete"
        "IsFeasible"
        "FeasibilityStatus"
        "FeasibilityReason"
    ];

    missingVariables = requiredVariables( ...
        ~ismember( ...
            requiredVariables, ...
            string(summary.Properties.VariableNames)));

    assert(isempty(missingVariables), ...
        "SOAnalysisContext:ConfigurationSummaryVariablesMissing", ...
        "Configuration summary is missing required variables: %s", ...
        strjoin(missingVariables, ", "));

    configIds = string(summary.ConfigId);

    assert(numel(unique(configIds)) == numel(configIds), ...
        "SOAnalysisContext:DuplicateConfigIds", ...
        "Configuration summary contains duplicate ConfigId values.");
end


function localRequireEligibleConfiguration(row, selection)

    assert(height(row) == 1, ...
        "SOAnalysisContext:InvalidSelectedRow", ...
        "Selected configuration must contain exactly one row.");

    if selection.RequireAssessmentComplete
        assert(logical(row.AssessmentComplete(1)), ...
            "SOAnalysisContext:AssessmentIncomplete", ...
            "Configuration '%s' cannot be selected because its assessment " + ...
            "is incomplete. Status: %s. Reason: %s", ...
            string(row.ConfigId(1)), ...
            string(row.FeasibilityStatus(1)), ...
            string(row.FeasibilityReason(1)));
    end

    if selection.RequireFeasible
        assert(logical(row.IsFeasible(1)), ...
            "SOAnalysisContext:ConfigurationInfeasible", ...
            "Configuration '%s' cannot be selected because it is not " + ...
            "feasible. Status: %s. Reason: %s", ...
            string(row.ConfigId(1)), ...
            string(row.FeasibilityStatus(1)), ...
            string(row.FeasibilityReason(1)));
    end
end


function choiceTable = localConfigurationChoiceTable(configurations)

    ConfigId = ...
        string(configurations.ConfigId);

    MusclePercent = ...
        double(configurations.MusclePercent);

    ActuatorPercent = ...
        double(configurations.ActuatorPercent);

    Status = ...
        string(configurations.FeasibilityStatus);

    choiceTable = table( ...
        ConfigId, ...
        MusclePercent, ...
        ActuatorPercent, ...
        Status);
end


function selectedIndex = localPromptConfigurationSelection(choiceTable)

    figureHandle = uifigure( ...
        "Name", ...
            "Static Optimization Analysis", ...
        "Position", ...
            [500 300 780 500], ...
        "WindowStyle", ...
            "modal");

    state = struct( ...
        "Accepted", false, ...
        "SelectedIndex", []);

    figureHandle.UserData = ...
        state;

    layout = uigridlayout( ...
        figureHandle, ...
        [3 1]);

    layout.RowHeight = { ...
        "fit", ...
        "1x", ...
        "fit"};

    layout.Padding = ...
        [12 12 12 12];

    layout.RowSpacing = ...
        8;

    instructionLabel = uilabel( ...
        layout, ...
        "Text", ...
            "Select a Static Optimization result set. Click a column " + ...
            "header to sort ascending or descending.");

    instructionLabel.Layout.Row = ...
        1;

    tableHandle = uitable( ...
        layout, ...
        "Data", ...
            choiceTable, ...
        "ColumnName", ...
            { ...
                "Configuration", ...
                "Muscle (%)", ...
                "Actuator (%)", ...
                "Status" ...
            }, ...
        "ColumnWidth", ...
            {"2x", 110, 110, "1.5x"}, ...
        "ColumnEditable", ...
            false, ...
        "ColumnSortable", ...
            true, ...
        "ColumnRearrangeable", ...
            false, ...
        "SelectionType", ...
            "row", ...
        "Multiselect", ...
            "off", ...
        "RowName", ...
            []);

    tableHandle.Layout.Row = ...
        2;

    localApplyFeasibilityStyles( ...
        tableHandle, ...
        choiceTable.Status);

    buttonLayout = uigridlayout( ...
        layout, ...
        [1 3]);

    buttonLayout.Layout.Row = ...
        3;

    buttonLayout.ColumnWidth = { ...
        "1x", ...
        100, ...
        100};

    cancelButton = uibutton( ...
        buttonLayout, ...
        "Text", ...
            "Cancel", ...
        "ButtonPushedFcn", ...
            @(~,~) localCancelPrompt(figureHandle));

    cancelButton.Layout.Column = ...
        2;

    selectButton = uibutton( ...
        buttonLayout, ...
        "Text", ...
            "Select", ...
        "ButtonPushedFcn", ...
            @(~,~) localAcceptPrompt( ...
                figureHandle, ...
                tableHandle));

    selectButton.Layout.Column = ...
        3;

    tableHandle.DoubleClickedFcn = ...
        @(~,~) localAcceptPrompt( ...
            figureHandle, ...
            tableHandle);

    figureHandle.CloseRequestFcn = ...
        @(~,~) localCancelPrompt(figureHandle);

    uiwait(figureHandle);

    state = ...
        figureHandle.UserData;

    if isvalid(figureHandle)
        delete(figureHandle);
    end

    assert(state.Accepted && ~isempty(state.SelectedIndex), ...
        "SOAnalysisContext:SelectionCancelled", ...
        "Static Optimization analysis configuration selection was cancelled.");

    selectedIndex = ...
        state.SelectedIndex;
end


function localApplyFeasibilityStyles(tableHandle, status)

    status = ...
        string(status);

    statusColumn = ...
        4;

    feasibleRows = ...
        find(status == "FEASIBLE");

    infeasibleRows = ...
        find(startsWith(status, "INFEASIBLE"));

    incompleteRows = ...
        find(startsWith(status, "INCOMPLETE"));

    legacyRows = ...
        find(status == "LEGACY");

    if ~isempty(feasibleRows)
        style = uistyle( ...
            "BackgroundColor", ...
                [0.84 0.94 0.84], ...
            "FontColor", ...
                [0.10 0.35 0.10], ...
            "FontWeight", ...
                "bold");

        addStyle( ...
            tableHandle, ...
            style, ...
            "cell", ...
            [ ...
                feasibleRows, ...
                repmat(statusColumn, numel(feasibleRows), 1) ...
            ]);
    end

    if ~isempty(infeasibleRows)
        style = uistyle( ...
            "BackgroundColor", ...
                [0.96 0.84 0.84], ...
            "FontColor", ...
                [0.55 0.10 0.10], ...
            "FontWeight", ...
                "bold");

        addStyle( ...
            tableHandle, ...
            style, ...
            "cell", ...
            [ ...
                infeasibleRows, ...
                repmat(statusColumn, numel(infeasibleRows), 1) ...
            ]);
    end

    if ~isempty(incompleteRows)
        style = uistyle( ...
            "BackgroundColor", ...
                [0.98 0.93 0.76], ...
            "FontColor", ...
                [0.45 0.30 0.05], ...
            "FontWeight", ...
                "bold");

        addStyle( ...
            tableHandle, ...
            style, ...
            "cell", ...
            [ ...
                incompleteRows, ...
                repmat(statusColumn, numel(incompleteRows), 1) ...
            ]);
    end

    if ~isempty(legacyRows)
        style = uistyle( ...
            "BackgroundColor", ...
                [0.90 0.90 0.90], ...
            "FontWeight", ...
                "bold");

        addStyle( ...
            tableHandle, ...
            style, ...
            "cell", ...
            [ ...
                legacyRows, ...
                repmat(statusColumn, numel(legacyRows), 1) ...
            ]);
    end
end


function localAcceptPrompt(figureHandle, tableHandle)

    selection = ...
        tableHandle.Selection;

    if isempty(selection)
        uialert( ...
            figureHandle, ...
            "Select a configuration row before continuing.", ...
            "No Configuration Selected");

        return;
    end

    state = ...
        figureHandle.UserData;

    state.Accepted = ...
        true;

    % Selection maps to the underlying Data row even after UI sorting.
    state.SelectedIndex = ...
        selection(1);

    figureHandle.UserData = ...
        state;

    uiresume(figureHandle);
end


function localCancelPrompt(figureHandle)

    state = ...
        figureHandle.UserData;

    state.Accepted = ...
        false;

    state.SelectedIndex = ...
        [];

    figureHandle.UserData = ...
        state;

    uiresume(figureHandle);
end


function context = localConfigurationContext( ...
        row, requestedMode, resolvedMode, legacyAvailable, ...
        eligibleConfigurations, selection)

    configRoot = string(row.ConfigRoot(1));
    analysisDirectory = string(row.AnalysisDirectory(1));

    assert(isfolder(configRoot), ...
        "SOAnalysisContext:ConfigRootNotFound", ...
        "Selected configuration root was not found:\n%s", ...
        configRoot);

    context = struct;
    context.SchemaVersion = 1;
    context.RequestedMode = requestedMode;
    context.ResolvedMode = resolvedMode;
    context.Configured = true;
    context.Legacy = false;
    context.ConfigId = string(row.ConfigId(1));
    context.MusclePercent = double(row.MusclePercent(1));
    context.ActuatorPercent = double(row.ActuatorPercent(1));
    context.DisplayName = string(sprintf( ...
        "%s (%g%% muscle, %g%% actuator)", ...
        context.ConfigId, ...
        context.MusclePercent, ...
        context.ActuatorPercent));
    context.AssessmentComplete = logical(row.AssessmentComplete(1));
    context.IsFeasible = logical(row.IsFeasible(1));
    context.FeasibilityStatus = string(row.FeasibilityStatus(1));
    context.FeasibilityReason = string(row.FeasibilityReason(1));
    context.SearchRoot = configRoot;
    context.AnalysisDirectory = analysisDirectory;
    context.LegacyAvailable = legacyAvailable;
    context.EligibleConfigurations = eligibleConfigurations;
    context.SelectionSettings = selection;
end


function context = localLegacyContext( ...
        outputRoot, requestedMode, legacyAvailable, ...
        eligibleConfigurations, selection)

    context = struct;
    context.SchemaVersion = 1;
    context.RequestedMode = requestedMode;
    context.ResolvedMode = "legacy";
    context.Configured = false;
    context.Legacy = true;
    context.ConfigId = "";
    context.MusclePercent = NaN;
    context.ActuatorPercent = NaN;
    context.DisplayName = ...
        "Legacy unconfigured Static Optimization results";
    context.AssessmentComplete = false;
    context.IsFeasible = false;
    context.FeasibilityStatus = "LEGACY_UNASSESSED";
    context.FeasibilityReason = ...
        "Legacy result sets do not have canonical strength-grid " + ...
        "feasibility metadata.";
    context.SearchRoot = outputRoot;
    context.AnalysisDirectory = ...
        string(fullfile(outputRoot, "static_optimization_analysis"));
    context.LegacyAvailable = legacyAvailable;
    context.EligibleConfigurations = eligibleConfigurations;
    context.SelectionSettings = selection;
end


function tf = localLegacyResultsExist(outputRoot)

    tf = false;

    conditionListing = dir(outputRoot);

    if isempty(conditionListing)
        return;
    end

    conditionNames = string({conditionListing.name}).';
    isDirectory = [conditionListing.isdir].';

    conditionMask = isDirectory & ...
        ~cellfun( ...
            @isempty, ...
            regexp(cellstr(conditionNames), '^-?\d+deg$', 'once'));

    conditionNames = conditionNames(conditionMask);

    for iCondition = 1:numel(conditionNames)

        conditionRoot = string(fullfile( ...
            outputRoot, ...
            conditionNames(iCondition)));

        trialListing = dir(conditionRoot);
        trialNames = string({trialListing.name}).';
        trialIsDirectory = [trialListing.isdir].';

        trialMask = trialIsDirectory & ...
            ~cellfun( ...
                @isempty, ...
                regexp(cellstr(trialNames), '^trial\d+$', 'once'));

        trialNames = trialNames(trialMask);

        for iTrial = 1:numel(trialNames)

            resultsDirectory = string(fullfile( ...
                conditionRoot, ...
                trialNames(iTrial), ...
                "04_static_optimization", ...
                "results"));

            if ~isfolder(resultsDirectory)
                continue;
            end

            forceListing = dir(fullfile( ...
                resultsDirectory, ...
                "*StaticOptimization_force.sto"));

            if ~isempty(forceListing)
                tf = true;
                return;
            end
        end
    end
end
