function trial = resolveTrialContext( ...
        projectCfg, conditionDeg, trialNumber, varargin)
%RESOLVETRIALCONTEXT Resolve canonical identity, inputs, and paths for a trial.
%
% trial = pipeline.resolveTrialContext( ...
%     projectCfg, conditionDeg, trialNumber)
%
% This function is the single authority for trial naming and pipeline path
% construction. It is intentionally SIDE-EFFECT FREE:
%
%   - it does not create directories;
%   - it does not require expected output files to exist;
%   - it does not run OpenSim;
%   - it does not modify projectCfg.
%
% This makes it safe to use from:
%   - thin example drivers;
%   - batch job enumeration;
%   - parfor workers;
%   - plotting/analysis;
%   - dependency/QC checks;
%   - unit tests.
%
% CANONICAL OUTPUT LAYOUT
%
% Configuration-independent stages:
%
%   <outputRoot>/
%       <conditionTag>/
%           <trialTag>/
%               01_initialization_ik/
%               02_locked_final_ik/
%
% When projectCfg.forceCapacity.enabled is true, configuration-dependent
% stages are isolated beneath the canonical strength-configuration root:
%
%   <outputRoot>/
%       static_optimization_configs/
%           <ConfigId>/
%               <conditionTag>/
%                   <trialTag>/
%                       03_static_optimization_prep/
%                       04_static_optimization/
%
% When force-capacity configuration is disabled, Processes 3 and 4 retain
% the legacy shared trial-root layout.
%
% CANONICAL IDENTITY
%
%   conditionTag = sprintf("%02ddeg", conditionDeg)
%   trialTag     = sprintf("trial%02d", trialNumber)
%   trialStem    = conditionTag + "_" + trialTag
%
% NAME-VALUE OPTIONS
%
%   MarkerFile
%       Explicit marker-file override. Default "" uses:
%
%           fullfile(projectCfg.rawDataRoot, ...
%               sprintf(projectCfg.pipeline.trialInput.markerFilePattern, ...
%                   conditionDeg, trialNumber))
%
%   RequireConfiguredTrial
%       Require conditionDeg and trialNumber to occur in
%       projectCfg.conditions and projectCfg.trials. Default true.
%
% RETURN STRUCTURE
%
%   trial.SchemaVersion
%   trial.ConditionDeg
%   trial.TrialNumber
%   trial.ConditionTag
%   trial.TrialTag
%   trial.TrialStem
%   trial.DisplayName
%   trial.Inputs
%   trial.Paths
%
% IMPORTANT
%
% This function resolves paths only. Stage workers are responsible for
% creating the directories they actually need.

    parser = inputParser;
    parser.FunctionName = ...
        "pipeline.resolveTrialContext";

    addRequired(parser, ...
        "projectCfg", ...
        @isstruct);

    addRequired(parser, ...
        "conditionDeg", ...
        @(x) isnumeric(x) && isscalar(x) && isfinite(x));

    addRequired(parser, ...
        "trialNumber", ...
        @(x) isnumeric(x) && isscalar(x) && ...
        isfinite(x) && x >= 1 && mod(x,1) == 0);

    addParameter(parser, ...
        "MarkerFile", ...
        "", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    addParameter(parser, ...
        "RequireConfiguredTrial", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, ...
        projectCfg, conditionDeg, trialNumber, varargin{:});

    conditionDeg = ...
        double(parser.Results.conditionDeg);

    trialNumber = ...
        double(parser.Results.trialNumber);

    markerFileOverride = ...
        string(parser.Results.MarkerFile);

    requireConfiguredTrial = ...
        parser.Results.RequireConfiguredTrial;

    %% Validate required project configuration

    requiredTopFields = [
        "projectRoot"
        "outputRoot"
        "rawDataRoot"
        "kinematicBaseModel"
        "initializationIkTemplate"
        "externalLoadsTemplate"
        "staticOptimizationTemplate"
        "conditions"
        "trials"
        "pipeline"
        "forceCapacity"
    ];

    missingTopFields = ...
        requiredTopFields( ...
            ~isfield( ...
                projectCfg, ...
                cellstr(requiredTopFields)));

    assert(isempty(missingTopFields), ...
        "TrialContext:ProjectConfigFieldsMissing", ...
        "projectCfg is missing required fields: %s", ...
        strjoin(missingTopFields, ", "));

    assert(isfield(projectCfg.pipeline, "trialInput") && ...
        isstruct(projectCfg.pipeline.trialInput), ...
        "TrialContext:TrialInputConfigMissing", ...
        "projectCfg.pipeline.trialInput is required.");

    assert(isfield( ...
            projectCfg.pipeline.trialInput, ...
            "markerFilePattern"), ...
        "TrialContext:MarkerPatternMissing", ...
        ["projectCfg.pipeline.trialInput.markerFilePattern " ...
         "is required."]);

    markerFilePattern = ...
        string( ...
            projectCfg.pipeline.trialInput.markerFilePattern);

    assert(strlength(markerFilePattern) > 0, ...
        "TrialContext:EmptyMarkerPattern", ...
        "Marker-file pattern must be nonempty.");

    assert(isstruct(projectCfg.forceCapacity) && ...
        isscalar(projectCfg.forceCapacity), ...
    "TrialContext:InvalidForceCapacityConfig", ...
    "projectCfg.forceCapacity must be a scalar struct.");

    assert(isfield( ...
            projectCfg.forceCapacity, ...
            "enabled"), ...
        "TrialContext:ForceCapacityEnabledMissing", ...
        "projectCfg.forceCapacity.enabled is required.");

    assert(islogical(projectCfg.forceCapacity.enabled) && ...
            isscalar(projectCfg.forceCapacity.enabled), ...
        "TrialContext:InvalidForceCapacityEnabled", ...
        "projectCfg.forceCapacity.enabled must be a logical scalar.");

    %% Identity validation

    % Current repository naming uses integer incline conditions. Rejecting
    % noninteger values prevents two conditions from silently collapsing to
    % the same rounded folder/file name.
    assert(mod(conditionDeg,1) == 0, ...
        "TrialContext:NonintegerCondition", ...
        ["Current canonical naming requires integer condition angles. " ...
         "Received conditionDeg=%g."], ...
        conditionDeg);

    if requireConfiguredTrial

        assert(any(projectCfg.conditions == conditionDeg), ...
            "TrialContext:ConditionNotConfigured", ...
            "Condition %g deg is not present in projectCfg.conditions.", ...
            conditionDeg);

        assert(any(projectCfg.trials == trialNumber), ...
            "TrialContext:TrialNotConfigured", ...
            "Trial %d is not present in projectCfg.trials.", ...
            trialNumber);
    end

    %% Canonical names

    conditionTag = string(sprintf( ...
        "%02ddeg", ...
        round(conditionDeg)));

    trialTag = string(sprintf( ...
        "trial%02d", ...
        trialNumber));

    trialStem = ...
        conditionTag + "_" + trialTag;

    displayName = string(sprintf( ...
        "%g deg, trial %d", ...
        conditionDeg, ...
        trialNumber));

    %% Resolve shared inputs

    inputs = struct;

    inputs.KinematicBaseModel = ...
        string(projectCfg.kinematicBaseModel);

    inputs.InitializationIkTemplate = ...
        string(projectCfg.initializationIkTemplate);

    inputs.ExternalLoadsTemplate = ...
        string(projectCfg.externalLoadsTemplate);

    inputs.StaticOptimizationTemplate = ...
        string(projectCfg.staticOptimizationTemplate);

    if strlength(markerFileOverride) > 0

        markerFile = ...
            markerFileOverride;

    else

        rawDataRoot = ...
            string(projectCfg.rawDataRoot);

        assert(strlength(rawDataRoot) > 0, ...
            "TrialContext:RawDataRootEmpty", ...
            ["projectCfg.rawDataRoot must be configured when MarkerFile " ...
             "is not supplied explicitly."]);

        try

            markerFileName = string(sprintf( ...
                char(markerFilePattern), ...
                round(conditionDeg), ...
                trialNumber));

        catch exception

            error( ...
                "TrialContext:MarkerPatternInvalid", ...
                ["Could not format marker-file pattern '%s' using " ...
                 "condition=%g and trial=%d.\n\n%s"], ...
                markerFilePattern, ...
                conditionDeg, ...
                trialNumber, ...
                exception.message);
        end

        assert(strlength(markerFileName) > 0, ...
            "TrialContext:MarkerFileNameEmpty", ...
            "Formatted marker-file name is empty.");

        markerFile = string(fullfile( ...
            rawDataRoot, ...
            markerFileName));
    end

    inputs.MarkerFile = markerFile;

    %% Root trial directory

    trialRoot = string(fullfile( ...
        projectCfg.outputRoot, ...
        conditionTag, ...
        trialTag));

    %% Strength-dependent Static Optimization root

    strengthConfigEnabled = ...
        logical(projectCfg.forceCapacity.enabled);

    strengthConfigId = "";
    strengthConfigRoot = "";

    staticOptimizationTrialRoot = ...
        trialRoot;

    if strengthConfigEnabled

        strengthContext = ...
            pipeline.resolveStrengthConfigContext( ...
                projectCfg);

        strengthConfigId = ...
            strengthContext.ConfigId;

        strengthConfigRoot = ...
            strengthContext.Paths.ConfigRoot;

        staticOptimizationTrialRoot = ...
            string(fullfile( ...
                strengthConfigRoot, ...
                conditionTag, ...
                trialTag));
    end

    %% Process 1 — initialization IK

    initialization = struct;

    initialization.Directory = string(fullfile( ...
        trialRoot, ...
        "01_initialization_ik"));

    initialization.QcDirectory = string(fullfile( ...
        initialization.Directory, ...
        "qc"));

    initialization.ModelAFile = string(fullfile( ...
        initialization.Directory, ...
        trialStem + ...
        "_modelA_initialization.osim"));

    initialization.IkSetupFile = string(fullfile( ...
        initialization.Directory, ...
        trialStem + ...
        "_initialization_ik_setup.xml"));

    initialization.IkMotionFile = string(fullfile( ...
        initialization.Directory, ...
        trialStem + ...
        "_initialization_ik.mot"));

    initialization.CoordinateConfigurationCsv = ...
        string(fullfile( ...
            initialization.QcDirectory, ...
            "modelA_coordinate_configuration.csv"));

    initialization.ConstraintConfigurationCsv = ...
        string(fullfile( ...
            initialization.QcDirectory, ...
            "modelA_constraint_configuration.csv"));

    initialization.MotionCoordinateAuditCsv = ...
        string(fullfile( ...
            initialization.QcDirectory, ...
            "initialization_ik_coordinate_audit.csv"));

    initialization.CheckpointFile = ...
        string(fullfile( ...
            initialization.QcDirectory, ...
            "initialization_ik_checkpoint.mat"));

    %% Process 2 — Model B / final IK

    modelB = struct;

    modelB.Directory = string(fullfile( ...
        trialRoot, ...
        "02_locked_final_ik"));

    modelB.QcDirectory = string(fullfile( ...
        modelB.Directory, ...
        "qc"));

    modelB.FilteredInitialIkMotionFile = string(fullfile( ...
        modelB.Directory, ...
        trialStem + ...
        "_initialization_ik_filtered_for_locks.mot"));

    modelB.ModelBFile = string(fullfile( ...
        modelB.Directory, ...
        trialStem + ...
        "_modelB_locked_ik.osim"));

    modelB.FinalIkSetupFile = string(fullfile( ...
        modelB.Directory, ...
        trialStem + ...
        "_final_ik_setup.xml"));

    modelB.FinalIkMotionFile = string(fullfile( ...
        modelB.Directory, ...
        trialStem + ...
        "_final_ik.mot"));

    modelB.LockFilterAuditCsv = string(fullfile( ...
        modelB.QcDirectory, ...
        "modelB_lock_filter_audit.csv"));

    modelB.LockValuesCsv = string(fullfile( ...
        modelB.QcDirectory, ...
        "modelB_lock_values.csv"));

    modelB.CoordinateConfigurationCsv = string(fullfile( ...
        modelB.QcDirectory, ...
        "modelB_coordinate_configuration.csv"));

    modelB.ConstraintConfigurationCsv = string(fullfile( ...
        modelB.QcDirectory, ...
        "modelB_constraint_configuration.csv"));

    modelB.DependentCoordinateStateCsv = string(fullfile( ...
        modelB.QcDirectory, ...
        "modelB_dependent_coordinate_state.csv"));

    modelB.LockedCoordinateAuditCsv = string(fullfile( ...
        modelB.QcDirectory, ...
        "final_ik_locked_coordinate_audit.csv"));

    modelB.IndependentSagittalStateCsv = string(fullfile( ...
        modelB.QcDirectory, ...
        "modelB_independent_sagittal_state.csv"));

    modelB.DependentOutOfPlaneSummaryCsv = string(fullfile( ...
        modelB.QcDirectory, ...
        "final_ik_dependent_out_of_plane_summary.csv"));

    modelB.IndependentSagittalSummaryCsv = string(fullfile( ...
        modelB.QcDirectory, ...
        "final_ik_independent_sagittal_summary.csv"));

    modelB.DependentSagittalSummaryCsv = string(fullfile( ...
        modelB.QcDirectory, ...
        "final_ik_dependent_sagittal_summary.csv"));

    modelB.SagittalSummaryCsv = string(fullfile( ...
        modelB.QcDirectory, ...
        "final_ik_sagittal_summary.csv"));

    modelB.SagittalTrajectoriesCsv = string(fullfile( ...
        modelB.QcDirectory, ...
        "final_ik_sagittal_trajectories.csv"));

    modelB.SagittalRelativeTrajectoriesCsv = ...
        string(fullfile( ...
            modelB.QcDirectory, ...
            "final_ik_sagittal_relative_trajectories.csv"));

    modelB.CheckpointFile = string(fullfile( ...
        modelB.QcDirectory, ...
        "model_b_final_ik_checkpoint.mat"));

    %% Process 3 — Model C / SO preparation

    prep = struct;

    prep.Directory = string(fullfile( ...
        staticOptimizationTrialRoot, ...
        "03_static_optimization_prep"));

    prep.QcDirectory = string(fullfile( ...
        prep.Directory, ...
        "qc"));

    prep.ModelCFile = string(fullfile( ...
        prep.Directory, ...
        trialStem + ...
        "_modelC_static_optimization.osim"));

    prep.CoordinateConfigurationCsv = string(fullfile( ...
        prep.QcDirectory, ...
        "modelC_coordinate_configuration.csv"));

    prep.ConstraintConfigurationCsv = string(fullfile( ...
        prep.QcDirectory, ...
        "modelC_constraint_configuration.csv"));

    prep.ForceConfigAuditCsv = string(fullfile( ...
        prep.QcDirectory, ...
        "modelC_force_capacity_config_audit.csv"));

    prep.CheckpointFile = string(fullfile( ...
        prep.QcDirectory, ...
        "model_c_checkpoint.mat"));

    % Body Kinematics
    bodyKinematics = struct;

    bodyKinematics.Directory = string(fullfile( ...
        prep.Directory, ...
        "body_kinematics"));

    bodyKinematics.ResultsDirectory = string(fullfile( ...
        bodyKinematics.Directory, ...
        "results"));

    bodyKinematics.QcDirectory = string(fullfile( ...
        bodyKinematics.Directory, ...
        "qc"));

    bodyKinematics.SetupFile = string(fullfile( ...
        bodyKinematics.Directory, ...
        trialStem + ...
        "_body_kinematics_setup.xml"));

    bodyKinematics.RawComCsv = string(fullfile( ...
        bodyKinematics.QcDirectory, ...
        "skull_com_raw.csv"));

    bodyKinematics.ResampledComCsv = string(fullfile( ...
        bodyKinematics.QcDirectory, ...
        "skull_com_resampled.csv"));

    bodyKinematics.ComSummaryCsv = string(fullfile( ...
        bodyKinematics.QcDirectory, ...
        "skull_com_summary.csv"));

    prep.BodyKinematics = bodyKinematics;

    % Head support force
    hsfPaths = struct;

    hsfPaths.Directory = string(fullfile( ...
        prep.Directory, ...
        "head_support_force"));

    hsfPaths.QcDirectory = string(fullfile( ...
        hsfPaths.Directory, ...
        "qc"));

    hsfPaths.EventDetectionSummaryCsv = string(fullfile( ...
        hsfPaths.QcDirectory, ...
        "contact_event_detection_summary.csv"));

    hsfPaths.EventDetectionPlot = string(fullfile( ...
        hsfPaths.QcDirectory, ...
        "contact_event_detection.png"));

    hsfPaths.MotionFile = string(fullfile( ...
        hsfPaths.Directory, ...
        trialStem + ...
        "_head_support_force.mot"));

    hsfPaths.SummaryCsv = string(fullfile( ...
        hsfPaths.QcDirectory, ...
        "hsf_summary.csv"));

    hsfPaths.SupportEnvelopeCsv = string(fullfile( ...
        hsfPaths.QcDirectory, ...
        "hsf_support_envelope.csv"));

    hsfPaths.ExternalLoadsFile = string(fullfile( ...
        hsfPaths.Directory, ...
        trialStem + ...
        "_external_loads.xml"));

    prep.HeadSupportForce = hsfPaths;

    %% Process 4 — Static Optimization

    staticOptimization = struct;

    staticOptimization.Directory = string(fullfile( ...
        staticOptimizationTrialRoot, ...
        "04_static_optimization"));

    staticOptimization.ResultsDirectory = string(fullfile( ...
        staticOptimization.Directory, ...
        "results"));

    staticOptimization.QcDirectory = string(fullfile( ...
        staticOptimization.Directory, ...
        "qc"));

    staticOptimization.PlotDirectory = string(fullfile( ...
        staticOptimization.QcDirectory, ...
        "plots"));

    staticOptimization.SetupFile = string(fullfile( ...
        staticOptimization.Directory, ...
        trialStem + ...
        "_so_setup.xml"));

    staticOptimization.OutputAuditCsv = string(fullfile( ...
        staticOptimization.QcDirectory, ...
        "static_optimization_output_audit.csv"));

    staticOptimization.CheckpointFile = string(fullfile( ...
        staticOptimization.QcDirectory, ...
        "static_optimization_run_checkpoint.mat"));

    % OpenSim chooses the leading result stem from the analysis/tool name,
    % so store canonical search patterns rather than inventing exact paths.
    staticOptimization.ForceResultPattern = ...
        "*StaticOptimization_force.sto";

    staticOptimization.ActivationResultPattern = ...
        "*StaticOptimization_activation.sto";

    %% Combined path object

    paths = struct;

    paths.TrialRoot = trialRoot;
    paths.StrengthConfigRoot = strengthConfigRoot;
    paths.StaticOptimizationTrialRoot = staticOptimizationTrialRoot;
    paths.Initialization = initialization;
    paths.ModelB = modelB;
    paths.StaticOptimizationPrep = prep;
    paths.StaticOptimization = staticOptimization;

    %% Return trial context

    trial = struct;

    trial.SchemaVersion = 2;

    trial.ConditionDeg = conditionDeg;
    trial.TrialNumber = trialNumber;

    trial.ConditionTag = conditionTag;
    trial.TrialTag = trialTag;
    trial.TrialStem = trialStem;
    trial.DisplayName = displayName;

    trial.Inputs = inputs;
    trial.Paths = paths;

    trial.StrengthConfigEnabled = strengthConfigEnabled;
    trial.StrengthConfigId = strengthConfigId;
end
