function context = resolveStaticOptimizationAnalysisContext( ...
        projectCfg, varargin)
%RESOLVESTATICOPTIMIZATIONANALYSISCONTEXT Resolve one SO analysis dataset.
%
% context = pipeline.resolveStaticOptimizationAnalysisContext(projectCfg)
%
% Resolves the user-selected Static Optimization result namespace
% independently of projectCfg.forceCapacity. This function does not create
% directories or modify projectCfg.
%
% Selection settings:
%   projectCfg.analysis.staticOptimization.selection
%
% Modes:
%   "prompt" - discover eligible configurations and show a listdlg.
%   "config" - resolve selection.configId exactly.
%   "legacy" - resolve the historical unconfigured output tree.
%
% Optional name-value inputs:
%   "ConfigurationSummary" - precomputed summary table equivalent to
%       soopt.summarizeStrengthConfigurations(projectCfg).
%   "PromptSelectionIndex" - deterministic prompt choice for tests/headless
%       regression. Normal interactive use leaves this empty.

    %% Validate project configuration

    assert(isstruct(projectCfg) && isscalar(projectCfg), ...
        "SOAnalysisContext:InvalidProjectConfig", ...
        "projectCfg must be a scalar struct.");

    requiredTopFields = ["outputRoot"; "analysis"];

    missingTopFields = requiredTopFields( ...
        ~isfield(projectCfg, cellstr(requiredTopFields)));

    assert(isempty(missingTopFields), ...
        "SOAnalysisContext:ProjectConfigFieldsMissing", ...
        "projectCfg is missing required fields: %s", ...
        strjoin(missingTopFields, ", "));

    outputRoot = string(projectCfg.outputRoot);

    assert(isscalar(outputRoot) && ~ismissing(outputRoot) && ...
            strlength(outputRoot) > 0, ...
        "SOAnalysisContext:InvalidOutputRoot", ...
        "projectCfg.outputRoot must be a nonempty scalar path.");

    assert(isfolder(outputRoot), ...
        "SOAnalysisContext:OutputRootNotFound", ...
        "Project output root was not found:\n%s", ...
        outputRoot);

    assert(isstruct(projectCfg.analysis) && ...
            isscalar(projectCfg.analysis) && ...
            isfield(projectCfg.analysis, "staticOptimization"), ...
        "SOAnalysisContext:StaticOptimizationConfigMissing", ...
        "projectCfg.analysis.staticOptimization is required.");

    analysisCfg = projectCfg.analysis.staticOptimization;

    assert(isstruct(analysisCfg) && isscalar(analysisCfg) && ...
            isfield(analysisCfg, "selection"), ...
        "SOAnalysisContext:SelectionConfigMissing", ...
        "projectCfg.analysis.staticOptimization.selection is required.");

    selection = localValidateSelectionConfig(analysisCfg.selection);

    %% Parse optional controls

    parser = inputParser;
    parser.FunctionName = ...
        "pipeline.resolveStaticOptimizationAnalysisContext";

    addParameter(parser, ...
        "ConfigurationSummary", ...
        [], ...
        @(x) isempty(x) || istable(x));

    addParameter(parser, ...
        "PromptSelectionIndex", ...
        [], ...
        @(x) isempty(x) || ...
            (isnumeric(x) && isscalar(x) && isfinite(x) && ...
            x >= 1 && mod(x,1) == 0));

    parse(parser, varargin{:});

    suppliedSummary = parser.Results.ConfigurationSummary;
    promptSelectionIndex = parser.Results.PromptSelectionIndex;

    requestedMode = selection.Mode;

    legacyAvailable = localLegacyResultsExist(outputRoot);

    eligibleConfigurations = table;

    if requestedMode == "legacy"

        assert(legacyAvailable, ...
            "SOAnalysisContext:LegacyResultsNotFound", ...
            "Legacy Static Optimization results were not found directly " + ...
            "beneath projectCfg.outputRoot:\n%s", ...
            outputRoot);

        context = localLegacyContext( ...
            outputRoot, ...
            requestedMode, ...
            legacyAvailable, ...
            eligibleConfigurations, ...
            selection);

        return;
    end

    %% Obtain configuration-level feasibility summary

    if istable(suppliedSummary)
        summary = suppliedSummary;
    else
        summary = soopt.summarizeStrengthConfigurations(projectCfg);
    end

    localValidateConfigurationSummary(summary);

    %% Explicit config mode

    if requestedMode == "config"

        match = string(summary.ConfigId) == selection.ConfigId;

        assert(nnz(match) == 1, ...
            "SOAnalysisContext:ConfigNotFound", ...
            "Static Optimization analysis configuration '%s' was not " + ...
            "found beneath:\n%s", ...
            selection.ConfigId, ...
            fullfile(outputRoot, "static_optimization_configs"));

        selectedRow = summary(match,:);

        localRequireEligibleConfiguration(selectedRow, selection);

        context = localConfigurationContext( ...
            selectedRow, ...
            requestedMode, ...
            "config", ...
            legacyAvailable, ...
            selectedRow, ...
            selection);

        return;
    end

    assert(requestedMode == "prompt", ...
        "SOAnalysisContext:UnsupportedSelectionMode", ...
        "Unsupported Static Optimization analysis selection mode: %s", ...
        requestedMode);

    %% Prompt mode eligibility

    eligibleMask = true(height(summary),1);

    if selection.RequireAssessmentComplete
        eligibleMask = ...
            eligibleMask & logical(summary.AssessmentComplete);
    end

    if selection.RequireFeasible
        eligibleMask = ...
            eligibleMask & logical(summary.IsFeasible);
    end

    eligibleConfigurations = summary(eligibleMask,:);

    if ~isempty(eligibleConfigurations)
        eligibleConfigurations = sortrows( ...
            eligibleConfigurations, ...
            {'MusclePercent','ActuatorPercent','ConfigId'});
    end

    choiceKinds = repmat( ...
        "config", ...
        height(eligibleConfigurations), ...
        1);

    choiceLabels = localConfigurationLabels(eligibleConfigurations);

    if selection.IncludeLegacyInPrompt && legacyAvailable
        choiceKinds(end+1,1) = "legacy";
        choiceLabels(end+1,1) = ...
            "LEGACY | unconfigured Static Optimization output tree";
    end

    assert(~isempty(choiceLabels), ...
        "SOAnalysisContext:NoEligibleConfigurations", ...
        "No Static Optimization result sets satisfy the current selection " + ...
        "policy. requireAssessmentComplete=%d, requireFeasible=%d, " + ...
        "includeLegacyInPrompt=%d.", ...
        selection.RequireAssessmentComplete, ...
        selection.RequireFeasible, ...
        selection.IncludeLegacyInPrompt);

    %% Resolve prompt choice

    if numel(choiceLabels) == 1 && ...
            selection.AutoSelectSingleCandidate %#ok<ISCL>

        selectedIndex = 1;

    elseif ~isempty(promptSelectionIndex)

        assert(promptSelectionIndex <= numel(choiceLabels), ...
            "SOAnalysisContext:PromptSelectionIndexOutOfRange", ...
            "PromptSelectionIndex=%d exceeds the %d available choices.", ...
            promptSelectionIndex, ...
            numel(choiceLabels));

        selectedIndex = promptSelectionIndex;

    else

        assert(usejava("awt"), ...
            "SOAnalysisContext:InteractiveSelectionUnavailable", ...
            "Interactive prompt mode requires MATLAB graphical UI support. " + ...
            "Use selection.mode='config' for noninteractive analysis.");

        [selectedIndex, accepted] = listdlg( ...
            "PromptString", ...
                "Select Static Optimization result set for analysis:", ...
            "SelectionMode", ...
                "single", ...
            "ListString", ...
                cellstr(choiceLabels), ...
            "ListSize", ...
                [760 420], ...
            "Name", ...
                "Static Optimization Analysis");

        assert(accepted && ~isempty(selectedIndex), ...
            "SOAnalysisContext:SelectionCancelled", ...
            "Static Optimization analysis configuration selection was cancelled.");
    end

    if choiceKinds(selectedIndex) == "legacy"

        context = localLegacyContext( ...
            outputRoot, ...
            requestedMode, ...
            legacyAvailable, ...
            eligibleConfigurations, ...
            selection);

        return;
    end

    selectedRow = eligibleConfigurations(selectedIndex,:);

    context = localConfigurationContext( ...
        selectedRow, ...
        requestedMode, ...
        "config", ...
        legacyAvailable, ...
        eligibleConfigurations, ...
        selection);
end


function selection = localValidateSelectionConfig(selectionCfg)

    assert(isstruct(selectionCfg) && isscalar(selectionCfg), ...
        "SOAnalysisContext:InvalidSelectionConfig", ...
        "projectCfg.analysis.staticOptimization.selection must be a " + ...
        "scalar struct.");

    requiredFields = [ ...
        "mode"
        "configId"
        "requireAssessmentComplete"
        "requireFeasible"
        "includeLegacyInPrompt"
        "autoSelectSingleCandidate"
    ];

    missingFields = requiredFields( ...
        ~isfield(selectionCfg, cellstr(requiredFields)));

    assert(isempty(missingFields), ...
        "SOAnalysisContext:SelectionFieldsMissing", ...
        "Static Optimization analysis selection config is missing: %s", ...
        strjoin(missingFields, ", "));

    mode = lower(strtrim(string(selectionCfg.mode)));

    assert(isscalar(mode) && ~ismissing(mode) && ...
            ismember(mode, ["prompt","config","legacy"]), ...
        "SOAnalysisContext:InvalidSelectionMode", ...
        "selection.mode must be 'prompt', 'config', or 'legacy'.");

    configId = strtrim(string(selectionCfg.configId));

    assert(isscalar(configId) && ~ismissing(configId), ...
        "SOAnalysisContext:InvalidConfigId", ...
        "selection.configId must be a scalar string.");

    if mode == "config"
        assert(strlength(configId) > 0, ...
            "SOAnalysisContext:ConfigIdRequired", ...
            "selection.configId must be nonempty when selection.mode='config'.");

        info = pipeline.parseStrengthConfigName(configId + ".json");
        configId = info.ConfigId;
    end

    logicalFields = [ ...
        "requireAssessmentComplete"
        "requireFeasible"
        "includeLegacyInPrompt"
        "autoSelectSingleCandidate"
    ];

    for fieldName = logicalFields.'
        value = selectionCfg.(fieldName);

        assert(islogical(value) && isscalar(value), ...
            "SOAnalysisContext:InvalidLogicalSetting", ...
            "selection.%s must be a logical scalar.", ...
            fieldName);
    end

    selection = struct;
    selection.Mode = mode;
    selection.ConfigId = configId;
    selection.RequireAssessmentComplete = ...
        logical(selectionCfg.requireAssessmentComplete);
    selection.RequireFeasible = ...
        logical(selectionCfg.requireFeasible);
    selection.IncludeLegacyInPrompt = ...
        logical(selectionCfg.includeLegacyInPrompt);
    selection.AutoSelectSingleCandidate = ...
        logical(selectionCfg.autoSelectSingleCandidate);
end


function localValidateConfigurationSummary(summary)

    assert(istable(summary), ...
        "SOAnalysisContext:InvalidConfigurationSummary", ...
        "Configuration summary must be a table.");

    requiredVariables = [ ...
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
        "ConfigRoot"
        "AnalysisDirectory"
        "AssessmentComplete"
        "IsFeasible"
        "FeasibilityStatus"
        "FeasibilityReason"
    ];

    missingVariables = requiredVariables( ...
        ~ismember( ...
            requiredVariables, ...
            string(summary.Properties.VariableNames)));

    assert(isempty(missingVariables), ...
        "SOAnalysisContext:ConfigurationSummaryVariablesMissing", ...
        "Configuration summary is missing required variables: %s", ...
        strjoin(missingVariables, ", "));

    configIds = string(summary.ConfigId);

    assert(numel(unique(configIds)) == numel(configIds), ...
        "SOAnalysisContext:DuplicateConfigIds", ...
        "Configuration summary contains duplicate ConfigId values.");
end


function localRequireEligibleConfiguration(row, selection)

    assert(height(row) == 1, ...
        "SOAnalysisContext:InvalidSelectedRow", ...
        "Selected configuration must contain exactly one row.");

    if selection.RequireAssessmentComplete
        assert(logical(row.AssessmentComplete(1)), ...
            "SOAnalysisContext:AssessmentIncomplete", ...
            "Configuration '%s' cannot be selected because its assessment " + ...
            "is incomplete. Status: %s. Reason: %s", ...
            string(row.ConfigId(1)), ...
            string(row.FeasibilityStatus(1)), ...
            string(row.FeasibilityReason(1)));
    end

    if selection.RequireFeasible
        assert(logical(row.IsFeasible(1)), ...
            "SOAnalysisContext:ConfigurationInfeasible", ...
            "Configuration '%s' cannot be selected because it is not " + ...
            "feasible. Status: %s. Reason: %s", ...
            string(row.ConfigId(1)), ...
            string(row.FeasibilityStatus(1)), ...
            string(row.FeasibilityReason(1)));
    end
end


function labels = localConfigurationLabels(configurations)

    labels = strings(height(configurations),1);

    for i = 1:height(configurations)
        labels(i) = string(sprintf( ...
            "%s | muscle %g%% | actuator %g%% | %s", ...
            string(configurations.ConfigId(i)), ...
            double(configurations.MusclePercent(i)), ...
            double(configurations.ActuatorPercent(i)), ...
            string(configurations.FeasibilityStatus(i))));
    end
end


function context = localConfigurationContext( ...
        row, requestedMode, resolvedMode, legacyAvailable, ...
        eligibleConfigurations, selection)

    configRoot = string(row.ConfigRoot(1));
    analysisDirectory = string(row.AnalysisDirectory(1));

    assert(isfolder(configRoot), ...
        "SOAnalysisContext:ConfigRootNotFound", ...
        "Selected configuration root was not found:\n%s", ...
        configRoot);

    context = struct;
    context.SchemaVersion = 1;
    context.RequestedMode = requestedMode;
    context.ResolvedMode = resolvedMode;
    context.Configured = true;
    context.Legacy = false;
    context.ConfigId = string(row.ConfigId(1));
    context.MusclePercent = double(row.MusclePercent(1));
    context.ActuatorPercent = double(row.ActuatorPercent(1));
    context.DisplayName = string(sprintf( ...
        "%s (%g%% muscle, %g%% actuator)", ...
        context.ConfigId, ...
        context.MusclePercent, ...
        context.ActuatorPercent));
    context.AssessmentComplete = logical(row.AssessmentComplete(1));
    context.IsFeasible = logical(row.IsFeasible(1));
    context.FeasibilityStatus = string(row.FeasibilityStatus(1));
    context.FeasibilityReason = string(row.FeasibilityReason(1));
    context.SearchRoot = configRoot;
    context.AnalysisDirectory = analysisDirectory;
    context.LegacyAvailable = legacyAvailable;
    context.EligibleConfigurations = eligibleConfigurations;
    context.SelectionSettings = selection;
end


function context = localLegacyContext( ...
        outputRoot, requestedMode, legacyAvailable, ...
        eligibleConfigurations, selection)

    context = struct;
    context.SchemaVersion = 1;
    context.RequestedMode = requestedMode;
    context.ResolvedMode = "legacy";
    context.Configured = false;
    context.Legacy = true;
    context.ConfigId = "";
    context.MusclePercent = NaN;
    context.ActuatorPercent = NaN;
    context.DisplayName = ...
        "Legacy unconfigured Static Optimization results";
    context.AssessmentComplete = false;
    context.IsFeasible = false;
    context.FeasibilityStatus = "LEGACY_UNASSESSED";
    context.FeasibilityReason = ...
        "Legacy result sets do not have canonical strength-grid " + ...
        "feasibility metadata.";
    context.SearchRoot = outputRoot;
    context.AnalysisDirectory = ...
        string(fullfile(outputRoot, "static_optimization_analysis"));
    context.LegacyAvailable = legacyAvailable;
    context.EligibleConfigurations = eligibleConfigurations;
    context.SelectionSettings = selection;
end


function tf = localLegacyResultsExist(outputRoot)

    tf = false;

    conditionListing = dir(outputRoot);

    if isempty(conditionListing)
        return;
    end

    conditionNames = string({conditionListing.name}).';
    isDirectory = [conditionListing.isdir].';

    conditionMask = isDirectory & ...
        ~cellfun( ...
            @isempty, ...
            regexp(cellstr(conditionNames), '^-?\d+deg$', 'once'));

    conditionNames = conditionNames(conditionMask);

    for iCondition = 1:numel(conditionNames)

        conditionRoot = string(fullfile( ...
            outputRoot, ...
            conditionNames(iCondition)));

        trialListing = dir(conditionRoot);
        trialNames = string({trialListing.name}).';
        trialIsDirectory = [trialListing.isdir].';

        trialMask = trialIsDirectory & ...
            ~cellfun( ...
                @isempty, ...
                regexp(cellstr(trialNames), '^trial\d+$', 'once'));

        trialNames = trialNames(trialMask);

        for iTrial = 1:numel(trialNames)

            resultsDirectory = string(fullfile( ...
                conditionRoot, ...
                trialNames(iTrial), ...
                "04_static_optimization", ...
                "results"));

            if ~isfolder(resultsDirectory)
                continue;
            end

            forceListing = dir(fullfile( ...
                resultsDirectory, ...
                "*StaticOptimization_force.sto"));

            if ~isempty(forceListing)
                tf = true;
                return;
            end
        end
    end
end
