function policy = resolveStorageRetentionPolicy(projectCfg)
%RESOLVESTORAGERETENTIONPOLICY Resolve validated artifact-retention policy.
%
% policy = pipeline.resolveStorageRetentionPolicy(projectCfg)
%
% Centralizes project-level storage/retention behavior. The resolver is
% intentionally side-effect free: it validates configuration and returns a
% normalized policy, but never creates or deletes files.
%
% Backward compatibility:
%   If projectCfg.storage is absent, a conservative keep-everything policy
%   is returned.
%
% Retention classes:
%   Immediate cleanup
%       Artifacts that may be deleted as soon as a successfully audited
%       stage has completed. Currently this includes the OpenSim Static
%       Optimization controls XML.
%
%   Finalization cleanup
%       Shared/cached artifacts that must remain available while additional
%       configurations may still be generated. These settings are exposed
%       now for one authoritative schema, but are intended to be applied by
%       a later explicit project-finalization/pruning utility.

    assert(isstruct(projectCfg) && isscalar(projectCfg), ...
        "StorageRetention:InvalidProjectConfig", ...
        "projectCfg must be a scalar struct.");

    policy = localDefaultPolicy();

    if ~isfield(projectCfg, "storage") || isempty(projectCfg.storage)
        return;
    end

    storageCfg = projectCfg.storage;

    assert(isstruct(storageCfg) && isscalar(storageCfg), ...
        "StorageRetention:InvalidStorageConfig", ...
        "projectCfg.storage must be a scalar struct.");

    allowedTopLevel = [
        "staticOptimizationPrep"
        "staticOptimization"
        "sharedStaticOptimizationPrep"
    ];

    localRejectUnknownFields( ...
        storageCfg, ...
        allowedTopLevel, ...
        "projectCfg.storage");

    if isfield(storageCfg, "staticOptimizationPrep")

        prepCfg = ...
            storageCfg.staticOptimizationPrep;

        assert(isstruct(prepCfg) && isscalar(prepCfg), ...
            "StorageRetention:InvalidStaticOptimizationPrepConfig", ...
            "projectCfg.storage.staticOptimizationPrep must be a " + ...
            "scalar struct.");

        allowed = [
            "keepConfiguredModelC"
            "keepQc"
            "keepCheckpoint"
        ];

        localRejectUnknownFields( ...
            prepCfg, ...
            allowed, ...
            "projectCfg.storage.staticOptimizationPrep");

        policy.StaticOptimizationPrep.KeepConfiguredModelC = ...
            localReadLogical( ...
                prepCfg, ...
                "keepConfiguredModelC", ...
                policy.StaticOptimizationPrep.KeepConfiguredModelC);

        policy.StaticOptimizationPrep.KeepQc = ...
            localReadLogical( ...
                prepCfg, ...
                "keepQc", ...
                policy.StaticOptimizationPrep.KeepQc);

        policy.StaticOptimizationPrep.KeepCheckpoint = ...
            localReadLogical( ...
                prepCfg, ...
                "keepCheckpoint", ...
                policy.StaticOptimizationPrep.KeepCheckpoint);

    end

    if isfield(storageCfg, "staticOptimization")

        soCfg = storageCfg.staticOptimization;

        assert(isstruct(soCfg) && isscalar(soCfg), ...
            "StorageRetention:InvalidStaticOptimizationConfig", ...
            "projectCfg.storage.staticOptimization must be a scalar struct.");

        allowed = [
            "keepControlsXml"
            "keepSetupXml"
            "keepForceSto"
            "keepActivationSto"
            "keepQc"
            "keepCheckpoint"
        ];

        localRejectUnknownFields( ...
            soCfg, ...
            allowed, ...
            "projectCfg.storage.staticOptimization");

        policy.StaticOptimization.KeepControlsXml = ...
            localReadLogical( ...
                soCfg, ...
                "keepControlsXml", ...
                policy.StaticOptimization.KeepControlsXml);

        policy.StaticOptimization.KeepSetupXml = ...
            localReadLogical( ...
                soCfg, ...
                "keepSetupXml", ...
                policy.StaticOptimization.KeepSetupXml);

        policy.StaticOptimization.KeepForceSto = ...
            localReadLogical( ...
                soCfg, ...
                "keepForceSto", ...
                policy.StaticOptimization.KeepForceSto);

        policy.StaticOptimization.KeepActivationSto = ...
            localReadLogical( ...
                soCfg, ...
                "keepActivationSto", ...
                policy.StaticOptimization.KeepActivationSto);

        policy.StaticOptimization.KeepQc = ...
            localReadLogical( ...
                soCfg, ...
                "keepQc", ...
                policy.StaticOptimization.KeepQc);

        policy.StaticOptimization.KeepCheckpoint = ...
            localReadLogical( ...
                soCfg, ...
                "keepCheckpoint", ...
                policy.StaticOptimization.KeepCheckpoint);
    end

    if isfield(storageCfg, "sharedStaticOptimizationPrep")

        sharedCfg = storageCfg.sharedStaticOptimizationPrep;

        assert(isstruct(sharedCfg) && isscalar(sharedCfg), ...
            "StorageRetention:InvalidSharedPrepConfig", ...
            "projectCfg.storage.sharedStaticOptimizationPrep must be a " + ...
            "scalar struct.");

        allowed = [
            "keepNeutralModelC"
            "keepBodyKinematics"
            "keepComCsv"
            "keepEventTiming"
            "keepHsfMotion"
            "keepExternalLoadsXml"
            "keepQc"
            "keepCheckpoint"
        ];

        localRejectUnknownFields( ...
            sharedCfg, ...
            allowed, ...
            "projectCfg.storage.sharedStaticOptimizationPrep");

        policy.SharedStaticOptimizationPrep.KeepNeutralModelC = ...
            localReadLogical( ...
                sharedCfg, ...
                "keepNeutralModelC", ...
                policy.SharedStaticOptimizationPrep.KeepNeutralModelC);

        policy.SharedStaticOptimizationPrep.KeepBodyKinematics = ...
            localReadLogical( ...
                sharedCfg, ...
                "keepBodyKinematics", ...
                policy.SharedStaticOptimizationPrep.KeepBodyKinematics);

        policy.SharedStaticOptimizationPrep.KeepComCsv = ...
            localReadLogical( ...
                sharedCfg, ...
                "keepComCsv", ...
                policy.SharedStaticOptimizationPrep.KeepComCsv);

        policy.SharedStaticOptimizationPrep.KeepEventTiming = ...
            localReadLogical( ...
                sharedCfg, ...
                "keepEventTiming", ...
                policy.SharedStaticOptimizationPrep.KeepEventTiming);

        policy.SharedStaticOptimizationPrep.KeepHsfMotion = ...
            localReadLogical( ...
                sharedCfg, ...
                "keepHsfMotion", ...
                policy.SharedStaticOptimizationPrep.KeepHsfMotion);

        policy.SharedStaticOptimizationPrep.KeepExternalLoadsXml = ...
            localReadLogical( ...
                sharedCfg, ...
                "keepExternalLoadsXml", ...
                policy.SharedStaticOptimizationPrep.KeepExternalLoadsXml);

        policy.SharedStaticOptimizationPrep.KeepQc = ...
            localReadLogical( ...
                sharedCfg, ...
                "keepQc", ...
                policy.SharedStaticOptimizationPrep.KeepQc);

        policy.SharedStaticOptimizationPrep.KeepCheckpoint = ...
            localReadLogical( ...
                sharedCfg, ...
                "keepCheckpoint", ...
                policy.SharedStaticOptimizationPrep.KeepCheckpoint);
    end
end


function policy = localDefaultPolicy()

    policy = struct;

    policy.SchemaVersion = 1;

    policy.StaticOptimizationPrep = ...
        struct( ...
            "KeepConfiguredModelC", true, ...
            "KeepQc", true, ...
            "KeepCheckpoint", true);

    policy.StaticOptimization = ...
        struct( ...
            "KeepControlsXml", true, ...
            "KeepSetupXml", true, ...
            "KeepForceSto", true, ...
            "KeepActivationSto", true, ...
            "KeepQc", true, ...
            "KeepCheckpoint", true);

    policy.SharedStaticOptimizationPrep = ...
        struct( ...
            "KeepNeutralModelC", true, ...
            "KeepBodyKinematics", true, ...
            "KeepComCsv", true, ...
            "KeepEventTiming", true, ...
            "KeepHsfMotion", true, ...
            "KeepExternalLoadsXml", true, ...
            "KeepQc", true, ...
            "KeepCheckpoint", true);
end


function value = localReadLogical(config, fieldName, defaultValue)

    value = defaultValue;

    if ~isfield(config, fieldName)
        return;
    end

    candidate = config.(fieldName);

    assert(islogical(candidate) && isscalar(candidate), ...
        "StorageRetention:InvalidLogicalSetting", ...
        "%s must be a logical scalar.", ...
        fieldName);

    value = candidate;
end


function localRejectUnknownFields(config, allowedFields, configLabel)

    actualFields = string(fieldnames(config));

    unknownFields = setdiff(actualFields, allowedFields);

    assert(isempty(unknownFields), ...
        "StorageRetention:UnknownSetting", ...
        "%s contains unknown storage settings: %s", ...
        configLabel, ...
        strjoin(unknownFields, ", "));
end
