function [sharedTrial, sharedCfg] = ...
        resolveStaticOptimizationSharedTrialContext( ...
            projectCfg, conditionDeg, trialNumber)
%RESOLVESTATICOPTIMIZATIONSHAREDTRIALCONTEXT Resolve strength-neutral SO prep.
%
% [sharedTrial, sharedCfg] = ...
%     pipeline.resolveStaticOptimizationSharedTrialContext( ...
%         projectCfg, conditionDeg, trialNumber)
%
% Returns a strength-independent trial context for preprocessing that is
% determined entirely by Process-2 kinematics and project HSF/QC settings.
%
% The normal trial-context resolver is used with force capacities disabled,
% then the Process-3 and reference Process-4 paths are rebased into:
%
%   <trial root>/03_static_optimization_shared_prep/
%
% This keeps Body Kinematics, skull CoM, event detection, HSF, ExternalLoads,
% and the neutral Model C outside static_optimization_configs.
%
% No directories or files are created by this function.

    assert(isstruct(projectCfg) && isscalar(projectCfg), ...
        "SharedSOPrepContext:InvalidProjectConfig", ...
        "projectCfg must be a scalar struct.");

    sharedCfg = ...
        projectCfg;

    if ~isfield(sharedCfg, "forceCapacity") || ...
            ~isstruct(sharedCfg.forceCapacity)

        sharedCfg.forceCapacity = ...
            struct;
    end

    sharedCfg.forceCapacity.enabled = ...
        false;

    sharedTrial = ...
        pipeline.resolveTrialContext( ...
            sharedCfg, ...
            conditionDeg, ...
            trialNumber);

    assert(~sharedTrial.StrengthConfigEnabled, ...
        "SharedSOPrepContext:StrengthConfigStillEnabled", ...
        "Shared SO preparation must resolve with force capacities disabled.");

    originalPrepRoot = ...
        string( ...
            sharedTrial.Paths.StaticOptimizationPrep.Directory);

    originalSoRoot = ...
        string( ...
            sharedTrial.Paths.StaticOptimization.Directory);

    sharedRoot = ...
        string(fullfile( ...
            sharedTrial.Paths.TrialRoot, ...
            "03_static_optimization_shared_prep"));

    referenceSoRoot = ...
        string(fullfile( ...
            sharedRoot, ...
            "so_reference"));

    sharedTrial.Paths.StaticOptimizationPrep = ...
        localRebasePathStruct( ...
            sharedTrial.Paths.StaticOptimizationPrep, ...
            originalPrepRoot, ...
            sharedRoot);

    sharedTrial.Paths.StaticOptimization = ...
        localRebasePathStruct( ...
            sharedTrial.Paths.StaticOptimization, ...
            originalSoRoot, ...
            referenceSoRoot);

    sharedTrial.Paths.StaticOptimizationTrialRoot = ...
        sharedTrial.Paths.TrialRoot;

    sharedTrial.Paths.StaticOptimizationSharedPrep = ...
        sharedTrial.Paths.StaticOptimizationPrep;

    sharedTrial.SharedPreparation = ...
        true;

    sharedTrial.SharedPreparationRoot = ...
        sharedRoot;
end


function value = ...
        localRebasePathStruct(value, oldRoot, newRoot)

    if isstruct(value)

        fields = ...
            fieldnames(value);

        for iField = 1:numel(fields)

            fieldName = ...
                fields{iField};

            value.(fieldName) = ...
                localRebasePathStruct( ...
                    value.(fieldName), ...
                    oldRoot, ...
                    newRoot);
        end

        return;
    end

    if isstring(value)

        value = ...
            replace( ...
                value, ...
                oldRoot, ...
                newRoot);

        return;
    end

    if ischar(value)

        value = ...
            char(replace( ...
                string(value), ...
                oldRoot, ...
                newRoot));
    end
end
