function result = runInitializationIkTrial( ...
        projectCfg, trial, varargin)
%RUNINITIALIZATIONIKTRIAL Run Process 1 for one resolved trial.
%
% result = pipeline.runInitializationIkTrial(projectCfg, trial)
%
% The trial input must be created by:
%
%   trial = pipeline.resolveTrialContext( ...
%       projectCfg, conditionDeg, trialNumber);
%
% This worker is the canonical implementation for:
%   1. creating Model A;
%   2. validating Model A configuration;
%   3. preparing the trial-specific IK setup;
%   4. executing initialization IK;
%   5. auditing the IK motion;
%   6. writing Process-1 QC outputs and checkpoint.
%
% Both the single-trial example and Batch Process 1 should call this
% function. Neither orchestration layer should reimplement these steps.
%
% NAME-VALUE OPTIONS
%
%   ExecuteIk
%       true (default). When false, Model A and the setup XML are prepared
%       and validated, but IK is not executed and motion QC/checkpointing
%       are skipped.
%
%   Overwrite
%       Defaults to projectCfg.overwriteExisting.
%
%   WriteQc
%       true (default). Write Model-A configuration and motion-audit CSVs.
%
%   SaveCheckpoint
%       true (default). Save the completed Process-1 checkpoint when IK is
%       executed successfully.
%
%   PrintProgress
%       true (default).
%
% RETURN
%
%   result.Stage
%   result.Trial
%   result.Paths
%   result.TimeRangeSec
%   result.ModelAResult
%   result.ModelAValidation
%   result.IkSetupResult
%   result.IkRunResult
%   result.IkMotionSummary
%   result.CoordinateAudit
%   result.AttentionAudit
%   result.CheckpointFile
%   result.Completed
%   result.DurationSeconds

    assert(isstruct(projectCfg), ...
        "PipelineInitialization:InvalidProjectConfig", ...
        "projectCfg must be a struct.");

    localValidateTrialContext(trial);

    defaultOverwrite = false;

    if isfield(projectCfg, "overwriteExisting")
        defaultOverwrite = ...
            projectCfg.overwriteExisting;
    end

    parser = inputParser;
    parser.FunctionName = ...
        "pipeline.runInitializationIkTrial";

    addRequired(parser, ...
        "projectCfg", ...
        @isstruct);

    addRequired(parser, ...
        "trial", ...
        @isstruct);

    addParameter(parser, ...
        "ExecuteIk", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "Overwrite", ...
        defaultOverwrite, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "WriteQc", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "SaveCheckpoint", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "PrintProgress", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, ...
        projectCfg, trial, varargin{:});

    executeIk = parser.Results.ExecuteIk;
    overwrite = parser.Results.Overwrite;
    writeQc = parser.Results.WriteQc;
    saveCheckpoint = parser.Results.SaveCheckpoint;
    printProgress = parser.Results.PrintProgress;

    stageStart = tic;

    %% Resolve stage configuration

    assert(isfield(projectCfg, "pipeline") && ...
        isfield(projectCfg.pipeline, "initializationIk"), ...
        "PipelineInitialization:ConfigMissing", ...
        "projectCfg.pipeline.initializationIk is required.");

    stageCfg = ...
        projectCfg.pipeline.initializationIk;

    assert(isfield(stageCfg, "timeRangeSec"), ...
        "PipelineInitialization:TimeRangeMissing", ...
        "initializationIk.timeRangeSec is required.");

    timeRangeSec = ...
        double(stageCfg.timeRangeSec(:)).';

    assert(numel(timeRangeSec) == 2 && ...
        all(isfinite(timeRangeSec)) && ...
        timeRangeSec(2) > timeRangeSec(1), ...
        "PipelineInitialization:InvalidTimeRange", ...
        "Initialization IK time range must be [start end].");

    assert(isfield(stageCfg, "reviewCoordinates"), ...
        "PipelineInitialization:ReviewCoordinatesMissing", ...
        ["projectCfg.pipeline.initializationIk.reviewCoordinates " ...
         "is required."]);

    reviewCoordinates = ...
        string(stageCfg.reviewCoordinates(:));

    assert(isfield(projectCfg, "modelValidation"), ...
        "PipelineInitialization:ModelValidationConfigMissing", ...
        "projectCfg.modelValidation is required.");

    expectedCoordinateCount = ...
        projectCfg.modelValidation.expectedCoordinateCount;

    expectedConstraintCount = ...
        projectCfg.modelValidation.expectedConstraintCount;

    %% Resolve inputs and outputs

    inputFiles = [
        string(trial.Inputs.KinematicBaseModel)
        string(trial.Inputs.MarkerFile)
        string(trial.Inputs.InitializationIkTemplate)
    ];

    inputLabels = [
        "Kinematic base model"
        "Marker file"
        "Initialization IK template"
    ];

    for inputIndex = 1:numel(inputFiles)

        assert(isfile(inputFiles(inputIndex)), ...
            "PipelineInitialization:InputNotFound", ...
            "%s was not found:\n%s", ...
            inputLabels(inputIndex), ...
            inputFiles(inputIndex));
    end

    paths = ...
        trial.Paths.Initialization;

    localEnsureDirectory(paths.Directory);
    localEnsureDirectory(paths.QcDirectory);

    if ~overwrite
        localAssertOutputsAbsent( ...
            paths, ...
            executeIk, ...
            writeQc, ...
            saveCheckpoint);
    end

    if printProgress

        fprintf( ...
            "\n=== Process 1: %s ===\n", ...
            trial.DisplayName);

        fprintf( ...
            "Marker file:\n%s\n", ...
            trial.Inputs.MarkerFile);

        fprintf( ...
            "Output directory:\n%s\n", ...
            paths.Directory);
    end

    %% Build Model A

    modelAResult = ...
        modelprep.buildInitializationModel( ...
            trial.Inputs.KinematicBaseModel, ...
            paths.ModelAFile);

    if writeQc

        writetable( ...
            modelAResult.Inspection.Coordinates, ...
            paths.CoordinateConfigurationCsv);

        writetable( ...
            modelAResult.Inspection.Constraints, ...
            paths.ConstraintConfigurationCsv);
    end

    %% Validate Model A

    modelAInspection = ...
        modelprep.inspectModel( ...
            paths.ModelAFile);

    coordinateCount = ...
        height(modelAInspection.Coordinates);

    constraintCount = ...
        height(modelAInspection.Constraints);

    assert(coordinateCount == expectedCoordinateCount, ...
        "PipelineInitialization:UnexpectedCoordinateCount", ...
        "Expected %d coordinates but found %d.", ...
        expectedCoordinateCount, ...
        coordinateCount);

    assert(constraintCount == expectedConstraintCount, ...
        "PipelineInitialization:UnexpectedConstraintCount", ...
        "Expected %d constraints but found %d.", ...
        expectedConstraintCount, ...
        constraintCount);

    allCoordinateNames = ...
        modelAInspection.Coordinates.Coordinate;

    modelAValidation = ...
        modelprep.validateModelConfiguration( ...
            paths.ModelAFile, ...
            "ExpectedUnlocked", ...
                allCoordinateNames, ...
            "ExpectedConstraintsEnforced", ...
                true, ...
            "ThrowOnFailure", ...
                true);

    assert(modelAValidation.Passed, ...
        "PipelineInitialization:ModelAValidationFailed", ...
        "Model A configuration validation failed.");

    %% Prepare initialization-IK setup

    toolName = ...
        trial.TrialStem + ...
        "_initialization_ik";

    ikSetupResult = ...
        opensimrun.prepareInverseKinematicsSetup( ...
            trial.Inputs.InitializationIkTemplate, ...
            paths.IkSetupFile, ...
            "ModelFile", ...
                paths.ModelAFile, ...
            "MarkerFile", ...
                trial.Inputs.MarkerFile, ...
            "OutputMotionFile", ...
                paths.IkMotionFile, ...
            "TimeRange", ...
                timeRangeSec, ...
            "ToolName", ...
                toolName, ...
            "Overwrite", ...
                overwrite);

    %% Return early when only setup preparation was requested

    if ~executeIk

        result = localMakeResult( ...
            trial, ...
            paths, ...
            timeRangeSec, ...
            modelAResult, ...
            modelAValidation, ...
            ikSetupResult, ...
            struct, ...
            struct, ...
            table, ...
            table, ...
            "", ...
            false, ...
            toc(stageStart));

        if printProgress

            fprintf( ...
                ["Initialization IK execution was disabled. " ...
                 "Model A and setup XML are ready for review.\n"]);
        end

        return;
    end

    %% Run initialization IK

    ikRunResult = ...
        opensimrun.runInverseKinematicsSetup( ...
            paths.IkSetupFile, ...
            "ModelInput", ...
                paths.ModelAFile, ...
            "ExpectedOutputMotionFile", ...
                paths.IkMotionFile, ...
            "Overwrite", ...
                overwrite);

    %% Audit initialization-IK output

    assert(isfile(paths.IkMotionFile), ...
        "PipelineInitialization:IkMotionMissing", ...
        "Initialization IK output was not found:\n%s", ...
        paths.IkMotionFile);

    ikMotion = ...
        opensimio.readMot( ...
            paths.IkMotionFile);

    assert(all(isfinite(ikMotion.Time)), ...
        "PipelineInitialization:InvalidIkTime", ...
        "IK time vector contains non-finite values.");

    assert(all(diff(ikMotion.Time) > 0), ...
        "PipelineInitialization:NonmonotonicIkTime", ...
        "IK time vector is not strictly increasing.");

    assert(all(isfinite(ikMotion.Data), "all"), ...
        "PipelineInitialization:NonfiniteIkData", ...
        "IK output contains non-finite coordinate values.");

    normalizedLabels = ...
        localNormalizeMotionLabels( ...
            ikMotion.Labels);

    modelCoordinates = ...
        string( ...
            modelAInspection.Coordinates.Coordinate);

    missingCoordinateColumns = ...
        setdiff( ...
            modelCoordinates, ...
            normalizedLabels, ...
            "stable");

    assert(isempty(missingCoordinateColumns), ...
        "PipelineInitialization:MissingIkCoordinates", ...
        "IK output is missing coordinate columns: %s", ...
        strjoin(missingCoordinateColumns, ", "));

    coordinateAudit = ...
        localBuildCoordinateAudit( ...
            ikMotion, ...
            normalizedLabels, ...
            modelAInspection.Coordinates, ...
            reviewCoordinates);

    groups = ...
        modelprep.coordinateGroups();

    attentionCoordinates = unique([
        "aux4jnt_r3"
        "aux4jnt_r1"
        "aux4jnt_r2"
        string(groups.IndependentOutOfPlane(:))
        string(groups.DependentOutOfPlane(:))
    ], "stable");

    attentionAudit = ...
        coordinateAudit( ...
            ismember( ...
                coordinateAudit.Coordinate, ...
                attentionCoordinates), ...
            :);

    if writeQc

        writetable( ...
            coordinateAudit, ...
            paths.MotionCoordinateAuditCsv);
    end

    ikMotionSummary = struct( ...
        "NumRows", ...
            ikMotion.NumRows, ...
        "NumColumns", ...
            ikMotion.NumColumns, ...
        "StartTime", ...
            ikMotion.Time(1), ...
        "EndTime", ...
            ikMotion.Time(end), ...
        "InDegrees", ...
            ikMotion.InDegrees);

    %% Save checkpoint

    checkpointFile = "";

    if saveCheckpoint

        checkpoint = struct;

        checkpoint.SchemaVersion = 1;
        checkpoint.Stage = "initialization_ik";
        checkpoint.Trial = trial;

        checkpoint.Configuration = struct( ...
            "TimeRangeSec", ...
                timeRangeSec, ...
            "ExpectedCoordinateCount", ...
                expectedCoordinateCount, ...
            "ExpectedConstraintCount", ...
                expectedConstraintCount, ...
            "ReviewCoordinates", ...
                reviewCoordinates, ...
            "Overwrite", ...
                overwrite);

        checkpoint.Paths = paths;
        checkpoint.ModelAResult = modelAResult;
        checkpoint.ModelAValidation = modelAValidation;
        checkpoint.IkSetupResult = ikSetupResult;
        checkpoint.IkRunResult = ...
            localSerializableIkRunResult( ...
                ikRunResult);

        checkpoint.IkMotionSummary = ...
            ikMotionSummary;

        checkpoint.CoordinateAudit = ...
            coordinateAudit;

        checkpoint.AttentionAudit = ...
            attentionAudit;

        checkpoint.Completed = true;
        checkpoint.CompletedAt = ...
            string(datetime("now"));

        save( ...
            paths.CheckpointFile, ...
            "checkpoint");

        checkpointFile = ...
            paths.CheckpointFile;
    end

    %% Return result

    result = localMakeResult( ...
        trial, ...
        paths, ...
        timeRangeSec, ...
        modelAResult, ...
        modelAValidation, ...
        ikSetupResult, ...
        localSerializableIkRunResult(ikRunResult), ...
        ikMotionSummary, ...
        coordinateAudit, ...
        attentionAudit, ...
        checkpointFile, ...
        true, ...
        toc(stageStart));

    if printProgress

        fprintf( ...
            "Initialization IK completed in %.3f s.\n", ...
            result.DurationSeconds);

        fprintf( ...
            "IK motion:\n%s\n", ...
            paths.IkMotionFile);

        if strlength(checkpointFile) > 0

            fprintf( ...
                "Checkpoint:\n%s\n", ...
                checkpointFile);
        end
    end
end


function localValidateTrialContext(trial)

    requiredFields = [
        "SchemaVersion"
        "ConditionDeg"
        "TrialNumber"
        "TrialStem"
        "DisplayName"
        "Inputs"
        "Paths"
    ];

    missingFields = ...
        requiredFields( ...
            ~isfield( ...
                trial, ...
                cellstr(requiredFields)));

    assert(isempty(missingFields), ...
        "PipelineInitialization:TrialContextIncomplete", ...
        "Trial context is missing fields: %s", ...
        strjoin(missingFields, ", "));

    assert(isfield(trial.Paths, "Initialization"), ...
        "PipelineInitialization:InitializationPathsMissing", ...
        "trial.Paths.Initialization is required.");
end


function localEnsureDirectory(directory)

    directory = string(directory);

    if ~isfolder(directory)
        mkdir(directory);
    end
end


function localAssertOutputsAbsent( ...
        paths, executeIk, writeQc, saveCheckpoint)

    outputFiles = [
        string(paths.ModelAFile)
        string(paths.IkSetupFile)
    ];

    if executeIk
        outputFiles(end+1,1) = ...
            string(paths.IkMotionFile);
    end

    if writeQc

        outputFiles = [
            outputFiles
            string(paths.CoordinateConfigurationCsv)
            string(paths.ConstraintConfigurationCsv)
        ];

        if executeIk

            outputFiles(end+1,1) = ...
                string(paths.MotionCoordinateAuditCsv);
        end
    end

    if executeIk && saveCheckpoint

        outputFiles(end+1,1) = ...
            string(paths.CheckpointFile);
    end

    existingFiles = ...
        outputFiles(isfile(outputFiles));

    if ~isempty(existingFiles)

        error( ...
            "PipelineInitialization:OutputExists", ...
            ["Process-1 output already exists and Overwrite=false:\n%s"], ...
            strjoin(existingFiles, newline));
    end
end


function normalizedLabels = ...
        localNormalizeMotionLabels(labels)

    labels = ...
        string(labels(:));

    normalizedLabels = ...
        strings(size(labels));

    for labelIndex = 1:numel(labels)

        label = ...
            regexprep( ...
                labels(labelIndex), ...
                "/value$", ...
                "");

        labelParts = ...
            split(label, "/");

        labelParts = ...
            labelParts( ...
                strlength(labelParts) > 0);

        if isempty(labelParts)

            normalizedLabels(labelIndex) = ...
                label;

        else

            normalizedLabels(labelIndex) = ...
                labelParts(end);
        end
    end
end


function audit = localBuildCoordinateAudit( ...
        motion, normalizedLabels, coordinateTable, ...
        reviewCoordinates)

    modelCoordinates = ...
        string(coordinateTable.Coordinate);

    reviewCoordinates = ...
        intersect( ...
            string(reviewCoordinates(:)), ...
            modelCoordinates, ...
            "stable");

    nCoordinates = ...
        numel(reviewCoordinates);

    Coordinate = ...
        reviewCoordinates;

    CoordinateType = ...
        strings(nCoordinates,1);

    MinimumDisplay = ...
        nan(nCoordinates,1);

    MaximumDisplay = ...
        nan(nCoordinates,1);

    RangeDisplay = ...
        nan(nCoordinates,1);

    StandardDeviationDisplay = ...
        nan(nCoordinates,1);

    DisplayUnit = ...
        strings(nCoordinates,1);

    for coordinateIndex = 1:nCoordinates

        coordinateName = ...
            reviewCoordinates(coordinateIndex);

        motionColumn = find( ...
            normalizedLabels == coordinateName, ...
            1);

        modelRow = find( ...
            modelCoordinates == coordinateName, ...
            1);

        assert(~isempty(motionColumn) && ...
            ~isempty(modelRow), ...
            "PipelineInitialization:CoordinateAuditLookupFailed", ...
            "Could not resolve coordinate %s.", ...
            coordinateName);

        coordinateType = ...
            string( ...
                coordinateTable. ...
                CoordinateType(modelRow));

        values = ...
            motion.Data(:, motionColumn);

        if coordinateType == "rotation"

            if islogical(motion.InDegrees) && ...
                    motion.InDegrees

                displayValues = ...
                    values;

            else

                displayValues = ...
                    rad2deg(values);
            end

            displayUnit = "deg";

        else

            displayValues = ...
                values;

            displayUnit = "m";
        end

        CoordinateType(coordinateIndex) = ...
            coordinateType;

        MinimumDisplay(coordinateIndex) = ...
            min(displayValues, [], "omitnan");

        MaximumDisplay(coordinateIndex) = ...
            max(displayValues, [], "omitnan");

        RangeDisplay(coordinateIndex) = ...
            MaximumDisplay(coordinateIndex) - ...
            MinimumDisplay(coordinateIndex);

        StandardDeviationDisplay(coordinateIndex) = ...
            std(displayValues, "omitnan");

        DisplayUnit(coordinateIndex) = ...
            displayUnit;
    end

    audit = table( ...
        Coordinate, ...
        CoordinateType, ...
        MinimumDisplay, ...
        MaximumDisplay, ...
        RangeDisplay, ...
        StandardDeviationDisplay, ...
        DisplayUnit);
end


function runResult = ...
        localSerializableIkRunResult(runResult)

    removableFields = ...
        intersect( ...
            fieldnames(runResult), ...
            {'Tool','Model'});

    if ~isempty(removableFields)

        runResult = ...
            rmfield( ...
                runResult, ...
                removableFields);
    end
end


function result = localMakeResult( ...
        trial, paths, timeRangeSec, ...
        modelAResult, modelAValidation, ...
        ikSetupResult, ikRunResult, ...
        ikMotionSummary, coordinateAudit, ...
        attentionAudit, checkpointFile, ...
        completed, durationSeconds)

    result = struct;

    result.Stage = ...
        "initialization_ik";

    result.Trial = ...
        trial;

    result.Paths = ...
        paths;

    result.TimeRangeSec = ...
        timeRangeSec;

    result.ModelAResult = ...
        modelAResult;

    result.ModelAValidation = ...
        modelAValidation;

    result.IkSetupResult = ...
        ikSetupResult;

    result.IkRunResult = ...
        ikRunResult;

    result.IkMotionSummary = ...
        ikMotionSummary;

    result.CoordinateAudit = ...
        coordinateAudit;

    result.AttentionAudit = ...
        attentionAudit;

    result.CheckpointFile = ...
        string(checkpointFile);

    result.Completed = ...
        logical(completed);

    result.DurationSeconds = ...
        double(durationSeconds);
end
