function result = runModelBTrial( ...
        projectCfg, trial, varargin)
%RUNMODELBTRIAL Run Process 2 for one resolved trial.
%
% result = pipeline.runModelBTrial(projectCfg, trial)
%
% The trial input must be created by:
%
%   trial = pipeline.resolveTrialContext( ...
%       projectCfg, conditionDeg, trialNumber);
%
% This worker is the canonical implementation for:
%   1. validating the completed Process-1 checkpoint;
%   2. optionally filtering initialization IK for lock extraction;
%   3. extracting trial-specific Model B lock values;
%   4. building and validating Model B;
%   5. preparing and running final IK;
%   6. auditing the requested locked coordinates;
%   7. summarizing dependent out-of-plane and sagittal motion;
%   8. writing Process-2 QC outputs and checkpoint.
%
% Both the single-trial example and Batch Process 2 should call this
% function. Neither orchestration layer should reimplement these steps.
%
% NAME-VALUE OPTIONS
%
%   ExecuteFinalIk
%       true (default). When false, Model B and the final-IK setup are
%       prepared and validated, but final IK and post-IK QC are not run.
%
%   Overwrite
%       Defaults to projectCfg.overwriteExisting.
%
%   WriteQc
%       true (default).
%
%   SaveCheckpoint
%       true (default). Checkpointing occurs only after final IK and all
%       required post-IK QC complete successfully.
%
%   PrintProgress
%       true (default).
%
% RETURN
%
%   result.Stage
%   result.Trial
%   result.Paths
%   result.TrialTimeRangeSec
%   result.LockWindowSec
%   result.LockExtractionMotionFile
%   result.LockFilterResult
%   result.LockValues
%   result.ModelBResult
%   result.ModelBValidation
%   result.DependentCoordinateState
%   result.IndependentSagittalState
%   result.FinalIkSetupResult
%   result.FinalIkRunResult
%   result.FinalIkMotionSummary
%   result.LockedCoordinateAudit
%   result.DependentOutOfPlaneSummary
%   result.IndependentSagittalSummary
%   result.DependentSagittalSummary
%   result.SagittalMotionSummary
%   result.CheckpointFile
%   result.Completed
%   result.DurationSeconds

    assert(isstruct(projectCfg), ...
        "PipelineModelB:InvalidProjectConfig", ...
        "projectCfg must be a struct.");

    localValidateTrialContext(trial);

    defaultOverwrite = false;

    if isfield(projectCfg, "overwriteExisting")
        defaultOverwrite = projectCfg.overwriteExisting;
    end

    parser = inputParser;
    parser.FunctionName = "pipeline.runModelBTrial";

    addRequired(parser, ...
        "projectCfg", ...
        @isstruct);

    addRequired(parser, ...
        "trial", ...
        @isstruct);

    addParameter(parser, ...
        "ExecuteFinalIk", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "Overwrite", ...
        defaultOverwrite, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "WriteQc", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "SaveCheckpoint", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "PrintProgress", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, ...
        projectCfg, trial, varargin{:});

    executeFinalIk = parser.Results.ExecuteFinalIk;
    overwrite = parser.Results.Overwrite;
    writeQc = parser.Results.WriteQc;
    saveCheckpoint = parser.Results.SaveCheckpoint;
    printProgress = parser.Results.PrintProgress;

    stageStart = tic;

    %% Resolve stage configuration

    localRequireField( ...
        projectCfg, ...
        "pipeline", ...
        "projectCfg.pipeline");

    localRequireField( ...
        projectCfg.pipeline, ...
        "modelB", ...
        "projectCfg.pipeline.modelB");

    localRequireField( ...
        projectCfg.pipeline.modelB, ...
        "lockWindowSec", ...
        "projectCfg.pipeline.modelB.lockWindowSec");

    lockWindowSec = double( ...
        projectCfg.pipeline.modelB.lockWindowSec(:)).';

    assert(numel(lockWindowSec) == 2 && ...
        all(isfinite(lockWindowSec)) && ...
        lockWindowSec(2) > lockWindowSec(1), ...
        "PipelineModelB:InvalidLockWindow", ...
        "Model B lock window must be [start end] with end > start.");

    localRequireField( ...
        projectCfg, ...
        "qc", ...
        "projectCfg.qc");

    localRequireField( ...
        projectCfg.qc, ...
        "lockExtraction", ...
        "projectCfg.qc.lockExtraction");

    localRequireField( ...
        projectCfg.qc, ...
        "lockExtractionFilter", ...
        "projectCfg.qc.lockExtractionFilter");

    localRequireField( ...
        projectCfg.qc, ...
        "lockAudit", ...
        "projectCfg.qc.lockAudit");

    extractionQc = projectCfg.qc.lockExtraction;
    filterQc = projectCfg.qc.lockExtractionFilter;
    auditQc = projectCfg.qc.lockAudit;

    %% Resolve paths and prerequisites

    initializationPaths = trial.Paths.Initialization;
    paths = trial.Paths.ModelB;

    localEnsureDirectory(paths.Directory);
    localEnsureDirectory(paths.QcDirectory);

    requiredInputs = [
        string(initializationPaths.CheckpointFile)
        string(initializationPaths.ModelAFile)
        string(initializationPaths.IkMotionFile)
        string(trial.Inputs.KinematicBaseModel)
        string(trial.Inputs.InitializationIkTemplate)
        string(trial.Inputs.MarkerFile)
    ];

    requiredLabels = [
        "Process-1 checkpoint"
        "Model A"
        "Initialization IK motion"
        "Kinematic base model"
        "IK template"
        "Marker file"
    ];

    for inputIndex = 1:numel(requiredInputs)

        assert(isfile(requiredInputs(inputIndex)), ...
            "PipelineModelB:InputNotFound", ...
            "%s was not found:\n%s", ...
            requiredLabels(inputIndex), ...
            requiredInputs(inputIndex));
    end

    if ~overwrite

        localAssertOutputsAbsent( ...
            paths, ...
            filterQc.enabled, ...
            executeFinalIk, ...
            writeQc, ...
            saveCheckpoint);
    end

    if printProgress

        fprintf( ...
            "\n=== Process 2: %s ===\n", ...
            trial.DisplayName);

        fprintf( ...
            "Process-1 checkpoint:\n%s\n", ...
            initializationPaths.CheckpointFile);

        fprintf( ...
            "Process-2 output directory:\n%s\n", ...
            paths.Directory);
    end

    %% Load and validate Process-1 checkpoint

    checkpointA = localLoadProcess1Checkpoint( ...
        initializationPaths.CheckpointFile);

    assert(checkpointA.Completed, ...
        "PipelineModelB:Process1Incomplete", ...
        "The Process-1 checkpoint is not marked complete.");

    assert(string(checkpointA.Stage) == "initialization_ik", ...
        "PipelineModelB:UnexpectedProcess1Stage", ...
        "Expected Process-1 stage 'initialization_ik' but found '%s'.", ...
        string(checkpointA.Stage));

    assert(checkpointA.Trial.ConditionDeg == trial.ConditionDeg, ...
        "PipelineModelB:ConditionMismatch", ...
        "Resolved condition is %g deg, but Process 1 contains %g deg.", ...
        trial.ConditionDeg, ...
        checkpointA.Trial.ConditionDeg);

    assert(checkpointA.Trial.TrialNumber == trial.TrialNumber, ...
        "PipelineModelB:TrialMismatch", ...
        "Resolved trial is %d, but Process 1 contains trial %d.", ...
        trial.TrialNumber, ...
        checkpointA.Trial.TrialNumber);

    assert(logical(checkpointA.ModelAValidation.Passed), ...
        "PipelineModelB:ModelAWasInvalid", ...
        "The Process-1 checkpoint reports that Model A failed validation.");

    assert(isfield(checkpointA.IkRunResult, "RunSucceeded") && ...
        logical(checkpointA.IkRunResult.RunSucceeded), ...
        "PipelineModelB:InitializationIkFailed", ...
        "The Process-1 checkpoint reports that initialization IK failed.");

    trialTimeRangeSec = [
        double(checkpointA.IkMotionSummary.StartTime)
        double(checkpointA.IkMotionSummary.EndTime)
    ].';

    assert(lockWindowSec(1) >= trialTimeRangeSec(1) && ...
        lockWindowSec(2) <= trialTimeRangeSec(2), ...
        "PipelineModelB:LockWindowOutsideTrial", ...
        "Lock window [%.9g, %.9g] must lie within trial range " + ...
        "[%.9g, %.9g].", ...
        lockWindowSec(1), ...
        lockWindowSec(2), ...
        trialTimeRangeSec(1), ...
        trialTimeRangeSec(2));

    if printProgress

        fprintf( ...
            "Process-1 checkpoint validated. Trial range: " + ...
            "%.5f to %.5f s.\n", ...
            trialTimeRangeSec(1), ...
            trialTimeRangeSec(2));
    end

    %% Coordinate groups

    groups = modelprep.coordinateGroups();

    requiredGroupFields = [
        "Root"
        "IndependentOutOfPlane"
        "DependentOutOfPlane"
        "IndependentSagittal"
        "DependentSagittal"
        "Sagittal"
        "AllDependent"
        "FinalIkLocked"
    ];

    missingGroupFields = requiredGroupFields( ...
        ~isfield(groups, cellstr(requiredGroupFields)));

    assert(isempty(missingGroupFields), ...
        "PipelineModelB:CoordinateGroupsMissing", ...
        "modelprep.coordinateGroups is missing: %s", ...
        strjoin(missingGroupFields, ", "));

    %% Filter initialization IK for lock extraction

    lockExtractionMotionFile = ...
        initializationPaths.IkMotionFile;

    lockFilterResult = struct;
    lockFilterResult.Enabled = logical(filterQc.enabled);
    lockFilterResult.SourceMotionFile = ...
        initializationPaths.IkMotionFile;
    lockFilterResult.FilteredMotionFile = "";
    lockFilterResult.AuditFile = "";
    lockFilterResult.FilteredCoordinates = strings(1,0);

    if filterQc.enabled

        filterCoordinates = reshape( ...
            string(filterQc.filterCoordinates), ...
            1, []);

        assert(~isempty(filterCoordinates), ...
            "PipelineModelB:NoFilterCoordinates", ...
            "Filtering is enabled but filterCoordinates is empty.");

        assert(all(ismember( ...
                filterCoordinates, ...
                groups.FinalIkLocked)), ...
            "PipelineModelB:UnexpectedFilterCoordinate", ...
            "All lock-extraction filter coordinates must belong to " + ...
            "groups.FinalIkLocked. Requested: %s", ...
            strjoin(filterCoordinates, ", "));

        filterResult = ...
            modelprep.filterCoordinateMotion( ...
                initializationPaths.IkMotionFile, ...
                filterCoordinates, ...
                "CutoffHz", ...
                    filterQc.selectedCutoffHz, ...
                "PrototypeOrder", ...
                    filterQc.prototypeOrder, ...
                "AuditWindow", ...
                    lockWindowSec);

        opensimio.writeOpenSimTable( ...
            paths.FilteredInitialIkMotionFile, ...
            filterResult.Motion);

        if writeQc

            writetable( ...
                filterResult.Audit, ...
                paths.LockFilterAuditCsv);
        end

        lockExtractionMotionFile = ...
            paths.FilteredInitialIkMotionFile;

        lockFilterResult.Enabled = true;
        lockFilterResult.FilteredMotionFile = ...
            paths.FilteredInitialIkMotionFile;

        if writeQc
            lockFilterResult.AuditFile = ...
                paths.LockFilterAuditCsv;
        end

        lockFilterResult.FilteredCoordinates = ...
            filterResult.FilteredCoordinates;

        lockFilterResult.SampleRateHz = ...
            filterResult.SampleRateHz;

        lockFilterResult.CutoffHz = ...
            filterResult.CutoffHz;

        lockFilterResult.PrototypeOrder = ...
            filterResult.PrototypeOrder;

        lockFilterResult.EffectiveZeroPhaseOrder = ...
            filterResult.EffectiveZeroPhaseOrder;

        lockFilterResult.AuditWindow = ...
            filterResult.AuditWindow;

        lockFilterResult.NumAuditSamples = ...
            filterResult.NumAuditSamples;

        lockFilterResult.Audit = ...
            filterResult.Audit;

        if printProgress

            fprintf( ...
                "Filtered initialization IK for lock extraction.\n" + ...
                "Coordinates: %s\n" + ...
                "Cutoff: %.3f Hz\n" + ...
                "Prototype order: %d " + ...
                "(effective zero-phase order %d)\n" + ...
                "Filtered motion:\n%s\n", ...
                strjoin(filterCoordinates, ", "), ...
                filterResult.CutoffHz, ...
                filterResult.PrototypeOrder, ...
                filterResult.EffectiveZeroPhaseOrder, ...
                paths.FilteredInitialIkMotionFile);
        end

    elseif printProgress

        fprintf( ...
            "Lock-extraction filtering is disabled. " + ...
            "Using raw Process-1 initialization IK.\n");
    end

    %% Extract trial-specific Model B lock values

    lockValues = ...
        modelprep.extractStableCoordinateValues( ...
            lockExtractionMotionFile, ...
            initializationPaths.ModelAFile, ...
            groups.FinalIkLocked, ...
            lockWindowSec, ...
            "Method", ...
                extractionQc.statistic, ...
            "RotationToleranceDeg", ...
                extractionQc.rotationToleranceDeg, ...
            "TranslationToleranceM", ...
                extractionQc.translationToleranceM, ...
            "OtherTolerance", ...
                extractionQc.otherToleranceSI, ...
            "RequireStable", ...
                false, ...
            "MinimumSamples", ...
                extractionQc.minimumSamples);

    if writeQc

        writetable( ...
            lockValues, ...
            paths.LockValuesCsv);
    end

    if extractionQc.requireStable

        assert(all(lockValues.IsStable), ...
            "PipelineModelB:UnstableLockValues", ...
            "One or more lock coordinates are unstable in the configured " + ...
            "window [%.5f, %.5f] s.", ...
            lockWindowSec(1), ...
            lockWindowSec(2));
    end

    %% Build Model B

    modelBResult = ...
        modelprep.buildLockedIkModel( ...
            trial.Inputs.KinematicBaseModel, ...
            lockValues, ...
            paths.ModelBFile, ...
            "CoordinateNames", ...
                groups.FinalIkLocked, ...
            "RequireStable", ...
                extractionQc.requireStable);

    if writeQc

        writetable( ...
            modelBResult.Inspection.Coordinates, ...
            paths.CoordinateConfigurationCsv);

        writetable( ...
            modelBResult.Inspection.Constraints, ...
            paths.ConstraintConfigurationCsv);
    end

    %% Validate Model B configuration

    modelBInspection = ...
        modelprep.inspectModel( ...
            paths.ModelBFile);

    allCoordinateNames = ...
        string(modelBInspection.Coordinates.Coordinate);

    expectedUnlocked = ...
        setdiff( ...
            allCoordinateNames, ...
            string(groups.FinalIkLocked), ...
            "stable");

    modelBValidation = ...
        modelprep.validateModelConfiguration( ...
            paths.ModelBFile, ...
            "ExpectedLocked", ...
                groups.FinalIkLocked, ...
            "ExpectedUnlocked", ...
                expectedUnlocked, ...
            "ExpectedConstraintsEnforced", ...
                true, ...
            "ThrowOnFailure", ...
                true);

    assert(modelBValidation.Passed, ...
        "PipelineModelB:ModelBValidationFailed", ...
        "Model B configuration validation failed.");

    dependentRows = ismember( ...
        string(modelBInspection.Coordinates.Coordinate), ...
        string(groups.AllDependent));

    dependentCoordinateState = ...
        modelBInspection.Coordinates( ...
            dependentRows, ...
            { ...
                'Coordinate'
                'DefaultLocked'
                'StateLocked'
                'StateDependent'
                'StateConstrained'
            });

    assert(height(dependentCoordinateState) == ...
        numel(groups.AllDependent), ...
        "PipelineModelB:DependentCoordinateCountMismatch", ...
        "Expected %d dependent coordinates but found %d.", ...
        numel(groups.AllDependent), ...
        height(dependentCoordinateState));

    assert(all(~dependentCoordinateState.DefaultLocked), ...
        "PipelineModelB:DependentCoordinateDefaultLocked", ...
        "One or more dependent auxiliary coordinates are default-locked.");

    assert(all(~dependentCoordinateState.StateLocked), ...
        "PipelineModelB:DependentCoordinateStateLocked", ...
        "One or more dependent auxiliary coordinates are state-locked.");

    assert(all(dependentCoordinateState.StateDependent), ...
        "PipelineModelB:DependentCoordinateNotDependent", ...
        "One or more expected auxiliary coordinates are not dependent.");

    assert(all(dependentCoordinateState.StateConstrained), ...
        "PipelineModelB:DependentCoordinateUnconstrained", ...
        "One or more expected auxiliary coordinates are not constrained.");

    independentSagittalRows = ismember( ...
        string(modelBInspection.Coordinates.Coordinate), ...
        string(groups.IndependentSagittal));

    independentSagittalState = ...
        modelBInspection.Coordinates( ...
            independentSagittalRows, ...
            { ...
                'Coordinate'
                'DefaultLocked'
                'StateLocked'
                'StateDependent'
                'StateConstrained'
            });

    assert(height(independentSagittalState) == ...
        numel(groups.IndependentSagittal), ...
        "PipelineModelB:IndependentSagittalCountMismatch", ...
        "Expected %d independent sagittal coordinates but found %d.", ...
        numel(groups.IndependentSagittal), ...
        height(independentSagittalState));

    assert(all(~independentSagittalState.DefaultLocked), ...
        "PipelineModelB:IndependentSagittalDefaultLocked", ...
        "One or more independent sagittal coordinates are default-locked.");

    assert(all(~independentSagittalState.StateLocked), ...
        "PipelineModelB:IndependentSagittalStateLocked", ...
        "One or more independent sagittal coordinates are state-locked.");

    assert(all(~independentSagittalState.StateDependent), ...
        "PipelineModelB:IndependentSagittalUnexpectedlyDependent", ...
        "One or more independent sagittal coordinates are dependent.");

    if writeQc

        writetable( ...
            dependentCoordinateState, ...
            paths.DependentCoordinateStateCsv);

        writetable( ...
            independentSagittalState, ...
            paths.IndependentSagittalStateCsv);
    end

    %% Prepare final-IK setup

    finalIkSetupResult = ...
        opensimrun.prepareInverseKinematicsSetup( ...
            trial.Inputs.InitializationIkTemplate, ...
            paths.FinalIkSetupFile, ...
            "ModelFile", ...
                paths.ModelBFile, ...
            "MarkerFile", ...
                trial.Inputs.MarkerFile, ...
            "OutputMotionFile", ...
                paths.FinalIkMotionFile, ...
            "TimeRange", ...
                trialTimeRangeSec, ...
            "ToolName", ...
                trial.TrialStem + "_final_ik", ...
            "Overwrite", ...
                overwrite);

    %% Return early if final IK execution is disabled

    if ~executeFinalIk

        result = localMakeResult( ...
            trial, ...
            paths, ...
            trialTimeRangeSec, ...
            lockWindowSec, ...
            lockExtractionMotionFile, ...
            lockFilterResult, ...
            lockValues, ...
            modelBResult, ...
            modelBValidation, ...
            dependentCoordinateState, ...
            independentSagittalState, ...
            finalIkSetupResult, ...
            struct, ...
            struct, ...
            struct, ...
            struct, ...
            struct, ...
            struct, ...
            struct, ...
            "", ...
            false, ...
            toc(stageStart));

        if printProgress

            fprintf( ...
                "Final IK execution is disabled. " + ...
                "Model B and the final-IK setup are ready for review.\n");
        end

        return;
    end

    %% Run final IK

    finalIkRunResult = ...
        opensimrun.runInverseKinematicsSetup( ...
            paths.FinalIkSetupFile, ...
            "ModelInput", ...
                paths.ModelBFile, ...
            "ExpectedOutputMotionFile", ...
                paths.FinalIkMotionFile, ...
            "Overwrite", ...
                overwrite);

    finalIkRunSummary = ...
        localSerializableIkRunResult( ...
            finalIkRunResult);

    %% Audit requested locked coordinates

    lockedCoordinateAudit = ...
        modelprep.auditLockedCoordinates( ...
            paths.FinalIkMotionFile, ...
            lockValues, ...
            "ModelInput", ...
                paths.ModelBFile, ...
            "TimeWindow", ...
                trialTimeRangeSec, ...
            "Statistic", ...
                auditQc.statistic, ...
            "RotationRangeToleranceDeg", ...
                auditQc.rotationRangeToleranceDeg, ...
            "TranslationRangeToleranceM", ...
                auditQc.translationRangeToleranceM, ...
            "OtherRangeToleranceSI", ...
                auditQc.otherRangeToleranceSI, ...
            "RotationMatchToleranceDeg", ...
                auditQc.rotationMatchToleranceDeg, ...
            "TranslationMatchToleranceM", ...
                auditQc.translationMatchToleranceM, ...
            "OtherMatchToleranceSI", ...
                auditQc.otherMatchToleranceSI, ...
            "MinimumSamples", ...
                auditQc.minimumSamples, ...
            "RequirePass", ...
                false);

    if writeQc

        writetable( ...
            lockedCoordinateAudit.Table, ...
            paths.LockedCoordinateAuditCsv);
    end

    if auditQc.requirePass

        assert(lockedCoordinateAudit.Passed, ...
            "PipelineModelB:LockedCoordinateAuditFailed", ...
            "Locked-coordinate QC failed for: %s", ...
            strjoin( ...
                lockedCoordinateAudit.FailedCoordinates, ...
                ", "));
    end

    %% Summarize final-IK motion

    dependentOutOfPlaneSummary = ...
        modelprep.summarizeCoordinateMotion( ...
            paths.FinalIkMotionFile, ...
            groups.DependentOutOfPlane, ...
            "TimeWindow", ...
                trialTimeRangeSec, ...
            "BaselineWindow", ...
                lockWindowSec, ...
            "BaselineStatistic", ...
                auditQc.statistic);

    independentSagittalSummary = ...
        modelprep.summarizeCoordinateMotion( ...
            paths.FinalIkMotionFile, ...
            groups.IndependentSagittal, ...
            "TimeWindow", ...
                trialTimeRangeSec, ...
            "BaselineWindow", ...
                lockWindowSec, ...
            "BaselineStatistic", ...
                auditQc.statistic);

    dependentSagittalSummary = ...
        modelprep.summarizeCoordinateMotion( ...
            paths.FinalIkMotionFile, ...
            groups.DependentSagittal, ...
            "TimeWindow", ...
                trialTimeRangeSec, ...
            "BaselineWindow", ...
                lockWindowSec, ...
            "BaselineStatistic", ...
                auditQc.statistic);

    sagittalMotionSummary = ...
        modelprep.summarizeCoordinateMotion( ...
            paths.FinalIkMotionFile, ...
            groups.Sagittal, ...
            "TimeWindow", ...
                trialTimeRangeSec, ...
            "BaselineWindow", ...
                lockWindowSec, ...
            "BaselineStatistic", ...
                auditQc.statistic);

    maxDependentOutOfPlaneRange = max( ...
        dependentOutOfPlaneSummary.Summary.Range, ...
        [], ...
        "omitnan");

    if maxDependentOutOfPlaneRange > ...
            auditQc.rotationRangeToleranceDeg

        warning( ...
            "PipelineModelB:DependentOutOfPlaneVariation", ...
            "One or more dependent out-of-plane coordinates vary by " + ...
            "more than %.9g deg. Review %s.", ...
            auditQc.rotationRangeToleranceDeg, ...
            paths.DependentOutOfPlaneSummaryCsv);
    end

    if writeQc

        writetable( ...
            dependentOutOfPlaneSummary.Summary, ...
            paths.DependentOutOfPlaneSummaryCsv);

        writetable( ...
            independentSagittalSummary.Summary, ...
            paths.IndependentSagittalSummaryCsv);

        writetable( ...
            dependentSagittalSummary.Summary, ...
            paths.DependentSagittalSummaryCsv);

        writetable( ...
            sagittalMotionSummary.Summary, ...
            paths.SagittalSummaryCsv);

        writetable( ...
            sagittalMotionSummary.Trajectories, ...
            paths.SagittalTrajectoriesCsv);

        writetable( ...
            sagittalMotionSummary.RelativeTrajectories, ...
            paths.SagittalRelativeTrajectoriesCsv);
    end

    %% Final-IK motion summary

    finalIkMotion = ...
        opensimio.readMot( ...
            paths.FinalIkMotionFile);

    finalIkMotionSummary = struct( ...
        "NumRows", ...
            finalIkMotion.NumRows, ...
        "NumColumns", ...
            finalIkMotion.NumColumns, ...
        "StartTime", ...
            finalIkMotion.Time(1), ...
        "EndTime", ...
            finalIkMotion.Time(end), ...
        "InDegrees", ...
            finalIkMotion.InDegrees);

    %% Save canonical Process-2 checkpoint

    checkpointFile = "";

    if saveCheckpoint

        checkpoint = struct;

        checkpoint.SchemaVersion = 1;
        checkpoint.Stage = "model_b_final_ik";
        checkpoint.Trial = trial;

        checkpoint.Configuration = struct( ...
            "ConditionDeg", ...
                trial.ConditionDeg, ...
            "TrialNumber", ...
                trial.TrialNumber, ...
            "MarkerFile", ...
                trial.Inputs.MarkerFile, ...
            "TrialTimeRangeSec", ...
                trialTimeRangeSec, ...
            "LockWindowSec", ...
                lockWindowSec, ...
            "LockExtraction", ...
                extractionQc, ...
            "LockExtractionFilter", ...
                filterQc, ...
            "LockAudit", ...
                auditQc, ...
            "Overwrite", ...
                overwrite);

        % Temporary lowercase aliases retain compatibility with the current
        % Process-3 example until that stage is refactored.
        checkpoint.Configuration.conditionDeg = ...
            trial.ConditionDeg;

        checkpoint.Configuration.trialNumber = ...
            trial.TrialNumber;

        checkpoint.Configuration.markerFile = ...
            trial.Inputs.MarkerFile;

        checkpoint.Configuration.lockWindow = ...
            lockWindowSec;

        checkpoint.TrialTimeRange = ...
            trialTimeRangeSec;

        checkpoint.Paths = paths;

        checkpoint.InitializationCheckpointFile = ...
            initializationPaths.CheckpointFile;

        checkpoint.MarkerFile = ...
            trial.Inputs.MarkerFile;

        checkpoint.LockExtractionMotionFile = ...
            lockExtractionMotionFile;

        checkpoint.LockFilterResult = ...
            lockFilterResult;

        checkpoint.LockValues = ...
            lockValues;

        checkpoint.ModelBResult = ...
            modelBResult;

        checkpoint.ModelBValidation = ...
            modelBValidation;

        checkpoint.DependentCoordinateState = ...
            dependentCoordinateState;

        checkpoint.IndependentSagittalState = ...
            independentSagittalState;

        checkpoint.FinalIkSetupResult = ...
            finalIkSetupResult;

        checkpoint.FinalIkRunResult = ...
            finalIkRunSummary;

        checkpoint.FinalIkMotionSummary = ...
            finalIkMotionSummary;

        checkpoint.LockedCoordinateAudit = ...
            lockedCoordinateAudit;

        checkpoint.DependentOutOfPlaneSummary = ...
            dependentOutOfPlaneSummary;

        checkpoint.IndependentSagittalSummary = ...
            independentSagittalSummary;

        checkpoint.DependentSagittalSummary = ...
            dependentSagittalSummary;

        checkpoint.SagittalMotionSummary = ...
            sagittalMotionSummary;

        checkpoint.Completed = true;

        checkpoint.CompletedAt = ...
            string(datetime("now"));

        % Temporary compatibility alias for the existing Process-3 example.
        % Both variables reference the same schema and can be removed once
        % Process 3 is refactored to load the canonical "checkpoint" name.
        modelBCheckpoint = checkpoint; %#ok<NASGU>

        save( ...
            paths.CheckpointFile, ...
            "checkpoint", ...
            "modelBCheckpoint", ...
            "-v7.3");

        checkpointFile = ...
            paths.CheckpointFile;
    end

    %% Return

    result = localMakeResult( ...
        trial, ...
        paths, ...
        trialTimeRangeSec, ...
        lockWindowSec, ...
        lockExtractionMotionFile, ...
        lockFilterResult, ...
        lockValues, ...
        modelBResult, ...
        modelBValidation, ...
        dependentCoordinateState, ...
        independentSagittalState, ...
        finalIkSetupResult, ...
        finalIkRunSummary, ...
        finalIkMotionSummary, ...
        lockedCoordinateAudit, ...
        dependentOutOfPlaneSummary, ...
        independentSagittalSummary, ...
        dependentSagittalSummary, ...
        sagittalMotionSummary, ...
        checkpointFile, ...
        true, ...
        toc(stageStart));

    if printProgress

        fprintf( ...
            "Final IK completed in %.3f s.\n", ...
            finalIkRunSummary.DurationSeconds);

        fprintf( ...
            "Locked-coordinate audit: %d/%d passed.\n", ...
            lockedCoordinateAudit.NumPassed, ...
            lockedCoordinateAudit.NumCoordinates);

        fprintf( ...
            "Process 2 completed in %.3f s.\n", ...
            result.DurationSeconds);

        fprintf( ...
            "Final IK motion:\n%s\n", ...
            paths.FinalIkMotionFile);

        if strlength(checkpointFile) > 0

            fprintf( ...
                "Checkpoint:\n%s\n", ...
                checkpointFile);
        end
    end
end


function checkpoint = localLoadProcess1Checkpoint(checkpointFile)

    loaded = load( ...
        checkpointFile, ...
        "checkpoint");

    assert(isfield(loaded, "checkpoint"), ...
        "PipelineModelB:Process1CheckpointVariableMissing", ...
        "Expected variable 'checkpoint' was not found in:\n%s", ...
        checkpointFile);

    checkpoint = loaded.checkpoint;

    requiredFields = [
        "SchemaVersion"
        "Stage"
        "Trial"
        "ModelAValidation"
        "IkRunResult"
        "IkMotionSummary"
        "Completed"
    ];

    missingFields = requiredFields( ...
        ~isfield(checkpoint, cellstr(requiredFields)));

    assert(isempty(missingFields), ...
        "PipelineModelB:Process1CheckpointIncomplete", ...
        "Process-1 checkpoint is missing fields: %s", ...
        strjoin(missingFields, ", "));
end


function localValidateTrialContext(trial)

    requiredFields = [
        "SchemaVersion"
        "ConditionDeg"
        "TrialNumber"
        "TrialStem"
        "DisplayName"
        "Inputs"
        "Paths"
    ];

    missingFields = requiredFields( ...
        ~isfield(trial, cellstr(requiredFields)));

    assert(isempty(missingFields), ...
        "PipelineModelB:TrialContextIncomplete", ...
        "Trial context is missing fields: %s", ...
        strjoin(missingFields, ", "));

    assert(isfield(trial.Paths, "Initialization") && ...
        isfield(trial.Paths, "ModelB"), ...
        "PipelineModelB:TrialPathsIncomplete", ...
        "trial.Paths.Initialization and trial.Paths.ModelB are required.");
end


function localRequireField(s, fieldName, label)

    assert(isfield(s, fieldName), ...
        "PipelineModelB:ConfigurationFieldMissing", ...
        "Required configuration field is missing: %s", ...
        label);
end


function localEnsureDirectory(directory)

    directory = string(directory);

    if ~isfolder(directory)
        mkdir(directory);
    end
end


function localAssertOutputsAbsent( ...
        paths, filteringEnabled, executeFinalIk, writeQc, saveCheckpoint)

    outputFiles = [
        string(paths.ModelBFile)
        string(paths.FinalIkSetupFile)
    ];

    if filteringEnabled

        outputFiles(end+1,1) = ...
            string(paths.FilteredInitialIkMotionFile);
    end

    if executeFinalIk

        outputFiles(end+1,1) = ...
            string(paths.FinalIkMotionFile);
    end

    if writeQc

        outputFiles = [
            outputFiles
            string(paths.LockValuesCsv)
            string(paths.CoordinateConfigurationCsv)
            string(paths.ConstraintConfigurationCsv)
            string(paths.DependentCoordinateStateCsv)
            string(paths.IndependentSagittalStateCsv)
        ];

        if filteringEnabled

            outputFiles(end+1,1) = ...
                string(paths.LockFilterAuditCsv);
        end

        if executeFinalIk

            outputFiles = [
                outputFiles
                string(paths.LockedCoordinateAuditCsv)
                string(paths.DependentOutOfPlaneSummaryCsv)
                string(paths.IndependentSagittalSummaryCsv)
                string(paths.DependentSagittalSummaryCsv)
                string(paths.SagittalSummaryCsv)
                string(paths.SagittalTrajectoriesCsv)
                string(paths.SagittalRelativeTrajectoriesCsv)
            ];
        end
    end

    if executeFinalIk && saveCheckpoint

        outputFiles(end+1,1) = ...
            string(paths.CheckpointFile);
    end

    existingFiles = ...
        outputFiles(isfile(outputFiles));

    if ~isempty(existingFiles)

        error( ...
            "PipelineModelB:OutputExists", ...
            "Process-2 output already exists and Overwrite=false:\n%s", ...
            strjoin(existingFiles, newline));
    end
end


function runResult = localSerializableIkRunResult(runResult)

    removableFields = intersect( ...
        fieldnames(runResult), ...
        {'Tool','Model','Motion'});

    if ~isempty(removableFields)

        runResult = rmfield( ...
            runResult, ...
            removableFields);
    end
end


function result = localMakeResult( ...
        trial, ...
        paths, ...
        trialTimeRangeSec, ...
        lockWindowSec, ...
        lockExtractionMotionFile, ...
        lockFilterResult, ...
        lockValues, ...
        modelBResult, ...
        modelBValidation, ...
        dependentCoordinateState, ...
        independentSagittalState, ...
        finalIkSetupResult, ...
        finalIkRunResult, ...
        finalIkMotionSummary, ...
        lockedCoordinateAudit, ...
        dependentOutOfPlaneSummary, ...
        independentSagittalSummary, ...
        dependentSagittalSummary, ...
        sagittalMotionSummary, ...
        checkpointFile, ...
        completed, ...
        durationSeconds)

    result = struct;

    result.Stage = ...
        "model_b_final_ik";

    result.Trial = ...
        trial;

    result.Paths = ...
        paths;

    result.TrialTimeRangeSec = ...
        trialTimeRangeSec;

    result.LockWindowSec = ...
        lockWindowSec;

    result.LockExtractionMotionFile = ...
        string(lockExtractionMotionFile);

    result.LockFilterResult = ...
        lockFilterResult;

    result.LockValues = ...
        lockValues;

    result.ModelBResult = ...
        modelBResult;

    result.ModelBValidation = ...
        modelBValidation;

    result.DependentCoordinateState = ...
        dependentCoordinateState;

    result.IndependentSagittalState = ...
        independentSagittalState;

    result.FinalIkSetupResult = ...
        finalIkSetupResult;

    result.FinalIkRunResult = ...
        finalIkRunResult;

    result.FinalIkMotionSummary = ...
        finalIkMotionSummary;

    result.LockedCoordinateAudit = ...
        lockedCoordinateAudit;

    result.DependentOutOfPlaneSummary = ...
        dependentOutOfPlaneSummary;

    result.IndependentSagittalSummary = ...
        independentSagittalSummary;

    result.DependentSagittalSummary = ...
        dependentSagittalSummary;

    result.SagittalMotionSummary = ...
        sagittalMotionSummary;

    result.CheckpointFile = ...
        string(checkpointFile);

    result.Completed = ...
        logical(completed);

    result.DurationSeconds = ...
        double(durationSeconds);
end
