function batchResult = runStaticOptimizationPrepBatch(projectCfg, varargin)
%RUNSTATICOPTIMIZATIONPREPBATCH Run Batch Process 3 from an in-memory config.
%
% batchResult = pipeline.runStaticOptimizationPrepBatch(projectCfg)
%
% Callable equivalent of batch/batch_run_process_3.m. Every trial is
% resolved through pipeline.resolveTrialContext and executed through
% pipeline.prepareStaticOptimizationTrial.
%
% The function NEVER reloads project configuration. This is intentional so
% higher-level controllers may select a strength configuration by modifying
% an in-memory projectCfg before invoking the batch.
%
% NAME-VALUE OPTIONS
%
%   Conditions
%   Trials
%   Overwrite
%   EnableParallel
%   MaxWorkers
%   ContinueOnError
%   PoolProfile
%   ClosePoolWhenFinished
%   ExecuteBodyKinematics
%   WriteSummary
%   PrintProgress
%
% Defaults are inherited from projectCfg except ExecuteBodyKinematics,
% WriteSummary, and PrintProgress, which default true.
%
% RETURN STRUCT
%
%   SchemaVersion
%   Process
%   Stage
%   StrengthConfigEnabled
%   ConfigId
%   MusclePercent
%   ActuatorPercent
%   DurationSeconds
%   SummaryTable
%   SucceededJobs
%   FailedJobs
%   Succeeded
%   SummaryCsv
%   SummaryMat
%   Configuration

    %% Parse options

    parser = inputParser;
    parser.FunctionName = "pipeline.runStaticOptimizationPrepBatch";

    addRequired(parser, ...
        "projectCfg", ...
        @(x) isstruct(x) && isscalar(x));

    addParameter(parser, ...
        "Conditions", ...
        projectCfg.conditions(:).', ...
        @(x) isnumeric(x) && isvector(x) && ~isempty(x));

    addParameter(parser, ...
        "Trials", ...
        projectCfg.trials(:).', ...
        @(x) isnumeric(x) && isvector(x) && ~isempty(x));

    addParameter(parser, ...
        "Overwrite", ...
        projectCfg.overwriteExisting, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "EnableParallel", ...
        projectCfg.batchProcessing.enableParallel, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "MaxWorkers", ...
        projectCfg.batchProcessing.maxWorkers, ...
        @(x) isnumeric(x) && isscalar(x) && x >= 1 && x == fix(x));

    addParameter(parser, ...
        "ContinueOnError", ...
        projectCfg.batchProcessing.continueOnError, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "PoolProfile", ...
        projectCfg.batchProcessing.poolProfile, ...
        @(x) ...
            (ischar(x) && isrow(x)) || ...
            (isstring(x) && isscalar(x) && ~ismissing(x)));

    addParameter(parser, ...
        "ClosePoolWhenFinished", ...
        projectCfg.batchProcessing.closePoolWhenFinished, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "ExecuteBodyKinematics", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "WriteSummary", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "PrintProgress", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, projectCfg, varargin{:});

    processCfg = struct;

    processCfg.conditions = ...
        double(parser.Results.Conditions(:).');

    processCfg.trials = ...
        double(parser.Results.Trials(:).');

    processCfg.overwrite = ...
        logical(parser.Results.Overwrite);

    processCfg.enableParallel = ...
        logical(parser.Results.EnableParallel);

    processCfg.maxWorkers = ...
        double(parser.Results.MaxWorkers);

    processCfg.continueOnError = ...
        logical(parser.Results.ContinueOnError);

    processCfg.poolProfile = ...
        string(parser.Results.PoolProfile);

    processCfg.closePoolWhenFinished = ...
        logical(parser.Results.ClosePoolWhenFinished);

    processCfg.executeBodyKinematics = ...
        logical(parser.Results.ExecuteBodyKinematics);

    processCfg.writeSummary = ...
        logical(parser.Results.WriteSummary);

    processCfg.printProgress = ...
        logical(parser.Results.PrintProgress);

    %% Resolve strength-configuration identity

    processCfg.strengthConfigEnabled = ...
        logical(projectCfg.forceCapacity.enabled);

    processCfg.configId = "";
    processCfg.musclePercent = NaN;
    processCfg.actuatorPercent = NaN;

    strengthContext = struct;

    if processCfg.strengthConfigEnabled

        strengthContext = ...
            pipeline.resolveStrengthConfigContext( ...
                projectCfg);

        processCfg.configId = ...
            strengthContext.ConfigId;

        processCfg.musclePercent = ...
            strengthContext.MusclePercent;

        processCfg.actuatorPercent = ...
            strengthContext.ActuatorPercent;

        assert( ...
            strlength(processCfg.configId) > 0, ...
            "BatchProcess3:StrengthConfigIdentityMissing", ...
            "Enabled strength configuration did not resolve a valid ConfigId.");
    end

    if processCfg.printProgress

        if processCfg.strengthConfigEnabled

            fprintf( ...
                "Model C force-capacity configuration enabled.\n" + ...
                "Config ID: %s\n" + ...
                "Muscle capacity: %g%%\n" + ...
                "Actuator capacity: %g%%\n" + ...
                "Config file:\n%s\n" + ...
                "Apply mode: %s\n", ...
                processCfg.configId, ...
                processCfg.musclePercent, ...
                processCfg.actuatorPercent, ...
                projectCfg.forceCapacity.configFile, ...
                projectCfg.forceCapacity.applyMode);

        else

            fprintf( ...
                "Model C force-capacity configuration disabled.\n");
        end
    end

    %% Build job matrix

    [conditionGrid, trialGrid] = ...
        ndgrid( ...
            processCfg.conditions, ...
            processCfg.trials);

    jobConditions = ...
        conditionGrid(:);

    jobTrials = ...
        trialGrid(:);

    nJobs = ...
        numel(jobConditions);

    assert(nJobs > 0, ...
        "BatchProcess3:NoJobs", ...
        "No Process-3 jobs were configured.");

    if processCfg.printProgress

        fprintf( ...
            "Running Process 3 for %d jobs " + ...
            "(%d conditions x %d trials).\n", ...
            nJobs, ...
            numel(processCfg.conditions), ...
            numel(processCfg.trials));
    end

    %% Pre-flight trial-context resolution

    for jobIndex = 1:nJobs

        pipeline.resolveTrialContext( ...
            projectCfg, ...
            jobConditions(jobIndex), ...
            jobTrials(jobIndex));
    end

    if processCfg.printProgress

        fprintf( ...
            "Trial-context pre-flight passed for all %d jobs.\n", ...
            nJobs);
    end

    %% Configure parallel pool

    pool = []; %#ok<*NASGU>

    if processCfg.enableParallel

        pool = ...
            gcp("nocreate");

        if isempty(pool)

            pool = ...
                parpool( ...
                    char(processCfg.poolProfile), ...
                    processCfg.maxWorkers);

        elseif pool.NumWorkers ~= ...
                processCfg.maxWorkers

            delete(pool);

            pool = ...
                parpool( ...
                    char(processCfg.poolProfile), ...
                    processCfg.maxWorkers);
        end

        if processCfg.printProgress

            fprintf( ...
                "Parallel execution enabled with %d workers.\n", ...
                pool.NumWorkers);
        end

    elseif processCfg.printProgress

        fprintf( ...
            "Parallel execution disabled; running serially.\n");
    end

    %% Run jobs

    jobResults = ...
        cell(nJobs,1);

    batchStart = ...
        tic;

    if processCfg.enableParallel

        parfor jobIndex = 1:nJobs

            jobResults{jobIndex} = ...
                localRunProcess3Job( ...
                    projectCfg, ...
                    jobConditions(jobIndex), ...
                    jobTrials(jobIndex), ...
                    processCfg);
        end

    else

        for jobIndex = 1:nJobs

            jobResults{jobIndex} = ...
                localRunProcess3Job( ...
                    projectCfg, ...
                    jobConditions(jobIndex), ...
                    jobTrials(jobIndex), ...
                    processCfg);

            if processCfg.printProgress

                fprintf( ...
                    "[%d/%d] %s: %s\n", ...
                    jobIndex, ...
                    nJobs, ...
                    jobResults{jobIndex}.TrialStem, ...
                    jobResults{jobIndex}.Status);
            end
        end
    end

    batchDurationSeconds = ...
        toc(batchStart);

    %% Collate summary

    summaryTable = ...
        struct2table( ...
            vertcat(jobResults{:}));

    summaryTable = ...
        sortrows( ...
            summaryTable, ...
            {'ConditionDeg','TrialNumber'});

    nSucceeded = ...
        nnz(summaryTable.Succeeded);

    nFailed = ...
        height(summaryTable) - ...
        nSucceeded;

    if processCfg.printProgress

        fprintf( ...
            "\nProcess 3 complete in %.3f s.\n", ...
            batchDurationSeconds);

        fprintf( ...
            "Succeeded: %d\nFailed: %d\n", ...
            nSucceeded, ...
            nFailed);

        disp(summaryTable(:, [
            "ConditionDeg"
            "TrialNumber"
            "Status"
            "DurationSeconds"
            "BodyKinematicsDurationSeconds"
            "LiftOffTimeSec"
            "RecontactTimeSec"
            "SkullMassKg"
        ]));
    end

    %% Resolve and optionally write batch summary

    if processCfg.strengthConfigEnabled

        batchQcDirectory = ...
            strengthContext.Paths.BatchQcDirectory;

    else

        batchQcDirectory = ...
            string(fullfile( ...
                projectCfg.outputRoot, ...
                "batch_qc"));
    end

    summaryCsv = ...
        string(fullfile( ...
            batchQcDirectory, ...
            "process_3_static_optimization_prep_summary.csv"));

    summaryMat = ...
        string(fullfile( ...
            batchQcDirectory, ...
            "process_3_static_optimization_prep_summary.mat"));

    batchSummary = struct;

    batchSummary.SchemaVersion = 2;
    batchSummary.Process = 3;
    batchSummary.Stage = "static_optimization_prep";

    batchSummary.StrengthConfigEnabled = ...
        processCfg.strengthConfigEnabled;

    batchSummary.ConfigId = ...
        processCfg.configId;

    batchSummary.MusclePercent = ...
        processCfg.musclePercent;

    batchSummary.ActuatorPercent = ...
        processCfg.actuatorPercent;

    batchSummary.CompletedAt = ...
        string(datetime("now"));

    batchSummary.DurationSeconds = ...
        batchDurationSeconds;

    batchSummary.Configuration = ...
        processCfg;

    batchSummary.SummaryTable = ...
        summaryTable;

    batchSummary.Succeeded = ...
        nFailed == 0;

    if processCfg.writeSummary

        if ~isfolder(batchQcDirectory)

            mkdir(batchQcDirectory);
        end

        existingSummaryFiles = [
            summaryCsv
            summaryMat
        ];

        existingSummaryFiles = ...
            existingSummaryFiles( ...
                isfile(existingSummaryFiles));

        if ~processCfg.overwrite && ...
                ~isempty(existingSummaryFiles)

            error( ...
                "BatchProcess3:SummaryExists", ...
                "Batch summary output already exists:\n%s", ...
                strjoin(existingSummaryFiles, newline));
        end

        writetable( ...
            summaryTable, ...
            summaryCsv);

        save( ...
            summaryMat, ...
            "batchSummary");

        if processCfg.printProgress

            fprintf( ...
                "Batch summary CSV:\n%s\n", ...
                summaryCsv);

            fprintf( ...
                "Batch summary MAT:\n%s\n", ...
                summaryMat);
        end

    else

        summaryCsv = "";
        summaryMat = "";
    end

    %% Clean up parallel pool

    if processCfg.enableParallel && ...
            processCfg.closePoolWhenFinished

        pool = ...
            gcp("nocreate");

        if ~isempty(pool)

            delete(pool);
        end
    end

    %% Return batch result before applying legacy failure policy

    batchResult = struct;

    batchResult.SchemaVersion = 1;
    batchResult.Process = 3;
    batchResult.Stage = "static_optimization_prep";

    batchResult.StrengthConfigEnabled = ...
        processCfg.strengthConfigEnabled;

    batchResult.ConfigId = ...
        processCfg.configId;

    batchResult.MusclePercent = ...
        processCfg.musclePercent;

    batchResult.ActuatorPercent = ...
        processCfg.actuatorPercent;

    batchResult.DurationSeconds = ...
        batchDurationSeconds;

    batchResult.SummaryTable = ...
        summaryTable;

    batchResult.SucceededJobs = ...
        nSucceeded;

    batchResult.FailedJobs = ...
        nFailed;

    batchResult.Succeeded = ...
        nFailed == 0;

    batchResult.SummaryCsv = ...
        summaryCsv;

    batchResult.SummaryMat = ...
        summaryMat;

    batchResult.Configuration = ...
        processCfg;

    if nFailed > 0 && ...
            ~processCfg.continueOnError

        error( ...
            "BatchProcess3:JobFailures", ...
            "%d Process-3 jobs failed. " + ...
            "See the batch summary for details.", ...
            nFailed);
    end
end


function job = localRunProcess3Job( ...
        projectCfg, conditionDeg, trialNumber, processCfg)

    jobStart = ...
        tic;

    trial = ...
        pipeline.resolveTrialContext( ...
            projectCfg, ...
            conditionDeg, ...
            trialNumber);

    job = struct;

    job.ConditionDeg = conditionDeg;
    job.TrialNumber = trialNumber;
    job.TrialStem = trial.TrialStem;

    job.ConfigId = processCfg.configId;
    job.MusclePercent = processCfg.musclePercent;
    job.ActuatorPercent = processCfg.actuatorPercent;

    job.Status = "not_started";
    job.Succeeded = false;
    job.DurationSeconds = NaN;
    job.BodyKinematicsDurationSeconds = NaN;

    job.BodyKinematicsExecuted = ...
        false;

    job.SharedPreparationReused = ...
        false;

    job.SharedPreparationCheckpointFile = ...
        "";

    job.ModelBCheckpointFile = ...
        trial.Paths.ModelB.CheckpointFile;

    job.ModelCFile = ...
        trial.Paths.StaticOptimizationPrep.ModelCFile;

    job.HsfMotionFile = ...
        trial.Paths.StaticOptimizationPrep. ...
            HeadSupportForce.MotionFile;

    job.ExternalLoadsFile = ...
        trial.Paths.StaticOptimizationPrep. ...
            HeadSupportForce.ExternalLoadsFile;

    job.StaticOptimizationSetupFile = ...
        trial.Paths.StaticOptimization.SetupFile;

    job.CheckpointFile = ...
        trial.Paths.StaticOptimizationPrep.CheckpointFile;

    job.ForceConfigApplied = false;
    job.LiftOffTimeSec = NaN;
    job.RecontactTimeSec = NaN;
    job.PeakComExcursionMm = NaN;
    job.SkullMassKg = NaN;
    job.HsfValidationPassed = false;
    job.ExternalLoadsVerified = false;
    job.StaticOptimizationSetupVerified = false;
    job.ErrorIdentifier = "";
    job.ErrorMessage = "";

    try

        useSharedConfigurationPrep = ...
            isfield(projectCfg, "forceCapacity") && ...
            isstruct(projectCfg.forceCapacity) && ...
            isfield(projectCfg.forceCapacity, "enabled") && ...
            logical(projectCfg.forceCapacity.enabled) && ...
            processCfg.executeBodyKinematics;

        if useSharedConfigurationPrep

            result = ...
                pipeline.prepareStaticOptimizationConfigurationTrial( ...
                    projectCfg, ...
                    trial, ...
                    "Overwrite", ...
                        processCfg.overwrite, ...
                    "WriteQc", ...
                        true, ...
                    "SaveCheckpoint", ...
                        true, ...
                    "EventFigureVisible", ...
                        "off", ...
                    "PrintProgress", ...
                        false);

        else

            result = ...
                pipeline.prepareStaticOptimizationTrial( ...
                    projectCfg, ...
                    trial, ...
                    "ExecuteBodyKinematics", ...
                        processCfg.executeBodyKinematics, ...
                    "Overwrite", ...
                        processCfg.overwrite, ...
                    "WriteQc", ...
                        true, ...
                    "SaveCheckpoint", ...
                        true, ...
                    "EventFigureVisible", ...
                        "off", ...
                    "PrintProgress", ...
                        false);
        end

        job.Status = ...
            "completed";

        job.Succeeded = ...
            result.Completed;

        if isfield( ...
                result, ...
                "SharedPreparationReused")

            job.SharedPreparationReused = ...
                logical( ...
                    result.SharedPreparationReused);

            job.SharedPreparationCheckpointFile = ...
                string( ...
                    result.SharedPreparationCheckpointFile);

            job.BodyKinematicsExecuted = ...
                ~job.SharedPreparationReused;

            job.HsfMotionFile = ...
                string( ...
                    result.SharedPaths. ...
                        HeadSupportForce.MotionFile);

            job.ExternalLoadsFile = ...
                string( ...
                    result.SharedPaths. ...
                        HeadSupportForce.ExternalLoadsFile);

        else

            job.BodyKinematicsExecuted = ...
                logical( ...
                    processCfg.executeBodyKinematics);
        end

        if job.BodyKinematicsExecuted && ...
                isstruct(result.BodyKinematicsResult) && ...
                isfield( ...
                    result.BodyKinematicsResult, ...
                    "DurationSeconds")

            job.BodyKinematicsDurationSeconds = ...
                result.BodyKinematicsResult.DurationSeconds;
        end

        job.ForceConfigApplied = ...
            logical( ...
                result.ForceCapacityConfigResult.Applied);

        if isstruct(result.EventDetectionResult) && ...
                isfield( ...
                    result.EventDetectionResult, ...
                    "LiftOffTime")

            job.LiftOffTimeSec = ...
                result.EventDetectionResult.LiftOffTime;

            job.RecontactTimeSec = ...
                result.EventDetectionResult.RecontactTime;

            job.PeakComExcursionMm = ...
                result.EventDetectionResult.PeakExcursionM * ...
                1000;
        end

        if isstruct(result.HsfParameters) && ...
                isfield( ...
                    result.HsfParameters, ...
                    "SkullMassKg")

            job.SkullMassKg = ...
                result.HsfParameters.SkullMassKg;
        end

        if isstruct(result.HsfResult) && ...
                isfield( ...
                    result.HsfResult, ...
                    "Validation")

            job.HsfValidationPassed = ...
                logical( ...
                    result.HsfResult.Validation.Passed);
        end

        job.ExternalLoadsVerified = ...
            logical( ...
                result.ExternalLoadsResult. ...
                    VerificationPassed);

        job.StaticOptimizationSetupVerified = ...
            logical( ...
                result.StaticOptimizationSetupResult. ...
                    VerificationPassed);

    catch exception

        job.Status = ...
            "failed";

        job.ErrorIdentifier = ...
            string(exception.identifier);

        job.ErrorMessage = ...
            string(exception.message);
    end

    job.DurationSeconds = ...
        toc(jobStart);
end
