function batchResult = runStaticOptimizationBatch(projectCfg, varargin)
%RUNSTATICOPTIMIZATIONBATCH Run Batch Process 4 from an in-memory config.
%
% batchResult = pipeline.runStaticOptimizationBatch(projectCfg)
%
% Callable equivalent of batch/batch_run_process_4.m. Every trial is
% resolved through pipeline.resolveTrialContext and executed through
% pipeline.runStaticOptimizationTrial.
%
% The function NEVER reloads project configuration. This allows a
% higher-level search controller to select a strength JSON in memory and
% execute Process 4 for that exact configuration.
%
% NAME-VALUE OPTIONS
%
%   Conditions
%   Trials
%   Overwrite
%   EnableParallel
%   MaxWorkers
%   ContinueOnError
%   PoolProfile
%   ClosePoolWhenFinished
%   ExecuteStaticOptimization
%   WriteSummary
%   PrintProgress
%
% Defaults are inherited from projectCfg except ExecuteStaticOptimization,
% WriteSummary, and PrintProgress, which default true.

    %% Parse options

    parser = inputParser;
    parser.FunctionName = "pipeline.runStaticOptimizationBatch";

    addRequired(parser, ...
        "projectCfg", ...
        @(x) isstruct(x) && isscalar(x));

    addParameter(parser, ...
        "Conditions", ...
        projectCfg.conditions(:).', ...
        @(x) isnumeric(x) && isvector(x) && ~isempty(x));

    addParameter(parser, ...
        "Trials", ...
        projectCfg.trials(:).', ...
        @(x) isnumeric(x) && isvector(x) && ~isempty(x));

    addParameter(parser, ...
        "Overwrite", ...
        projectCfg.overwriteExisting, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "EnableParallel", ...
        projectCfg.batchProcessing.enableParallel, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "MaxWorkers", ...
        projectCfg.batchProcessing.maxWorkers, ...
        @(x) isnumeric(x) && isscalar(x) && x >= 1 && x == fix(x));

    addParameter(parser, ...
        "ContinueOnError", ...
        projectCfg.batchProcessing.continueOnError, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "PoolProfile", ...
        projectCfg.batchProcessing.poolProfile, ...
        @(x) ...
            (ischar(x) && isrow(x)) || ...
            (isstring(x) && isscalar(x) && ~ismissing(x)));

    addParameter(parser, ...
        "ClosePoolWhenFinished", ...
        projectCfg.batchProcessing.closePoolWhenFinished, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "ExecuteStaticOptimization", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "WriteSummary", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "PrintProgress", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, projectCfg, varargin{:});

    processCfg = struct;

    processCfg.conditions = ...
        double(parser.Results.Conditions(:).');

    processCfg.trials = ...
        double(parser.Results.Trials(:).');

    processCfg.overwrite = ...
        logical(parser.Results.Overwrite);

    processCfg.enableParallel = ...
        logical(parser.Results.EnableParallel);

    processCfg.maxWorkers = ...
        double(parser.Results.MaxWorkers);

    processCfg.continueOnError = ...
        logical(parser.Results.ContinueOnError);

    processCfg.poolProfile = ...
        string(parser.Results.PoolProfile);

    processCfg.closePoolWhenFinished = ...
        logical(parser.Results.ClosePoolWhenFinished);

    processCfg.executeStaticOptimization = ...
        logical(parser.Results.ExecuteStaticOptimization);

    processCfg.writeSummary = ...
        logical(parser.Results.WriteSummary);

    processCfg.printProgress = ...
        logical(parser.Results.PrintProgress);

    %% Resolve strength-configuration identity

    processCfg.strengthConfigEnabled = ...
        logical(projectCfg.forceCapacity.enabled);

    processCfg.configId = "";
    processCfg.musclePercent = NaN;
    processCfg.actuatorPercent = NaN;

    strengthContext = struct;

    if processCfg.strengthConfigEnabled

        strengthContext = ...
            pipeline.resolveStrengthConfigContext( ...
                projectCfg);

        processCfg.configId = ...
            strengthContext.ConfigId;

        processCfg.musclePercent = ...
            strengthContext.MusclePercent;

        processCfg.actuatorPercent = ...
            strengthContext.ActuatorPercent;

        assert( ...
            strlength(processCfg.configId) > 0, ...
            "BatchProcess4:StrengthConfigIdentityMissing", ...
            "Enabled strength configuration did not resolve a valid ConfigId.");
    end

    if processCfg.printProgress

        if processCfg.strengthConfigEnabled

            fprintf( ...
                "Static Optimization strength configuration enabled.\n" + ...
                "Config ID: %s\n" + ...
                "Muscle capacity: %g%%\n" + ...
                "Actuator capacity: %g%%\n" + ...
                "Config file:\n%s\n" + ...
                "Apply mode: %s\n", ...
                processCfg.configId, ...
                processCfg.musclePercent, ...
                processCfg.actuatorPercent, ...
                projectCfg.forceCapacity.configFile, ...
                projectCfg.forceCapacity.applyMode);

        else

            fprintf( ...
                "Static Optimization strength configuration disabled.\n");
        end

        fprintf( ...
            "Static Optimization output requirements:\n" + ...
            "  Force output required:      %d\n" + ...
            "  Activation output required: %d\n" + ...
            "  Time tolerance:             %.9g s\n", ...
            projectCfg.pipeline.staticOptimization.requireForceOutput, ...
            projectCfg.pipeline.staticOptimization.requireActivationOutput, ...
            projectCfg.pipeline.staticOptimization.timeToleranceSec);
    end

    %% Build job matrix

    [conditionGrid, trialGrid] = ...
        ndgrid( ...
            processCfg.conditions, ...
            processCfg.trials);

    jobConditions = ...
        conditionGrid(:);

    jobTrials = ...
        trialGrid(:);

    nJobs = ...
        numel(jobConditions);

    assert(nJobs > 0, ...
        "BatchProcess4:NoJobs", ...
        "No Process-4 jobs were configured.");

    if processCfg.printProgress

        fprintf( ...
            "Running Process 4 for %d jobs " + ...
            "(%d conditions x %d trials).\n", ...
            nJobs, ...
            numel(processCfg.conditions), ...
            numel(processCfg.trials));
    end

    %% Pre-flight trial-context resolution

    for jobIndex = 1:nJobs

        pipeline.resolveTrialContext( ...
            projectCfg, ...
            jobConditions(jobIndex), ...
            jobTrials(jobIndex));
    end

    if processCfg.printProgress

        fprintf( ...
            "Trial-context pre-flight passed for all %d jobs.\n", ...
            nJobs);
    end

    %% Configure parallel pool

    pool = [];

    if processCfg.enableParallel

        pool = ...
            gcp("nocreate");

        if isempty(pool)

            pool = ...
                parpool( ...
                    char(processCfg.poolProfile), ...
                    processCfg.maxWorkers);

        elseif pool.NumWorkers ~= ...
                processCfg.maxWorkers

            delete(pool);

            pool = ...
                parpool( ...
                    char(processCfg.poolProfile), ...
                    processCfg.maxWorkers);
        end

        if processCfg.printProgress

            fprintf( ...
                "Parallel execution enabled with %d workers.\n", ...
                pool.NumWorkers);
        end

    elseif processCfg.printProgress

        fprintf( ...
            "Parallel execution disabled; running serially.\n");
    end

    %% Run jobs

    jobResults = ...
        cell(nJobs,1);

    batchStart = ...
        tic;

    if processCfg.enableParallel

        parfor jobIndex = 1:nJobs

            jobResults{jobIndex} = ...
                localRunProcess4Job( ...
                    projectCfg, ...
                    jobConditions(jobIndex), ...
                    jobTrials(jobIndex), ...
                    processCfg);
        end

    else

        for jobIndex = 1:nJobs

            jobResults{jobIndex} = ...
                localRunProcess4Job( ...
                    projectCfg, ...
                    jobConditions(jobIndex), ...
                    jobTrials(jobIndex), ...
                    processCfg);

            if processCfg.printProgress

                fprintf( ...
                    "[%d/%d] %s: %s\n", ...
                    jobIndex, ...
                    nJobs, ...
                    jobResults{jobIndex}.TrialStem, ...
                    jobResults{jobIndex}.Status);
            end
        end
    end

    batchDurationSeconds = ...
        toc(batchStart);

    %% Collate summary

    summaryTable = ...
        struct2table( ...
            vertcat(jobResults{:}));

    summaryTable = ...
        sortrows( ...
            summaryTable, ...
            {'ConditionDeg','TrialNumber'});

    nSucceeded = ...
        nnz(summaryTable.Succeeded);

    nFailed = ...
        height(summaryTable) - ...
        nSucceeded;

    if processCfg.printProgress

        fprintf( ...
            "\nProcess 4 complete in %.3f s.\n", ...
            batchDurationSeconds);

        fprintf( ...
            "Succeeded: %d\nFailed: %d\n", ...
            nSucceeded, ...
            nFailed);

        disp(summaryTable(:, [
            "ConditionDeg"
            "TrialNumber"
            "Status"
            "DurationSeconds"
            "StaticOptimizationDurationSeconds"
            "ForceRows"
            "ActivationRows"
            "OutputAuditPassed"
            "ActivationSaturationPassed"
            "PeakAbsoluteActivation"
            "SaturatedChannelCount"
        ]));
    end

    %% Resolve and optionally write batch summary

    if processCfg.strengthConfigEnabled

        batchQcDirectory = ...
            strengthContext.Paths.BatchQcDirectory;

    else

        batchQcDirectory = ...
            string(fullfile( ...
                projectCfg.outputRoot, ...
                "batch_qc"));
    end

    summaryCsv = ...
        string(fullfile( ...
            batchQcDirectory, ...
            "process_4_static_optimization_summary.csv"));

    summaryMat = ...
        string(fullfile( ...
            batchQcDirectory, ...
            "process_4_static_optimization_summary.mat"));

    batchSummary = struct;

    batchSummary.SchemaVersion = 2;
    batchSummary.Process = 4;
    batchSummary.Stage = "static_optimization";

    batchSummary.StrengthConfigEnabled = ...
        processCfg.strengthConfigEnabled;

    batchSummary.ConfigId = ...
        processCfg.configId;

    batchSummary.MusclePercent = ...
        processCfg.musclePercent;

    batchSummary.ActuatorPercent = ...
        processCfg.actuatorPercent;

    batchSummary.CompletedAt = ...
        string(datetime("now"));

    batchSummary.DurationSeconds = ...
        batchDurationSeconds;

    batchSummary.Configuration = ...
        processCfg;

    batchSummary.SummaryTable = ...
        summaryTable;

    batchSummary.Succeeded = ...
        nFailed == 0;

    if processCfg.writeSummary

        if ~isfolder(batchQcDirectory)

            mkdir(batchQcDirectory);
        end

        existingSummaryFiles = [
            summaryCsv
            summaryMat
        ];

        existingSummaryFiles = ...
            existingSummaryFiles( ...
                isfile(existingSummaryFiles));

        if ~processCfg.overwrite && ...
                ~isempty(existingSummaryFiles)

            error( ...
                "BatchProcess4:SummaryExists", ...
                "Batch summary output already exists:\n%s", ...
                strjoin(existingSummaryFiles, newline));
        end

        writetable( ...
            summaryTable, ...
            summaryCsv);

        save( ...
            summaryMat, ...
            "batchSummary");

        if processCfg.printProgress

            fprintf( ...
                "Batch summary CSV:\n%s\n", ...
                summaryCsv);

            fprintf( ...
                "Batch summary MAT:\n%s\n", ...
                summaryMat);
        end

    else

        summaryCsv = "";
        summaryMat = "";
    end

    %% Clean up parallel pool

    if processCfg.enableParallel && ...
            processCfg.closePoolWhenFinished

        pool = ...
            gcp("nocreate");

        if ~isempty(pool)

            delete(pool);
        end
    end

    %% Return batch result before applying legacy failure policy

    batchResult = struct;

    batchResult.SchemaVersion = 1;
    batchResult.Process = 4;
    batchResult.Stage = "static_optimization";

    batchResult.StrengthConfigEnabled = ...
        processCfg.strengthConfigEnabled;

    batchResult.ConfigId = ...
        processCfg.configId;

    batchResult.MusclePercent = ...
        processCfg.musclePercent;

    batchResult.ActuatorPercent = ...
        processCfg.actuatorPercent;

    batchResult.DurationSeconds = ...
        batchDurationSeconds;

    batchResult.SummaryTable = ...
        summaryTable;

    batchResult.SucceededJobs = ...
        nSucceeded;

    batchResult.FailedJobs = ...
        nFailed;

    batchResult.Succeeded = ...
        nFailed == 0;

    batchResult.SummaryCsv = ...
        summaryCsv;

    batchResult.SummaryMat = ...
        summaryMat;

    batchResult.Configuration = ...
        processCfg;

    if nFailed > 0 && ...
            ~processCfg.continueOnError

        error( ...
            "BatchProcess4:JobFailures", ...
            "%d Process-4 jobs failed. " + ...
            "See the batch summary for details.", ...
            nFailed);
    end
end


function job = localRunProcess4Job( ...
        projectCfg, conditionDeg, trialNumber, processCfg)

    jobStart = ...
        tic;

    trial = ...
        pipeline.resolveTrialContext( ...
            projectCfg, ...
            conditionDeg, ...
            trialNumber);

    job = struct;

    job.ConditionDeg = conditionDeg;
    job.TrialNumber = trialNumber;
    job.TrialStem = trial.TrialStem;

    job.ConfigId = processCfg.configId;
    job.MusclePercent = processCfg.musclePercent;
    job.ActuatorPercent = processCfg.actuatorPercent;

    job.Status = "not_started";
    job.Succeeded = false;
    job.DurationSeconds = NaN;
    job.StaticOptimizationDurationSeconds = NaN;

    job.Process3CheckpointFile = ...
        trial.Paths.StaticOptimizationPrep.CheckpointFile;

    job.StaticOptimizationSetupFile = ...
        trial.Paths.StaticOptimization.SetupFile;

    job.ResultsDirectory = ...
        trial.Paths.StaticOptimization.ResultsDirectory;

    job.ForceFile = "";
    job.ActivationFile = "";
    job.ForceRows = NaN;
    job.ActivationRows = NaN;
    job.OutputAuditPassed = false;

    job.ActivationSaturationAudited = false;
    job.ActivationSaturationPassed = false;
    job.ActivationSaturationThreshold = NaN;
    job.PeakAbsoluteActivation = NaN;
    job.PeakActivationValue = NaN;
    job.PeakActivationLabel = "";
    job.PeakActivationTime = NaN;
    job.SaturatedValueCount = NaN;
    job.SaturatedChannelCount = NaN;
    job.SaturatedLabels = "";
    job.FirstSaturationTime = NaN;
    job.LastSaturationTime = NaN;
    job.ActivationAuditCsv = "";

    job.CheckpointFile = "";
    job.ErrorIdentifier = "";
    job.ErrorMessage = "";

    try

        result = ...
            pipeline.runStaticOptimizationTrial( ...
                projectCfg, ...
                trial, ...
                "ExecuteStaticOptimization", ...
                    processCfg.executeStaticOptimization, ...
                "Overwrite", ...
                    processCfg.overwrite, ...
                "WriteQc", ...
                    true, ...
                "SaveCheckpoint", ...
                    true, ...
                "PrintProgress", ...
                    false);

        job.Succeeded = ...
            result.Completed;

        if result.Completed

            job.Status = ...
                "completed";

        elseif result.FailureStatus == ...
                "activation_saturation"

            job.Status = ...
                "activation_saturation";

        else

            job.Status = ...
                "failed";
        end

        job.ForceFile = ...
            result.ForceFile;

        job.ActivationFile = ...
            result.ActivationFile;

        job.CheckpointFile = ...
            result.CheckpointFile;

        job.ActivationAuditCsv = ...
            result.ActivationAuditCsv;

        job.ActivationSaturationAudited = ...
            result.ActivationSaturationAudited;

        job.ActivationSaturationPassed = ...
            result.ActivationSaturationPassed;

        if result.ActivationSaturationAudited

            activationAudit = ...
                result.ActivationAudit;

            job.ActivationSaturationThreshold = ...
                activationAudit.SaturationThreshold;

            job.PeakAbsoluteActivation = ...
                activationAudit.PeakAbsoluteActivation;

            job.PeakActivationValue = ...
                activationAudit.PeakActivationValue;

            job.PeakActivationLabel = ...
                activationAudit.PeakLabel;

            job.PeakActivationTime = ...
                activationAudit.PeakTime;

            job.SaturatedValueCount = ...
                activationAudit.SaturatedValueCount;

            job.SaturatedChannelCount = ...
                activationAudit.SaturatedChannelCount;

            job.SaturatedLabels = ...
                strjoin( ...
                    string(activationAudit.SaturatedLabels(:)), ...
                    ";");

            job.FirstSaturationTime = ...
                activationAudit.FirstSaturationTime;

            job.LastSaturationTime = ...
                activationAudit.LastSaturationTime;
        end

        if isstruct(result.RunResult) && ...
                isfield( ...
                    result.RunResult, ...
                    "DurationSeconds")

            job.StaticOptimizationDurationSeconds = ...
                result.RunResult.DurationSeconds;
        end

        if ~isempty(result.OutputAudit)

            job.OutputAuditPassed = ...
                all(result.OutputAudit.Passed);

            forceRows = ...
                result.OutputAudit( ...
                    result.OutputAudit.OutputType == "force", ...
                    :);

            activationRows = ...
                result.OutputAudit( ...
                    result.OutputAudit.OutputType == "activation", ...
                    :);

            if height(forceRows) == 1

                job.ForceRows = ...
                    forceRows.NumRows;
            end

            if height(activationRows) == 1

                job.ActivationRows = ...
                    activationRows.NumRows;
            end
        end

    catch exception

        job.Status = ...
            "failed";

        job.ErrorIdentifier = ...
            string(exception.identifier);

        job.ErrorMessage = ...
            string(exception.message);
    end

    job.DurationSeconds = ...
        toc(jobStart);
end
