function result = runStaticOptimizationTrial( ...
        projectCfg, trial, varargin)
%RUNSTATICOPTIMIZATIONTRIAL Run Process 4 for one resolved trial.
%
% result = pipeline.runStaticOptimizationTrial(projectCfg, trial)
%
% The trial input must be created by:
%
%   trial = pipeline.resolveTrialContext( ...
%       projectCfg, conditionDeg, trialNumber);
%
% This worker is the canonical implementation for:
%   1. validating the completed Process-3 checkpoint;
%   2. validating the prepared Static Optimization setup artifact;
%   3. executing Static Optimization exactly from the setup XML;
%   4. auditing force and activation STO outputs;
%   5. writing Process-4 QC and checkpoint artifacts.
%
% Both the single-trial example and Batch Process 4 should call this
% function. Neither orchestration layer should reimplement these steps.
%
% NAME-VALUE OPTIONS
%
%   ExecuteStaticOptimization
%       true (default). When false, prerequisites are validated but SO is
%       not executed.
%
%   Overwrite
%       Defaults to projectCfg.overwriteExisting.
%
%   WriteQc
%       true (default).
%
%   SaveCheckpoint
%       true (default). A checkpoint is saved only after successful SO
%       execution and output QC.
%
%   PrintProgress
%       true (default).
%
% RETURN
%
%   result.Stage
%   result.Trial
%   result.Paths
%   result.Process3CheckpointFile
%   result.StaticOptimizationSetupFile
%   result.RunResult
%   result.OutputAudit
%   result.ForceFile
%   result.ActivationFile
%   result.CheckpointFile
%   result.Completed
%   result.DurationSeconds

    assert(isstruct(projectCfg), ...
        "PipelineSO:InvalidProjectConfig", ...
        "projectCfg must be a struct.");

    localValidateTrialContext(trial);

    defaultOverwrite = false;

    if isfield(projectCfg, "overwriteExisting")
        defaultOverwrite = projectCfg.overwriteExisting;
    end

    parser = inputParser;
    parser.FunctionName = ...
        "pipeline.runStaticOptimizationTrial";

    addRequired(parser, ...
        "projectCfg", ...
        @isstruct);

    addRequired(parser, ...
        "trial", ...
        @isstruct);

    addParameter(parser, ...
        "ExecuteStaticOptimization", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "Overwrite", ...
        defaultOverwrite, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "WriteQc", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "SaveCheckpoint", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "PrintProgress", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, ...
        projectCfg, trial, varargin{:});

    executeStaticOptimization = ...
        parser.Results.ExecuteStaticOptimization;

    overwrite = ...
        parser.Results.Overwrite;

    writeQc = ...
        parser.Results.WriteQc;

    saveCheckpoint = ...
        parser.Results.SaveCheckpoint;

    printProgress = ...
        parser.Results.PrintProgress;

    stageStart = tic;

    %% Resolve Process-4 configuration

    localRequireField( ...
        projectCfg, ...
        "pipeline", ...
        "projectCfg.pipeline");

    localRequireField( ...
        projectCfg.pipeline, ...
        "staticOptimization", ...
        "projectCfg.pipeline.staticOptimization");

    soCfg = ...
        projectCfg.pipeline.staticOptimization;

    requiredSoConfigFields = [
        "requireForceOutput"
        "requireActivationOutput"
        "timeToleranceSec"
        "requireUnsaturatedActivations"
        "activationSaturationLimit"
        "activationSaturationTolerance"
    ];

    missingSoConfigFields = ...
        requiredSoConfigFields( ...
            ~isfield( ...
                soCfg, ...
                cellstr(requiredSoConfigFields)));

    assert(isempty(missingSoConfigFields), ...
        "PipelineSO:ConfigurationMissing", ...
        "Static Optimization configuration is missing: %s", ...
        strjoin(missingSoConfigFields, ", "));

    %% Resolve paths and prerequisites

    process3Paths = ...
        trial.Paths.StaticOptimizationPrep;

    paths = ...
        trial.Paths.StaticOptimization;

    localEnsureDirectory(paths.Directory);
    localEnsureDirectory(paths.ResultsDirectory);
    localEnsureDirectory(paths.QcDirectory);

    requiredInputs = [
        string(process3Paths.CheckpointFile)
        string(paths.SetupFile)
    ];

    requiredLabels = [
        "Process-3 checkpoint"
        "Static Optimization setup"
    ];

    for inputIndex = 1:numel(requiredInputs)

        assert(isfile(requiredInputs(inputIndex)), ...
            "PipelineSO:InputNotFound", ...
            "%s was not found:\n%s", ...
            requiredLabels(inputIndex), ...
            requiredInputs(inputIndex));
    end

    if ~overwrite

        localAssertWorkerOutputsAbsent( ...
            paths, ...
            executeStaticOptimization, ...
            writeQc, ...
            saveCheckpoint);
    end

    if printProgress

        fprintf( ...
            "\n=== Process 4: %s ===\n", ...
            trial.DisplayName);

        fprintf( ...
            "Process-3 checkpoint:\n%s\n", ...
            process3Paths.CheckpointFile);

        fprintf( ...
            "Static Optimization setup:\n%s\n", ...
            paths.SetupFile);

        fprintf( ...
            "Results directory:\n%s\n", ...
            paths.ResultsDirectory);
    end

    %% Validate Process-3 checkpoint

    checkpointC = ...
        localLoadProcess3Checkpoint( ...
            process3Paths.CheckpointFile);

    assert(checkpointC.Completed, ...
        "PipelineSO:Process3Incomplete", ...
        "The Process-3 checkpoint is not marked complete.");

    assert(string(checkpointC.Stage) == ...
            "static_optimization_prep", ...
        "PipelineSO:UnexpectedProcess3Stage", ...
        "Expected Process-3 stage 'static_optimization_prep' " + ...
        "but found '%s'.", ...
        string(checkpointC.Stage));

    assert(checkpointC.Trial.ConditionDeg == ...
            trial.ConditionDeg, ...
        "PipelineSO:ConditionMismatch", ...
        "Resolved condition is %g deg, but Process 3 contains %g deg.", ...
        trial.ConditionDeg, ...
        checkpointC.Trial.ConditionDeg);

    assert(checkpointC.Trial.TrialNumber == ...
            trial.TrialNumber, ...
        "PipelineSO:TrialMismatch", ...
        "Resolved trial is %d, but Process 3 contains trial %d.", ...
        trial.TrialNumber, ...
        checkpointC.Trial.TrialNumber);

    assert(logical(checkpointC.ModelCValidation.Passed), ...
        "PipelineSO:ModelCWasInvalid", ...
        "The Process-3 checkpoint reports that Model C failed validation.");

    assert(logical( ...
            checkpointC.ExternalLoadsResult.VerificationPassed), ...
        "PipelineSO:ExternalLoadsWasInvalid", ...
        "The Process-3 checkpoint reports failed ExternalLoads verification.");

    assert(logical( ...
            checkpointC.StaticOptimizationSetupResult.VerificationPassed), ...
        "PipelineSO:SetupWasInvalid", ...
        "The Process-3 checkpoint reports failed SO setup verification.");

    assert(isfield(checkpointC, "HsfResult") && ...
        isfield(checkpointC.HsfResult, "Validation") && ...
        logical(checkpointC.HsfResult.Validation.Passed), ...
        "PipelineSO:HsfWasInvalid", ...
        "The Process-3 checkpoint reports failed HSF validation.");

    if isfield( ...
            checkpointC, ...
            "StaticOptimizationPaths") && ...
            isfield( ...
                checkpointC.StaticOptimizationPaths, ...
                "SetupFile")

        checkpointSetupFile = ...
            localCanonicalPath( ...
                checkpointC.StaticOptimizationPaths.SetupFile);

        resolvedSetupFile = ...
            localCanonicalPath( ...
                paths.SetupFile);

        assert(checkpointSetupFile == resolvedSetupFile, ...
            "PipelineSO:SetupPathMismatch", ...
            "Resolved SO setup does not match the Process-3 checkpoint.\n" + ...
            "Resolved: %s\nCheckpoint: %s", ...
            paths.SetupFile, ...
            checkpointC.StaticOptimizationPaths.SetupFile);
    end

    if printProgress

        fprintf( ...
            "Process-3 checkpoint validation passed.\n");
    end

    %% Optional validation-only exit

    if ~executeStaticOptimization

        result = ...
            localMakeResult( ...
                trial, ...
                paths, ...
                process3Paths.CheckpointFile, ...
                paths.SetupFile, ...
                struct, ...
                table, ...
                "", ...
                "", ...
                "", ...
                false, ...
                toc(stageStart));

        if printProgress

            fprintf( ...
                "Static Optimization execution is disabled. " + ...
                "Prerequisites and setup validation passed.\n");
        end

        return;
    end

    %% Execute Static Optimization from the prepared XML

    runResult = ...
        opensimrun.runStaticOptimizationSetup( ...
            paths.SetupFile, ...
            "Overwrite", ...
                overwrite, ...
            "RequireForceOutput", ...
                soCfg.requireForceOutput, ...
            "RequireActivationOutput", ...
                soCfg.requireActivationOutput, ...
            "TimeToleranceSec", ...
                soCfg.timeToleranceSec);

    assert(runResult.RunSucceeded, ...
        "PipelineSO:RunFailed", ...
        "Static Optimization did not report success.");

    assert(~isempty(runResult.OutputAudit) && ...
        all(runResult.OutputAudit.Passed), ...
        "PipelineSO:OutputAuditFailed", ...
        "Static Optimization outputs failed QC.");

    assert(localCanonicalPath( ...
            runResult.ResultsDirectory) == ...
        localCanonicalPath( ...
            paths.ResultsDirectory), ...
        "PipelineSO:ResultsDirectoryMismatch", ...
        "SO setup resolved an unexpected results directory.\n" + ...
        "Expected: %s\nResolved: %s", ...
        paths.ResultsDirectory, ...
        runResult.ResultsDirectory);

    %% Write QC

    if writeQc

        writetable( ...
            runResult.OutputAudit, ...
            paths.OutputAuditCsv);
    end

    %% Save canonical Process-4 checkpoint

    checkpointFile = "";

    if saveCheckpoint

        checkpoint = struct;

        checkpoint.SchemaVersion = ...
            1;

        checkpoint.Stage = ...
            "static_optimization";

        checkpoint.Trial = ...
            trial;

        checkpoint.Configuration = struct( ...
            "RequireForceOutput", ...
                logical(soCfg.requireForceOutput), ...
            "RequireActivationOutput", ...
                logical(soCfg.requireActivationOutput), ...
            "TimeToleranceSec", ...
                double(soCfg.timeToleranceSec), ...
            "Overwrite", ...
                overwrite);

        checkpoint.Paths = ...
            paths;

        checkpoint.Process3CheckpointFile = ...
            process3Paths.CheckpointFile;

        checkpoint.StaticOptimizationSetupFile = ...
            paths.SetupFile;

        checkpoint.RunResult = ...
            localSerializableRunResult( ...
                runResult);

        checkpoint.OutputAudit = ...
            runResult.OutputAudit;

        checkpoint.Completed = ...
            true;

        checkpoint.CompletedAt = ...
            string(datetime("now"));

        save( ...
            paths.CheckpointFile, ...
            "checkpoint", ...
            "-v7.3");

        checkpointFile = ...
            paths.CheckpointFile;
    end

    %% Return

    result = ...
        localMakeResult( ...
            trial, ...
            paths, ...
            process3Paths.CheckpointFile, ...
            paths.SetupFile, ...
            localSerializableRunResult(runResult), ...
            runResult.OutputAudit, ...
            runResult.ForceFile, ...
            runResult.ActivationFile, ...
            checkpointFile, ...
            true, ...
            toc(stageStart));

    if printProgress

        fprintf( ...
            "Static Optimization completed in %.3f s.\n", ...
            runResult.DurationSeconds);

        fprintf( ...
            "Force output:\n%s\n", ...
            runResult.ForceFile);

        fprintf( ...
            "Activation output:\n%s\n", ...
            runResult.ActivationFile);

        fprintf( ...
            "Process 4 completed in %.3f s.\n", ...
            result.DurationSeconds);

        if strlength(checkpointFile) > 0

            fprintf( ...
                "Checkpoint:\n%s\n", ...
                checkpointFile);
        end
    end
end


function checkpoint = localLoadProcess3Checkpoint(checkpointFile)

    loaded = ...
        load( ...
            checkpointFile, ...
            "checkpoint");

    assert(isfield(loaded, "checkpoint"), ...
        "PipelineSO:Process3CheckpointVariableMissing", ...
        "Expected variable 'checkpoint' was not found in:\n%s", ...
        checkpointFile);

    checkpoint = ...
        loaded.checkpoint;

    requiredFields = [
        "SchemaVersion"
        "Stage"
        "Trial"
        "ModelCValidation"
        "HsfResult"
        "ExternalLoadsResult"
        "StaticOptimizationSetupResult"
        "Completed"
    ];

    missingFields = ...
        requiredFields( ...
            ~isfield( ...
                checkpoint, ...
                cellstr(requiredFields)));

    assert(isempty(missingFields), ...
        "PipelineSO:Process3CheckpointIncomplete", ...
        "Process-3 checkpoint is missing fields: %s", ...
        strjoin(missingFields, ", "));
end


function localValidateTrialContext(trial)

    requiredFields = [
        "SchemaVersion"
        "ConditionDeg"
        "TrialNumber"
        "TrialStem"
        "DisplayName"
        "Paths"
    ];

    missingFields = ...
        requiredFields( ...
            ~isfield( ...
                trial, ...
                cellstr(requiredFields)));

    assert(isempty(missingFields), ...
        "PipelineSO:TrialContextIncomplete", ...
        "Trial context is missing fields: %s", ...
        strjoin(missingFields, ", "));

    assert(isfield( ...
            trial.Paths, ...
            "StaticOptimizationPrep") && ...
        isfield( ...
            trial.Paths, ...
            "StaticOptimization"), ...
        "PipelineSO:TrialPathsIncomplete", ...
        "Process-3 and Process-4 trial paths are required.");
end


function localRequireField(s, fieldName, label)

    assert(isfield(s, fieldName), ...
        "PipelineSO:ConfigurationFieldMissing", ...
        "Required configuration field is missing: %s", ...
        label);
end


function localEnsureDirectory(directory)

    directory = ...
        string(directory);

    if ~isfolder(directory)
        mkdir(directory);
    end
end


function localAssertWorkerOutputsAbsent( ...
        paths, executeStaticOptimization, writeQc, saveCheckpoint)

    outputFiles = strings(0,1);

    if executeStaticOptimization && ...
            writeQc

        outputFiles(end+1,1) = ...
            string(paths.OutputAuditCsv);
    end

    if executeStaticOptimization && ...
            saveCheckpoint

        outputFiles(end+1,1) = ...
            string(paths.CheckpointFile);
    end

    existingFiles = ...
        outputFiles(isfile(outputFiles));

    if ~isempty(existingFiles)

        error( ...
            "PipelineSO:WorkerOutputExists", ...
            "Process-4 QC/checkpoint output already exists and " + ...
            "Overwrite=false:\n%s", ...
            strjoin(existingFiles, newline));
    end
end


function runResult = localSerializableRunResult(runResult)

    removableFields = ...
        intersect( ...
            fieldnames(runResult), ...
            {'Tool','Model'});

    if ~isempty(removableFields)

        runResult = ...
            rmfield( ...
                runResult, ...
                removableFields);
    end
end


function canonicalPath = localCanonicalPath(pathValue)

    pathValue = ...
        string(pathValue);

    canonicalPath = ...
        string(char( ...
            java.io.File(char(pathValue)).getCanonicalPath()));

    if ispc
        canonicalPath = lower(canonicalPath);
    end
end


function result = localMakeResult( ...
        trial, ...
        paths, ...
        process3CheckpointFile, ...
        setupFile, ...
        runResult, ...
        outputAudit, ...
        forceFile, ...
        activationFile, ...
        checkpointFile, ...
        completed, ...
        durationSeconds)

    result = struct;

    result.Stage = ...
        "static_optimization";

    result.Trial = ...
        trial;

    result.Paths = ...
        paths;

    result.Process3CheckpointFile = ...
        string(process3CheckpointFile);

    result.StaticOptimizationSetupFile = ...
        string(setupFile);

    result.RunResult = ...
        runResult;

    result.OutputAudit = ...
        outputAudit;

    result.ForceFile = ...
        string(forceFile);

    result.ActivationFile = ...
        string(activationFile);

    result.CheckpointFile = ...
        string(checkpointFile);

    result.Completed = ...
        logical(completed);

    result.DurationSeconds = ...
        double(durationSeconds);
end
