function result = writeStaticOptimizationAnalysisProvenance( ...
        projectCfg, analysisContext, analysisDirectory)
%WRITESTATICOPTIMIZATIONANALYSISPROVENANCE Write SO analysis provenance.
%
% result = pipeline.writeStaticOptimizationAnalysisProvenance( ...
%     projectCfg, analysisContext, analysisDirectory)
%
% Writes two compact provenance files beside study-level Static
% Optimization analysis outputs when:
%
%   projectCfg.analysis.staticOptimization.writeContextManifest == true
%
% Files:
%   static_optimization_analysis_context.csv
%       One-row, human-readable flattened manifest.
%
%   static_optimization_analysis_context.mat
%       Structured provenance preserving vectors/matrices such as
%       normalization breaks, project conditions/trials, and exclusions.
%
% This function intentionally excludes analysisContext.EligibleConfigurations
% because that table describes the selection UI candidate pool rather than
% the scientific identity of the selected analysis dataset.

    assert(isstruct(projectCfg) && isscalar(projectCfg), ...
        "SOAnalysisProvenance:InvalidProjectConfig", ...
        "projectCfg must be a scalar struct.");

    assert(isstruct(analysisContext) && isscalar(analysisContext), ...
        "SOAnalysisProvenance:InvalidAnalysisContext", ...
        "analysisContext must be a scalar struct.");

    analysisDirectory = string(analysisDirectory);

    assert(isscalar(analysisDirectory) && ...
            ~ismissing(analysisDirectory) && ...
            strlength(analysisDirectory) > 0, ...
        "SOAnalysisProvenance:InvalidAnalysisDirectory", ...
        "analysisDirectory must be a nonempty scalar path.");

    assert(isfolder(analysisDirectory), ...
        "SOAnalysisProvenance:AnalysisDirectoryMissing", ...
        "Analysis directory was not found:\n%s", ...
        analysisDirectory);

    assert(isfield(projectCfg, "analysis") && ...
            isstruct(projectCfg.analysis) && ...
            isfield(projectCfg.analysis, "staticOptimization"), ...
        "SOAnalysisProvenance:AnalysisConfigMissing", ...
        "projectCfg.analysis.staticOptimization is required.");

    analysisCfg = projectCfg.analysis.staticOptimization;

    assert(isfield(analysisCfg, "writeContextManifest") && ...
            islogical(analysisCfg.writeContextManifest) && ...
            isscalar(analysisCfg.writeContextManifest), ...
        "SOAnalysisProvenance:WriteFlagMissing", ...
        "analysisCfg.writeContextManifest must be a logical scalar.");

    csvFile = string(fullfile( ...
        analysisDirectory, ...
        "static_optimization_analysis_context.csv"));

    matFile = string(fullfile( ...
        analysisDirectory, ...
        "static_optimization_analysis_context.mat"));

    result = struct;
    result.SchemaVersion = 1;
    result.Written = false;
    result.CsvFile = csvFile;
    result.MatFile = matFile;
    result.Provenance = struct;

    if ~analysisCfg.writeContextManifest
        return;
    end

    requiredContextFields = [
        "SchemaVersion"
        "RequestedMode"
        "ResolvedMode"
        "Configured"
        "Legacy"
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
        "DisplayName"
        "AssessmentComplete"
        "IsFeasible"
        "FeasibilityStatus"
        "FeasibilityReason"
        "SearchRoot"
        "AnalysisDirectory"
    ];

    missingContextFields = requiredContextFields( ...
        ~isfield(analysisContext, cellstr(requiredContextFields)));

    assert(isempty(missingContextFields), ...
        "SOAnalysisProvenance:ContextFieldsMissing", ...
        "analysisContext is missing required fields: %s", ...
        strjoin(missingContextFields, ", "));

    createdAtUtc = datetime( ...
        "now", ...
        "TimeZone", "UTC", ...
        "Format", "yyyy-MM-dd'T'HH:mm:ss'Z'");

    provenance = struct;
    provenance.SchemaVersion = 1;
    provenance.CreatedAtUtc = createdAtUtc;
    provenance.ProjectConfigSchemaVersion = ...
        localOptionalScalar(projectCfg, "configSchemaVersion", NaN);
    provenance.AnalysisContextSchemaVersion = ...
        double(analysisContext.SchemaVersion);

    provenance.Selection = struct( ...
        "RequestedMode", string(analysisContext.RequestedMode), ...
        "ResolvedMode", string(analysisContext.ResolvedMode), ...
        "Configured", logical(analysisContext.Configured), ...
        "Legacy", logical(analysisContext.Legacy));

    provenance.Configuration = struct( ...
        "ConfigId", string(analysisContext.ConfigId), ...
        "MusclePercent", double(analysisContext.MusclePercent), ...
        "ActuatorPercent", double(analysisContext.ActuatorPercent), ...
        "DisplayName", string(analysisContext.DisplayName), ...
        "AssessmentComplete", logical(analysisContext.AssessmentComplete), ...
        "IsFeasible", logical(analysisContext.IsFeasible), ...
        "FeasibilityStatus", string(analysisContext.FeasibilityStatus), ...
        "FeasibilityReason", string(analysisContext.FeasibilityReason));

    provenance.Paths = struct( ...
        "SearchRoot", string(analysisContext.SearchRoot), ...
        "AnalysisDirectory", string(analysisContext.AnalysisDirectory));

    provenance.ProjectDataset = struct( ...
        "ConditionsDeg", ...
            localOptionalNumericVector(projectCfg, "conditions"), ...
        "Trials", ...
            localOptionalNumericVector(projectCfg, "trials"));

    provenance.AnalysisSettings = ...
        localExtractAnalysisSettings(analysisCfg);

    save(matFile, "provenance");

    flat = localFlattenProvenance(provenance);

    writetable( ...
        flat, ...
        csvFile, ...
        "Delimiter", ...
            ",", ...
        "WriteVariableNames", ...
            true, ...
        "QuoteStrings", ...
            "all");

    result.Written = true;
    result.Provenance = provenance;
end


function settings = localExtractAnalysisSettings(analysisCfg)

    settings = struct;

    settings.NormalizedBreaksPercent = ...
        localRequiredNumericVector( ...
            analysisCfg, ...
            "normalizedBreaksPercent");

    settings.PointsPerPhase = ...
        localRequiredNumericVector( ...
            analysisCfg, ...
            "pointsPerPhase");

    settings.StatisticsWindowPercent = ...
        localRequiredNumericVector( ...
            analysisCfg, ...
            "statisticsWindowPercent");

    settings.MotionOutputWindowPercent = ...
        localRequiredNumericVector( ...
            analysisCfg, ...
            "motionOutputWindowPercent");

    settings.ExtensorLandmarkPercent = ...
        localRequiredNumericScalar( ...
            analysisCfg, ...
            "extensorLandmarkPercent");

    settings.ExcludedTrials = ...
        localRequiredExcludedTrials(analysisCfg);

    settings.FlexionGroupName = ...
        localRequiredStringScalar( ...
            analysisCfg, ...
            "flexionGroupName");

    settings.ExtensionGroupName = ...
        localRequiredStringScalar( ...
            analysisCfg, ...
            "extensionGroupName");

    settings.ExpectedFlexorCount = ...
        localRequiredNumericScalar( ...
            analysisCfg, ...
            "expectedFlexorCount");

    settings.ExpectedExtensorCount = ...
        localRequiredNumericScalar( ...
            analysisCfg, ...
            "expectedExtensorCount");

    settings.TopReserveCount = ...
        localRequiredNumericScalar( ...
            analysisCfg, ...
            "topReserveCount");
end


function flat = localFlattenProvenance(provenance)

    flat = table( ...
        double(provenance.SchemaVersion), ...
        string(provenance.CreatedAtUtc), ...
        double(provenance.ProjectConfigSchemaVersion), ...
        double(provenance.AnalysisContextSchemaVersion), ...
        string(provenance.Selection.RequestedMode), ...
        string(provenance.Selection.ResolvedMode), ...
        logical(provenance.Selection.Configured), ...
        logical(provenance.Selection.Legacy), ...
        string(provenance.Configuration.ConfigId), ...
        double(provenance.Configuration.MusclePercent), ...
        double(provenance.Configuration.ActuatorPercent), ...
        string(provenance.Configuration.DisplayName), ...
        logical(provenance.Configuration.AssessmentComplete), ...
        logical(provenance.Configuration.IsFeasible), ...
        string(provenance.Configuration.FeasibilityStatus), ...
        string(provenance.Configuration.FeasibilityReason), ...
        string(provenance.Paths.SearchRoot), ...
        string(provenance.Paths.AnalysisDirectory), ...
        localFormatNumericVector( ...
            provenance.ProjectDataset.ConditionsDeg), ...
        localFormatNumericVector( ...
            provenance.ProjectDataset.Trials), ...
        localFormatNumericVector( ...
            provenance.AnalysisSettings.NormalizedBreaksPercent), ...
        localFormatNumericVector( ...
            provenance.AnalysisSettings.PointsPerPhase), ...
        localFormatNumericVector( ...
            provenance.AnalysisSettings.StatisticsWindowPercent), ...
        localFormatNumericVector( ...
            provenance.AnalysisSettings.MotionOutputWindowPercent), ...
        double(provenance.AnalysisSettings.ExtensorLandmarkPercent), ...
        localFormatExcludedTrials( ...
            provenance.AnalysisSettings.ExcludedTrials), ...
        string(provenance.AnalysisSettings.FlexionGroupName), ...
        string(provenance.AnalysisSettings.ExtensionGroupName), ...
        double(provenance.AnalysisSettings.ExpectedFlexorCount), ...
        double(provenance.AnalysisSettings.ExpectedExtensorCount), ...
        double(provenance.AnalysisSettings.TopReserveCount), ...
        "VariableNames", { ...
            "schema_version", ...
            "created_at_utc", ...
            "project_config_schema_version", ...
            "analysis_context_schema_version", ...
            "requested_mode", ...
            "resolved_mode", ...
            "configured", ...
            "legacy", ...
            "config_id", ...
            "muscle_percent", ...
            "actuator_percent", ...
            "display_name", ...
            "assessment_complete", ...
            "is_feasible", ...
            "feasibility_status", ...
            "feasibility_reason", ...
            "search_root", ...
            "analysis_directory", ...
            "conditions_deg", ...
            "trials", ...
            "normalized_breaks_percent", ...
            "points_per_phase", ...
            "statistics_window_percent", ...
            "motion_output_window_percent", ...
            "extensor_landmark_percent", ...
            "excluded_trials", ...
            "flexion_group_name", ...
            "extension_group_name", ...
            "expected_flexor_count", ...
            "expected_extensor_count", ...
            "top_reserve_count" ...
        });
end


function value = localOptionalScalar(config, fieldName, defaultValue)

    value = defaultValue;

    if ~isfield(config, fieldName)
        return;
    end

    candidate = config.(fieldName);

    if isnumeric(candidate) && isscalar(candidate) && isfinite(candidate)
        value = double(candidate);
    end
end


function value = localOptionalNumericVector(config, fieldName)

    value = zeros(1,0);

    if ~isfield(config, fieldName)
        return;
    end

    candidate = config.(fieldName);

    assert(isnumeric(candidate) && isvector(candidate) && ...
            all(isfinite(candidate)), ...
        "SOAnalysisProvenance:InvalidProjectVector", ...
        "projectCfg.%s must be a finite numeric vector.", ...
        fieldName);

    value = double(candidate(:).');
end


function value = localRequiredNumericVector(config, fieldName)

    assert(isfield(config, fieldName), ...
        "SOAnalysisProvenance:AnalysisSettingMissing", ...
        "analysisCfg.%s is required.", ...
        fieldName);

    candidate = config.(fieldName);

    assert(isnumeric(candidate) && isvector(candidate) && ...
            ~isempty(candidate) && all(isfinite(candidate)), ...
        "SOAnalysisProvenance:InvalidNumericVector", ...
        "analysisCfg.%s must be a nonempty finite numeric vector.", ...
        fieldName);

    value = double(candidate(:).');
end


function value = localRequiredNumericScalar(config, fieldName)

    assert(isfield(config, fieldName), ...
        "SOAnalysisProvenance:AnalysisSettingMissing", ...
        "analysisCfg.%s is required.", ...
        fieldName);

    candidate = config.(fieldName);

    assert(isnumeric(candidate) && isscalar(candidate) && ...
            isfinite(candidate), ...
        "SOAnalysisProvenance:InvalidNumericScalar", ...
        "analysisCfg.%s must be a finite numeric scalar.", ...
        fieldName);

    value = double(candidate);
end


function value = localRequiredStringScalar(config, fieldName)

    assert(isfield(config, fieldName), ...
        "SOAnalysisProvenance:AnalysisSettingMissing", ...
        "analysisCfg.%s is required.", ...
        fieldName);

    value = string(config.(fieldName));

    assert(isscalar(value) && ~ismissing(value) && strlength(value) > 0, ...
        "SOAnalysisProvenance:InvalidStringScalar", ...
        "analysisCfg.%s must be a nonempty scalar string.", ...
        fieldName);
end


function value = localRequiredExcludedTrials(analysisCfg)

    assert(isfield(analysisCfg, "excludedTrials"), ...
        "SOAnalysisProvenance:AnalysisSettingMissing", ...
        "analysisCfg.excludedTrials is required.");

    value = double(analysisCfg.excludedTrials);

    assert(isnumeric(value) && ismatrix(value) && ...
            size(value,2) == 2 && all(isfinite(value), "all"), ...
        "SOAnalysisProvenance:InvalidExcludedTrials", ...
        "analysisCfg.excludedTrials must be an N-by-2 finite numeric matrix.");
end


function text = localFormatNumericVector(values)

    values = double(values(:).');

    if isempty(values)
        text = "";
        return;
    end

    text = strjoin(compose("%.15g", values), " ");
end


function text = localFormatExcludedTrials(excludedTrials)

    if isempty(excludedTrials)
        text = "";
        return;
    end

    entries = strings(size(excludedTrials,1),1);

    for iRow = 1:size(excludedTrials,1)
        entries(iRow) = string(sprintf( ...
            "%g:%g", ...
            excludedTrials(iRow,1), ...
            excludedTrials(iRow,2)));
    end

    text = strjoin(entries, ";");
end
