%% batch_run_process_4.m
% Batch Process 4:
%   execute and audit Static Optimization.
%
% Every trial is resolved through pipeline.resolveTrialContext() and run
% through pipeline.runStaticOptimizationTrial(). The batch script contains
% no independent Static Optimization execution logic.
%
% Prerequisite:
%   Successful Process-3 checkpoint and prepared SO setup for each trial.
%
% Output:
%   <outputRoot>/batch_qc/process_4_static_optimization_summary.csv
%   <outputRoot>/batch_qc/process_4_static_optimization_summary.mat

%% SECTION 0 — PROJECT CONFIGURATION

clear;
clc;
dbstop if error

projectCfg = ...
    load_project_config();

processCfg = struct;

processCfg.conditions = ...
    projectCfg.conditions(:).';

processCfg.trials = ...
    projectCfg.trials(:).';

processCfg.overwrite = ...
    projectCfg.overwriteExisting;

processCfg.enableParallel = ...
    projectCfg.batchProcessing.enableParallel;

processCfg.maxWorkers = ...
    projectCfg.batchProcessing.maxWorkers;

processCfg.continueOnError = ...
    projectCfg.batchProcessing.continueOnError;

processCfg.poolProfile = ...
    projectCfg.batchProcessing.poolProfile;

processCfg.closePoolWhenFinished = ...
    projectCfg.batchProcessing.closePoolWhenFinished;

processCfg.executeStaticOptimization = ...
    true;

fprintf( ...
    "Static Optimization output requirements:\n" + ...
    "  Force output required:      %d\n" + ...
    "  Activation output required: %d\n" + ...
    "  Time tolerance:             %.9g s\n", ...
    projectCfg.pipeline.staticOptimization.requireForceOutput, ...
    projectCfg.pipeline.staticOptimization.requireActivationOutput, ...
    projectCfg.pipeline.staticOptimization.timeToleranceSec);

%% SECTION 1 — BUILD JOB MATRIX

[conditionGrid, trialGrid] = ...
    ndgrid( ...
        processCfg.conditions, ...
        processCfg.trials);

jobConditions = ...
    conditionGrid(:);

jobTrials = ...
    trialGrid(:);

nJobs = ...
    numel(jobConditions);

assert(nJobs > 0, ...
    "BatchProcess4:NoJobs", ...
    "No Process-4 jobs were configured.");

fprintf( ...
    "Running Process 4 for %d jobs " + ...
    "(%d conditions x %d trials).\n", ...
    nJobs, ...
    numel(processCfg.conditions), ...
    numel(processCfg.trials));

%% SECTION 2 — PRE-FLIGHT CONTEXT RESOLUTION

for jobIndex = 1:nJobs

    pipeline.resolveTrialContext( ...
        projectCfg, ...
        jobConditions(jobIndex), ...
        jobTrials(jobIndex));
end

fprintf( ...
    "Trial-context pre-flight passed for all %d jobs.\n", ...
    nJobs);

%% SECTION 3 — CONFIGURE PARALLEL POOL

pool = [];

if processCfg.enableParallel

    pool = ...
        gcp("nocreate");

    if isempty(pool)

        pool = ...
            parpool( ...
                char(processCfg.poolProfile), ...
                processCfg.maxWorkers);

    elseif pool.NumWorkers ~= ...
            processCfg.maxWorkers

        delete(pool);

        pool = ...
            parpool( ...
                char(processCfg.poolProfile), ...
                processCfg.maxWorkers);
    end

    fprintf( ...
        "Parallel execution enabled with %d workers.\n", ...
        pool.NumWorkers);

else

    fprintf( ...
        "Parallel execution disabled; running serially.\n");
end

%% SECTION 4 — RUN JOBS

jobResults = ...
    cell(nJobs,1);

batchStart = tic;

if processCfg.enableParallel

    parfor jobIndex = 1:nJobs

        jobResults{jobIndex} = ...
            localRunProcess4Job( ...
                projectCfg, ...
                jobConditions(jobIndex), ...
                jobTrials(jobIndex), ...
                processCfg);
    end

else

    for jobIndex = 1:nJobs

        jobResults{jobIndex} = ...
            localRunProcess4Job( ...
                projectCfg, ...
                jobConditions(jobIndex), ...
                jobTrials(jobIndex), ...
                processCfg);

        fprintf( ...
            "[%d/%d] %s: %s\n", ...
            jobIndex, ...
            nJobs, ...
            jobResults{jobIndex}.TrialStem, ...
            jobResults{jobIndex}.Status);
    end
end

batchDurationSeconds = ...
    toc(batchStart);

%% SECTION 5 — COLLATE SUMMARY

summaryTable = ...
    struct2table( ...
        vertcat(jobResults{:}));

summaryTable = ...
    sortrows( ...
        summaryTable, ...
        {'ConditionDeg','TrialNumber'});

nSucceeded = ...
    nnz(summaryTable.Succeeded);

nFailed = ...
    height(summaryTable) - ...
    nSucceeded;

fprintf( ...
    "\nProcess 4 complete in %.3f s.\n", ...
    batchDurationSeconds);

fprintf( ...
    "Succeeded: %d\nFailed: %d\n", ...
    nSucceeded, ...
    nFailed);

disp(summaryTable(:, [
    "ConditionDeg"
    "TrialNumber"
    "Status"
    "DurationSeconds"
    "StaticOptimizationDurationSeconds"
    "ForceRows"
    "ActivationRows"
    "OutputAuditPassed"
]));

%% SECTION 6 — WRITE BATCH SUMMARY

batchQcDirectory = ...
    string(fullfile( ...
        projectCfg.outputRoot, ...
        "batch_qc"));

if ~isfolder(batchQcDirectory)
    mkdir(batchQcDirectory);
end

summaryCsv = ...
    string(fullfile( ...
        batchQcDirectory, ...
        "process_4_static_optimization_summary.csv"));

summaryMat = ...
    string(fullfile( ...
        batchQcDirectory, ...
        "process_4_static_optimization_summary.mat"));

existingSummaryFiles = [
    summaryCsv
    summaryMat
];

existingSummaryFiles = ...
    existingSummaryFiles( ...
        isfile(existingSummaryFiles));

if ~processCfg.overwrite && ...
        ~isempty(existingSummaryFiles)

    error( ...
        "BatchProcess4:SummaryExists", ...
        "Batch summary output already exists:\n%s", ...
        strjoin(existingSummaryFiles, newline));
end

writetable( ...
    summaryTable, ...
    summaryCsv);

batchSummary = struct;

batchSummary.SchemaVersion = ...
    1;

batchSummary.Process = ...
    4;

batchSummary.Stage = ...
    "static_optimization";

batchSummary.CompletedAt = ...
    string(datetime("now"));

batchSummary.DurationSeconds = ...
    batchDurationSeconds;

batchSummary.Configuration = ...
    processCfg;

batchSummary.SummaryTable = ...
    summaryTable;

batchSummary.Succeeded = ...
    nFailed == 0;

save( ...
    summaryMat, ...
    "batchSummary");

fprintf( ...
    "Batch summary CSV:\n%s\n", ...
    summaryCsv);

fprintf( ...
    "Batch summary MAT:\n%s\n", ...
    summaryMat);

%% SECTION 7 — CLEAN UP / FAILURE POLICY

if processCfg.enableParallel && ...
        processCfg.closePoolWhenFinished

    pool = ...
        gcp("nocreate");

    if ~isempty(pool)
        delete(pool);
    end
end

if nFailed > 0 && ...
        ~processCfg.continueOnError

    error( ...
        "BatchProcess4:JobFailures", ...
        "%d Process-4 jobs failed. " + ...
        "See the batch summary for details.", ...
        nFailed);
end


function job = localRunProcess4Job( ...
        projectCfg, conditionDeg, trialNumber, processCfg)

    jobStart = tic;

    trial = ...
        pipeline.resolveTrialContext( ...
            projectCfg, ...
            conditionDeg, ...
            trialNumber);

    job = struct;

    job.ConditionDeg = ...
        conditionDeg;

    job.TrialNumber = ...
        trialNumber;

    job.TrialStem = ...
        trial.TrialStem;

    job.Status = ...
        "not_started";

    job.Succeeded = ...
        false;

    job.DurationSeconds = ...
        NaN;

    job.StaticOptimizationDurationSeconds = ...
        NaN;

    job.Process3CheckpointFile = ...
        trial.Paths.StaticOptimizationPrep.CheckpointFile;

    job.StaticOptimizationSetupFile = ...
        trial.Paths.StaticOptimization.SetupFile;

    job.ResultsDirectory = ...
        trial.Paths.StaticOptimization.ResultsDirectory;

    job.ForceFile = ...
        "";

    job.ActivationFile = ...
        "";

    job.ForceRows = ...
        NaN;

    job.ActivationRows = ...
        NaN;

    job.OutputAuditPassed = ...
        false;

    job.CheckpointFile = ...
        trial.Paths.StaticOptimization.CheckpointFile;

    job.ErrorIdentifier = ...
        "";

    job.ErrorMessage = ...
        "";

    try

        result = ...
            pipeline.runStaticOptimizationTrial( ...
                projectCfg, ...
                trial, ...
                "ExecuteStaticOptimization", ...
                    processCfg.executeStaticOptimization, ...
                "Overwrite", ...
                    processCfg.overwrite, ...
                "WriteQc", ...
                    true, ...
                "SaveCheckpoint", ...
                    true, ...
                "PrintProgress", ...
                    false);

        job.Status = ...
            "completed";

        job.Succeeded = ...
            result.Completed;

        job.ForceFile = ...
            result.ForceFile;

        job.ActivationFile = ...
            result.ActivationFile;

        if isstruct(result.RunResult) && ...
                isfield( ...
                    result.RunResult, ...
                    "DurationSeconds")

            job.StaticOptimizationDurationSeconds = ...
                result.RunResult.DurationSeconds;
        end

        if ~isempty(result.OutputAudit)

            job.OutputAuditPassed = ...
                all(result.OutputAudit.Passed);

            forceRows = ...
                result.OutputAudit( ...
                    result.OutputAudit.OutputType == "force", ...
                    :);

            activationRows = ...
                result.OutputAudit( ...
                    result.OutputAudit.OutputType == "activation", ...
                    :);

            if height(forceRows) == 1

                job.ForceRows = ...
                    forceRows.NumRows;
            end

            if height(activationRows) == 1

                job.ActivationRows = ...
                    activationRows.NumRows;
            end
        end

    catch exception

        job.Status = ...
            "failed";

        job.ErrorIdentifier = ...
            string(exception.identifier);

        job.ErrorMessage = ...
            string(exception.message);
    end

    job.DurationSeconds = ...
        toc(jobStart);
end
