%% batch_run_process_1.m
% Batch Process 1:
%   Model A + initialization inverse kinematics.
%
% Every trial is resolved through pipeline.resolveTrialContext() and run
% through pipeline.runInitializationIkTrial(). The batch script contains no
% independent Model-A/IK implementation.
%
% Output:
%   <outputRoot>/batch_qc/process_1_initialization_ik_summary.csv
%   <outputRoot>/batch_qc/process_1_initialization_ik_summary.mat

%% SECTION 0 — PROJECT CONFIGURATION

clear;
clc;
dbstop if error

projectCfg = ...
    load_project_config();

processCfg = struct;

processCfg.conditions = ...
    projectCfg.conditions(:).';

processCfg.trials = ...
    projectCfg.trials(:).';

processCfg.overwrite = ...
    projectCfg.overwriteExisting;

processCfg.enableParallel = ...
    projectCfg.batchProcessing.enableParallel;

processCfg.maxWorkers = ...
    projectCfg.batchProcessing.maxWorkers;

processCfg.continueOnError = ...
    projectCfg.batchProcessing.continueOnError;

processCfg.poolProfile = ...
    projectCfg.batchProcessing.poolProfile;

processCfg.closePoolWhenFinished = ...
    projectCfg.batchProcessing.closePoolWhenFinished;

% Process 1 always executes IK in batch mode.
processCfg.executeIk = true;

%% SECTION 1 — BUILD JOB MATRIX

[conditionGrid, trialGrid] = ndgrid( ...
    processCfg.conditions, ...
    processCfg.trials);

jobConditions = ...
    conditionGrid(:);

jobTrials = ...
    trialGrid(:);

nJobs = ...
    numel(jobConditions);

assert(nJobs > 0, ...
    "BatchProcess1:NoJobs", ...
    "No Process-1 jobs were configured.");

fprintf( ...
    "Running Process 1 for %d jobs " + ...
    "(%d conditions x %d trials).\n", ...
    nJobs, ...
    numel(processCfg.conditions), ...
    numel(processCfg.trials));

%% SECTION 2 — PRE-FLIGHT RESOLUTION

% Resolve all contexts once before starting OpenSim work. This catches
% naming/configuration problems before any job mutates the output tree.

for jobIndex = 1:nJobs

    pipeline.resolveTrialContext( ...
        projectCfg, ...
        jobConditions(jobIndex), ...
        jobTrials(jobIndex));
end

fprintf( ...
    "Trial-context pre-flight passed for all %d jobs.\n", ...
    nJobs);

%% SECTION 3 — CONFIGURE PARALLEL POOL

pool = [];

if processCfg.enableParallel

    pool = ...
        gcp("nocreate");

    if isempty(pool)

        pool = parpool( ...
            char(processCfg.poolProfile), ...
            processCfg.maxWorkers);

    elseif pool.NumWorkers ~= ...
            processCfg.maxWorkers

        delete(pool);

        pool = parpool( ...
            char(processCfg.poolProfile), ...
            processCfg.maxWorkers);
    end

    fprintf( ...
        "Parallel execution enabled with %d workers.\n", ...
        pool.NumWorkers);

else

    fprintf( ...
        "Parallel execution disabled; running serially.\n");
end

%% SECTION 4 — RUN JOBS

jobResults = ...
    cell(nJobs,1);

batchStart = tic;

if processCfg.enableParallel

    parfor jobIndex = 1:nJobs

        jobResults{jobIndex} = ...
            localRunProcess1Job( ...
                projectCfg, ...
                jobConditions(jobIndex), ...
                jobTrials(jobIndex), ...
                processCfg);
    end

else

    for jobIndex = 1:nJobs

        jobResults{jobIndex} = ...
            localRunProcess1Job( ...
                projectCfg, ...
                jobConditions(jobIndex), ...
                jobTrials(jobIndex), ...
                processCfg);

        fprintf( ...
            "[%d/%d] %s: %s\n", ...
            jobIndex, ...
            nJobs, ...
            jobResults{jobIndex}.TrialStem, ...
            jobResults{jobIndex}.Status);
    end
end

batchDurationSeconds = ...
    toc(batchStart);

%% SECTION 5 — COLLATE SUMMARY

summaryTable = ...
    struct2table( ...
        vertcat(jobResults{:}));

summaryTable = ...
    sortrows( ...
        summaryTable, ...
        {'ConditionDeg','TrialNumber'});

nSucceeded = ...
    nnz(summaryTable.Succeeded);

nFailed = ...
    height(summaryTable) - ...
    nSucceeded;

fprintf( ...
    "\nProcess 1 complete in %.3f s.\n", ...
    batchDurationSeconds);

fprintf( ...
    "Succeeded: %d\nFailed: %d\n", ...
    nSucceeded, ...
    nFailed);

disp(summaryTable(:, [
    "ConditionDeg"
    "TrialNumber"
    "Status"
    "DurationSeconds"
]));

%% SECTION 6 — WRITE BATCH SUMMARY

batchQcDirectory = string(fullfile( ...
    projectCfg.outputRoot, ...
    "batch_qc"));

if ~isfolder(batchQcDirectory)
    mkdir(batchQcDirectory);
end

summaryCsv = string(fullfile( ...
    batchQcDirectory, ...
    "process_1_initialization_ik_summary.csv"));

summaryMat = string(fullfile( ...
    batchQcDirectory, ...
    "process_1_initialization_ik_summary.mat"));

existingSummaryFiles = [
    summaryCsv
    summaryMat
];

existingSummaryFiles = ...
    existingSummaryFiles( ...
        isfile(existingSummaryFiles));

if ~processCfg.overwrite && ...
        ~isempty(existingSummaryFiles)

    error( ...
        "BatchProcess1:SummaryExists", ...
        "Batch summary output already exists:\n%s", ...
        strjoin(existingSummaryFiles, newline));
end

writetable( ...
    summaryTable, ...
    summaryCsv);

batchSummary = struct;

batchSummary.SchemaVersion = 1;
batchSummary.Process = 1;
batchSummary.Stage = "initialization_ik";
batchSummary.CompletedAt = string(datetime("now"));
batchSummary.DurationSeconds = batchDurationSeconds;
batchSummary.Configuration = processCfg;
batchSummary.SummaryTable = summaryTable;
batchSummary.Succeeded = nFailed == 0;

save( ...
    summaryMat, ...
    "batchSummary");

fprintf( ...
    "Batch summary CSV:\n%s\n", ...
    summaryCsv);

fprintf( ...
    "Batch summary MAT:\n%s\n", ...
    summaryMat);

%% SECTION 7 — CLEAN UP / FAILURE POLICY

if processCfg.enableParallel && ...
        processCfg.closePoolWhenFinished

    pool = ...
        gcp("nocreate");

    if ~isempty(pool)
        delete(pool);
    end
end

if nFailed > 0 && ...
        ~processCfg.continueOnError

    error( ...
        "BatchProcess1:JobFailures", ...
        "%d Process-1 jobs failed. " + ...
        "See the batch summary for details.", ...
        nFailed);
end


function job = localRunProcess1Job( ...
        projectCfg, conditionDeg, trialNumber, processCfg)

    jobStart = tic;

    trial = ...
        pipeline.resolveTrialContext( ...
            projectCfg, ...
            conditionDeg, ...
            trialNumber);

    job = struct;

    job.ConditionDeg = ...
        conditionDeg;

    job.TrialNumber = ...
        trialNumber;

    job.TrialStem = ...
        trial.TrialStem;

    job.Status = ...
        "not_started";

    job.Succeeded = ...
        false;

    job.DurationSeconds = ...
        NaN;

    job.IkDurationSeconds = ...
        NaN;

    job.ModelAFile = ...
        trial.Paths.Initialization.ModelAFile;

    job.IkMotionFile = ...
        trial.Paths.Initialization.IkMotionFile;

    job.CheckpointFile = ...
        trial.Paths.Initialization.CheckpointFile;

    job.ErrorIdentifier = ...
        "";

    job.ErrorMessage = ...
        "";

    try

        result = ...
            pipeline.runInitializationIkTrial( ...
                projectCfg, ...
                trial, ...
                "ExecuteIk", ...
                    processCfg.executeIk, ...
                "Overwrite", ...
                    processCfg.overwrite, ...
                "WriteQc", ...
                    true, ...
                "SaveCheckpoint", ...
                    true, ...
                "PrintProgress", ...
                    false);

        job.Status = ...
            "completed";

        job.Succeeded = ...
            result.Completed;

        if isstruct(result.IkRunResult) && ...
                isfield( ...
                    result.IkRunResult, ...
                    "DurationSeconds")

            job.IkDurationSeconds = ...
                result.IkRunResult.DurationSeconds;
        end

    catch exception

        job.Status = ...
            "failed";

        job.ErrorIdentifier = ...
            string(exception.identifier);

        job.ErrorMessage = ...
            string(exception.message);
    end

    job.DurationSeconds = ...
        toc(jobStart);
end
