%% batch_run_process_3.m
% Batch Process 3:
%   Model C + Body Kinematics + HSF + ExternalLoads + SO setup.
%
% Every trial is resolved through pipeline.resolveTrialContext() and run
% through pipeline.prepareStaticOptimizationTrial(). The batch script
% contains no independent Process-3 biomechanics implementation.
%
% Prerequisite:
%   Successful Process-2 checkpoint for each trial.
%
% Output when force-capacity configuration is enabled:
%
%   <outputRoot>/
%       static_optimization_configs/
%           <ConfigId>/
%               batch_qc/
%                   process_3_static_optimization_prep_summary.csv
%                   process_3_static_optimization_prep_summary.mat
%
% Output when force-capacity configuration is disabled:
%
%   <outputRoot>/
%       batch_qc/
%           process_3_static_optimization_prep_summary.csv
%           process_3_static_optimization_prep_summary.mat

%% SECTION 0 — PROJECT CONFIGURATION

clear;
clc;
dbstop if error

projectCfg = ...
    load_project_config();

processCfg = struct;

% processCfg.conditions = ...
%     projectCfg.conditions(:).';
% 
% processCfg.trials = ...
%     projectCfg.trials(:).';
processCfg.conditions = 0;
processCfg.trials = 1;

processCfg.overwrite = ...
    projectCfg.overwriteExisting;

processCfg.enableParallel = ...
    projectCfg.batchProcessing.enableParallel;

processCfg.maxWorkers = ...
    projectCfg.batchProcessing.maxWorkers;

processCfg.continueOnError = ...
    projectCfg.batchProcessing.continueOnError;

processCfg.poolProfile = ...
    projectCfg.batchProcessing.poolProfile;

processCfg.closePoolWhenFinished = ...
    projectCfg.batchProcessing.closePoolWhenFinished;

processCfg.executeBodyKinematics = ...
    true;

% Strength-configuration batch identity

processCfg.strengthConfigEnabled = ...
    logical(projectCfg.forceCapacity.enabled);

processCfg.configId = "";
processCfg.musclePercent = NaN;
processCfg.actuatorPercent = NaN;

strengthContext = struct;

if processCfg.strengthConfigEnabled

    strengthContext = ...
        pipeline.resolveStrengthConfigContext( ...
            projectCfg);

    processCfg.configId = ...
        strengthContext.ConfigId;

    processCfg.musclePercent = ...
        strengthContext.MusclePercent;

    processCfg.actuatorPercent = ...
        strengthContext.ActuatorPercent;

    assert( ...
        strlength(processCfg.configId) > 0, ...
        "BatchProcess3:StrengthConfigIdentityMissing", ...
        "Enabled strength configuration did not resolve a valid ConfigId.");

end

%% SECTION 1 — BUILD JOB MATRIX

[conditionGrid, trialGrid] = ndgrid( ...
    processCfg.conditions, ...
    processCfg.trials);

jobConditions = ...
    conditionGrid(:);

jobTrials = ...
    trialGrid(:);

nJobs = ...
    numel(jobConditions);

assert(nJobs > 0, ...
    "BatchProcess3:NoJobs", ...
    "No Process-3 jobs were configured.");

if processCfg.strengthConfigEnabled

    fprintf( ...
        "Model C force-capacity configuration enabled.\n" + ...
        "Config ID: %s\n" + ...
        "Muscle capacity: %g%%\n" + ...
        "Actuator capacity: %g%%\n" + ...
        "Config file:\n%s\n" + ...
        "Apply mode: %s\n", ...
        processCfg.configId, ...
        processCfg.musclePercent, ...
        processCfg.actuatorPercent, ...
        projectCfg.forceCapacity.configFile, ...
        projectCfg.forceCapacity.applyMode);

else

    fprintf( ...
        "Model C force-capacity configuration disabled.\n");
end

fprintf( ...
    "Running Process 3 for %d jobs " + ...
    "(%d conditions x %d trials).\n", ...
    nJobs, ...
    numel(processCfg.conditions), ...
    numel(processCfg.trials));

%% SECTION 2 — PRE-FLIGHT CONTEXT RESOLUTION

for jobIndex = 1:nJobs

    pipeline.resolveTrialContext( ...
        projectCfg, ...
        jobConditions(jobIndex), ...
        jobTrials(jobIndex));
end

fprintf( ...
    "Trial-context pre-flight passed for all %d jobs.\n", ...
    nJobs);

%% SECTION 3 — CONFIGURE PARALLEL POOL

pool = [];

if processCfg.enableParallel

    pool = ...
        gcp("nocreate");

    if isempty(pool)

        pool = parpool( ...
            char(processCfg.poolProfile), ...
            processCfg.maxWorkers);

    elseif pool.NumWorkers ~= ...
            processCfg.maxWorkers

        delete(pool);

        pool = parpool( ...
            char(processCfg.poolProfile), ...
            processCfg.maxWorkers);
    end

    fprintf( ...
        "Parallel execution enabled with %d workers.\n", ...
        pool.NumWorkers);

else

    fprintf( ...
        "Parallel execution disabled; running serially.\n");
end

%% SECTION 4 — RUN JOBS

jobResults = ...
    cell(nJobs,1);

batchStart = tic;

if processCfg.enableParallel

    parfor jobIndex = 1:nJobs

        jobResults{jobIndex} = ...
            localRunProcess3Job( ...
                projectCfg, ...
                jobConditions(jobIndex), ...
                jobTrials(jobIndex), ...
                processCfg);
    end

else

    for jobIndex = 1:nJobs

        jobResults{jobIndex} = ...
            localRunProcess3Job( ...
                projectCfg, ...
                jobConditions(jobIndex), ...
                jobTrials(jobIndex), ...
                processCfg);

        fprintf( ...
            "[%d/%d] %s: %s\n", ...
            jobIndex, ...
            nJobs, ...
            jobResults{jobIndex}.TrialStem, ...
            jobResults{jobIndex}.Status);
    end
end

batchDurationSeconds = ...
    toc(batchStart);

%% SECTION 5 — COLLATE SUMMARY

summaryTable = ...
    struct2table( ...
        vertcat(jobResults{:}));

summaryTable = ...
    sortrows( ...
        summaryTable, ...
        {'ConditionDeg','TrialNumber'});

nSucceeded = ...
    nnz(summaryTable.Succeeded);

nFailed = ...
    height(summaryTable) - ...
    nSucceeded;

fprintf( ...
    "\nProcess 3 complete in %.3f s.\n", ...
    batchDurationSeconds);

fprintf( ...
    "Succeeded: %d\nFailed: %d\n", ...
    nSucceeded, ...
    nFailed);

disp(summaryTable(:, [
    "ConditionDeg"
    "TrialNumber"
    "Status"
    "DurationSeconds"
    "BodyKinematicsDurationSeconds"
    "LiftOffTimeSec"
    "RecontactTimeSec"
    "SkullMassKg"
]));

%% SECTION 6 — WRITE BATCH SUMMARY

if processCfg.strengthConfigEnabled

    batchQcDirectory = ...
        strengthContext.Paths.BatchQcDirectory;

else

    batchQcDirectory = ...
        string(fullfile( ...
            projectCfg.outputRoot, ...
            "batch_qc"));
end

if ~isfolder(batchQcDirectory)
    mkdir(batchQcDirectory);
end

summaryCsv = ...
    string(fullfile( ...
        batchQcDirectory, ...
        "process_3_static_optimization_prep_summary.csv"));

summaryMat = ...
    string(fullfile( ...
        batchQcDirectory, ...
        "process_3_static_optimization_prep_summary.mat"));

existingSummaryFiles = [
    summaryCsv
    summaryMat
];

existingSummaryFiles = ...
    existingSummaryFiles( ...
        isfile(existingSummaryFiles));

if ~processCfg.overwrite && ...
        ~isempty(existingSummaryFiles)

    error( ...
        "BatchProcess3:SummaryExists", ...
        "Batch summary output already exists:\n%s", ...
        strjoin(existingSummaryFiles, newline));
end

writetable( ...
    summaryTable, ...
    summaryCsv);

batchSummary = struct;

batchSummary.SchemaVersion = ...
    2;

batchSummary.Process = ...
    3;

batchSummary.Stage = ...
    "static_optimization_prep";

batchSummary.StrengthConfigEnabled = ...
    processCfg.strengthConfigEnabled;

batchSummary.ConfigId = ...
    processCfg.configId;

batchSummary.MusclePercent = ...
    processCfg.musclePercent;

batchSummary.ActuatorPercent = ...
    processCfg.actuatorPercent;

batchSummary.CompletedAt = ...
    string(datetime("now"));

batchSummary.DurationSeconds = ...
    batchDurationSeconds;

batchSummary.Configuration = ...
    processCfg;

batchSummary.SummaryTable = ...
    summaryTable;

batchSummary.Succeeded = ...
    nFailed == 0;

save( ...
    summaryMat, ...
    "batchSummary");

fprintf( ...
    "Batch summary CSV:\n%s\n", ...
    summaryCsv);

fprintf( ...
    "Batch summary MAT:\n%s\n", ...
    summaryMat);

%% SECTION 7 — CLEAN UP / FAILURE POLICY

if processCfg.enableParallel && ...
        processCfg.closePoolWhenFinished

    pool = ...
        gcp("nocreate");

    if ~isempty(pool)
        delete(pool);
    end
end

if nFailed > 0 && ...
        ~processCfg.continueOnError

    error( ...
        "BatchProcess3:JobFailures", ...
        "%d Process-3 jobs failed. " + ...
        "See the batch summary for details.", ...
        nFailed);
end


function job = localRunProcess3Job( ...
        projectCfg, conditionDeg, trialNumber, processCfg)

    jobStart = tic;

    trial = ...
        pipeline.resolveTrialContext( ...
            projectCfg, ...
            conditionDeg, ...
            trialNumber);

    job = struct;

    job.ConditionDeg = ...
        conditionDeg;

    job.TrialNumber = ...
        trialNumber;

    job.TrialStem = ...
        trial.TrialStem;

    job.ConfigId = ...
        processCfg.configId;

    job.MusclePercent = ...
        processCfg.musclePercent;

    job.ActuatorPercent = ...
        processCfg.actuatorPercent;

    job.Status = ...
        "not_started";

    job.Succeeded = ...
        false;

    job.DurationSeconds = ...
        NaN;

    job.BodyKinematicsDurationSeconds = ...
        NaN;

    job.ModelBCheckpointFile = ...
        trial.Paths.ModelB.CheckpointFile;

    job.ModelCFile = ...
        trial.Paths.StaticOptimizationPrep.ModelCFile;

    job.HsfMotionFile = ...
        trial.Paths.StaticOptimizationPrep. ...
            HeadSupportForce.MotionFile;

    job.ExternalLoadsFile = ...
        trial.Paths.StaticOptimizationPrep. ...
            HeadSupportForce.ExternalLoadsFile;

    job.StaticOptimizationSetupFile = ...
        trial.Paths.StaticOptimization.SetupFile;

    job.CheckpointFile = ...
        trial.Paths.StaticOptimizationPrep.CheckpointFile;

    job.ForceConfigApplied = ...
        false;

    job.LiftOffTimeSec = ...
        NaN;

    job.RecontactTimeSec = ...
        NaN;

    job.PeakComExcursionMm = ...
        NaN;

    job.SkullMassKg = ...
        NaN;

    job.HsfValidationPassed = ...
        false;

    job.ExternalLoadsVerified = ...
        false;

    job.StaticOptimizationSetupVerified = ...
        false;

    job.ErrorIdentifier = ...
        "";

    job.ErrorMessage = ...
        "";

    try

        result = ...
            pipeline.prepareStaticOptimizationTrial( ...
                projectCfg, ...
                trial, ...
                "ExecuteBodyKinematics", ...
                    processCfg.executeBodyKinematics, ...
                "Overwrite", ...
                    processCfg.overwrite, ...
                "WriteQc", ...
                    true, ...
                "SaveCheckpoint", ...
                    true, ...
                "EventFigureVisible", ...
                    "off", ...
                "PrintProgress", ...
                    false);

        job.Status = ...
            "completed";

        job.Succeeded = ...
            result.Completed;

        if isstruct(result.BodyKinematicsResult) && ...
                isfield( ...
                    result.BodyKinematicsResult, ...
                    "DurationSeconds")

            job.BodyKinematicsDurationSeconds = ...
                result.BodyKinematicsResult.DurationSeconds;
        end

        job.ForceConfigApplied = ...
            logical( ...
                result.ForceCapacityConfigResult.Applied);

        if isstruct(result.EventDetectionResult) && ...
                isfield( ...
                    result.EventDetectionResult, ...
                    "LiftOffTime")

            job.LiftOffTimeSec = ...
                result.EventDetectionResult.LiftOffTime;

            job.RecontactTimeSec = ...
                result.EventDetectionResult.RecontactTime;

            job.PeakComExcursionMm = ...
                result.EventDetectionResult.PeakExcursionM * ...
                1000;
        end

        if isstruct(result.HsfParameters) && ...
                isfield( ...
                    result.HsfParameters, ...
                    "SkullMassKg")

            job.SkullMassKg = ...
                result.HsfParameters.SkullMassKg;
        end

        if isstruct(result.HsfResult) && ...
                isfield( ...
                    result.HsfResult, ...
                    "Validation")

            job.HsfValidationPassed = ...
                logical( ...
                    result.HsfResult.Validation.Passed);
        end

        job.ExternalLoadsVerified = ...
            logical( ...
                result.ExternalLoadsResult. ...
                    VerificationPassed);

        job.StaticOptimizationSetupVerified = ...
            logical( ...
                result.StaticOptimizationSetupResult. ...
                    VerificationPassed);

    catch exception

        job.Status = ...
            "failed";

        job.ErrorIdentifier = ...
            string(exception.identifier);

        job.ErrorMessage = ...
            string(exception.message);
    end

    job.DurationSeconds = ...
        toc(jobStart);
end
