function context = resolveStrengthConfigContext(projectCfg)
%RESOLVESTRENGTHCONFIGCONTEXT Resolve canonical strength-config identity and paths.
%
% context = pipeline.resolveStrengthConfigContext(projectCfg)
%
% This function is the single authority for configuration-level identity
% and output-root construction for percentage-based Static Optimization
% force-capacity configurations.
%
% It is intentionally SIDE-EFFECT FREE:
%
%   - it does not create directories;
%   - it does not require the configured JSON file to exist;
%   - it does not load or apply the force-capacity configuration;
%   - it does not modify projectCfg.
%
% The active force-capacity configuration must use the canonical filename:
%
%   m{muscle_percent}p_a{actuator_percent}p.json
%
% Example:
%
%   m25p_a75p.json
%
% resolves to:
%
%   context.ConfigId        = "m25p_a75p"
%   context.MusclePercent   = 25
%   context.ActuatorPercent = 75
%
% CANONICAL OUTPUT LAYOUT
%
%   <outputRoot>/
%       static_optimization_configs/
%           <ConfigId>/
%               batch_qc/
%               static_optimization_analysis/
%
% Trial-specific Process-3 and Process-4 paths will subsequently be
% resolved beneath context.Paths.ConfigRoot.
%
% IMPORTANT
%
% Percentage-based configuration identity assumes target-mode application.
% Scale mode can produce different absolute capacities from the same JSON
% depending on the target model's current values and therefore cannot share
% the same deterministic ConfigId namespace.

    %% Validate project configuration

    assert(isstruct(projectCfg) && isscalar(projectCfg), ...
        "StrengthConfigContext:InvalidProjectConfig", ...
        "projectCfg must be a scalar struct.");

    requiredTopFields = [
        "outputRoot"
        "forceCapacity"
    ];

    missingTopFields = ...
        requiredTopFields( ...
            ~isfield( ...
                projectCfg, ...
                cellstr(requiredTopFields)));

    assert(isempty(missingTopFields), ...
        "StrengthConfigContext:ProjectConfigFieldsMissing", ...
        "projectCfg is missing required fields: %s", ...
        strjoin(missingTopFields, ", "));

    assert(isstruct(projectCfg.forceCapacity) && ...
            isscalar(projectCfg.forceCapacity), ...
        "StrengthConfigContext:InvalidForceCapacityConfig", ...
        "projectCfg.forceCapacity must be a scalar struct.");

    forceCfg = ...
        projectCfg.forceCapacity;

    requiredForceFields = [
        "enabled"
        "configFile"
        "applyMode"
    ];

    missingForceFields = ...
        requiredForceFields( ...
            ~isfield( ...
                forceCfg, ...
                cellstr(requiredForceFields)));

    assert(isempty(missingForceFields), ...
        "StrengthConfigContext:ForceCapacityFieldsMissing", ...
        "projectCfg.forceCapacity is missing required fields: %s", ...
        strjoin(missingForceFields, ", "));

    %% Validate active configuration

    assert(islogical(forceCfg.enabled) && ...
            isscalar(forceCfg.enabled), ...
        "StrengthConfigContext:InvalidEnabledFlag", ...
        "projectCfg.forceCapacity.enabled must be a logical scalar.");

    assert(forceCfg.enabled, ...
        "StrengthConfigContext:ForceCapacityDisabled", ...
        "A strength configuration context requires " + ...
        "projectCfg.forceCapacity.enabled=true.");

    configFile = ...
        string(forceCfg.configFile);

    assert(isscalar(configFile) && ...
            strlength(configFile) > 0, ...
        "StrengthConfigContext:ConfigFileMissing", ...
        "projectCfg.forceCapacity.configFile must be a nonempty path.");

    applyMode = ...
        lower(string(forceCfg.applyMode));

    assert(isscalar(applyMode) && ...
            strlength(applyMode) > 0, ...
        "StrengthConfigContext:InvalidApplyMode", ...
        "projectCfg.forceCapacity.applyMode must be a nonempty scalar.");

    assert(applyMode == "target", ...
        "StrengthConfigContext:NonTargetApplyMode", ...
        "Percentage-named strength configuration contexts require " + ...
        "projectCfg.forceCapacity.applyMode='target'. Scale mode does " + ...
        "not provide deterministic absolute strength identity.");

    %% Parse canonical configuration identity

    info = ...
        pipeline.parseStrengthConfigName( ...
            configFile);

    %% Resolve canonical configuration paths

    outputRoot = ...
        string(projectCfg.outputRoot);

    assert(isscalar(outputRoot) && ...
            strlength(outputRoot) > 0, ...
        "StrengthConfigContext:OutputRootMissing", ...
        "projectCfg.outputRoot must be a nonempty path.");

    collectionRoot = ...
        string(fullfile( ...
            outputRoot, ...
            "static_optimization_configs"));

    configRoot = ...
        string(fullfile( ...
            collectionRoot, ...
            info.ConfigId));

    paths = struct;

    paths.CollectionRoot = ...
        collectionRoot;

    paths.ConfigRoot = ...
        configRoot;

    paths.BatchQcDirectory = ...
        string(fullfile( ...
            configRoot, ...
            "batch_qc"));

    paths.AnalysisDirectory = ...
        string(fullfile( ...
            configRoot, ...
            "static_optimization_analysis"));

    %% Return configuration context

    inputs = struct;

    inputs.ConfigFile = ...
        info.ConfigFile;

    inputs.FileName = ...
        info.FileName;

    inputs.ApplyMode = ...
        applyMode;

    context = struct;

    context.SchemaVersion = 1;

    context.ConfigId = ...
        info.ConfigId;

    context.MusclePercent = ...
        info.MusclePercent;

    context.ActuatorPercent = ...
        info.ActuatorPercent;

    context.DisplayName = ...
        string(sprintf( ...
            "%d%% muscle, %d%% actuator", ...
            info.MusclePercent, ...
            info.ActuatorPercent));

    context.Inputs = ...
        inputs;

    context.Paths = ...
        paths;
end