function tests = test_static_optimization_shared_prep_refactor
%TEST_STATIC_OPTIMIZATION_SHARED_PREP_REFACTOR Contract tests for P3 cache.

    tests = ...
        functiontests(localfunctions);
end


function testSharedContextIsStrengthIndependent(testCase)

    cfg = ...
        localTestConfig();

    trial = ...
        pipeline.resolveTrialContext( ...
            cfg, ...
            cfg.conditions(1), ...
            cfg.trials(1));

    [sharedTrial, sharedCfg] = ...
        pipeline.resolveStaticOptimizationSharedTrialContext( ...
            cfg, ...
            trial.ConditionDeg, ...
            trial.TrialNumber);

    verifyFalse(testCase, ...
        sharedCfg.forceCapacity.enabled);

    verifyFalse(testCase, ...
        sharedTrial.StrengthConfigEnabled);

    verifyEqual(testCase, ...
        sharedTrial.Paths.ModelB.ModelBFile, ...
        trial.Paths.ModelB.ModelBFile);

    verifyEqual(testCase, ...
        sharedTrial.Paths.ModelB.FinalIkMotionFile, ...
        trial.Paths.ModelB.FinalIkMotionFile);

    verifyNotEqual(testCase, ...
        sharedTrial.Paths.StaticOptimizationPrep.Directory, ...
        trial.Paths.StaticOptimizationPrep.Directory);

    verifyTrue(testCase, ...
        contains( ...
            sharedTrial.Paths.StaticOptimizationPrep.Directory, ...
            "03_static_optimization_shared_prep"));

    verifyFalse(testCase, ...
        contains( ...
            sharedTrial.Paths.StaticOptimizationPrep.Directory, ...
            "static_optimization_configs"));
end


function testSharedContextRebasesAllHeavyArtifacts(testCase)

    cfg = ...
        localTestConfig();

    [sharedTrial, ~] = ...
        pipeline.resolveStaticOptimizationSharedTrialContext( ...
            cfg, ...
            cfg.conditions(1), ...
            cfg.trials(1));

    prep = ...
        sharedTrial.Paths.StaticOptimizationPrep;

    verifyTrue(testCase, ...
        contains( ...
            prep.ModelCFile, ...
            prep.Directory));

    verifyTrue(testCase, ...
        contains( ...
            prep.BodyKinematics.RawComCsv, ...
            prep.Directory));

    verifyTrue(testCase, ...
        contains( ...
            prep.BodyKinematics.ResampledComCsv, ...
            prep.Directory));

    verifyTrue(testCase, ...
        contains( ...
            prep.HeadSupportForce.MotionFile, ...
            prep.Directory));

    verifyTrue(testCase, ...
        contains( ...
            prep.HeadSupportForce.ExternalLoadsFile, ...
            prep.Directory));

    verifyTrue(testCase, ...
        contains( ...
            prep.CheckpointFile, ...
            prep.Directory));
end


function testSharedAndConfigurationWorkersAreResolvable(testCase)

    verifyNotEmpty(testCase, ...
        which( ...
            "pipeline.prepareStaticOptimizationSharedTrial"));

    verifyNotEmpty(testCase, ...
        which( ...
            "pipeline.prepareStaticOptimizationConfigurationTrial"));
end


function testSharedWorkerDelegatesEstablishedNumericalPath(testCase)

    source = ...
        localReadFunctionSource( ...
            "pipeline.prepareStaticOptimizationSharedTrial");

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "pipeline.prepareStaticOptimizationTrial"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            '"ExecuteBodyKinematics"'));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            '"ForceRebuild"'));
end


function testConfigurationWorkerUsesSharedArtifacts(testCase)

    source = ...
        localReadFunctionSource( ...
            "pipeline.prepareStaticOptimizationConfigurationTrial");

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "pipeline.prepareStaticOptimizationSharedTrial"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "copyfile"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "modelprep.applyConfiguredForceCapacitiesIfEnabled"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "sharedPaths.HeadSupportForce.ExternalLoadsFile"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "opensimrun.prepareStaticOptimizationSetup"));
end


function testConfigurationCheckpointIsCompactByContract(testCase)

    source = ...
        localReadFunctionSource( ...
            "pipeline.prepareStaticOptimizationConfigurationTrial");

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "SharedPreparationCheckpointFile"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "localCompactHsfValidation"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "localCompactExternalLoadsResult"));

    verifyFalse(testCase, ...
        contains( ...
            source, ...
            '"modelCCheckpoint"'));

    verifyFalse(testCase, ...
        contains( ...
            source, ...
            '"-v7.3"'));
end


function testCallableBatchRoutesFullStrengthPrepThroughCache(testCase)

    source = ...
        localReadFunctionSource( ...
            "pipeline.runStaticOptimizationPrepBatch");

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "pipeline.prepareStaticOptimizationConfigurationTrial"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "SharedPreparationReused"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "SharedPreparationCheckpointFile"));
end


function cfg = localTestConfig()

    cfg = ...
        localLoadConfig();

    cfg.rawDataRoot = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_raw_data"));

    cfg.outputRoot = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_outputs"));

    cfg.conditions = ...
        0;

    cfg.trials = ...
        1;

    cfg.forceCapacity.enabled = ...
        true;

    cfg.forceCapacity.applyMode = ...
        "target";

    cfg.forceCapacity.applyStages = ...
        "modelC";

    configDirectory = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_strength_configs"));

    cfg.forceCapacity.configFile = ...
        string(fullfile( ...
            configDirectory, ...
            "m25p_a25p.json"));
end


function cfg = localLoadConfig()

    repositoryRoot = ...
        string(fileparts(fileparts( ...
            mfilename("fullpath"))));

    addpath(repositoryRoot);

    cfg = ...
        load_project_config( ...
            "RequireLocalConfig", ...
                false, ...
            "ValidatePaths", ...
                false);
end


function source = localReadFunctionSource(functionName)

    functionFile = ...
        which(functionName);

    verifyFunctionFile = ...
        string(functionFile);

    assert(strlength(verifyFunctionFile) > 0, ...
        "SharedPrepRefactorTest:FunctionMissing", ...
        "Function was not found: %s", ...
        functionName);

    source = ...
        string(fileread(functionFile));
end
