function tests = test_strength_configuration_pareto
%TEST_STRENGTH_CONFIGURATION_PARETO Contract tests for Pareto classification.

    tests = ...
        functiontests(localfunctions);
end


function testIdentifiesNondominatedFeasibleConfigurations(testCase)

    T = ...
        localSummaryTable( ...
            [
                "m25p_a75p"
                "m50p_a50p"
                "m50p_a75p"
            ], ...
            [25; 50; 50], ...
            [75; 50; 75], ...
            [true; true; true], ...
            [true; true; true]);

    T = ...
        soopt.findParetoFrontier(T);

    verifyEqual(testCase, ...
        T.IsParetoEligible, ...
        [true; true; true]);

    verifyEqual(testCase, ...
        T.IsParetoOptimal, ...
        [true; true; false]);

    row = ...
        T.ConfigId == "m50p_a75p";

    verifyEqual(testCase, ...
        T.DominatedByCount(row), ...
        2);

    verifyEqual(testCase, ...
        T.DominatingConfigIds(row), ...
        "m25p_a75p;m50p_a50p");
end


function testInfeasibleConfigurationsDoNotDominate(testCase)

    T = ...
        localSummaryTable( ...
            [
                "m25p_a25p"
                "m50p_a50p"
            ], ...
            [25; 50], ...
            [25; 50], ...
            [true; true], ...
            [false; true]);

    T = ...
        soopt.findParetoFrontier(T);

    rowInfeasible = ...
        T.ConfigId == "m25p_a25p";

    rowFeasible = ...
        T.ConfigId == "m50p_a50p";

    verifyFalse(testCase, ...
        T.IsParetoEligible(rowInfeasible));

    verifyFalse(testCase, ...
        T.IsParetoOptimal(rowInfeasible));

    verifyTrue(testCase, ...
        T.IsParetoOptimal(rowFeasible));

    verifyEqual(testCase, ...
        T.DominatedByCount(rowFeasible), ...
        0);

    verifyEqual(testCase, ...
        T.DominatingConfigIds(rowFeasible), ...
        "");
end


function testIncompleteConfigurationsDoNotDominate(testCase)

    T = ...
        localSummaryTable( ...
            [
                "m25p_a25p"
                "m50p_a50p"
            ], ...
            [25; 50], ...
            [25; 50], ...
            [false; true], ...
            [false; true]);

    T = ...
        soopt.findParetoFrontier(T);

    rowIncomplete = ...
        T.ConfigId == "m25p_a25p";

    rowFeasible = ...
        T.ConfigId == "m50p_a50p";

    verifyFalse(testCase, ...
        T.IsParetoEligible(rowIncomplete));

    verifyFalse(testCase, ...
        T.IsParetoOptimal(rowIncomplete));

    verifyTrue(testCase, ...
        T.IsParetoOptimal(rowFeasible));
end


function testSingleEligibleConfigurationIsParetoOptimal(testCase)

    T = ...
        localSummaryTable( ...
            "m50p_a75p", ...
            50, ...
            75, ...
            true, ...
            true);

    T = ...
        soopt.findParetoFrontier(T);

    verifyTrue(testCase, ...
        T.IsParetoEligible);

    verifyTrue(testCase, ...
        T.IsParetoOptimal);

    verifyEqual(testCase, ...
        T.DominatedByCount, ...
        0);

    verifyEqual(testCase, ...
        T.DominatingConfigIds, ...
        "");
end


function testDominatingIdsAreDeterministicallySorted(testCase)

    T = ...
        localSummaryTable( ...
            [
                "m50p_a50p"
                "m25p_a75p"
                "m25p_a50p"
                "m75p_a75p"
            ], ...
            [50; 25; 25; 75], ...
            [50; 75; 50; 75], ...
            [true; true; true; true], ...
            [true; true; true; true]);

    T = ...
        soopt.findParetoFrontier(T);

    row = ...
        T.ConfigId == "m75p_a75p";

    verifyEqual(testCase, ...
        T.DominatedByCount(row), ...
        3);

    verifyEqual(testCase, ...
        T.DominatingConfigIds(row), ...
        "m25p_a50p;m25p_a75p;m50p_a50p");

    rowBest = ...
        T.ConfigId == "m25p_a50p";

    verifyTrue(testCase, ...
        T.IsParetoOptimal(rowBest));
end


function testEmptyTableIsSupported(testCase)

    T = ...
        localSummaryTable( ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            false(0,1), ...
            false(0,1));

    T = ...
        soopt.findParetoFrontier(T);

    verifyEqual(testCase, ...
        height(T), ...
        0);

    verifyTrue(testCase, ...
        all(ismember( ...
            { ...
                'IsParetoEligible', ...
                'IsParetoOptimal', ...
                'DominatedByCount', ...
                'DominatingConfigIds'}, ...
            T.Properties.VariableNames)));
end


function testDuplicateConfigIdRejected(testCase)

    T = ...
        localSummaryTable( ...
            [
                "m50p_a75p"
                "m50p_a75p"
            ], ...
            [50; 50], ...
            [75; 75], ...
            [true; true], ...
            [true; true]);

    verifyError(testCase, ...
        @() soopt.findParetoFrontier(T), ...
        "StrengthPareto:DuplicateConfigId");
end


function T = localSummaryTable( ...
        configId, musclePercent, actuatorPercent, ...
        assessmentComplete, isFeasible)

    ConfigId = ...
        string(configId(:));

    MusclePercent = ...
        double(musclePercent(:));

    ActuatorPercent = ...
        double(actuatorPercent(:));

    AssessmentComplete = ...
        logical(assessmentComplete(:));

    IsFeasible = ...
        logical(isFeasible(:));

    T = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            AssessmentComplete, ...
            IsFeasible);
end
