function tests = test_strength_proposed_config_resolution
%TEST_STRENGTH_PROPOSED_CONFIG_RESOLUTION Tests proposal-to-JSON mapping.

    tests = ...
        functiontests(localfunctions);
end


function testResolvesTopProposalToExactJson(testCase)

    [result, root, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    selection = ...
        soopt.resolveProposedStrengthConfig( ...
            result);

    verifyEqual(testCase, ...
        selection.SchemaVersion, ...
        1);

    verifyEqual(testCase, ...
        selection.PriorityRank, ...
        1);

    verifyEqual(testCase, ...
        selection.ConfigId, ...
        "m15p_a15p");

    verifyEqual(testCase, ...
        selection.MusclePercent, ...
        15);

    verifyEqual(testCase, ...
        selection.ActuatorPercent, ...
        15);

    verifyEqual(testCase, ...
        selection.FileName, ...
        "m15p_a15p.json");

    verifyTrue(testCase, ...
        isfile(selection.ConfigFile));

    verifyEqual(testCase, ...
        selection.ConfigFile, ...
        string(fullfile( ...
            root, ...
            "m15p_a15p.json")));

    verifyEqual(testCase, ...
        selection.Proposal.ConfigId, ...
        "m15p_a15p");

    verifyEqual(testCase, ...
        selection.PoolConfiguration.ConfigId, ...
        "m15p_a15p");
end


function testCanResolveNonTopRank(testCase)

    [result, root, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    selection = ...
        soopt.resolveProposedStrengthConfig( ...
            result, ...
            "ProposalRank", ...
            2);

    verifyEqual(testCase, ...
        selection.PriorityRank, ...
        2);

    verifyEqual(testCase, ...
        selection.ConfigId, ...
        "m20p_a10p");

    verifyEqual(testCase, ...
        selection.ConfigFile, ...
        string(fullfile( ...
            root, ...
            "m20p_a10p.json")));
end


function testPlanningUnavailableIsRejected(testCase)

    [result, ~, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    result.PlanningAvailable = ...
        false;

    result.PlanningStatus = ...
        "UNAVAILABLE_MONOTONICITY_VIOLATION";

    result.PlanningReason = ...
        "synthetic violation";

    verifyError(testCase, ...
        @() soopt.resolveProposedStrengthConfig(result), ...
        "StrengthProposalResolve:PlanningUnavailable");
end


function testEmptyProposalTableIsRejected(testCase)

    [result, ~, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    result.Proposals = ...
        result.Proposals([], :);

    verifyError(testCase, ...
        @() soopt.resolveProposedStrengthConfig(result), ...
        "StrengthProposalResolve:NoProposals");
end


function testUnavailableProposalRankIsRejected(testCase)

    [result, ~, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    verifyError(testCase, ...
        @() soopt.resolveProposedStrengthConfig( ...
            result, ...
            "ProposalRank", ...
            3), ...
        "StrengthProposalResolve:ProposalRankNotFound");
end


function testMissingPoolMappingIsRejected(testCase)

    [result, ~, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    result.ConfigPool.Configurations( ...
        result.ConfigPool.Configurations.ConfigId == ...
            "m15p_a15p", ...
        :) = [];

    verifyError(testCase, ...
        @() soopt.resolveProposedStrengthConfig(result), ...
        "StrengthProposalResolve:ConfigNotFound");
end


function testCoordinateMismatchIsRejected(testCase)

    [result, ~, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    row = ...
        result.ConfigPool.Configurations.ConfigId == ...
        "m15p_a15p";

    result.ConfigPool.Configurations.MusclePercent(row) = ...
        20;

    verifyError(testCase, ...
        @() soopt.resolveProposedStrengthConfig(result), ...
        "StrengthProposalResolve:CoordinateMismatch");
end


function testDuplicatePoolConfigIdIsRejected(testCase)

    [result, ~, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    row = ...
        result.ConfigPool.Configurations( ...
            result.ConfigPool.Configurations.ConfigId == ...
                "m15p_a15p", ...
            :);

    result.ConfigPool.Configurations = [
        result.ConfigPool.Configurations
        row
    ];

    verifyError(testCase, ...
        @() soopt.resolveProposedStrengthConfig(result), ...
        "StrengthProposalResolve:DuplicateConfigId");
end


function testDeletedJsonIsRejected(testCase)

    [result, root, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    delete( ...
        fullfile( ...
            root, ...
            "m15p_a15p.json"));

    verifyError(testCase, ...
        @() soopt.resolveProposedStrengthConfig(result), ...
        "StrengthProposalResolve:ConfigFileNotFound");
end


function [result, root, cleanup] = localCreateFixture()

    root = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_proposal_resolve_" + ...
            string(java.util.UUID.randomUUID())));

    mkdir(root);

    cleanup = ...
        onCleanup(@() localRemoveTree(root));

    configIds = [
        "m15p_a15p"
        "m20p_a10p"
        "m25p_a25p"
    ];

    musclePercent = ...
        [15; 20; 25];

    actuatorPercent = ...
        [15; 10; 25];

    fileName = ...
        configIds + ...
        ".json";

    configFile = ...
        strings(numel(configIds),1);

    for iConfig = 1:numel(configIds)

        configFile(iConfig) = ...
            string(fullfile( ...
                root, ...
                fileName(iConfig)));

        localWriteJson( ...
            configFile(iConfig));
    end

    configurations = ...
        table( ...
            configIds, ...
            musclePercent, ...
            actuatorPercent, ...
            fileName, ...
            configFile, ...
            'VariableNames', { ...
                'ConfigId', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'FileName', ...
                'ConfigFile'});

    PriorityRank = ...
        [1; 2];

    ConfigId = [
        "m15p_a15p"
        "m20p_a10p"
    ];

    MusclePercent = ...
        [15; 20];

    ActuatorPercent = ...
        [15; 10];

    ExistingIncomplete = ...
        [false; true];

    FeasibleOutcomeResolvedCount = ...
        [4; 3];

    InfeasibleOutcomeResolvedCount = ...
        [3; 4];

    WorstCaseResolvedCount = ...
        [3; 3];

    BestCaseResolvedCount = ...
        [4; 4];

    TotalResolutionPotential = ...
        [7; 7];

    ResolutionImbalance = ...
        [1; 1];

    GridCenterDistance = ...
        [0.1; 0.2];

    proposals = ...
        table( ...
            PriorityRank, ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            ExistingIncomplete, ...
            FeasibleOutcomeResolvedCount, ...
            InfeasibleOutcomeResolvedCount, ...
            WorstCaseResolvedCount, ...
            BestCaseResolvedCount, ...
            TotalResolutionPotential, ...
            ResolutionImbalance, ...
            GridCenterDistance);

    configPool = struct;

    configPool.SchemaVersion = ...
        1;

    configPool.ConfigDirectory = ...
        root;

    configPool.Configurations = ...
        configurations;

    result = struct;

    result.SchemaVersion = ...
        1;

    result.ConfigPool = ...
        configPool;

    result.Proposals = ...
        proposals;

    result.PlanningAvailable = ...
        true;

    result.PlanningStatus = ...
        "AVAILABLE";

    result.PlanningReason = ...
        "synthetic";
end


function localWriteJson(filePath)

    fid = ...
        fopen(filePath, "w");

    assert(fid >= 0, ...
        "StrengthProposalResolveTest:FileCreateFailed", ...
        "Could not create synthetic JSON:\n%s", ...
        filePath);

    cleanup = ...
        onCleanup(@() fclose(fid)); %#ok<NASGU>

    fprintf(fid, "{}\n");
end


function localRemoveTree(root)

    if isfolder(root)

        rmdir(root, "s");
    end
end
