function tests = test_static_optimization_retrospective_reaudit
%TEST_STATIC_OPTIMIZATION_RETROSPECTIVE_REAUDIT Tests saved-result re-audit.

    tests = ...
        functiontests(localfunctions);
end


function testReauditDemotesSaturatedLegacyTrial(testCase)

    [cfg, configRoot, cleanup] = ...
        localCreateProject(); %#ok<ASGLU>

    summary = ...
        localCreateLegacySummary( ...
            configRoot, ...
            "m25p_a50p", ...
            25, ...
            50, ...
            [0; 15], ...
            [1; 1], ...
            [0.50; 1.00]);

    localWriteLegacyBatchSummary( ...
        configRoot, ...
        summary);

    report = ...
        soopt.reauditStaticOptimizationConfigurations( ...
            cfg, ...
            "PrintProgress", ...
            false);

    verifyEqual(testCase, ...
        report.Status, ...
        "REAUDITED");

    verifyEqual(testCase, ...
        report.TrialsAudited, ...
        2);

    verifyEqual(testCase, ...
        report.TrialsSaturated, ...
        1);

    verifyEqual(testCase, ...
        report.TrialsDemoted, ...
        1);

    verifyEqual(testCase, ...
        report.TrialsSucceededAfterReaudit, ...
        1);

    verifyFalse(testCase, ...
        report.ConfigurationFeasible);

    updated = ...
        readtable( ...
            localSummaryCsv(configRoot), ...
            "TextType", ...
            "string");

    verifyEqual(testCase, ...
        logical(updated.Succeeded), ...
        [true; false]);

    verifyEqual(testCase, ...
        string(updated.Status), ...
        [ ...
            "completed"
            "activation_saturation"
        ]);

    verifyEqual(testCase, ...
        logical(updated.ActivationSaturationPassed), ...
        [true; false]);

    verifyEqual(testCase, ...
        updated.SaturatedChannelCount, ...
        [0; 1]);

    checkpointFile = ...
        string(updated.CheckpointFile(2));

    verifyTrue(testCase, ...
        ismissing(checkpointFile) || ...
        strlength(checkpointFile) == 0);

    auditCsv = ...
        string(updated.ActivationAuditCsv);

    verifyTrue(testCase, ...
        all(isfile(auditCsv)));

    verifyTrue(testCase, ...
        isfile(report.BackupCsv));

    verifyTrue(testCase, ...
        isfile(report.BackupMat));

    loaded = ...
        load( ...
            localSummaryMat(configRoot), ...
            "batchSummary");

    verifyFalse(testCase, ...
        loaded.batchSummary.Succeeded);

    verifyTrue(testCase, ...
        isfield( ...
            loaded.batchSummary, ...
            "ActivationSaturationReaudit"));

    reauditMetadata = ...
        loaded.batchSummary.ActivationSaturationReaudit;

    verifyEqual(testCase, ...
        reauditMetadata.SchemaVersion, ...
        2);

    verifyEqual(testCase, ...
        reauditMetadata.SaturationThreshold, ...
        0.999, ...
        "AbsTol", ...
        1e-12);

    verifyFalse(testCase, ...
        isfield(reauditMetadata, "SaturationLimit"));

    verifyFalse(testCase, ...
        isfield(reauditMetadata, "SaturationTolerance"));
end


function testDryRunDoesNotModifyFilesystem(testCase)

    [cfg, configRoot, cleanup] = ...
        localCreateProject(); %#ok<ASGLU>

    summary = ...
        localCreateLegacySummary( ...
            configRoot, ...
            "m25p_a50p", ...
            25, ...
            50, ...
            0, ...
            1, ...
            1.00);

    writetable( ...
        summary, ...
        localSummaryCsv(configRoot));

    originalText = ...
        string(fileread( ...
            localSummaryCsv(configRoot)));

    report = ...
        soopt.reauditStaticOptimizationConfigurations( ...
            cfg, ...
            "WriteChanges", ...
            false, ...
            "PrintProgress", ...
            false);

    verifyEqual(testCase, ...
        report.TrialsSaturated, ...
        1);

    verifyFalse(testCase, ...
        report.SummaryUpdated);

    verifyEqual(testCase, ...
        string(fileread( ...
            localSummaryCsv(configRoot))), ...
        originalText);

    auditCsv = ...
        string(fullfile( ...
            configRoot, ...
            "00deg", ...
            "trial01", ...
            "04_static_optimization", ...
            "qc", ...
            "static_optimization_activation_audit.csv"));

    verifyFalse(testCase, ...
        isfile(auditCsv));

    verifyEqual(testCase, ...
        report.BackupCsv, ...
        "");
end


function testMissingActivationFileConservativelyDemotesSuccess(testCase)

    [cfg, configRoot, cleanup] = ...
        localCreateProject(); %#ok<ASGLU>

    summary = ...
        localCreateLegacySummary( ...
            configRoot, ...
            "m25p_a50p", ...
            25, ...
            50, ...
            0, ...
            1, ...
            0.50);

    delete( ...
        summary.ActivationFile(1));

    writetable( ...
        summary, ...
        localSummaryCsv(configRoot));

    report = ...
        soopt.reauditStaticOptimizationConfigurations( ...
            cfg, ...
            "PrintProgress", ...
            false);

    updated = ...
        readtable( ...
            localSummaryCsv(configRoot), ...
            "TextType", ...
            "string");

    verifyEqual(testCase, ...
        report.TrialsAuditUnavailable, ...
        1);

    verifyEqual(testCase, ...
        report.TrialsDemoted, ...
        1);

    verifyFalse(testCase, ...
        logical(updated.Succeeded));

    verifyEqual(testCase, ...
        string(updated.Status), ...
        "failed");

    verifyEqual(testCase, ...
        string(updated.ErrorIdentifier), ...
        "PipelineSO:ActivationAuditUnavailable");
end


function testExistingFailureIsNeverPromoted(testCase)

    [cfg, configRoot, cleanup] = ...
        localCreateProject(); %#ok<ASGLU>

    summary = ...
        localCreateLegacySummary( ...
            configRoot, ...
            "m25p_a50p", ...
            25, ...
            50, ...
            0, ...
            1, ...
            0.50);

    summary.Succeeded(1) = ...
        false;

    summary.Status(1) = ...
        "failed";

    summary.ErrorIdentifier(1) = ...
        "Existing:Failure";

    writetable( ...
        summary, ...
        localSummaryCsv(configRoot));

    report = ...
        soopt.reauditStaticOptimizationConfigurations( ...
            cfg, ...
            "PrintProgress", ...
            false);

    updated = ...
        readtable( ...
            localSummaryCsv(configRoot), ...
            "TextType", ...
            "string");

    verifyTrue(testCase, ...
        logical(updated.ActivationSaturationPassed));

    verifyFalse(testCase, ...
        logical(updated.Succeeded));

    verifyEqual(testCase, ...
        string(updated.Status), ...
        "failed");

    verifyEqual(testCase, ...
        string(updated.ErrorIdentifier), ...
        "Existing:Failure");

    verifyEqual(testCase, ...
        report.TrialsDemoted, ...
        0);
end


function testConfigIdFilterLimitsReaudit(testCase)

    [cfg, configRoot1, cleanup] = ...
        localCreateProject(); %#ok<ASGLU>

    outputRoot = ...
        string(cfg.outputRoot);

    configRoot2 = ...
        string(fullfile( ...
            outputRoot, ...
            "static_optimization_configs", ...
            "m50p_a75p"));

    mkdir(fullfile(configRoot2, "batch_qc"));

    summary1 = ...
        localCreateLegacySummary( ...
            configRoot1, ...
            "m25p_a50p", ...
            25, ...
            50, ...
            0, ...
            1, ...
            0.50);

    summary2 = ...
        localCreateLegacySummary( ...
            configRoot2, ...
            "m50p_a75p", ...
            50, ...
            75, ...
            0, ...
            1, ...
            0.50);

    writetable(summary1, localSummaryCsv(configRoot1));
    writetable(summary2, localSummaryCsv(configRoot2));

    report = ...
        soopt.reauditStaticOptimizationConfigurations( ...
            cfg, ...
            "ConfigIds", ...
            "m50p_a75p", ...
            "PrintProgress", ...
            false);

    verifyEqual(testCase, ...
        height(report), ...
        1);

    verifyEqual(testCase, ...
        report.ConfigId, ...
        "m50p_a75p");

    untouched = ...
        readtable( ...
            localSummaryCsv(configRoot1), ...
            "TextType", ...
            "string");

    verifyFalse(testCase, ...
        ismember( ...
            "ActivationSaturationPassed", ...
            string(untouched.Properties.VariableNames)));
end


function [cfg, configRoot, cleanup] = localCreateProject()

    root = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_so_reaudit_" + ...
            string(java.util.UUID.randomUUID())));

    outputRoot = ...
        string(fullfile( ...
            root, ...
            "output"));

    configRoot = ...
        string(fullfile( ...
            outputRoot, ...
            "static_optimization_configs", ...
            "m25p_a50p"));

    mkdir(fullfile(configRoot, "batch_qc"));

    cleanup = ...
        onCleanup(@() localRemoveTree(root));

    cfg = struct;

    cfg.outputRoot = ...
        outputRoot;

    cfg.pipeline = struct;
    cfg.pipeline.staticOptimization = struct;

    cfg.pipeline.staticOptimization.activationSaturationThreshold = ...
        0.999;
end


function summary = localCreateLegacySummary( ...
        configRoot, ...
        configId, ...
        musclePercent, ...
        actuatorPercent, ...
        conditionDeg, ...
        trialNumber, ...
        peakActivation)

    conditionDeg = ...
        double(conditionDeg(:));

    trialNumber = ...
        double(trialNumber(:));

    peakActivation = ...
        double(peakActivation(:));

    nRows = ...
        numel(conditionDeg);

    TrialStem = strings(nRows,1);
    ResultsDirectory = strings(nRows,1);
    ActivationFile = strings(nRows,1);
    CheckpointFile = strings(nRows,1);

    for iRow = 1:nRows

        conditionTag = ...
            string(sprintf( ...
                "%02ddeg", ...
                round(conditionDeg(iRow))));

        trialTag = ...
            string(sprintf( ...
                "trial%02d", ...
                trialNumber(iRow)));

        TrialStem(iRow) = ...
            conditionTag + "_" + trialTag;

        soDirectory = ...
            string(fullfile( ...
                configRoot, ...
                conditionTag, ...
                trialTag, ...
                "04_static_optimization"));

        ResultsDirectory(iRow) = ...
            string(fullfile( ...
                soDirectory, ...
                "results"));

        qcDirectory = ...
            string(fullfile( ...
                soDirectory, ...
                "qc"));

        mkdir(ResultsDirectory(iRow));
        mkdir(qcDirectory);

        ActivationFile(iRow) = ...
            string(fullfile( ...
                ResultsDirectory(iRow), ...
                TrialStem(iRow) + ...
                "_StaticOptimization_activation.sto"));

        localWriteActivationSto( ...
            ActivationFile(iRow), ...
            peakActivation(iRow));

        CheckpointFile(iRow) = ...
            string(fullfile( ...
                qcDirectory, ...
                "static_optimization_run_checkpoint.mat"));

        checkpoint = struct; %#ok<NASGU>
        save( ...
            CheckpointFile(iRow), ...
            "checkpoint");
    end

    ConfigId = ...
        repmat(string(configId), nRows, 1);

    MusclePercent = ...
        repmat(double(musclePercent), nRows, 1);

    ActuatorPercent = ...
        repmat(double(actuatorPercent), nRows, 1);

    ConditionDeg = ...
        conditionDeg;

    TrialNumber = ...
        trialNumber;

    Status = ...
        repmat("completed", nRows, 1);

    Succeeded = ...
        true(nRows,1);

    DurationSeconds = ...
        ones(nRows,1);

    StaticOptimizationDurationSeconds = ...
        ones(nRows,1);

    Process3CheckpointFile = ...
        repmat("process3.mat", nRows, 1);

    StaticOptimizationSetupFile = ...
        repmat("setup.xml", nRows, 1);

    ForceFile = ...
        repmat("force.sto", nRows, 1);

    ForceRows = ...
        repmat(3, nRows, 1);

    ActivationRows = ...
        repmat(3, nRows, 1);

    OutputAuditPassed = ...
        true(nRows,1);

    ErrorIdentifier = ...
        strings(nRows,1);

    ErrorMessage = ...
        strings(nRows,1);

    summary = ...
        table( ...
            ConditionDeg, ...
            TrialNumber, ...
            TrialStem, ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            Status, ...
            Succeeded, ...
            DurationSeconds, ...
            StaticOptimizationDurationSeconds, ...
            Process3CheckpointFile, ...
            StaticOptimizationSetupFile, ...
            ResultsDirectory, ...
            ForceFile, ...
            ActivationFile, ...
            ForceRows, ...
            ActivationRows, ...
            OutputAuditPassed, ...
            CheckpointFile, ...
            ErrorIdentifier, ...
            ErrorMessage);
end


function localWriteActivationSto(filePath, peakActivation)

    data = [
        0.00  0.20
        0.01  peakActivation
        0.02  0.30
    ];

    labels = ...
        ["time" "muscle_1"];

    fid = ...
        fopen(filePath, "w");

    assert(fid >= 0, ...
        "RetrospectiveSOAuditTest:FileCreateFailed", ...
        "Could not create synthetic STO:\n%s", ...
        filePath);

    cleaner = ...
        onCleanup(@() fclose(fid)); %#ok<NASGU>

    fprintf(fid, "name test_activation\n");
    fprintf(fid, "nRows=%d\n", size(data,1));
    fprintf(fid, "nColumns=%d\n", size(data,2));
    fprintf(fid, "endheader\n");

    fprintf( ...
        fid, ...
        "%s\n", ...
        strjoin( ...
            string(labels(:)).', ...
            sprintf('\t')));

    format = ...
        strjoin( ...
            repmat("%.12g", 1, size(data,2)), ...
            "\t") + ...
        "\n";

    for iRow = 1:size(data,1)

        fprintf( ...
            fid, ...
            format, ...
            data(iRow,:));
    end
end


function localWriteLegacyBatchSummary(configRoot, summary)

    writetable( ...
        summary, ...
        localSummaryCsv(configRoot));

    batchSummary = struct;
    batchSummary.SchemaVersion = 2;
    batchSummary.Process = 4;
    batchSummary.Stage = "static_optimization";
    batchSummary.StrengthConfigEnabled = true;
    batchSummary.ConfigId = "m25p_a50p";
    batchSummary.MusclePercent = 25;
    batchSummary.ActuatorPercent = 50;
    batchSummary.CompletedAt = "legacy";
    batchSummary.DurationSeconds = 10;
    batchSummary.Configuration = struct;
    batchSummary.SummaryTable = summary;
    batchSummary.Succeeded = true;

    save( ...
        localSummaryMat(configRoot), ...
        "batchSummary");
end


function filePath = localSummaryCsv(configRoot)

    filePath = ...
        string(fullfile( ...
            configRoot, ...
            "batch_qc", ...
            "process_4_static_optimization_summary.csv"));
end


function filePath = localSummaryMat(configRoot)

    filePath = ...
        string(fullfile( ...
            configRoot, ...
            "batch_qc", ...
            "process_4_static_optimization_summary.mat"));
end


function localRemoveTree(root)

    if isfolder(root)
        rmdir(root, "s");
    end
end
