function tests = test_callable_static_optimization_batches
%TEST_CALLABLE_STATIC_OPTIMIZATION_BATCHES Refactor contract tests.
%
% These tests verify the callable Process-3/4 batch architecture without
% executing OpenSim.

    tests = ...
        functiontests(localfunctions);
end


function testCallableBatchFunctionsAreResolvable(testCase)

    verifyNotEmpty(testCase, ...
        which("pipeline.runStaticOptimizationPrepBatch"));

    verifyNotEmpty(testCase, ...
        which("pipeline.runStaticOptimizationBatch"));
end


function testProcess3CallableUsesCanonicalTrialWorker(testCase)

    source = ...
        localReadFunctionSource( ...
            "pipeline.runStaticOptimizationPrepBatch");

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "pipeline.prepareStaticOptimizationTrial"));

    verifyFalse(testCase, ...
        contains( ...
            source, ...
            "load_project_config("));
end


function testProcess4CallableUsesCanonicalTrialWorker(testCase)

    source = ...
        localReadFunctionSource( ...
            "pipeline.runStaticOptimizationBatch");

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "pipeline.runStaticOptimizationTrial"));

    verifyFalse(testCase, ...
        contains( ...
            source, ...
            "load_project_config("));
end


function testProcess3ScriptIsThinWrapper(testCase)

    cfg = ...
        localLoadConfig();

    scriptFile = ...
        string(fullfile( ...
            cfg.batchDirectory, ...
            "batch_run_process_3.m"));

    source = ...
        string(fileread(scriptFile));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "load_project_config()"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "pipeline.runStaticOptimizationPrepBatch"));

    verifyFalse(testCase, ...
        contains( ...
            source, ...
            "localRunProcess3Job"));

    verifyFalse(testCase, ...
        contains( ...
            source, ...
            "pipeline.prepareStaticOptimizationTrial"));
end


function testProcess4ScriptIsThinWrapper(testCase)

    cfg = ...
        localLoadConfig();

    scriptFile = ...
        string(fullfile( ...
            cfg.batchDirectory, ...
            "batch_run_process_4.m"));

    source = ...
        string(fileread(scriptFile));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "load_project_config()"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "pipeline.runStaticOptimizationBatch"));

    verifyFalse(testCase, ...
        contains( ...
            source, ...
            "localRunProcess4Job"));

    verifyFalse(testCase, ...
        contains( ...
            source, ...
            "pipeline.runStaticOptimizationTrial"));
end


function testCallableFunctionsExposeAutomationOverrides(testCase)

    process3Source = ...
        localReadFunctionSource( ...
            "pipeline.runStaticOptimizationPrepBatch");

    process4Source = ...
        localReadFunctionSource( ...
            "pipeline.runStaticOptimizationBatch");

    sharedOptions = [
        "Conditions"
        "Trials"
        "Overwrite"
        "EnableParallel"
        "MaxWorkers"
        "ContinueOnError"
        "PoolProfile"
        "ClosePoolWhenFinished"
        "WriteSummary"
        "PrintProgress"
    ];

    for option = sharedOptions.'

        quotedOption = ...
            """" + option + """";

        verifyTrue(testCase, ...
            contains( ...
                process3Source, ...
                quotedOption));

        verifyTrue(testCase, ...
            contains( ...
                process4Source, ...
                quotedOption));
    end

    verifyTrue(testCase, ...
        contains( ...
            process3Source, ...
            '"ExecuteBodyKinematics"'));

    verifyTrue(testCase, ...
        contains( ...
            process4Source, ...
            '"ExecuteStaticOptimization"'));
end


function source = localReadFunctionSource(functionName)

    filePath = ...
        string(which(functionName));

    verifyFile = ...
        isfile(filePath);

    assert(verifyFile, ...
        "CallableBatchTest:FunctionNotFound", ...
        "Could not resolve function source for %s.", ...
        functionName);

    source = ...
        string(fileread(filePath));
end


function cfg = localLoadConfig()

    repositoryRoot = ...
        string(fileparts(fileparts( ...
            mfilename("fullpath"))));

    addpath(repositoryRoot);

    cfg = ...
        load_project_config( ...
            "RequireLocalConfig", false, ...
            "ValidatePaths", false);
end
