function tests = test_project_config_contract
%TEST_PROJECT_CONFIG_CONTRACT Validate the canonical configuration schema.

    tests = functiontests(localfunctions);
end


function testDefaultStudyDesign(testCase)

    cfg = localLoadWithoutLocal();

    verifyEqual(testCase, ...
        cfg.configSchemaVersion, ...
        4);

    verifyEqual(testCase, ...
        cfg.conditions, ...
        [0 15 30 45]);

    verifyEqual(testCase, ...
        cfg.trials, ...
        1:5);
end


function testCanonicalBatchNamespace(testCase)

    cfg = localLoadWithoutLocal();

    verifyTrue(testCase, ...
        isfield(cfg, "batchProcessing"));

    verifyTrue(testCase, ...
        isfield(cfg.batchProcessing, "enableParallel"));

    verifyTrue(testCase, ...
        isfield(cfg.batchProcessing, "maxWorkers"));

    verifyFalse(testCase, ...
        isfield(cfg, "enableParallel"));

    verifyFalse(testCase, ...
        isfield(cfg, "maxWorkers"));
end


function testStagePolicyExists(testCase)

    cfg = localLoadWithoutLocal();

    verifyEqual(testCase, ...
        cfg.pipeline.initializationIk.timeRangeSec, ...
        [0.00 19.99]);

    verifyEqual(testCase, ...
        cfg.pipeline.modelB.lockWindowSec, ...
        [0.10 0.15]);

    verifyEqual(testCase, ...
        cfg.pipeline.staticOptimizationPrep. ...
        bodyKinematicsLowpassCutoffHz, ...
        -1);

    verifyEqual(testCase, ...
        cfg.pipeline.staticOptimization.activationSaturationThreshold, ...
        0.999);

    verifyFalse(testCase, ...
        isfield( ...
            cfg.pipeline.staticOptimization, ...
            "activationSaturationLimit"));

    verifyFalse(testCase, ...
        isfield( ...
            cfg.pipeline.staticOptimization, ...
            "activationSaturationTolerance"));
end


function testAnalysisPolicyExists(testCase)

    cfg = localLoadWithoutLocal();

    analysisCfg = ...
        cfg.analysis.staticOptimization;

    verifyEqual(testCase, ...
        analysisCfg.normalizedBreaksPercent, ...
        [0 20 80 100]);

    verifyEqual(testCase, ...
        analysisCfg.pointsPerPhase, ...
        [200 600 200]);

    verifyEqual(testCase, ...
        analysisCfg.statisticsWindowPercent, ...
        [20 80]);

    verifyEqual(testCase, ...
        analysisCfg.expectedFlexorCount, ...
        16);

    verifyEqual(testCase, ...
        analysisCfg.expectedExtensorCount, ...
        36);

    verifyEqual(testCase, ...
        analysisCfg.motionOutputWindowPercent, ...
        [0 100]);

    verifyEqual(testCase, ...
        analysisCfg.extensorLandmarkPercent, ...
        50);
end


function testHsfPolicyExists(testCase)

    cfg = localLoadWithoutLocal();

    verifyTrue(testCase, ...
        cfg.hsf.useModelBodyMass);

    verifyEqual(testCase, ...
        cfg.hsf.Parameters.BodyName, ...
        "skull");

    verifyEqual(testCase, ...
        cfg.hsf.Parameters.TargetRateHz, ...
        1000);

    verifyEqual(testCase, ...
        cfg.hsf.Parameters.RampDuration, ...
        0.10);
end


function cfg = localLoadWithoutLocal()

    projectRoot = ...
        string(fileparts(fileparts(mfilename("fullpath"))));

    defaultsFile = ...
        string(fullfile( ...
            projectRoot, ...
            "config", ...
            "project_defaults.m"));

    cfg = struct;

    run(defaultsFile);
end
