function tests = test_static_optimization_artifact_pruning
%TEST_STATIC_OPTIMIZATION_ARTIFACT_PRUNING Tests explicit SO pruning.

    tests = functiontests(localfunctions);
end


function testDryRunDoesNotDeleteFiles(testCase)

    [cfg, root, cleanup] = localFixture(); %#ok<ASGLU>
    localPopulate(root, "m25p_a25p");

    cfg.storage.staticOptimization.keepControlsXml = false;

    result = pipeline.pruneStaticOptimizationArtifacts( ...
        cfg, ...
        "DryRun", true, ...
        "PrintProgress", false);

    verifyGreaterThan(testCase, result.DeleteCandidateCount, 0);
    verifyEqual(testCase, result.DeletedFileCount, 0);

    controls = fullfile( ...
        root, "static_optimization_configs", "m25p_a25p", ...
        "00deg", "trial01", "04_static_optimization", "results", ...
        "SO_00deg_trial01_StaticOptimization_controls.xml");

    verifyTrue(testCase, isfile(controls));
end


function testApplyHonorsIndependentPolicies(testCase)

    [cfg, root, cleanup] = localFixture(); %#ok<ASGLU>
    localPopulate(root, "m25p_a25p");

    cfg.storage.staticOptimization.keepControlsXml = false;
    cfg.storage.staticOptimization.keepSetupXml = false;
    cfg.storage.staticOptimization.keepForceSto = true;
    cfg.storage.staticOptimization.keepActivationSto = true;

    cfg.storage.staticOptimizationPrep.keepConfiguredModelC = false;

    cfg.storage.sharedStaticOptimizationPrep.keepNeutralModelC = false;
    cfg.storage.sharedStaticOptimizationPrep.keepBodyKinematics = false;
    cfg.storage.sharedStaticOptimizationPrep.keepComCsv = true;

    result = pipeline.pruneStaticOptimizationArtifacts( ...
        cfg, ...
        "DryRun", false, ...
        "PrintProgress", false);

    verifyEqual(testCase, result.DeleteFailureCount, 0);

    configRoot = fullfile( ...
        root, "static_optimization_configs", "m25p_a25p", ...
        "00deg", "trial01");

    verifyFalse(testCase, isfile(fullfile( ...
        configRoot, "03_static_optimization_prep", ...
        "00deg_trial01_modelC_static_optimization.osim")));

    verifyFalse(testCase, isfile(fullfile( ...
        configRoot, "04_static_optimization", ...
        "00deg_trial01_so_setup.xml")));

    verifyFalse(testCase, isfile(fullfile( ...
        configRoot, "04_static_optimization", "results", ...
        "SO_00deg_trial01_StaticOptimization_controls.xml")));

    verifyTrue(testCase, isfile(fullfile( ...
        configRoot, "04_static_optimization", "results", ...
        "SO_00deg_trial01_StaticOptimization_force.sto")));

    verifyTrue(testCase, isfile(fullfile( ...
        configRoot, "04_static_optimization", "results", ...
        "SO_00deg_trial01_StaticOptimization_activation.sto")));

    sharedRoot = fullfile( ...
        root, "00deg", "trial01", ...
        "03_static_optimization_shared_prep");

    verifyFalse(testCase, isfile(fullfile( ...
        sharedRoot, ...
        "00deg_trial01_modelC_static_optimization.osim")));

    verifyFalse(testCase, isfile(fullfile( ...
        sharedRoot, "body_kinematics", ...
        "00deg_trial01_body_kinematics_setup.xml")));

    verifyFalse(testCase, isfile(fullfile( ...
        sharedRoot, "body_kinematics", "results", ...
        "BodyKinematics_pos_global.sto")));

    verifyTrue(testCase, isfile(fullfile( ...
        sharedRoot, "body_kinematics", "qc", ...
        "skull_com_resampled.csv")));
end


function testQcCheckpointAndEventPoliciesAreIndependent(testCase)

    [cfg, root, cleanup] = localFixture(); %#ok<ASGLU>
    localPopulate(root, "m25p_a25p");

    cfg.storage.staticOptimization.keepQc = false;
    cfg.storage.staticOptimization.keepCheckpoint = true;

    cfg.storage.staticOptimizationPrep.keepQc = false;
    cfg.storage.staticOptimizationPrep.keepCheckpoint = true;

    cfg.storage.sharedStaticOptimizationPrep.keepQc = false;
    cfg.storage.sharedStaticOptimizationPrep.keepCheckpoint = true;
    cfg.storage.sharedStaticOptimizationPrep.keepComCsv = true;
    cfg.storage.sharedStaticOptimizationPrep.keepEventTiming = true;

    pipeline.pruneStaticOptimizationArtifacts( ...
        cfg, ...
        "DryRun", false, ...
        "PrintProgress", false);

    configRoot = fullfile( ...
        root, "static_optimization_configs", "m25p_a25p", ...
        "00deg", "trial01");

    verifyTrue(testCase, isfile(fullfile( ...
        configRoot, "03_static_optimization_prep", "qc", ...
        "model_c_checkpoint.mat")));

    verifyFalse(testCase, isfile(fullfile( ...
        configRoot, "03_static_optimization_prep", "qc", ...
        "modelC_force_capacity_config_audit.csv")));

    verifyTrue(testCase, isfile(fullfile( ...
        configRoot, "04_static_optimization", "qc", ...
        "static_optimization_run_checkpoint.mat")));

    verifyFalse(testCase, isfile(fullfile( ...
        configRoot, "04_static_optimization", "qc", ...
        "static_optimization_output_audit.csv")));

    sharedRoot = fullfile( ...
        root, "00deg", "trial01", ...
        "03_static_optimization_shared_prep");

    verifyTrue(testCase, isfile(fullfile( ...
        sharedRoot, "qc", "model_c_checkpoint.mat")));

    verifyTrue(testCase, isfile(fullfile( ...
        sharedRoot, "body_kinematics", "qc", ...
        "skull_com_raw.csv")));

    verifyTrue(testCase, isfile(fullfile( ...
        sharedRoot, "head_support_force", "qc", ...
        "contact_event_detection_summary.csv")));

    verifyFalse(testCase, isfile(fullfile( ...
        sharedRoot, "head_support_force", "qc", ...
        "hsf_summary.csv")));
end


function testUnknownFileIsRetained(testCase)

    [cfg, root, cleanup] = localFixture(); %#ok<ASGLU>
    localPopulate(root, "m25p_a25p");

    unknown = fullfile( ...
        root, "static_optimization_configs", "m25p_a25p", ...
        "00deg", "trial01", "04_static_optimization", "results", ...
        "future_diagnostic.dat");

    localTouch(unknown, 64);

    cfg.storage.staticOptimization.keepForceSto = false;

    result = pipeline.pruneStaticOptimizationArtifacts( ...
        cfg, ...
        "DryRun", false, ...
        "PrintProgress", false);

    verifyTrue(testCase, isfile(unknown));
    verifyTrue(testCase, ...
        any(result.UnmanagedFiles.File == string(unknown)));
end


function testConfigSelectionLimitsApply(testCase)

    [cfg, root, cleanup] = localFixture(); %#ok<ASGLU>
    localPopulate(root, "m25p_a25p");
    localPopulate(root, "m50p_a50p");

    cfg.storage.staticOptimization.keepForceSto = false;

    pipeline.pruneStaticOptimizationArtifacts( ...
        cfg, ...
        "DryRun", false, ...
        "IncludeShared", false, ...
        "ConfigIds", "m25p_a25p", ...
        "PrintProgress", false);

    fileA = fullfile( ...
        root, "static_optimization_configs", "m25p_a25p", ...
        "00deg", "trial01", "04_static_optimization", "results", ...
        "SO_00deg_trial01_StaticOptimization_force.sto");

    fileB = fullfile( ...
        root, "static_optimization_configs", "m50p_a50p", ...
        "00deg", "trial01", "04_static_optimization", "results", ...
        "SO_00deg_trial01_StaticOptimization_force.sto");

    verifyFalse(testCase, isfile(fileA));
    verifyTrue(testCase, isfile(fileB));
end


function [cfg, root, cleanup] = localFixture()

    root = string(fullfile( ...
        tempdir, ...
        "headneck_so_prune_" + string(java.util.UUID.randomUUID())));

    mkdir(root);
    cleanup = onCleanup(@() localRemoveTree(root));

    cfg = struct;
    cfg.outputRoot = root;
    cfg.conditions = 0;
    cfg.trials = 1;

    cfg.storage = struct;

    cfg.storage.staticOptimizationPrep = struct( ...
        "keepConfiguredModelC", true, ...
        "keepQc", true, ...
        "keepCheckpoint", true);

    cfg.storage.staticOptimization = struct( ...
        "keepControlsXml", true, ...
        "keepSetupXml", true, ...
        "keepForceSto", true, ...
        "keepActivationSto", true, ...
        "keepQc", true, ...
        "keepCheckpoint", true);

    cfg.storage.sharedStaticOptimizationPrep = struct( ...
        "keepNeutralModelC", true, ...
        "keepBodyKinematics", true, ...
        "keepComCsv", true, ...
        "keepEventTiming", true, ...
        "keepHsfMotion", true, ...
        "keepExternalLoadsXml", true, ...
        "keepQc", true, ...
        "keepCheckpoint", true);
end


function localPopulate(root, configId)

    shared = fullfile( ...
        root, "00deg", "trial01", ...
        "03_static_optimization_shared_prep");

    localTouch(fullfile(shared, ...
        "00deg_trial01_modelC_static_optimization.osim"), 128);
    localTouch(fullfile(shared, "qc", ...
        "model_c_checkpoint.mat"), 64);
    localTouch(fullfile(shared, "qc", ...
        "modelC_coordinate_configuration.csv"), 64);

    localTouch(fullfile(shared, "body_kinematics", ...
        "00deg_trial01_body_kinematics_setup.xml"), 64);
    localTouch(fullfile(shared, "body_kinematics", "results", ...
        "BodyKinematics_pos_global.sto"), 512);
    localTouch(fullfile(shared, "body_kinematics", "qc", ...
        "skull_com_raw.csv"), 64);
    localTouch(fullfile(shared, "body_kinematics", "qc", ...
        "skull_com_resampled.csv"), 64);
    localTouch(fullfile(shared, "body_kinematics", "qc", ...
        "skull_com_summary.csv"), 64);

    localTouch(fullfile(shared, "head_support_force", ...
        "00deg_trial01_head_support_force.mot"), 512);
    localTouch(fullfile(shared, "head_support_force", ...
        "00deg_trial01_external_loads.xml"), 64);
    localTouch(fullfile(shared, "head_support_force", "qc", ...
        "contact_event_detection_summary.csv"), 64);
    localTouch(fullfile(shared, "head_support_force", "qc", ...
        "hsf_summary.csv"), 64);

    config = fullfile( ...
        root, "static_optimization_configs", configId, ...
        "00deg", "trial01");

    localTouch(fullfile(config, "03_static_optimization_prep", ...
        "00deg_trial01_modelC_static_optimization.osim"), 128);
    localTouch(fullfile(config, "03_static_optimization_prep", "qc", ...
        "model_c_checkpoint.mat"), 64);
    localTouch(fullfile(config, "03_static_optimization_prep", "qc", ...
        "modelC_force_capacity_config_audit.csv"), 64);

    localTouch(fullfile(config, "04_static_optimization", ...
        "00deg_trial01_so_setup.xml"), 64);
    localTouch(fullfile(config, "04_static_optimization", "results", ...
        "SO_00deg_trial01_StaticOptimization_force.sto"), 512);
    localTouch(fullfile(config, "04_static_optimization", "results", ...
        "SO_00deg_trial01_StaticOptimization_activation.sto"), 512);
    localTouch(fullfile(config, "04_static_optimization", "results", ...
        "SO_00deg_trial01_StaticOptimization_controls.xml"), 1024);

    localTouch(fullfile(config, "04_static_optimization", "qc", ...
        "static_optimization_run_checkpoint.mat"), 64);
    localTouch(fullfile(config, "04_static_optimization", "qc", ...
        "static_optimization_output_audit.csv"), 64);
    localTouch(fullfile(config, "04_static_optimization", "qc", ...
        "static_optimization_activation_audit.csv"), 64);
end


function localTouch(filePath, nBytes)

    parent = fileparts(filePath);

    if ~isfolder(parent)
        mkdir(parent);
    end

    fid = fopen(filePath, "w");

    assert(fid >= 0, ...
        "SOPruneTest:FileCreateFailed", ...
        "Could not create test file:\n%s", ...
        string(filePath));

    cleanup = onCleanup(@() fclose(fid));
    fwrite(fid, zeros(nBytes,1,"uint8"), "uint8");
end


function localRemoveTree(root)

    if isfolder(root)
        rmdir(root, "s");
    end
end
