function tests = test_static_optimization_prep_pipeline_contract
%TEST_STATIC_OPTIMIZATION_PREP_PIPELINE_CONTRACT Process-3 contract tests.
%
% These tests verify configuration, resolved paths, dependencies, and
% worker availability without executing OpenSim.

    tests = functiontests(localfunctions);
end


function testStaticOptimizationPrepConfigExists(testCase)

    cfg = ...
        localLoadConfig();

    verifyTrue(testCase, ...
        isfield( ...
            cfg.pipeline, ...
            "staticOptimizationPrep"));

    prepCfg = ...
        cfg.pipeline.staticOptimizationPrep;

    verifyTrue(testCase, ...
        isfield( ...
            prepCfg, ...
            "bodyKinematicsLowpassCutoffHz"));

    verifyTrue(testCase, ...
        isfield( ...
            prepCfg, ...
            "timeRangeSec"));

    verifyEqual(testCase, ...
        prepCfg.bodyKinematicsLowpassCutoffHz, ...
        -1);
end


function testHsfProjectPolicyExists(testCase)

    cfg = ...
        localLoadConfig();

    verifyTrue(testCase, ...
        isfield(cfg, "hsf"));

    verifyTrue(testCase, ...
        isfield( ...
            cfg.hsf, ...
            "useModelBodyMass"));

    verifyTrue(testCase, ...
        isfield( ...
            cfg.hsf, ...
            "Parameters"));

    requiredFields = [
        "BodyName"
        "SkullMassKg"
        "GravityY"
        "TargetRateHz"
        "RampDuration"
        "RampShape"
        "RadialSign"
        "AzimuthConvention"
        "InterpolationMethod"
        "ForcePrefix"
        "PointPrefix"
    ];

    verifyTrue(testCase, ...
        all(isfield( ...
            cfg.hsf.Parameters, ...
            cellstr(requiredFields))));
end


function testResolvedContextContainsProcess3Dependencies(testCase)

    cfg = ...
        localTestConfig();

    trial = ...
        pipeline.resolveTrialContext( ...
            cfg, ...
            cfg.conditions(1), ...
            cfg.trials(1));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.ModelB, ...
            "CheckpointFile"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.ModelB, ...
            "ModelBFile"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.ModelB, ...
            "FinalIkMotionFile"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Inputs, ...
            "ExternalLoadsTemplate"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Inputs, ...
            "StaticOptimizationTemplate"));
end


function testResolvedContextContainsProcess3Outputs(testCase)

    cfg = ...
        localTestConfig();

    trial = ...
        pipeline.resolveTrialContext( ...
            cfg, ...
            cfg.conditions(1), ...
            cfg.trials(1));

    prepPaths = ...
        trial.Paths.StaticOptimizationPrep;

    verifyTrue(testCase, ...
        isfield( ...
            prepPaths, ...
            "ModelCFile"));

    verifyTrue(testCase, ...
        isfield( ...
            prepPaths, ...
            "ForceConfigAuditCsv"));

    verifyTrue(testCase, ...
        isfield( ...
            prepPaths, ...
            "BodyKinematics"));

    verifyTrue(testCase, ...
        isfield( ...
            prepPaths, ...
            "HeadSupportForce"));

    verifyTrue(testCase, ...
        isfield( ...
            prepPaths, ...
            "CheckpointFile"));
end


function testResolvedContextContainsProcess4SetupOutput(testCase)

    cfg = ...
        localTestConfig();

    trial = ...
        pipeline.resolveTrialContext( ...
            cfg, ...
            cfg.conditions(1), ...
            cfg.trials(1));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.StaticOptimization, ...
            "SetupFile"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.StaticOptimization, ...
            "ResultsDirectory"));
end


function testSharedWorkerIsResolvable(testCase)

    workerFile = ...
        which( ...
            "pipeline.prepareStaticOptimizationTrial");

    verifyNotEmpty(testCase, ...
        workerFile);
end


function cfg = localTestConfig()

    cfg = ...
        localLoadConfig();

    cfg.rawDataRoot = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_raw_data"));

    cfg.outputRoot = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_outputs"));
end


function cfg = localLoadConfig()

    repositoryRoot = ...
        string(fileparts(fileparts( ...
            mfilename("fullpath"))));

    addpath(repositoryRoot);

    cfg = ...
        load_project_config( ...
            "LocalConfigPolicy", "disabled", ...
            "ValidatePaths", false);
end
