function tests = test_resolve_trial_context
%TEST_RESOLVE_TRIAL_CONTEXT Contract tests for canonical trial resolution.

    tests = functiontests(localfunctions);
end


function testCanonicalIdentity(testCase)

    cfg = localTestConfig();

    trial = pipeline.resolveTrialContext( ...
        cfg, 45, 1);

    verifyEqual(testCase, ...
        trial.SchemaVersion, ...
        2);

    verifyEqual(testCase, ...
        trial.ConditionDeg, ...
        45);

    verifyEqual(testCase, ...
        trial.TrialNumber, ...
        1);

    verifyEqual(testCase, ...
        trial.ConditionTag, ...
        "45deg");

    verifyEqual(testCase, ...
        trial.TrialTag, ...
        "trial01");

    verifyEqual(testCase, ...
        trial.TrialStem, ...
        "45deg_trial01");

    verifyEqual(testCase, ...
        trial.DisplayName, ...
        "45 deg, trial 1");
end


function testMarkerFileNaming(testCase)

    cfg = localTestConfig();

    trial0 = pipeline.resolveTrialContext( ...
        cfg, 0, 1);

    verifyEqual(testCase, ...
        trial0.Inputs.MarkerFile, ...
        string(fullfile( ...
            cfg.rawDataRoot, ...
            "0DEG0001.trc")));

    trial45 = pipeline.resolveTrialContext( ...
        cfg, 45, 5);

    verifyEqual(testCase, ...
        trial45.Inputs.MarkerFile, ...
        string(fullfile( ...
            cfg.rawDataRoot, ...
            "45DEG0005.trc")));
end


function testMarkerOverride(testCase)

    cfg = localTestConfig();

    explicitMarker = string(fullfile( ...
        tempdir, ...
        "special_trial.trc"));

    trial = pipeline.resolveTrialContext( ...
        cfg, 15, 2, ...
        "MarkerFile", explicitMarker);

    verifyEqual(testCase, ...
        trial.Inputs.MarkerFile, ...
        explicitMarker);
end


function testInitializationPathsMatchExistingConvention(testCase)

    cfg = localTestConfig();

    trial = pipeline.resolveTrialContext( ...
        cfg, 0, 1);

    expectedDirectory = string(fullfile( ...
        cfg.outputRoot, ...
        "00deg", ...
        "trial01", ...
        "01_initialization_ik"));

    verifyEqual(testCase, ...
        trial.Paths.Initialization.Directory, ...
        expectedDirectory);

    verifyEqual(testCase, ...
        trial.Paths.Initialization.ModelAFile, ...
        string(fullfile( ...
            expectedDirectory, ...
            "00deg_trial01_modelA_initialization.osim")));

    verifyEqual(testCase, ...
        trial.Paths.Initialization.IkMotionFile, ...
        string(fullfile( ...
            expectedDirectory, ...
            "00deg_trial01_initialization_ik.mot")));

    verifyEqual(testCase, ...
        trial.Paths.Initialization.CheckpointFile, ...
        string(fullfile( ...
            expectedDirectory, ...
            "qc", ...
            "initialization_ik_checkpoint.mat")));
end


function testModelBPathsMatchExistingConvention(testCase)

    cfg = localTestConfig();

    trial = pipeline.resolveTrialContext( ...
        cfg, 30, 4);

    expectedDirectory = string(fullfile( ...
        cfg.outputRoot, ...
        "30deg", ...
        "trial04", ...
        "02_locked_final_ik"));

    verifyEqual(testCase, ...
        trial.Paths.ModelB.Directory, ...
        expectedDirectory);

    verifyEqual(testCase, ...
        trial.Paths.ModelB.ModelBFile, ...
        string(fullfile( ...
            expectedDirectory, ...
            "30deg_trial04_modelB_locked_ik.osim")));

    verifyEqual(testCase, ...
        trial.Paths.ModelB.FinalIkMotionFile, ...
        string(fullfile( ...
            expectedDirectory, ...
            "30deg_trial04_final_ik.mot")));

    verifyEqual(testCase, ...
        trial.Paths.ModelB.CheckpointFile, ...
        string(fullfile( ...
            expectedDirectory, ...
            "qc", ...
            "model_b_final_ik_checkpoint.mat")));
end


function testStaticOptimizationPrepPathsMatchExistingConvention(testCase)

    cfg = localTestConfig();

    trial = pipeline.resolveTrialContext( ...
        cfg, 15, 3);

    prepDirectory = string(fullfile( ...
        cfg.outputRoot, ...
        "15deg", ...
        "trial03", ...
        "03_static_optimization_prep"));

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimizationPrep.ModelCFile, ...
        string(fullfile( ...
            prepDirectory, ...
            "15deg_trial03_modelC_static_optimization.osim")));

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimizationPrep. ...
        BodyKinematics.SetupFile, ...
        string(fullfile( ...
            prepDirectory, ...
            "body_kinematics", ...
            "15deg_trial03_body_kinematics_setup.xml")));

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimizationPrep. ...
        HeadSupportForce.MotionFile, ...
        string(fullfile( ...
            prepDirectory, ...
            "head_support_force", ...
            "15deg_trial03_head_support_force.mot")));

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimizationPrep. ...
        HeadSupportForce.EventDetectionSummaryCsv, ...
        string(fullfile( ...
            prepDirectory, ...
            "head_support_force", ...
            "qc", ...
            "contact_event_detection_summary.csv")));
end


function testStaticOptimizationPathsMatchExistingConvention(testCase)

    cfg = localTestConfig();

    trial = pipeline.resolveTrialContext( ...
        cfg, 45, 5);

    soDirectory = string(fullfile( ...
        cfg.outputRoot, ...
        "45deg", ...
        "trial05", ...
        "04_static_optimization"));

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimization.SetupFile, ...
        string(fullfile( ...
            soDirectory, ...
            "45deg_trial05_so_setup.xml")));

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimization.ResultsDirectory, ...
        string(fullfile( ...
            soDirectory, ...
            "results")));

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimization.OutputAuditCsv, ...
        string(fullfile( ...
            soDirectory, ...
            "qc", ...
            "static_optimization_output_audit.csv")));

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimization.ForceResultPattern, ...
        "*StaticOptimization_force.sto");

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimization.ActivationResultPattern, ...
        "*StaticOptimization_activation.sto");
end


function testResolverHasNoFilesystemSideEffects(testCase)

    cfg = localTestConfig();

    uniqueRoot = string(fullfile( ...
        tempdir, ...
        "headneck_trial_context_" + ...
        string(java.util.UUID.randomUUID())));

    cfg.outputRoot = uniqueRoot;

    verifyFalse(testCase, ...
        isfolder(uniqueRoot));

    pipeline.resolveTrialContext( ...
        cfg, 0, 1);

    verifyFalse(testCase, ...
        isfolder(uniqueRoot));
end


function testRejectsUnconfiguredConditionByDefault(testCase)

    cfg = localTestConfig();

    verifyError(testCase, ...
        @() pipeline.resolveTrialContext( ...
            cfg, 10, 1), ...
        "TrialContext:ConditionNotConfigured");
end


function testRejectsUnconfiguredTrialByDefault(testCase)

    cfg = localTestConfig();

    verifyError(testCase, ...
        @() pipeline.resolveTrialContext( ...
            cfg, 0, 99), ...
        "TrialContext:TrialNotConfigured");
end


function testCanResolveExplicitUnconfiguredIdentity(testCase)

    cfg = localTestConfig();

    trial = pipeline.resolveTrialContext( ...
        cfg, 10, 99, ...
        "RequireConfiguredTrial", false);

    verifyEqual(testCase, ...
        trial.ConditionTag, ...
        "10deg");

    verifyEqual(testCase, ...
        trial.TrialTag, ...
        "trial99");
end


function testAllStudyTrialRootsAreUnique(testCase)

    cfg = localTestConfig();

    roots = strings( ...
        numel(cfg.conditions) * ...
        numel(cfg.trials), ...
        1);

    index = 0;

    for conditionDeg = cfg.conditions

        for trialNumber = cfg.trials

            index = index + 1;

            trial = pipeline.resolveTrialContext( ...
                cfg, ...
                conditionDeg, ...
                trialNumber);

            roots(index) = ...
                trial.Paths.TrialRoot;
        end
    end

    verifyEqual(testCase, ...
        numel(unique(roots)), ...
        numel(roots));
end


function cfg = localTestConfig()

    repositoryRoot = ...
        string(fileparts(fileparts(mfilename("fullpath"))));

    addpath(repositoryRoot);

    cfg = load_project_config( ...
        "RequireLocalConfig", false, ...
        "ValidatePaths", false);

    % Keep tests independent of machine-local path existence.
    cfg.rawDataRoot = string(fullfile( ...
        tempdir, ...
        "headneck_raw_data"));

    cfg.outputRoot = string(fullfile( ...
        tempdir, ...
        "headneck_outputs"));

    % Keep baseline path-contract tests independent of project_local.m.
    % Strength-config-specific tests enable a profile explicitly through
    % localEnableStrengthConfig().
    cfg.forceCapacity.enabled = false;
    cfg.forceCapacity.configFile = "";
    cfg.forceCapacity.applyMode = "target";
end

function testDisabledStrengthConfigPreservesLegacyPaths(testCase)

    cfg = ...
        localTestConfig();

    cfg.forceCapacity.enabled = ...
        false;

    trial = ...
        pipeline.resolveTrialContext( ...
            cfg, ...
            15, ...
            3);

    expectedTrialRoot = ...
        string(fullfile( ...
            cfg.outputRoot, ...
            "15deg", ...
            "trial03"));

    verifyFalse(testCase, ...
        trial.StrengthConfigEnabled);

    verifyEqual(testCase, ...
        trial.StrengthConfigId, ...
        "");

    verifyEqual(testCase, ...
        trial.Paths.TrialRoot, ...
        expectedTrialRoot);

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimizationTrialRoot, ...
        expectedTrialRoot);

    verifyEqual(testCase, ...
        trial.Paths.StrengthConfigRoot, ...
        "");
end

function testStrengthConfigIsolatesProcess3And4Paths(testCase)

    cfg = ...
        localTestConfig();

    cfg = ...
        localEnableStrengthConfig( ...
            cfg, ...
            "m25p_a75p.json");

    trial = ...
        pipeline.resolveTrialContext( ...
            cfg, ...
            15, ...
            3);

    sharedTrialRoot = ...
        string(fullfile( ...
            cfg.outputRoot, ...
            "15deg", ...
            "trial03"));

    configRoot = ...
        string(fullfile( ...
            cfg.outputRoot, ...
            "static_optimization_configs", ...
            "m25p_a75p"));

    soTrialRoot = ...
        string(fullfile( ...
            configRoot, ...
            "15deg", ...
            "trial03"));

    verifyTrue(testCase, ...
        trial.StrengthConfigEnabled);

    verifyEqual(testCase, ...
        trial.StrengthConfigId, ...
        "m25p_a75p");

    verifyEqual(testCase, ...
        trial.Paths.TrialRoot, ...
        sharedTrialRoot);

    verifyEqual(testCase, ...
        trial.Paths.StrengthConfigRoot, ...
        configRoot);

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimizationTrialRoot, ...
        soTrialRoot);

    verifyEqual(testCase, ...
        trial.Paths.Initialization.Directory, ...
        string(fullfile( ...
            sharedTrialRoot, ...
            "01_initialization_ik")));

    verifyEqual(testCase, ...
        trial.Paths.ModelB.Directory, ...
        string(fullfile( ...
            sharedTrialRoot, ...
            "02_locked_final_ik")));

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimizationPrep.Directory, ...
        string(fullfile( ...
            soTrialRoot, ...
            "03_static_optimization_prep")));

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimization.Directory, ...
        string(fullfile( ...
            soTrialRoot, ...
            "04_static_optimization")));
end

function testStrengthConfigsShareIkButIsolateSoPaths(testCase)

    cfg25_50 = ...
        localEnableStrengthConfig( ...
            localTestConfig(), ...
            "m25p_a50p.json");

    cfg25_75 = ...
        localEnableStrengthConfig( ...
            localTestConfig(), ...
            "m25p_a75p.json");

    trial25_50 = ...
        pipeline.resolveTrialContext( ...
            cfg25_50, ...
            30, ...
            2);

    trial25_75 = ...
        pipeline.resolveTrialContext( ...
            cfg25_75, ...
            30, ...
            2);

    % Configuration-independent stages are identical.
    verifyEqual(testCase, ...
        trial25_50.Paths.Initialization.Directory, ...
        trial25_75.Paths.Initialization.Directory);

    verifyEqual(testCase, ...
        trial25_50.Paths.ModelB.Directory, ...
        trial25_75.Paths.ModelB.Directory);

    % Configuration-dependent stages are isolated.
    verifyNotEqual(testCase, ...
        trial25_50.Paths.StaticOptimizationPrep.Directory, ...
        trial25_75.Paths.StaticOptimizationPrep.Directory);

    verifyNotEqual(testCase, ...
        trial25_50.Paths.StaticOptimization.Directory, ...
        trial25_75.Paths.StaticOptimization.Directory);

    verifyEqual(testCase, ...
        trial25_50.StrengthConfigId, ...
        "m25p_a50p");

    verifyEqual(testCase, ...
        trial25_75.StrengthConfigId, ...
        "m25p_a75p");
end

function testConfiguredResolverHasNoFilesystemSideEffects(testCase)

    cfg = ...
        localTestConfig();

    uniqueRoot = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_strength_trial_context_" + ...
            string(java.util.UUID.randomUUID())));

    cfg.outputRoot = ...
        uniqueRoot;

    cfg = ...
        localEnableStrengthConfig( ...
            cfg, ...
            "m50p_a50p.json");

    verifyFalse(testCase, ...
        isfolder(uniqueRoot));

    pipeline.resolveTrialContext( ...
        cfg, ...
        0, ...
        1);

    verifyFalse(testCase, ...
        isfolder(uniqueRoot));
end

function cfg = localEnableStrengthConfig( ...
        cfg, configFileName)

    cfg.forceCapacity.enabled = ...
        true;

    cfg.forceCapacity.configFile = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_force_configs", ...
            configFileName));

    cfg.forceCapacity.applyMode = ...
        "target";
end