function tests = test_initialization_pipeline_contract
%TEST_INITIALIZATION_PIPELINE_CONTRACT Non-OpenSim contract checks for Process 1.
%
% These tests do not execute OpenSim. They verify that configuration,
% trial resolution, and the shared worker entry point are wired together.

    tests = functiontests(localfunctions);
end


function testInitializationConfigHasReviewCoordinates(testCase)

    cfg = localLoadConfig();

    verifyTrue(testCase, ...
        isfield( ...
            cfg.pipeline.initializationIk, ...
            "reviewCoordinates"));

    reviewCoordinates = string( ...
        cfg.pipeline.initializationIk. ...
        reviewCoordinates(:));

    verifyNotEmpty(testCase, ...
        reviewCoordinates);

    verifyEqual(testCase, ...
        numel(unique(reviewCoordinates)), ...
        numel(reviewCoordinates));
end


function testResolvedContextContainsWorkerInputs(testCase)

    cfg = localLoadConfig();

    cfg.rawDataRoot = string(fullfile( ...
        tempdir, ...
        "headneck_raw_data"));

    cfg.outputRoot = string(fullfile( ...
        tempdir, ...
        "headneck_outputs"));

    trial = pipeline.resolveTrialContext( ...
        cfg, ...
        cfg.conditions(1), ...
        cfg.trials(1));

    verifyTrue(testCase, ...
        isfield(trial.Inputs, ...
            "KinematicBaseModel"));

    verifyTrue(testCase, ...
        isfield(trial.Inputs, ...
            "MarkerFile"));

    verifyTrue(testCase, ...
        isfield(trial.Inputs, ...
            "InitializationIkTemplate"));

    verifyTrue(testCase, ...
        isfield(trial.Paths, ...
            "Initialization"));

    verifyTrue(testCase, ...
        isfield(trial.Paths.Initialization, ...
            "ModelAFile"));

    verifyTrue(testCase, ...
        isfield(trial.Paths.Initialization, ...
            "IkSetupFile"));

    verifyTrue(testCase, ...
        isfield(trial.Paths.Initialization, ...
            "IkMotionFile"));

    verifyTrue(testCase, ...
        isfield(trial.Paths.Initialization, ...
            "CheckpointFile"));
end


function testSharedWorkerIsResolvable(testCase)

    workerFile = which( ...
        "pipeline.runInitializationIkTrial");

    verifyNotEmpty(testCase, ...
        workerFile);
end


function cfg = localLoadConfig()

    repositoryRoot = ...
        string(fileparts(fileparts(mfilename("fullpath"))));

    addpath(repositoryRoot);

    cfg = load_project_config( ...
        "LocalConfigPolicy", "disabled", ...
        "ValidatePaths", false);
end
