function tests = test_strength_grid_analysis_write
%TEST_STRENGTH_GRID_ANALYSIS_WRITE Tests strength-grid persistence layer.

    tests = ...
        functiontests(localfunctions);
end


function testWritesCompleteAnalysisPackage(testCase)

    [cfg, result, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    outputs = ...
        soopt.writeStrengthGridAnalysis( ...
            result, ...
            cfg);

    verifyTrue(testCase, ...
        isfolder(outputs.OutputDirectory));

    requiredFiles = [
        outputs.SummaryCsv
        outputs.ParetoFrontierCsv
        outputs.GridPlanCsv
        outputs.ProposalsCsv
        outputs.MonotonicityViolationsCsv
        outputs.CandidateConfigPoolCsv
        outputs.MissingConfigCombinationsCsv
        outputs.FigurePng
        outputs.AnalysisMat
    ];

    verifyTrue(testCase, ...
        all(isfile(requiredFiles)));

    verifyTrue(testCase, ...
        outputs.FigureExported);

    writtenSummary = ...
        readtable( ...
            outputs.SummaryCsv, ...
            "TextType", ...
            "string");

    verifyEqual(testCase, ...
        string(writtenSummary.ConfigId), ...
        result.Summary.ConfigId);

    writtenPareto = ...
        readtable( ...
            outputs.ParetoFrontierCsv, ...
            "TextType", ...
            "string");

    verifyEqual(testCase, ...
        string(writtenPareto.ConfigId), ...
        result.ParetoFrontier.ConfigId);

    loaded = ...
        load( ...
            outputs.AnalysisMat, ...
            "analysisSnapshot");

    verifyEqual(testCase, ...
        loaded.analysisSnapshot.SchemaVersion, ...
        1);

    verifyEqual(testCase, ...
        loaded.analysisSnapshot.Result.Figure, ...
        []);

    verifyEqual(testCase, ...
        loaded.analysisSnapshot.Result.Axes, ...
        []);

    verifyEqual(testCase, ...
        loaded.analysisSnapshot.Result.PlanningStatus, ...
        result.PlanningStatus);

    verifyEqual(testCase, ...
        loaded.analysisSnapshot.ProjectConfig.outputRoot, ...
        cfg.outputRoot);
end


function testDefaultWriteIsNonDestructive(testCase)

    [cfg, result, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    soopt.writeStrengthGridAnalysis( ...
        result, ...
        cfg, ...
        "ExportFigure", ...
        false);

    verifyError(testCase, ...
        @() soopt.writeStrengthGridAnalysis( ...
            result, ...
            cfg, ...
            "ExportFigure", ...
            false), ...
        "StrengthGridWrite:OutputExists");
end


function testOverwriteReplacesExistingArtifacts(testCase)

    [cfg, result, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    outputs = ...
        soopt.writeStrengthGridAnalysis( ...
            result, ...
            cfg, ...
            "ExportFigure", ...
            false);

    firstText = ...
        string(fileread( ...
            outputs.SummaryCsv));

    result.Summary.FeasibilityReason(:) = ...
        "updated";

    outputs = ...
        soopt.writeStrengthGridAnalysis( ...
            result, ...
            cfg, ...
            "Overwrite", ...
            true, ...
            "ExportFigure", ...
            false);

    secondText = ...
        string(fileread( ...
            outputs.SummaryCsv));

    verifyNotEqual(testCase, ...
        secondText, ...
        firstText);

    verifyFalse(testCase, ...
        outputs.FigureExported);

    verifyEqual(testCase, ...
        outputs.FigurePng, ...
        "");
end


function testCustomOutputDirectoryIsSupported(testCase)

    [cfg, result, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    customDirectory = ...
        string(fullfile( ...
            fileparts(cfg.outputRoot), ...
            "custom_grid_report"));

    outputs = ...
        soopt.writeStrengthGridAnalysis( ...
            result, ...
            cfg, ...
            "OutputDirectory", ...
            customDirectory, ...
            "ExportFigure", ...
            false);

    verifyEqual(testCase, ...
        outputs.OutputDirectory, ...
        customDirectory);

    verifyTrue(testCase, ...
        isfile(outputs.AnalysisMat));
end


function testExistingFigureIsNotClosed(testCase)

    [cfg, result, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    [fig, ax, plotInfo] = ...
        soopt.plotFeasibilityMap( ...
            result.Summary, ...
            "Visible", ...
            "off");

    figureCleanup = ...
        onCleanup(@() localCloseFigure(fig)); %#ok<NASGU>

    result.Figure = ...
        fig;

    result.Axes = ...
        ax;

    result.PlotInfo = ...
        plotInfo;

    outputs = ...
        soopt.writeStrengthGridAnalysis( ...
            result, ...
            cfg);

    verifyTrue(testCase, ...
        isfile(outputs.FigurePng));

    verifyTrue(testCase, ...
        isgraphics(fig, "figure"));
end


function testMissingRequiredResultFieldIsRejected(testCase)

    [cfg, result, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    result = ...
        rmfield( ...
            result, ...
            "Proposals");

    verifyError(testCase, ...
        @() soopt.writeStrengthGridAnalysis( ...
            result, ...
            cfg), ...
        "StrengthGridWrite:ResultFieldsMissing");
end


function [cfg, result, cleanup] = localCreateFixture()

    root = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_grid_write_" + ...
            string(java.util.UUID.randomUUID())));

    outputRoot = ...
        string(fullfile( ...
            root, ...
            "output"));

    mkdir(outputRoot);

    cleanup = ...
        onCleanup(@() localRemoveTree(root));

    cfg = struct;

    cfg.outputRoot = ...
        outputRoot;

    cfg.projectName = ...
        "synthetic-test";

    %% Configuration pool

    ConfigId = [
        "m25p_a50p"
        "m25p_a75p"
        "m50p_a50p"
        "m50p_a75p"
    ];

    MusclePercent = ...
        [25; 25; 50; 50];

    ActuatorPercent = ...
        [50; 75; 50; 75];

    FileName = ...
        ConfigId + ".json";

    ConfigFile = ...
        "C:\configs\" + FileName;

    configurations = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            FileName, ...
            ConfigFile);

    configPool = struct;

    configPool.SchemaVersion = ...
        1;

    configPool.ConfigDirectory = ...
        "C:\configs";

    configPool.Configurations = ...
        configurations;

    configPool.MuscleGrid = ...
        [25; 50];

    configPool.ActuatorGrid = ...
        [50; 75];

    configPool.DiscoveredConfigurationCount = ...
        4;

    configPool.ExpectedCartesianCount = ...
        4;

    configPool.IsCompleteCartesianGrid = ...
        true;

    configPool.MissingCombinations = ...
        table( ...
            zeros(0,1), ...
            zeros(0,1), ...
            'VariableNames', { ...
                'MusclePercent', ...
                'ActuatorPercent'});

    %% Observed summary

    ConfigId = [
        "m25p_a50p"
        "m25p_a75p"
        "m50p_a50p"
    ];

    MusclePercent = ...
        [25; 25; 50];

    ActuatorPercent = ...
        [50; 75; 50];

    AssessmentComplete = ...
        [true; true; true];

    IsFeasible = ...
        [false; true; true];

    FeasibilityStatus = [
        "INFEASIBLE_SO_FAILURE"
        "FEASIBLE"
        "FEASIBLE"
    ];

    FeasibilityReason = [
        "failed"
        "passed"
        "passed"
    ];

    IsParetoEligible = ...
        [false; true; true];

    IsParetoOptimal = ...
        [false; true; true];

    DominatedByCount = ...
        [0; 0; 0];

    DominatingConfigIds = ...
        strings(3,1);

    summary = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            AssessmentComplete, ...
            IsFeasible, ...
            FeasibilityStatus, ...
            FeasibilityReason, ...
            IsParetoEligible, ...
            IsParetoOptimal, ...
            DominatedByCount, ...
            DominatingConfigIds);

    paretoFrontier = ...
        summary( ...
            summary.IsParetoOptimal, ...
            :);

    %% Monotonicity audit

    violations = ...
        table( ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            'VariableNames', { ...
                'LowerFeasibleConfigId', ...
                'LowerMusclePercent', ...
                'LowerActuatorPercent', ...
                'HigherInfeasibleConfigId', ...
                'HigherMusclePercent', ...
                'HigherActuatorPercent', ...
                'MuscleIncrease', ...
                'ActuatorIncrease'});

    monotonicityAudit = struct;

    monotonicityAudit.SchemaVersion = ...
        1;

    monotonicityAudit.IsMonotonic = ...
        true;

    monotonicityAudit.ViolationCount = ...
        0;

    monotonicityAudit.AssessedConfigurations = ...
        3;

    monotonicityAudit.FeasibleConfigurations = ...
        2;

    monotonicityAudit.InfeasibleConfigurations = ...
        1;

    monotonicityAudit.Violations = ...
        violations;

    %% Grid plan

    ConfigId = [
        "m25p_a50p"
        "m25p_a75p"
        "m50p_a50p"
        "m50p_a75p"
    ];

    MusclePercent = ...
        [25; 25; 50; 50];

    ActuatorPercent = ...
        [50; 75; 50; 75];

    ExistsInSummary = ...
        [true; true; true; false];

    ExistingIncomplete = ...
        false(4,1);

    AssessmentComplete = ...
        [true; true; true; false];

    ObservedFeasible = ...
        [false; true; true; false];

    GridStatus = [
        "ASSESSED_INFEASIBLE"
        "ASSESSED_FEASIBLE"
        "ASSESSED_FEASIBLE"
        "INFERRED_FEASIBLE"
    ];

    NeedsAssessment = ...
        false(4,1);

    FeasibleInferenceSources = [
        ""
        ""
        ""
        "m25p_a75p;m50p_a50p"
    ];

    InfeasibleInferenceSources = ...
        strings(4,1);

    gridPlan = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            ExistsInSummary, ...
            ExistingIncomplete, ...
            AssessmentComplete, ...
            ObservedFeasible, ...
            GridStatus, ...
            NeedsAssessment, ...
            FeasibleInferenceSources, ...
            InfeasibleInferenceSources);

    %% Proposals

    proposals = ...
        table( ...
            zeros(0,1), ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            false(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            'VariableNames', { ...
                'PriorityRank', ...
                'ConfigId', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ExistingIncomplete', ...
                'FeasibleOutcomeResolvedCount', ...
                'InfeasibleOutcomeResolvedCount', ...
                'WorstCaseResolvedCount', ...
                'BestCaseResolvedCount', ...
                'TotalResolutionPotential', ...
                'ResolutionImbalance', ...
                'GridCenterDistance'});

    %% Analysis result

    result = struct;

    result.SchemaVersion = ...
        1;

    result.ConfigPool = ...
        configPool;

    result.Summary = ...
        summary;

    result.ParetoFrontier = ...
        paretoFrontier;

    result.MonotonicityAudit = ...
        monotonicityAudit;

    result.PlanningAvailable = ...
        true;

    result.PlanningStatus = ...
        "AVAILABLE";

    result.PlanningReason = ...
        "synthetic";

    result.GridPlan = ...
        gridPlan;

    result.Proposals = ...
        proposals;

    result.Figure = ...
        gobjects(0,1);

    result.Axes = ...
        gobjects(0,1);

    result.PlotInfo = ...
        struct;
end


function localCloseFigure(fig)

    if isgraphics(fig, "figure")

        close(fig);
    end
end


function localRemoveTree(root)

    if isfolder(root)

        rmdir(root, "s");
    end
end
