function tests = test_strength_boundary_refinement
%TEST_STRENGTH_BOUNDARY_REFINEMENT Tests adaptive numeric boundary proposals.

    tests = ...
        functiontests(localfunctions);
end


function testSimpleVerticalBracketProposesMidpoint(testCase)

    summary = ...
        localSummary( ...
            [ ...
                "m25p_a15p"
                "m25p_a25p"
            ], ...
            [25; 25], ...
            [15; 25], ...
            [true; true], ...
            [false; true]);

    proposals = ...
        soopt.proposeBoundaryRefinement( ...
            summary);

    verifyEqual(testCase, ...
        height(proposals), ...
        1);

    verifyEqual(testCase, ...
        proposals.ConfigId, ...
        "m25p_a20p");

    verifyEqual(testCase, ...
        proposals.MusclePercent, ...
        25);

    verifyEqual(testCase, ...
        proposals.ActuatorPercent, ...
        20);

    verifyEqual(testCase, ...
        proposals.LowerInfeasibleConfigId, ...
        "m25p_a15p");

    verifyEqual(testCase, ...
        proposals.UpperFeasibleConfigId, ...
        "m25p_a25p");
end


function testSimpleHorizontalBracketProposesMidpoint(testCase)

    summary = ...
        localSummary( ...
            [ ...
                "m20p_a25p"
                "m30p_a25p"
            ], ...
            [20; 30], ...
            [25; 25], ...
            [true; true], ...
            [false; true]);

    proposals = ...
        soopt.proposeBoundaryRefinement( ...
            summary);

    verifyEqual(testCase, ...
        proposals.ConfigId, ...
        "m25p_a25p");
end


function testResolvedAtFivePercentReturnsEmpty(testCase)

    summary = ...
        localSummary( ...
            [ ...
                "m25p_a15p"
                "m25p_a20p"
            ], ...
            [25; 25], ...
            [15; 20], ...
            [true; true], ...
            [false; true]);

    proposals = ...
        soopt.proposeBoundaryRefinement( ...
            summary);

    verifyEqual(testCase, ...
        height(proposals), ...
        0);
end


function testOnePercentPassCanRefineFivePercentBracket(testCase)

    summary = ...
        localSummary( ...
            [ ...
                "m25p_a15p"
                "m25p_a20p"
            ], ...
            [25; 25], ...
            [15; 20], ...
            [true; true], ...
            [false; true]);

    proposals = ...
        soopt.proposeBoundaryRefinement( ...
            summary, ...
            "IncrementPercent", ...
            1);

    verifyEqual(testCase, ...
        proposals.MusclePercent, ...
        25);

    verifyTrue(testCase, ...
        ismember( ...
            proposals.ActuatorPercent, ...
            [17 18]));

    verifyEqual(testCase, ...
        proposals.IncrementPercent, ...
        1);
end


function testNonlinearBoundaryUsesLocalEvidenceOnly(testCase)

    summary = ...
        localSummary( ...
            [ ...
                "m10p_a40p"
                "m10p_a50p"
                "m25p_a15p"
                "m25p_a25p"
                "m40p_a05p"
                "m40p_a15p"
            ], ...
            [10; 10; 25; 25; 40; 40], ...
            [40; 50; 15; 25; 5; 15], ...
            true(6,1), ...
            [false; true; false; true; false; true]);

    proposals = ...
        soopt.proposeBoundaryRefinement( ...
            summary, ...
            "MaxProposals", ...
            Inf);

    verifyGreaterThan(testCase, ...
        height(proposals), ...
        0);

    verifyFalse(testCase, ...
        any( ...
            proposals.MusclePercent == 25 & ...
            proposals.ActuatorPercent == 15));

    verifyFalse(testCase, ...
        any( ...
            proposals.MusclePercent == 25 & ...
            proposals.ActuatorPercent == 25));

    verifyTrue(testCase, ...
        all( ...
            mod(proposals.MusclePercent, 5) == 0));

    verifyTrue(testCase, ...
        all( ...
            mod(proposals.ActuatorPercent, 5) == 0));

    verifyTrue(testCase, ...
        all( ...
            strlength(proposals.LowerInfeasibleConfigId) > 0));

    verifyTrue(testCase, ...
        all( ...
            strlength(proposals.UpperFeasibleConfigId) > 0));
end


function testMonotonicityViolationIsRejected(testCase)

    summary = ...
        localSummary( ...
            [ ...
                "m20p_a20p"
                "m30p_a30p"
            ], ...
            [20; 30], ...
            [20; 30], ...
            [true; true], ...
            [true; false]);

    verifyError(testCase, ...
        @() soopt.proposeBoundaryRefinement(summary), ...
        "StrengthBoundary:MonotonicityViolation");
end


function testOnlyOneOutcomeClassReturnsEmpty(testCase)

    feasibleOnly = ...
        localSummary( ...
            [ ...
                "m20p_a20p"
                "m30p_a30p"
            ], ...
            [20; 30], ...
            [20; 30], ...
            [true; true], ...
            [true; true]);

    infeasibleOnly = ...
        localSummary( ...
            [ ...
                "m20p_a20p"
                "m30p_a30p"
            ], ...
            [20; 30], ...
            [20; 30], ...
            [true; true], ...
            [false; false]);

    verifyEqual(testCase, ...
        height( ...
            soopt.proposeBoundaryRefinement( ...
                feasibleOnly)), ...
        0);

    verifyEqual(testCase, ...
        height( ...
            soopt.proposeBoundaryRefinement( ...
                infeasibleOnly)), ...
        0);
end


function testExistingIncompleteCoordinateCanBeProposed(testCase)

    summary = ...
        localSummary( ...
            [ ...
                "m25p_a15p"
                "m25p_a20p"
                "m25p_a25p"
            ], ...
            [25; 25; 25], ...
            [15; 20; 25], ...
            [true; false; true], ...
            [false; false; true]);

    proposals = ...
        soopt.proposeBoundaryRefinement( ...
            summary);

    verifyEqual(testCase, ...
        proposals.ConfigId, ...
        "m25p_a20p");

    verifyTrue(testCase, ...
        proposals.ExistingIncomplete);

    verifyEqual(testCase, ...
        proposals.ExistingConfigId, ...
        "m25p_a20p");
end


function testExplicitBoundsRestrictVirtualLattice(testCase)

    summary = ...
        localSummary( ...
            [ ...
                "m10p_a10p"
                "m40p_a40p"
            ], ...
            [10; 40], ...
            [10; 40], ...
            [true; true], ...
            [false; true]);

    proposals = ...
        soopt.proposeBoundaryRefinement( ...
            summary, ...
            "MuscleBounds", ...
            [20 30], ...
            "ActuatorBounds", ...
            [20 30], ...
            "MaxProposals", ...
            Inf);

    verifyTrue(testCase, ...
        all( ...
            proposals.MusclePercent >= 20 & ...
            proposals.MusclePercent <= 30));

    verifyTrue(testCase, ...
        all( ...
            proposals.ActuatorPercent >= 20 & ...
            proposals.ActuatorPercent <= 30));
end


function summary = ...
        localSummary( ...
            configId, ...
            musclePercent, ...
            actuatorPercent, ...
            assessmentComplete, ...
            isFeasible)

    ConfigId = ...
        string(configId(:));

    MusclePercent = ...
        double(musclePercent(:));

    ActuatorPercent = ...
        double(actuatorPercent(:));

    AssessmentComplete = ...
        logical(assessmentComplete(:));

    IsFeasible = ...
        logical(isFeasible(:));

    summary = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            AssessmentComplete, ...
            IsFeasible);
end
