function tests = test_strength_config_identity
%TEST_STRENGTH_CONFIG_IDENTITY Test canonical strength-config naming.

    tests = functiontests(localfunctions);
end


function testCanonicalName(testCase)

    info = ...
        pipeline.parseStrengthConfigName( ...
            "m25p_a75p.json");

    verifyEqual( ...
        testCase, ...
        info.ConfigId, ...
        "m25p_a75p");

    verifyEqual( ...
        testCase, ...
        info.MusclePercent, ...
        25);

    verifyEqual( ...
        testCase, ...
        info.ActuatorPercent, ...
        75);

    verifyEqual( ...
        testCase, ...
        info.FileName, ...
        "m25p_a75p.json");
end


function testFullPath(testCase)

    configFile = ...
        fullfile( ...
            tempdir, ...
            "configs", ...
            "m50p_a25p.json");

    info = ...
        pipeline.parseStrengthConfigName( ...
            configFile);

    verifyEqual( ...
        testCase, ...
        info.ConfigId, ...
        "m50p_a25p");

    verifyEqual( ...
        testCase, ...
        info.MusclePercent, ...
        50);

    verifyEqual( ...
        testCase, ...
        info.ActuatorPercent, ...
        25);

    verifyEqual( ...
        testCase, ...
        info.ConfigFile, ...
        string(configFile));
end


function testInvalidNameRejected(testCase)

    verifyError( ...
        testCase, ...
        @() pipeline.parseStrengthConfigName( ...
            "muscle25_actuator75.json"), ...
        "StrengthConfig:InvalidName");
end


function testMissingPercentMarkersRejected(testCase)

    verifyError( ...
        testCase, ...
        @() pipeline.parseStrengthConfigName( ...
            "m25_a75.json"), ...
        "StrengthConfig:InvalidName");
end


function testWrongExtensionRejected(testCase)

    verifyError( ...
        testCase, ...
        @() pipeline.parseStrengthConfigName( ...
            "m25p_a75p.mat"), ...
        "StrengthConfig:InvalidExtension");
end


function testZeroMusclePercentRejected(testCase)

    verifyError( ...
        testCase, ...
        @() pipeline.parseStrengthConfigName( ...
            "m0p_a75p.json"), ...
        "StrengthConfig:InvalidMusclePercent");
end


function testZeroActuatorPercentRejected(testCase)

    verifyError( ...
        testCase, ...
        @() pipeline.parseStrengthConfigName( ...
            "m25p_a0p.json"), ...
        "StrengthConfig:InvalidActuatorPercent");
end