function tests = test_strength_configuration_write
%TEST_STRENGTH_CONFIGURATION_WRITE Tests adaptive strength JSON generation.

    tests = functiontests(localfunctions);
end


function testWritesCanonicalConfigFromTemplate(testCase)

    [cfg, templateFile, root, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    templateBefore = ...
        string(fileread(templateFile));

    result = ...
        soopt.writeStrengthConfiguration( ...
            cfg, ...
            25, ...
            15);

    verifyEqual(testCase, ...
        result.ConfigId, ...
        "m25p_a15p");

    verifyEqual(testCase, ...
        result.FileName, ...
        "m25p_a15p.json");

    verifyTrue(testCase, ...
        result.Created);

    verifyFalse(testCase, ...
        result.ReusedExisting);

    verifyEqual(testCase, ...
        result.ConfigDirectory, ...
        string(fullfile( ...
            root, ...
            "adaptive_generated")));

    verifyTrue(testCase, ...
        isfile(result.ConfigFile));

    verifyEqual(testCase, ...
        string(fileread(templateFile)), ...
        templateBefore);

    loaded = ...
        modelprep.loadForceCapacityConfig( ...
            result.ConfigFile);

    localVerifyCoordinate( ...
        testCase, ...
        loaded.Config, ...
        25, ...
        15);

    verifyEqual(testCase, ...
        string(loaded.Config.DefaultApplyMode), ...
        "target");
end


function testPreservesNonStrengthEntries(testCase)

    [cfg, templateFile, ~, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    template = ...
        modelprep.loadForceCapacityConfig( ...
            templateFile);

    result = ...
        soopt.writeStrengthConfiguration( ...
            cfg, ...
            30, ...
            20);

    generated = ...
        modelprep.loadForceCapacityConfig( ...
            result.ConfigFile);

    templateEntries = ...
        template.Config.Entries(:);

    generatedEntries = ...
        generated.Config.Entries(:);

    verifyEqual(testCase, ...
        numel(generatedEntries), ...
        numel(templateEntries));

    passiveIndex = ...
        find( ...
            string({templateEntries.ObjectType}).' == ...
                "BushingForce", ...
            1);

    verifyNotEmpty(testCase, ...
        passiveIndex);

    verifyEqual(testCase, ...
        generatedEntries(passiveIndex), ...
        templateEntries(passiveIndex));

    preserveIndex = ...
        find( ...
            string({templateEntries.Name}).' == ...
                "preserved_actuator", ...
            1);

    verifyNotEmpty(testCase, ...
        preserveIndex);

    verifyEqual(testCase, ...
        generatedEntries(preserveIndex), ...
        templateEntries(preserveIndex));
end


function testExistingMatchingConfigIsReused(testCase)

    [cfg, ~, ~, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    first = ...
        soopt.writeStrengthConfiguration( ...
            cfg, ...
            20, ...
            10);

    second = ...
        soopt.writeStrengthConfiguration( ...
            cfg, ...
            20, ...
            10);

    verifyTrue(testCase, ...
        first.Created);

    verifyFalse(testCase, ...
        second.Created);

    verifyTrue(testCase, ...
        second.ReusedExisting);

    verifyEqual(testCase, ...
        second.ConfigFile, ...
        first.ConfigFile);
end


function testExistingMismatchIsRejected(testCase)

    [cfg, ~, root, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    outputDirectory = ...
        string(fullfile( ...
            root, ...
            "adaptive_generated"));

    mkdir(outputDirectory);

    conflictingFile = ...
        string(fullfile( ...
            outputDirectory, ...
            "m25p_a15p.json"));

    localWriteTemplate( ...
        conflictingFile, ...
        0.50, ...
        0.50);

    verifyError(testCase, ...
        @() soopt.writeStrengthConfiguration( ...
            cfg, ...
            25, ...
            15), ...
        "StrengthConfigWrite:ExistingConfigMismatch");
end


function testCustomDirectoryAndLeadingZero(testCase)

    [cfg, ~, root, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    customDirectory = ...
        string(fullfile( ...
            root, ...
            "custom_adaptive"));

    result = ...
        soopt.writeStrengthConfiguration( ...
            cfg, ...
            35, ...
            5, ...
            "ConfigDirectory", ...
            customDirectory);

    verifyEqual(testCase, ...
        result.ConfigDirectory, ...
        customDirectory);

    verifyEqual(testCase, ...
        result.FileName, ...
        "m35p_a05p.json");

    verifyTrue(testCase, ...
        isfile(result.ConfigFile));
end


function testPositiveIntegerPercentRequired(testCase)

    [cfg, ~, ~, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    verifyError(testCase, ...
        @() soopt.writeStrengthConfiguration( ...
            cfg, ...
            12.5, ...
            10), ...
        "StrengthConfigWrite:InvalidPercent");

    verifyError(testCase, ...
        @() soopt.writeStrengthConfiguration( ...
            cfg, ...
            10, ...
            0), ...
        "StrengthConfigWrite:InvalidPercent");
end


function testTemplateRequiresActuatorEntry(testCase)

    [cfg, ~, root, cleanup] = ...
        localCreateFixture(); %#ok<ASGLU>

    noActuatorFile = ...
        string(fullfile( ...
            root, ...
            "no_actuator_template.json"));

    entry = ...
        localSetEntry( ...
            "stern_mast_r", ...
            "Millard2012EquilibriumMuscle", ...
            "Muscle", ...
            "Flexion", ...
            "max_isometric_force", ...
            100, ...
            0.50);

    localWriteConfig( ...
        noActuatorFile, ...
        localConfig(entry));

    verifyError(testCase, ...
        @() soopt.writeStrengthConfiguration( ...
            cfg, ...
            20, ...
            20, ...
            "TemplateConfigFile", ...
            noActuatorFile), ...
        "StrengthConfigWrite:NoActuatorEntries");
end


function [cfg, templateFile, root, cleanup] = ...
        localCreateFixture()

    root = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_strength_write_" + ...
            string(java.util.UUID.randomUUID())));

    mkdir(root);

    cleanup = ...
        onCleanup(@() localRemoveTree(root));

    templateFile = ...
        string(fullfile( ...
            root, ...
            "m50p_a50p.json"));

    localWriteTemplate( ...
        templateFile, ...
        0.50, ...
        0.50);

    cfg = struct;
    cfg.optimization = struct;
    cfg.optimization.staticOptimization = struct;
    cfg.optimization.staticOptimization.adaptiveBoundary = struct;

    cfg.optimization.staticOptimization.adaptiveBoundary. ...
        templateConfigFile = ...
        templateFile;

    cfg.optimization.staticOptimization.adaptiveBoundary. ...
        configDirectory = ...
        string(fullfile( ...
            root, ...
            "adaptive_generated"));

    cfg.forceCapacity = struct;
    cfg.forceCapacity.configFile = ...
        string(fullfile( ...
            root, ...
            "unrelated", ...
            "selected_profile.json"));
end


function localWriteTemplate( ...
        filePath, ...
        muscleScale, ...
        actuatorScale)

    entries = ...
        repmat( ...
            localEntry(), ...
            6, ...
            1);

    entries(1) = ...
        localSetEntry( ...
            "stern_mast_r", ...
            "Millard2012EquilibriumMuscle", ...
            "Muscle", ...
            "Flexion", ...
            "max_isometric_force", ...
            100, ...
            muscleScale);

    entries(2) = ...
        localSetEntry( ...
            "splen_cap_r", ...
            "Millard2012EquilibriumMuscle", ...
            "Muscle", ...
            "Extension", ...
            "max_isometric_force", ...
            80, ...
            muscleScale);

    entries(3) = ...
        localSetEntry( ...
            "pitch1_reserve", ...
            "CoordinateActuator", ...
            "Actuator", ...
            "Coordinate actuator", ...
            "optimal_force", ...
            2, ...
            actuatorScale);

    entries(4) = ...
        localSetEntry( ...
            "yaw1_reserve", ...
            "TorqueActuator", ...
            "Actuator", ...
            "Torque actuator", ...
            "optimal_force", ...
            1, ...
            actuatorScale);

    entries(5) = ...
        localEntry();

    entries(5).Name = ...
        "passive_bushing";

    entries(5).ObjectType = ...
        "BushingForce";

    entries(5).Category = ...
        "Passive force";

    entries(5).Group = ...
        "Bushing";

    entries(5).CapacityAction = ...
        "preserve";

    entries(5).AppliesForceAction = ...
        "set";

    entries(5).TargetAppliesForce = ...
        false;

    entries(6) = ...
        localEntry();

    entries(6).Name = ...
        "preserved_actuator";

    entries(6).ObjectType = ...
        "CoordinateActuator";

    entries(6).Category = ...
        "Actuator";

    entries(6).Group = ...
        "Coordinate actuator";

    entries(6).CapacityParameter = ...
        "optimal_force";

    localWriteConfig( ...
        filePath, ...
        localConfig(entries));
end


function config = localConfig(entries)

    sourceModel = struct;

    sourceModel.FileName = ...
        "synthetic.osim";

    sourceModel.FullPath = ...
        "C:\synthetic\synthetic.osim";

    sourceModel.Bytes = ...
        1234;

    sourceModel.Modified = ...
        "synthetic";

    config = struct;

    config.Schema = ...
        "headneck-force-capacity-config";

    config.Version = ...
        1;

    config.CreatedAt = ...
        "2026-08-27T00:00:00";

    config.Description = ...
        "synthetic template";

    config.SourceModel = ...
        sourceModel;

    config.DefaultApplyMode = ...
        "target";

    config.EntryCount = ...
        numel(entries);

    config.Entries = ...
        entries;
end


function entry = localEntry()

    entry = struct( ...
        "Name", "", ...
        "ObjectType", "", ...
        "Category", "", ...
        "Group", "", ...
        "CapacityParameter", "", ...
        "CapacityAction", "preserve", ...
        "ReferenceValue", [], ...
        "TargetValue", [], ...
        "ScaleFactor", [], ...
        "UnitNote", "", ...
        "AppliesForceAction", "preserve", ...
        "ReferenceAppliesForce", true, ...
        "TargetAppliesForce", true);
end


function entry = localSetEntry( ...
        name, ...
        objectType, ...
        category, ...
        group, ...
        capacityParameter, ...
        referenceValue, ...
        scaleFactor)

    entry = ...
        localEntry();

    entry.Name = ...
        name;

    entry.ObjectType = ...
        objectType;

    entry.Category = ...
        category;

    entry.Group = ...
        group;

    entry.CapacityParameter = ...
        capacityParameter;

    entry.CapacityAction = ...
        "set";

    entry.ReferenceValue = ...
        referenceValue;

    entry.TargetValue = ...
        referenceValue * ...
        scaleFactor;

    entry.ScaleFactor = ...
        scaleFactor;

    entry.UnitNote = ...
        "synthetic";
end


function localWriteConfig(filePath, config)

    try
        jsonText = ...
            jsonencode( ...
                config, ...
                "PrettyPrint", ...
                true);
    catch
        jsonText = ...
            jsonencode(config);
    end

    fid = ...
        fopen(filePath, "w");

    assert(fid >= 0, ...
        "StrengthConfigWriteTest:FileCreateFailed", ...
        "Could not create synthetic JSON:\n%s", ...
        filePath);

    cleaner = ...
        onCleanup(@() fclose(fid)); %#ok<NASGU>

    fwrite(fid, jsonText, "char");
end


function localVerifyCoordinate( ...
        testCase, ...
        config, ...
        musclePercent, ...
        actuatorPercent)

    entries = ...
        config.Entries(:);

    for iEntry = 1:numel(entries)

        if lower(string(entries(iEntry).CapacityAction)) ~= "set"
            continue;
        end

        objectType = ...
            lower(string(entries(iEntry).ObjectType));

        if endsWith(objectType, "muscle")
            expectedScale = musclePercent / 100;
        elseif contains(objectType, "actuator")
            expectedScale = actuatorPercent / 100;
        else
            continue;
        end

        verifyEqual(testCase, ...
            double(entries(iEntry).ScaleFactor), ...
            expectedScale, ...
            "AbsTol", ...
            1e-12);

        verifyEqual(testCase, ...
            double(entries(iEntry).TargetValue), ...
            double(entries(iEntry).ReferenceValue) * ...
                expectedScale, ...
            "AbsTol", ...
            1e-12);
    end
end


function localRemoveTree(root)

    if isfolder(root)
        rmdir(root, "s");
    end
end
