function tests = test_strength_configuration_feasibility
%TEST_STRENGTH_CONFIGURATION_FEASIBILITY Contract tests for SO feasibility.
%
% These tests use synthetic Process-4 batch summaries. No OpenSim execution
% is required.

    tests = ...
        functiontests(localfunctions);
end


function testCompleteSuccessfulBatchIsFeasible(testCase)

    [cfg, configRow, cleanup] = ...
        localCreateConfiguration(); %#ok<ASGLU>

    summary = ...
        localBaseSummary(cfg, configRow);

    localWriteSummary( ...
        configRow, ...
        summary);

    result = ...
        soopt.evaluateFeasibility( ...
            configRow, ...
            cfg);

    verifyTrue(testCase, ...
        result.AssessmentComplete);

    verifyTrue(testCase, ...
        result.IsFeasible);

    verifyEqual(testCase, ...
        result.Status, ...
        "FEASIBLE");

    verifyEqual(testCase, ...
        result.ExpectedTrials, ...
        4);

    verifyEqual(testCase, ...
        result.SummaryRows, ...
        4);

    verifyEqual(testCase, ...
        result.SucceededTrials, ...
        4);

    verifyEqual(testCase, ...
        result.FailedTrials, ...
        0);

    verifyEqual(testCase, ...
        result.OutputAuditFailedTrials, ...
        0);
end


function testFullProcess4StyleSummaryIsFeasible(testCase)

    [cfg, configRow, cleanup] = ...
        localCreateConfiguration(); %#ok<ASGLU>

    summary = ...
        localBaseSummary(cfg, configRow);

    nRows = ...
        height(summary);

    summary.TrialStem = ...
        compose( ...
            "%02gdeg_trial%02d", ...
            summary.ConditionDeg, ...
            summary.TrialNumber);

    summary.DurationSeconds = ...
        ones(nRows,1);

    summary.StaticOptimizationDurationSeconds = ...
        ones(nRows,1);

    summary.Process3CheckpointFile = ...
        repmat("checkpoint.mat", nRows, 1);

    summary.StaticOptimizationSetupFile = ...
        repmat("setup.xml", nRows, 1);

    summary.ResultsDirectory = ...
        repmat("results", nRows, 1);

    summary.ForceFile = ...
        repmat("force.sto", nRows, 1);

    summary.ActivationFile = ...
        repmat("activation.sto", nRows, 1);

    summary.ForceRows = ...
        repmat(401, nRows, 1);

    summary.ActivationRows = ...
        repmat(401, nRows, 1);

    summary.CheckpointFile = ...
        repmat("run_checkpoint.mat", nRows, 1);

    summary.ErrorIdentifier = ...
        strings(nRows,1);

    summary.ErrorMessage = ...
        strings(nRows,1);

    localWriteSummary( ...
        configRow, ...
        summary);

    result = ...
        soopt.evaluateFeasibility( ...
            configRow, ...
            cfg);

    verifyTrue(testCase, ...
        result.AssessmentComplete);

    verifyTrue(testCase, ...
        result.IsFeasible);

    verifyEqual(testCase, ...
        result.Status, ...
        "FEASIBLE");

    verifyEqual(testCase, ...
        result.SummaryRows, ...
        4);
end


function testStaticOptimizationFailureIsInfeasible(testCase)

    [cfg, configRow, cleanup] = ...
        localCreateConfiguration(); %#ok<ASGLU>

    summary = ...
        localBaseSummary(cfg, configRow);

    failureRow = ...
        summary.ConditionDeg == 15 & ...
        summary.TrialNumber == 1;

    verifyEqual(testCase, ...
        nnz(failureRow), ...
        1);

    summary.Succeeded(failureRow) = ...
        false;

    summary.Status(failureRow) = ...
        "failed";

    summary.OutputAuditPassed(failureRow) = ...
        false;

    localWriteSummary( ...
        configRow, ...
        summary);

    result = ...
        soopt.evaluateFeasibility( ...
            configRow, ...
            cfg);

    verifyTrue(testCase, ...
        result.AssessmentComplete);

    verifyFalse(testCase, ...
        result.IsFeasible);

    verifyEqual(testCase, ...
        result.Status, ...
        "INFEASIBLE_SO_FAILURE");

    verifyEqual(testCase, ...
        result.FailedTrials, ...
        1);

    verifyEqual(testCase, ...
        result.FailedTrialKeys, ...
        "15deg|trial01");

    % OutputAuditPassed=false on a failed SO run is not double-counted as
    % an independent output-audit failure.
    verifyEqual(testCase, ...
        result.OutputAuditFailedTrials, ...
        0);
end


function testOutputAuditFailureIsInfeasible(testCase)

    [cfg, configRow, cleanup] = ...
        localCreateConfiguration(); %#ok<ASGLU>

    summary = ...
        localBaseSummary(cfg, configRow);

    auditFailureRow = ...
        summary.ConditionDeg == 0 & ...
        summary.TrialNumber == 2;

    verifyEqual(testCase, ...
        nnz(auditFailureRow), ...
        1);

    summary.OutputAuditPassed(auditFailureRow) = ...
        false;

    localWriteSummary( ...
        configRow, ...
        summary);

    result = ...
        soopt.evaluateFeasibility( ...
            configRow, ...
            cfg);

    verifyTrue(testCase, ...
        result.AssessmentComplete);

    verifyFalse(testCase, ...
        result.IsFeasible);

    verifyEqual(testCase, ...
        result.Status, ...
        "INFEASIBLE_OUTPUT_AUDIT");

    verifyEqual(testCase, ...
        result.FailedTrials, ...
        0);

    verifyEqual(testCase, ...
        result.OutputAuditFailedTrials, ...
        1);

    verifyEqual(testCase, ...
        result.OutputAuditFailedTrialKeys, ...
        "0deg|trial02");
end


function testMissingSummaryIsIncompleteNotInfeasible(testCase)

    [cfg, configRow, cleanup] = ...
        localCreateConfiguration(); %#ok<ASGLU>

    result = ...
        soopt.evaluateFeasibility( ...
            configRow, ...
            cfg);

    verifyFalse(testCase, ...
        result.AssessmentComplete);

    verifyFalse(testCase, ...
        result.IsFeasible);

    verifyEqual(testCase, ...
        result.Status, ...
        "INCOMPLETE_MISSING_BATCH_SUMMARY");
end


function testMissingExpectedTrialIsIncomplete(testCase)

    [cfg, configRow, cleanup] = ...
        localCreateConfiguration(); %#ok<ASGLU>

    summary = ...
        localBaseSummary(cfg, configRow);

    summary(end,:) = ...
        [];

    localWriteSummary( ...
        configRow, ...
        summary);

    result = ...
        soopt.evaluateFeasibility( ...
            configRow, ...
            cfg);

    verifyFalse(testCase, ...
        result.AssessmentComplete);

    verifyFalse(testCase, ...
        result.IsFeasible);

    verifyEqual(testCase, ...
        result.Status, ...
        "INCOMPLETE_TRIAL_SET_MISMATCH");

    verifyEqual(testCase, ...
        result.MissingTrialKeys, ...
        "15deg|trial02");
end


function testDuplicateTrialIsIncomplete(testCase)

    [cfg, configRow, cleanup] = ...
        localCreateConfiguration(); %#ok<ASGLU>

    summary = ...
        localBaseSummary(cfg, configRow);

    summary = ...
        [ ...
            summary
            summary(1,:) ...
        ];

    localWriteSummary( ...
        configRow, ...
        summary);

    result = ...
        soopt.evaluateFeasibility( ...
            configRow, ...
            cfg);

    verifyFalse(testCase, ...
        result.AssessmentComplete);

    verifyEqual(testCase, ...
        result.Status, ...
        "INCOMPLETE_DUPLICATE_TRIALS");

    verifyEqual(testCase, ...
        result.DuplicateTrialKeys, ...
        "0deg|trial01");
end


function testConfigurationIdentityMismatchIsIncomplete(testCase)

    [cfg, configRow, cleanup] = ...
        localCreateConfiguration(); %#ok<ASGLU>

    summary = ...
        localBaseSummary(cfg, configRow);

    summary.ConfigId(:) = ...
        "m25p_a75p";

    summary.MusclePercent(:) = ...
        25;

    localWriteSummary( ...
        configRow, ...
        summary);

    result = ...
        soopt.evaluateFeasibility( ...
            configRow, ...
            cfg);

    verifyFalse(testCase, ...
        result.AssessmentComplete);

    verifyFalse(testCase, ...
        result.IsFeasible);

    verifyEqual(testCase, ...
        result.Status, ...
        "INCOMPLETE_CONFIG_IDENTITY_MISMATCH");
end


function [cfg, configRow, cleanup] = localCreateConfiguration()

    root = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_strength_feasibility_" + ...
            string(java.util.UUID.randomUUID())));

    mkdir(root);

    cleanup = ...
        onCleanup(@() localRemoveTree(root));

    cfg = struct;

    cfg.outputRoot = ...
        root;

    cfg.conditions = ...
        [0 15];

    cfg.trials = ...
        [1 2];

    configRoot = ...
        string(fullfile( ...
            root, ...
            "static_optimization_configs", ...
            "m50p_a75p"));

    batchQcDirectory = ...
        string(fullfile( ...
            configRoot, ...
            "batch_qc"));

    mkdir(batchQcDirectory);

    configRow = ...
        table( ...
            "m50p_a75p", ...
            50, ...
            75, ...
            string(fullfile( ...
                batchQcDirectory, ...
                "process_4_static_optimization_summary.csv")), ...
            'VariableNames', { ...
                'ConfigId', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'Process4SummaryCsv'});
end


function summary = localBaseSummary(cfg, configRow)

    [conditionGrid, trialGrid] = ...
        ndgrid( ...
            cfg.conditions, ...
            cfg.trials);

    ConditionDeg = ...
        conditionGrid(:);

    TrialNumber = ...
        trialGrid(:);

    nRows = ...
        numel(ConditionDeg);

    ConfigId = ...
        repmat( ...
            string(configRow.ConfigId), ...
            nRows, ...
            1);

    MusclePercent = ...
        repmat( ...
            double(configRow.MusclePercent), ...
            nRows, ...
            1);

    ActuatorPercent = ...
        repmat( ...
            double(configRow.ActuatorPercent), ...
            nRows, ...
            1);

    Status = ...
        repmat( ...
            "completed", ...
            nRows, ...
            1);

    Succeeded = ...
        true(nRows,1);

    OutputAuditPassed = ...
        true(nRows,1);

    summary = ...
        table( ...
            ConditionDeg, ...
            TrialNumber, ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            Status, ...
            Succeeded, ...
            OutputAuditPassed);
end


function localWriteSummary(configRow, summary)

    summaryFile = ...
        string(configRow.Process4SummaryCsv);

    summaryDirectory = ...
        string(fileparts(summaryFile));

    if ~isfolder(summaryDirectory)

        mkdir(summaryDirectory);
    end

    writetable( ...
        summary, ...
        summaryFile);
end


function localRemoveTree(root)

    if isfolder(root)

        rmdir(root, "s");
    end
end
