function tests = test_project_config_contract
%TEST_PROJECT_CONFIG_CONTRACT Regression tests for canonical config fields.

    tests = functiontests(localfunctions);
end


function testVersionControlledDefaults(testCase)

    repositoryRoot = ...
        string(fileparts(fileparts(mfilename("fullpath"))));

    addpath(repositoryRoot);

    cfg = load_project_config( ...
        "RequireLocalConfig", false, ...
        "ValidatePaths", false);

    verifyEqual(testCase, ...
        cfg.conditions, ...
        [0 15 30 45]);

    verifyEqual(testCase, ...
        cfg.trials, ...
        1:5);

    verifyTrue(testCase, ...
        isfield(cfg, "batchProcessing"));

    verifyTrue(testCase, ...
        isfield(cfg.batchProcessing, "enableParallel"));

    verifyTrue(testCase, ...
        isfield(cfg.batchProcessing, "maxWorkers"));

    verifyFalse(testCase, ...
        isfield(cfg, "enableParallel"));

    verifyFalse(testCase, ...
        isfield(cfg, "maxWorkers"));
end


function testBatchSettingsHaveExpectedTypes(testCase)

    repositoryRoot = ...
        string(fileparts(fileparts(mfilename("fullpath"))));

    addpath(repositoryRoot);

    cfg = load_project_config( ...
        "RequireLocalConfig", false, ...
        "ValidatePaths", false);

    verifyTrue(testCase, ...
        islogical(cfg.batchProcessing.enableParallel));

    verifyTrue(testCase, ...
        isnumeric(cfg.batchProcessing.maxWorkers));

    verifyGreaterThanOrEqual(testCase, ...
        cfg.batchProcessing.maxWorkers, ...
        1);

    verifyEqual(testCase, ...
        mod(cfg.batchProcessing.maxWorkers, 1), ...
        0);
end
