function tests = test_static_optimization_analysis_identity_columns
%TEST_STATIC_OPTIMIZATION_ANALYSIS_IDENTITY_COLUMNS Provenance column tests.

    tests = ...
        functiontests(localfunctions);
end


function testConfiguredColumnsArePrepended(testCase)

    inputTable = ...
        table( ...
            ["trial01"; "trial02"], ...
            [0; 15], ...
            [1.2; 2.3], ...
            "VariableNames", ...
                {'trial','condition_deg','peak_flexor_N'});

    context = ...
        localConfiguredContext();

    outputTable = ...
        pipeline.addStaticOptimizationAnalysisIdentityColumns( ...
            inputTable, ...
            context, ...
            true);

    expectedNames = [
        "config_id"
        "muscle_percent"
        "actuator_percent"
        "trial"
        "condition_deg"
        "peak_flexor_N"
    ];

    verifyEqual(testCase, ...
        string(outputTable.Properties.VariableNames), ...
        expectedNames.');

    verifyEqual(testCase, ...
        outputTable.config_id, ...
        repmat("m20p_a35p", 2, 1));

    verifyEqual(testCase, ...
        outputTable.muscle_percent, ...
        [20; 20]);

    verifyEqual(testCase, ...
        outputTable.actuator_percent, ...
        [35; 35]);

    verifyEqual(testCase, ...
        outputTable.trial, ...
        inputTable.trial);

    verifyEqual(testCase, ...
        outputTable.peak_flexor_N, ...
        inputTable.peak_flexor_N);
end


function testLegacyColumnsUseEmptyIdAndNaNPercentages(testCase)

    inputTable = ...
        table( ...
            [0; 15], ...
            [5; 5], ...
            "VariableNames", ...
                {'condition_deg','GroupCount'});

    context = ...
        localConfiguredContext();

    context.ConfigId = ...
        "";

    context.MusclePercent = ...
        NaN;

    context.ActuatorPercent = ...
        NaN;

    outputTable = ...
        pipeline.addStaticOptimizationAnalysisIdentityColumns( ...
            inputTable, ...
            context, ...
            true);

    verifyEqual(testCase, ...
        outputTable.config_id, ...
        repmat("", 2, 1));

    verifyTrue(testCase, ...
        all(isnan(outputTable.muscle_percent)));

    verifyTrue(testCase, ...
        all(isnan(outputTable.actuator_percent)));
end


function testDisabledReturnsInputUnchanged(testCase)

    inputTable = ...
        table( ...
            [1; 2], ...
            "VariableNames", ...
                {'value'});

    outputTable = ...
        pipeline.addStaticOptimizationAnalysisIdentityColumns( ...
            inputTable, ...
            localConfiguredContext(), ...
            false);

    verifyEqual(testCase, ...
        outputTable, ...
        inputTable);
end


function testEmptyTableKeepsTypedIdentityColumns(testCase)

    inputTable = ...
        table( ...
            'Size', ...
                [0 2], ...
            'VariableTypes', ...
                {'double','double'}, ...
            'VariableNames', ...
                {'condition_deg','GroupCount'});

    outputTable = ...
        pipeline.addStaticOptimizationAnalysisIdentityColumns( ...
            inputTable, ...
            localConfiguredContext(), ...
            true);

    verifyEqual(testCase, ...
        height(outputTable), ...
        0);

    verifyEqual(testCase, ...
        width(outputTable), ...
        5);

    verifyClass(testCase, ...
        outputTable.config_id, ...
        "string");

    verifyClass(testCase, ...
        outputTable.muscle_percent, ...
        "double");

    verifyClass(testCase, ...
        outputTable.actuator_percent, ...
        "double");
end


function testExistingIdentityColumnsAreRejected(testCase)

    inputTable = ...
        table;

    inputTable.config_id = ...
        "existing";

    verifyError(testCase, ...
        @() pipeline.addStaticOptimizationAnalysisIdentityColumns( ...
            inputTable, ...
            localConfiguredContext(), ...
            true), ...
        "SOAnalysisIdentity:ColumnsAlreadyPresent");
end


function testAnalysisScriptUsesIdentityColumnsForTargetExports(testCase)

    projectRoot = ...
        string(fileparts(fileparts(mfilename("fullpath"))));

    scriptFile = ...
        string(fullfile( ...
            projectRoot, ...
            "run_static_optimization_analysis.m"));

    verifyTrue(testCase, ...
        isfile(scriptFile));

    source = ...
        string(fileread(scriptFile));

    verifyTrue(testCase, ...
        contains(source, "normalizedExport"));

    verifyTrue(testCase, ...
        contains(source, "metricsExport"));

    verifyTrue(testCase, ...
        contains(source, "conditionSummaryExport"));

    verifyGreaterThanOrEqual(testCase, ...
        count( ...
            source, ...
            "pipeline.addStaticOptimizationAnalysisIdentityColumns"), ...
        3);
end


function context = localConfiguredContext()

    context = ...
        struct;

    context.ConfigId = ...
        "m20p_a35p";

    context.MusclePercent = ...
        20;

    context.ActuatorPercent = ...
        35;
end
