function tests = test_storage_retention_policy
%TEST_STORAGE_RETENTION_POLICY Tests storage policy and immediate SO cleanup.

    tests = functiontests(localfunctions);
end


function testMissingStorageConfigUsesConservativeDefaults(testCase)

    cfg = struct;

    policy = ...
        pipeline.resolveStorageRetentionPolicy(cfg);

    verifyTrue(testCase, ...
        policy.StaticOptimization.KeepControlsXml);

    verifyTrue(testCase, ...
        policy.StaticOptimization.KeepForceSto);

    verifyTrue(testCase, ...
        policy.SharedStaticOptimizationPrep.KeepHsfMotion);
end


function testConfiguredPolicyIsResolved(testCase)

    cfg = localConfiguredPolicy(false);

    policy = ...
        pipeline.resolveStorageRetentionPolicy(cfg);

    verifyFalse(testCase, ...
        policy.StaticOptimization.KeepControlsXml);

    verifyTrue(testCase, ...
        policy.StaticOptimization.KeepForceSto);

    verifyTrue(testCase, ...
        policy.SharedStaticOptimizationPrep.KeepBodyKinematics);

    verifyFalse(testCase, ...
        policy.SharedStaticOptimizationPrep.KeepQc);
end


function testUnknownSettingIsRejected(testCase)

    cfg = localConfiguredPolicy(false);

    cfg.storage.staticOptimization.notARealSetting = true;

    verifyError(testCase, ...
        @() pipeline.resolveStorageRetentionPolicy(cfg), ...
        "StorageRetention:UnknownSetting");
end


function testControlsXmlDeletedWhenPolicyDisablesRetention(testCase)

    [root, cleanup] = ...
        localTempDirectory(); %#ok<ASGLU>

    controlsFile = string(fullfile( ...
        root, ...
        "SO_00deg_trial01_StaticOptimization_controls.xml"));

    forceFile = string(fullfile( ...
        root, ...
        "SO_00deg_trial01_StaticOptimization_force.sto"));

    localTouch(controlsFile);
    localTouch(forceFile);

    cfg = localConfiguredPolicy(false);

    result = ...
        pipeline.applyStaticOptimizationRetention( ...
            cfg, ...
            root);

    verifyFalse(testCase, ...
        isfile(controlsFile));

    verifyTrue(testCase, ...
        isfile(forceFile));

    verifyEqual(testCase, ...
        result.ControlsXmlFilesFound, ...
        1);

    verifyEqual(testCase, ...
        result.ControlsXmlFilesDeleted, ...
        1);

    verifyEqual(testCase, ...
        result.ControlsXmlFilesRetained, ...
        0);
end


function testControlsXmlRetainedWhenPolicyRequiresIt(testCase)

    [root, cleanup] = ...
        localTempDirectory(); %#ok<ASGLU>

    controlsFile = string(fullfile( ...
        root, ...
        "SO_trial_StaticOptimization_controls.xml"));

    localTouch(controlsFile);

    cfg = localConfiguredPolicy(true);

    result = ...
        pipeline.applyStaticOptimizationRetention( ...
            cfg, ...
            root);

    verifyTrue(testCase, ...
        isfile(controlsFile));

    verifyEqual(testCase, ...
        result.ControlsXmlFilesDeleted, ...
        0);

    verifyEqual(testCase, ...
        result.ControlsXmlFilesRetained, ...
        1);
end


function testMultipleControlsFilesHandledDeterministically(testCase)

    [root, cleanup] = ...
        localTempDirectory(); %#ok<ASGLU>

    localTouch(fullfile( ...
        root, ...
        "A_StaticOptimization_controls.xml"));

    localTouch(fullfile( ...
        root, ...
        "B_StaticOptimization_controls.xml"));

    localTouch(fullfile( ...
        root, ...
        "unrelated.xml"));

    cfg = localConfiguredPolicy(false);

    result = ...
        pipeline.applyStaticOptimizationRetention( ...
            cfg, ...
            root);

    verifyEqual(testCase, ...
        result.ControlsXmlFilesFound, ...
        2);

    verifyEqual(testCase, ...
        result.ControlsXmlFilesDeleted, ...
        2);

    verifyTrue(testCase, ...
        isfile(fullfile( ...
            root, ...
            "unrelated.xml")));
end


function testProjectDefaultsExposeStoragePolicy(testCase)

    cfg = ...
        load_project_config( ...
            "RequireLocalConfig", ...
                false, ...
            "ValidatePaths", ...
                false);

    verifyTrue(testCase, ...
        isfield(cfg, "storage"));

    verifyFalse(testCase, ...
        cfg.storage.staticOptimization.keepControlsXml);

    verifyTrue(testCase, ...
        cfg.storage.staticOptimization.keepForceSto);

    verifyTrue(testCase, ...
        cfg.storage.sharedStaticOptimizationPrep.keepHsfMotion);
end


function testProcess4InvokesImmediateRetention(testCase)

    functionFile = ...
        which( ...
            "pipeline.runStaticOptimizationTrial");

    verifyNotEmpty(testCase, ...
        functionFile);

    source = ...
        string(fileread(functionFile));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "pipeline.applyStaticOptimizationRetention"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "result.RetentionResult"));
end


function cfg = localConfiguredPolicy(keepControlsXml)

    cfg = struct;

    cfg.storage = struct;

    cfg.storage.staticOptimization = ...
        struct( ...
            "keepControlsXml", logical(keepControlsXml), ...
            "keepSetupXml", true, ...
            "keepForceSto", true, ...
            "keepActivationSto", true, ...
            "keepQc", true, ...
            "keepCheckpoint", true);

    cfg.storage.sharedStaticOptimizationPrep = ...
        struct( ...
            "keepNeutralModelC", true, ...
            "keepBodyKinematics", true, ...
            "keepComCsv", true, ...
            "keepEventTiming", true, ...
            "keepHsfMotion", true, ...
            "keepExternalLoadsXml", true, ...
            "keepQc", false, ...
            "keepCheckpoint", true);
end


function [root, cleanup] = localTempDirectory()

    root = string(fullfile( ...
        tempdir, ...
        "headneck_storage_retention_" + ...
        string(java.util.UUID.randomUUID())));

    mkdir(root);

    cleanup = ...
        onCleanup(@() localRemoveTree(root));
end


function localTouch(filePath)

    fid = fopen(filePath, "w");

    assert(fid >= 0, ...
        "StorageRetentionTest:FileCreateFailed", ...
        "Could not create test file:\n%s", ...
        string(filePath));

    cleaner = onCleanup(@() fclose(fid)); %#ok<NASGU>

    fprintf(fid, "test");
end


function localRemoveTree(root)

    if isfolder(root)
        rmdir(root, "s");
    end
end
