function tests = test_strength_configuration_feasibility_map
%TEST_STRENGTH_CONFIGURATION_FEASIBILITY_MAP Tests for grid visualization.

    tests = ...
        functiontests(localfunctions);
end


function testClassifiesAllPlotStates(testCase)

    T = ...
        localClassifiedTable();

    [fig, ax, info] = ...
        soopt.plotFeasibilityMap( ...
            T, ...
            "Visible", "off");

    cleanup = ...
        onCleanup(@() close(fig)); %#ok<NASGU>

    verifyEqual(testCase, ...
        info.TotalConfigurations, ...
        5);

    verifyEqual(testCase, ...
        info.IncompleteCount, ...
        1);

    verifyEqual(testCase, ...
        info.InfeasibleCount, ...
        1);

    verifyEqual(testCase, ...
        info.FeasibleDominatedCount, ...
        1);

    verifyEqual(testCase, ...
        info.ParetoOptimalCount, ...
        2);

    verifyEqual(testCase, ...
        info.IncompleteConfigIds, ...
        "m25p_a25p");

    verifyEqual(testCase, ...
        info.InfeasibleConfigIds, ...
        "m25p_a50p");

    verifyEqual(testCase, ...
        info.FeasibleDominatedConfigIds, ...
        "m50p_a75p");

    verifyEqual(testCase, ...
        info.ParetoOptimalConfigIds, ...
        [
            "m25p_a75p"
            "m50p_a50p"
        ]);

    verifyEqual(testCase, ...
        string(ax.XLabel.String), ...
        "Muscle strength (% target)");

    verifyEqual(testCase, ...
        string(ax.YLabel.String), ...
        "Reserve actuator strength (% target)");
end


function testLabelsCanBeDisabled(testCase)

    T = ...
        localClassifiedTable();

    [fig, ax] = ...
        soopt.plotFeasibilityMap( ...
            T, ...
            "Visible", "off", ...
            "ShowConfigLabels", false);

    cleanup = ...
        onCleanup(@() close(fig)); %#ok<NASGU>

    textObjects = ...
        findobj( ...
            ax, ...
            "Type", "text");

    % Axes title and labels are not children of the axes in the same way as
    % data annotations. Verify no ConfigId annotation was created.
    annotationStrings = ...
        strings(0,1);

    for iObject = 1:numel(textObjects)

        value = ...
            string(textObjects(iObject).String);

        if any(startsWith(strtrim(value), "m"))

            annotationStrings(end+1,1) = value; %#ok<AGROW>
        end
    end

    verifyEmpty(testCase, ...
        annotationStrings);
end


function testSingleParetoPointIsSupported(testCase)

    T = ...
        table( ...
            "m50p_a75p", ...
            50, ...
            75, ...
            true, ...
            true, ...
            true, ...
            'VariableNames', { ...
                'ConfigId', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'AssessmentComplete', ...
                'IsFeasible', ...
                'IsParetoOptimal'});

    [fig, ~, info] = ...
        soopt.plotFeasibilityMap( ...
            T, ...
            "Visible", "off");

    cleanup = ...
        onCleanup(@() close(fig)); %#ok<NASGU>

    verifyEqual(testCase, ...
        info.ParetoOptimalCount, ...
        1);

    verifyEqual(testCase, ...
        info.ParetoOptimalConfigIds, ...
        "m50p_a75p");
end


function testEmptyTableIsSupported(testCase)

    T = ...
        table( ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            false(0,1), ...
            false(0,1), ...
            false(0,1), ...
            'VariableNames', { ...
                'ConfigId', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'AssessmentComplete', ...
                'IsFeasible', ...
                'IsParetoOptimal'});

    [fig, ~, info] = ...
        soopt.plotFeasibilityMap( ...
            T, ...
            "Visible", "off");

    cleanup = ...
        onCleanup(@() close(fig)); %#ok<NASGU>

    verifyEqual(testCase, ...
        info.TotalConfigurations, ...
        0);

    verifyEqual(testCase, ...
        info.ParetoOptimalCount, ...
        0);
end


function testInvalidParetoStateRejected(testCase)

    T = ...
        table( ...
            "m25p_a25p", ...
            25, ...
            25, ...
            false, ...
            false, ...
            true, ...
            'VariableNames', { ...
                'ConfigId', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'AssessmentComplete', ...
                'IsFeasible', ...
                'IsParetoOptimal'});

    verifyError(testCase, ...
        @() soopt.plotFeasibilityMap( ...
            T, ...
            "Visible", "off"), ...
        "StrengthFeasibilityMap:InvalidParetoState");
end


function T = localClassifiedTable()

    ConfigId = [
        "m25p_a25p"
        "m25p_a50p"
        "m25p_a75p"
        "m50p_a50p"
        "m50p_a75p"
    ];

    MusclePercent = ...
        [25; 25; 25; 50; 50];

    ActuatorPercent = ...
        [25; 50; 75; 50; 75];

    AssessmentComplete = ...
        [false; true; true; true; true];

    IsFeasible = ...
        [false; false; true; true; true];

    IsParetoOptimal = ...
        [false; false; true; true; false];

    T = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            AssessmentComplete, ...
            IsFeasible, ...
            IsParetoOptimal);
end
