classdef TestHsfHelpers < matlab.unittest.TestCase
%TESTHSFHELPERS Unit tests for HSF mechanics and file construction.
%
% The class name and filename deliberately follow MATLAB's conventional
% Test*.m pattern. All helper methods are contained inside the class for
% compatibility with MATLAB releases that reject local functions after a
% classdef block.

    methods (Test)

        function zeroDegreeForce(testCase)

            result = hsf.computeForceComponents( ...
                1.1704014720812095, -9.80665, 0, 37);

            testCase.verifyEqual( ...
                result.ForceX, 0, 'AbsTol', 1e-12);

            testCase.verifyEqual( ...
                result.ForceZ, 0, 'AbsTol', 1e-12);

            testCase.verifyEqual( ...
                result.ForceY, ...
                result.WeightMagnitudeN, ...
                'AbsTol', 1e-12);

            testCase.verifyEqual( ...
                result.ForceMagnitudeN, ...
                result.WeightMagnitudeN, ...
                'AbsTol', 1e-12);

            testCase.verifyTrue(result.ComponentCheckPassed);
        end

        function fortyFiveDegreeForce(testCase)

            result = hsf.computeForceComponents( ...
                1.1704014720812095, -9.80665, 45, 0);

            testCase.verifyEqual( ...
                result.ForceX, ...
                result.WeightMagnitudeN, ...
                'AbsTol', 1e-10);

            testCase.verifyEqual( ...
                result.ForceY, ...
                result.WeightMagnitudeN, ...
                'AbsTol', 1e-10);

            testCase.verifyEqual( ...
                result.ForceZ, 0, ...
                'AbsTol', 1e-10);

            testCase.verifyEqual( ...
                result.ForceMagnitudeN, ...
                result.WeightMagnitudeN / cosd(45), ...
                'AbsTol', 1e-10);

            testCase.verifyTrue(result.ComponentCheckPassed);
        end

        function azimuthAtNinetyDegrees(testCase)

            result = hsf.computeForceComponents( ...
                1, -9.80665, 30, 90);

            testCase.verifyEqual( ...
                result.ForceX, 0, ...
                'AbsTol', 1e-12);

            testCase.verifyEqual( ...
                result.ForceZ, ...
                result.RadialMagnitudeN, ...
                'AbsTol', 1e-12);
        end

        function supportEnvelope(testCase)

            time = (0:0.001:2).';

            result = hsf.makeSupportEnvelope( ...
                time, ...
                'OffIntervals', [0.8, 1.2], ...
                'RampDuration', 0.1, ...
                'RampShape', 'linear');

            index08 = TestHsfHelpers.nearestIndex(time, 0.8);
            index10 = TestHsfHelpers.nearestIndex(time, 1.0);
            index12 = TestHsfHelpers.nearestIndex(time, 1.2);
            index07 = TestHsfHelpers.nearestIndex(time, 0.7);
            index13 = TestHsfHelpers.nearestIndex(time, 1.3);
            index075 = TestHsfHelpers.nearestIndex(time, 0.75);
            index125 = TestHsfHelpers.nearestIndex(time, 1.25);

            testCase.verifyEqual( ...
                result.Envelope(index08), 0, ...
                'AbsTol', 1e-12);

            testCase.verifyEqual( ...
                result.Envelope(index10), 0, ...
                'AbsTol', 1e-12);

            testCase.verifyEqual( ...
                result.Envelope(index12), 0, ...
                'AbsTol', 1e-12);

            testCase.verifyEqual( ...
                result.Envelope(index07), 1, ...
                'AbsTol', 1e-12);

            testCase.verifyEqual( ...
                result.Envelope(index13), 1, ...
                'AbsTol', 1e-12);

            testCase.verifyEqual( ...
                result.Envelope(index075), 0.5, ...
                'AbsTol', 1e-12);

            testCase.verifyEqual( ...
                result.Envelope(index125), 0.5, ...
                'AbsTol', 1e-12);
        end

        function comResampling(testCase)

            com = struct;
            com.Time = (0:0.01:0.1).';
            com.X = com.Time;
            com.Y = 2 * com.Time;
            com.Z = -com.Time;

            result = hsf.resampleCom( ...
                com, ...
                1000, ...
                'InterpolationMethod', 'linear');

            testCase.verifyEqual(numel(result.Time), 101);

            testCase.verifyEqual( ...
                result.Time(2) - result.Time(1), ...
                0.001, ...
                'AbsTol', 1e-14);

            testCase.verifyEqual( ...
                result.X, ...
                result.Time, ...
                'AbsTol', 1e-12);

            testCase.verifyEqual( ...
                result.Y, ...
                2 * result.Time, ...
                'AbsTol', 1e-12);
        end

        function buildMotion(testCase)

            time = (0:0.001:0.01).';

            com = struct;
            com.Time = time;
            com.X = ones(size(time));
            com.Y = 2 * ones(size(time));
            com.Z = 3 * ones(size(time));

            force = hsf.computeForceComponents( ...
                1, -9.80665, 0, 0);

            envelope = ones(size(time));

            built = hsf.buildMotion( ...
                com, force, envelope);

            testCase.verifyEqual( ...
                size(built.Motion.Data), ...
                [11, 7]);

            testCase.verifyEqual( ...
                built.Motion.Labels(1), ...
                "time");

            testCase.verifyEqual( ...
                built.Motion.Labels(2), ...
                "ground_force_1_vx");

            testCase.verifyEqual( ...
                built.Motion.Data(:,5), ...
                ones(size(time)));

            testCase.verifyEqual( ...
                built.Motion.Data(:,6), ...
                2 * ones(size(time)));

            testCase.verifyEqual( ...
                built.Motion.Data(:,7), ...
                3 * ones(size(time)));

            validation = hsf.validateMotion( ...
                built.Motion, ...
                'ExpectedRateHz', 1000);

            testCase.verifyTrue(validation.Passed);
        end
    end

    methods (Static, Access = private)

        function index = nearestIndex(values, target)

            [~, index] = min(abs(values - target));
        end
    end
end
