function tests = test_static_optimization_activation_audit
%TEST_STATIC_OPTIMIZATION_ACTIVATION_AUDIT Tests SO saturation detection.

    tests = ...
        functiontests(localfunctions);
end


function testUnsaturatedFilePasses(testCase)

    [filePath, cleanup] = ...
        localWriteActivationSto( ...
            [ ...
                0.00  0.20  0.30
                0.01  0.40 -0.50
                0.02  0.60  0.70
            ], ...
            ["time" "muscle_1" "reserve_1"]); %#ok<ASGLU>

    audit = ...
        opensimrun.auditStaticOptimizationActivations( ...
            filePath);

    verifyEqual(testCase, ...
        audit.SchemaVersion, ...
        2);

    verifyEqual(testCase, ...
        audit.SaturationThreshold, ...
        0.999, ...
        "AbsTol", ...
        1e-12);

    verifyFalse(testCase, ...
        isfield(audit, "SaturationLimit"));

    verifyFalse(testCase, ...
        isfield(audit, "SaturationTolerance"));

    verifyTrue(testCase, ...
        audit.Passed);

    verifyEqual(testCase, ...
        audit.SaturatedValueCount, ...
        0);

    verifyEqual(testCase, ...
        audit.SaturatedChannelCount, ...
        0);

    verifyEmpty(testCase, ...
        audit.SaturatedLabels);

    verifyEqual(testCase, ...
        audit.PeakAbsoluteActivation, ...
        0.70, ...
        "AbsTol", ...
        1e-12);

    verifyEqual(testCase, ...
        audit.PeakLabel, ...
        "reserve_1");

    verifyEqual(testCase, ...
        audit.PeakTime, ...
        0.02, ...
        "AbsTol", ...
        1e-12);
end


function testPositiveSaturationFails(testCase)

    [filePath, cleanup] = ...
        localWriteActivationSto( ...
            [ ...
                0.00  0.25
                0.01  1.00
                0.02  0.40
            ], ...
            ["time" "muscle_1"]); %#ok<ASGLU>

    audit = ...
        opensimrun.auditStaticOptimizationActivations( ...
            filePath);

    verifyFalse(testCase, ...
        audit.Passed);

    verifyEqual(testCase, ...
        audit.SaturatedValueCount, ...
        1);

    verifyEqual(testCase, ...
        audit.SaturatedChannelCount, ...
        1);

    verifyEqual(testCase, ...
        audit.SaturatedLabels, ...
        "muscle_1");

    verifyEqual(testCase, ...
        audit.FirstSaturationTime, ...
        0.01, ...
        "AbsTol", ...
        1e-12);
end


function testNegativeSaturationAlsoFails(testCase)

    [filePath, cleanup] = ...
        localWriteActivationSto( ...
            [ ...
                0.00  0.10
                0.01 -1.00
                0.02 -0.30
            ], ...
            ["time" "reserve_1"]); %#ok<ASGLU>

    audit = ...
        opensimrun.auditStaticOptimizationActivations( ...
            filePath);

    verifyFalse(testCase, ...
        audit.Passed);

    verifyEqual(testCase, ...
        audit.PeakActivationValue, ...
        -1.00, ...
        "AbsTol", ...
        1e-12);

    verifyEqual(testCase, ...
        audit.PeakAbsoluteActivation, ...
        1.00, ...
        "AbsTol", ...
        1e-12);
end


function testValueAtThresholdFails(testCase)

    [filePath, cleanup] = ...
        localWriteActivationSto( ...
            [ ...
                0.00  0.20
                0.01  0.999
                0.02  0.40
            ], ...
            ["time" "muscle_1"]); %#ok<ASGLU>

    audit = ...
        opensimrun.auditStaticOptimizationActivations( ...
            filePath, ...
            "SaturationThreshold", ...
            0.999);

    verifyFalse(testCase, ...
        audit.Passed);
end


function testValueBelowThresholdPasses(testCase)

    [filePath, cleanup] = ...
        localWriteActivationSto( ...
            [ ...
                0.00  0.20
                0.01  0.998
                0.02  0.40
            ], ...
            ["time" "muscle_1"]); %#ok<ASGLU>

    audit = ...
        opensimrun.auditStaticOptimizationActivations( ...
            filePath, ...
            "SaturationThreshold", ...
            0.999);

    verifyTrue(testCase, ...
        audit.Passed);
end


function testMultipleChannelsProduceChannelDiagnostics(testCase)

    [filePath, cleanup] = ...
        localWriteActivationSto( ...
            [ ...
                0.00  0.20  0.30  0.10
                0.01  1.00  0.40 -1.00
                0.02  1.00  0.50 -0.80
            ], ...
            [ ...
                "time"
                "muscle_1"
                "muscle_2"
                "reserve_1"
            ]); %#ok<ASGLU>

    audit = ...
        opensimrun.auditStaticOptimizationActivations( ...
            filePath);

    verifyFalse(testCase, ...
        audit.Passed);

    verifyEqual(testCase, ...
        audit.SaturatedChannelCount, ...
        2);

    verifyEqual(testCase, ...
        audit.SaturatedValueCount, ...
        3);

    verifyEqual(testCase, ...
        audit.SaturatedLabels, ...
        [ ...
            "muscle_1"
            "reserve_1"
        ]);

    muscleRow = ...
        audit.ChannelSummary.Label == ...
        "muscle_1";

    verifyEqual(testCase, ...
        audit.ChannelSummary.SaturatedSampleCount(muscleRow), ...
        2);

    verifyEqual(testCase, ...
        audit.ChannelSummary.FirstSaturationTime(muscleRow), ...
        0.01, ...
        "AbsTol", ...
        1e-12);

    verifyEqual(testCase, ...
        audit.ChannelSummary.LastSaturationTime(muscleRow), ...
        0.02, ...
        "AbsTol", ...
        1e-12);
end


function testCustomThresholdIsSupported(testCase)

    [filePath, cleanup] = ...
        localWriteActivationSto( ...
            [ ...
                0.00  0.70
                0.01  0.80
                0.02  0.75
            ], ...
            ["time" "muscle_1"]); %#ok<ASGLU>

    audit = ...
        opensimrun.auditStaticOptimizationActivations( ...
            filePath, ...
            "SaturationThreshold", ...
            0.8);

    verifyFalse(testCase, ...
        audit.Passed);

    verifyEqual(testCase, ...
        audit.SaturationThreshold, ...
        0.8, ...
        "AbsTol", ...
        1e-12);
end


function testNoActivationChannelsRejected(testCase)

    [filePath, cleanup] = ...
        localWriteActivationSto( ...
            [ ...
                0.00
                0.01
                0.02
            ], ...
            "time"); %#ok<ASGLU>

    verifyError(testCase, ...
        @() opensimrun.auditStaticOptimizationActivations( ...
            filePath), ...
        "StaticOptimizationActivationAudit:NoActivationChannels");
end


function testInvalidThresholdRejected(testCase)

    [filePath, cleanup] = ...
        localWriteActivationSto( ...
            [ ...
                0.00  0.20
                0.01  0.30
            ], ...
            ["time" "muscle_1"]); %#ok<ASGLU>

    verifyError(testCase, ...
        @() opensimrun.auditStaticOptimizationActivations( ...
            filePath, ...
            "SaturationThreshold", ...
            0), ...
        "StaticOptimizationActivationAudit:InvalidThreshold");
end


function [filePath, cleanup] = ...
        localWriteActivationSto(data, labels)

    root = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_so_activation_audit_" + ...
            string(java.util.UUID.randomUUID())));

    mkdir(root);

    cleanup = ...
        onCleanup(@() localRemoveTree(root));

    filePath = ...
        string(fullfile( ...
            root, ...
            "test_StaticOptimization_activation.sto"));

    fid = ...
        fopen(filePath, "w");

    assert(fid >= 0, ...
        "StaticOptimizationActivationAuditTest:FileCreateFailed", ...
        "Could not create synthetic STO:\n%s", ...
        filePath);

    cleaner = ...
        onCleanup(@() fclose(fid)); %#ok<NASGU>

    fprintf(fid, "name test_activation\n");
    fprintf(fid, "nRows=%d\n", size(data,1));
    fprintf(fid, "nColumns=%d\n", size(data,2));
    fprintf(fid, "endheader\n");

    fprintf( ...
        fid, ...
        "%s\n", ...
        strjoin( ...
            string(labels(:)).', ...
            sprintf('\t')));

    format = ...
        strjoin( ...
            repmat("%.12g", 1, size(data,2)), ...
            "\t") + ...
        "\n";

    for iRow = 1:size(data,1)

        fprintf( ...
            fid, ...
            format, ...
            data(iRow,:));
    end
end


function localRemoveTree(root)

    if isfolder(root)
        rmdir(root, "s");
    end
end
