function tests = test_strength_configuration_discovery
%TEST_STRENGTH_CONFIGURATION_DISCOVERY Contract tests for grid discovery.
%
% These tests create temporary synthetic configuration trees; no OpenSim
% execution is required.

    tests = functiontests(localfunctions);
end


function testDiscoversCanonicalConfigurations(testCase)

    [cfg, cleanup] = localCreateSyntheticProject(); %#ok<ASGLU>

    localMakeStrengthConfigArtifacts( ...
        cfg, ...
        "m50p_a75p", ...
        true, ...
        true, ...
        true);

    localMakeStrengthConfigArtifacts( ...
        cfg, ...
        "m25p_a50p", ...
        true, ...
        false, ...
        false);

    T = soopt.discoverStrengthConfigurations(cfg);

    verifyEqual(testCase, ...
        height(T), ...
        2);

    verifyEqual(testCase, ...
        T.ConfigId, ...
        [
            "m25p_a50p"
            "m50p_a75p"
        ]);

    verifyEqual(testCase, ...
        T.MusclePercent, ...
        [
            25
            50
        ]);

    verifyEqual(testCase, ...
        T.ActuatorPercent, ...
        [
            50
            75
        ]);

    verifyTrue(testCase, ...
        all(T.Process4SummaryCsvExists));

    verifyEqual(testCase, ...
        T.Process4SummaryMatExists, ...
        [
            false
            true
        ]);

    verifyEqual(testCase, ...
        T.AnalysisExists, ...
        [
            false
            true
        ]);
end


function testIgnoresNoncanonicalDirectories(testCase)

    [cfg, cleanup] = localCreateSyntheticProject(); %#ok<ASGLU>

    localMakeStrengthConfigArtifacts( ...
        cfg, ...
        "m50p_a75p", ...
        false, ...
        false, ...
        false);

    collectionRoot = localCollectionRoot(cfg);

    mkdir(fullfile( ...
        collectionRoot, ...
        "archive"));

    mkdir(fullfile( ...
        collectionRoot, ...
        "m50_a75"));

    mkdir(fullfile( ...
        collectionRoot, ...
        "m0p_a75p"));

    T = soopt.discoverStrengthConfigurations(cfg);

    verifyEqual(testCase, ...
        height(T), ...
        1);

    verifyEqual(testCase, ...
        T.ConfigId, ...
        "m50p_a75p");
end


function testExpectedArtifactPathsAreDeterministic(testCase)

    [cfg, cleanup] = localCreateSyntheticProject(); %#ok<ASGLU>

    localMakeStrengthConfigArtifacts( ...
        cfg, ...
        "m25p_a75p", ...
        false, ...
        false, ...
        false);

    T = soopt.discoverStrengthConfigurations(cfg);

    configRoot = string(fullfile( ...
        localCollectionRoot(cfg), ...
        "m25p_a75p"));

    batchQcDirectory = string(fullfile( ...
        configRoot, ...
        "batch_qc"));

    verifyEqual(testCase, ...
        T.ConfigRoot, ...
        configRoot);

    verifyEqual(testCase, ...
        T.BatchQcDirectory, ...
        batchQcDirectory);

    verifyEqual(testCase, ...
        T.Process4SummaryCsv, ...
        string(fullfile( ...
            batchQcDirectory, ...
            "process_4_static_optimization_summary.csv")));

    verifyEqual(testCase, ...
        T.Process4SummaryMat, ...
        string(fullfile( ...
            batchQcDirectory, ...
            "process_4_static_optimization_summary.mat")));

    verifyEqual(testCase, ...
        T.AnalysisDirectory, ...
        string(fullfile( ...
            configRoot, ...
            "static_optimization_analysis")));

    verifyFalse(testCase, ...
        T.Process4SummaryCsvExists);

    verifyFalse(testCase, ...
        T.Process4SummaryMatExists);

    verifyFalse(testCase, ...
        T.AnalysisExists);
end


function testMissingCollectionRootReturnsEmptyTable(testCase)

    [cfg, cleanup] = localCreateSyntheticProject(); %#ok<ASGLU>

    collectionRoot = localCollectionRoot(cfg);

    verifyFalse(testCase, ...
        isfolder(collectionRoot));

    T = soopt.discoverStrengthConfigurations(cfg);

    verifyEqual(testCase, ...
        height(T), ...
        0);

    verifyEqual(testCase, ...
        T.Properties.VariableNames, ...
        { ...
            'ConfigId', ...
            'MusclePercent', ...
            'ActuatorPercent', ...
            'ConfigRoot', ...
            'BatchQcDirectory', ...
            'Process4SummaryCsv', ...
            'Process4SummaryCsvExists', ...
            'Process4SummaryMat', ...
            'Process4SummaryMatExists', ...
            'AnalysisDirectory', ...
            'AnalysisExists'});
end


function testDiscoveryHasNoFilesystemSideEffects(testCase)

    [cfg, cleanup] = localCreateSyntheticProject(); %#ok<ASGLU>

    collectionRoot = localCollectionRoot(cfg);

    verifyFalse(testCase, ...
        isfolder(collectionRoot));

    soopt.discoverStrengthConfigurations(cfg);

    verifyFalse(testCase, ...
        isfolder(collectionRoot));
end


function testMissingOutputRootRejected(testCase)

    cfg = struct;

    cfg.outputRoot = string(fullfile( ...
        tempdir, ...
        "headneck_missing_strength_discovery_" + ...
        string(java.util.UUID.randomUUID())));

    verifyError(testCase, ...
        @() soopt.discoverStrengthConfigurations(cfg), ...
        "StrengthConfigDiscovery:OutputRootNotFound");
end


function [cfg, cleanup] = localCreateSyntheticProject()

    root = string(fullfile( ...
        tempdir, ...
        "headneck_strength_discovery_" + ...
        string(java.util.UUID.randomUUID())));

    mkdir(root);

    cleanup = onCleanup(@() localRemoveTree(root));

    cfg = struct;
    cfg.outputRoot = root;
end


function collectionRoot = localCollectionRoot(cfg)

    collectionRoot = string(fullfile( ...
        cfg.outputRoot, ...
        "static_optimization_configs"));
end


function localMakeStrengthConfigArtifacts( ...
        cfg, configId, includeCsv, includeMat, includeAnalysis)

    configRoot = string(fullfile( ...
        localCollectionRoot(cfg), ...
        configId));

    mkdir(configRoot);

    batchQcDirectory = string(fullfile( ...
        configRoot, ...
        "batch_qc"));

    if includeCsv || includeMat
        mkdir(batchQcDirectory);
    end

    if includeCsv
        localTouch(fullfile( ...
            batchQcDirectory, ...
            "process_4_static_optimization_summary.csv"));
    end

    if includeMat
        localTouch(fullfile( ...
            batchQcDirectory, ...
            "process_4_static_optimization_summary.mat"));
    end

    if includeAnalysis
        mkdir(fullfile( ...
            configRoot, ...
            "static_optimization_analysis"));
    end
end


function localTouch(filePath)

    [folder, ~, ~] = fileparts(filePath);

    if ~isfolder(folder)
        mkdir(folder);
    end

    fid = fopen(filePath, "w");

    assert(fid >= 0, ...
        "StrengthConfigDiscoveryTest:FileCreateFailed", ...
        "Could not create synthetic test file:\n%s", ...
        filePath);

    cleaner = onCleanup(@() fclose(fid)); %#ok<NASGU>

    fprintf(fid, "test\n");
end


function localRemoveTree(root)

    if isfolder(root)
        rmdir(root, "s");
    end
end
