function tests = test_resolve_strength_grid_search_controller_config
%TEST_RESOLVE_STRENGTH_GRID_SEARCH_CONTROLLER_CONFIG Resolver tests.

    tests = ...
        functiontests(localfunctions);
end


function testResolvesConfiguredValues(testCase)

    cfg = ...
        localFixture();

    controllerCfg = ...
        soopt.resolveStrengthGridSearchControllerConfig( ...
            cfg);

    verifyEqual(testCase, ...
        controllerCfg.SchemaVersion, ...
        1);

    verifyEqual(testCase, ...
        controllerCfg.ConfigDirectory, ...
        "D:\configs\fixed");

    verifyEqual(testCase, ...
        controllerCfg.SearchMode, ...
        "adaptive_boundary");

    verifyEqual(testCase, ...
        controllerCfg.BoundaryIncrementPercent, ...
        5);

    verifyEqual(testCase, ...
        controllerCfg.BoundaryMuscleBounds, ...
        [10 50]);

    verifyEqual(testCase, ...
        controllerCfg.BoundaryActuatorBounds, ...
        [5 75]);

    verifyEqual(testCase, ...
        controllerCfg.AdaptiveConfigDirectory, ...
        "D:\configs\adaptive");

    verifyEqual(testCase, ...
        controllerCfg.AdaptiveTemplateConfigFile, ...
        "D:\configs\template.json");

    verifyEqual(testCase, ...
        controllerCfg.MaxIterations, ...
        12);

    verifyTrue(testCase, ...
        controllerCfg.DryRun);

    verifyFalse(testCase, ...
        controllerCfg.OverwriteIncompleteConfiguration);

    verifyFalse(testCase, ...
        controllerCfg.WriteAnalysis);

    verifyEqual(testCase, ...
        controllerCfg.AnalysisOutputDirectory, ...
        "D:\analysis");

    verifyFalse(testCase, ...
        controllerCfg.ExportFigure);

    verifyEqual(testCase, ...
        controllerCfg.FigureResolution, ...
        300);

    verifyFalse(testCase, ...
        controllerCfg.WriteSearchHistory);

    verifyFalse(testCase, ...
        controllerCfg.PrintProgress);
end


function testNormalizesModePathsAndBounds(testCase)

    cfg = ...
        localFixture();

    cfg.optimization.staticOptimization.searchMode = ...
        "  FIXED_GRID  ";

    cfg.optimization.staticOptimization.fixedGrid.configDirectory = ...
        '  D:\fixed  ';

    cfg.optimization.staticOptimization.adaptiveBoundary.muscleBounds = ...
        [10; 40];

    cfg.optimization.staticOptimization.adaptiveBoundary.actuatorBounds = ...
        [];

    cfg.optimization.staticOptimization.adaptiveBoundary.configDirectory = ...
        '';

    cfg.optimization.staticOptimization.output.analysisDirectory = ...
        "   ";

    controllerCfg = ...
        soopt.resolveStrengthGridSearchControllerConfig( ...
            cfg);

    verifyEqual(testCase, ...
        controllerCfg.SearchMode, ...
        "fixed_grid");

    verifyEqual(testCase, ...
        controllerCfg.ConfigDirectory, ...
        "D:\fixed");

    verifyEqual(testCase, ...
        controllerCfg.BoundaryMuscleBounds, ...
        [10 40]);

    verifyEqual(testCase, ...
        controllerCfg.BoundaryActuatorBounds, ...
        zeros(1,0));

    verifyEqual(testCase, ...
        controllerCfg.AdaptiveConfigDirectory, ...
        "");

    verifyEqual(testCase, ...
        controllerCfg.AnalysisOutputDirectory, ...
        "");
end


function testNormalizesHybridMode(testCase)

    cfg = ...
        localFixture();

    cfg.optimization.staticOptimization.searchMode = ...
        "  FIXED_THEN_ADAPTIVE  ";

    controllerCfg = ...
        soopt.resolveStrengthGridSearchControllerConfig( ...
            cfg);

    verifyEqual(testCase, ...
        controllerCfg.SearchMode, ...
        "fixed_then_adaptive");
end


function testMissingOptimizationConfigFails(testCase)

    cfg = ...
        localFixture();

    cfg = ...
        rmfield( ...
            cfg, ...
            "optimization");

    verifyError(testCase, ...
        @() soopt.resolveStrengthGridSearchControllerConfig(cfg), ...
        "StrengthGridSearchConfig:OptimizationMissing");
end


function testMissingNestedFieldFails(testCase)

    cfg = ...
        localFixture();

    cfg.optimization.staticOptimization.adaptiveBoundary = ...
        rmfield( ...
            cfg.optimization.staticOptimization.adaptiveBoundary, ...
            "incrementPercent");

    verifyError(testCase, ...
        @() soopt.resolveStrengthGridSearchControllerConfig(cfg), ...
        "StrengthGridSearchConfig:AdaptiveBoundaryFieldsMissing");
end


function testInvalidModeFails(testCase)

    cfg = ...
        localFixture();

    cfg.optimization.staticOptimization.searchMode = ...
        "hybrid";

    verifyError(testCase, ...
        @() soopt.resolveStrengthGridSearchControllerConfig(cfg), ...
        "StrengthGridSearchConfig:InvalidSearchMode");
end


function testInvalidLogicalFails(testCase)

    cfg = ...
        localFixture();

    cfg.optimization.staticOptimization.dryRun = ...
        1;

    verifyError(testCase, ...
        @() soopt.resolveStrengthGridSearchControllerConfig(cfg), ...
        "StrengthGridSearchConfig:InvalidLogicalSetting");
end


function testInvalidIterationCountFails(testCase)

    cfg = ...
        localFixture();

    cfg.optimization.staticOptimization.maxIterations = ...
        2.5;

    verifyError(testCase, ...
        @() soopt.resolveStrengthGridSearchControllerConfig(cfg), ...
        "StrengthGridSearchConfig:InvalidPositiveInteger");
end


function testReversedBoundsFail(testCase)

    cfg = ...
        localFixture();

    cfg.optimization.staticOptimization.adaptiveBoundary.muscleBounds = ...
        [50 10];

    verifyError(testCase, ...
        @() soopt.resolveStrengthGridSearchControllerConfig(cfg), ...
        "StrengthGridSearchConfig:ReversedBounds");
end


function testEmptyDelegatedPathsAreAllowed(testCase)

    cfg = ...
        localFixture();

    cfg.optimization.staticOptimization.fixedGrid.configDirectory = ...
        "";

    cfg.optimization.staticOptimization.adaptiveBoundary.configDirectory = ...
        "";

    cfg.optimization.staticOptimization.adaptiveBoundary.templateConfigFile = ...
        "";

    cfg.optimization.staticOptimization.output.analysisDirectory = ...
        "";

    controllerCfg = ...
        soopt.resolveStrengthGridSearchControllerConfig( ...
            cfg);

    verifyEqual(testCase, ...
        controllerCfg.ConfigDirectory, ...
        "");

    verifyEqual(testCase, ...
        controllerCfg.AdaptiveConfigDirectory, ...
        "");

    verifyEqual(testCase, ...
        controllerCfg.AdaptiveTemplateConfigFile, ...
        "");

    verifyEqual(testCase, ...
        controllerCfg.AnalysisOutputDirectory, ...
        "");
end


function cfg = localFixture()

    cfg = ...
        struct;

    cfg.optimization = ...
        struct;

    cfg.optimization.staticOptimization = ...
        struct;

    searchCfg = ...
        cfg.optimization.staticOptimization;

    searchCfg.searchMode = ...
        "adaptive_boundary";

    searchCfg.maxIterations = ...
        12;

    searchCfg.dryRun = ...
        true;

    searchCfg.overwriteIncompleteConfiguration = ...
        false;

    searchCfg.fixedGrid = ...
        struct;

    searchCfg.fixedGrid.configDirectory = ...
        "D:\configs\fixed";

    searchCfg.adaptiveBoundary = ...
        struct;

    searchCfg.adaptiveBoundary.incrementPercent = ...
        5;

    searchCfg.adaptiveBoundary.muscleBounds = ...
        [10 50];

    searchCfg.adaptiveBoundary.actuatorBounds = ...
        [5 75];

    searchCfg.adaptiveBoundary.configDirectory = ...
        "D:\configs\adaptive";

    searchCfg.adaptiveBoundary.templateConfigFile = ...
        "D:\configs\template.json";

    searchCfg.output = ...
        struct;

    searchCfg.output.writeAnalysis = ...
        false;

    searchCfg.output.analysisDirectory = ...
        "D:\analysis";

    searchCfg.output.exportFigure = ...
        false;

    searchCfg.output.figureResolution = ...
        300;

    searchCfg.output.writeSearchHistory = ...
        false;

    searchCfg.printProgress = ...
        false;

    cfg.optimization.staticOptimization = ...
        searchCfg;
end
