function tests = test_strength_grid_analysis
%TEST_STRENGTH_GRID_ANALYSIS Tests top-level SO grid orchestration.

    tests = ...
        functiontests(localfunctions);
end


function testOrchestratesObservedParetoAndProposal(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject(); %#ok<ASGLU>

    localCreatePool( ...
        configDirectory, ...
        [25 50], ...
        [50 75]);

    localWriteConfigSummary( ...
        cfg, ...
        "m25p_a75p", ...
        25, ...
        75, ...
        true);

    localWriteConfigSummary( ...
        cfg, ...
        "m50p_a50p", ...
        50, ...
        50, ...
        true);

    localWriteConfigSummary( ...
        cfg, ...
        "m50p_a75p", ...
        50, ...
        75, ...
        true);

    result = ...
        soopt.analyzeStrengthGrid( ...
            cfg, ...
            "CreateFigure", ...
            false);

    verifyEqual(testCase, ...
        result.SchemaVersion, ...
        1);

    verifyTrue(testCase, ...
        result.PlanningAvailable);

    verifyEqual(testCase, ...
        result.PlanningStatus, ...
        "AVAILABLE");

    verifyTrue(testCase, ...
        result.MonotonicityAudit.IsMonotonic);

    verifyEqual(testCase, ...
        result.ParetoFrontier.ConfigId, ...
        [ ...
            "m25p_a75p"
            "m50p_a50p"
        ]);

    verifyEqual(testCase, ...
        result.Proposals.ConfigId, ...
        "m25p_a50p");

    verifyEqual(testCase, ...
        height(result.GridPlan), ...
        4);

    verifyEqual(testCase, ...
        result.ConfigPool.DiscoveredConfigurationCount, ...
        4);
end


function testParetoFrontierContainsOnlyObservedFeasibleRows(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject(); %#ok<ASGLU>

    localCreatePool( ...
        configDirectory, ...
        [25 50], ...
        [50 75]);

    localWriteConfigSummary( ...
        cfg, ...
        "m25p_a50p", ...
        25, ...
        50, ...
        true);

    result = ...
        soopt.analyzeStrengthGrid( ...
            cfg, ...
            "CreateFigure", ...
            false);

    verifyEqual(testCase, ...
        height(result.ParetoFrontier), ...
        1);

    verifyTrue(testCase, ...
        all(result.ParetoFrontier.AssessmentComplete));

    verifyTrue(testCase, ...
        all(result.ParetoFrontier.IsFeasible));

    verifyTrue(testCase, ...
        all(result.ParetoFrontier.IsParetoOptimal));

    inferredRows = ...
        startsWith( ...
            result.GridPlan.GridStatus, ...
            "INFERRED_");

    verifyGreaterThan(testCase, ...
        nnz(inferredRows), ...
        0);

    verifyFalse(testCase, ...
        any(ismember( ...
            result.GridPlan.ConfigId(inferredRows), ...
            result.ParetoFrontier.ConfigId)));
end


function testIncompleteConfigPoolWithholdsPlanning(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject(); %#ok<ASGLU>

    localTouchJson(configDirectory, "m25p_a50p.json");
    localTouchJson(configDirectory, "m25p_a75p.json");
    localTouchJson(configDirectory, "m50p_a50p.json");

    localWriteConfigSummary( ...
        cfg, ...
        "m25p_a75p", ...
        25, ...
        75, ...
        true);

    result = ...
        soopt.analyzeStrengthGrid( ...
            cfg, ...
            "CreateFigure", ...
            false);

    verifyFalse(testCase, ...
        result.ConfigPool.IsCompleteCartesianGrid);

    verifyFalse(testCase, ...
        result.PlanningAvailable);

    verifyEqual(testCase, ...
        result.PlanningStatus, ...
        "UNAVAILABLE_INCOMPLETE_CONFIG_POOL");

    verifyEqual(testCase, ...
        height(result.GridPlan), ...
        0);

    verifyEqual(testCase, ...
        height(result.Proposals), ...
        0);

    verifyEqual(testCase, ...
        height(result.ParetoFrontier), ...
        1);
end


function testMonotonicityViolationWithholdsPlanning(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject(); %#ok<ASGLU>

    localCreatePool( ...
        configDirectory, ...
        [25 50], ...
        [50 75]);

    localWriteConfigSummary( ...
        cfg, ...
        "m25p_a50p", ...
        25, ...
        50, ...
        true);

    localWriteConfigSummary( ...
        cfg, ...
        "m50p_a75p", ...
        50, ...
        75, ...
        false);

    result = ...
        soopt.analyzeStrengthGrid( ...
            cfg, ...
            "CreateFigure", ...
            false);

    verifyFalse(testCase, ...
        result.MonotonicityAudit.IsMonotonic);

    verifyEqual(testCase, ...
        result.MonotonicityAudit.ViolationCount, ...
        1);

    verifyFalse(testCase, ...
        result.PlanningAvailable);

    verifyEqual(testCase, ...
        result.PlanningStatus, ...
        "UNAVAILABLE_MONOTONICITY_VIOLATION");

    verifyEqual(testCase, ...
        height(result.Proposals), ...
        0);
end


function testPoolWithoutObservedRunsCanStillPropose(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject(); %#ok<ASGLU>

    localCreatePool( ...
        configDirectory, ...
        [25 50], ...
        [50 75]);

    result = ...
        soopt.analyzeStrengthGrid( ...
            cfg, ...
            "CreateFigure", ...
            false);

    verifyEqual(testCase, ...
        height(result.Summary), ...
        0);

    verifyEqual(testCase, ...
        height(result.ParetoFrontier), ...
        0);

    verifyTrue(testCase, ...
        result.PlanningAvailable);

    verifyEqual(testCase, ...
        height(result.GridPlan), ...
        4);

    verifyEqual(testCase, ...
        height(result.Proposals), ...
        1);

    verifyTrue(testCase, ...
        result.Proposals.PriorityRank == 1);
end


function testEmptyConfigPoolWithholdsPlanning(testCase)

    [cfg, ~, cleanup] = ...
        localCreateProject(); %#ok<ASGLU>

    result = ...
        soopt.analyzeStrengthGrid( ...
            cfg, ...
            "CreateFigure", ...
            false);

    verifyFalse(testCase, ...
        result.PlanningAvailable);

    verifyEqual(testCase, ...
        result.PlanningStatus, ...
        "UNAVAILABLE_EMPTY_CONFIG_POOL");

    verifyEqual(testCase, ...
        height(result.GridPlan), ...
        0);

    verifyEqual(testCase, ...
        height(result.Proposals), ...
        0);
end


function testMaxProposalsPassesThrough(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject(); %#ok<ASGLU>

    localCreatePool( ...
        configDirectory, ...
        [10 25 50], ...
        [25 50 75]);

    localWriteConfigSummary( ...
        cfg, ...
        "m25p_a50p", ...
        25, ...
        50, ...
        true);

    result = ...
        soopt.analyzeStrengthGrid( ...
            cfg, ...
            "MaxProposals", ...
            3, ...
            "CreateFigure", ...
            false);

    verifyEqual(testCase, ...
        height(result.Proposals), ...
        3);

    verifyEqual(testCase, ...
        result.Proposals.PriorityRank, ...
        [1; 2; 3]);
end


function testInvisibleFigureIsReturned(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject(); %#ok<ASGLU>

    localCreatePool( ...
        configDirectory, ...
        [25 50], ...
        [50 75]);

    localWriteConfigSummary( ...
        cfg, ...
        "m50p_a75p", ...
        50, ...
        75, ...
        true);

    result = ...
        soopt.analyzeStrengthGrid( ...
            cfg, ...
            "FigureVisible", ...
            "off");

    figureCleanup = ...
        onCleanup(@() close(result.Figure)); %#ok<NASGU>

    verifyTrue(testCase, ...
        isgraphics(result.Figure, "figure"));

    verifyTrue(testCase, ...
        isgraphics(result.Axes, "axes"));

    verifyEqual(testCase, ...
        result.PlotInfo.TotalConfigurations, ...
        1);

    verifyEqual(testCase, ...
        result.PlotInfo.ParetoOptimalCount, ...
        1);
end


function [cfg, configDirectory, cleanup] = localCreateProject()

    root = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_grid_analysis_" + ...
            string(java.util.UUID.randomUUID())));

    outputRoot = ...
        string(fullfile( ...
            root, ...
            "output"));

    configDirectory = ...
        string(fullfile( ...
            root, ...
            "force_configs"));

    mkdir(outputRoot);
    mkdir(configDirectory);

    cleanup = ...
        onCleanup(@() localRemoveTree(root));

    cfg = struct;

    cfg.outputRoot = ...
        outputRoot;

    cfg.conditions = ...
        [0 15];

    cfg.trials = ...
        1;

    cfg.forceCapacity = struct;

    cfg.forceCapacity.configFile = ...
        string(fullfile( ...
            root, ...
            "unrelated", ...
            "selected_profile.json"));

    cfg.optimization = struct;
    cfg.optimization.staticOptimization = struct;
    cfg.optimization.staticOptimization.fixedGrid = struct;
    cfg.optimization.staticOptimization.fixedGrid.configDirectory = ...
        configDirectory;
end


function localCreatePool(configDirectory, muscleGrid, actuatorGrid)

    for muscle = muscleGrid
        for actuator = actuatorGrid

            localTouchJson( ...
                configDirectory, ...
                localConfigId( ...
                    muscle, ...
                    actuator) + ...
                ".json");
        end
    end
end


function localWriteConfigSummary( ...
        cfg, configId, musclePercent, actuatorPercent, isFeasible)

    configRoot = ...
        string(fullfile( ...
            cfg.outputRoot, ...
            "static_optimization_configs", ...
            configId));

    batchQcDirectory = ...
        string(fullfile( ...
            configRoot, ...
            "batch_qc"));

    mkdir(batchQcDirectory);

    ConditionDeg = ...
        double(cfg.conditions(:));

    TrialNumber = ...
        repmat( ...
            double(cfg.trials(1)), ...
            numel(ConditionDeg), ...
            1);

    nRows = ...
        numel(ConditionDeg);

    ConfigId = ...
        repmat( ...
            string(configId), ...
            nRows, ...
            1);

    MusclePercent = ...
        repmat( ...
            double(musclePercent), ...
            nRows, ...
            1);

    ActuatorPercent = ...
        repmat( ...
            double(actuatorPercent), ...
            nRows, ...
            1);

    if isFeasible

        Succeeded = ...
            true(nRows,1);

        Status = ...
            repmat( ...
                "completed", ...
                nRows, ...
                1);

        OutputAuditPassed = ...
            true(nRows,1);

    else

        Succeeded = ...
            true(nRows,1);

        Succeeded(end) = ...
            false;

        Status = ...
            repmat( ...
                "completed", ...
                nRows, ...
                1);

        Status(end) = ...
            "activation_saturation";

        OutputAuditPassed = ...
            true(nRows,1);

        OutputAuditPassed(end) = ...
            false;
    end

    summary = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            ConditionDeg, ...
            TrialNumber, ...
            Succeeded, ...
            Status, ...
            OutputAuditPassed);

    summaryCsv = ...
        string(fullfile( ...
            batchQcDirectory, ...
            "process_4_static_optimization_summary.csv"));

    writetable( ...
        summary, ...
        summaryCsv);
end


function configId = localConfigId(musclePercent, actuatorPercent)

    configId = ...
        "m" + ...
        string(musclePercent) + ...
        "p_a" + ...
        compose("%02d", actuatorPercent) + ...
        "p";
end


function localTouchJson(directory, fileName)

    filePath = ...
        string(fullfile( ...
            directory, ...
            fileName));

    fid = ...
        fopen(filePath, "w");

    assert(fid >= 0, ...
        "StrengthGridAnalysisTest:FileCreateFailed", ...
        "Could not create synthetic JSON file:\n%s", ...
        filePath);

    cleaner = ...
        onCleanup(@() fclose(fid)); %#ok<NASGU>

    fprintf(fid, "{}\n");
end


function localRemoveTree(root)

    if isfolder(root)

        rmdir(root, "s");
    end
end
