function tests = test_strength_grid_replay
%TEST_STRENGTH_GRID_REPLAY Tests retrospective hybrid-policy replay.

    tests = ...
        functiontests(localfunctions);
end


function testReplayTransitionsAndResolvesDeterministically(testCase)

    outcomes = ...
        localOutcomeSummary( ...
            [ ...
                "m25p_a10p"
                "m25p_a20p"
                "m25p_a25p"
                "m25p_a30p" ...
            ], ...
            25 * ones(4,1), ...
            [10; 20; 25; 30], ...
            [false; false; true; true]);

    expectedConfigIds = [
        "m25p_a20p"
        "m25p_a30p"
        "m25p_a25p"
    ];

    replay1 = ...
        soopt.replayHybridStrengthSearch( ...
            outcomes, ...
            "FixedMuscleGrid", ...
                25, ...
            "FixedActuatorGrid", ...
                [10 20 30], ...
            "BoundaryIncrementPercent", ...
                5, ...
            "ExpectedConfigIds", ...
                expectedConfigIds);

    replay2 = ...
        soopt.replayHybridStrengthSearch( ...
            outcomes, ...
            "FixedMuscleGrid", ...
                25, ...
            "FixedActuatorGrid", ...
                [10 20 30], ...
            "BoundaryIncrementPercent", ...
                5);

    verifyEqual(testCase, ...
        replay1.StopStatus, ...
        "REPLAY_COMPLETE_BOUNDARY_RESOLVED");

    verifyEqual(testCase, ...
        replay1.SelectedConfigIds, ...
        expectedConfigIds);

    verifyEqual(testCase, ...
        replay1.Iterations.SearchPhase, ...
        [ ...
            "fixed"
            "fixed"
            "adaptive" ...
        ]);

    verifyEqual(testCase, ...
        replay1.ReplayedEvaluationCount, ...
        3);

    verifyEqual(testCase, ...
        replay1.FixedEvaluationCount, ...
        2);

    verifyEqual(testCase, ...
        replay1.AdaptiveEvaluationCount, ...
        1);

    verifyEqual(testCase, ...
        replay1.TransitionIteration, ...
        3);

    verifyTrue(testCase, ...
        replay1.SequenceMatchesExpected);

    verifyEqual(testCase, ...
        replay2.SelectedConfigIds, ...
        replay1.SelectedConfigIds);
end


function testReplayStopsWhenCounterfactualOutcomeIsUnavailable(testCase)

    outcomes = ...
        localOutcomeSummary( ...
            "m25p_a20p", ...
            25, ...
            20, ...
            false);

    replay = ...
        soopt.replayHybridStrengthSearch( ...
            outcomes, ...
            "FixedMuscleGrid", ...
                25, ...
            "FixedActuatorGrid", ...
                [10 20 30]);

    verifyEqual(testCase, ...
        replay.StopStatus, ...
        "REPLAY_STOPPED_OUTCOME_UNAVAILABLE");

    verifyEqual(testCase, ...
        replay.ReplayedEvaluationCount, ...
        1);

    verifyEqual(testCase, ...
        height(replay.Iterations), ...
        2);

    verifyEqual(testCase, ...
        replay.Iterations.Status, ...
        [ ...
            "replayed"
            "outcome_unavailable" ...
        ]);

    verifyFalse(testCase, ...
        replay.Iterations.OutcomeAvailable(2));
end


function testSeedEvidenceCanBeginInAdaptivePhase(testCase)

    outcomes = ...
        localOutcomeSummary( ...
            [ ...
                "m25p_a20p"
                "m25p_a25p"
                "m25p_a30p" ...
            ], ...
            25 * ones(3,1), ...
            [20; 25; 30], ...
            [false; true; true]);

    replay = ...
        soopt.replayHybridStrengthSearch( ...
            outcomes, ...
            "InitialConfigIds", ...
                ["m25p_a20p"; "m25p_a30p"], ...
            "FixedMuscleGrid", ...
                25, ...
            "FixedActuatorGrid", ...
                [20 30], ...
            "BoundaryIncrementPercent", ...
                5);

    verifyEqual(testCase, ...
        replay.StopStatus, ...
        "REPLAY_COMPLETE_BOUNDARY_RESOLVED");

    verifyEqual(testCase, ...
        replay.Iterations.SearchPhase, ...
        "adaptive");

    verifyEqual(testCase, ...
        replay.SelectedConfigIds, ...
        "m25p_a25p");

    verifyEqual(testCase, ...
        replay.TransitionIteration, ...
        1);
end


function testIncomparableSeedEvidenceDoesNotResolveBoundary(testCase)

    outcomes = ...
        localOutcomeSummary( ...
            [ ...
                "m30p_a20p"
                "m20p_a30p" ...
            ], ...
            [30; 20], ...
            [20; 30], ...
            [false; true]);

    replay = ...
        soopt.replayHybridStrengthSearch( ...
            outcomes, ...
            "InitialConfigIds", ...
                outcomes.ConfigId, ...
            "FixedMuscleGrid", ...
                [20 30], ...
            "FixedActuatorGrid", ...
                [20 30]);

    verifyEqual(testCase, ...
        replay.StopStatus, ...
        "REPLAY_STOPPED_HYBRID_BOUNDARY_UNBRACKETED");

    verifyFalse(testCase, ...
        replay.AdaptivePhaseReached);

    verifyEqual(testCase, ...
        replay.ReplayedEvaluationCount, ...
        0);
end


function testExpectedSequenceMismatchIsReported(testCase)

    outcomes = ...
        localOutcomeSummary( ...
            [ ...
                "m25p_a10p"
                "m25p_a20p"
                "m25p_a30p" ...
            ], ...
            25 * ones(3,1), ...
            [10; 20; 30], ...
            [false; false; true]);

    replay = ...
        soopt.replayHybridStrengthSearch( ...
            outcomes, ...
            "FixedMuscleGrid", ...
                25, ...
            "FixedActuatorGrid", ...
                [10 20 30], ...
            "ExpectedConfigIds", ...
                ["m25p_a10p"; "m25p_a30p"]);

    verifyFalse(testCase, ...
        replay.SequenceMatchesExpected);

    verifyEqual(testCase, ...
        replay.FirstMismatchIteration, ...
        1);

    verifyEqual(testCase, ...
        replay.Iterations.ExpectedConfigId(1), ...
        "m25p_a10p");

    verifyFalse(testCase, ...
        replay.Iterations.MatchesExpected(1));
end


function summary = localOutcomeSummary( ...
        configId, ...
        musclePercent, ...
        actuatorPercent, ...
        isFeasible)

    ConfigId = ...
        string(configId(:));

    MusclePercent = ...
        double(musclePercent(:));

    ActuatorPercent = ...
        double(actuatorPercent(:));

    AssessmentComplete = ...
        true(size(ConfigId));

    IsFeasible = ...
        logical(isFeasible(:));

    FeasibilityStatus = ...
        repmat( ...
            "INFEASIBLE", ...
            size(ConfigId));

    FeasibilityStatus(IsFeasible) = ...
        "FEASIBLE";

    summary = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            AssessmentComplete, ...
            IsFeasible, ...
            FeasibilityStatus);
end
