function tests = test_strength_configuration_summary
%TEST_STRENGTH_CONFIGURATION_SUMMARY Contract tests for grid summarization.
%
% These tests build temporary canonical configuration trees and synthetic
% Process-4 summary CSVs. No OpenSim execution is required.

    tests = ...
        functiontests(localfunctions);
end


function testSummarizesMixedConfigurationStates(testCase)

    [cfg, cleanup] = ...
        localCreateSyntheticProject(); %#ok<ASGLU>

    % Feasible configuration.
    row25_75 = ...
        localMakeConfig( ...
            cfg, ...
            "m25p_a75p");

    summary25_75 = ...
        localBaseProcess4Summary( ...
            cfg, ...
            row25_75);

    localWriteSummary( ...
        row25_75, ...
        summary25_75);

    % Infeasible configuration due to one SO failure.
    row50_50 = ...
        localMakeConfig( ...
            cfg, ...
            "m50p_a50p");

    summary50_50 = ...
        localBaseProcess4Summary( ...
            cfg, ...
            row50_50);

    failureRow = ...
        summary50_50.ConditionDeg == 15 & ...
        summary50_50.TrialNumber == 1;

    verifyEqual(testCase, ...
        nnz(failureRow), ...
        1);

    summary50_50.Succeeded(failureRow) = ...
        false;

    summary50_50.Status(failureRow) = ...
        "failed";

    summary50_50.OutputAuditPassed(failureRow) = ...
        false;

    localWriteSummary( ...
        row50_50, ...
        summary50_50);

    % Discovered but not yet evaluated: no Process-4 CSV.
    localMakeConfig( ...
        cfg, ...
        "m50p_a75p");

    T = ...
        soopt.summarizeStrengthConfigurations( ...
            cfg);

    verifyEqual(testCase, ...
        T.ConfigId, ...
        [
            "m25p_a75p"
            "m50p_a50p"
            "m50p_a75p"
        ]);

    row = ...
        T.ConfigId == "m25p_a75p";

    verifyTrue(testCase, ...
        T.AssessmentComplete(row));

    verifyTrue(testCase, ...
        T.IsFeasible(row));

    verifyEqual(testCase, ...
        T.FeasibilityStatus(row), ...
        "FEASIBLE");

    row = ...
        T.ConfigId == "m50p_a50p";

    verifyTrue(testCase, ...
        T.AssessmentComplete(row));

    verifyFalse(testCase, ...
        T.IsFeasible(row));

    verifyEqual(testCase, ...
        T.FeasibilityStatus(row), ...
        "INFEASIBLE_SO_FAILURE");

    verifyEqual(testCase, ...
        T.FailedTrials(row), ...
        1);

    verifyEqual(testCase, ...
        T.FailedTrialKeys(row), ...
        "15deg|trial01");

    row = ...
        T.ConfigId == "m50p_a75p";

    verifyFalse(testCase, ...
        T.AssessmentComplete(row));

    verifyFalse(testCase, ...
        T.IsFeasible(row));

    verifyEqual(testCase, ...
        T.FeasibilityStatus(row), ...
        "INCOMPLETE_MISSING_BATCH_SUMMARY");
end


function testPreservesDiscoveryMetadata(testCase)

    [cfg, cleanup] = ...
        localCreateSyntheticProject(); %#ok<ASGLU>

    configRow = ...
        localMakeConfig( ...
            cfg, ...
            "m50p_a75p");

    process4Summary = ...
        localBaseProcess4Summary( ...
            cfg, ...
            configRow);

    localWriteSummary( ...
        configRow, ...
        process4Summary);

    analysisDirectory = ...
        string(fullfile( ...
            configRow.ConfigRoot, ...
            "static_optimization_analysis"));

    mkdir(analysisDirectory);

    T = ...
        soopt.summarizeStrengthConfigurations( ...
            cfg);

    verifyEqual(testCase, ...
        height(T), ...
        1);

    verifyEqual(testCase, ...
        T.ConfigRoot, ...
        configRow.ConfigRoot);

    verifyEqual(testCase, ...
        T.Process4SummaryCsv, ...
        configRow.Process4SummaryCsv);

    verifyTrue(testCase, ...
        T.Process4SummaryCsvExists);

    verifyTrue(testCase, ...
        T.AnalysisExists);

    verifyEqual(testCase, ...
        T.AnalysisDirectory, ...
        analysisDirectory);
end


function testTrialKeyDiagnosticsAreFlattenedDeterministically(testCase)

    [cfg, cleanup] = ...
        localCreateSyntheticProject(); %#ok<ASGLU>

    configRow = ...
        localMakeConfig( ...
            cfg, ...
            "m25p_a50p");

    process4Summary = ...
        localBaseProcess4Summary( ...
            cfg, ...
            configRow);

    process4Summary.Succeeded(:) = ...
        false;

    process4Summary.Status(:) = ...
        "failed";

    process4Summary.OutputAuditPassed(:) = ...
        false;

    localWriteSummary( ...
        configRow, ...
        process4Summary);

    T = ...
        soopt.summarizeStrengthConfigurations( ...
            cfg);

    verifyEqual(testCase, ...
        T.FailedTrials, ...
        4);

    verifyEqual(testCase, ...
        T.FailedTrialKeys, ...
        "0deg|trial01;0deg|trial02;15deg|trial01;15deg|trial02");
end


function testMissingCollectionReturnsTypedEmptySummary(testCase)

    [cfg, cleanup] = ...
        localCreateSyntheticProject(); %#ok<ASGLU>

    T = ...
        soopt.summarizeStrengthConfigurations( ...
            cfg);

    verifyEqual(testCase, ...
        height(T), ...
        0);

    verifyEqual(testCase, ...
        T.Properties.VariableNames, ...
        { ...
            'ConfigId', ...
            'MusclePercent', ...
            'ActuatorPercent', ...
            'ConfigRoot', ...
            'BatchQcDirectory', ...
            'Process4SummaryCsv', ...
            'Process4SummaryCsvExists', ...
            'Process4SummaryMat', ...
            'Process4SummaryMatExists', ...
            'AnalysisDirectory', ...
            'AnalysisExists', ...
            'AssessmentComplete', ...
            'IsFeasible', ...
            'FeasibilityStatus', ...
            'FeasibilityReason', ...
            'ExpectedTrials', ...
            'SummaryRows', ...
            'UniqueTrialRows', ...
            'SucceededTrials', ...
            'FailedTrials', ...
            'OutputAuditPassedTrials', ...
            'OutputAuditFailedTrials', ...
            'MissingTrialKeys', ...
            'UnexpectedTrialKeys', ...
            'DuplicateTrialKeys', ...
            'FailedTrialKeys', ...
            'OutputAuditFailedTrialKeys'});
end


function testSummaryHasNoAdditionalFilesystemSideEffects(testCase)

    [cfg, cleanup] = ...
        localCreateSyntheticProject(); %#ok<ASGLU>

    configRow = ...
        localMakeConfig( ...
            cfg, ...
            "m50p_a75p");

    verifyFalse(testCase, ...
        isfolder(configRow.BatchQcDirectory));

    soopt.summarizeStrengthConfigurations( ...
        cfg);

    verifyFalse(testCase, ...
        isfolder(configRow.BatchQcDirectory));

    verifyFalse(testCase, ...
        isfolder(configRow.AnalysisDirectory));
end


function [cfg, cleanup] = localCreateSyntheticProject()

    root = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_strength_summary_" + ...
            string(java.util.UUID.randomUUID())));

    mkdir(root);

    cleanup = ...
        onCleanup(@() localRemoveTree(root));

    cfg = struct;

    cfg.outputRoot = ...
        root;

    cfg.conditions = ...
        [0 15];

    cfg.trials = ...
        [1 2];
end


function configRow = localMakeConfig(cfg, configId)

    info = ...
        pipeline.parseStrengthConfigName( ...
            configId + ".json");

    collectionRoot = ...
        string(fullfile( ...
            cfg.outputRoot, ...
            "static_optimization_configs"));

    configRoot = ...
        string(fullfile( ...
            collectionRoot, ...
            configId));

    mkdir(configRoot);

    batchQcDirectory = ...
        string(fullfile( ...
            configRoot, ...
            "batch_qc"));

    process4SummaryCsv = ...
        string(fullfile( ...
            batchQcDirectory, ...
            "process_4_static_optimization_summary.csv"));

    process4SummaryMat = ...
        string(fullfile( ...
            batchQcDirectory, ...
            "process_4_static_optimization_summary.mat"));

    analysisDirectory = ...
        string(fullfile( ...
            configRoot, ...
            "static_optimization_analysis"));

    configRow = ...
        table( ...
            info.ConfigId, ...
            info.MusclePercent, ...
            info.ActuatorPercent, ...
            configRoot, ...
            batchQcDirectory, ...
            process4SummaryCsv, ...
            false, ...
            process4SummaryMat, ...
            false, ...
            analysisDirectory, ...
            false, ...
            'VariableNames', { ...
                'ConfigId', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ConfigRoot', ...
                'BatchQcDirectory', ...
                'Process4SummaryCsv', ...
                'Process4SummaryCsvExists', ...
                'Process4SummaryMat', ...
                'Process4SummaryMatExists', ...
                'AnalysisDirectory', ...
                'AnalysisExists'});
end


function summary = localBaseProcess4Summary(cfg, configRow)

    [conditionGrid, trialGrid] = ...
        ndgrid( ...
            cfg.conditions, ...
            cfg.trials);

    ConditionDeg = ...
        conditionGrid(:);

    TrialNumber = ...
        trialGrid(:);

    nRows = ...
        numel(ConditionDeg);

    ConfigId = ...
        repmat( ...
            string(configRow.ConfigId), ...
            nRows, ...
            1);

    MusclePercent = ...
        repmat( ...
            double(configRow.MusclePercent), ...
            nRows, ...
            1);

    ActuatorPercent = ...
        repmat( ...
            double(configRow.ActuatorPercent), ...
            nRows, ...
            1);

    Status = ...
        repmat( ...
            "completed", ...
            nRows, ...
            1);

    Succeeded = ...
        true(nRows,1);

    OutputAuditPassed = ...
        true(nRows,1);

    summary = ...
        table( ...
            ConditionDeg, ...
            TrialNumber, ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            Status, ...
            Succeeded, ...
            OutputAuditPassed);
end


function localWriteSummary(configRow, summary)

    summaryFile = ...
        string(configRow.Process4SummaryCsv);

    summaryDirectory = ...
        string(fileparts(summaryFile));

    if ~isfolder(summaryDirectory)

        mkdir(summaryDirectory);
    end

    writetable( ...
        summary, ...
        summaryFile);
end


function localRemoveTree(root)

    if isfolder(root)

        rmdir(root, "s");
    end
end
