function tests = test_opensimio_normalize_motion_label
%TEST_OPENSIMIO_NORMALIZE_MOTION_LABEL Unit tests for label normalization.

    tests = ...
        functiontests( ...
            localfunctions);
end


function testTimeLabel(testCase)

    actual = ...
        opensimio.normalizeMotionLabel( ...
            " time ");

    verifyEqual( ...
        testCase, ...
        actual, ...
        "time");
end


function testBareCoordinateLabel(testCase)

    actual = ...
        opensimio.normalizeMotionLabel( ...
            "gndroll");

    verifyEqual( ...
        testCase, ...
        actual, ...
        "gndroll");
end


function testFullCoordinatePathWithValueSuffix(testCase)

    actual = ...
        opensimio.normalizeMotionLabel( ...
            "/jointset/c1c2/pitch1/value");

    verifyEqual( ...
        testCase, ...
        actual, ...
        "pitch1");
end


function testFullCoordinatePathWithoutValueSuffix(testCase)

    actual = ...
        opensimio.normalizeMotionLabel( ...
            "/jointset/c1c2/yaw1");

    verifyEqual( ...
        testCase, ...
        actual, ...
        "yaw1");
end


function testCaseInsensitiveTimeNormalization(testCase)

    actual = ...
        opensimio.normalizeMotionLabel( ...
            "TIME");

    verifyEqual( ...
        testCase, ...
        actual, ...
        "time");
end


function testTrailingSlash(testCase)

    actual = ...
        opensimio.normalizeMotionLabel( ...
            "/jointset/c1c2/roll1/");

    verifyEqual( ...
        testCase, ...
        actual, ...
        "roll1");
end


function testRejectsNonscalarStringArray(testCase)

    verifyError( ...
        testCase, ...
        @() opensimio.normalizeMotionLabel( ...
            ["pitch1", "pitch2"]), ...
        "opensimio:InvalidMotionLabel");
end
