function tests = test_strength_configuration_proposal
%TEST_STRENGTH_CONFIGURATION_PROPOSAL Tests adaptive grid proposals.

    tests = ...
        functiontests(localfunctions);
end


function testCurrentSingleFeasiblePointProposesBoundaryProbe(testCase)

    summary = ...
        localSummaryTable( ...
            "m50p_a75p", ...
            50, ...
            75, ...
            true, ...
            true);

    plan = ...
        soopt.buildStrengthGridPlan( ...
            summary, ...
            [25 50 75 100], ...
            [25 50 75 100]);

    proposals = ...
        soopt.proposeNextConfigurations( ...
            plan);

    verifyEqual(testCase, ...
        height(proposals), ...
        1);

    verifyEqual(testCase, ...
        proposals.ConfigId, ...
        "m50p_a50p");

    verifyEqual(testCase, ...
        proposals.FeasibleOutcomeResolvedCount, ...
        3);

    verifyEqual(testCase, ...
        proposals.InfeasibleOutcomeResolvedCount, ...
        4);

    verifyEqual(testCase, ...
        proposals.WorstCaseResolvedCount, ...
        3);

    verifyEqual(testCase, ...
        proposals.TotalResolutionPotential, ...
        7);
end


function testEmptyEvidenceChoosesBalancedCentralProbe(testCase)

    summary = ...
        localSummaryTable( ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            false(0,1), ...
            false(0,1));

    plan = ...
        soopt.buildStrengthGridPlan( ...
            summary, ...
            [25 50 75 100], ...
            [25 50 75 100]);

    proposals = ...
        soopt.proposeNextConfigurations( ...
            plan);

    % m50p_a75p and m75p_a50p are symmetric maximin ties.
    % Deterministic muscle-first ordering selects m50p_a75p.
    verifyEqual(testCase, ...
        proposals.ConfigId, ...
        "m50p_a75p");

    verifyEqual(testCase, ...
        proposals.FeasibleOutcomeResolvedCount, ...
        6);

    verifyEqual(testCase, ...
        proposals.InfeasibleOutcomeResolvedCount, ...
        6);

    verifyEqual(testCase, ...
        proposals.WorstCaseResolvedCount, ...
        6);
end


function testMultipleProposalsReturnRankedCandidates(testCase)

    summary = ...
        localSummaryTable( ...
            "m50p_a75p", ...
            50, ...
            75, ...
            true, ...
            true);

    plan = ...
        soopt.buildStrengthGridPlan( ...
            summary, ...
            [25 50 75 100], ...
            [25 50 75 100]);

    proposals = ...
        soopt.proposeNextConfigurations( ...
            plan, ...
            "MaxProposals", ...
            2);

    verifyEqual(testCase, ...
        height(proposals), ...
        2);

    verifyEqual(testCase, ...
        proposals.PriorityRank, ...
        [1; 2]);

    verifyEqual(testCase, ...
        proposals.ConfigId, ...
        [
            "m50p_a50p"
            "m75p_a25p"
        ]);
end


function testExistingIncompleteWinsExactRankingTie(testCase)

    plan = ...
        localPlanTable( ...
            [
                "m25p_a50p"
                "m50p_a25p"
            ], ...
            [25; 50], ...
            [50; 25], ...
            [true; false], ...
            ["UNKNOWN"; "UNKNOWN"], ...
            [true; true]);

    proposals = ...
        soopt.proposeNextConfigurations( ...
            plan);

    verifyEqual(testCase, ...
        proposals.ConfigId, ...
        "m25p_a50p");

    verifyTrue(testCase, ...
        proposals.ExistingIncomplete);
end


function testNoUnknownPointsReturnsEmptyTable(testCase)

    plan = ...
        localPlanTable( ...
            [
                "m25p_a25p"
                "m50p_a50p"
            ], ...
            [25; 50], ...
            [25; 50], ...
            [false; false], ...
            [ ...
                "ASSESSED_INFEASIBLE"
                "ASSESSED_FEASIBLE"
            ], ...
            [false; false]);

    proposals = ...
        soopt.proposeNextConfigurations( ...
            plan);

    verifyEqual(testCase, ...
        height(proposals), ...
        0);

    verifyEqual(testCase, ...
        proposals.Properties.VariableNames, ...
        { ...
            'PriorityRank', ...
            'ConfigId', ...
            'MusclePercent', ...
            'ActuatorPercent', ...
            'ExistingIncomplete', ...
            'FeasibleOutcomeResolvedCount', ...
            'InfeasibleOutcomeResolvedCount', ...
            'WorstCaseResolvedCount', ...
            'BestCaseResolvedCount', ...
            'TotalResolutionPotential', ...
            'ResolutionImbalance', ...
            'GridCenterDistance'});
end


function testMaxProposalsInfReturnsFullRanking(testCase)

    summary = ...
        localSummaryTable( ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            false(0,1), ...
            false(0,1));

    plan = ...
        soopt.buildStrengthGridPlan( ...
            summary, ...
            [25 50], ...
            [25 50]);

    proposals = ...
        soopt.proposeNextConfigurations( ...
            plan, ...
            "MaxProposals", ...
            Inf);

    verifyEqual(testCase, ...
        height(proposals), ...
        4);

    verifyEqual(testCase, ...
        proposals.PriorityRank, ...
        (1:4).');
end


function testInconsistentNeedsAssessmentStateRejected(testCase)

    plan = ...
        localPlanTable( ...
            "m50p_a50p", ...
            50, ...
            50, ...
            false, ...
            "INFERRED_FEASIBLE", ...
            true);

    verifyError(testCase, ...
        @() soopt.proposeNextConfigurations(plan), ...
        "StrengthProposal:InconsistentPlanState");
end


function T = localSummaryTable( ...
        configId, musclePercent, actuatorPercent, ...
        assessmentComplete, isFeasible)

    ConfigId = ...
        string(configId(:));

    MusclePercent = ...
        double(musclePercent(:));

    ActuatorPercent = ...
        double(actuatorPercent(:));

    AssessmentComplete = ...
        logical(assessmentComplete(:));

    IsFeasible = ...
        logical(isFeasible(:));

    T = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            AssessmentComplete, ...
            IsFeasible);
end


function T = localPlanTable( ...
        configId, musclePercent, actuatorPercent, ...
        existingIncomplete, gridStatus, needsAssessment)

    ConfigId = ...
        string(configId(:));

    MusclePercent = ...
        double(musclePercent(:));

    ActuatorPercent = ...
        double(actuatorPercent(:));

    ExistingIncomplete = ...
        logical(existingIncomplete(:));

    GridStatus = ...
        string(gridStatus(:));

    NeedsAssessment = ...
        logical(needsAssessment(:));

    T = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            ExistingIncomplete, ...
            GridStatus, ...
            NeedsAssessment);
end
