function tests = test_model_b_pipeline_contract
%TEST_MODEL_B_PIPELINE_CONTRACT Non-OpenSim contract tests for Process 2.
%
% These tests verify that the shared configuration, resolved trial context,
% Process-1 dependency paths, and Process-2 worker entry point remain
% aligned. They do not execute OpenSim.

    tests = functiontests(localfunctions);
end


function testModelBConfigExists(testCase)

    cfg = localLoadConfig();

    verifyTrue(testCase, ...
        isfield(cfg.pipeline, "modelB"));

    verifyTrue(testCase, ...
        isfield( ...
            cfg.pipeline.modelB, ...
            "lockWindowSec"));

    verifyEqual(testCase, ...
        cfg.pipeline.modelB.lockWindowSec, ...
        [0.10 0.15]);
end


function testRequiredQcNamespacesExist(testCase)

    cfg = localLoadConfig();

    verifyTrue(testCase, ...
        isfield(cfg.qc, "lockExtraction"));

    verifyTrue(testCase, ...
        isfield(cfg.qc, "lockExtractionFilter"));

    verifyTrue(testCase, ...
        isfield(cfg.qc, "lockAudit"));
end


function testResolvedContextContainsProcess2Dependencies(testCase)

    cfg = localLoadConfig();

    cfg.rawDataRoot = string(fullfile( ...
        tempdir, ...
        "headneck_raw_data"));

    cfg.outputRoot = string(fullfile( ...
        tempdir, ...
        "headneck_outputs"));

    trial = pipeline.resolveTrialContext( ...
        cfg, ...
        cfg.conditions(1), ...
        cfg.trials(1));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.Initialization, ...
            "CheckpointFile"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.Initialization, ...
            "ModelAFile"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.Initialization, ...
            "IkMotionFile"));

    verifyTrue(testCase, ...
        isfield(trial.Paths, "ModelB"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.ModelB, ...
            "FilteredInitialIkMotionFile"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.ModelB, ...
            "ModelBFile"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.ModelB, ...
            "FinalIkSetupFile"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.ModelB, ...
            "FinalIkMotionFile"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.ModelB, ...
            "CheckpointFile"));
end


function testResolvedContextContainsProcess2QcPaths(testCase)

    cfg = localLoadConfig();

    cfg.rawDataRoot = string(fullfile( ...
        tempdir, ...
        "headneck_raw_data"));

    cfg.outputRoot = string(fullfile( ...
        tempdir, ...
        "headneck_outputs"));

    trial = pipeline.resolveTrialContext( ...
        cfg, ...
        cfg.conditions(1), ...
        cfg.trials(1));

    requiredFields = [
        "LockFilterAuditCsv"
        "LockValuesCsv"
        "CoordinateConfigurationCsv"
        "ConstraintConfigurationCsv"
        "DependentCoordinateStateCsv"
        "IndependentSagittalStateCsv"
        "LockedCoordinateAuditCsv"
        "DependentOutOfPlaneSummaryCsv"
        "IndependentSagittalSummaryCsv"
        "DependentSagittalSummaryCsv"
        "SagittalSummaryCsv"
        "SagittalTrajectoriesCsv"
        "SagittalRelativeTrajectoriesCsv"
    ];

    verifyTrue(testCase, ...
        all(isfield( ...
            trial.Paths.ModelB, ...
            cellstr(requiredFields))));
end


function testSharedWorkerIsResolvable(testCase)

    workerFile = which( ...
        "pipeline.runModelBTrial");

    verifyNotEmpty(testCase, ...
        workerFile);
end


function cfg = localLoadConfig()

    repositoryRoot = ...
        string(fileparts(fileparts(mfilename("fullpath"))));

    addpath(repositoryRoot);

    cfg = load_project_config( ...
        "RequireLocalConfig", false, ...
        "ValidatePaths", false);
end
