function tests = test_static_optimization_checkpoint_compaction
%TEST_STATIC_OPTIMIZATION_CHECKPOINT_COMPACTION Tests compact P4 payloads.

    tests = ...
        functiontests(localfunctions);
end


function testRunResultDropsDuplicatedHeavyFields(testCase)

    runResult = ...
        localRunResult();

    activationAudit = ...
        localActivationAudit();

    [compactRun, ~] = ...
        pipeline.compactStaticOptimizationCheckpointData( ...
            runResult, ...
            activationAudit);

    verifyFalse(testCase, ...
        isfield(compactRun, "Tool"));

    verifyFalse(testCase, ...
        isfield(compactRun, "Model"));

    verifyFalse(testCase, ...
        isfield(compactRun, "OutputAudit"));

    verifyEqual(testCase, ...
        compactRun.ForceFile, ...
        runResult.ForceFile);

    verifyEqual(testCase, ...
        compactRun.ActivationFile, ...
        runResult.ActivationFile);

    verifyEqual(testCase, ...
        compactRun.RequestedTimeRange, ...
        runResult.RequestedTimeRange);
end


function testActivationAuditDropsChannelSummaryOnly(testCase)

    runResult = ...
        localRunResult();

    activationAudit = ...
        localActivationAudit();

    [~, compactAudit] = ...
        pipeline.compactStaticOptimizationCheckpointData( ...
            runResult, ...
            activationAudit);

    verifyFalse(testCase, ...
        isfield(compactAudit, "ChannelSummary"));

    summaryFields = [
        "SchemaVersion"
        "ActivationFile"
        "SaturationLimit"
        "SaturationTolerance"
        "SaturationThreshold"
        "Passed"
        "PeakAbsoluteActivation"
        "PeakActivationValue"
        "PeakLabel"
        "PeakTime"
        "SaturatedValueCount"
        "SaturatedChannelCount"
        "SaturatedLabels"
        "FirstSaturationTime"
        "LastSaturationTime"
    ];

    for fieldName = summaryFields.'

        verifyTrue(testCase, ...
            isfield( ...
                compactAudit, ...
                fieldName));
    end
end


function testEmptyActivationAuditIsSupported(testCase)

    [~, compactAudit] = ...
        pipeline.compactStaticOptimizationCheckpointData( ...
            localRunResult(), ...
            struct);

    verifyTrue(testCase, ...
        isstruct(compactAudit));

    verifyEmpty(testCase, ...
        fieldnames(compactAudit));
end


function testInputsAreNotModified(testCase)

    runResult = ...
        localRunResult();

    activationAudit = ...
        localActivationAudit();

    pipeline.compactStaticOptimizationCheckpointData( ...
        runResult, ...
        activationAudit);

    verifyTrue(testCase, ...
        isfield(runResult, "OutputAudit"));

    verifyTrue(testCase, ...
        isfield(activationAudit, "ChannelSummary"));
end


function testProcess4UsesCompactCheckpointPayload(testCase)

    functionFile = ...
        which( ...
            "pipeline.runStaticOptimizationTrial");

    verifyNotEmpty(testCase, ...
        functionFile);

    source = ...
        string(fileread(functionFile));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "pipeline.compactStaticOptimizationCheckpointData"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "checkpoint.SchemaVersion"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "checkpoint.OutputAudit"));

    verifyFalse(testCase, ...
        contains( ...
            source, ...
            '"-v7.3"'));
end


function runResult = localRunResult()

    OutputType = [
        "force"
        "activation"
    ];

    File = [
        "force.sto"
        "activation.sto"
    ];

    Passed = ...
        [true; true];

    outputAudit = ...
        table( ...
            OutputType, ...
            File, ...
            Passed);

    runResult = ...
        struct;

    runResult.SetupFile = ...
        "setup.xml";

    runResult.ToolName = ...
        "SO_trial01";

    runResult.ModelFile = ...
        "model.osim";

    runResult.CoordinatesFile = ...
        "ik.mot";

    runResult.ExternalLoadsFile = ...
        "external_loads.xml";

    runResult.ResultsDirectory = ...
        "results";

    runResult.RequestedTimeRange = ...
        [1 2];

    runResult.RunSucceeded = ...
        true;

    runResult.DurationSeconds = ...
        10;

    runResult.ForceFile = ...
        "force.sto";

    runResult.ActivationFile = ...
        "activation.sto";

    runResult.OutputAudit = ...
        outputAudit;

    runResult.Tool = ...
        struct("large", rand(100));

    runResult.Model = ...
        struct("large", rand(100));
end


function audit = localActivationAudit()

    Label = ...
        ["muscle1"; "muscle2"];

    PeakAbsoluteActivation = ...
        [0.5; 0.8];

    Saturated = ...
        [false; false];

    audit = ...
        struct;

    audit.SchemaVersion = ...
        1;

    audit.ActivationFile = ...
        "activation.sto";

    audit.SaturationLimit = ...
        1.0;

    audit.SaturationTolerance = ...
        1e-3;

    audit.SaturationThreshold = ...
        0.999;

    audit.Passed = ...
        true;

    audit.PeakAbsoluteActivation = ...
        0.8;

    audit.PeakActivationValue = ...
        0.8;

    audit.PeakLabel = ...
        "muscle2";

    audit.PeakTime = ...
        1.5;

    audit.SaturatedValueCount = ...
        0;

    audit.SaturatedChannelCount = ...
        0;

    audit.SaturatedLabels = ...
        strings(0,1);

    audit.FirstSaturationTime = ...
        NaN;

    audit.LastSaturationTime = ...
        NaN;

    audit.ChannelSummary = ...
        table( ...
            Label, ...
            PeakAbsoluteActivation, ...
            Saturated);
end
