function tests = test_strength_grid_plan
%TEST_STRENGTH_GRID_PLAN Contract tests for inference-based grid planning.

    tests = ...
        functiontests(localfunctions);
end


function testBuildsFullDeterministicGrid(testCase)

    summary = ...
        localSummaryTable( ...
            "m50p_a75p", ...
            50, ...
            75, ...
            true, ...
            true);

    plan = ...
        soopt.buildStrengthGridPlan( ...
            summary, ...
            [50 25], ...
            [75 25 50]);

    verifyEqual(testCase, ...
        height(plan), ...
        6);

    verifyEqual(testCase, ...
        plan.ConfigId, ...
        [
            "m25p_a25p"
            "m25p_a50p"
            "m25p_a75p"
            "m50p_a25p"
            "m50p_a50p"
            "m50p_a75p"
        ]);
end


function testAssessedFeasibleAndInferredFeasibleStates(testCase)

    summary = ...
        localSummaryTable( ...
            "m25p_a50p", ...
            25, ...
            50, ...
            true, ...
            true);

    plan = ...
        soopt.buildStrengthGridPlan( ...
            summary, ...
            [25 50], ...
            [25 50 75]);

    row = ...
        plan.ConfigId == "m25p_a50p";

    verifyEqual(testCase, ...
        plan.GridStatus(row), ...
        "ASSESSED_FEASIBLE");

    verifyFalse(testCase, ...
        plan.NeedsAssessment(row));

    row = ...
        plan.ConfigId == "m50p_a75p";

    verifyEqual(testCase, ...
        plan.GridStatus(row), ...
        "INFERRED_FEASIBLE");

    verifyFalse(testCase, ...
        plan.NeedsAssessment(row));

    verifyEqual(testCase, ...
        plan.FeasibleInferenceSources(row), ...
        "m25p_a50p");

    row = ...
        plan.ConfigId == "m25p_a25p";

    verifyEqual(testCase, ...
        plan.GridStatus(row), ...
        "UNKNOWN");

    verifyTrue(testCase, ...
        plan.NeedsAssessment(row));
end


function testAssessedInfeasibleAndInferredInfeasibleStates(testCase)

    summary = ...
        localSummaryTable( ...
            "m50p_a50p", ...
            50, ...
            50, ...
            true, ...
            false);

    plan = ...
        soopt.buildStrengthGridPlan( ...
            summary, ...
            [25 50 75], ...
            [25 50 75]);

    row = ...
        plan.ConfigId == "m50p_a50p";

    verifyEqual(testCase, ...
        plan.GridStatus(row), ...
        "ASSESSED_INFEASIBLE");

    verifyFalse(testCase, ...
        plan.NeedsAssessment(row));

    row = ...
        plan.ConfigId == "m25p_a25p";

    verifyEqual(testCase, ...
        plan.GridStatus(row), ...
        "INFERRED_INFEASIBLE");

    verifyFalse(testCase, ...
        plan.NeedsAssessment(row));

    verifyEqual(testCase, ...
        plan.InfeasibleInferenceSources(row), ...
        "m50p_a50p");

    row = ...
        plan.ConfigId == "m75p_a75p";

    verifyEqual(testCase, ...
        plan.GridStatus(row), ...
        "UNKNOWN");

    verifyTrue(testCase, ...
        plan.NeedsAssessment(row));
end


function testIncompleteExistingConfigurationCanStillBeInferred(testCase)

    summary = ...
        localSummaryTable( ...
            [
                "m25p_a50p"
                "m50p_a75p"
            ], ...
            [25; 50], ...
            [50; 75], ...
            [true; false], ...
            [true; false]);

    plan = ...
        soopt.buildStrengthGridPlan( ...
            summary, ...
            [25 50], ...
            [50 75]);

    row = ...
        plan.ConfigId == "m50p_a75p";

    verifyTrue(testCase, ...
        plan.ExistsInSummary(row));

    verifyTrue(testCase, ...
        plan.ExistingIncomplete(row));

    verifyFalse(testCase, ...
        plan.AssessmentComplete(row));

    verifyEqual(testCase, ...
        plan.GridStatus(row), ...
        "INFERRED_FEASIBLE");

    verifyFalse(testCase, ...
        plan.NeedsAssessment(row));
end


function testUnknownIncompleteConfigurationNeedsAssessment(testCase)

    summary = ...
        localSummaryTable( ...
            "m50p_a50p", ...
            50, ...
            50, ...
            false, ...
            false);

    plan = ...
        soopt.buildStrengthGridPlan( ...
            summary, ...
            [50], ...
            [50]);

    verifyTrue(testCase, ...
        plan.ExistsInSummary);

    verifyTrue(testCase, ...
        plan.ExistingIncomplete);

    verifyEqual(testCase, ...
        plan.GridStatus, ...
        "UNKNOWN");

    verifyTrue(testCase, ...
        plan.NeedsAssessment);
end


function testInferenceSourcesAreDeterministicallySorted(testCase)

    summary = ...
        localSummaryTable( ...
            [
                "m50p_a25p"
                "m25p_a50p"
                "m25p_a25p"
            ], ...
            [50; 25; 25], ...
            [25; 50; 25], ...
            [true; true; true], ...
            [true; true; true]);

    plan = ...
        soopt.buildStrengthGridPlan( ...
            summary, ...
            [25 50 75], ...
            [25 50 75]);

    row = ...
        plan.ConfigId == "m75p_a75p";

    verifyEqual(testCase, ...
        plan.FeasibleInferenceSources(row), ...
        "m25p_a25p;m25p_a50p;m50p_a25p");
end


function testMonotonicityViolationStopsPlanning(testCase)

    summary = ...
        localSummaryTable( ...
            [
                "m25p_a50p"
                "m50p_a75p"
            ], ...
            [25; 50], ...
            [50; 75], ...
            [true; true], ...
            [true; false]);

    verifyError(testCase, ...
        @() soopt.buildStrengthGridPlan( ...
            summary, ...
            [25 50], ...
            [50 75]), ...
        "StrengthGridPlan:MonotonicityViolation");
end


function testEmptySummaryLeavesAllPointsUnknown(testCase)

    summary = ...
        localSummaryTable( ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            false(0,1), ...
            false(0,1));

    plan = ...
        soopt.buildStrengthGridPlan( ...
            summary, ...
            [25 50], ...
            [25 50]);

    verifyEqual(testCase, ...
        height(plan), ...
        4);

    verifyTrue(testCase, ...
        all(plan.GridStatus == "UNKNOWN"));

    verifyTrue(testCase, ...
        all(plan.NeedsAssessment));
end


function testDuplicateGridValuesRejected(testCase)

    summary = ...
        localSummaryTable( ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            false(0,1), ...
            false(0,1));

    verifyError(testCase, ...
        @() soopt.buildStrengthGridPlan( ...
            summary, ...
            [25 25 50], ...
            [25 50]), ...
        "StrengthGridPlan:InvalidMuscleGrid");
end


function T = localSummaryTable( ...
        configId, musclePercent, actuatorPercent, ...
        assessmentComplete, isFeasible)

    ConfigId = ...
        string(configId(:));

    MusclePercent = ...
        double(musclePercent(:));

    ActuatorPercent = ...
        double(actuatorPercent(:));

    AssessmentComplete = ...
        logical(assessmentComplete(:));

    IsFeasible = ...
        logical(isFeasible(:));

    T = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            AssessmentComplete, ...
            IsFeasible);
end
