function tests = test_strength_configuration_monotonicity
%TEST_STRENGTH_CONFIGURATION_MONOTONICITY Tests monotonic feasibility audit.

    tests = ...
        functiontests(localfunctions);
end


function testMonotonicAssessedGridPasses(testCase)

    T = ...
        localSummaryTable( ...
            [
                "m25p_a25p"
                "m25p_a50p"
                "m50p_a25p"
                "m50p_a50p"
            ], ...
            [25; 25; 50; 50], ...
            [25; 50; 25; 50], ...
            [true; true; true; true], ...
            [false; false; false; true]);

    audit = ...
        soopt.auditFeasibilityMonotonicity(T);

    verifyTrue(testCase, ...
        audit.IsMonotonic);

    verifyEqual(testCase, ...
        audit.ViolationCount, ...
        0);

    verifyEqual(testCase, ...
        audit.AssessedConfigurations, ...
        4);

    verifyEqual(testCase, ...
        audit.FeasibleConfigurations, ...
        1);

    verifyEqual(testCase, ...
        audit.InfeasibleConfigurations, ...
        3);

    verifyEqual(testCase, ...
        height(audit.Violations), ...
        0);
end


function testFeasibleLowerAndInfeasibleHigherIsViolation(testCase)

    T = ...
        localSummaryTable( ...
            [
                "m25p_a50p"
                "m50p_a75p"
            ], ...
            [25; 50], ...
            [50; 75], ...
            [true; true], ...
            [true; false]);

    audit = ...
        soopt.auditFeasibilityMonotonicity(T);

    verifyFalse(testCase, ...
        audit.IsMonotonic);

    verifyEqual(testCase, ...
        audit.ViolationCount, ...
        1);

    verifyEqual(testCase, ...
        audit.Violations.LowerFeasibleConfigId, ...
        "m25p_a50p");

    verifyEqual(testCase, ...
        audit.Violations.HigherInfeasibleConfigId, ...
        "m50p_a75p");

    verifyEqual(testCase, ...
        audit.Violations.MuscleIncrease, ...
        25);

    verifyEqual(testCase, ...
        audit.Violations.ActuatorIncrease, ...
        25);
end


function testIncomparablePointsDoNotViolateMonotonicity(testCase)

    T = ...
        localSummaryTable( ...
            [
                "m25p_a75p"
                "m50p_a50p"
            ], ...
            [25; 50], ...
            [75; 50], ...
            [true; true], ...
            [true; false]);

    audit = ...
        soopt.auditFeasibilityMonotonicity(T);

    verifyTrue(testCase, ...
        audit.IsMonotonic);

    verifyEqual(testCase, ...
        audit.ViolationCount, ...
        0);
end


function testIncompleteHigherPointIsIgnored(testCase)

    T = ...
        localSummaryTable( ...
            [
                "m25p_a50p"
                "m50p_a75p"
            ], ...
            [25; 50], ...
            [50; 75], ...
            [true; false], ...
            [true; false]);

    audit = ...
        soopt.auditFeasibilityMonotonicity(T);

    verifyTrue(testCase, ...
        audit.IsMonotonic);

    verifyEqual(testCase, ...
        audit.AssessedConfigurations, ...
        1);

    verifyEqual(testCase, ...
        audit.ViolationCount, ...
        0);
end


function testMultipleViolationsAreReportedDeterministically(testCase)

    T = ...
        localSummaryTable( ...
            [
                "m50p_a75p"
                "m25p_a50p"
                "m50p_a50p"
                "m75p_a75p"
            ], ...
            [50; 25; 50; 75], ...
            [75; 50; 50; 75], ...
            [true; true; true; true], ...
            [false; true; true; false]);

    audit = ...
        soopt.auditFeasibilityMonotonicity(T);

    verifyFalse(testCase, ...
        audit.IsMonotonic);

    verifyEqual(testCase, ...
        audit.ViolationCount, ...
        4);

    verifyEqual(testCase, ...
        audit.Violations.LowerFeasibleConfigId, ...
        [
            "m25p_a50p"
            "m25p_a50p"
            "m50p_a50p"
            "m50p_a50p"
        ]);

    verifyEqual(testCase, ...
        audit.Violations.HigherInfeasibleConfigId, ...
        [
            "m50p_a75p"
            "m75p_a75p"
            "m50p_a75p"
            "m75p_a75p"
        ]);
end


function testSingleFeasibleConfigurationIsMonotonic(testCase)

    T = ...
        localSummaryTable( ...
            "m50p_a75p", ...
            50, ...
            75, ...
            true, ...
            true);

    audit = ...
        soopt.auditFeasibilityMonotonicity(T);

    verifyTrue(testCase, ...
        audit.IsMonotonic);

    verifyEqual(testCase, ...
        audit.ViolationCount, ...
        0);
end


function testEmptyTableIsSupported(testCase)

    T = ...
        localSummaryTable( ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            false(0,1), ...
            false(0,1));

    audit = ...
        soopt.auditFeasibilityMonotonicity(T);

    verifyTrue(testCase, ...
        audit.IsMonotonic);

    verifyEqual(testCase, ...
        audit.AssessedConfigurations, ...
        0);

    verifyEqual(testCase, ...
        height(audit.Violations), ...
        0);
end


function testDuplicateConfigIdRejected(testCase)

    T = ...
        localSummaryTable( ...
            [
                "m50p_a75p"
                "m50p_a75p"
            ], ...
            [50; 50], ...
            [75; 75], ...
            [true; true], ...
            [true; false]);

    verifyError(testCase, ...
        @() soopt.auditFeasibilityMonotonicity(T), ...
        "StrengthMonotonicity:DuplicateConfigId");
end


function T = localSummaryTable( ...
        configId, musclePercent, actuatorPercent, ...
        assessmentComplete, isFeasible)

    ConfigId = ...
        string(configId(:));

    MusclePercent = ...
        double(musclePercent(:));

    ActuatorPercent = ...
        double(actuatorPercent(:));

    AssessmentComplete = ...
        logical(assessmentComplete(:));

    IsFeasible = ...
        logical(isFeasible(:));

    T = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            AssessmentComplete, ...
            IsFeasible);
end
