function tests = test_static_optimization_pipeline_contract
%TEST_STATIC_OPTIMIZATION_PIPELINE_CONTRACT Process-4 contract tests.
%
% These tests verify configuration, resolved paths, dependencies, canonical
% stage layout, and worker availability without executing OpenSim.

    tests = functiontests(localfunctions);
end


function testStaticOptimizationConfigExists(testCase)

    cfg = ...
        localLoadConfig();

    verifyTrue(testCase, ...
        isfield( ...
            cfg.pipeline, ...
            "staticOptimization"));

    soCfg = ...
        cfg.pipeline.staticOptimization;

    requiredFields = [
        "requireForceOutput"
        "requireActivationOutput"
        "timeToleranceSec"
    ];

    verifyTrue(testCase, ...
        all(isfield( ...
            soCfg, ...
            cellstr(requiredFields))));

    verifyTrue(testCase, ...
        soCfg.requireForceOutput);

    verifyTrue(testCase, ...
        soCfg.requireActivationOutput);

    verifyEqual(testCase, ...
        soCfg.timeToleranceSec, ...
        1e-6);
end


function testResolvedContextContainsProcess4Dependencies(testCase)

    cfg = ...
        localTestConfig();

    trial = ...
        pipeline.resolveTrialContext( ...
            cfg, ...
            cfg.conditions(1), ...
            cfg.trials(1));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths, ...
            "StaticOptimizationPrep"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.StaticOptimizationPrep, ...
            "CheckpointFile"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths, ...
            "StaticOptimization"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.StaticOptimization, ...
            "SetupFile"));

    verifyTrue(testCase, ...
        isfield( ...
            trial.Paths.StaticOptimization, ...
            "ResultsDirectory"));
end


function testResolvedContextContainsProcess4QcPaths(testCase)

    cfg = ...
        localTestConfig();

    trial = ...
        pipeline.resolveTrialContext( ...
            cfg, ...
            cfg.conditions(1), ...
            cfg.trials(1));

    soPaths = ...
        trial.Paths.StaticOptimization;

    requiredFields = [
        "Directory"
        "ResultsDirectory"
        "QcDirectory"
        "PlotDirectory"
        "SetupFile"
        "OutputAuditCsv"
        "CheckpointFile"
        "ForceResultPattern"
        "ActivationResultPattern"
    ];

    verifyTrue(testCase, ...
        all(isfield( ...
            soPaths, ...
            cellstr(requiredFields))));

    verifyEqual(testCase, ...
        soPaths.ForceResultPattern, ...
        "*StaticOptimization_force.sto");

    verifyEqual(testCase, ...
        soPaths.ActivationResultPattern, ...
        "*StaticOptimization_activation.sto");
end


function testProcess4PathsUseCanonicalStageLayout(testCase)

    cfg = ...
        localTestConfig();

    trial = ...
        pipeline.resolveTrialContext( ...
            cfg, ...
            45, ...
            1);

    expectedProcess4Directory = ...
        string(fullfile( ...
            cfg.outputRoot, ...
            "45deg", ...
            "trial01", ...
            "04_static_optimization"));

    expectedResultsDirectory = ...
        string(fullfile( ...
            expectedProcess4Directory, ...
            "results"));

    expectedQcDirectory = ...
        string(fullfile( ...
            expectedProcess4Directory, ...
            "qc"));

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimization.Directory, ...
        expectedProcess4Directory);

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimization.ResultsDirectory, ...
        expectedResultsDirectory);

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimization.QcDirectory, ...
        expectedQcDirectory);

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimization.SetupFile, ...
        string(fullfile( ...
            expectedProcess4Directory, ...
            "45deg_trial01_so_setup.xml")));

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimization.OutputAuditCsv, ...
        string(fullfile( ...
            expectedQcDirectory, ...
            "static_optimization_output_audit.csv")));

    verifyEqual(testCase, ...
        trial.Paths.StaticOptimization.CheckpointFile, ...
        string(fullfile( ...
            expectedQcDirectory, ...
            "static_optimization_run_checkpoint.mat")));
end


function testProcess3CheckpointFeedsProcess4(testCase)

    cfg = ...
        localTestConfig();

    trial = ...
        pipeline.resolveTrialContext( ...
            cfg, ...
            cfg.conditions(1), ...
            cfg.trials(1));

    process3Checkpoint = ...
        trial.Paths.StaticOptimizationPrep.CheckpointFile;

    process4Setup = ...
        trial.Paths.StaticOptimization.SetupFile;

    verifyTrue(testCase, ...
        contains( ...
            process3Checkpoint, ...
            "03_static_optimization_prep"));

    verifyTrue(testCase, ...
        contains( ...
            process4Setup, ...
            "04_static_optimization"));

    verifyNotEqual(testCase, ...
        string(fileparts(process3Checkpoint)), ...
        string(fileparts(process4Setup)));
end


function testSharedWorkerIsResolvable(testCase)

    workerFile = ...
        which( ...
            "pipeline.runStaticOptimizationTrial");

    verifyNotEmpty(testCase, ...
        workerFile);
end


function cfg = localTestConfig()

    cfg = ...
        localLoadConfig();

    cfg.rawDataRoot = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_raw_data"));

    cfg.outputRoot = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_outputs"));
end


function cfg = localLoadConfig()

    repositoryRoot = ...
        string(fileparts(fileparts( ...
            mfilename("fullpath"))));

    addpath(repositoryRoot);

    cfg = ...
        load_project_config( ...
            "RequireLocalConfig", false, ...
            "ValidatePaths", false);
end
