function tests = test_strength_grid_search_controller
%TEST_STRENGTH_GRID_SEARCH_CONTROLLER Tests closed-loop controller contract.
%
% The focused suite does not execute OpenSim. It exercises initial analysis,
% proposal resolution, stop logic, dry-run behavior, and source-level
% integration with the callable Process-3/4 batch APIs.

    tests = ...
        functiontests(localfunctions);
end


function testDryRunResolvesCurrentTopProposal(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject( ...
            [0], ...
            1); %#ok<ASGLU>

    localCreatePool( ...
        configDirectory, ...
        [10 20], ...
        [10 20]);

    localWriteCompleteSummary( ...
        cfg, ...
        "m20p_a20p", ...
        20, ...
        20, ...
        true);

    expectedAnalysis = ...
        soopt.analyzeStrengthGrid( ...
            cfg, ...
            "ConfigDirectory", ...
                configDirectory, ...
            "CreateFigure", ...
                false);

    expectedSelection = ...
        soopt.resolveProposedStrengthConfig( ...
            expectedAnalysis);

    search = ...
        soopt.runStrengthGridSearch( ...
            cfg, ...
            "ConfigDirectory", ...
                configDirectory, ...
            "DryRun", ...
                true, ...
            "PrintProgress", ...
                false);

    verifyEqual(testCase, ...
        search.StopStatus, ...
        "SEARCH_DRY_RUN_READY");

    verifyEqual(testCase, ...
        search.ExecutedIterations, ...
        0);

    verifyEqual(testCase, ...
        height(search.Iterations), ...
        1);

    verifyEqual(testCase, ...
        search.Iterations.ConfigId, ...
        expectedSelection.ConfigId);

    verifyEqual(testCase, ...
        search.Iterations.ConfigFile, ...
        expectedSelection.ConfigFile);

    verifyEqual(testCase, ...
        search.Iterations.Status, ...
        "dry_run_selected");
end


function testDryRunDoesNotWriteFiles(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject( ...
            [0], ...
            1); %#ok<ASGLU>

    localCreatePool( ...
        configDirectory, ...
        [10 20], ...
        [10 20]);

    localWriteCompleteSummary( ...
        cfg, ...
        "m20p_a20p", ...
        20, ...
        20, ...
        true);

    analysisDirectory = ...
        string(fullfile( ...
            cfg.outputRoot, ...
            "static_optimization_configs", ...
            "grid_search_analysis"));

    search = ...
        soopt.runStrengthGridSearch( ...
            cfg, ...
            "ConfigDirectory", ...
                configDirectory, ...
            "DryRun", ...
                true, ...
            "WriteAnalysis", ...
                true, ...
            "WriteSearchHistory", ...
                true, ...
            "PrintProgress", ...
                false);

    verifyFalse(testCase, ...
        isfolder(analysisDirectory));

    verifyEqual(testCase, ...
        search.SearchHistoryCsv, ...
        "");

    verifyEqual(testCase, ...
        search.SearchHistoryMat, ...
        "");
end


function testNoProposalStopsWithoutExecuting(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject( ...
            [0], ...
            1); %#ok<ASGLU>

    localCreatePool( ...
        configDirectory, ...
        25, ...
        50);

    localWriteCompleteSummary( ...
        cfg, ...
        "m25p_a50p", ...
        25, ...
        50, ...
        true);

    search = ...
        soopt.runStrengthGridSearch( ...
            cfg, ...
            "ConfigDirectory", ...
                configDirectory, ...
            "WriteAnalysis", ...
                false, ...
            "WriteSearchHistory", ...
                false, ...
            "PrintProgress", ...
                false);

    verifyEqual(testCase, ...
        search.StopStatus, ...
        "SEARCH_COMPLETE_NO_PROPOSALS");

    verifyEqual(testCase, ...
        search.ExecutedIterations, ...
        0);

    verifyEqual(testCase, ...
        height(search.Iterations), ...
        0);
end


function testIncompleteCandidatePoolStopsPlanning(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject( ...
            [0], ...
            1); %#ok<ASGLU>

    localTouchJson( ...
        configDirectory, ...
        "m10p_a10p.json");

    localTouchJson( ...
        configDirectory, ...
        "m10p_a20p.json");

    localTouchJson( ...
        configDirectory, ...
        "m20p_a10p.json");

    search = ...
        soopt.runStrengthGridSearch( ...
            cfg, ...
            "ConfigDirectory", ...
                configDirectory, ...
            "WriteAnalysis", ...
                false, ...
            "WriteSearchHistory", ...
                false, ...
            "PrintProgress", ...
                false);

    verifyEqual(testCase, ...
        search.StopStatus, ...
        "SEARCH_STOPPED_PLANNING_UNAVAILABLE");

    verifyEqual(testCase, ...
        search.FinalAnalysis.PlanningStatus, ...
        "UNAVAILABLE_INCOMPLETE_CONFIG_POOL");

    verifyEqual(testCase, ...
        search.ExecutedIterations, ...
        0);
end


function testIncompleteOverwriteDisabledStopsBeforeBatch(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject( ...
            [0 15], ...
            1); %#ok<ASGLU>

    localCreatePool( ...
        configDirectory, ...
        25, ...
        50);

    localWriteIncompleteSummary( ...
        cfg, ...
        "m25p_a50p", ...
        25, ...
        50);

    search = ...
        soopt.runStrengthGridSearch( ...
            cfg, ...
            "ConfigDirectory", ...
                configDirectory, ...
            "OverwriteIncompleteConfiguration", ...
                false, ...
            "WriteAnalysis", ...
                false, ...
            "WriteSearchHistory", ...
                false, ...
            "PrintProgress", ...
                false);

    verifyEqual(testCase, ...
        search.StopStatus, ...
        "SEARCH_STOPPED_INCOMPLETE_OVERWRITE_DISABLED");

    verifyEqual(testCase, ...
        search.ExecutedIterations, ...
        0);

    verifyEqual(testCase, ...
        height(search.Iterations), ...
        1);

    verifyTrue(testCase, ...
        search.Iterations.ExistingIncomplete);

    verifyEqual(testCase, ...
        search.Iterations.Status, ...
        "incomplete_overwrite_disabled");
end


function testControllerUsesCallablePipelineStages(testCase)

    source = ...
        localReadFunctionSource( ...
            "soopt.runStrengthGridSearch");

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "soopt.analyzeStrengthGrid"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "soopt.resolveProposedStrengthConfig"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "pipeline.runStaticOptimizationPrepBatch"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "pipeline.runStaticOptimizationBatch"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "soopt.writeStrengthGridAnalysis"));

    verifyFalse(testCase, ...
        contains( ...
            source, ...
            "load_project_config("));
end


function testControllerUsesResolvedProjectDefaults(testCase)

    source = ...
        localReadFunctionSource( ...
            "soopt.runStrengthGridSearch");

    sourceWithoutWhitespace = ...
        regexprep( ...
            erase(source, "..."), ...
            "\s+", ...
            "");

    verifyTrue(testCase, ...
        contains( ...
            sourceWithoutWhitespace, ...
            "soopt.resolveStrengthGridSearchControllerConfig(" + ...
            "projectCfg)"));

    optionNames = [
        "ConfigDirectory"
        "SearchMode"
        "BoundaryIncrementPercent"
        "BoundaryMuscleBounds"
        "BoundaryActuatorBounds"
        "AdaptiveConfigDirectory"
        "AdaptiveTemplateConfigFile"
        "MaxIterations"
        "DryRun"
        "OverwriteIncompleteConfiguration"
        "WriteAnalysis"
        "AnalysisOutputDirectory"
        "ExportFigure"
        "FigureResolution"
        "WriteSearchHistory"
        "PrintProgress"
    ];

    for optionName = optionNames'

        expectedParserPrefix = ...
            "addParameter(parser,""" + ...
            optionName + ...
            """,controllerDefaults." + ...
            optionName + ...
            ",";

        verifyTrue(testCase, ...
            contains( ...
                sourceWithoutWhitespace, ...
                expectedParserPrefix), ...
            "Parser default for " + ...
            optionName + ...
            " was not sourced from controllerDefaults.");
    end
end


function testConfiguredDefaultsAndExplicitOverridesReachRuntime(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject( ...
            [0], ...
            1); %#ok<ASGLU>

    localCreatePool( ...
        configDirectory, ...
        [10 20], ...
        [10 20]);

    localWriteCompleteSummary( ...
        cfg, ...
        "m20p_a20p", ...
        20, ...
        20, ...
        true);

    cfg.optimization.staticOptimization.fixedGrid.configDirectory = ...
        configDirectory;

    cfg.optimization.staticOptimization.output.figureResolution = ...
        321;

    search = ...
        soopt.runStrengthGridSearch( ...
            cfg, ...
            "DryRun", ...
                true, ...
            "PrintProgress", ...
                false);

    verifyEqual(testCase, ...
        search.Configuration.ConfigDirectory, ...
        configDirectory);

    verifyEqual(testCase, ...
        search.Configuration.FigureResolution, ...
        321);

    verifyTrue(testCase, ...
        search.Configuration.DryRun);

    verifyFalse(testCase, ...
        search.Configuration.PrintProgress);
end


function testControllerExplicitlyUsesTargetApplyMode(testCase)

    source = ...
        localReadFunctionSource( ...
            "soopt.runStrengthGridSearch");

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            'applyMode'));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            '"target"'));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "StrengthGridSearch:NonIdempotentApplyMode"));
end



function testAdaptiveDryRunSelectsBoundaryProposalWithoutWriting(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject( ...
            [0], ...
            1); %#ok<ASGLU>

    localCreatePool( ...
        configDirectory, ...
        25, ...
        [15 25]);

    localWriteCompleteSummary( ...
        cfg, ...
        "m25p_a15p", ...
        25, ...
        15, ...
        false);

    localWriteCompleteSummary( ...
        cfg, ...
        "m25p_a25p", ...
        25, ...
        25, ...
        true);

    adaptiveDirectory = ...
        string(fullfile( ...
            configDirectory, ...
            "adaptive_generated"));

    search = ...
        soopt.runStrengthGridSearch( ...
            cfg, ...
            "ConfigDirectory", ...
                configDirectory, ...
            "SearchMode", ...
                "adaptive_boundary", ...
            "BoundaryIncrementPercent", ...
                5, ...
            "DryRun", ...
                true, ...
            "PrintProgress", ...
                false);

    verifyEqual(testCase, ...
        search.StopStatus, ...
        "SEARCH_DRY_RUN_READY");

    verifyEqual(testCase, ...
        height(search.Iterations), ...
        1);

    verifyEqual(testCase, ...
        search.Iterations.SearchMode, ...
        "adaptive_boundary");

    verifyEqual(testCase, ...
        search.Iterations.ConfigId, ...
        "m25p_a20p");

    verifyEqual(testCase, ...
        search.Iterations.ConfigFile, ...
        "");

    verifyFalse(testCase, ...
        search.Iterations.ConfigCreated);

    verifyFalse(testCase, ...
        isfolder(adaptiveDirectory));
end


function testAdaptiveBoundaryResolvedAtRequestedIncrement(testCase)

    [cfg, configDirectory, cleanup] = ...
        localCreateProject( ...
            [0], ...
            1); %#ok<ASGLU>

    localCreatePool( ...
        configDirectory, ...
        25, ...
        [15 20]);

    localWriteCompleteSummary( ...
        cfg, ...
        "m25p_a15p", ...
        25, ...
        15, ...
        false);

    localWriteCompleteSummary( ...
        cfg, ...
        "m25p_a20p", ...
        25, ...
        20, ...
        true);

    search = ...
        soopt.runStrengthGridSearch( ...
            cfg, ...
            "ConfigDirectory", ...
                configDirectory, ...
            "SearchMode", ...
                "adaptive_boundary", ...
            "BoundaryIncrementPercent", ...
                5, ...
            "WriteAnalysis", ...
                false, ...
            "WriteSearchHistory", ...
                false, ...
            "PrintProgress", ...
                false);

    verifyEqual(testCase, ...
        search.StopStatus, ...
        "SEARCH_COMPLETE_BOUNDARY_RESOLVED");

    verifyEqual(testCase, ...
        search.ExecutedIterations, ...
        0);

    verifyEqual(testCase, ...
        height(search.FinalAnalysis.Proposals), ...
        0);
end


function testInvalidSearchModeIsRejected(testCase)

    [cfg, ~, cleanup] = ...
        localCreateProject( ...
            [0], ...
            1); %#ok<ASGLU>

    verifyError(testCase, ...
        @() soopt.runStrengthGridSearch( ...
            cfg, ...
            "SearchMode", ...
                "not_a_mode", ...
            "DryRun", ...
                true, ...
            "PrintProgress", ...
                false), ...
        "StrengthGridSearch:InvalidSearchMode");
end


function testControllerReferencesAdaptiveProposalRoute(testCase)

    source = ...
        localReadFunctionSource( ...
            "soopt.runStrengthGridSearch");

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            '"SearchMode"'));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            '"adaptive_boundary"'));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "soopt.proposeBoundaryRefinement"));

    verifyTrue(testCase, ...
        contains( ...
            source, ...
            "soopt.materializeBoundaryRefinement"));
end


function [cfg, configDirectory, cleanup] = ...
        localCreateProject(conditions, trials)

    root = ...
        string(fullfile( ...
            tempdir, ...
            "headneck_grid_search_" + ...
            string(java.util.UUID.randomUUID())));

    outputRoot = ...
        string(fullfile( ...
            root, ...
            "output"));

    configDirectory = ...
        string(fullfile( ...
            root, ...
            "force_configs"));

    mkdir(outputRoot);
    mkdir(configDirectory);

    cleanup = ...
        onCleanup(@() localRemoveTree(root));

    cfg = struct;

    cfg.outputRoot = ...
        outputRoot;

    cfg.conditions = ...
        double(conditions);

    cfg.trials = ...
        double(trials);

    cfg.overwriteExisting = ...
        false;

    cfg.forceCapacity = struct;

    cfg.forceCapacity.enabled = ...
        false;

    cfg.forceCapacity.configFile = ...
        string(fullfile( ...
            configDirectory, ...
            "m25p_a50p.json"));

    cfg.forceCapacity.applyMode = ...
        "target";

    cfg.batchProcessing = struct;

    cfg.batchProcessing.enableParallel = ...
        false;

    cfg.batchProcessing.maxWorkers = ...
        1;

    cfg.batchProcessing.continueOnError = ...
        true;

    cfg.batchProcessing.poolProfile = ...
        "local";

    cfg.batchProcessing.closePoolWhenFinished = ...
        false;

    cfg.optimization = struct;
    cfg.optimization.staticOptimization = struct;

    searchCfg = struct;
    searchCfg.searchMode = "fixed_grid";
    searchCfg.maxIterations = 20;
    searchCfg.dryRun = false;
    searchCfg.overwriteIncompleteConfiguration = true;

    searchCfg.fixedGrid = struct;
    searchCfg.fixedGrid.configDirectory = "";

    searchCfg.adaptiveBoundary = struct;
    searchCfg.adaptiveBoundary.incrementPercent = 5;
    searchCfg.adaptiveBoundary.muscleBounds = [];
    searchCfg.adaptiveBoundary.actuatorBounds = [];
    searchCfg.adaptiveBoundary.configDirectory = "";
    searchCfg.adaptiveBoundary.templateConfigFile = "";

    searchCfg.output = struct;
    searchCfg.output.writeAnalysis = true;
    searchCfg.output.analysisDirectory = "";
    searchCfg.output.exportFigure = true;
    searchCfg.output.figureResolution = 300;
    searchCfg.output.writeSearchHistory = true;

    searchCfg.printProgress = true;

    cfg.optimization.staticOptimization = ...
        searchCfg;
end


function localCreatePool( ...
        configDirectory, ...
        muscleGrid, ...
        actuatorGrid)

    for muscle = muscleGrid

        for actuator = actuatorGrid

            localTouchJson( ...
                configDirectory, ...
                localConfigId( ...
                    muscle, ...
                    actuator) + ...
                ".json");
        end
    end
end


function localWriteCompleteSummary( ...
        cfg, ...
        configId, ...
        musclePercent, ...
        actuatorPercent, ...
        isFeasible)

    ConditionDeg = ...
        cfg.conditions(:);

    nConditions = ...
        numel(ConditionDeg);

    TrialNumber = ...
        repmat( ...
            cfg.trials(1), ...
            nConditions, ...
            1);

    ConfigId = ...
        repmat( ...
            string(configId), ...
            nConditions, ...
            1);

    MusclePercent = ...
        repmat( ...
            musclePercent, ...
            nConditions, ...
            1);

    ActuatorPercent = ...
        repmat( ...
            actuatorPercent, ...
            nConditions, ...
            1);

    Succeeded = ...
        true(nConditions,1);

    Status = ...
        repmat( ...
            "completed", ...
            nConditions, ...
            1);

    OutputAuditPassed = ...
        true(nConditions,1);

    if ~isFeasible

        Succeeded(end) = ...
            false;

        Status(end) = ...
            "activation_saturation";
    end

    summary = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            ConditionDeg, ...
            TrialNumber, ...
            Succeeded, ...
            Status, ...
            OutputAuditPassed);

    localWriteSummaryTable( ...
        cfg, ...
        configId, ...
        summary);
end


function localWriteIncompleteSummary( ...
        cfg, ...
        configId, ...
        musclePercent, ...
        actuatorPercent)

    ConfigId = ...
        string(configId);

    MusclePercent = ...
        musclePercent;

    ActuatorPercent = ...
        actuatorPercent;

    ConditionDeg = ...
        cfg.conditions(1);

    TrialNumber = ...
        cfg.trials(1);

    Succeeded = ...
        true;

    Status = ...
        "completed";

    OutputAuditPassed = ...
        true;

    summary = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            ConditionDeg, ...
            TrialNumber, ...
            Succeeded, ...
            Status, ...
            OutputAuditPassed);

    localWriteSummaryTable( ...
        cfg, ...
        configId, ...
        summary);
end


function localWriteSummaryTable( ...
        cfg, ...
        configId, ...
        summary)

    batchQcDirectory = ...
        string(fullfile( ...
            cfg.outputRoot, ...
            "static_optimization_configs", ...
            configId, ...
            "batch_qc"));

    mkdir(batchQcDirectory);

    summaryCsv = ...
        string(fullfile( ...
            batchQcDirectory, ...
            "process_4_static_optimization_summary.csv"));

    writetable( ...
        summary, ...
        summaryCsv);
end


function configId = localConfigId( ...
        musclePercent, ...
        actuatorPercent)

    configId = ...
        "m" + ...
        string(musclePercent) + ...
        "p_a" + ...
        compose("%02d", actuatorPercent) + ...
        "p";
end


function localTouchJson(directory, fileName)

    filePath = ...
        string(fullfile( ...
            directory, ...
            fileName));

    fid = ...
        fopen(filePath, "w");

    assert(fid >= 0, ...
        "StrengthGridSearchTest:FileCreateFailed", ...
        "Could not create synthetic JSON:\n%s", ...
        filePath);

    cleaner = ...
        onCleanup(@() fclose(fid)); %#ok<NASGU>

    fprintf(fid, "{}\n");
end


function source = localReadFunctionSource(functionName)

    filePath = ...
        string(which(functionName));

    assert(isfile(filePath), ...
        "StrengthGridSearchTest:FunctionNotFound", ...
        "Could not resolve function source for %s.", ...
        functionName);

    source = ...
        string(fileread(filePath));
end


function localRemoveTree(root)

    if isfolder(root)

        rmdir(root, "s");
    end
end
