function result = applyForceCapacityConfig( ...
        modelFile, configFile, varargin)
%APPLYFORCECAPACITYCONFIG Apply a reusable ForceSet configuration to a model.
%
% result = modelprep.applyForceCapacityConfig(modelFile, configFile)
%
% NAME-VALUE OPTIONS
%   OutputModelFile
%       Destination .osim. Default: modelFile (in-place requested).
%
%   AllowInPlace
%       Required true when OutputModelFile == modelFile.
%       Default false.
%
%   ApplyMode
%       "default" (use config DefaultApplyMode), "target", or "scale".
%       Default "default".
%
%   RequireAllEntries
%       Error if any config entry cannot be matched in target model.
%       Default true.
%
%   AuditFile
%       Optional CSV path. Default: sibling
%       <model>_force_config_audit.csv.
%
%   Overwrite
%       Permit replacing an existing separate OutputModelFile.
%       Default false.
%
% APPLICATION MODES
%   target:
%       Set each configured capacity to the exact TargetValue selected in
%       the base model.
%
%   scale:
%       Multiply the target model's CURRENT capacity by the saved
%       ScaleFactor.
%
% appliesForce changes are always applied as explicit target states when
% AppliesForceAction == "set".
%
% For safe in-place application, edits are written to a temporary model,
% verified, then atomically moved over the generated model.

    parser = inputParser;
    parser.FunctionName = ...
        "modelprep.applyForceCapacityConfig";

    addRequired(parser, "modelFile", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    addRequired(parser, "configFile", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    addParameter(parser, "OutputModelFile", "", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    addParameter(parser, "AllowInPlace", false, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, "ApplyMode", "default", ...
        @(x) any(strcmpi(string(x), ...
            ["default","target","scale"])));

    addParameter(parser, "RequireAllEntries", true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, "AuditFile", "", ...
        @(x) ischar(x) || (isstring(x) && isscalar(x)));

    addParameter(parser, "Overwrite", false, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, modelFile, configFile, varargin{:});

    modelFile = string(parser.Results.modelFile);
    configFile = string(parser.Results.configFile);
    outputModelFile = string(parser.Results.OutputModelFile);
    allowInPlace = parser.Results.AllowInPlace;
    requireAllEntries = parser.Results.RequireAllEntries;
    auditFile = string(parser.Results.AuditFile);
    overwrite = parser.Results.Overwrite;

    assert(isfile(modelFile), ...
        "ForceCapacityConfig:TargetModelMissing", ...
        "Target model was not found:\n%s", modelFile);

    if strlength(outputModelFile) == 0
        outputModelFile = modelFile;
    end

    sameFile = ...
        strcmpi( ...
            char(java.io.File(char(modelFile)).getCanonicalPath()), ...
            char(java.io.File(char(outputModelFile)).getCanonicalPath()));

    if sameFile && ~allowInPlace
        error( ...
            "ForceCapacityConfig:InPlaceNotAllowed", ...
            ["OutputModelFile resolves to the input model. " ...
             "Set AllowInPlace=true explicitly for pipeline use."]);
    end

    loaded = ...
        modelprep.loadForceCapacityConfig( ...
            configFile);

    config = loaded.Config;

    applyMode = ...
        lower(string(parser.Results.ApplyMode));

    if applyMode == "default"
        applyMode = ...
            lower(string(config.DefaultApplyMode));
    end

    inspection = ...
        modelprep.inspectForceCapacities( ...
            modelFile);

    targetTable = ...
        inspection.Capacities;

    entries = config.Entries(:);

    changeRows = table();
    applicationAudit = table();

    unmatched = strings(0,1);

    for iEntry = 1:numel(entries)

        entry = entries(iEntry);

        name = string(entry.Name);
        objectType = string(entry.ObjectType);

        match = ...
            targetTable.Name == name & ...
            targetTable.ObjectType == objectType;

        if nnz(match) ~= 1

            unmatched(end+1,1) = ...
                name + " [" + objectType + "]"; %#ok<AGROW>
            continue;
        end

        row = targetTable(match, :);

        proposedEnabled = ...
            row.AppliesForce;

        appliesAction = ...
            lower(string(entry.AppliesForceAction));

        if appliesAction == "set"
            proposedEnabled = ...
                logical(entry.TargetAppliesForce);
        end

        parameterName = ...
            string(entry.CapacityParameter);

        proposedValue = ...
            row.CurrentValue;

        capacityAction = ...
            lower(string(entry.CapacityAction));

        if capacityAction == "set"

            assert(row.HasScalarCapacity, ...
                "ForceCapacityConfig:TargetNotScalable", ...
                ["Configured object '%s' no longer exposes a supported " ...
                 "scalar capacity in the target model."], ...
                name);

            assert(row.CapacityParameter == parameterName, ...
                "ForceCapacityConfig:ParameterMismatch", ...
                ["Configured parameter '%s' for '%s' does not match " ...
                 "target parameter '%s'."], ...
                parameterName, name, row.CapacityParameter);

            switch applyMode

                case "target"
                    proposedValue = ...
                        double(entry.TargetValue);

                case "scale"
                    proposedValue = ...
                        row.CurrentValue * ...
                        double(entry.ScaleFactor);
            end
        end

        thisChange = table( ...
            name, ...
            objectType, ...
            proposedEnabled, ...
            parameterName, ...
            proposedValue, ...
            'VariableNames', { ...
                'Name', ...
                'ObjectType', ...
                'ProposedAppliesForce', ...
                'CapacityParameter', ...
                'ProposedValue'});

        changeRows = [ ...
            changeRows
            thisChange]; %#ok<AGROW>

        sourceReferenceValue = NaN;
        configuredTargetValue = NaN;
        configuredScaleFactor = NaN;

        if capacityAction == "set"
            sourceReferenceValue = ...
                double(entry.ReferenceValue);
            configuredTargetValue = ...
                double(entry.TargetValue);
            configuredScaleFactor = ...
                double(entry.ScaleFactor);
        end

        auditRow = table( ...
            name, ...
            objectType, ...
            string(entry.Group), ...
            parameterName, ...
            capacityAction, ...
            applyMode, ...
            sourceReferenceValue, ...
            row.CurrentValue, ...
            configuredTargetValue, ...
            configuredScaleFactor, ...
            proposedValue, ...
            row.AppliesForce, ...
            proposedEnabled, ...
            'VariableNames', { ...
                'Name', ...
                'ObjectType', ...
                'Group', ...
                'CapacityParameter', ...
                'CapacityAction', ...
                'ApplyMode', ...
                'ConfigReferenceValue', ...
                'TargetModelOriginalValue', ...
                'ConfigTargetValue', ...
                'ConfigScaleFactor', ...
                'AppliedValue', ...
                'TargetModelOriginalAppliesForce', ...
                'AppliedAppliesForce'});

        applicationAudit = [ ...
            applicationAudit
            auditRow]; %#ok<AGROW>
    end

    if ~isempty(unmatched)

        if requireAllEntries
            error( ...
                "ForceCapacityConfig:UnmatchedEntries", ...
                ["The following configuration entries could not be " ...
                 "matched uniquely in the target model:\n%s"], ...
                strjoin(unmatched, newline));
        else
            warning( ...
                "ForceCapacityConfig:UnmatchedEntries", ...
                "Skipping unmatched entries:\n%s", ...
                strjoin(unmatched, newline));
        end
    end

    assert(~isempty(changeRows), ...
        "ForceCapacityConfig:NoApplicableEntries", ...
        "No configuration entries could be applied to the target model.");

    %% Determine audit path.

    if strlength(auditFile) == 0

        [auditFolder, auditStem, ~] = ...
            fileparts(outputModelFile);

        auditFile = string(fullfile( ...
            auditFolder, ...
            string(auditStem) + ...
            "_force_config_audit.csv"));
    end

    %% Safe write.

    if sameFile

        [targetFolder, targetStem, ~] = ...
            fileparts(modelFile);

        temporaryModel = string(fullfile( ...
            targetFolder, ...
            string(targetStem) + ...
            "_force_config_tmp.osim"));

        if isfile(temporaryModel)
            delete(temporaryModel);
        end

        applyResult = ...
            modelprep.applyForceCapacityChanges( ...
                modelFile, ...
                temporaryModel, ...
                changeRows, ...
                "Overwrite", true);

        [movePassed, moveMessage] = ...
            movefile( ...
                temporaryModel, ...
                modelFile, ...
                "f");

        assert(movePassed, ...
            "ForceCapacityConfig:InPlaceReplaceFailed", ...
            "Could not replace target model:\n%s", ...
            moveMessage);

        finalModelFile = modelFile;

    else

        applyResult = ...
            modelprep.applyForceCapacityChanges( ...
                modelFile, ...
                outputModelFile, ...
                changeRows, ...
                "Overwrite", overwrite);

        finalModelFile = outputModelFile;
    end

    %% Final verification and audit merge.

    finalInspection = ...
        modelprep.inspectForceCapacities( ...
            finalModelFile);

    finalTable = finalInspection.Capacities;

    verifiedValue = nan(height(applicationAudit),1);
    verifiedAppliesForce = false(height(applicationAudit),1);
    verificationPassed = false(height(applicationAudit),1);

    for iRow = 1:height(applicationAudit)

        match = ...
            finalTable.Name == applicationAudit.Name(iRow) & ...
            finalTable.ObjectType == applicationAudit.ObjectType(iRow);

        assert(nnz(match) == 1, ...
            "ForceCapacityConfig:FinalVerificationLookupFailed", ...
            "Could not verify '%s' in final model.", ...
            applicationAudit.Name(iRow));

        verifiedValue(iRow) = ...
            finalTable.CurrentValue(match);

        verifiedAppliesForce(iRow) = ...
            finalTable.AppliesForce(match);

        if applicationAudit.CapacityAction(iRow) == "set"
            valuePassed = ...
                abs(verifiedValue(iRow) - ...
                    applicationAudit.AppliedValue(iRow)) <= ...
                max(1e-12, ...
                    1e-10 * ...
                    abs(applicationAudit.AppliedValue(iRow)));
        else
            valuePassed = true;
        end

        enabledPassed = ...
            verifiedAppliesForce(iRow) == ...
            applicationAudit.AppliedAppliesForce(iRow);

        verificationPassed(iRow) = ...
            valuePassed && enabledPassed;
    end

    applicationAudit.VerifiedValue = ...
        verifiedValue;

    applicationAudit.VerifiedAppliesForce = ...
        verifiedAppliesForce;

    applicationAudit.VerificationPassed = ...
        verificationPassed;

    assert(all(verificationPassed), ...
        "ForceCapacityConfig:FinalVerificationFailed", ...
        "One or more applied configuration entries failed verification.");

    [auditFolder,~,~] = fileparts(auditFile);

    if strlength(string(auditFolder)) > 0 && ...
            ~isfolder(auditFolder)
        mkdir(auditFolder);
    end

    writetable( ...
        applicationAudit, ...
        auditFile);

    result = struct;
    result.ModelFile = finalModelFile;
    result.ConfigFile = configFile;
    result.ApplyMode = applyMode;
    result.AuditFile = auditFile;
    result.Audit = applicationAudit;
    result.UnmatchedEntries = unmatched;
    result.VerificationPassed = all(verificationPassed);
    result.ApplyResult = applyResult;
end
