function result = filterCoordinateMotion( ...
    motionInput, coordinateNames, varargin)
%FILTERCOORDINATEMOTION Low-pass filter selected OpenSim coordinates.
%
% result = modelprep.filterCoordinateMotion( ...
%     motionInput, coordinateNames)
%
% Applies a zero-phase Butterworth low-pass filter to selected coordinate
% columns while leaving all other columns unchanged.
%
% INPUTS
%   motionInput
%       Either:
%           - OpenSim motion struct returned by opensimio.readMot
%           - path to an OpenSim .mot file
%
%   coordinateNames
%       String array, character vector, or cell array containing the
%       coordinate names to filter.
%
% NAME-VALUE OPTIONS
%   "CutoffHz"
%       Low-pass cutoff frequency in Hz.
%       Default: 1.0
%
%   "PrototypeOrder"
%       Order supplied to butter().
%       Default: 2
%
%       Because filtfilt applies the filter forward and backward, the
%       effective zero-phase magnitude response is twice this order.
%
%   "AuditWindow"
%       Optional [startTime endTime] interval used for descriptive QC
%       metrics. If empty, the full trajectory is used.
%       Default: []
%
%   "UniformSamplingTolerance"
%       Maximum permitted fractional deviation of individual sample
%       intervals from the median sample interval.
%       Default: 1e-3
%
% OUTPUT
%   result.Motion
%       OpenSim motion struct with only the requested coordinate columns
%       filtered.
%
%   result.Audit
%       Table containing before/after descriptive metrics.
%
%   result.SampleRateHz
%   result.CutoffHz
%   result.PrototypeOrder
%   result.EffectiveZeroPhaseOrder
%   result.FilteredCoordinates
%   result.AuditWindow
%   result.NumAuditSamples
%   result.SourceFile
%
% NOTES
%   - The time column is never filtered.
%   - Filtering is performed over the entire trajectory, not only over the
%     audit/lock window. This minimizes boundary artifacts within the
%     supported-pose interval.
%   - The function does not determine whether the resulting trajectory is
%     sufficiently stable. Stability assessment remains the responsibility
%     of modelprep.extractStableCoordinateValues or another QC function.

    parser = inputParser;
    parser.FunctionName = ...
        "modelprep.filterCoordinateMotion";

    addRequired(parser, "motionInput");

    addRequired(parser, "coordinateNames", ...
        @(x) ischar(x) || isstring(x) || iscellstr(x));

    addParameter(parser, "CutoffHz", 1.0, ...
        @(x) isnumeric(x) && isscalar(x) && ...
        isfinite(x) && x > 0);

    addParameter(parser, "PrototypeOrder", 2, ...
        @(x) isnumeric(x) && isscalar(x) && ...
        isfinite(x) && x >= 1 && mod(x, 1) == 0);

    addParameter(parser, "AuditWindow", [], ...
        @(x) isempty(x) || ...
        (isnumeric(x) && numel(x) == 2 && ...
        all(isfinite(x))));

    addParameter(parser, ...
        "UniformSamplingTolerance", ...
        1e-3, ...
        @(x) isnumeric(x) && isscalar(x) && ...
        isfinite(x) && x >= 0);

    parse(parser, ...
        motionInput, ...
        coordinateNames, ...
        varargin{:});

    coordinateNames = reshape( ...
        string(parser.Results.coordinateNames), ...
        1, []);

    cutoffHz = ...
        double(parser.Results.CutoffHz);

    prototypeOrder = ...
        double(parser.Results.PrototypeOrder);

    auditWindowRequested = ...
        parser.Results.AuditWindow;

    uniformSamplingTolerance = ...
        double(parser.Results.UniformSamplingTolerance);

    %% Validate requested coordinate names

    assert(~isempty(coordinateNames), ...
        "At least one coordinate must be specified.");

    assert(all(strlength(coordinateNames) > 0), ...
        "Coordinate names cannot be empty.");

    assert(~any(strcmpi(coordinateNames, "time")), ...
        "The time column cannot be filtered.");

    assert(numel(unique(coordinateNames)) == ...
        numel(coordinateNames), ...
        "coordinateNames contains duplicate entries.");

    %% Resolve motion input

    [motion, sourceFile] = ...
        opensimio.resolveMotion( ...
            motionInput);

    %% Validate required OpenSim motion fields

    requiredFields = [
        "Labels"
        "Data"
        "Time"
        "InDegrees"
    ];

    for iField = 1:numel(requiredFields)

        fieldName = requiredFields(iField);

        assert(isfield(motion, fieldName), ...
            "Motion input is missing required field '%s'.", ...
            fieldName);

    end

    labels = reshape( ...
        string(motion.Labels), ...
        1, []);

    data = motion.Data;
    time = motion.Time(:);

    assert(isnumeric(data) && ismatrix(data), ...
        "motion.Data must be a numeric two-dimensional array.");

    assert(size(data, 1) == numel(time), ...
        ["Number of motion data rows (%d) does not match " ...
         "the time vector length (%d)."], ...
        size(data, 1), ...
        numel(time));

    assert(size(data, 2) == numel(labels), ...
        ["Number of motion data columns (%d) does not match " ...
         "the number of labels (%d)."], ...
        size(data, 2), ...
        numel(labels));

    assert(all(isfinite(time)), ...
        "Motion time vector contains nonfinite values.");

    assert(all(diff(time) > 0), ...
        "Motion time vector must be strictly increasing.");

    %% Determine and validate sampling frequency

    dt = diff(time);

    medianDt = median(dt);
    sampleRateHz = 1 / medianDt;

    relativeDtVariation = ...
        max(abs(dt - medianDt)) / medianDt;

    assert(relativeDtVariation <= ...
        uniformSamplingTolerance, ...
        ["Motion sampling is insufficiently uniform for " ...
         "digital filtering. Maximum fractional interval " ...
         "deviation = %.3e; tolerance = %.3e."], ...
        relativeDtVariation, ...
        uniformSamplingTolerance);

    nyquistHz = sampleRateHz / 2;

    assert(cutoffHz < nyquistHz, ...
        ["Cutoff frequency %.3f Hz must be below the " ...
         "Nyquist frequency %.3f Hz."], ...
        cutoffHz, ...
        nyquistHz);

    %% Resolve audit interval

    if isempty(auditWindowRequested)

        auditWindow = [
            time(1)
            time(end)
        ];

    else

        auditWindow = ...
            double(auditWindowRequested(:));

        assert(auditWindow(2) > auditWindow(1), ...
            "AuditWindow end time must exceed its start time.");

        assert(auditWindow(1) >= time(1) && ...
            auditWindow(2) <= time(end), ...
            ["AuditWindow [%.6f %.6f] lies outside motion " ...
             "time range [%.6f %.6f]."], ...
            auditWindow(1), ...
            auditWindow(2), ...
            time(1), ...
            time(end));

    end

    auditMask = ...
        time >= auditWindow(1) & ...
        time <= auditWindow(2);

    numAuditSamples = nnz(auditMask);

    assert(numAuditSamples >= 2, ...
        "Audit window must contain at least two samples.");

    auditTime = time(auditMask);

    %% Design Butterworth filter

    normalizedCutoff = ...
        cutoffHz / nyquistHz;

    [b, a] = butter( ...
        prototypeOrder, ...
        normalizedCutoff, ...
        "low");

    % MATLAB filtfilt requires enough samples for endpoint handling.
    minimumFilterSamples = ...
        3 * (max(numel(a), numel(b)) - 1) + 1;

    assert(numel(time) >= minimumFilterSamples, ...
        ["Motion contains only %d samples; at least %d " ...
         "are required for the selected filter."], ...
        numel(time), ...
        minimumFilterSamples);

    %% Prepare filtered motion output

    filteredMotion = motion;

    filteredData = data;

    numCoordinates = ...
        numel(coordinateNames);

    %% Allocate audit variables

    coordinateColumn = ...
        strings(numCoordinates, 1);

    columnIndexColumn = ...
        nan(numCoordinates, 1);

    rawMedianColumn = ...
        nan(numCoordinates, 1);

    filteredMedianColumn = ...
        nan(numCoordinates, 1);

    medianShiftColumn = ...
        nan(numCoordinates, 1);

    absoluteMedianShiftColumn = ...
        nan(numCoordinates, 1);

    rawRangeColumn = ...
        nan(numCoordinates, 1);

    filteredRangeColumn = ...
        nan(numCoordinates, 1);

    rangeReductionColumn = ...
        nan(numCoordinates, 1);

    rawStdColumn = ...
        nan(numCoordinates, 1);

    filteredStdColumn = ...
        nan(numCoordinates, 1);

    stdReductionColumn = ...
        nan(numCoordinates, 1);

    rawSlopeColumn = ...
        nan(numCoordinates, 1);

    filteredSlopeColumn = ...
        nan(numCoordinates, 1);

    %% Filter requested coordinates

    for iCoordinate = 1:numCoordinates

        coordinate = ...
            coordinateNames(iCoordinate);

        matches = find(labels == coordinate);

        assert(~isempty(matches), ...
            "Coordinate '%s' was not found in the motion file.", ...
            coordinate);

        assert(numel(matches) == 1, ...
            "Coordinate '%s' occurs more than once.", ...
            coordinate);

        columnIndex = matches(1);

        raw = data(:, columnIndex);

        assert(all(isfinite(raw)), ...
            "Coordinate '%s' contains nonfinite samples.", ...
            coordinate);

        filtered = filtfilt( ...
            b, ...
            a, ...
            raw);

        assert(all(isfinite(filtered)), ...
            ["Filtering coordinate '%s' produced " ...
             "nonfinite samples."], ...
            coordinate);

        filteredData(:, columnIndex) = ...
            filtered;

        %% Audit within selected interval

        rawWindow = ...
            raw(auditMask);

        filteredWindow = ...
            filtered(auditMask);

        rawMedian = ...
            median(rawWindow);

        filteredMedian = ...
            median(filteredWindow);

        medianShift = ...
            filteredMedian - rawMedian;

        rawRange = ...
            max(rawWindow) - min(rawWindow);

        filteredRange = ...
            max(filteredWindow) - ...
            min(filteredWindow);

        rawStd = ...
            std(rawWindow);

        filteredStd = ...
            std(filteredWindow);

        rawSlope = ...
            localLinearSlope( ...
                auditTime, ...
                rawWindow);

        filteredSlope = ...
            localLinearSlope( ...
                auditTime, ...
                filteredWindow);

        if rawRange > 0

            rangeReduction = ...
                100 * ...
                (1 - filteredRange / rawRange);

        else

            rangeReduction = NaN;

        end

        if rawStd > 0

            stdReduction = ...
                100 * ...
                (1 - filteredStd / rawStd);

        else

            stdReduction = NaN;

        end

        %% Store audit metrics

        coordinateColumn(iCoordinate) = ...
            coordinate;

        columnIndexColumn(iCoordinate) = ...
            columnIndex;

        rawMedianColumn(iCoordinate) = ...
            rawMedian;

        filteredMedianColumn(iCoordinate) = ...
            filteredMedian;

        medianShiftColumn(iCoordinate) = ...
            medianShift;

        absoluteMedianShiftColumn(iCoordinate) = ...
            abs(medianShift);

        rawRangeColumn(iCoordinate) = ...
            rawRange;

        filteredRangeColumn(iCoordinate) = ...
            filteredRange;

        rangeReductionColumn(iCoordinate) = ...
            rangeReduction;

        rawStdColumn(iCoordinate) = ...
            rawStd;

        filteredStdColumn(iCoordinate) = ...
            filteredStd;

        stdReductionColumn(iCoordinate) = ...
            stdReduction;

        rawSlopeColumn(iCoordinate) = ...
            rawSlope;

        filteredSlopeColumn(iCoordinate) = ...
            filteredSlope;

    end

    filteredMotion.Data = filteredData;

    %% Construct audit table

    audit = table( ...
        coordinateColumn, ...
        columnIndexColumn, ...
        repmat(sampleRateHz, numCoordinates, 1), ...
        repmat(cutoffHz, numCoordinates, 1), ...
        repmat(prototypeOrder, numCoordinates, 1), ...
        repmat(2 * prototypeOrder, numCoordinates, 1), ...
        repmat(auditWindow(1), numCoordinates, 1), ...
        repmat(auditWindow(2), numCoordinates, 1), ...
        repmat(numAuditSamples, numCoordinates, 1), ...
        rawMedianColumn, ...
        filteredMedianColumn, ...
        medianShiftColumn, ...
        absoluteMedianShiftColumn, ...
        rawRangeColumn, ...
        filteredRangeColumn, ...
        rangeReductionColumn, ...
        rawStdColumn, ...
        filteredStdColumn, ...
        stdReductionColumn, ...
        rawSlopeColumn, ...
        filteredSlopeColumn, ...
        'VariableNames', { ...
            'Coordinate', ...
            'ColumnIndex', ...
            'SampleRateHz', ...
            'CutoffHz', ...
            'PrototypeOrder', ...
            'EffectiveZeroPhaseOrder', ...
            'AuditWindowStart', ...
            'AuditWindowEnd', ...
            'NumAuditSamples', ...
            'RawMedian', ...
            'FilteredMedian', ...
            'MedianShift', ...
            'AbsoluteMedianShift', ...
            'RawRange', ...
            'FilteredRange', ...
            'RangeReductionPct', ...
            'RawStandardDeviation', ...
            'FilteredStandardDeviation', ...
            'StandardDeviationReductionPct', ...
            'RawSlopePerSecond', ...
            'FilteredSlopePerSecond'});

    %% Assemble result

    result = struct;

    result.Motion = filteredMotion;
    result.Audit = audit;

    result.SampleRateHz = sampleRateHz;

    result.CutoffHz = cutoffHz;
    result.PrototypeOrder = prototypeOrder;

    result.EffectiveZeroPhaseOrder = ...
        2 * prototypeOrder;

    result.FilteredCoordinates = ...
        coordinateNames;

    result.AuditWindow = ...
        auditWindow(:).';

    result.NumAuditSamples = ...
        numAuditSamples;

    result.SourceFile = ...
        sourceFile;

end


function slope = localLinearSlope(time, values)
%LOCALLINEARSLOPE Return least-squares linear slope per second.

    time = time(:);
    values = values(:);

    assert(numel(time) == numel(values), ...
        "Time and value vectors must have equal lengths.");

    if numel(time) < 2

        slope = NaN;
        return;

    end

    shiftedTime = ...
        time - time(1);

    coefficients = ...
        polyfit( ...
            shiftedTime, ...
            values, ...
            1);

    slope = ...
        coefficients(1);

end