function app = interactiveForceCapacityEditor(modelFile)
%INTERACTIVEFORCECAPACITYEDITOR Interactive editor for all ForceSet objects.
%
% app = modelprep.interactiveForceCapacityEditor(modelFile)
%
% Every direct ForceSet object is displayed, including muscles, actuators,
% passive forces, and any future concrete object classes found in the XML.
%
% Editable concepts:
%   1) appliesForce state for every ForceSet object.
%   2) primary scalar capacity where available:
%        Muscle            -> max_isometric_force
%        PointActuator      -> optimal_force
%        TorqueActuator     -> optimal_force
%        CoordinateActuator -> optimal_force
%
% BushingForce and other objects without one clear scalar capacity remain
% visible and can be enabled/disabled. Their stiffness/damping properties
% are deliberately not collapsed into a single "force" value.
%
% Capacity operations:
%   Scale to % of current
%   Set absolute
%
% Enable-state operations:
%   Enable selected
%   Disable selected
%
% Save As writes a new model and an audit CSV.

    if nargin < 1 || strlength(string(modelFile)) == 0

        [fileName, fileFolder] = ...
            uigetfile( ...
                {'*.osim','OpenSim model (*.osim)'}, ...
                'Select OpenSim model');

        if isequal(fileName,0)
            app = [];
            return;
        end

        modelFile = string(fullfile( ...
            fileFolder, fileName));
    else
        modelFile = string(modelFile);
    end

    inspection = ...
        modelprep.inspectForceCapacities(modelFile);

    data = inspection.Capacities;

    % Keep a complete backing table. The uitable below is only a filtered
    % view of this master table so edits persist when Scope changes.
    masterData = data;
    visibleRowIndices = (1:height(masterData)).';

    %% Window

    fig = uifigure( ...
        "Name", ...
        "OpenSim ForceSet Editor", ...
        "Position", ...
        [80 80 1380 760]);

    mainGrid = uigridlayout(fig, [3 1]);
    mainGrid.RowHeight = {104, '1x', 58};
    mainGrid.Padding = [10 10 10 10];

    %% Toolbar

    controls = uigridlayout(mainGrid, [2 10]);
    controls.Layout.Row = 1;

    controls.ColumnWidth = { ...
        80, 180, ...
        85, 180, ...
        55, 90, ...
        100, 110, 110, '1x'};

    lblModel = uilabel(controls, "Text", "Model:");
    lblModel.Layout.Row = 1;
    lblModel.Layout.Column = 1;

    modelPathLabel = uilabel( ...
        controls, ...
        "Text", char(modelFile), ...
        "Tooltip", char(modelFile));
    modelPathLabel.Layout.Row = 1;
    modelPathLabel.Layout.Column = [2 10];

    lblScope = uilabel(controls, "Text", "Scope");
    lblScope.Layout.Row = 2;
    lblScope.Layout.Column = 1;

    scopeDropdown = uidropdown( ...
        controls, ...
        "Items", { ...
            'All force objects', ...
            'All scalable objects', ...
            'All muscles', ...
            'Flexion', ...
            'Extension', ...
            'Excluded/other muscles', ...
            'All actuators', ...
            'Torque actuators', ...
            'Point actuators', ...
            'Passive forces', ...
            'Enabled objects', ...
            'Disabled objects', ...
            'Manual selection'}, ...
        "Value", 'All scalable objects', ...
        "ValueChangedFcn", @scopeChanged);
    scopeDropdown.Layout.Row = 2;
    scopeDropdown.Layout.Column = 2;

    lblOp = uilabel(controls, "Text", "Capacity");
    lblOp.Layout.Row = 2;
    lblOp.Layout.Column = 3;

    operationDropdown = uidropdown( ...
        controls, ...
        "Items", { ...
            'Scale to % of current', ...
            'Set absolute'}, ...
        "Value", 'Scale to % of current');
    operationDropdown.Layout.Row = 2;
    operationDropdown.Layout.Column = 4;

    lblValue = uilabel(controls, "Text", "Value");
    lblValue.Layout.Row = 2;
    lblValue.Layout.Column = 5;

    valueField = uieditfield( ...
        controls, "numeric", ...
        "Value", 100, ...
        "Limits", [0 Inf]);
    valueField.Layout.Row = 2;
    valueField.Layout.Column = 6;

    previewButton = uibutton( ...
        controls, ...
        "Text", "Preview", ...
        "ButtonPushedFcn", @previewCapacity);
    previewButton.Layout.Row = 2;
    previewButton.Layout.Column = 7;

    enableButton = uibutton( ...
        controls, ...
        "Text", "Enable selected", ...
        "ButtonPushedFcn", @(~,~) setSelectedEnabled(true));
    enableButton.Layout.Row = 2;
    enableButton.Layout.Column = 8;

    disableButton = uibutton( ...
        controls, ...
        "Text", "Disable selected", ...
        "ButtonPushedFcn", @(~,~) setSelectedEnabled(false));
    disableButton.Layout.Row = 2;
    disableButton.Layout.Column = 9;

    resetButtonTop = uibutton( ...
        controls, ...
        "Text", "Reset all", ...
        "ButtonPushedFcn", @resetAll);
    resetButtonTop.Layout.Row = 2;
    resetButtonTop.Layout.Column = 10;

    %% Data table

    tableHandle = uitable( ...
        mainGrid, ...
        "Data", masterData, ...
        "ColumnEditable", ...
        [true false false false false false false true false false true false false], ...
        "ColumnName", { ...
            'Select', ...
            'Name', ...
            'Object type', ...
            'Category', ...
            'Group', ...
            'Enabled', ...
            'Enabled explicit', ...
            'Proposed enabled', ...
            'Capacity parameter', ...
            'Current', ...
            'Proposed', ...
            'Unit', ...
            'Scalable'}, ...
        "CellEditCallback", @tableEdited);

    tableHandle.Layout.Row = 2;

    tableHandle.ColumnWidth = { ...
        55, 175, 170, 95, 120, ...
        70, 95, 105, 150, 85, 85, 120, 70};

    %% Footer

    bottom = uigridlayout(mainGrid, [1 6]);
    bottom.Layout.Row = 3;
    bottom.ColumnWidth = {'1x', 135, 120, 125, 120, 100};

    statusLabel = uilabel( ...
        bottom, ...
        "Text", localStatusText(masterData, numel(visibleRowIndices)));
    statusLabel.Layout.Column = 1;

    selectScopeButton = uibutton( ...
        bottom, ...
        "Text", "Select visible", ...
        "ButtonPushedFcn", @selectVisibleRows);
    selectScopeButton.Layout.Column = 2;

    resetPreviewButton = uibutton( ...
        bottom, ...
        "Text", "Reset changes", ...
        "ButtonPushedFcn", @resetAll);
    resetPreviewButton.Layout.Column = 3;

    saveConfigButton = uibutton( ...
        bottom, ...
        "Text", "Save Config...", ...
        "ButtonPushedFcn", @saveConfig);
    saveConfigButton.Layout.Column = 4;

    saveButton = uibutton( ...
        bottom, ...
        "Text", "Save Model As...", ...
        "ButtonPushedFcn", @saveModel);
    saveButton.Layout.Column = 5;

    closeButton = uibutton( ...
        bottom, ...
        "Text", "Close", ...
        "ButtonPushedFcn", @(~,~) delete(fig));
    closeButton.Layout.Column = 6;

    app = struct;
    app.Figure = fig;
    app.Table = tableHandle;
    app.ModelFile = modelFile;

    %% Callbacks

    function scopeChanged(~,~)
        % Scope controls visibility only. It must never modify selection.
        syncVisibleToMaster();
        refreshScopeView();
    end


    function selectVisibleRows(~,~)

        syncVisibleToMaster();

        % This is the ONLY scope-level control that intentionally changes
        % selection. Make the visible scope the complete active selection.
        masterData.Select(:) = false;
        masterData.Select(visibleRowIndices) = true;

        refreshScopeView();
    end


    function refreshScopeView()

        scope = string(scopeDropdown.Value);

        mask = localScopeMask( ...
            masterData, ...
            scope);

        visibleRowIndices = find(mask);

        % Manual selection intentionally exposes the complete ForceSet.
        if scope == "Manual selection"
            visibleRowIndices = (1:height(masterData)).';
        end

        tableHandle.Data = ...
            masterData(visibleRowIndices, :);

        updateStatus();
    end


    function syncVisibleToMaster()

        if isempty(visibleRowIndices)
            return;
        end

        visibleData = tableHandle.Data;

        if height(visibleData) ~= numel(visibleRowIndices)
            return;
        end

        masterData(visibleRowIndices, :) = ...
            visibleData;
    end


    function previewCapacity(~,~)

        syncVisibleToMaster();

        selected = false(height(masterData),1);
        selected(visibleRowIndices) = ...
            logical(masterData.Select(visibleRowIndices));

        scalableSelected = ...
            selected & ...
            masterData.HasScalarCapacity;

        if ~any(selected)
            uialert(fig, ...
                "No rows are selected.", ...
                "Nothing to preview");
            return;
        end

        if ~any(scalableSelected)
            uialert(fig, ...
                "The selected objects do not expose a supported single scalar force-capacity parameter.", ...
                "No scalable objects");
            return;
        end

        operation = string(operationDropdown.Value);
        value = double(valueField.Value);

        switch operation

            case "Scale to % of current"

                if value <= 0
                    uialert(fig, ...
                        "Scale percentage must be greater than zero.", ...
                        "Invalid value");
                    return;
                end

                masterData.ProposedValue(scalableSelected) = ...
                    masterData.CurrentValue(scalableSelected) .* ...
                    (value / 100);

            case "Set absolute"

                selectedUnits = unique( ...
                    masterData.UnitNote(scalableSelected));

                if numel(selectedUnits) > 1
                    uialert(fig, ...
                        "Absolute assignment is blocked when the selection contains different physical units. Select a homogeneous class/group instead.", ...
                        "Mixed units");
                    return;
                end

                if value <= 0
                    uialert(fig, ...
                        "Absolute capacity must be greater than zero.", ...
                        "Invalid value");
                    return;
                end

                masterData.ProposedValue(scalableSelected) = value;
        end

        refreshScopeView();
    end


    function setSelectedEnabled(newState)

        syncVisibleToMaster();

        selected = false(height(masterData),1);
        selected(visibleRowIndices) = ...
            logical(masterData.Select(visibleRowIndices));

        if ~any(selected)
            uialert(fig, ...
                "No rows are selected.", ...
                "Nothing selected");
            return;
        end

        masterData.ProposedAppliesForce(selected) = ...
            logical(newState);

        % Enabled/disabled scopes can change membership after the edit.
        refreshScopeView();
    end


    function resetAll(~,~)

        masterData.Select(:) = false;
        masterData.ProposedValue = ...
            masterData.CurrentValue;
        masterData.ProposedAppliesForce = ...
            masterData.AppliesForce;

        refreshScopeView();
    end


    function tableEdited(~,event)

        visibleData = tableHandle.Data;

        row = event.Indices(1);
        column = event.Indices(2);

        masterRow = visibleRowIndices(row);

        % ProposedValue is column 11.
        if column == 11

            if ~visibleData.HasScalarCapacity(row)

                visibleData.ProposedValue(row) = ...
                    visibleData.CurrentValue(row);

                tableHandle.Data = visibleData;

                masterData.ProposedValue(masterRow) = ...
                    masterData.CurrentValue(masterRow);

                uialert(fig, ...
                    "This object has no supported single scalar force-capacity parameter. Its appliesForce state can still be changed.", ...
                    "Capacity not editable");
                return;
            end

            proposed = visibleData.ProposedValue(row);

            if ~isfinite(proposed) || proposed <= 0

                visibleData.ProposedValue(row) = ...
                    visibleData.CurrentValue(row);

                tableHandle.Data = visibleData;

                masterData.ProposedValue(masterRow) = ...
                    masterData.CurrentValue(masterRow);

                uialert(fig, ...
                    "Proposed capacity must be greater than zero.", ...
                    "Invalid value");
                return;
            end
        end

        % Copy the edited visible row back into the complete master table.
        masterData(masterRow, :) = ...
            visibleData(row, :);

        updateStatus();
    end


    function saveConfig(~,~)

        syncVisibleToMaster();

        valueChanged = ...
            masterData.HasScalarCapacity & ...
            abs(masterData.ProposedValue - masterData.CurrentValue) > ...
            max(1e-12, ...
                1e-10 .* abs(masterData.CurrentValue));

        enabledChanged = ...
            masterData.ProposedAppliesForce ~= ...
            masterData.AppliesForce;

        changed = ...
            valueChanged | enabledChanged;

        if ~any(changed)

            uialert(fig, ...
                "No capacity values or appliesForce states have changed. Preview a change before saving a configuration.", ...
                "Nothing to save");
            return;
        end

        [inputFolder,inputStem,~] = ...
            fileparts(modelFile);

        suggestedName = ...
            string(inputStem) + ...
            "_force_config.json";

        [fileName,fileFolder] = ...
            uiputfile( ...
                {'*.json','Force configuration (*.json)'}, ...
                'Save reusable force configuration', ...
                fullfile(inputFolder, suggestedName));

        if isequal(fileName,0)
            return;
        end

        configFile = ...
            string(fullfile(fileFolder,fileName));

        try

            configResult = ...
                modelprep.saveForceCapacityConfig( ...
                    modelFile, ...
                    masterData, ...
                    configFile, ...
                    "DefaultApplyMode", "target");

        catch ME

            uialert(fig, ...
                ME.message, ...
                "Configuration save failed");
            return;
        end

        uialert(fig, ...
            sprintf( ...
                "Saved %d reusable ForceSet configuration entries.\n\nConfig:\n%s\n\nThe file stores both exact target values and relative scale factors.", ...
                configResult.EntryCount, ...
                configFile), ...
            "Configuration saved");

        statusLabel.Text = sprintf( ...
            "Saved force configuration with %d entries.", ...
            configResult.EntryCount);
    end


    function saveModel(~,~)

        syncVisibleToMaster();

        current = masterData;

        valueChanged = ...
            current.HasScalarCapacity & ...
            abs(current.ProposedValue - current.CurrentValue) > ...
            max(1e-12, 1e-10 .* abs(current.CurrentValue));

        enabledChanged = ...
            current.ProposedAppliesForce ~= ...
            current.AppliesForce;

        changed = ...
            valueChanged | enabledChanged;

        if ~any(changed)

            uialert(fig, ...
                "No force-object values or enabled states have changed.", ...
                "Nothing to save");
            return;
        end

        [inputFolder,inputStem,~] = ...
            fileparts(modelFile);

        suggestedName = ...
            string(inputStem) + ...
            "_force_adjusted.osim";

        [fileName,fileFolder] = ...
            uiputfile( ...
                {'*.osim','OpenSim model (*.osim)'}, ...
                'Save adjusted OpenSim model', ...
                fullfile(inputFolder, suggestedName));

        if isequal(fileName,0)
            return;
        end

        outputModelFile = ...
            string(fullfile(fileFolder,fileName));

        [auditFolder,auditStem,~] = ...
            fileparts(outputModelFile);

        auditFile = string(fullfile( ...
            auditFolder, ...
            string(auditStem) + ...
            "_force_capacity_audit.csv"));

        changes = current( ...
            changed, ...
            { ...
                'Name', ...
                'ObjectType', ...
                'ProposedAppliesForce', ...
                'CapacityParameter', ...
                'ProposedValue'});

        try

            result = ...
                modelprep.applyForceCapacityChanges( ...
                    modelFile, ...
                    outputModelFile, ...
                    changes, ...
                    "Overwrite", true, ...
                    "AuditFile", auditFile);

        catch ME

            uialert(fig, ...
                ME.message, ...
                "Save failed");
            return;
        end

        uialert(fig, ...
            sprintf( ...
                "Saved %d verified changes.\n\nModel:\n%s\n\nAudit:\n%s", ...
                height(result.Audit), ...
                outputModelFile, ...
                auditFile), ...
            "Model saved");

        statusLabel.Text = sprintf( ...
            "Saved %d verified changes.", ...
            height(result.Audit));
    end


    function updateStatus()

        statusLabel.Text = ...
            localStatusText( ...
                masterData, ...
                numel(visibleRowIndices));
    end

    % Apply initial dropdown filter after all controls/callbacks exist.
    % Filtering never implies selection.
    refreshScopeView();
end


function textValue = localStatusText(data, visibleCount)

    selectedCount = nnz(data.Select);

    valueChanged = ...
        data.HasScalarCapacity & ...
        abs(data.ProposedValue - data.CurrentValue) > ...
        max(1e-12, ...
            1e-10 .* abs(data.CurrentValue));

    enabledChanged = ...
        data.ProposedAppliesForce ~= ...
        data.AppliesForce;

    textValue = sprintf( ...
        "%d visible / %d total | %d selected total | %d capacity changes | %d enable-state changes", ...
        visibleCount, ...
        height(data), ...
        selectedCount, ...
        nnz(valueChanged), ...
        nnz(enabledChanged));
end


function mask = localScopeMask(data, scope)

    switch scope

        case "All force objects"
            mask = true(height(data),1);

        case "All scalable objects"
            mask = data.HasScalarCapacity;

        case "All muscles"
            mask = data.Category == "Muscle";

        case "Flexion"
            mask = ...
                data.Category == "Muscle" & ...
                data.Group == "Flexion";

        case "Extension"
            mask = ...
                data.Category == "Muscle" & ...
                data.Group == "Extension";

        case "Excluded/other muscles"
            mask = ...
                data.Category == "Muscle" & ...
                data.Group == "Excluded/other";

        case "All actuators"
            mask = data.Category == "Actuator";

        case "Torque actuators"
            mask = data.ObjectType == "TorqueActuator";

        case "Point actuators"
            mask = data.ObjectType == "PointActuator";

        case "Passive forces"
            mask = data.Category == "Passive force";

        case "Enabled objects"
            % Use the proposed state so this filtered view responds
            % immediately to enable/disable edits.
            mask = data.ProposedAppliesForce;

        case "Disabled objects"
            mask = ~data.ProposedAppliesForce;

        case "Manual selection"
            mask = true(height(data),1);

        otherwise
            error( ...
                "ForceCapacityUI:UnknownScope", ...
                "Unknown scope '%s'.", scope);
    end
end
