function result = loadForceCapacityConfig(configFile)
%LOADFORCECAPACITYCONFIG Read and validate a ForceSet JSON configuration.
%
% result = modelprep.loadForceCapacityConfig(configFile)

    configFile = string(configFile);

    assert(isfile(configFile), ...
        "ForceCapacityConfig:FileMissing", ...
        "Force-capacity config was not found:\n%s", ...
        configFile);

    [~,~,extension] = fileparts(configFile);

    assert(strcmpi(extension, ".json"), ...
        "ForceCapacityConfig:InvalidExtension", ...
        "Force-capacity config must use the .json extension.");

    jsonText = fileread(configFile);

    try
        config = jsondecode(jsonText);
    catch exception
        error( ...
            "ForceCapacityConfig:JsonParseFailed", ...
            "Could not parse JSON config:\n%s\n\n%s", ...
            configFile, exception.message);
    end

    requiredTopFields = [ ...
        "Schema"
        "Version"
        "SourceModel"
        "DefaultApplyMode"
        "EntryCount"
        "Entries"
    ];

    assert(all(isfield(config, requiredTopFields)), ...
        "ForceCapacityConfig:SchemaFieldsMissing", ...
        "Configuration is missing required top-level fields.");

    assert(strcmp( ...
        string(config.Schema), ...
        "headneck-force-capacity-config"), ...
        "ForceCapacityConfig:WrongSchema", ...
        "Unexpected configuration schema '%s'.", ...
        string(config.Schema));

    assert(double(config.Version) == 1, ...
        "ForceCapacityConfig:UnsupportedVersion", ...
        "Unsupported force-capacity config version: %g.", ...
        double(config.Version));

    assert(any(strcmpi( ...
        string(config.DefaultApplyMode), ...
        ["target","scale"])), ...
        "ForceCapacityConfig:InvalidApplyMode", ...
        "DefaultApplyMode must be 'target' or 'scale'.");

    entries = config.Entries;

    if isstruct(entries)
        entries = entries(:);
    end

    assert(double(config.EntryCount) == numel(entries), ...
        "ForceCapacityConfig:EntryCountMismatch", ...
        "EntryCount does not match the number of JSON entries.");

    requiredEntryFields = [ ...
        "Name"
        "ObjectType"
        "CapacityParameter"
        "CapacityAction"
        "AppliesForceAction"
        "TargetAppliesForce"
    ];

    for iEntry = 1:numel(entries)

        assert(all(isfield(entries(iEntry), requiredEntryFields)), ...
            "ForceCapacityConfig:EntryFieldsMissing", ...
            "Configuration entry %d is missing required fields.", ...
            iEntry);

        capacityAction = ...
            lower(string(entries(iEntry).CapacityAction));

        appliesAction = ...
            lower(string(entries(iEntry).AppliesForceAction));

        assert(any(capacityAction == ["set","preserve"]), ...
            "ForceCapacityConfig:InvalidCapacityAction", ...
            "Invalid CapacityAction in entry %d.", ...
            iEntry);

        assert(any(appliesAction == ["set","preserve"]), ...
            "ForceCapacityConfig:InvalidAppliesForceAction", ...
            "Invalid AppliesForceAction in entry %d.", ...
            iEntry);

        if capacityAction == "set"

            assert(isfield(entries(iEntry), "TargetValue") && ...
                   isfield(entries(iEntry), "ScaleFactor") && ...
                   isfield(entries(iEntry), "ReferenceValue"), ...
                "ForceCapacityConfig:CapacityFieldsMissing", ...
                "Capacity entry %d lacks target/scaling fields.", ...
                iEntry);

            assert(isfinite(double(entries(iEntry).TargetValue)) && ...
                   double(entries(iEntry).TargetValue) > 0, ...
                "ForceCapacityConfig:InvalidTargetValue", ...
                "Entry %d has an invalid TargetValue.", ...
                iEntry);

            assert(isfinite(double(entries(iEntry).ScaleFactor)) && ...
                   double(entries(iEntry).ScaleFactor) > 0, ...
                "ForceCapacityConfig:InvalidScaleFactor", ...
                "Entry %d has an invalid ScaleFactor.", ...
                iEntry);
        end
    end

    result = struct;
    result.ConfigFile = configFile;
    result.Config = config;
end
