function result = analyzeStrengthGrid(projectCfg, varargin)
%ANALYZESTRENGTHGRID Run the complete SO strength-grid analysis workflow.
%
% result = soopt.analyzeStrengthGrid(projectCfg)
%
% This is the user-facing orchestration layer for the Static Optimization
% muscle/reserve strength grid. It introduces no new feasibility, Pareto,
% monotonicity, inference, or proposal mathematics. Instead it coordinates
% the validated +soopt components in this order:
%
%   1. discoverStrengthConfigPool
%   2. summarizeStrengthConfigurations
%   3. findParetoFrontier
%   4. auditFeasibilityMonotonicity
%   5. buildStrengthGridPlan        [when safe]
%   6. proposeNextConfigurations    [when safe]
%   7. plotFeasibilityMap           [optional]
%
% PLANNING SAFETY
%
% Inference-based planning is available only when:
%
%   - at least one canonical candidate JSON exists;
%   - the discovered JSON pool forms a complete Cartesian grid; and
%   - the assessed configuration evidence is monotonic.
%
% Observed summary/Pareto results and the feasibility plot remain available
% even when planning is withheld.
%
% NAME-VALUE OPTIONS
%
%   ConfigDirectory
%       Optional explicit strength-configuration JSON directory. Default ""
%       delegates directory resolution to discoverStrengthConfigPool.
%
%   MaxProposals
%       Positive integer or Inf. Default 1.
%
%   CreateFigure
%       Logical scalar. Default true.
%
%   FigureVisible
%       "on" or "off". Default "on".
%
%   ShowConfigLabels
%       Logical scalar. Default true.
%
%   FigureTitle
%       Plot title. Default:
%       "Static Optimization strength feasibility map"
%
% RETURN STRUCT
%
%   SchemaVersion
%   ConfigPool
%   Summary
%   ParetoFrontier
%   MonotonicityAudit
%   PlanningAvailable
%   PlanningStatus
%   PlanningReason
%   GridPlan
%   Proposals
%   Figure
%   Axes
%   PlotInfo
%
% IMPORTANT
%
% ParetoFrontier contains only configurations that were actually assessed,
% feasible, and nondominated. Inferred feasible points are never promoted
% into the reported Pareto frontier.
%
% The orchestration function does not write files.

    %% Parse inputs

    parser = ...
        inputParser;

    parser.FunctionName = ...
        "soopt.analyzeStrengthGrid";

    addRequired(parser, ...
        "projectCfg", ...
        @(x) isstruct(x) && isscalar(x));

    addParameter(parser, ...
        "ConfigDirectory", ...
        "", ...
        @(x) ...
            (ischar(x) && (isrow(x) || isempty(x))) || ...
            (isstring(x) && isscalar(x) && ~ismissing(x)));

    addParameter(parser, ...
        "MaxProposals", ...
        1, ...
        @(x) ...
            isnumeric(x) && ...
            isscalar(x) && ...
            (isinf(x) || ...
                (isfinite(x) && x >= 1 && x == fix(x))));

    addParameter(parser, ...
        "CreateFigure", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "FigureVisible", ...
        "on", ...
        @(x) ...
            (ischar(x) && isrow(x)) || ...
            (isstring(x) && isscalar(x) && ~ismissing(x)));

    addParameter(parser, ...
        "ShowConfigLabels", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "FigureTitle", ...
        "Static Optimization strength feasibility map", ...
        @(x) ...
            (ischar(x) && isrow(x)) || ...
            (isstring(x) && isscalar(x) && ~ismissing(x)));

    parse(parser, ...
        projectCfg, ...
        varargin{:});

    configDirectory = ...
        string(parser.Results.ConfigDirectory);

    maxProposals = ...
        double(parser.Results.MaxProposals);

    createFigure = ...
        logical(parser.Results.CreateFigure);

    figureVisible = ...
        lower(string(parser.Results.FigureVisible));

    showConfigLabels = ...
        logical(parser.Results.ShowConfigLabels);

    figureTitle = ...
        string(parser.Results.FigureTitle);

    assert(ismember(figureVisible, ["on", "off"]), ...
        "StrengthGridAnalysis:InvalidFigureVisible", ...
        "FigureVisible must be ""on"" or ""off"".");

    %% Discover candidate JSON pool

    if strlength(configDirectory) > 0

        configPool = ...
            soopt.discoverStrengthConfigPool( ...
                projectCfg, ...
                "ConfigDirectory", ...
                configDirectory);

    else

        configPool = ...
            soopt.discoverStrengthConfigPool( ...
                projectCfg);
    end

    %% Summarize observed configuration evidence

    summary = ...
        soopt.summarizeStrengthConfigurations( ...
            projectCfg);

    summary = ...
        soopt.findParetoFrontier( ...
            summary);

    paretoFrontier = ...
        summary( ...
            summary.IsParetoOptimal, ...
            :);

    monotonicityAudit = ...
        soopt.auditFeasibilityMonotonicity( ...
            summary);

    %% Determine whether inference-based planning is safe

    planningAvailable = ...
        true;

    planningStatus = ...
        "AVAILABLE";

    planningReason = ...
        "Candidate pool is nonempty and Cartesian-complete, and " + ...
        "assessed feasibility is monotonic.";

    if configPool.DiscoveredConfigurationCount == 0

        planningAvailable = ...
            false;

        planningStatus = ...
            "UNAVAILABLE_EMPTY_CONFIG_POOL";

        planningReason = ...
            "No canonical strength-configuration JSON files were discovered.";

    elseif ~configPool.IsCompleteCartesianGrid

        planningAvailable = ...
            false;

        planningStatus = ...
            "UNAVAILABLE_INCOMPLETE_CONFIG_POOL";

        planningReason = ...
            "The discovered strength-configuration JSON pool does not " + ...
            "contain every combination implied by its muscle and " + ...
            "actuator percentage values.";

    elseif ~monotonicityAudit.IsMonotonic

        planningAvailable = ...
            false;

        planningStatus = ...
            "UNAVAILABLE_MONOTONICITY_VIOLATION";

        planningReason = ...
            sprintf( ...
                "Assessed configuration evidence contains %d " + ...
                "monotonicity violation(s); inference-based planning " + ...
                "was withheld.", ...
                monotonicityAudit.ViolationCount);
    end

    %% Build grid plan and proposals only when safe

    if planningAvailable

        gridPlan = ...
            soopt.buildStrengthGridPlan( ...
                summary, ...
                configPool.MuscleGrid, ...
                configPool.ActuatorGrid);

        proposals = ...
            soopt.proposeNextConfigurations( ...
                gridPlan, ...
                "MaxProposals", ...
                maxProposals);

    else

        gridPlan = ...
            localEmptyGridPlan();

        proposals = ...
            localEmptyProposalTable();
    end

    %% Optional observed feasibility / Pareto visualization

    figureHandle = ...
        gobjects(0,1);

    axesHandle = ...
        gobjects(0,1);

    plotInfo = ...
        struct;

    if createFigure

        [figureHandle, axesHandle, plotInfo] = ...
            soopt.plotFeasibilityMap( ...
                summary, ...
                "Visible", ...
                    figureVisible, ...
                "ShowConfigLabels", ...
                    showConfigLabels, ...
                "Title", ...
                    figureTitle);
    end

    %% Return orchestration result

    result = struct;

    result.SchemaVersion = ...
        1;

    result.ConfigPool = ...
        configPool;

    result.Summary = ...
        summary;

    result.ParetoFrontier = ...
        paretoFrontier;

    result.MonotonicityAudit = ...
        monotonicityAudit;

    result.PlanningAvailable = ...
        planningAvailable;

    result.PlanningStatus = ...
        planningStatus;

    result.PlanningReason = ...
        planningReason;

    result.GridPlan = ...
        gridPlan;

    result.Proposals = ...
        proposals;

    result.Figure = ...
        figureHandle;

    result.Axes = ...
        axesHandle;

    result.PlotInfo = ...
        plotInfo;
end


function T = localEmptyGridPlan()

    T = ...
        table( ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            false(0,1), ...
            false(0,1), ...
            false(0,1), ...
            false(0,1), ...
            strings(0,1), ...
            false(0,1), ...
            strings(0,1), ...
            strings(0,1), ...
            'VariableNames', { ...
                'ConfigId', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ExistsInSummary', ...
                'ExistingIncomplete', ...
                'AssessmentComplete', ...
                'ObservedFeasible', ...
                'GridStatus', ...
                'NeedsAssessment', ...
                'FeasibleInferenceSources', ...
                'InfeasibleInferenceSources'});
end


function T = localEmptyProposalTable()

    T = ...
        table( ...
            zeros(0,1), ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            false(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            'VariableNames', { ...
                'PriorityRank', ...
                'ConfigId', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ExistingIncomplete', ...
                'FeasibleOutcomeResolvedCount', ...
                'InfeasibleOutcomeResolvedCount', ...
                'WorstCaseResolvedCount', ...
                'BestCaseResolvedCount', ...
                'TotalResolutionPotential', ...
                'ResolutionImbalance', ...
                'GridCenterDistance'});
end
