function audit = auditFeasibilityMonotonicity(summary)
%AUDITFEASIBILITYMONOTONICITY Audit expected monotone SO feasibility.
%
% audit = soopt.auditFeasibilityMonotonicity(summary)
%
% Input must be a configuration-level table containing at least:
%
%   ConfigId
%   MusclePercent
%   ActuatorPercent
%   AssessmentComplete
%   IsFeasible
%
% Only assessed configurations participate:
%
%   AssessmentComplete == true
%
% EXPECTED MONOTONICITY
%
% If configuration A is feasible, then any assessed configuration B with:
%
%   B.MusclePercent   >= A.MusclePercent
%   B.ActuatorPercent >= A.ActuatorPercent
%
% should also be feasible.
%
% A monotonicity violation therefore occurs when:
%
%   A is assessed and feasible;
%   B is assessed and infeasible;
%   A.MusclePercent   <= B.MusclePercent;
%   A.ActuatorPercent <= B.ActuatorPercent.
%
% Incomparable points do not constitute violations.
%
% RETURN STRUCT
%
%   SchemaVersion
%   IsMonotonic
%   ViolationCount
%   AssessedConfigurations
%   FeasibleConfigurations
%   InfeasibleConfigurations
%   Violations
%
% Violations is a table with:
%
%   LowerFeasibleConfigId
%   LowerMusclePercent
%   LowerActuatorPercent
%   HigherInfeasibleConfigId
%   HigherMusclePercent
%   HigherActuatorPercent
%   MuscleIncrease
%   ActuatorIncrease
%
% The function is intentionally SIDE-EFFECT FREE and has no filesystem or
% OpenSim dependencies.

    %% Validate input

    assert(istable(summary), ...
        "StrengthMonotonicity:InvalidInput", ...
        "Input must be a table.");

    requiredVariables = [
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
        "AssessmentComplete"
        "IsFeasible"
    ];

    missingVariables = ...
        requiredVariables( ...
            ~ismember( ...
                requiredVariables, ...
                string(summary.Properties.VariableNames)));

    assert(isempty(missingVariables), ...
        "StrengthMonotonicity:VariablesMissing", ...
        "Input table is missing required variables: %s", ...
        strjoin(missingVariables, ", "));

    configIds = ...
        string(summary.ConfigId);

    musclePercent = ...
        double(summary.MusclePercent);

    actuatorPercent = ...
        double(summary.ActuatorPercent);

    assessmentComplete = ...
        logical(summary.AssessmentComplete);

    isFeasible = ...
        logical(summary.IsFeasible);

    assert(all(~ismissing(configIds) & strlength(configIds) > 0), ...
        "StrengthMonotonicity:InvalidConfigId", ...
        "ConfigId must contain nonempty string values.");

    assert(numel(unique(configIds)) == height(summary), ...
        "StrengthMonotonicity:DuplicateConfigId", ...
        "ConfigId values must be unique.");

    assert(all(isfinite(musclePercent) & musclePercent > 0), ...
        "StrengthMonotonicity:InvalidMusclePercent", ...
        "MusclePercent must contain finite positive values.");

    assert(all(isfinite(actuatorPercent) & actuatorPercent > 0), ...
        "StrengthMonotonicity:InvalidActuatorPercent", ...
        "ActuatorPercent must contain finite positive values.");

    %% Identify assessed feasible and infeasible rows

    assessedIndices = ...
        find(assessmentComplete);

    feasibleIndices = ...
        find( ...
            assessmentComplete & ...
            isFeasible);

    infeasibleIndices = ...
        find( ...
            assessmentComplete & ...
            ~isFeasible);

    %% Find violating feasible-lower -> infeasible-higher pairs

    lowerFeasibleIndex = ...
        zeros(0,1);

    higherInfeasibleIndex = ...
        zeros(0,1);

    for iFeasible = feasibleIndices.'

        higherOrEqualMuscle = ...
            musclePercent(infeasibleIndices) >= ...
            musclePercent(iFeasible);

        higherOrEqualActuator = ...
            actuatorPercent(infeasibleIndices) >= ...
            actuatorPercent(iFeasible);

        violatingInfeasibleIndices = ...
            infeasibleIndices( ...
                higherOrEqualMuscle & ...
                higherOrEqualActuator);

        nViolations = ...
            numel(violatingInfeasibleIndices);

        if nViolations == 0
            continue;
        end

        lowerFeasibleIndex = ...
            [ ...
                lowerFeasibleIndex
                repmat(iFeasible, nViolations, 1) ...
            ]; %#ok<AGROW>

        higherInfeasibleIndex = ...
            [ ...
                higherInfeasibleIndex
                violatingInfeasibleIndices(:) ...
            ]; %#ok<AGROW>
    end

    %% Build deterministic violation table

    if isempty(lowerFeasibleIndex)

        violations = ...
            localEmptyViolationTable();

    else

        LowerFeasibleConfigId = ...
            configIds(lowerFeasibleIndex);

        LowerMusclePercent = ...
            musclePercent(lowerFeasibleIndex);

        LowerActuatorPercent = ...
            actuatorPercent(lowerFeasibleIndex);

        HigherInfeasibleConfigId = ...
            configIds(higherInfeasibleIndex);

        HigherMusclePercent = ...
            musclePercent(higherInfeasibleIndex);

        HigherActuatorPercent = ...
            actuatorPercent(higherInfeasibleIndex);

        MuscleIncrease = ...
            HigherMusclePercent - ...
            LowerMusclePercent;

        ActuatorIncrease = ...
            HigherActuatorPercent - ...
            LowerActuatorPercent;

        violations = ...
            table( ...
                LowerFeasibleConfigId, ...
                LowerMusclePercent, ...
                LowerActuatorPercent, ...
                HigherInfeasibleConfigId, ...
                HigherMusclePercent, ...
                HigherActuatorPercent, ...
                MuscleIncrease, ...
                ActuatorIncrease);

        violations = ...
            sortrows( ...
                violations, ...
                { ...
                    'LowerMusclePercent', ...
                    'LowerActuatorPercent', ...
                    'LowerFeasibleConfigId', ...
                    'HigherMusclePercent', ...
                    'HigherActuatorPercent', ...
                    'HigherInfeasibleConfigId'});
    end

    %% Return audit

    audit = struct;

    audit.SchemaVersion = ...
        1;

    audit.IsMonotonic = ...
        isempty(violations);

    audit.ViolationCount = ...
        height(violations);

    audit.AssessedConfigurations = ...
        numel(assessedIndices);

    audit.FeasibleConfigurations = ...
        numel(feasibleIndices);

    audit.InfeasibleConfigurations = ...
        numel(infeasibleIndices);

    audit.Violations = ...
        violations;
end


function T = localEmptyViolationTable()

    T = ...
        table( ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            'VariableNames', { ...
                'LowerFeasibleConfigId', ...
                'LowerMusclePercent', ...
                'LowerActuatorPercent', ...
                'HigherInfeasibleConfigId', ...
                'HigherMusclePercent', ...
                'HigherActuatorPercent', ...
                'MuscleIncrease', ...
                'ActuatorIncrease'});
end
