function plan = buildStrengthGridPlan(summary, muscleGrid, actuatorGrid)
%BUILDSTRENGTHGRIDPLAN Classify a candidate strength grid from existing evidence.
%
% plan = soopt.buildStrengthGridPlan(summary, muscleGrid, actuatorGrid)
%
% summary must contain at least the configuration-level fields required by:
%
%   soopt.auditFeasibilityMonotonicity
%
% muscleGrid and actuatorGrid define the candidate percentage values to
% evaluate. Values must be unique positive integers.
%
% The function first audits the assessed data for monotonicity. If a
% violation exists, planning stops rather than making unsafe inferences.
%
% GRID STATUS
%
%   ASSESSED_FEASIBLE
%       This exact grid point has complete evidence and is feasible.
%
%   ASSESSED_INFEASIBLE
%       This exact grid point has complete evidence and is infeasible.
%
%   INFERRED_FEASIBLE
%       Unassessed point inferred feasible because at least one assessed
%       feasible point has no greater muscle or actuator strength.
%
%   INFERRED_INFEASIBLE
%       Unassessed point inferred infeasible because at least one assessed
%       infeasible point has no lower muscle or actuator strength.
%
%   UNKNOWN
%       Neither direct evidence nor monotonic inference determines the
%       point. This point remains a candidate for assessment.
%
% ExistingIncomplete is true when the configuration already exists in the
% summary table but its own assessment is incomplete.
%
% RETURN TABLE
%
%   ConfigId
%   MusclePercent
%   ActuatorPercent
%   ExistsInSummary
%   ExistingIncomplete
%   AssessmentComplete
%   ObservedFeasible
%   GridStatus
%   NeedsAssessment
%   FeasibleInferenceSources
%   InfeasibleInferenceSources
%
% Inference source IDs are semicolon-delimited and deterministically sorted
% by muscle %, actuator %, then ConfigId.
%
% This function is intentionally SIDE-EFFECT FREE.

    %% Validate candidate grids

    muscleGrid = ...
        localValidateGrid( ...
            muscleGrid, ...
            "muscleGrid", ...
            "StrengthGridPlan:InvalidMuscleGrid");

    actuatorGrid = ...
        localValidateGrid( ...
            actuatorGrid, ...
            "actuatorGrid", ...
            "StrengthGridPlan:InvalidActuatorGrid");

    %% Validate summary and monotonicity before inference

    assert(istable(summary), ...
        "StrengthGridPlan:InvalidSummary", ...
        "summary must be a table.");

    audit = ...
        soopt.auditFeasibilityMonotonicity( ...
            summary);

    assert(audit.IsMonotonic, ...
        "StrengthGridPlan:MonotonicityViolation", ...
        "Cannot build an inference-based grid plan because the assessed " + ...
        "configuration set contains %d monotonicity violation(s).", ...
        audit.ViolationCount);

    requiredVariables = [
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
        "AssessmentComplete"
        "IsFeasible"
    ];

    missingVariables = ...
        requiredVariables( ...
            ~ismember( ...
                requiredVariables, ...
                string(summary.Properties.VariableNames)));

    assert(isempty(missingVariables), ...
        "StrengthGridPlan:VariablesMissing", ...
        "summary is missing required variables: %s", ...
        strjoin(missingVariables, ", "));

    summaryConfigId = ...
        string(summary.ConfigId);

    summaryMuscle = ...
        double(summary.MusclePercent);

    summaryActuator = ...
        double(summary.ActuatorPercent);

    summaryAssessmentComplete = ...
        logical(summary.AssessmentComplete);

    summaryIsFeasible = ...
        logical(summary.IsFeasible);

    coordinateKeys = ...
        compose( ...
            "%d|%d", ...
            summaryMuscle, ...
            summaryActuator);

    assert(numel(unique(coordinateKeys)) == height(summary), ...
        "StrengthGridPlan:DuplicateCoordinates", ...
        "summary contains more than one configuration at the same " + ...
        "muscle/actuator coordinate.");

    %% Build full candidate grid

    [muscleMesh, actuatorMesh] = ...
        ndgrid( ...
            muscleGrid, ...
            actuatorGrid);

    MusclePercent = ...
        muscleMesh(:);

    ActuatorPercent = ...
        actuatorMesh(:);

    ConfigId = ...
        "m" + ...
        string(MusclePercent) + ...
        "p_a" + ...
        compose("%02d", ActuatorPercent) + ...
        "p";

    plan = ...
        table( ...
            string(ConfigId), ...
            MusclePercent, ...
            ActuatorPercent, ...
            'VariableNames', { ...
                'ConfigId', ...
                'MusclePercent', ...
                'ActuatorPercent'});

    plan = ...
        sortrows( ...
            plan, ...
            { ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ConfigId'});

    nPoints = ...
        height(plan);

    %% Allocate planning fields

    ExistsInSummary = ...
        false(nPoints,1);

    ExistingIncomplete = ...
        false(nPoints,1);

    AssessmentComplete = ...
        false(nPoints,1);

    ObservedFeasible = ...
        false(nPoints,1);

    GridStatus = ...
        repmat( ...
            "UNKNOWN", ...
            nPoints, ...
            1);

    NeedsAssessment = ...
        true(nPoints,1);

    FeasibleInferenceSources = ...
        strings(nPoints,1);

    InfeasibleInferenceSources = ...
        strings(nPoints,1);

    assessedFeasible = ...
        summaryAssessmentComplete & ...
        summaryIsFeasible;

    assessedInfeasible = ...
        summaryAssessmentComplete & ...
        ~summaryIsFeasible;

    %% Classify each grid point

    for iPoint = 1:nPoints

        muscle = ...
            plan.MusclePercent(iPoint);

        actuator = ...
            plan.ActuatorPercent(iPoint);

        directMatch = ...
            summaryMuscle == muscle & ...
            summaryActuator == actuator;

        if any(directMatch)

            iSummary = ...
                find(directMatch, 1, "first");

            ExistsInSummary(iPoint) = ...
                true;

            AssessmentComplete(iPoint) = ...
                summaryAssessmentComplete(iSummary);

            ObservedFeasible(iPoint) = ...
                summaryIsFeasible(iSummary);

            ExistingIncomplete(iPoint) = ...
                ~summaryAssessmentComplete(iSummary);

            if summaryAssessmentComplete(iSummary)

                NeedsAssessment(iPoint) = ...
                    false;

                if summaryIsFeasible(iSummary)

                    GridStatus(iPoint) = ...
                        "ASSESSED_FEASIBLE";

                else

                    GridStatus(iPoint) = ...
                        "ASSESSED_INFEASIBLE";
                end

                continue;
            end
        end

        feasibleSources = ...
            find( ...
                assessedFeasible & ...
                summaryMuscle <= muscle & ...
                summaryActuator <= actuator);

        infeasibleSources = ...
            find( ...
                assessedInfeasible & ...
                summaryMuscle >= muscle & ...
                summaryActuator >= actuator);

        FeasibleInferenceSources(iPoint) = ...
            localJoinSourceIds( ...
                summaryConfigId, ...
                summaryMuscle, ...
                summaryActuator, ...
                feasibleSources);

        InfeasibleInferenceSources(iPoint) = ...
            localJoinSourceIds( ...
                summaryConfigId, ...
                summaryMuscle, ...
                summaryActuator, ...
                infeasibleSources);

        assert(isempty(feasibleSources) || isempty(infeasibleSources), ...
            "StrengthGridPlan:ConflictingInference", ...
            "Grid point %s received both feasible and infeasible " + ...
            "monotonic inferences.", ...
            plan.ConfigId(iPoint));

        if ~isempty(feasibleSources)

            GridStatus(iPoint) = ...
                "INFERRED_FEASIBLE";

            NeedsAssessment(iPoint) = ...
                false;

        elseif ~isempty(infeasibleSources)

            GridStatus(iPoint) = ...
                "INFERRED_INFEASIBLE";

            NeedsAssessment(iPoint) = ...
                false;
        end
    end

    %% Append classification

    planningColumns = ...
        table( ...
            ExistsInSummary, ...
            ExistingIncomplete, ...
            AssessmentComplete, ...
            ObservedFeasible, ...
            GridStatus, ...
            NeedsAssessment, ...
            FeasibleInferenceSources, ...
            InfeasibleInferenceSources);

    plan = ...
        [plan planningColumns];
end


function grid = localValidateGrid(grid, variableName, errorId)

    assert(isnumeric(grid) && isvector(grid) && ~isempty(grid), ...
        errorId, ...
        "%s must be a nonempty numeric vector.", ...
        variableName);

    grid = ...
        double(grid(:));

    assert(all(isfinite(grid)) && ...
            all(grid > 0) && ...
            all(grid == fix(grid)), ...
        errorId, ...
        "%s must contain finite positive integer percentages.", ...
        variableName);

    assert(numel(unique(grid)) == numel(grid), ...
        errorId, ...
        "%s must not contain duplicate percentages.", ...
        variableName);

    grid = ...
        sort(grid);
end


function text = localJoinSourceIds( ...
        configId, musclePercent, actuatorPercent, indices)

    if isempty(indices)

        text = "";

        return;
    end

    sourceTable = ...
        table( ...
            musclePercent(indices), ...
            actuatorPercent(indices), ...
            configId(indices), ...
            'VariableNames', { ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ConfigId'});

    sourceTable = ...
        sortrows( ...
            sourceTable, ...
            { ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ConfigId'});

    text = ...
        strjoin( ...
            sourceTable.ConfigId, ...
            ";");
end
