function result = evaluateFeasibility(configRow, projectCfg)
%EVALUATEFEASIBILITY Evaluate SO feasibility for one strength configuration.
%
% result = soopt.evaluateFeasibility(configRow, projectCfg)
%
% configRow must be exactly one row returned by:
%
%   soopt.discoverStrengthConfigurations(projectCfg)
%
% Feasibility is determined from the configuration-specific Process-4
% batch summary CSV.
%
% A configuration is FEASIBLE only when:
%
%   1. the Process-4 summary exists and is structurally valid;
%   2. the summary identity matches configRow;
%   3. every expected condition/trial pair is represented exactly once;
%   4. every expected trial has Succeeded == true; and
%   5. every succeeded trial has OutputAuditPassed == true.
%
% IMPORTANT
%
% Assessment completeness is intentionally distinct from feasibility.
% Missing, malformed, or identity-mismatched output is not interpreted as
% scientific/model infeasibility.
%
% Key return fields:
%
%   AssessmentComplete
%   IsFeasible
%   Status
%   Reason
%   ExpectedTrials
%   SummaryRows
%   FailedTrials
%   OutputAuditFailedTrials
%   MissingTrialKeys
%   UnexpectedTrialKeys
%   FailedTrialKeys
%   OutputAuditFailedTrialKeys

    %% Validate inputs

    assert(istable(configRow) && height(configRow) == 1, ...
        "StrengthFeasibility:InvalidConfigRow", ...
        "configRow must be a one-row table.");

    requiredConfigVariables = [
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
        "Process4SummaryCsv"
    ];

    missingConfigVariables = ...
        requiredConfigVariables( ...
            ~ismember( ...
                requiredConfigVariables, ...
                string(configRow.Properties.VariableNames)));

    assert(isempty(missingConfigVariables), ...
        "StrengthFeasibility:ConfigVariablesMissing", ...
        "configRow is missing required variables: %s", ...
        strjoin(missingConfigVariables, ", "));

    assert(isstruct(projectCfg) && isscalar(projectCfg), ...
        "StrengthFeasibility:InvalidProjectConfig", ...
        "projectCfg must be a scalar struct.");

    requiredProjectFields = [
        "conditions"
        "trials"
    ];

    missingProjectFields = ...
        requiredProjectFields( ...
            ~isfield( ...
                projectCfg, ...
                cellstr(requiredProjectFields)));

    assert(isempty(missingProjectFields), ...
        "StrengthFeasibility:ProjectFieldsMissing", ...
        "projectCfg is missing required fields: %s", ...
        strjoin(missingProjectFields, ", "));

    conditions = ...
        double(projectCfg.conditions(:));

    trials = ...
        double(projectCfg.trials(:));

    assert(~isempty(conditions) && ...
            all(isfinite(conditions)), ...
        "StrengthFeasibility:InvalidConditions", ...
        "projectCfg.conditions must contain finite numeric values.");

    assert(~isempty(trials) && ...
            all(isfinite(trials)) && ...
            all(trials == fix(trials)), ...
        "StrengthFeasibility:InvalidTrials", ...
        "projectCfg.trials must contain finite integer values.");

    %% Initialize result identity

    configId = ...
        string(configRow.ConfigId(1));

    musclePercent = ...
        double(configRow.MusclePercent(1));

    actuatorPercent = ...
        double(configRow.ActuatorPercent(1));

    summaryFile = ...
        string(configRow.Process4SummaryCsv(1));

    result = struct;

    result.SchemaVersion = 1;

    result.ConfigId = ...
        configId;

    result.MusclePercent = ...
        musclePercent;

    result.ActuatorPercent = ...
        actuatorPercent;

    result.Process4SummaryCsv = ...
        summaryFile;

    result.AssessmentComplete = ...
        false;

    result.IsFeasible = ...
        false;

    result.Status = ...
        "NOT_EVALUATED";

    result.Reason = ...
        "";

    result.ExpectedTrials = ...
        numel(conditions) * numel(trials);

    result.SummaryRows = ...
        0;

    result.UniqueTrialRows = ...
        0;

    result.SucceededTrials = ...
        0;

    result.FailedTrials = ...
        0;

    result.OutputAuditPassedTrials = ...
        0;

    result.OutputAuditFailedTrials = ...
        0;

    result.MissingTrialKeys = ...
        strings(0,1);

    result.UnexpectedTrialKeys = ...
        strings(0,1);

    result.DuplicateTrialKeys = ...
        strings(0,1);

    result.FailedTrialKeys = ...
        strings(0,1);

    result.OutputAuditFailedTrialKeys = ...
        strings(0,1);

    %% Build expected trial set

    [conditionGrid, trialGrid] = ...
        ndgrid( ...
            conditions, ...
            trials);

    expectedConditionDeg = ...
        conditionGrid(:);

    expectedTrialNumber = ...
        trialGrid(:);

    expectedKeys = ...
        localTrialKeys( ...
            expectedConditionDeg, ...
            expectedTrialNumber);

    expectedKeys = ...
        sort(expectedKeys);

    %% Require Process-4 summary

    if ~isfile(summaryFile)

        result.Status = ...
            "INCOMPLETE_MISSING_BATCH_SUMMARY";

        result.Reason = ...
            "Process-4 batch summary CSV was not found.";

        return;
    end

    %% Read and validate summary schema

    try

        summaryTable = ...
            readtable( ...
                summaryFile, ...
                "TextType", "string");

    catch exception

        result.Status = ...
            "INCOMPLETE_UNREADABLE_BATCH_SUMMARY";

        result.Reason = ...
            "Process-4 batch summary could not be read: " + ...
            string(exception.message);

        return;
    end

    result.SummaryRows = ...
        height(summaryTable);

    if isempty(summaryTable)

        result.Status = ...
            "INCOMPLETE_EMPTY_BATCH_SUMMARY";

        result.Reason = ...
            "Process-4 batch summary contains no trial rows.";

        return;
    end

    requiredSummaryVariables = [
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
        "ConditionDeg"
        "TrialNumber"
        "Succeeded"
        "Status"
        "OutputAuditPassed"
    ];

    missingSummaryVariables = ...
        requiredSummaryVariables( ...
            ~ismember( ...
                requiredSummaryVariables, ...
                string(summaryTable.Properties.VariableNames)));

    if ~isempty(missingSummaryVariables)

        result.Status = ...
            "INCOMPLETE_INVALID_BATCH_SUMMARY_SCHEMA";

        result.Reason = ...
            "Process-4 batch summary is missing required variables: " + ...
            strjoin(missingSummaryVariables, ", ");

        return;
    end

    %% Validate configuration identity

    summaryConfigIds = ...
        string(summaryTable.ConfigId);

    summaryMusclePercent = ...
        double(summaryTable.MusclePercent);

    summaryActuatorPercent = ...
        double(summaryTable.ActuatorPercent);

    identityMatches = ...
        all(summaryConfigIds == configId) && ...
        all(summaryMusclePercent == musclePercent) && ...
        all(summaryActuatorPercent == actuatorPercent);

    if ~identityMatches

        result.Status = ...
            "INCOMPLETE_CONFIG_IDENTITY_MISMATCH";

        result.Reason = ...
            "Process-4 batch summary configuration identity does not " + ...
            "match the discovered configuration.";

        return;
    end

    %% Validate actual trial set

    actualConditionDeg = ...
        double(summaryTable.ConditionDeg);

    actualTrialNumber = ...
        double(summaryTable.TrialNumber);

    if any(~isfinite(actualConditionDeg)) || ...
            any(~isfinite(actualTrialNumber)) || ...
            any(actualTrialNumber ~= fix(actualTrialNumber))

        result.Status = ...
            "INCOMPLETE_INVALID_TRIAL_IDENTITY";

        result.Reason = ...
            "Process-4 batch summary contains invalid condition or trial IDs.";

        return;
    end

    actualKeys = ...
        localTrialKeys( ...
            actualConditionDeg, ...
            actualTrialNumber);

    [uniqueActualKeys, ~, keyGroup] = ...
        unique( ...
            actualKeys, ...
            "stable");

    result.UniqueTrialRows = ...
        numel(uniqueActualKeys);

    keyCounts = ...
        accumarray( ...
            keyGroup, ...
            1);

    duplicateKeys = ...
        uniqueActualKeys(keyCounts > 1);

    result.DuplicateTrialKeys = ...
        sort(duplicateKeys);

    if ~isempty(duplicateKeys)

        result.Status = ...
            "INCOMPLETE_DUPLICATE_TRIALS";

        result.Reason = ...
            "Process-4 batch summary contains duplicate condition/trial rows.";

        return;
    end

    result.MissingTrialKeys = ...
        sort(setdiff( ...
            expectedKeys, ...
            actualKeys));

    result.UnexpectedTrialKeys = ...
        sort(setdiff( ...
            actualKeys, ...
            expectedKeys));

    if ~isempty(result.MissingTrialKeys) || ...
            ~isempty(result.UnexpectedTrialKeys)

        result.Status = ...
            "INCOMPLETE_TRIAL_SET_MISMATCH";

        result.Reason = ...
            "Process-4 batch summary trial set does not exactly match " + ...
            "projectCfg.conditions x projectCfg.trials.";

        return;
    end

    %% Convert trial-level completion fields

    try

        succeeded = ...
            localLogicalVector( ...
                summaryTable.Succeeded, ...
                "Succeeded");

        outputAuditPassed = ...
            localLogicalVector( ...
                summaryTable.OutputAuditPassed, ...
                "OutputAuditPassed");

    catch exception

        result.Status = ...
            "INCOMPLETE_INVALID_LOGICAL_FIELDS";

        result.Reason = ...
            string(exception.message);

        return;
    end

    result.SucceededTrials = ...
        nnz(succeeded);

    result.FailedTrials = ...
        nnz(~succeeded);

    result.OutputAuditPassedTrials = ...
        nnz(succeeded & outputAuditPassed);

    % Failed SO jobs initialize OutputAuditPassed=false. Therefore audit
    % failure is counted only among trials whose SO execution succeeded.
    auditFailed = ...
        succeeded & ...
        ~outputAuditPassed;

    result.OutputAuditFailedTrials = ...
        nnz(auditFailed);

    result.FailedTrialKeys = ...
        sort(actualKeys(~succeeded));

    result.OutputAuditFailedTrialKeys = ...
        sort(actualKeys(auditFailed));

    %% Final feasibility classification

    result.AssessmentComplete = ...
        true;

    if any(~succeeded)

        result.Status = ...
            "INFEASIBLE_SO_FAILURE";

        result.Reason = ...
            sprintf( ...
                "%d of %d expected trials failed Static Optimization.", ...
                result.FailedTrials, ...
                result.ExpectedTrials);

        return;
    end

    if any(~outputAuditPassed)

        result.Status = ...
            "INFEASIBLE_OUTPUT_AUDIT";

        result.Reason = ...
            sprintf( ...
                "%d of %d expected trials failed the Process-4 output audit.", ...
                result.OutputAuditFailedTrials, ...
                result.ExpectedTrials);

        return;
    end

    result.IsFeasible = ...
        true;

    result.Status = ...
        "FEASIBLE";

    result.Reason = ...
        sprintf( ...
            "All %d expected trials completed Static Optimization and " + ...
            "passed the Process-4 output audit.", ...
            result.ExpectedTrials);
end


function keys = localTrialKeys(conditionDeg, trialNumber)

    conditionDeg = ...
        double(conditionDeg(:));

    trialNumber = ...
        double(trialNumber(:));

    assert(numel(conditionDeg) == numel(trialNumber), ...
        "StrengthFeasibility:TrialKeySizeMismatch", ...
        "Condition and trial vectors must have equal length.");

    keys = ...
        compose( ...
            "%gdeg|trial%02d", ...
            conditionDeg, ...
            trialNumber);

    keys = ...
        string(keys);
end


function values = localLogicalVector(rawValues, variableName)

    if islogical(rawValues)

        values = ...
            rawValues(:);

        return;
    end

    if isnumeric(rawValues)

        rawValues = ...
            rawValues(:);

        if any(~ismember(rawValues, [0 1]))

            error( ...
                "StrengthFeasibility:InvalidLogicalVariable", ...
                "%s must contain only logical, 0/1, or true/false values.", ...
                variableName);
        end

        values = ...
            logical(rawValues);

        return;
    end

    textValues = ...
        lower(strtrim(string(rawValues(:))));

    values = ...
        false(size(textValues));

    isTrue = ...
        ismember( ...
            textValues, ...
            ["true", "1"]);

    isFalse = ...
        ismember( ...
            textValues, ...
            ["false", "0"]);

    if any(~(isTrue | isFalse))

        error( ...
            "StrengthFeasibility:InvalidLogicalVariable", ...
            "%s contains values that cannot be interpreted as logical.", ...
            variableName);
    end

    values(isTrue) = ...
        true;
end
