function summary = findParetoFrontier(summary)
%FINDPARETOFRONTIER Classify feasible strength configurations by dominance.
%
% summary = soopt.findParetoFrontier(summary)
%
% Input must be a configuration-level table containing at least:
%
%   ConfigId
%   MusclePercent
%   ActuatorPercent
%   AssessmentComplete
%   IsFeasible
%
% Only configurations with:
%
%   AssessmentComplete == true
%   IsFeasible == true
%
% participate in Pareto dominance.
%
% Configuration A dominates configuration B when:
%
%   A.MusclePercent   <= B.MusclePercent
%   A.ActuatorPercent <= B.ActuatorPercent
%
% and at least one inequality is strict.
%
% The function appends:
%
%   IsParetoEligible
%       true only for assessed feasible configurations.
%
%   IsParetoOptimal
%       true for eligible configurations not dominated by another eligible
%       configuration.
%
%   DominatedByCount
%       number of eligible configurations that dominate the row.
%
%   DominatingConfigIds
%       semicolon-delimited ConfigIds of all dominating configurations,
%       sorted deterministically by muscle %, actuator %, then ConfigId.
%
% The function is intentionally SIDE-EFFECT FREE and has no filesystem or
% OpenSim dependencies.

    %% Validate input table

    assert(istable(summary), ...
        "StrengthPareto:InvalidInput", ...
        "Input must be a table.");

    requiredVariables = [
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
        "AssessmentComplete"
        "IsFeasible"
    ];

    missingVariables = ...
        requiredVariables( ...
            ~ismember( ...
                requiredVariables, ...
                string(summary.Properties.VariableNames)));

    assert(isempty(missingVariables), ...
        "StrengthPareto:VariablesMissing", ...
        "Input table is missing required variables: %s", ...
        strjoin(missingVariables, ", "));

    %% Validate identity and optimization coordinates

    configIds = ...
        string(summary.ConfigId);

    musclePercent = ...
        double(summary.MusclePercent);

    actuatorPercent = ...
        double(summary.ActuatorPercent);

    assessmentComplete = ...
        logical(summary.AssessmentComplete);

    isFeasible = ...
        logical(summary.IsFeasible);

    assert(all(~ismissing(configIds) & strlength(configIds) > 0), ...
        "StrengthPareto:InvalidConfigId", ...
        "ConfigId must contain nonempty string values.");

    assert(numel(unique(configIds)) == height(summary), ...
        "StrengthPareto:DuplicateConfigId", ...
        "ConfigId values must be unique.");

    assert(all(isfinite(musclePercent) & musclePercent > 0), ...
        "StrengthPareto:InvalidMusclePercent", ...
        "MusclePercent must contain finite positive values.");

    assert(all(isfinite(actuatorPercent) & actuatorPercent > 0), ...
        "StrengthPareto:InvalidActuatorPercent", ...
        "ActuatorPercent must contain finite positive values.");

    %% Allocate Pareto classification

    nConfigs = ...
        height(summary);

    IsParetoEligible = ...
        assessmentComplete & ...
        isFeasible;

    IsParetoOptimal = ...
        false(nConfigs,1);

    DominatedByCount = ...
        zeros(nConfigs,1);

    DominatingConfigIds = ...
        strings(nConfigs,1);

    %% Evaluate pairwise dominance among eligible configurations

    eligibleIndices = ...
        find(IsParetoEligible);

    for iRow = eligibleIndices.'

        candidateMuscle = ...
            musclePercent(iRow);

        candidateActuator = ...
            actuatorPercent(iRow);

        otherIndices = ...
            eligibleIndices(eligibleIndices ~= iRow);

        if isempty(otherIndices)

            IsParetoOptimal(iRow) = ...
                true;

            continue;
        end

        noWorseMuscle = ...
            musclePercent(otherIndices) <= candidateMuscle;

        noWorseActuator = ...
            actuatorPercent(otherIndices) <= candidateActuator;

        strictlyBetterInAtLeastOne = ...
            musclePercent(otherIndices) < candidateMuscle | ...
            actuatorPercent(otherIndices) < candidateActuator;

        dominatesCandidate = ...
            noWorseMuscle & ...
            noWorseActuator & ...
            strictlyBetterInAtLeastOne;

        dominatingIndices = ...
            otherIndices(dominatesCandidate);

        DominatedByCount(iRow) = ...
            numel(dominatingIndices);

        IsParetoOptimal(iRow) = ...
            isempty(dominatingIndices);

        if ~isempty(dominatingIndices)

            dominators = ...
                table( ...
                    musclePercent(dominatingIndices), ...
                    actuatorPercent(dominatingIndices), ...
                    configIds(dominatingIndices), ...
                    dominatingIndices, ...
                    'VariableNames', { ...
                        'MusclePercent', ...
                        'ActuatorPercent', ...
                        'ConfigId', ...
                        'OriginalIndex'});

            dominators = ...
                sortrows( ...
                    dominators, ...
                    { ...
                        'MusclePercent', ...
                        'ActuatorPercent', ...
                        'ConfigId'});

            DominatingConfigIds(iRow) = ...
                strjoin( ...
                    dominators.ConfigId, ...
                    ";");
        end
    end

    %% Append classification columns

    paretoColumns = ...
        table( ...
            IsParetoEligible, ...
            IsParetoOptimal, ...
            DominatedByCount, ...
            DominatingConfigIds);

    summary = ...
        [summary paretoColumns];
end
