function [fig, ax, info] = plotFeasibilityMap(summary, varargin)
%PLOTFEASIBILITYMAP Plot assessed SO strength-grid feasibility and Pareto state.
%
% [fig, ax, info] = soopt.plotFeasibilityMap(summary)
%
% Input must be a Pareto-classified configuration table containing:
%
%   ConfigId
%   MusclePercent
%   ActuatorPercent
%   AssessmentComplete
%   IsFeasible
%   IsParetoOptimal
%
% Grid coordinates:
%
%   x-axis = MusclePercent
%   y-axis = ActuatorPercent
%
% Plot categories:
%
%   Incomplete
%       AssessmentComplete == false
%
%   Infeasible
%       AssessmentComplete == true
%       IsFeasible == false
%
%   Feasible, dominated
%       AssessmentComplete == true
%       IsFeasible == true
%       IsParetoOptimal == false
%
%   Pareto optimal
%       AssessmentComplete == true
%       IsFeasible == true
%       IsParetoOptimal == true
%
% NAME-VALUE OPTIONS
%
%   Visible
%       "on" or "off". Default "on".
%
%   ShowConfigLabels
%       Logical scalar. Default true.
%
%   Title
%       Figure title string. Default:
%       "Static Optimization strength feasibility map"
%
% The function does not write files. Callers may export the returned figure
% with exportgraphics when desired.
%
% info contains category counts and ConfigIds for lightweight downstream
% auditing and unit testing.

    %% Parse inputs

    parser = ...
        inputParser;

    parser.FunctionName = ...
        "soopt.plotFeasibilityMap";

    addRequired(parser, ...
        "summary", ...
        @istable);

    addParameter(parser, ...
        "Visible", ...
        "on", ...
        @(x) ...
            (ischar(x) && isrow(x)) || ...
            (isstring(x) && isscalar(x) && ~ismissing(x)));

    addParameter(parser, ...
        "ShowConfigLabels", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "Title", ...
        "Static Optimization strength feasibility map", ...
        @(x) ...
            (ischar(x) && isrow(x)) || ...
            (isstring(x) && isscalar(x) && ~ismissing(x)));

    parse(parser, ...
        summary, ...
        varargin{:});

    visible = ...
        lower(string(parser.Results.Visible));

    assert(ismember(visible, ["on", "off"]), ...
        "StrengthFeasibilityMap:InvalidVisible", ...
        "Visible must be ""on"" or ""off"".");

    showConfigLabels = ...
        logical(parser.Results.ShowConfigLabels);

    figureTitle = ...
        string(parser.Results.Title);

    %% Validate required columns

    requiredVariables = [
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
        "AssessmentComplete"
        "IsFeasible"
        "IsParetoOptimal"
    ];

    missingVariables = ...
        requiredVariables( ...
            ~ismember( ...
                requiredVariables, ...
                string(summary.Properties.VariableNames)));

    assert(isempty(missingVariables), ...
        "StrengthFeasibilityMap:VariablesMissing", ...
        "Input table is missing required variables: %s", ...
        strjoin(missingVariables, ", "));

    configIds = ...
        string(summary.ConfigId);

    musclePercent = ...
        double(summary.MusclePercent);

    actuatorPercent = ...
        double(summary.ActuatorPercent);

    assessmentComplete = ...
        logical(summary.AssessmentComplete);

    isFeasible = ...
        logical(summary.IsFeasible);

    isParetoOptimal = ...
        logical(summary.IsParetoOptimal);

    assert(all(~ismissing(configIds) & strlength(configIds) > 0), ...
        "StrengthFeasibilityMap:InvalidConfigId", ...
        "ConfigId must contain nonempty string values.");

    assert(all(isfinite(musclePercent) & musclePercent > 0), ...
        "StrengthFeasibilityMap:InvalidMusclePercent", ...
        "MusclePercent must contain finite positive values.");

    assert(all(isfinite(actuatorPercent) & actuatorPercent > 0), ...
        "StrengthFeasibilityMap:InvalidActuatorPercent", ...
        "ActuatorPercent must contain finite positive values.");

    assert(~any(isParetoOptimal & (~assessmentComplete | ~isFeasible)), ...
        "StrengthFeasibilityMap:InvalidParetoState", ...
        "IsParetoOptimal may only be true for assessed feasible rows.");

    %% Classify rows

    isIncomplete = ...
        ~assessmentComplete;

    isInfeasible = ...
        assessmentComplete & ...
        ~isFeasible;

    isFeasibleDominated = ...
        assessmentComplete & ...
        isFeasible & ...
        ~isParetoOptimal;

    isPareto = ...
        assessmentComplete & ...
        isFeasible & ...
        isParetoOptimal;

    %% Return lightweight classification metadata

    info = struct;

    info.SchemaVersion = ...
        1;

    info.TotalConfigurations = ...
        height(summary);

    info.IncompleteCount = ...
        nnz(isIncomplete);

    info.InfeasibleCount = ...
        nnz(isInfeasible);

    info.FeasibleDominatedCount = ...
        nnz(isFeasibleDominated);

    info.ParetoOptimalCount = ...
        nnz(isPareto);

    info.IncompleteConfigIds = ...
        configIds(isIncomplete);

    info.InfeasibleConfigIds = ...
        configIds(isInfeasible);

    info.FeasibleDominatedConfigIds = ...
        configIds(isFeasibleDominated);

    info.ParetoOptimalConfigIds = ...
        configIds(isPareto);

    %% Create figure

    fig = ...
        figure( ...
            "Visible", visible, ...
            "Color", "w", ...
            "Name", figureTitle);

    ax = ...
        axes(fig);

    hold(ax, "on");

    legendHandles = ...
        gobjects(0,1);

    legendLabels = ...
        strings(0,1);

    %% Plot categories

    if any(isIncomplete)

        h = ...
            plot( ...
                ax, ...
                musclePercent(isIncomplete), ...
                actuatorPercent(isIncomplete), ...
                "x", ...
                "LineStyle", "none", ...
                "MarkerSize", 9, ...
                "LineWidth", 1.5);

        legendHandles(end+1,1) = h;
        legendLabels(end+1,1) = "Incomplete";
    end

    if any(isInfeasible)

        h = ...
            plot( ...
                ax, ...
                musclePercent(isInfeasible), ...
                actuatorPercent(isInfeasible), ...
                "s", ...
                "LineStyle", "none", ...
                "MarkerSize", 9, ...
                "LineWidth", 1.5);

        legendHandles(end+1,1) = h;
        legendLabels(end+1,1) = "Infeasible";
    end

    if any(isFeasibleDominated)

        h = ...
            plot( ...
                ax, ...
                musclePercent(isFeasibleDominated), ...
                actuatorPercent(isFeasibleDominated), ...
                "o", ...
                "LineStyle", "none", ...
                "MarkerSize", 9, ...
                "LineWidth", 1.5);

        legendHandles(end+1,1) = h;
        legendLabels(end+1,1) = "Feasible, dominated";
    end

    if any(isPareto)

        h = ...
            plot( ...
                ax, ...
                musclePercent(isPareto), ...
                actuatorPercent(isPareto), ...
                "p", ...
                "LineStyle", "none", ...
                "MarkerSize", 12, ...
                "LineWidth", 1.75);

        legendHandles(end+1,1) = h;
        legendLabels(end+1,1) = "Pareto optimal";
    end

    %% Optional configuration labels

    if showConfigLabels && ~isempty(summary)

        for iConfig = 1:height(summary)

            text( ...
                ax, ...
                musclePercent(iConfig), ...
                actuatorPercent(iConfig), ...
                "  " + configIds(iConfig), ...
                "Interpreter", "none", ...
                "VerticalAlignment", "bottom");
        end
    end

    %% Axes formatting

    xlabel(ax, ...
        "Muscle strength (% target)");

    ylabel(ax, ...
        "Reserve actuator strength (% target)");

    title(ax, ...
        figureTitle, ...
        "Interpreter", "none");

    grid(ax, "on");
    box(ax, "on");

    if ~isempty(summary)

        xticks(ax, ...
            unique(musclePercent));

        yticks(ax, ...
            unique(actuatorPercent));

        xlim(ax, ...
            localAxisLimits(musclePercent));

        ylim(ax, ...
            localAxisLimits(actuatorPercent));
    end

    if ~isempty(legendHandles)

        legend( ...
            ax, ...
            legendHandles, ...
            legendLabels, ...
            "Location", "best");
    end

    hold(ax, "off");
end


function limits = localAxisLimits(values)

    values = ...
        double(values(:));

    minimumValue = ...
        min(values);

    maximumValue = ...
        max(values);

    if minimumValue == maximumValue

        padding = ...
            max(5, 0.10 * maximumValue);

    else

        padding = ...
            max(2, 0.08 * (maximumValue - minimumValue));
    end

    limits = ...
        [ ...
            max(0, minimumValue - padding), ...
            maximumValue + padding ...
        ];

    if limits(1) == limits(2)

        limits = ...
            limits + [-1 1];
    end
end
