function proposals = proposeNextConfigurations(plan, varargin)
%PROPOSENEXTCONFIGURATIONS Rank unknown strength-grid points for assessment.
%
% proposals = soopt.proposeNextConfigurations(plan)
%
% Input must be a table returned by:
%
%   soopt.buildStrengthGridPlan
%
% Only rows satisfying:
%
%   GridStatus == "UNKNOWN"
%   NeedsAssessment == true
%
% are eligible for proposal.
%
% RANKING PRINCIPLE
%
% For each unknown candidate, the function estimates how many currently
% unknown points would become resolved under either possible outcome:
%
%   Candidate is feasible:
%       all unknown points with muscle >= candidate muscle and
%       actuator >= candidate actuator become inferred feasible.
%
%   Candidate is infeasible:
%       all unknown points with muscle <= candidate muscle and
%       actuator <= candidate actuator become inferred infeasible.
%
% Candidates are ranked primarily by:
%
%   1. maximum WorstCaseResolvedCount;
%   2. maximum TotalResolutionPotential;
%   3. minimum ResolutionImbalance;
%   4. existing incomplete configurations before entirely new points;
%   5. minimum normalized distance from the candidate-grid center;
%   6. deterministic coordinate / ConfigId ordering.
%
% This is a maximin information heuristic. It does not assign a scalar
% scientific preference between muscle and actuator strength.
%
% NAME-VALUE OPTIONS
%
%   MaxProposals
%       Positive integer or Inf. Default 1.
%
% RETURN TABLE
%
%   PriorityRank
%   ConfigId
%   MusclePercent
%   ActuatorPercent
%   ExistingIncomplete
%   FeasibleOutcomeResolvedCount
%   InfeasibleOutcomeResolvedCount
%   WorstCaseResolvedCount
%   BestCaseResolvedCount
%   TotalResolutionPotential
%   ResolutionImbalance
%   GridCenterDistance
%
% The function is intentionally SIDE-EFFECT FREE.

    %% Parse inputs

    parser = ...
        inputParser;

    parser.FunctionName = ...
        "soopt.proposeNextConfigurations";

    addRequired(parser, ...
        "plan", ...
        @istable);

    addParameter(parser, ...
        "MaxProposals", ...
        1, ...
        @(x) ...
            isnumeric(x) && ...
            isscalar(x) && ...
            (isinf(x) || ...
                (isfinite(x) && x >= 1 && x == fix(x))));

    parse(parser, ...
        plan, ...
        varargin{:});

    maxProposals = ...
        double(parser.Results.MaxProposals);

    %% Validate planning table

    requiredVariables = [
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
        "ExistingIncomplete"
        "GridStatus"
        "NeedsAssessment"
    ];

    missingVariables = ...
        requiredVariables( ...
            ~ismember( ...
                requiredVariables, ...
                string(plan.Properties.VariableNames)));

    assert(isempty(missingVariables), ...
        "StrengthProposal:VariablesMissing", ...
        "plan is missing required variables: %s", ...
        strjoin(missingVariables, ", "));

    configId = ...
        string(plan.ConfigId);

    musclePercent = ...
        double(plan.MusclePercent);

    actuatorPercent = ...
        double(plan.ActuatorPercent);

    existingIncomplete = ...
        logical(plan.ExistingIncomplete);

    gridStatus = ...
        string(plan.GridStatus);

    needsAssessment = ...
        logical(plan.NeedsAssessment);

    assert(all(~ismissing(configId) & strlength(configId) > 0), ...
        "StrengthProposal:InvalidConfigId", ...
        "ConfigId must contain nonempty string values.");

    assert(numel(unique(configId)) == height(plan), ...
        "StrengthProposal:DuplicateConfigId", ...
        "ConfigId values must be unique.");

    assert(all(isfinite(musclePercent) & musclePercent > 0), ...
        "StrengthProposal:InvalidMusclePercent", ...
        "MusclePercent must contain finite positive values.");

    assert(all(isfinite(actuatorPercent) & actuatorPercent > 0), ...
        "StrengthProposal:InvalidActuatorPercent", ...
        "ActuatorPercent must contain finite positive values.");

    assert(all(ismember( ...
            gridStatus, ...
            [ ...
                "ASSESSED_FEASIBLE"
                "ASSESSED_INFEASIBLE"
                "INFERRED_FEASIBLE"
                "INFERRED_INFEASIBLE"
                "UNKNOWN" ...
            ])), ...
        "StrengthProposal:InvalidGridStatus", ...
        "GridStatus contains unsupported values.");

    inconsistentNeedsAssessment = ...
        needsAssessment & ...
        gridStatus ~= "UNKNOWN";

    assert(~any(inconsistentNeedsAssessment), ...
        "StrengthProposal:InconsistentPlanState", ...
        "NeedsAssessment may only be true for UNKNOWN grid points.");

    %% Identify unknown candidates

    candidateMask = ...
        needsAssessment & ...
        gridStatus == "UNKNOWN";

    candidateIndices = ...
        find(candidateMask);

    if isempty(candidateIndices)

        proposals = ...
            localEmptyProposalTable();

        return;
    end

    candidateConfigId = ...
        configId(candidateIndices);

    candidateMuscle = ...
        musclePercent(candidateIndices);

    candidateActuator = ...
        actuatorPercent(candidateIndices);

    candidateExistingIncomplete = ...
        existingIncomplete(candidateIndices);

    nCandidates = ...
        numel(candidateIndices);

    %% Evaluate outcome-dependent resolution potential

    FeasibleOutcomeResolvedCount = ...
        zeros(nCandidates,1);

    InfeasibleOutcomeResolvedCount = ...
        zeros(nCandidates,1);

    for iCandidate = 1:nCandidates

        FeasibleOutcomeResolvedCount(iCandidate) = ...
            nnz( ...
                candidateMuscle >= candidateMuscle(iCandidate) & ...
                candidateActuator >= candidateActuator(iCandidate));

        InfeasibleOutcomeResolvedCount(iCandidate) = ...
            nnz( ...
                candidateMuscle <= candidateMuscle(iCandidate) & ...
                candidateActuator <= candidateActuator(iCandidate));
    end

    WorstCaseResolvedCount = ...
        min( ...
            FeasibleOutcomeResolvedCount, ...
            InfeasibleOutcomeResolvedCount);

    BestCaseResolvedCount = ...
        max( ...
            FeasibleOutcomeResolvedCount, ...
            InfeasibleOutcomeResolvedCount);

    TotalResolutionPotential = ...
        FeasibleOutcomeResolvedCount + ...
        InfeasibleOutcomeResolvedCount;

    ResolutionImbalance = ...
        abs( ...
            FeasibleOutcomeResolvedCount - ...
            InfeasibleOutcomeResolvedCount);

    %% Compute symmetric normalized grid-center tie breaker

    muscleMinimum = ...
        min(musclePercent);

    muscleMaximum = ...
        max(musclePercent);

    actuatorMinimum = ...
        min(actuatorPercent);

    actuatorMaximum = ...
        max(actuatorPercent);

    muscleCenter = ...
        (muscleMinimum + muscleMaximum) / 2;

    actuatorCenter = ...
        (actuatorMinimum + actuatorMaximum) / 2;

    muscleRange = ...
        muscleMaximum - muscleMinimum;

    actuatorRange = ...
        actuatorMaximum - actuatorMinimum;

    if muscleRange == 0
        normalizedMuscleDistance = zeros(nCandidates,1);
    else
        normalizedMuscleDistance = ...
            (candidateMuscle - muscleCenter) ./ muscleRange;
    end

    if actuatorRange == 0
        normalizedActuatorDistance = zeros(nCandidates,1);
    else
        normalizedActuatorDistance = ...
            (candidateActuator - actuatorCenter) ./ actuatorRange;
    end

    GridCenterDistance = ...
        sqrt( ...
            normalizedMuscleDistance.^2 + ...
            normalizedActuatorDistance.^2);

    %% Rank candidates deterministically

    ranking = ...
        table( ...
            candidateConfigId, ...
            candidateMuscle, ...
            candidateActuator, ...
            candidateExistingIncomplete, ...
            FeasibleOutcomeResolvedCount, ...
            InfeasibleOutcomeResolvedCount, ...
            WorstCaseResolvedCount, ...
            BestCaseResolvedCount, ...
            TotalResolutionPotential, ...
            ResolutionImbalance, ...
            GridCenterDistance, ...
            'VariableNames', { ...
                'ConfigId', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ExistingIncomplete', ...
                'FeasibleOutcomeResolvedCount', ...
                'InfeasibleOutcomeResolvedCount', ...
                'WorstCaseResolvedCount', ...
                'BestCaseResolvedCount', ...
                'TotalResolutionPotential', ...
                'ResolutionImbalance', ...
                'GridCenterDistance'});

    ranking = ...
        sortrows( ...
            ranking, ...
            { ...
                'WorstCaseResolvedCount', ...
                'TotalResolutionPotential', ...
                'ResolutionImbalance', ...
                'ExistingIncomplete', ...
                'GridCenterDistance', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ConfigId'}, ...
            { ...
                'descend', ...
                'descend', ...
                'ascend', ...
                'descend', ...
                'ascend', ...
                'ascend', ...
                'ascend', ...
                'ascend'});

    nSelected = ...
        min( ...
            height(ranking), ...
            maxProposals);

    if isinf(maxProposals)
        nSelected = height(ranking);
    end

    proposals = ...
        ranking(1:nSelected,:);

    PriorityRank = ...
        (1:nSelected).';

    proposals = ...
        addvars( ...
            proposals, ...
            PriorityRank, ...
            'Before', ...
            1);
end


function T = localEmptyProposalTable()

    T = ...
        table( ...
            zeros(0,1), ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            false(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            'VariableNames', { ...
                'PriorityRank', ...
                'ConfigId', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ExistingIncomplete', ...
                'FeasibleOutcomeResolvedCount', ...
                'InfeasibleOutcomeResolvedCount', ...
                'WorstCaseResolvedCount', ...
                'BestCaseResolvedCount', ...
                'TotalResolutionPotential', ...
                'ResolutionImbalance', ...
                'GridCenterDistance'});
end
