function proposals = proposeBoundaryRefinement(summary, varargin)
%PROPOSEBOUNDARYREFINEMENT Propose quantized adaptive boundary assessments.
%
% proposals = soopt.proposeBoundaryRefinement(summary)
%
% Proposes unassessed muscle/actuator strength coordinates that refine the
% observed feasible/infeasible boundary without requiring a pre-generated
% Cartesian JSON pool.
%
% The function is intentionally NONPARAMETRIC. It does not fit or assume a
% linear, polynomial, or other functional boundary.
%
% METHOD
%
%   1. Use only AssessmentComplete rows as feasibility evidence.
%   2. Require the assessed evidence to satisfy the existing monotonicity
%      assumption.
%   3. Build a virtual numeric lattice at IncrementPercent spacing.
%   4. Remove coordinates that are already assessed or can already be
%      classified by monotonic inference.
%   5. By default, retain only coordinates explicitly bracketed by:
%
%          an assessed infeasible point at or below/left, and
%          an assessed feasible point at or above/right.
%
%   6. Rank candidates toward the largest unresolved local bracket, then by
%      maximin information gain and proximity to the bracket midpoint.
%
% No files are created or modified.
%
% NAME-VALUE OPTIONS
%
%   IncrementPercent
%       Positive integer lattice increment. Default 5.
%
%   MuscleBounds
%       Two-element [min max] numeric vector. Default is the min/max muscle
%       percentage among assessed configurations.
%
%   ActuatorBounds
%       Two-element [min max] numeric vector. Default is the min/max
%       actuator percentage among assessed configurations.
%
%   RequireExplicitBracket
%       Logical scalar. Default true. When true, a candidate must lie
%       between explicit assessed infeasible and feasible support points.
%
%   MaxProposals
%       Positive integer or Inf. Default 1.
%
% RETURN TABLE
%
%   PriorityRank
%   ConfigId
%   MusclePercent
%   ActuatorPercent
%   ExistingIncomplete
%   ExistingConfigId
%   IncrementPercent
%   LowerInfeasibleConfigId
%   LowerInfeasibleMusclePercent
%   LowerInfeasibleActuatorPercent
%   UpperFeasibleConfigId
%   UpperFeasibleMusclePercent
%   UpperFeasibleActuatorPercent
%   MuscleBracketWidth
%   ActuatorBracketWidth
%   BracketSpanSteps
%   DistanceToLowerSteps
%   DistanceToUpperSteps
%   CenterImbalanceSteps
%   FeasibleOutcomeResolvedCount
%   InfeasibleOutcomeResolvedCount
%   WorstCaseResolvedCount
%   BestCaseResolvedCount
%   TotalResolutionPotential
%   ResolutionImbalance
%
% Existing incomplete coordinates may be proposed if they remain genuinely
% unresolved under the current assessed evidence.

    %% Parse inputs

    parser = inputParser;

    parser.FunctionName = ...
        "soopt.proposeBoundaryRefinement";

    addRequired(parser, ...
        "summary", ...
        @istable);

    addParameter(parser, ...
        "IncrementPercent", ...
        5, ...
        @(x) ...
            isnumeric(x) && ...
            isscalar(x) && ...
            isfinite(x) && ...
            x >= 1 && ...
            x == fix(x));

    addParameter(parser, ...
        "MuscleBounds", ...
        [], ...
        @(x) ...
            isempty(x) || ...
            (isnumeric(x) && ...
                isvector(x) && ...
                numel(x) == 2 && ...
                all(isfinite(x))));

    addParameter(parser, ...
        "ActuatorBounds", ...
        [], ...
        @(x) ...
            isempty(x) || ...
            (isnumeric(x) && ...
                isvector(x) && ...
                numel(x) == 2 && ...
                all(isfinite(x))));

    addParameter(parser, ...
        "RequireExplicitBracket", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "MaxProposals", ...
        1, ...
        @(x) ...
            isnumeric(x) && ...
            isscalar(x) && ...
            (isinf(x) || ...
                (isfinite(x) && ...
                    x >= 1 && ...
                    x == fix(x))));

    parse(parser, ...
        summary, ...
        varargin{:});

    incrementPercent = ...
        double(parser.Results.IncrementPercent);

    muscleBounds = ...
        double(parser.Results.MuscleBounds);

    actuatorBounds = ...
        double(parser.Results.ActuatorBounds);

    requireExplicitBracket = ...
        logical(parser.Results.RequireExplicitBracket);

    maxProposals = ...
        double(parser.Results.MaxProposals);

    %% Validate summary contract

    requiredVariables = [
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
        "AssessmentComplete"
        "IsFeasible"
    ];

    missingVariables = ...
        requiredVariables( ...
            ~ismember( ...
                requiredVariables, ...
                string(summary.Properties.VariableNames)));

    assert(isempty(missingVariables), ...
        "StrengthBoundary:VariablesMissing", ...
        "summary is missing required variables: %s", ...
        strjoin(missingVariables, ", "));

    if isempty(summary)

        proposals = ...
            localEmptyProposalTable();

        return;
    end

    configIds = ...
        string(summary.ConfigId);

    musclePercent = ...
        double(summary.MusclePercent);

    actuatorPercent = ...
        double(summary.ActuatorPercent);

    assessmentComplete = ...
        logical(summary.AssessmentComplete);

    isFeasible = ...
        logical(summary.IsFeasible);

    assert(all( ...
        ~ismissing(configIds) & ...
        strlength(configIds) > 0), ...
        "StrengthBoundary:InvalidConfigId", ...
        "ConfigId values must be nonempty.");

    assert(numel(unique(configIds)) == height(summary), ...
        "StrengthBoundary:DuplicateConfigId", ...
        "ConfigId values must be unique.");

    assert(all( ...
        isfinite(musclePercent) & ...
        musclePercent > 0 & ...
        musclePercent == fix(musclePercent)), ...
        "StrengthBoundary:InvalidMusclePercent", ...
        "MusclePercent values must be positive integers.");

    assert(all( ...
        isfinite(actuatorPercent) & ...
        actuatorPercent > 0 & ...
        actuatorPercent == fix(actuatorPercent)), ...
        "StrengthBoundary:InvalidActuatorPercent", ...
        "ActuatorPercent values must be positive integers.");

    coordinateKeys = ...
        compose( ...
            "%d|%d", ...
            musclePercent, ...
            actuatorPercent);

    assert(numel(unique(coordinateKeys)) == height(summary), ...
        "StrengthBoundary:DuplicateCoordinate", ...
        "Each numeric muscle/actuator coordinate must be unique.");

    %% Require safe monotonic evidence

    monotonicity = ...
        soopt.auditFeasibilityMonotonicity( ...
            summary);

    assert(monotonicity.IsMonotonic, ...
        "StrengthBoundary:MonotonicityViolation", ...
        "Adaptive boundary refinement is unsafe because the assessed " + ...
        "evidence contains %d monotonicity violation(s).", ...
        monotonicity.ViolationCount);

    assessedMask = ...
        assessmentComplete;

    feasibleMask = ...
        assessedMask & ...
        isFeasible;

    infeasibleMask = ...
        assessedMask & ...
        ~isFeasible;

    if ~any(feasibleMask) || ...
            ~any(infeasibleMask)

        proposals = ...
            localEmptyProposalTable();

        return;
    end

    %% Resolve numeric search bounds

    assessedMuscle = ...
        musclePercent(assessedMask);

    assessedActuator = ...
        actuatorPercent(assessedMask);

    if isempty(muscleBounds)

        muscleBounds = [
            min(assessedMuscle)
            max(assessedMuscle)
        ];

    else

        muscleBounds = ...
            sort(muscleBounds(:));
    end

    if isempty(actuatorBounds)

        actuatorBounds = [
            min(assessedActuator)
            max(assessedActuator)
        ];

    else

        actuatorBounds = ...
            sort(actuatorBounds(:));
    end

    assert( ...
        muscleBounds(1) > 0 && ...
        muscleBounds(2) >= muscleBounds(1), ...
        "StrengthBoundary:InvalidMuscleBounds", ...
        "MuscleBounds must define a positive nondecreasing interval.");

    assert( ...
        actuatorBounds(1) > 0 && ...
        actuatorBounds(2) >= actuatorBounds(1), ...
        "StrengthBoundary:InvalidActuatorBounds", ...
        "ActuatorBounds must define a positive nondecreasing interval.");

    muscleGrid = ...
        localQuantizedAxis( ...
            muscleBounds, ...
            incrementPercent);

    actuatorGrid = ...
        localQuantizedAxis( ...
            actuatorBounds, ...
            incrementPercent);

    if isempty(muscleGrid) || ...
            isempty(actuatorGrid)

        proposals = ...
            localEmptyProposalTable();

        return;
    end

    %% Build virtual adaptive lattice

    [muscleMatrix, actuatorMatrix] = ...
        ndgrid( ...
            muscleGrid, ...
            actuatorGrid);

    gridMuscle = ...
        muscleMatrix(:);

    gridActuator = ...
        actuatorMatrix(:);

    nGrid = ...
        numel(gridMuscle);

    alreadyAssessed = ...
        false(nGrid,1);

    existingIncomplete = ...
        false(nGrid,1);

    existingConfigId = ...
        strings(nGrid,1);

    inferredFeasible = ...
        false(nGrid,1);

    inferredInfeasible = ...
        false(nGrid,1);

    boundaryBracketed = ...
        false(nGrid,1);

    lowerSupportIndex = ...
        zeros(nGrid,1);

    upperSupportIndex = ...
        zeros(nGrid,1);

    feasibleIndices = ...
        find(feasibleMask);

    infeasibleIndices = ...
        find(infeasibleMask);

    for iGrid = 1:nGrid

        candidateMuscle = ...
            gridMuscle(iGrid);

        candidateActuator = ...
            gridActuator(iGrid);

        exactMask = ...
            musclePercent == candidateMuscle & ...
            actuatorPercent == candidateActuator;

        if any(exactMask)

            exactIndex = ...
                find(exactMask, 1);

            existingConfigId(iGrid) = ...
                configIds(exactIndex);

            if assessmentComplete(exactIndex)

                alreadyAssessed(iGrid) = ...
                    true;

            else

                existingIncomplete(iGrid) = ...
                    true;
            end
        end

        feasibleLowerLeft = ...
            feasibleIndices( ...
                musclePercent(feasibleIndices) <= candidateMuscle & ...
                actuatorPercent(feasibleIndices) <= candidateActuator);

        infeasibleUpperRight = ...
            infeasibleIndices( ...
                musclePercent(infeasibleIndices) >= candidateMuscle & ...
                actuatorPercent(infeasibleIndices) >= candidateActuator);

        inferredFeasible(iGrid) = ...
            ~isempty(feasibleLowerLeft);

        inferredInfeasible(iGrid) = ...
            ~isempty(infeasibleUpperRight);

        lowerInfeasible = ...
            infeasibleIndices( ...
                musclePercent(infeasibleIndices) <= candidateMuscle & ...
                actuatorPercent(infeasibleIndices) <= candidateActuator);

        upperFeasible = ...
            feasibleIndices( ...
                musclePercent(feasibleIndices) >= candidateMuscle & ...
                actuatorPercent(feasibleIndices) >= candidateActuator);

        boundaryBracketed(iGrid) = ...
            ~isempty(lowerInfeasible) && ...
            ~isempty(upperFeasible);

        if boundaryBracketed(iGrid)

            lowerSupportIndex(iGrid) = ...
                localNearestLowerSupport( ...
                    lowerInfeasible, ...
                    musclePercent, ...
                    actuatorPercent, ...
                    configIds, ...
                    candidateMuscle, ...
                    candidateActuator);

            upperSupportIndex(iGrid) = ...
                localNearestUpperSupport( ...
                    upperFeasible, ...
                    musclePercent, ...
                    actuatorPercent, ...
                    configIds, ...
                    candidateMuscle, ...
                    candidateActuator);
        end
    end

    assert(~any( ...
        inferredFeasible & ...
        inferredInfeasible), ...
        "StrengthBoundary:ConflictingInference", ...
        "Virtual lattice contains conflicting monotonic feasibility " + ...
        "inference despite a passing monotonicity audit.");

    needsAssessment = ...
        ~alreadyAssessed & ...
        ~inferredFeasible & ...
        ~inferredInfeasible;

    if requireExplicitBracket

        eligible = ...
            needsAssessment & ...
            boundaryBracketed;

    else

        eligible = ...
            needsAssessment;
    end

    eligibleIndices = ...
        find(eligible);

    if isempty(eligibleIndices)

        proposals = ...
            localEmptyProposalTable();

        return;
    end

    %% Allocate candidate diagnostics

    nCandidates = ...
        numel(eligibleIndices);

    ConfigId = ...
        strings(nCandidates,1);

    MusclePercent = ...
        zeros(nCandidates,1);

    ActuatorPercent = ...
        zeros(nCandidates,1);

    ExistingIncomplete = ...
        false(nCandidates,1);

    ExistingConfigId = ...
        strings(nCandidates,1);

    IncrementPercent = ...
        repmat( ...
            incrementPercent, ...
            nCandidates, ...
            1);

    LowerInfeasibleConfigId = ...
        strings(nCandidates,1);

    LowerInfeasibleMusclePercent = ...
        NaN(nCandidates,1);

    LowerInfeasibleActuatorPercent = ...
        NaN(nCandidates,1);

    UpperFeasibleConfigId = ...
        strings(nCandidates,1);

    UpperFeasibleMusclePercent = ...
        NaN(nCandidates,1);

    UpperFeasibleActuatorPercent = ...
        NaN(nCandidates,1);

    MuscleBracketWidth = ...
        NaN(nCandidates,1);

    ActuatorBracketWidth = ...
        NaN(nCandidates,1);

    BracketSpanSteps = ...
        NaN(nCandidates,1);

    DistanceToLowerSteps = ...
        NaN(nCandidates,1);

    DistanceToUpperSteps = ...
        NaN(nCandidates,1);

    CenterImbalanceSteps = ...
        NaN(nCandidates,1);

    FeasibleOutcomeResolvedCount = ...
        zeros(nCandidates,1);

    InfeasibleOutcomeResolvedCount = ...
        zeros(nCandidates,1);

    WorstCaseResolvedCount = ...
        zeros(nCandidates,1);

    BestCaseResolvedCount = ...
        zeros(nCandidates,1);

    TotalResolutionPotential = ...
        zeros(nCandidates,1);

    ResolutionImbalance = ...
        zeros(nCandidates,1);

    %% Score candidates

    unresolvedIndices = ...
        find(eligible);

    for iCandidate = 1:nCandidates

        iGrid = ...
            eligibleIndices(iCandidate);

        candidateMuscle = ...
            gridMuscle(iGrid);

        candidateActuator = ...
            gridActuator(iGrid);

        ConfigId(iCandidate) = ...
            localConfigId( ...
                candidateMuscle, ...
                candidateActuator);

        MusclePercent(iCandidate) = ...
            candidateMuscle;

        ActuatorPercent(iCandidate) = ...
            candidateActuator;

        ExistingIncomplete(iCandidate) = ...
            existingIncomplete(iGrid);

        ExistingConfigId(iCandidate) = ...
            existingConfigId(iGrid);

        if boundaryBracketed(iGrid)

            iLower = ...
                lowerSupportIndex(iGrid);

            iUpper = ...
                upperSupportIndex(iGrid);

            LowerInfeasibleConfigId(iCandidate) = ...
                configIds(iLower);

            LowerInfeasibleMusclePercent(iCandidate) = ...
                musclePercent(iLower);

            LowerInfeasibleActuatorPercent(iCandidate) = ...
                actuatorPercent(iLower);

            UpperFeasibleConfigId(iCandidate) = ...
                configIds(iUpper);

            UpperFeasibleMusclePercent(iCandidate) = ...
                musclePercent(iUpper);

            UpperFeasibleActuatorPercent(iCandidate) = ...
                actuatorPercent(iUpper);

            MuscleBracketWidth(iCandidate) = ...
                musclePercent(iUpper) - ...
                musclePercent(iLower);

            ActuatorBracketWidth(iCandidate) = ...
                actuatorPercent(iUpper) - ...
                actuatorPercent(iLower);

            BracketSpanSteps(iCandidate) = ...
                ( ...
                    MuscleBracketWidth(iCandidate) + ...
                    ActuatorBracketWidth(iCandidate) ...
                ) / ...
                incrementPercent;

            DistanceToLowerSteps(iCandidate) = ...
                ( ...
                    candidateMuscle - ...
                    musclePercent(iLower) + ...
                    candidateActuator - ...
                    actuatorPercent(iLower) ...
                ) / ...
                incrementPercent;

            DistanceToUpperSteps(iCandidate) = ...
                ( ...
                    musclePercent(iUpper) - ...
                    candidateMuscle + ...
                    actuatorPercent(iUpper) - ...
                    candidateActuator ...
                ) / ...
                incrementPercent;

            CenterImbalanceSteps(iCandidate) = ...
                abs( ...
                    DistanceToLowerSteps(iCandidate) - ...
                    DistanceToUpperSteps(iCandidate));
        end

        feasibleResolved = ...
            unresolvedIndices( ...
                gridMuscle(unresolvedIndices) >= candidateMuscle & ...
                gridActuator(unresolvedIndices) >= candidateActuator);

        infeasibleResolved = ...
            unresolvedIndices( ...
                gridMuscle(unresolvedIndices) <= candidateMuscle & ...
                gridActuator(unresolvedIndices) <= candidateActuator);

        FeasibleOutcomeResolvedCount(iCandidate) = ...
            numel(feasibleResolved);

        InfeasibleOutcomeResolvedCount(iCandidate) = ...
            numel(infeasibleResolved);

        WorstCaseResolvedCount(iCandidate) = ...
            min( ...
                FeasibleOutcomeResolvedCount(iCandidate), ...
                InfeasibleOutcomeResolvedCount(iCandidate));

        BestCaseResolvedCount(iCandidate) = ...
            max( ...
                FeasibleOutcomeResolvedCount(iCandidate), ...
                InfeasibleOutcomeResolvedCount(iCandidate));

        TotalResolutionPotential(iCandidate) = ...
            FeasibleOutcomeResolvedCount(iCandidate) + ...
            InfeasibleOutcomeResolvedCount(iCandidate);

        ResolutionImbalance(iCandidate) = ...
            abs( ...
                FeasibleOutcomeResolvedCount(iCandidate) - ...
                InfeasibleOutcomeResolvedCount(iCandidate));
    end

    %% Rank deterministically

    candidateTable = ...
        table( ...
            ConfigId, ...
            MusclePercent, ...
            ActuatorPercent, ...
            ExistingIncomplete, ...
            ExistingConfigId, ...
            IncrementPercent, ...
            LowerInfeasibleConfigId, ...
            LowerInfeasibleMusclePercent, ...
            LowerInfeasibleActuatorPercent, ...
            UpperFeasibleConfigId, ...
            UpperFeasibleMusclePercent, ...
            UpperFeasibleActuatorPercent, ...
            MuscleBracketWidth, ...
            ActuatorBracketWidth, ...
            BracketSpanSteps, ...
            DistanceToLowerSteps, ...
            DistanceToUpperSteps, ...
            CenterImbalanceSteps, ...
            FeasibleOutcomeResolvedCount, ...
            InfeasibleOutcomeResolvedCount, ...
            WorstCaseResolvedCount, ...
            BestCaseResolvedCount, ...
            TotalResolutionPotential, ...
            ResolutionImbalance);

    candidateTable = ...
        sortrows( ...
            candidateTable, ...
            { ...
                'BracketSpanSteps', ...
                'WorstCaseResolvedCount', ...
                'CenterImbalanceSteps', ...
                'ExistingIncomplete', ...
                'TotalResolutionPotential', ...
                'ResolutionImbalance', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ConfigId' ...
            }, ...
            { ...
                'descend', ...
                'descend', ...
                'ascend', ...
                'descend', ...
                'descend', ...
                'ascend', ...
                'ascend', ...
                'ascend', ...
                'ascend' ...
            });

    nReturn = ...
        min( ...
            height(candidateTable), ...
            maxProposals);

    if isinf(maxProposals)

        nReturn = ...
            height(candidateTable);
    end

    proposals = ...
        candidateTable( ...
            1:nReturn, ...
            :);

    PriorityRank = ...
        (1:height(proposals)).';

    proposals = ...
        addvars( ...
            proposals, ...
            PriorityRank, ...
            'Before', ...
            1);
end


function axisValues = ...
        localQuantizedAxis(bounds, incrementPercent)

    lowerValue = ...
        ceil(bounds(1) / incrementPercent) * ...
        incrementPercent;

    upperValue = ...
        floor(bounds(2) / incrementPercent) * ...
        incrementPercent;

    if lowerValue > upperValue

        axisValues = ...
            zeros(0,1);

        return;
    end

    axisValues = ...
        ( ...
            lowerValue : ...
            incrementPercent : ...
            upperValue ...
        ).';
end


function index = localNearestLowerSupport( ...
        candidateIndices, ...
        musclePercent, ...
        actuatorPercent, ...
        configIds, ...
        candidateMuscle, ...
        candidateActuator)

    distance = ...
        (candidateMuscle - musclePercent(candidateIndices)) + ...
        (candidateActuator - actuatorPercent(candidateIndices));

    supportTable = ...
        table( ...
            candidateIndices(:), ...
            distance(:), ...
            musclePercent(candidateIndices), ...
            actuatorPercent(candidateIndices), ...
            configIds(candidateIndices), ...
            'VariableNames', { ...
                'Index', ...
                'Distance', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ConfigId'});

    supportTable = ...
        sortrows( ...
            supportTable, ...
            { ...
                'Distance', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ConfigId' ...
            }, ...
            { ...
                'ascend', ...
                'descend', ...
                'descend', ...
                'ascend' ...
            });

    index = ...
        supportTable.Index(1);
end


function index = localNearestUpperSupport( ...
        candidateIndices, ...
        musclePercent, ...
        actuatorPercent, ...
        configIds, ...
        candidateMuscle, ...
        candidateActuator)

    distance = ...
        (musclePercent(candidateIndices) - candidateMuscle) + ...
        (actuatorPercent(candidateIndices) - candidateActuator);

    supportTable = ...
        table( ...
            candidateIndices(:), ...
            distance(:), ...
            musclePercent(candidateIndices), ...
            actuatorPercent(candidateIndices), ...
            configIds(candidateIndices), ...
            'VariableNames', { ...
                'Index', ...
                'Distance', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ConfigId'});

    supportTable = ...
        sortrows( ...
            supportTable, ...
            { ...
                'Distance', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ConfigId' ...
            }, ...
            { ...
                'ascend', ...
                'ascend', ...
                'ascend', ...
                'ascend' ...
            });

    index = ...
        supportTable.Index(1);
end


function configId = ...
        localConfigId(musclePercent, actuatorPercent)

    configId = ...
        "m" + ...
        string(musclePercent) + ...
        "p_a" + ...
        compose("%02d", actuatorPercent) + ...
        "p";
end


function T = localEmptyProposalTable()

    T = ...
        table( ...
            zeros(0,1), ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            false(0,1), ...
            strings(0,1), ...
            zeros(0,1), ...
            strings(0,1), ...
            NaN(0,1), ...
            NaN(0,1), ...
            strings(0,1), ...
            NaN(0,1), ...
            NaN(0,1), ...
            NaN(0,1), ...
            NaN(0,1), ...
            NaN(0,1), ...
            NaN(0,1), ...
            NaN(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            'VariableNames', { ...
                'PriorityRank', ...
                'ConfigId', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ExistingIncomplete', ...
                'ExistingConfigId', ...
                'IncrementPercent', ...
                'LowerInfeasibleConfigId', ...
                'LowerInfeasibleMusclePercent', ...
                'LowerInfeasibleActuatorPercent', ...
                'UpperFeasibleConfigId', ...
                'UpperFeasibleMusclePercent', ...
                'UpperFeasibleActuatorPercent', ...
                'MuscleBracketWidth', ...
                'ActuatorBracketWidth', ...
                'BracketSpanSteps', ...
                'DistanceToLowerSteps', ...
                'DistanceToUpperSteps', ...
                'CenterImbalanceSteps', ...
                'FeasibleOutcomeResolvedCount', ...
                'InfeasibleOutcomeResolvedCount', ...
                'WorstCaseResolvedCount', ...
                'BestCaseResolvedCount', ...
                'TotalResolutionPotential', ...
                'ResolutionImbalance'});
end
