function report = reauditStaticOptimizationConfigurations(projectCfg, varargin)
%REAUDITSTATICOPTIMIZATIONCONFIGURATIONS Re-audit saved SO activation files.
%
% report = soopt.reauditStaticOptimizationConfigurations(projectCfg)
%
% This utility retrospectively applies the current Static Optimization
% activation-saturation criterion to configuration runs that already exist
% beneath:
%
%   <outputRoot>/static_optimization_configs/<ConfigId>/
%
% Static Optimization is NEVER re-executed.
%
% For each configuration with an existing canonical Process-4 summary:
%
%   1. read the saved batch summary CSV;
%   2. resolve each saved activation STO;
%   3. run opensimrun.auditStaticOptimizationActivations;
%   4. write/update the per-trial activation-audit CSV;
%   5. demote formerly successful saturated trials to:
%
%          Status    = "activation_saturation"
%          Succeeded = false
%
%   6. preserve any pre-existing trial failures;
%   7. rewrite the canonical Process-4 CSV/MAT summary.
%
% A trial that previously succeeded but whose activation STO cannot be
% resolved is conservatively marked failed because the required saturation
% criterion cannot be evaluated.
%
% Existing raw STO files and physical Process-4 checkpoints are NEVER
% deleted or modified. For a trial newly demoted by this audit, the
% CheckpointFile entry in the rewritten summary is cleared so the summary
% reflects the current Process-4 success contract.
%
% By default, the original summary CSV/MAT are backed up once using:
%
%   *_pre_activation_saturation_reaudit.csv
%   *_pre_activation_saturation_reaudit.mat
%
% NAME-VALUE OPTIONS
%
%   ConfigIds
%       Optional string vector of configuration IDs to re-audit. Default
%       empty means every discovered configuration directory.
%
%   WriteChanges
%       true (default). When false, perform the full audit in memory but do
%       not write QC files, backups, or rewritten summaries.
%
%   BackupExistingSummaries
%       true (default). Applies only when WriteChanges is true.
%
%   PrintProgress
%       true (default).
%
% RETURN TABLE
%
%   ConfigId
%   MusclePercent
%   ActuatorPercent
%   SummaryFound
%   TrialsInSummary
%   TrialsAudited
%   TrialsSaturated
%   TrialsAuditUnavailable
%   TrialsDemoted
%   TrialsSucceededAfterReaudit
%   ConfigurationFeasible
%   SummaryUpdated
%   BackupCsv
%   BackupMat
%   Status
%   ErrorIdentifier
%   ErrorMessage
%
% This function intentionally has filesystem side effects only when
% WriteChanges == true.

    %% Parse inputs

    parser = inputParser;

    parser.FunctionName = ...
        "soopt.reauditStaticOptimizationConfigurations";

    addRequired(parser, ...
        "projectCfg", ...
        @(x) isstruct(x) && isscalar(x));

    addParameter(parser, ...
        "ConfigIds", ...
        strings(0,1), ...
        @(x) ischar(x) || isstring(x) || iscellstr(x));

    addParameter(parser, ...
        "WriteChanges", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "BackupExistingSummaries", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "PrintProgress", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, ...
        projectCfg, ...
        varargin{:});

    requestedConfigIds = ...
        string(parser.Results.ConfigIds(:));

    requestedConfigIds = ...
        requestedConfigIds( ...
            ~ismissing(requestedConfigIds) & ...
            strlength(requestedConfigIds) > 0);

    writeChanges = ...
        parser.Results.WriteChanges;

    backupExistingSummaries = ...
        parser.Results.BackupExistingSummaries;

    printProgress = ...
        parser.Results.PrintProgress;

    %% Validate saturation configuration

    assert(isfield(projectCfg, "pipeline") && ...
            isfield(projectCfg.pipeline, "staticOptimization"), ...
        "RetrospectiveSOAudit:ConfigurationMissing", ...
        "projectCfg.pipeline.staticOptimization is required.");

    soCfg = ...
        projectCfg.pipeline.staticOptimization;

    requiredSoFields = ...
        "activationSaturationThreshold";

    missingSoFields = ...
        requiredSoFields( ...
            ~isfield( ...
                soCfg, ...
                cellstr(requiredSoFields)));

    assert(isempty(missingSoFields), ...
        "RetrospectiveSOAudit:ConfigurationMissing", ...
        "Static Optimization configuration is missing: %s", ...
        strjoin(missingSoFields, ", "));

    saturationThreshold = ...
        double(soCfg.activationSaturationThreshold);

    %% Discover completed/output configuration roots

    configs = ...
        soopt.discoverStrengthConfigurations( ...
            projectCfg);

    if isempty(configs)

        report = ...
            localEmptyReport();

        return;
    end

    if ~isempty(requestedConfigIds)

        missingRequested = ...
            requestedConfigIds( ...
                ~ismember( ...
                    requestedConfigIds, ...
                    configs.ConfigId));

        assert(isempty(missingRequested), ...
            "RetrospectiveSOAudit:ConfigNotFound", ...
            "Requested configuration directories were not found: %s", ...
            strjoin(missingRequested, ", "));

        configs = ...
            configs( ...
                ismember( ...
                    configs.ConfigId, ...
                    requestedConfigIds), ...
                :);
    end

    %% Re-audit configurations independently

    nConfigs = ...
        height(configs);

    rows = ...
        repmat( ...
            localEmptyReportRow(), ...
            nConfigs, ...
            1);

    for iConfig = 1:nConfigs

        configRow = ...
            configs(iConfig,:);

        rows(iConfig) = ...
            localReauditConfiguration( ...
                configRow, ...
                saturationThreshold, ...
                writeChanges, ...
                backupExistingSummaries, ...
                printProgress);
    end

    report = ...
        struct2table(rows);

    report = ...
        sortrows( ...
            report, ...
            { ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ConfigId'});
end


function row = localReauditConfiguration( ...
        configRow, ...
        saturationThreshold, ...
        writeChanges, ...
        backupExistingSummaries, ...
        printProgress)

    row = ...
        localEmptyReportRow();

    row.ConfigId = ...
        string(configRow.ConfigId);

    row.MusclePercent = ...
        double(configRow.MusclePercent);

    row.ActuatorPercent = ...
        double(configRow.ActuatorPercent);

    summaryCsv = ...
        string(configRow.Process4SummaryCsv);

    summaryMat = ...
        string(configRow.Process4SummaryMat);

    row.SummaryFound = ...
        isfile(summaryCsv);

    if printProgress

        fprintf( ...
            "\nRe-auditing %s (%g%% muscle, %g%% actuator)\n", ...
            row.ConfigId, ...
            row.MusclePercent, ...
            row.ActuatorPercent);
    end

    if ~row.SummaryFound

        row.Status = ...
            "SUMMARY_MISSING";

        if printProgress

            fprintf( ...
                "  Process-4 summary not found; skipped.\n");
        end

        return;
    end

    try

        summary = ...
            readtable( ...
                summaryCsv, ...
                "Delimiter", ",", ...
                "ReadVariableNames", true, ...
                "VariableNamingRule", "preserve", ...
                "TextType", "string");

        localValidateSummaryIdentity( ...
            summary, ...
            configRow);

        summary = ...
            localPrepareSummaryColumns( ...
                summary);

        row.TrialsInSummary = ...
            height(summary);

        originalSucceeded = ...
            localLogicalVector( ...
                summary.Succeeded, ...
                "Succeeded");

        outputAuditPassed = ...
            localLogicalVector( ...
                summary.OutputAuditPassed, ...
                "OutputAuditPassed");

        summary.Succeeded = ...
            originalSucceeded;

        summary.OutputAuditPassed = ...
            outputAuditPassed;

        for iTrial = 1:height(summary)

            priorSucceeded = ...
                originalSucceeded(iTrial);

            try

                [activationFile, resolutionErrorId, resolutionErrorMessage] = ...
                    localResolveActivationFile( ...
                        summary, ...
                        iTrial);

                if strlength(activationFile) == 0

                    summary.ActivationSaturationAudited(iTrial) = ...
                        false;

                    summary.ActivationSaturationPassed(iTrial) = ...
                        false;

                    if priorSucceeded

                        summary.Succeeded(iTrial) = ...
                            false;

                        summary.Status(iTrial) = ...
                            "failed";

                        summary.CheckpointFile(iTrial) = ...
                            "";
                    end

                    if strlength(resolutionErrorId) == 0

                        resolutionErrorId = ...
                            "PipelineSO:ActivationAuditUnavailable";

                        resolutionErrorMessage = ...
                            "Activation saturation QC is required, but " + ...
                            "no saved activation output file was available.";
                    end

                    if strlength(summary.ErrorIdentifier(iTrial)) == 0

                        summary.ErrorIdentifier(iTrial) = ...
                            resolutionErrorId;

                        summary.ErrorMessage(iTrial) = ...
                            resolutionErrorMessage;
                    end

                    row.TrialsAuditUnavailable = ...
                        row.TrialsAuditUnavailable + 1;

                    continue;
                end

                summary.ActivationFile(iTrial) = ...
                    activationFile;

                audit = ...
                    opensimrun.auditStaticOptimizationActivations( ...
                        activationFile, ...
                        "SaturationThreshold", ...
                            saturationThreshold);

                row.TrialsAudited = ...
                    row.TrialsAudited + 1;

                summary.ActivationSaturationAudited(iTrial) = ...
                    true;

                summary.ActivationSaturationPassed(iTrial) = ...
                    logical(audit.Passed);

                summary.ActivationSaturationThreshold(iTrial) = ...
                    audit.SaturationThreshold;

                summary.PeakAbsoluteActivation(iTrial) = ...
                    audit.PeakAbsoluteActivation;

                summary.PeakActivationValue(iTrial) = ...
                    audit.PeakActivationValue;

                summary.PeakActivationLabel(iTrial) = ...
                    audit.PeakLabel;

                summary.PeakActivationTime(iTrial) = ...
                    audit.PeakTime;

                summary.SaturatedValueCount(iTrial) = ...
                    audit.SaturatedValueCount;

                summary.SaturatedChannelCount(iTrial) = ...
                    audit.SaturatedChannelCount;

                summary.SaturatedLabels(iTrial) = ...
                    strjoin( ...
                        string(audit.SaturatedLabels(:)), ...
                        ";");

                summary.FirstSaturationTime(iTrial) = ...
                    audit.FirstSaturationTime;

                summary.LastSaturationTime(iTrial) = ...
                    audit.LastSaturationTime;

                auditCsv = ...
                    localActivationAuditCsv( ...
                        summary, ...
                        iTrial, ...
                        activationFile);

                if writeChanges

                    auditDirectory = ...
                        string(fileparts(auditCsv));

                    if ~isfolder(auditDirectory)

                        mkdir(auditDirectory);
                    end

                    writetable( ...
                        audit.ChannelSummary, ...
                        auditCsv);

                    summary.ActivationAuditCsv(iTrial) = ...
                        auditCsv;
                end

                if ~audit.Passed

                    row.TrialsSaturated = ...
                        row.TrialsSaturated + 1;

                    if priorSucceeded

                        summary.Succeeded(iTrial) = ...
                            false;

                        summary.Status(iTrial) = ...
                            "activation_saturation";

                        summary.CheckpointFile(iTrial) = ...
                            "";
                    end

                elseif priorSucceeded && ...
                        outputAuditPassed(iTrial)

                    summary.Succeeded(iTrial) = ...
                        true;

                    summary.Status(iTrial) = ...
                        "completed";
                end

            catch exception

                if priorSucceeded

                    summary.Succeeded(iTrial) = ...
                        false;

                    summary.Status(iTrial) = ...
                        "failed";

                    summary.CheckpointFile(iTrial) = ...
                        "";
                end

                summary.ActivationSaturationAudited(iTrial) = ...
                    false;

                summary.ActivationSaturationPassed(iTrial) = ...
                    false;

                if strlength(summary.ErrorIdentifier(iTrial)) == 0

                    summary.ErrorIdentifier(iTrial) = ...
                        string(exception.identifier);

                    summary.ErrorMessage(iTrial) = ...
                        string(exception.message);
                end

                row.TrialsAuditUnavailable = ...
                    row.TrialsAuditUnavailable + 1;
            end
        end

        row.TrialsDemoted = ...
            nnz( ...
                originalSucceeded & ...
                ~summary.Succeeded);

        row.TrialsSucceededAfterReaudit = ...
            nnz(summary.Succeeded);

        row.ConfigurationFeasible = ...
            ~isempty(summary) && ...
            all(summary.Succeeded) && ...
            all(summary.OutputAuditPassed) && ...
            all(summary.ActivationSaturationAudited) && ...
            all(summary.ActivationSaturationPassed);

        if writeChanges

            if backupExistingSummaries

                row.BackupCsv = ...
                    localBackupOnce( ...
                        summaryCsv);

                if isfile(summaryMat)

                    row.BackupMat = ...
                        localBackupOnce( ...
                            summaryMat);
                end
            end

            writetable( ...
                summary, ...
                summaryCsv);

            localWriteBatchSummaryMat( ...
                summaryMat, ...
                summary, ...
                configRow, ...
                saturationThreshold);

            row.SummaryUpdated = ...
                true;
        end

        row.Status = ...
            "REAUDITED";

        if printProgress

            fprintf( ...
                "  Audited: %d | Saturated: %d | Unavailable: %d | " + ...
                "Succeeded after re-audit: %d/%d\n", ...
                row.TrialsAudited, ...
                row.TrialsSaturated, ...
                row.TrialsAuditUnavailable, ...
                row.TrialsSucceededAfterReaudit, ...
                row.TrialsInSummary);
        end

    catch exception

        row.Status = ...
            "ERROR";

        row.ErrorIdentifier = ...
            string(exception.identifier);

        row.ErrorMessage = ...
            string(exception.message);

        if printProgress

            fprintf( ...
                "  ERROR: %s\n", ...
                exception.message);
        end
    end
end


function localValidateSummaryIdentity(summary, configRow)

    requiredVariables = [
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
        "ConditionDeg"
        "TrialNumber"
        "Status"
        "Succeeded"
        "ResultsDirectory"
        "ActivationFile"
        "OutputAuditPassed"
        "CheckpointFile"
    ];

    missingVariables = ...
        requiredVariables( ...
            ~ismember( ...
                requiredVariables, ...
                string(summary.Properties.VariableNames)));

    assert(isempty(missingVariables), ...
        "RetrospectiveSOAudit:SummarySchemaInvalid", ...
        "Process-4 summary is missing required variables: %s", ...
        strjoin(missingVariables, ", "));

    assert(all(string(summary.ConfigId) == string(configRow.ConfigId)), ...
        "RetrospectiveSOAudit:ConfigIdentityMismatch", ...
        "Process-4 summary ConfigId does not match directory identity %s.", ...
        string(configRow.ConfigId));

    assert(all(double(summary.MusclePercent) == ...
            double(configRow.MusclePercent)), ...
        "RetrospectiveSOAudit:ConfigIdentityMismatch", ...
        "Process-4 summary MusclePercent does not match %s.", ...
        string(configRow.ConfigId));

    assert(all(double(summary.ActuatorPercent) == ...
            double(configRow.ActuatorPercent)), ...
        "RetrospectiveSOAudit:ConfigIdentityMismatch", ...
        "Process-4 summary ActuatorPercent does not match %s.", ...
        string(configRow.ConfigId));
end


function summary = localPrepareSummaryColumns(summary)

    nRows = ...
        height(summary);

    summary.ConfigId = ...
        string(summary.ConfigId);

    summary.Status = ...
        fillmissing( ...
            string(summary.Status), ...
            "constant", ...
            "");

    summary.ResultsDirectory = ...
        fillmissing( ...
            string(summary.ResultsDirectory), ...
            "constant", ...
            "");

    summary.ActivationFile = ...
        fillmissing( ...
            string(summary.ActivationFile), ...
            "constant", ...
            "");

    summary.CheckpointFile = ...
        fillmissing( ...
            string(summary.CheckpointFile), ...
            "constant", ...
            "");

    if ~ismember( ...
            "ErrorIdentifier", ...
            string(summary.Properties.VariableNames))

        summary.ErrorIdentifier = ...
            strings(nRows,1);

        summary.ErrorMessage = ...
            strings(nRows,1);

    else

        summary.ErrorIdentifier = ...
            fillmissing( ...
                string(summary.ErrorIdentifier), ...
                "constant", ...
                "");

        summary.ErrorMessage = ...
            fillmissing( ...
                string(summary.ErrorMessage), ...
                "constant", ...
                "");
    end

    variableNames = ...
        string(summary.Properties.VariableNames);

    if ~ismember("ActivationSaturationAudited", variableNames)
        summary.ActivationSaturationAudited = false(nRows,1);
    end

    if ~ismember("ActivationSaturationPassed", variableNames)
        summary.ActivationSaturationPassed = false(nRows,1);
    end

    if ~ismember("ActivationSaturationThreshold", variableNames)
        summary.ActivationSaturationThreshold = nan(nRows,1);
    end

    if ~ismember("PeakAbsoluteActivation", variableNames)
        summary.PeakAbsoluteActivation = nan(nRows,1);
    end

    if ~ismember("PeakActivationValue", variableNames)
        summary.PeakActivationValue = nan(nRows,1);
    end

    if ~ismember("PeakActivationLabel", variableNames)
        summary.PeakActivationLabel = strings(nRows,1);
    else
        summary.PeakActivationLabel = ...
            fillmissing( ...
                string(summary.PeakActivationLabel), ...
                "constant", ...
                "");
    end

    if ~ismember("PeakActivationTime", variableNames)
        summary.PeakActivationTime = nan(nRows,1);
    end

    if ~ismember("SaturatedValueCount", variableNames)
        summary.SaturatedValueCount = nan(nRows,1);
    end

    if ~ismember("SaturatedChannelCount", variableNames)
        summary.SaturatedChannelCount = nan(nRows,1);
    end

    if ~ismember("SaturatedLabels", variableNames)
        summary.SaturatedLabels = strings(nRows,1);
    else
        summary.SaturatedLabels = string(summary.SaturatedLabels);
    end

    if ~ismember("FirstSaturationTime", variableNames)
        summary.FirstSaturationTime = nan(nRows,1);
    end

    if ~ismember("LastSaturationTime", variableNames)
        summary.LastSaturationTime = nan(nRows,1);
    end

    if ~ismember("ActivationAuditCsv", variableNames)
        summary.ActivationAuditCsv = strings(nRows,1);
    else
        summary.ActivationAuditCsv = string(summary.ActivationAuditCsv);
    end
end


function values = localLogicalVector(values, variableName)

    if islogical(values)

        values = ...
            values(:);

        return;
    end

    if isnumeric(values)

        assert(all(ismember(values(:), [0 1])), ...
            "RetrospectiveSOAudit:InvalidLogicalField", ...
            "%s must contain only logical/0/1 values.", ...
            variableName);

        values = ...
            logical(values(:));

        return;
    end

    text = ...
        lower(strtrim(string(values(:))));

    assert(all(ismember( ...
            text, ...
            ["true" "false" "1" "0"])), ...
        "RetrospectiveSOAudit:InvalidLogicalField", ...
        "%s contains values that cannot be interpreted as logical.", ...
        variableName);

    values = ...
        text == "true" | ...
        text == "1";
end


function [activationFile, errorId, errorMessage] = ...
        localResolveActivationFile(summary, iTrial)

    activationFile = ...
        string(summary.ActivationFile(iTrial));

    errorId = "";
    errorMessage = "";

    if strlength(activationFile) > 0 && ...
            isfile(activationFile)

        return;
    end

    resultsDirectory = ...
        string(summary.ResultsDirectory(iTrial));

    if ~isfolder(resultsDirectory)

        activationFile = "";

        return;
    end

    listing = ...
        dir(fullfile( ...
            resultsDirectory, ...
            "*StaticOptimization_activation.sto"));

    if isempty(listing)

        activationFile = "";

        return;
    end

    if numel(listing) > 1

        activationFile = "";

        errorId = ...
            "RetrospectiveSOAudit:AmbiguousActivationFiles";

        errorMessage = ...
            "Multiple Static Optimization activation STO files were " + ...
            "found in: " + ...
            resultsDirectory;

        return;
    end

    activationFile = ...
        string(fullfile( ...
            listing(1).folder, ...
            listing(1).name));
end


function auditCsv = localActivationAuditCsv( ...
        summary, iTrial, activationFile)

    resultsDirectory = ...
        string(summary.ResultsDirectory(iTrial));

    if ~isfolder(resultsDirectory)

        resultsDirectory = ...
            string(fileparts(activationFile));
    end

    staticOptimizationDirectory = ...
        string(fileparts(resultsDirectory));

    auditCsv = ...
        string(fullfile( ...
            staticOptimizationDirectory, ...
            "qc", ...
            "static_optimization_activation_audit.csv"));
end


function backupFile = localBackupOnce(filePath)

    filePath = ...
        string(filePath);

    [directory, stem, extension] = ...
        fileparts(filePath);

    backupFile = ...
        string(fullfile( ...
            directory, ...
            stem + ...
            "_pre_activation_saturation_reaudit" + ...
            extension));

    if ~isfile(backupFile)

        [copied, message] = ...
            copyfile( ...
                filePath, ...
                backupFile);

        assert(copied, ...
            "RetrospectiveSOAudit:BackupFailed", ...
            "Could not back up:\n%s\n\n%s", ...
            filePath, ...
            message);
    end
end


function localWriteBatchSummaryMat( ...
        summaryMat, ...
        summary, ...
        configRow, ...
        saturationThreshold)

    batchSummary = struct;

    if isfile(summaryMat)

        loaded = ...
            load( ...
                summaryMat, ...
                "batchSummary");

        if isfield(loaded, "batchSummary")

            batchSummary = ...
                loaded.batchSummary;
        end
    end

    if ~isfield(batchSummary, "SchemaVersion")
        batchSummary.SchemaVersion = 2;
    end

    if ~isfield(batchSummary, "Process")
        batchSummary.Process = 4;
    end

    if ~isfield(batchSummary, "Stage")
        batchSummary.Stage = "static_optimization";
    end

    batchSummary.StrengthConfigEnabled = ...
        true;

    batchSummary.ConfigId = ...
        string(configRow.ConfigId);

    batchSummary.MusclePercent = ...
        double(configRow.MusclePercent);

    batchSummary.ActuatorPercent = ...
        double(configRow.ActuatorPercent);

    if ~isfield(batchSummary, "CompletedAt")
        batchSummary.CompletedAt = "";
    end

    if ~isfield(batchSummary, "DurationSeconds")
        batchSummary.DurationSeconds = NaN;
    end

    if ~isfield(batchSummary, "Configuration")
        batchSummary.Configuration = struct;
    end

    batchSummary.SummaryTable = ...
        summary;

    batchSummary.Succeeded = ...
        ~isempty(summary) && ...
        all(summary.Succeeded) && ...
        all(summary.OutputAuditPassed) && ...
        all(summary.ActivationSaturationAudited) && ...
        all(summary.ActivationSaturationPassed);

    batchSummary.ActivationSaturationReaudit = ...
        struct( ...
            "SchemaVersion", 2, ...
            "CompletedAt", string(datetime("now")), ...
            "SaturationThreshold", saturationThreshold);

    save( ...
        summaryMat, ...
        "batchSummary", ...
        "-v7.3");
end


function row = localEmptyReportRow()

    row = struct;

    row.ConfigId = "";
    row.MusclePercent = NaN;
    row.ActuatorPercent = NaN;
    row.SummaryFound = false;
    row.TrialsInSummary = 0;
    row.TrialsAudited = 0;
    row.TrialsSaturated = 0;
    row.TrialsAuditUnavailable = 0;
    row.TrialsDemoted = 0;
    row.TrialsSucceededAfterReaudit = 0;
    row.ConfigurationFeasible = false;
    row.SummaryUpdated = false;
    row.BackupCsv = "";
    row.BackupMat = "";
    row.Status = "";
    row.ErrorIdentifier = "";
    row.ErrorMessage = "";
end


function T = localEmptyReport()

    T = ...
        struct2table( ...
            repmat( ...
                localEmptyReportRow(), ...
                0, ...
                1));
end
