function replay = replayHybridStrengthSearch(outcomeSummary, varargin)
%REPLAYHYBRIDSTRENGTHSEARCH Replay hybrid selection from saved outcomes.
%
% replay = soopt.replayHybridStrengthSearch(outcomeSummary)
%
% Retrospectively evaluates the fixed-then-adaptive selection policy using
% already assessed configuration outcomes. Static Optimization is never
% executed and no files are written.
%
% The replay begins with InitialConfigIds as revealed evidence. At each
% step it asks the same lower-level fixed/adaptive planners for the next
% configuration, looks up that configuration in outcomeSummary, and then
% reveals the saved outcome. If the policy selects a configuration whose
% outcome was never observed, the replay stops explicitly rather than
% inventing a counterfactual result.
%
% REQUIRED OUTCOME SUMMARY VARIABLES
%
%   ConfigId
%   MusclePercent
%   ActuatorPercent
%   AssessmentComplete
%   IsFeasible
%
% NAME-VALUE OPTIONS
%
%   InitialConfigIds
%       Assessed configuration IDs available before iteration 1. Default
%       empty starts the replay without prior evidence.
%
%   FixedMuscleGrid / FixedActuatorGrid
%       Positive integer axes for the coarse fixed phase. Empty defaults
%       to the unique corresponding values in outcomeSummary.
%
%   BoundaryIncrementPercent
%       Positive integer adaptive lattice increment. Default 5.
%
%   BoundaryMuscleBounds / BoundaryActuatorBounds
%       Optional nondecreasing [min max] adaptive bounds.
%
%   MaxIterations
%       Positive integer or Inf. Default Inf.
%
%   ExpectedConfigIds
%       Optional expected selection sequence for deterministic historical
%       comparison.
%
% RETURN STRUCT
%
%   SchemaVersion
%   StopStatus
%   StopReason
%   KnownOutcomeCount
%   InitialEvidenceCount
%   ReplayedEvaluationCount
%   FixedEvaluationCount
%   AdaptiveEvaluationCount
%   AdaptivePhaseReached
%   TransitionIteration
%   FixedGridPointCount
%   SelectedConfigIds
%   ExpectedConfigIds
%   HasExpectedSequence
%   SequenceMatchesExpected
%   FirstMismatchIteration
%   UnusedKnownOutcomeCount
%   Iterations
%   FinalEvidence
%   Configuration
%
% The function is side-effect free.

    %% Parse inputs

    parser = ...
        inputParser;

    parser.FunctionName = ...
        "soopt.replayHybridStrengthSearch";

    addRequired(parser, ...
        "outcomeSummary", ...
        @istable);

    addParameter(parser, ...
        "InitialConfigIds", ...
        strings(0,1), ...
        @(x) ischar(x) || isstring(x) || iscellstr(x));

    addParameter(parser, ...
        "FixedMuscleGrid", ...
        [], ...
        @(x) isempty(x) || (isnumeric(x) && isvector(x)));

    addParameter(parser, ...
        "FixedActuatorGrid", ...
        [], ...
        @(x) isempty(x) || (isnumeric(x) && isvector(x)));

    addParameter(parser, ...
        "BoundaryIncrementPercent", ...
        5, ...
        @(x) ...
            isnumeric(x) && ...
            isscalar(x) && ...
            isfinite(x) && ...
            x >= 1 && ...
            x == fix(x));

    addParameter(parser, ...
        "BoundaryMuscleBounds", ...
        [], ...
        @(x) isempty(x) || (isnumeric(x) && isvector(x)));

    addParameter(parser, ...
        "BoundaryActuatorBounds", ...
        [], ...
        @(x) isempty(x) || (isnumeric(x) && isvector(x)));

    addParameter(parser, ...
        "MaxIterations", ...
        Inf, ...
        @(x) ...
            isnumeric(x) && ...
            isscalar(x) && ...
            (isinf(x) || ...
                (isfinite(x) && x >= 1 && x == fix(x))));

    addParameter(parser, ...
        "ExpectedConfigIds", ...
        strings(0,1), ...
        @(x) ischar(x) || isstring(x) || iscellstr(x));

    parse(parser, ...
        outcomeSummary, ...
        varargin{:});

    %% Validate and normalize known outcomes

    requiredVariables = [
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
        "AssessmentComplete"
        "IsFeasible"
    ];

    missingVariables = ...
        requiredVariables( ...
            ~ismember( ...
                requiredVariables, ...
                string(outcomeSummary.Properties.VariableNames)));

    assert(isempty(missingVariables), ...
        "StrengthSearchReplay:VariablesMissing", ...
        "outcomeSummary is missing required variables: %s", ...
        strjoin(missingVariables, ", "));

    configIds = ...
        string(outcomeSummary.ConfigId);

    musclePercent = ...
        double(outcomeSummary.MusclePercent);

    actuatorPercent = ...
        double(outcomeSummary.ActuatorPercent);

    assessmentComplete = ...
        logical(outcomeSummary.AssessmentComplete);

    assert(all(~ismissing(configIds) & strlength(configIds) > 0), ...
        "StrengthSearchReplay:InvalidConfigId", ...
        "ConfigId must contain nonempty values.");

    assert(numel(unique(configIds)) == height(outcomeSummary), ...
        "StrengthSearchReplay:DuplicateConfigId", ...
        "ConfigId values must be unique.");

    assert(all( ...
            isfinite(musclePercent) & ...
            musclePercent > 0 & ...
            musclePercent == fix(musclePercent)), ...
        "StrengthSearchReplay:InvalidMusclePercent", ...
        "MusclePercent must contain positive integers.");

    assert(all( ...
            isfinite(actuatorPercent) & ...
            actuatorPercent > 0 & ...
            actuatorPercent == fix(actuatorPercent)), ...
        "StrengthSearchReplay:InvalidActuatorPercent", ...
        "ActuatorPercent must contain positive integers.");

    coordinateKeys = ...
        compose( ...
            "%d|%d", ...
            musclePercent, ...
            actuatorPercent);

    assert(numel(unique(coordinateKeys)) == height(outcomeSummary), ...
        "StrengthSearchReplay:DuplicateCoordinates", ...
        "outcomeSummary contains duplicate strength coordinates.");

    knownOutcomes = ...
        outcomeSummary( ...
            assessmentComplete, ...
            :);

    initialConfigIds = ...
        localNormalizeIds( ...
            parser.Results.InitialConfigIds);

    expectedConfigIds = ...
        localNormalizeIds( ...
            parser.Results.ExpectedConfigIds);

    missingInitialIds = ...
        initialConfigIds( ...
            ~ismember( ...
                initialConfigIds, ...
                string(knownOutcomes.ConfigId)));

    assert(isempty(missingInitialIds), ...
        "StrengthSearchReplay:InitialOutcomeUnavailable", ...
        "InitialConfigIds do not have assessed outcomes: %s", ...
        strjoin(missingInitialIds, ", "));

    fixedMuscleGrid = ...
        localResolveGrid( ...
            parser.Results.FixedMuscleGrid, ...
            musclePercent, ...
            "FixedMuscleGrid");

    fixedActuatorGrid = ...
        localResolveGrid( ...
            parser.Results.FixedActuatorGrid, ...
            actuatorPercent, ...
            "FixedActuatorGrid");

    boundaryIncrementPercent = ...
        double(parser.Results.BoundaryIncrementPercent);

    boundaryMuscleBounds = ...
        localOptionalBounds( ...
            parser.Results.BoundaryMuscleBounds, ...
            "BoundaryMuscleBounds");

    boundaryActuatorBounds = ...
        localOptionalBounds( ...
            parser.Results.BoundaryActuatorBounds, ...
            "BoundaryActuatorBounds");

    maxIterations = ...
        double(parser.Results.MaxIterations);

    %% Replay observed outcomes

    revealedConfigIds = ...
        initialConfigIds;

    iterationRows = ...
        repmat( ...
            localEmptyIterationRow(), ...
            0, ...
            1);

    stopStatus = ...
        "";

    stopReason = ...
        "";

    while true

        evidence = ...
            knownOutcomes( ...
                ismember( ...
                    string(knownOutcomes.ConfigId), ...
                    revealedConfigIds), ...
                :);

        monotonicity = ...
            soopt.auditFeasibilityMonotonicity( ...
                evidence);

        if ~monotonicity.IsMonotonic

            stopStatus = ...
                "REPLAY_STOPPED_MONOTONICITY_VIOLATION";

            stopReason = ...
                sprintf( ...
                    "Revealed evidence contains %d monotonicity " + ...
                    "violation(s).", ...
                    monotonicity.ViolationCount);

            break;
        end

        hasBracket = ...
            soopt.hasExplicitStrengthBoundaryBracket( ...
                evidence);

        if hasBracket

            proposalArguments = { ...
                "IncrementPercent", ...
                boundaryIncrementPercent, ...
                "MaxProposals", ...
                1 ...
            };

            if ~isempty(boundaryMuscleBounds)

                proposalArguments(end+1:end+2) = { ...
                    "MuscleBounds", ...
                    boundaryMuscleBounds ...
                };
            end

            if ~isempty(boundaryActuatorBounds)

                proposalArguments(end+1:end+2) = { ...
                    "ActuatorBounds", ...
                    boundaryActuatorBounds ...
                };
            end

            proposals = ...
                soopt.proposeBoundaryRefinement( ...
                    evidence, ...
                    proposalArguments{:});

            if isempty(proposals)

                stopStatus = ...
                    "REPLAY_COMPLETE_BOUNDARY_RESOLVED";

                stopReason = ...
                    sprintf( ...
                        "No unresolved explicitly bracketed boundary " + ...
                        "point remains at %g%% resolution.", ...
                        boundaryIncrementPercent);

                break;
            end

            searchPhase = ...
                "adaptive";

        else

            fixedPlan = ...
                soopt.buildStrengthGridPlan( ...
                    evidence, ...
                    fixedMuscleGrid, ...
                    fixedActuatorGrid);

            proposals = ...
                soopt.proposeNextConfigurations( ...
                    fixedPlan, ...
                    "MaxProposals", ...
                    1);

            if isempty(proposals)

                stopStatus = ...
                    "REPLAY_STOPPED_HYBRID_BOUNDARY_UNBRACKETED";

                stopReason = ...
                    "The fixed-grid replay has no unresolved proposals, " + ...
                    "but the revealed evidence does not explicitly " + ...
                    "bracket an adaptive boundary.";

                break;
            end

            searchPhase = ...
                "fixed";
        end

        if numel(iterationRows) >= maxIterations

            stopStatus = ...
                "REPLAY_STOPPED_MAX_ITERATIONS";

            stopReason = ...
                sprintf( ...
                    "The replay reached MaxIterations=%g while " + ...
                    "additional proposals remained.", ...
                    maxIterations);

            break;
        end

        proposal = ...
            proposals(1,:);

        configId = ...
            string(proposal.ConfigId);

        outcomeMask = ...
            string(knownOutcomes.ConfigId) == ...
            configId;

        row = ...
            localEmptyIterationRow();

        row.Iteration = ...
            numel(iterationRows) + 1;

        row.SearchPhase = ...
            searchPhase;

        row.ConfigId = ...
            configId;

        row.MusclePercent = ...
            double(proposal.MusclePercent);

        row.ActuatorPercent = ...
            double(proposal.ActuatorPercent);

        row.EvidenceCountBefore = ...
            height(evidence);

        row.OutcomeAvailable = ...
            nnz(outcomeMask) == 1;

        if row.Iteration <= numel(expectedConfigIds)

            row.ExpectedConfigId = ...
                expectedConfigIds(row.Iteration);

            row.MatchesExpected = ...
                row.ConfigId == ...
                row.ExpectedConfigId;
        end

        if ~row.OutcomeAvailable

            row.Status = ...
                "outcome_unavailable";

            row.EvidenceCountAfter = ...
                height(evidence);

            iterationRows(end+1,1) = ...
                row; %#ok<AGROW>

            stopStatus = ...
                "REPLAY_STOPPED_OUTCOME_UNAVAILABLE";

            stopReason = ...
                "The hybrid policy selected " + ...
                configId + ...
                ", but no assessed historical outcome is available.";

            break;
        end

        outcome = ...
            knownOutcomes(outcomeMask,:);

        row.IsFeasible = ...
            logical(outcome.IsFeasible);

        if ismember( ...
                "FeasibilityStatus", ...
                string(outcome.Properties.VariableNames))

            row.FeasibilityStatus = ...
                string(outcome.FeasibilityStatus);

        elseif row.IsFeasible

            row.FeasibilityStatus = ...
                "FEASIBLE";

        else

            row.FeasibilityStatus = ...
                "INFEASIBLE";
        end

        revealedConfigIds(end+1,1) = ...
            configId;

        row.EvidenceCountAfter = ...
            height(evidence) + 1;

        row.Status = ...
            "replayed";

        iterationRows(end+1,1) = ...
            row; %#ok<AGROW>
    end

    %% Assemble report

    iterations = ...
        localRowsToTable( ...
            iterationRows);

    selectedConfigIds = ...
        string(iterations.ConfigId);

    replayedMask = ...
        iterations.Status == ...
        "replayed";

    fixedMask = ...
        replayedMask & ...
        iterations.SearchPhase == ...
        "fixed";

    adaptiveMask = ...
        replayedMask & ...
        iterations.SearchPhase == ...
        "adaptive";

    adaptiveSelectionIndices = ...
        find( ...
            iterations.SearchPhase == ...
            "adaptive");

    transitionIteration = ...
        NaN;

    if ~isempty(adaptiveSelectionIndices)

        transitionIteration = ...
            adaptiveSelectionIndices(1);
    end

    [sequenceMatchesExpected, firstMismatchIteration] = ...
        localCompareSequences( ...
            selectedConfigIds, ...
            expectedConfigIds);

    finalEvidence = ...
        knownOutcomes( ...
            ismember( ...
                string(knownOutcomes.ConfigId), ...
                revealedConfigIds), ...
            :);

    replay = ...
        struct;

    replay.SchemaVersion = ...
        1;

    replay.StopStatus = ...
        stopStatus;

    replay.StopReason = ...
        stopReason;

    replay.KnownOutcomeCount = ...
        height(knownOutcomes);

    replay.InitialEvidenceCount = ...
        numel(initialConfigIds);

    replay.ReplayedEvaluationCount = ...
        nnz(replayedMask);

    replay.FixedEvaluationCount = ...
        nnz(fixedMask);

    replay.AdaptiveEvaluationCount = ...
        nnz(adaptiveMask);

    replay.AdaptivePhaseReached = ...
        any( ...
            iterations.SearchPhase == ...
            "adaptive") || ...
        stopStatus == ...
            "REPLAY_COMPLETE_BOUNDARY_RESOLVED";

    replay.TransitionIteration = ...
        transitionIteration;

    replay.FixedGridPointCount = ...
        numel(fixedMuscleGrid) * ...
        numel(fixedActuatorGrid);

    replay.SelectedConfigIds = ...
        selectedConfigIds;

    replay.ExpectedConfigIds = ...
        expectedConfigIds;

    replay.HasExpectedSequence = ...
        ~isempty(expectedConfigIds);

    replay.SequenceMatchesExpected = ...
        sequenceMatchesExpected;

    replay.FirstMismatchIteration = ...
        firstMismatchIteration;

    replay.UnusedKnownOutcomeCount = ...
        height(knownOutcomes) - ...
        height(finalEvidence);

    replay.Iterations = ...
        iterations;

    replay.FinalEvidence = ...
        finalEvidence;

    replay.Configuration = ...
        struct( ...
            "FixedMuscleGrid", fixedMuscleGrid, ...
            "FixedActuatorGrid", fixedActuatorGrid, ...
            "BoundaryIncrementPercent", boundaryIncrementPercent, ...
            "BoundaryMuscleBounds", boundaryMuscleBounds, ...
            "BoundaryActuatorBounds", boundaryActuatorBounds, ...
            "MaxIterations", maxIterations);
end


function ids = localNormalizeIds(value)

    ids = ...
        string(value(:));

    ids = ...
        strip(ids);

    ids = ...
        ids( ...
            ~ismissing(ids) & ...
            strlength(ids) > 0);

    assert(numel(unique(ids)) == numel(ids), ...
        "StrengthSearchReplay:DuplicateRequestedConfigId", ...
        "Requested configuration IDs must be unique.");
end


function grid = localResolveGrid(requested, fallback, fieldName)

    if isempty(requested)

        grid = ...
            unique(double(fallback(:))).';

    else

        grid = ...
            unique(double(requested(:))).';
    end

    assert(~isempty(grid) && ...
            all(isfinite(grid)) && ...
            all(grid > 0) && ...
            all(grid == fix(grid)), ...
        "StrengthSearchReplay:InvalidFixedGrid", ...
        "%s must resolve to positive integer values.", ...
        fieldName);
end


function bounds = localOptionalBounds(value, fieldName)

    if isempty(value)

        bounds = ...
            zeros(1,0);

        return;
    end

    bounds = ...
        double(value(:)).';

    assert(numel(bounds) == 2 && ...
            all(isfinite(bounds)) && ...
            all(bounds > 0) && ...
            bounds(1) <= bounds(2), ...
        "StrengthSearchReplay:InvalidBounds", ...
        "%s must be empty or a positive nondecreasing [min max] vector.", ...
        fieldName);
end


function [matches, firstMismatch] = ...
        localCompareSequences(actual, expected)

    if isempty(expected)

        matches = ...
            true;

        firstMismatch = ...
            NaN;

        return;
    end

    nShared = ...
        min( ...
            numel(actual), ...
            numel(expected));

    mismatch = ...
        find( ...
            actual(1:nShared) ~= ...
            expected(1:nShared), ...
            1, ...
            "first");

    if isempty(mismatch) && ...
            numel(actual) ~= numel(expected)

        mismatch = ...
            nShared + 1;
    end

    matches = ...
        isempty(mismatch);

    if matches

        firstMismatch = ...
            NaN;

    else

        firstMismatch = ...
            mismatch;
    end
end


function row = localEmptyIterationRow()

    row = ...
        struct;

    row.Iteration = NaN;
    row.SearchPhase = "";
    row.ConfigId = "";
    row.MusclePercent = NaN;
    row.ActuatorPercent = NaN;
    row.EvidenceCountBefore = 0;
    row.OutcomeAvailable = false;
    row.IsFeasible = false;
    row.FeasibilityStatus = "";
    row.EvidenceCountAfter = 0;
    row.ExpectedConfigId = "";
    row.MatchesExpected = false;
    row.Status = "";
end


function T = localRowsToTable(rows)

    if isempty(rows)

        T = ...
            struct2table( ...
                localEmptyIterationRow());

        T = ...
            T(zeros(0,1),:);

        return;
    end

    T = ...
        struct2table(rows);
end
