function selection = resolveProposedStrengthConfig(result, varargin)
%RESOLVEPROPOSEDSTRENGTHCONFIG Resolve a ranked proposal to its exact JSON.
%
% selection = soopt.resolveProposedStrengthConfig(result)
%
% Resolves the rank-1 proposal returned by soopt.analyzeStrengthGrid to the
% exact candidate JSON row stored in result.ConfigPool.Configurations.
%
% The function does NOT reconstruct filenames from muscle/actuator values.
% It requires an exact ConfigId mapping to the discovered candidate pool and
% cross-checks the proposal coordinates against that pool row.
%
% NAME-VALUE OPTIONS
%
%   ProposalRank
%       Positive integer proposal rank to resolve. Default 1.
%
% RETURN STRUCT
%
%   SchemaVersion
%   PriorityRank
%   ConfigId
%   MusclePercent
%   ActuatorPercent
%   ExistingIncomplete
%   FileName
%   ConfigFile
%   ConfigDirectory
%   ProposalRowIndex
%   PoolRowIndex
%   Proposal
%   PoolConfiguration
%
% The referenced JSON must still exist at resolution time.
%
% This function is intentionally SIDE-EFFECT FREE.

    %% Parse inputs

    parser = ...
        inputParser;

    parser.FunctionName = ...
        "soopt.resolveProposedStrengthConfig";

    addRequired(parser, ...
        "result", ...
        @(x) isstruct(x) && isscalar(x));

    addParameter(parser, ...
        "ProposalRank", ...
        1, ...
        @(x) ...
            isnumeric(x) && ...
            isscalar(x) && ...
            isfinite(x) && ...
            x >= 1 && ...
            x == fix(x));

    parse(parser, ...
        result, ...
        varargin{:});

    requestedRank = ...
        double(parser.Results.ProposalRank);

    %% Validate top-level analysis contract

    requiredResultFields = [
        "ConfigPool"
        "Proposals"
        "PlanningAvailable"
        "PlanningStatus"
        "PlanningReason"
    ];

    missingResultFields = ...
        requiredResultFields( ...
            ~isfield( ...
                result, ...
                cellstr(requiredResultFields)));

    assert(isempty(missingResultFields), ...
        "StrengthProposalResolve:ResultFieldsMissing", ...
        "Analysis result is missing required fields: %s", ...
        strjoin(missingResultFields, ", "));

    assert(isscalar(result.PlanningAvailable) && ...
            (islogical(result.PlanningAvailable) || ...
                isnumeric(result.PlanningAvailable)), ...
        "StrengthProposalResolve:InvalidPlanningAvailable", ...
        "result.PlanningAvailable must be a logical scalar.");

    planningAvailable = ...
        logical(result.PlanningAvailable);

    if ~planningAvailable

        error( ...
            "StrengthProposalResolve:PlanningUnavailable", ...
            "Strength-grid planning is unavailable (%s): %s", ...
            string(result.PlanningStatus), ...
            string(result.PlanningReason));
    end

    assert(istable(result.Proposals), ...
        "StrengthProposalResolve:InvalidProposals", ...
        "result.Proposals must be a table.");

    assert(isstruct(result.ConfigPool) && ...
            isscalar(result.ConfigPool) && ...
            isfield(result.ConfigPool, "Configurations"), ...
        "StrengthProposalResolve:InvalidConfigPool", ...
        "result.ConfigPool.Configurations is required.");

    assert(istable(result.ConfigPool.Configurations), ...
        "StrengthProposalResolve:InvalidConfigPool", ...
        "result.ConfigPool.Configurations must be a table.");

    proposals = ...
        result.Proposals;

    configurations = ...
        result.ConfigPool.Configurations;

    %% Validate proposal table

    proposalRequiredVariables = [
        "PriorityRank"
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
    ];

    missingProposalVariables = ...
        proposalRequiredVariables( ...
            ~ismember( ...
                proposalRequiredVariables, ...
                string(proposals.Properties.VariableNames)));

    assert(isempty(missingProposalVariables), ...
        "StrengthProposalResolve:ProposalVariablesMissing", ...
        "result.Proposals is missing required variables: %s", ...
        strjoin(missingProposalVariables, ", "));

    if isempty(proposals)

        error( ...
            "StrengthProposalResolve:NoProposals", ...
            "No strength-grid proposals are available to resolve.");
    end

    priorityRank = ...
        double(proposals.PriorityRank);

    assert(all(isfinite(priorityRank) & ...
            priorityRank >= 1 & ...
            priorityRank == fix(priorityRank)), ...
        "StrengthProposalResolve:InvalidPriorityRank", ...
        "Proposal PriorityRank values must be positive integers.");

    assert(numel(unique(priorityRank)) == ...
            height(proposals), ...
        "StrengthProposalResolve:DuplicatePriorityRank", ...
        "Proposal PriorityRank values must be unique.");

    proposalMask = ...
        priorityRank == requestedRank;

    if ~any(proposalMask)

        error( ...
            "StrengthProposalResolve:ProposalRankNotFound", ...
            "Proposal rank %d is not available.", ...
            requestedRank);
    end

    assert(nnz(proposalMask) == 1, ...
        "StrengthProposalResolve:DuplicatePriorityRank", ...
        "Proposal rank %d occurs more than once.", ...
        requestedRank);

    proposalRowIndex = ...
        find(proposalMask, 1);

    proposal = ...
        proposals( ...
            proposalRowIndex, ...
            :);

    proposalConfigId = ...
        string(proposal.ConfigId);

    proposalMusclePercent = ...
        double(proposal.MusclePercent);

    proposalActuatorPercent = ...
        double(proposal.ActuatorPercent);

    assert(isscalar(proposalConfigId) && ...
            ~ismissing(proposalConfigId) && ...
            strlength(proposalConfigId) > 0, ...
        "StrengthProposalResolve:InvalidProposalConfigId", ...
        "The selected proposal has an invalid ConfigId.");

    assert(isscalar(proposalMusclePercent) && ...
            isfinite(proposalMusclePercent) && ...
            proposalMusclePercent > 0, ...
        "StrengthProposalResolve:InvalidProposalCoordinate", ...
        "The selected proposal has an invalid MusclePercent.");

    assert(isscalar(proposalActuatorPercent) && ...
            isfinite(proposalActuatorPercent) && ...
            proposalActuatorPercent > 0, ...
        "StrengthProposalResolve:InvalidProposalCoordinate", ...
        "The selected proposal has an invalid ActuatorPercent.");

    %% Validate candidate-pool table

    poolRequiredVariables = [
        "ConfigId"
        "MusclePercent"
        "ActuatorPercent"
        "FileName"
        "ConfigFile"
    ];

    missingPoolVariables = ...
        poolRequiredVariables( ...
            ~ismember( ...
                poolRequiredVariables, ...
                string(configurations.Properties.VariableNames)));

    assert(isempty(missingPoolVariables), ...
        "StrengthProposalResolve:PoolVariablesMissing", ...
        "result.ConfigPool.Configurations is missing required variables: %s", ...
        strjoin(missingPoolVariables, ", "));

    poolConfigId = ...
        string(configurations.ConfigId);

    matchMask = ...
        poolConfigId == proposalConfigId;

    if ~any(matchMask)

        error( ...
            "StrengthProposalResolve:ConfigNotFound", ...
            "Proposed ConfigId %s was not found in the discovered " + ...
            "candidate configuration pool.", ...
            proposalConfigId);
    end

    if nnz(matchMask) > 1

        error( ...
            "StrengthProposalResolve:DuplicateConfigId", ...
            "Proposed ConfigId %s maps to %d candidate pool rows.", ...
            proposalConfigId, ...
            nnz(matchMask));
    end

    poolRowIndex = ...
        find(matchMask, 1);

    poolRow = ...
        configurations( ...
            poolRowIndex, ...
            :);

    poolMusclePercent = ...
        double(poolRow.MusclePercent);

    poolActuatorPercent = ...
        double(poolRow.ActuatorPercent);

    if poolMusclePercent ~= proposalMusclePercent || ...
            poolActuatorPercent ~= proposalActuatorPercent

        error( ...
            "StrengthProposalResolve:CoordinateMismatch", ...
            "Proposal %s has coordinates (%g, %g), but the matching " + ...
            "candidate pool row has coordinates (%g, %g).", ...
            proposalConfigId, ...
            proposalMusclePercent, ...
            proposalActuatorPercent, ...
            poolMusclePercent, ...
            poolActuatorPercent);
    end

    %% Validate exact JSON identity and current filesystem state

    fileName = ...
        string(poolRow.FileName);

    configFile = ...
        string(poolRow.ConfigFile);

    assert(isscalar(fileName) && ...
            ~ismissing(fileName) && ...
            strlength(fileName) > 0, ...
        "StrengthProposalResolve:InvalidFileName", ...
        "Candidate pool row for %s has an invalid FileName.", ...
        proposalConfigId);

    assert(isscalar(configFile) && ...
            ~ismissing(configFile) && ...
            strlength(configFile) > 0, ...
        "StrengthProposalResolve:InvalidConfigFile", ...
        "Candidate pool row for %s has an invalid ConfigFile.", ...
        proposalConfigId);

    [configDirectory, configStem, configExtension] = ...
        fileparts(configFile);

    resolvedFileName = ...
        string(configStem) + ...
        string(configExtension);

    assert(resolvedFileName == fileName, ...
        "StrengthProposalResolve:FilePathMismatch", ...
        "Candidate pool FileName and ConfigFile disagree for %s.", ...
        proposalConfigId);

    parsedIdentity = ...
        pipeline.parseStrengthConfigName( ...
            fileName);

    assert(parsedIdentity.ConfigId == proposalConfigId && ...
            parsedIdentity.MusclePercent == proposalMusclePercent && ...
            parsedIdentity.ActuatorPercent == proposalActuatorPercent, ...
        "StrengthProposalResolve:CanonicalIdentityMismatch", ...
        "Candidate JSON filename identity does not agree with the " + ...
        "selected proposal %s.", ...
        proposalConfigId);

    assert(isfile(configFile), ...
        "StrengthProposalResolve:ConfigFileNotFound", ...
        "The proposed configuration JSON no longer exists:\n%s", ...
        configFile);

    %% Return exact selection

    existingIncomplete = ...
        false;

    if ismember( ...
            "ExistingIncomplete", ...
            string(proposal.Properties.VariableNames))

        existingIncomplete = ...
            logical(proposal.ExistingIncomplete);
    end

    selection = struct;

    selection.SchemaVersion = ...
        1;

    selection.PriorityRank = ...
        requestedRank;

    selection.ConfigId = ...
        proposalConfigId;

    selection.MusclePercent = ...
        proposalMusclePercent;

    selection.ActuatorPercent = ...
        proposalActuatorPercent;

    selection.ExistingIncomplete = ...
        existingIncomplete;

    selection.FileName = ...
        fileName;

    selection.ConfigFile = ...
        configFile;

    selection.ConfigDirectory = ...
        string(configDirectory);

    selection.ProposalRowIndex = ...
        proposalRowIndex;

    selection.PoolRowIndex = ...
        poolRowIndex;

    selection.Proposal = ...
        proposal;

    selection.PoolConfiguration = ...
        poolRow;
end
