function controllerCfg = resolveStrengthGridSearchControllerConfig(projectCfg)
%RESOLVESTRENGTHGRIDSEARCHCONTROLLERCONFIG Resolve SO search-controller config.
%
% controllerCfg = soopt.resolveStrengthGridSearchControllerConfig(projectCfg)
%
% Resolves and validates:
%
%   projectCfg.optimization.staticOptimization
%
% into the flat option vocabulary currently consumed by
% soopt.runStrengthGridSearch.
%
% This function is intentionally SIDE-EFFECT FREE:
%
%   - it does not create directories;
%   - it does not require configured directories/files to exist;
%   - it does not run or analyze any Static Optimization configurations;
%   - it does not modify projectCfg.
%
% Returned fields:
%
%   SchemaVersion
%   ConfigDirectory
%   SearchMode
%   BoundaryIncrementPercent
%   BoundaryMuscleBounds
%   BoundaryActuatorBounds
%   AdaptiveConfigDirectory
%   AdaptiveTemplateConfigFile
%   MaxIterations
%   DryRun
%   OverwriteIncompleteConfiguration
%   WriteAnalysis
%   AnalysisOutputDirectory
%   ExportFigure
%   FigureResolution
%   WriteSearchHistory
%   PrintProgress
%
% Empty path values are preserved intentionally so downstream controller
% helpers can continue using their existing canonical path-resolution
% behavior.

    %% Validate top-level project structure

    assert(isstruct(projectCfg) && isscalar(projectCfg), ...
        "StrengthGridSearchConfig:InvalidProjectConfig", ...
        "projectCfg must be a scalar struct.");

    assert(isfield(projectCfg, "optimization"), ...
        "StrengthGridSearchConfig:OptimizationMissing", ...
        "projectCfg.optimization is required.");

    optimizationCfg = ...
        projectCfg.optimization;

    assert(isstruct(optimizationCfg) && isscalar(optimizationCfg), ...
        "StrengthGridSearchConfig:InvalidOptimizationConfig", ...
        "projectCfg.optimization must be a scalar struct.");

    assert(isfield(optimizationCfg, "staticOptimization"), ...
        "StrengthGridSearchConfig:StaticOptimizationMissing", ...
        "projectCfg.optimization.staticOptimization is required.");

    searchCfg = ...
        optimizationCfg.staticOptimization;

    assert(isstruct(searchCfg) && isscalar(searchCfg), ...
        "StrengthGridSearchConfig:InvalidStaticOptimizationConfig", ...
        "projectCfg.optimization.staticOptimization must be a scalar struct.");

    requiredSearchFields = [
        "searchMode"
        "maxIterations"
        "dryRun"
        "overwriteIncompleteConfiguration"
        "fixedGrid"
        "adaptiveBoundary"
        "output"
        "printProgress"
    ];

    localRequireFields( ...
        searchCfg, ...
        requiredSearchFields, ...
        "projectCfg.optimization.staticOptimization", ...
        "StrengthGridSearchConfig:SearchFieldsMissing");

    fixedGridCfg = ...
        localRequireScalarStruct( ...
            searchCfg.fixedGrid, ...
            "projectCfg.optimization.staticOptimization.fixedGrid", ...
            "StrengthGridSearchConfig:InvalidFixedGridConfig");

    adaptiveCfg = ...
        localRequireScalarStruct( ...
            searchCfg.adaptiveBoundary, ...
            "projectCfg.optimization.staticOptimization.adaptiveBoundary", ...
            "StrengthGridSearchConfig:InvalidAdaptiveBoundaryConfig");

    outputCfg = ...
        localRequireScalarStruct( ...
            searchCfg.output, ...
            "projectCfg.optimization.staticOptimization.output", ...
            "StrengthGridSearchConfig:InvalidOutputConfig");

    localRequireFields( ...
        fixedGridCfg, ...
        "configDirectory", ...
        "projectCfg.optimization.staticOptimization.fixedGrid", ...
        "StrengthGridSearchConfig:FixedGridFieldsMissing");

    requiredAdaptiveFields = [
        "incrementPercent"
        "muscleBounds"
        "actuatorBounds"
        "configDirectory"
        "templateConfigFile"
    ];

    localRequireFields( ...
        adaptiveCfg, ...
        requiredAdaptiveFields, ...
        "projectCfg.optimization.staticOptimization.adaptiveBoundary", ...
        "StrengthGridSearchConfig:AdaptiveBoundaryFieldsMissing");

    requiredOutputFields = [
        "writeAnalysis"
        "analysisDirectory"
        "exportFigure"
        "figureResolution"
        "writeSearchHistory"
    ];

    localRequireFields( ...
        outputCfg, ...
        requiredOutputFields, ...
        "projectCfg.optimization.staticOptimization.output", ...
        "StrengthGridSearchConfig:OutputFieldsMissing");

    %% Resolve controller mode

    searchMode = ...
        localScalarString( ...
            searchCfg.searchMode, ...
            "projectCfg.optimization.staticOptimization.searchMode", ...
            false);

    searchMode = ...
        lower(searchMode);

    assert(ismember( ...
            searchMode, ...
            ["fixed_grid", "adaptive_boundary"]), ...
        "StrengthGridSearchConfig:InvalidSearchMode", ...
        "projectCfg.optimization.staticOptimization.searchMode must be " + ...
        "'fixed_grid' or 'adaptive_boundary'.");

    %% Resolve flat controller settings

    controllerCfg = ...
        struct;

    controllerCfg.SchemaVersion = ...
        1;

    controllerCfg.ConfigDirectory = ...
        localScalarString( ...
            fixedGridCfg.configDirectory, ...
            "projectCfg.optimization.staticOptimization.fixedGrid.configDirectory", ...
            true);

    controllerCfg.SearchMode = ...
        searchMode;

    controllerCfg.BoundaryIncrementPercent = ...
        localPositiveInteger( ...
            adaptiveCfg.incrementPercent, ...
            "projectCfg.optimization.staticOptimization." + ...
            "adaptiveBoundary.incrementPercent");

    controllerCfg.BoundaryMuscleBounds = ...
        localOptionalBounds( ...
            adaptiveCfg.muscleBounds, ...
            "projectCfg.optimization.staticOptimization." + ...
            "adaptiveBoundary.muscleBounds");

    controllerCfg.BoundaryActuatorBounds = ...
        localOptionalBounds( ...
            adaptiveCfg.actuatorBounds, ...
            "projectCfg.optimization.staticOptimization." + ...
            "adaptiveBoundary.actuatorBounds");

    controllerCfg.AdaptiveConfigDirectory = ...
        localScalarString( ...
            adaptiveCfg.configDirectory, ...
            "projectCfg.optimization.staticOptimization." + ...
            "adaptiveBoundary.configDirectory", ...
            true);

    controllerCfg.AdaptiveTemplateConfigFile = ...
        localScalarString( ...
            adaptiveCfg.templateConfigFile, ...
            "projectCfg.optimization.staticOptimization." + ...
            "adaptiveBoundary.templateConfigFile", ...
            true);

    controllerCfg.MaxIterations = ...
        localPositiveInteger( ...
            searchCfg.maxIterations, ...
            "projectCfg.optimization.staticOptimization.maxIterations");

    controllerCfg.DryRun = ...
        localLogicalScalar( ...
            searchCfg.dryRun, ...
            "projectCfg.optimization.staticOptimization.dryRun");

    controllerCfg.OverwriteIncompleteConfiguration = ...
        localLogicalScalar( ...
            searchCfg.overwriteIncompleteConfiguration, ...
            "projectCfg.optimization.staticOptimization." + ...
            "overwriteIncompleteConfiguration");

    controllerCfg.WriteAnalysis = ...
        localLogicalScalar( ...
            outputCfg.writeAnalysis, ...
            "projectCfg.optimization.staticOptimization.output.writeAnalysis");

    controllerCfg.AnalysisOutputDirectory = ...
        localScalarString( ...
            outputCfg.analysisDirectory, ...
            "projectCfg.optimization.staticOptimization.output.analysisDirectory", ...
            true);

    controllerCfg.ExportFigure = ...
        localLogicalScalar( ...
            outputCfg.exportFigure, ...
            "projectCfg.optimization.staticOptimization.output.exportFigure");

    controllerCfg.FigureResolution = ...
        localPositiveFiniteScalar( ...
            outputCfg.figureResolution, ...
            "projectCfg.optimization.staticOptimization.output.figureResolution");

    controllerCfg.WriteSearchHistory = ...
        localLogicalScalar( ...
            outputCfg.writeSearchHistory, ...
            "projectCfg.optimization.staticOptimization.output.writeSearchHistory");

    controllerCfg.PrintProgress = ...
        localLogicalScalar( ...
            searchCfg.printProgress, ...
            "projectCfg.optimization.staticOptimization.printProgress");
end


function localRequireFields(value, requiredFields, location, errorId)

    requiredFields = ...
        string(requiredFields(:));

    missingFields = ...
        requiredFields( ...
            ~isfield( ...
                value, ...
                cellstr(requiredFields)));

    assert(isempty(missingFields), ...
        errorId, ...
        "%s is missing required field(s): %s", ...
        location, ...
        strjoin(missingFields, ", "));
end


function value = localRequireScalarStruct(value, location, errorId)

    assert(isstruct(value) && isscalar(value), ...
        errorId, ...
        "%s must be a scalar struct.", ...
        location);
end


function value = localScalarString(value, location, allowEmpty)

    validChar = ...
        ischar(value) && ...
        (isrow(value) || isempty(value));

    validString = ...
        isstring(value) && ...
        isscalar(value) && ...
        ~ismissing(value);

    assert(validChar || validString, ...
        "StrengthGridSearchConfig:InvalidStringSetting", ...
        "%s must be a scalar string or character vector.", ...
        location);

    value = ...
        strtrim(string(value));

    assert(allowEmpty || strlength(value) > 0, ...
        "StrengthGridSearchConfig:EmptyStringSetting", ...
        "%s must be nonempty.", ...
        location);
end


function value = localLogicalScalar(value, location)

    assert(islogical(value) && isscalar(value), ...
        "StrengthGridSearchConfig:InvalidLogicalSetting", ...
        "%s must be a logical scalar.", ...
        location);

    value = ...
        logical(value);
end


function value = localPositiveInteger(value, location)

    assert(isnumeric(value) && ...
            isscalar(value) && ...
            isfinite(value) && ...
            value >= 1 && ...
            value == fix(value), ...
        "StrengthGridSearchConfig:InvalidPositiveInteger", ...
        "%s must be a positive integer scalar.", ...
        location);

    value = ...
        double(value);
end


function value = localPositiveFiniteScalar(value, location)

    assert(isnumeric(value) && ...
            isscalar(value) && ...
            isfinite(value) && ...
            value > 0, ...
        "StrengthGridSearchConfig:InvalidPositiveScalar", ...
        "%s must be a positive finite numeric scalar.", ...
        location);

    value = ...
        double(value);
end


function value = localOptionalBounds(value, location)

    if isempty(value)

        value = ...
            zeros(1,0);

        return;
    end

    assert(isnumeric(value) && ...
            isvector(value) && ...
            numel(value) == 2 && ...
            all(isfinite(value)), ...
        "StrengthGridSearchConfig:InvalidBounds", ...
        "%s must be empty or a finite two-element numeric vector.", ...
        location);

    value = ...
        double(value(:).');

    assert(value(1) <= value(2), ...
        "StrengthGridSearchConfig:ReversedBounds", ...
        "%s must be ordered as [minimum maximum].", ...
        location);
end
