function search = runStrengthGridSearch(projectCfg, varargin)
%RUNSTRENGTHGRIDSEARCH Execute the closed-loop SO strength-grid search.
%
% search = soopt.runStrengthGridSearch(projectCfg)
%
% This is the top-level automated controller for the Static Optimization
% muscle/reserve capacity search. Each iteration:
%
%   1. analyzes the currently observed grid;
%   2. resolves the rank-1 proposal to its exact JSON;
%   3. applies that JSON to an in-memory projectCfg;
%   4. runs Process 3 across the complete configured study matrix;
%   5. requires Process 3 to succeed for every trial;
%   6. runs Process 4 across the complete configured study matrix;
%   7. treats Process-4 trial failures/saturation as scientific evidence;
%   8. reanalyzes the grid;
%   9. optionally persists the current analysis and search history;
%  10. repeats until an explicit termination criterion is reached.
%
% RESTARTABILITY
%
% Search state is derived from the existing configuration output folders and
% Process-4 summaries on every invocation. A prior controller checkpoint is
% not required to resume a search.
%
% If an existing INCOMPLETE configuration is proposed, the controller may
% rerun that complete configuration with overwrite enabled. This policy is
% controlled by OverwriteIncompleteConfiguration.
%
% PROCESS FAILURE POLICY
%
% Process 3:
%   Any failed trial stops the controller. Static Optimization should not be
%   attempted for a configuration whose preparation stage is incomplete.
%
% Process 4:
%   Individual failed/saturated trials do NOT stop the controller. They are
%   retained in the canonical Process-4 summary and become infeasibility
%   evidence during the next grid analysis. A controller-level Process-4
%   exception does stop the search.
%
% NAME-VALUE OPTIONS
%
%   ConfigDirectory
%       Explicit candidate JSON directory. Default "" delegates resolution
%       to soopt.analyzeStrengthGrid / discoverStrengthConfigPool.
%
%   MaxIterations
%       Maximum configurations executed in this invocation. Default 20.
%
%   DryRun
%       Default false. When true, analyze and resolve the current rank-1
%       proposal but do not execute Process 3/4 and do not write files.
%
%   OverwriteIncompleteConfiguration
%       Default true. Allows a proposed ExistingIncomplete configuration to
%       be rerun from Process 3 with overwrite enabled.
%
%   WriteAnalysis
%       Default true. Persist the refreshed analysis after each completed
%       Process-4 batch and at terminal no-run states.
%
%   AnalysisOutputDirectory
%       Optional directory passed to writeStrengthGridAnalysis. Default ""
%       uses its canonical grid_search_analysis directory.
%
%   ExportFigure
%       Default true. Export the feasibility map when analysis is written.
%
%   FigureResolution
%       Positive finite DPI. Default 200.
%
%   WriteSearchHistory
%       Default true. Persist controller iteration history to:
%           strength_grid_search_history.csv
%           strength_grid_search.mat
%       in the analysis output directory.
%
%   PrintProgress
%       Default true.
%
% STOP STATUSES
%
%   SEARCH_COMPLETE_NO_PROPOSALS
%   SEARCH_STOPPED_PLANNING_UNAVAILABLE
%   SEARCH_STOPPED_INCOMPLETE_OVERWRITE_DISABLED
%   SEARCH_STOPPED_PROCESS3_FAILURE
%   SEARCH_STOPPED_PROCESS3_ERROR
%   SEARCH_STOPPED_PROCESS4_ERROR
%   SEARCH_STOPPED_ANALYSIS_WRITE_ERROR
%   SEARCH_STOPPED_MAX_ITERATIONS
%   SEARCH_DRY_RUN_READY
%
% RETURN STRUCT
%
%   SchemaVersion
%   StartedAt
%   CompletedAt
%   DurationSeconds
%   StopStatus
%   StopReason
%   ExecutedIterations
%   Iterations
%   FinalAnalysis
%   FinalAnalysisOutputs
%   SearchHistoryCsv
%   SearchHistoryMat
%   Configuration
%
% The caller's projectCfg is never modified.

    %% Parse options

    parser = ...
        inputParser;

    parser.FunctionName = ...
        "soopt.runStrengthGridSearch";

    addRequired(parser, ...
        "projectCfg", ...
        @(x) isstruct(x) && isscalar(x));

    addParameter(parser, ...
        "ConfigDirectory", ...
        "", ...
        @(x) ...
            (ischar(x) && (isrow(x) || isempty(x))) || ...
            (isstring(x) && isscalar(x) && ~ismissing(x)));

    addParameter(parser, ...
        "MaxIterations", ...
        20, ...
        @(x) ...
            isnumeric(x) && ...
            isscalar(x) && ...
            isfinite(x) && ...
            x >= 1 && ...
            x == fix(x));

    addParameter(parser, ...
        "DryRun", ...
        false, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "OverwriteIncompleteConfiguration", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "WriteAnalysis", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "AnalysisOutputDirectory", ...
        "", ...
        @(x) ...
            (ischar(x) && (isrow(x) || isempty(x))) || ...
            (isstring(x) && isscalar(x) && ~ismissing(x)));

    addParameter(parser, ...
        "ExportFigure", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "FigureResolution", ...
        200, ...
        @(x) ...
            isnumeric(x) && ...
            isscalar(x) && ...
            isfinite(x) && ...
            x > 0);

    addParameter(parser, ...
        "WriteSearchHistory", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "PrintProgress", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    parse(parser, ...
        projectCfg, ...
        varargin{:});

    options = struct;

    options.ConfigDirectory = ...
        string(parser.Results.ConfigDirectory);

    options.MaxIterations = ...
        double(parser.Results.MaxIterations);

    options.DryRun = ...
        logical(parser.Results.DryRun);

    options.OverwriteIncompleteConfiguration = ...
        logical(parser.Results.OverwriteIncompleteConfiguration);

    options.WriteAnalysis = ...
        logical(parser.Results.WriteAnalysis);

    options.AnalysisOutputDirectory = ...
        string(parser.Results.AnalysisOutputDirectory);

    options.ExportFigure = ...
        logical(parser.Results.ExportFigure);

    options.FigureResolution = ...
        double(parser.Results.FigureResolution);

    options.WriteSearchHistory = ...
        logical(parser.Results.WriteSearchHistory);

    options.PrintProgress = ...
        logical(parser.Results.PrintProgress);

    %% Validate controller-level project contract

    assert(isfield(projectCfg, "outputRoot"), ...
        "StrengthGridSearch:OutputRootMissing", ...
        "projectCfg.outputRoot is required.");

    assert(isfield(projectCfg, "forceCapacity") && ...
            isstruct(projectCfg.forceCapacity) && ...
            isscalar(projectCfg.forceCapacity), ...
        "StrengthGridSearch:ForceCapacityMissing", ...
        "projectCfg.forceCapacity is required.");

    assert(isfield(projectCfg.forceCapacity, "configFile"), ...
        "StrengthGridSearch:ConfigFileFieldMissing", ...
        "projectCfg.forceCapacity.configFile is required.");

    assert(isfield(projectCfg.forceCapacity, "applyMode"), ...
        "StrengthGridSearch:ApplyModeMissing", ...
        "projectCfg.forceCapacity.applyMode is required.");

    assert(isfield(projectCfg, "batchProcessing") && ...
            isstruct(projectCfg.batchProcessing) && ...
            isscalar(projectCfg.batchProcessing), ...
        "StrengthGridSearch:BatchProcessingMissing", ...
        "projectCfg.batchProcessing is required.");

    requiredBatchFields = [
        "enableParallel"
        "maxWorkers"
        "continueOnError"
        "poolProfile"
        "closePoolWhenFinished"
    ];

    missingBatchFields = ...
        requiredBatchFields( ...
            ~isfield( ...
                projectCfg.batchProcessing, ...
                cellstr(requiredBatchFields)));

    assert(isempty(missingBatchFields), ...
        "StrengthGridSearch:BatchProcessingFieldsMissing", ...
        "projectCfg.batchProcessing is missing required fields: %s", ...
        strjoin(missingBatchFields, ", "));

    %% Initialize controller result

    startedAt = ...
        string(datetime("now"));

    controllerTimer = ...
        tic;

    iterationRows = ...
        repmat( ...
            localEmptyIterationRow(), ...
            0, ...
            1);

    finalAnalysis = ...
        struct; %#ok<*NASGU>

    finalAnalysisOutputs = ...
        struct;

    stopStatus = ...
        "";

    stopReason = ...
        "";

    executedIterations = ...
        0;

    analysisOutputDirectory = ...
        localResolveAnalysisOutputDirectory( ...
            projectCfg, ...
            options.AnalysisOutputDirectory);

    historyCsv = ...
        string(fullfile( ...
            analysisOutputDirectory, ...
            "strength_grid_search_history.csv"));

    historyMat = ...
        string(fullfile( ...
            analysisOutputDirectory, ...
            "strength_grid_search.mat"));

    %% Keep a controller-owned parallel pool alive across iterations

    closePoolAtEnd = ...
        logical( ...
            projectCfg.batchProcessing.enableParallel && ...
            projectCfg.batchProcessing.closePoolWhenFinished);

    poolCleanup = ...
        onCleanup(@() ...
            localCloseParallelPool( ...
                closePoolAtEnd));

    %% Initial grid analysis

    currentAnalysis = ...
        localAnalyze( ...
            projectCfg, ...
            options);

    finalAnalysis = ...
        currentAnalysis;

    if options.PrintProgress

        fprintf( ...
            "\nStrength-grid search initialized.\n" + ...
            "Observed configurations: %d\n" + ...
            "Planning status: %s\n" + ...
            "Pareto configurations: %d\n", ...
            height(currentAnalysis.Summary), ...
            currentAnalysis.PlanningStatus, ...
            height(currentAnalysis.ParetoFrontier));
    end

    %% Evaluate initial stop state

    [shouldStop, stopStatus, stopReason] = ...
        localEvaluateAnalysisStopState( ...
            currentAnalysis);

    if shouldStop

        if ~options.DryRun

            [finalAnalysisOutputs, writeError] = ...
                localPersistAnalysis( ...
                    currentAnalysis, ...
                    projectCfg, ...
                    options);

            if strlength(writeError) > 0

                stopStatus = ...
                    "SEARCH_STOPPED_ANALYSIS_WRITE_ERROR";

                stopReason = ...
                    writeError;
            end
        end

        if ~options.DryRun && ...
                options.WriteSearchHistory

            localWriteSearchHistory( ...
                iterationRows, ...
                startedAt, ...
                stopStatus, ...
                stopReason, ...
                executedIterations, ...
                finalAnalysis, ...
                projectCfg, ...
                options, ...
                historyCsv, ...
                historyMat);
        end

        search = ...
            localFinalizeSearch( ...
                startedAt, ...
                controllerTimer, ...
                stopStatus, ...
                stopReason, ...
                executedIterations, ...
                iterationRows, ...
                finalAnalysis, ...
                finalAnalysisOutputs, ...
                historyCsv, ...
                historyMat, ...
                options, ...
                projectCfg);

        return;
    end

    %% Closed-loop execution

    for iteration = 1:options.MaxIterations

        iterationTimer = ...
            tic;

        row = ...
            localEmptyIterationRow();

        row.Iteration = ...
            iteration;

        row.StartedAt = ...
            string(datetime("now"));

        selection = ...
            soopt.resolveProposedStrengthConfig( ...
                currentAnalysis, ...
                "ProposalRank", ...
                1);

        row.ConfigId = ...
            selection.ConfigId;

        row.MusclePercent = ...
            selection.MusclePercent;

        row.ActuatorPercent = ...
            selection.ActuatorPercent;

        row.ConfigFile = ...
            selection.ConfigFile;

        row.ExistingIncomplete = ...
            selection.ExistingIncomplete;

        row.Status = ...
            "selected";

        if options.PrintProgress

            fprintf( ...
                "\nGrid-search iteration %d/%d\n" + ...
                "Selected: %s\n" + ...
                "Muscle: %g%% | Actuator: %g%%\n" + ...
                "Existing incomplete: %d\n", ...
                iteration, ...
                options.MaxIterations, ...
                selection.ConfigId, ...
                selection.MusclePercent, ...
                selection.ActuatorPercent, ...
                selection.ExistingIncomplete);
        end

        %% Dry-run selection check

        if options.DryRun

            row.Status = ...
                "dry_run_selected";

            row.CompletedAt = ...
                string(datetime("now"));

            row.DurationSeconds = ...
                toc(iterationTimer);

            iterationRows(end+1,1) = ... 
                row; %#ok<*AGROW>

            stopStatus = ...
                "SEARCH_DRY_RUN_READY";

            stopReason = ...
                "The rank-1 proposal resolved successfully. " + ...
                "DryRun=true prevented Process 3/4 execution and " + ...
                "filesystem writes.";

            finalAnalysis = ...
                currentAnalysis;

            break;
        end

        %% Incomplete-config overwrite policy

        if selection.ExistingIncomplete && ...
                ~options.OverwriteIncompleteConfiguration

            row.Status = ...
                "incomplete_overwrite_disabled";

            row.CompletedAt = ...
                string(datetime("now"));

            row.DurationSeconds = ...
                toc(iterationTimer);

            iterationRows(end+1,1) = ... 
                row;

            stopStatus = ...
                "SEARCH_STOPPED_INCOMPLETE_OVERWRITE_DISABLED";

            stopReason = ...
                "The selected proposal is an existing incomplete " + ...
                "configuration, but OverwriteIncompleteConfiguration=false.";

            finalAnalysis = ...
                currentAnalysis;

            break;
        end

        overwriteSelected = ...
            logical( ...
                selection.ExistingIncomplete && ...
                options.OverwriteIncompleteConfiguration);

        %% Create selected in-memory project config

        selectedCfg = ...
            projectCfg;

        selectedCfg.forceCapacity.enabled = ...
            true;

        selectedCfg.forceCapacity.configFile = ...
            selection.ConfigFile;

        assert( ...
            lower(string(selectedCfg.forceCapacity.applyMode)) == ...
                "target", ...
            "StrengthGridSearch:NonIdempotentApplyMode", ...
            "Automated strength-grid search requires " + ...
            "projectCfg.forceCapacity.applyMode=""target"".");

        %% Process 3

        row.Status = ...
            "process3_running";

        try

            process3 = ...
                pipeline.runStaticOptimizationPrepBatch( ...
                    selectedCfg, ...
                    "Overwrite", ...
                        overwriteSelected, ...
                    "ContinueOnError", ...
                        true, ...
                    "ClosePoolWhenFinished", ...
                        false, ...
                    "WriteSummary", ...
                        true, ...
                    "PrintProgress", ...
                        options.PrintProgress);

        catch exception

            row.Status = ...
                "process3_error";

            row.ErrorIdentifier = ...
                string(exception.identifier);

            row.ErrorMessage = ...
                string(exception.message);

            row.CompletedAt = ...
                string(datetime("now"));

            row.DurationSeconds = ...
                toc(iterationTimer);

            iterationRows(end+1,1) = ...
                row;

            stopStatus = ...
                "SEARCH_STOPPED_PROCESS3_ERROR";

            stopReason = ...
                "Process 3 raised a controller-level exception for " + ...
                selection.ConfigId + ...
                ": " + ...
                string(exception.message);

            finalAnalysis = ...
                currentAnalysis;

            break;
        end

        row.Process3Succeeded = ...
            process3.Succeeded;

        row.Process3FailedJobs = ...
            process3.FailedJobs;

        row.Process3SummaryCsv = ...
            process3.SummaryCsv;

        if ~process3.Succeeded

            row.Status = ...
                "process3_failed";

            row.CompletedAt = ...
                string(datetime("now"));

            row.DurationSeconds = ...
                toc(iterationTimer);

            iterationRows(end+1,1) = ...
                row;

            stopStatus = ...
                "SEARCH_STOPPED_PROCESS3_FAILURE";

            stopReason = ...
                sprintf( ...
                    "Process 3 completed for %s but %d trial(s) failed. " + ...
                    "Static Optimization was not started.", ...
                    selection.ConfigId, ...
                    process3.FailedJobs);

            finalAnalysis = ...
                currentAnalysis;

            break;
        end

        %% Process 4

        row.Status = ...
            "process4_running";

        try

            process4 = ...
                pipeline.runStaticOptimizationBatch( ...
                    selectedCfg, ...
                    "Overwrite", ...
                        overwriteSelected, ...
                    "ContinueOnError", ...
                        true, ...
                    "ClosePoolWhenFinished", ...
                        false, ...
                    "WriteSummary", ...
                        true, ...
                    "PrintProgress", ...
                        options.PrintProgress);

        catch exception

            row.Status = ...
                "process4_error";

            row.ErrorIdentifier = ...
                string(exception.identifier);

            row.ErrorMessage = ...
                string(exception.message);

            row.CompletedAt = ...
                string(datetime("now"));

            row.DurationSeconds = ...
                toc(iterationTimer);

            iterationRows(end+1,1) = ...
                row;

            stopStatus = ...
                "SEARCH_STOPPED_PROCESS4_ERROR";

            stopReason = ...
                "Process 4 raised a controller-level exception for " + ...
                selection.ConfigId + ...
                ": " + ...
                string(exception.message);

            finalAnalysis = ...
                currentAnalysis;

            break;
        end

        executedIterations = ...
            executedIterations + 1;

        row.Process4BatchSucceeded = ...
            process4.Succeeded;

        row.Process4FailedJobs = ...
            process4.FailedJobs;

        row.Process4SummaryCsv = ...
            process4.SummaryCsv;

        %% Refresh grid evidence

        refreshedAnalysis = ...
            localAnalyze( ...
                projectCfg, ...
                options);

        finalAnalysis = ...
            refreshedAnalysis;

        row = ...
            localPopulateAssessment( ...
                row, ...
                refreshedAnalysis, ...
                selection.ConfigId);

        row.ParetoConfigIdsAfter = ...
            localJoinConfigIds( ...
                refreshedAnalysis.ParetoFrontier);

        if ~isempty(refreshedAnalysis.Proposals)

            row.NextProposalConfigId = ...
                string( ...
                    refreshedAnalysis.Proposals.ConfigId(1));
        end

        row.Status = ...
            "completed";

        row.CompletedAt = ...
            string(datetime("now"));

        row.DurationSeconds = ...
            toc(iterationTimer);
 
        iterationRows(end+1,1) = ...
            row;

        %% Persist refreshed analysis

        if options.WriteAnalysis

            [analysisOutputs, writeError] = ...
                localPersistAnalysis( ...
                    refreshedAnalysis, ...
                    projectCfg, ...
                    options);

            if strlength(writeError) > 0

                finalAnalysisOutputs = ...
                    struct;

                stopStatus = ...
                    "SEARCH_STOPPED_ANALYSIS_WRITE_ERROR";

                stopReason = ...
                    writeError;

                break;
            end

            finalAnalysisOutputs = ...
                analysisOutputs;
        end

        %% Persist iteration history

        if options.WriteSearchHistory

            localWriteSearchHistory( ...
                iterationRows, ...
                startedAt, ...
                "", ...
                "", ...
                executedIterations, ...
                refreshedAnalysis, ...
                projectCfg, ...
                options, ...
                historyCsv, ...
                historyMat);
        end

        if options.PrintProgress

            fprintf( ...
                "Iteration %d assessment: %s\n" + ...
                "Feasible: %d\n" + ...
                "Pareto after iteration: %s\n", ...
                iteration, ...
                row.FeasibilityStatus, ...
                row.IsFeasible, ...
                row.ParetoConfigIdsAfter);
        end

        %% Evaluate refreshed stop state

        [shouldStop, stopStatus, stopReason] = ...
            localEvaluateAnalysisStopState( ...
                refreshedAnalysis);

        if shouldStop

            currentAnalysis = ...
                refreshedAnalysis;

            break;
        end

        if iteration == options.MaxIterations

            stopStatus = ...
                "SEARCH_STOPPED_MAX_ITERATIONS";

            stopReason = ...
                sprintf( ...
                    "The controller executed the requested maximum of " + ...
                    "%d configuration(s). Additional proposals remain.", ...
                    options.MaxIterations);

            currentAnalysis = ...
                refreshedAnalysis;

            break;
        end

        currentAnalysis = ...
            refreshedAnalysis;
    end

    %% Defensive fallback

    if strlength(stopStatus) == 0

        stopStatus = ...
            "SEARCH_STOPPED_MAX_ITERATIONS";

        stopReason = ...
            sprintf( ...
                "The controller reached MaxIterations=%d.", ...
                options.MaxIterations);
    end

    %% Final persistence

    if ~options.DryRun

        if options.WriteAnalysis && ...
                isempty(fieldnames(finalAnalysisOutputs))

            [analysisOutputs, writeError] = ...
                localPersistAnalysis( ...
                    finalAnalysis, ...
                    projectCfg, ...
                    options);

            if strlength(writeError) > 0

                stopStatus = ...
                    "SEARCH_STOPPED_ANALYSIS_WRITE_ERROR";

                stopReason = ...
                    writeError;

            else

                finalAnalysisOutputs = ...
                    analysisOutputs;
            end
        end

        if options.WriteSearchHistory

            localWriteSearchHistory( ...
                iterationRows, ...
                startedAt, ...
                stopStatus, ...
                stopReason, ...
                executedIterations, ...
                finalAnalysis, ...
                projectCfg, ...
                options, ...
                historyCsv, ...
                historyMat);
        end
    end

    %% Final result

    search = ...
        localFinalizeSearch( ...
            startedAt, ...
            controllerTimer, ...
            stopStatus, ...
            stopReason, ...
            executedIterations, ...
            iterationRows, ...
            finalAnalysis, ...
            finalAnalysisOutputs, ...
            historyCsv, ...
            historyMat, ...
            options, ...
            projectCfg);

    if options.PrintProgress

        fprintf( ...
            "\nStrength-grid search stopped.\n" + ...
            "Status: %s\n" + ...
            "Reason: %s\n" + ...
            "Executed configurations: %d\n", ...
            search.StopStatus, ...
            search.StopReason, ...
            search.ExecutedIterations);
    end
end


function analysis = localAnalyze(projectCfg, options)

    if strlength(options.ConfigDirectory) > 0

        analysis = ...
            soopt.analyzeStrengthGrid( ...
                projectCfg, ...
                "ConfigDirectory", ...
                    options.ConfigDirectory, ...
                "MaxProposals", ...
                    1, ...
                "CreateFigure", ...
                    false);

    else

        analysis = ...
            soopt.analyzeStrengthGrid( ...
                projectCfg, ...
                "MaxProposals", ...
                    1, ...
                "CreateFigure", ...
                    false);
    end
end


function [shouldStop, status, reason] = ...
        localEvaluateAnalysisStopState(analysis)

    shouldStop = ...
        false;

    status = ...
        "";

    reason = ...
        "";

    if ~analysis.PlanningAvailable

        shouldStop = ...
            true;

        status = ...
            "SEARCH_STOPPED_PLANNING_UNAVAILABLE";

        reason = ...
            "Grid planning is unavailable (" + ...
            string(analysis.PlanningStatus) + ...
            "): " + ...
            string(analysis.PlanningReason);

        return;
    end

    if isempty(analysis.Proposals)

        shouldStop = ...
            true;

        status = ...
            "SEARCH_COMPLETE_NO_PROPOSALS";

        reason = ...
            "No unresolved strength configurations remain to assess.";
    end
end


function [outputs, errorText] = ...
        localPersistAnalysis(analysis, projectCfg, options)

    outputs = ...
        struct;

    errorText = ...
        "";

    if ~options.WriteAnalysis

        return;
    end

    try

        if strlength(options.AnalysisOutputDirectory) > 0

            outputs = ...
                soopt.writeStrengthGridAnalysis( ...
                    analysis, ...
                    projectCfg, ...
                    "OutputDirectory", ...
                        options.AnalysisOutputDirectory, ...
                    "Overwrite", ...
                        true, ...
                    "ExportFigure", ...
                        options.ExportFigure, ...
                    "FigureResolution", ...
                        options.FigureResolution);

        else

            outputs = ...
                soopt.writeStrengthGridAnalysis( ...
                    analysis, ...
                    projectCfg, ...
                    "Overwrite", ...
                        true, ...
                    "ExportFigure", ...
                        options.ExportFigure, ...
                    "FigureResolution", ...
                        options.FigureResolution);
        end

    catch exception

        errorText = ...
            "Writing the strength-grid analysis failed: " + ...
            string(exception.identifier) + ...
            " | " + ...
            string(exception.message);
    end
end


function row = ...
        localPopulateAssessment(row, analysis, configId)

    if isempty(analysis.Summary)

        return;
    end

    mask = ...
        string(analysis.Summary.ConfigId) == ...
        string(configId);

    if nnz(mask) ~= 1

        return;
    end

    assessed = ...
        analysis.Summary(mask, :);

    row.AssessmentComplete = ...
        logical(assessed.AssessmentComplete);

    row.IsFeasible = ...
        logical(assessed.IsFeasible);

    row.FeasibilityStatus = ...
        string(assessed.FeasibilityStatus);

    row.FeasibilityReason = ...
        string(assessed.FeasibilityReason);
end


function text = localJoinConfigIds(T)

    if isempty(T) || ...
            ~ismember( ...
                "ConfigId", ...
                string(T.Properties.VariableNames))

        text = ...
            "";

        return;
    end

    ids = ...
        string(T.ConfigId(:));

    ids = ...
        ids( ...
            ~ismissing(ids) & ...
            strlength(ids) > 0);

    text = ...
        strjoin( ...
            ids, ...
            ";");
end


function outputDirectory = ...
        localResolveAnalysisOutputDirectory( ...
            projectCfg, requestedDirectory)

    requestedDirectory = ...
        string(requestedDirectory);

    if strlength(requestedDirectory) > 0

        outputDirectory = ...
            requestedDirectory;

        return;
    end

    outputRoot = ...
        string(projectCfg.outputRoot);

    assert(isscalar(outputRoot) && ...
            ~ismissing(outputRoot) && ...
            strlength(outputRoot) > 0, ...
        "StrengthGridSearch:OutputRootMissing", ...
        "projectCfg.outputRoot must be nonempty.");

    outputDirectory = ...
        string(fullfile( ...
            outputRoot, ...
            "static_optimization_configs", ...
            "grid_search_analysis"));
end


function localWriteSearchHistory( ...
        iterationRows, ...
        startedAt, ...
        stopStatus, ...
        stopReason, ...
        executedIterations, ...
        finalAnalysis, ...
        projectCfg, ...
        options, ...
        historyCsv, ...
        historyMat)

    outputDirectory = ...
        string(fileparts(historyCsv));

    if ~isfolder(outputDirectory)

        mkdir(outputDirectory);
    end

    iterations = ...
        localRowsToTable( ...
            iterationRows);

    writetable( ...
        iterations, ...
        historyCsv);

    serializableAnalysis = ...
        finalAnalysis;

    if isstruct(serializableAnalysis)

        if isfield(serializableAnalysis, "Figure")

            serializableAnalysis.Figure = ...
                [];
        end

        if isfield(serializableAnalysis, "Axes")

            serializableAnalysis.Axes = ...
                [];
        end
    end

    searchSnapshot = struct;

    searchSnapshot.SchemaVersion = ...
        1;

    searchSnapshot.StartedAt = ...
        startedAt;

    searchSnapshot.WrittenAt = ...
        string(datetime("now"));

    searchSnapshot.StopStatus = ...
        string(stopStatus);

    searchSnapshot.StopReason = ...
        string(stopReason);

    searchSnapshot.ExecutedIterations = ...
        executedIterations;

    searchSnapshot.Iterations = ...
        iterations;

    searchSnapshot.FinalAnalysis = ...
        serializableAnalysis;

    searchSnapshot.ProjectConfig = ...
        projectCfg;

    searchSnapshot.ControllerOptions = ...
        options;

    save( ...
        historyMat, ...
        "searchSnapshot", ...
        "-v7.3");
end


function search = ...
        localFinalizeSearch( ...
            startedAt, ...
            controllerTimer, ...
            stopStatus, ...
            stopReason, ...
            executedIterations, ...
            iterationRows, ...
            finalAnalysis, ...
            finalAnalysisOutputs, ...
            historyCsv, ...
            historyMat, ...
            options, ...
            projectCfg)

    search = struct;

    search.SchemaVersion = ...
        1;

    search.StartedAt = ...
        startedAt;

    search.CompletedAt = ...
        string(datetime("now"));

    search.DurationSeconds = ...
        toc(controllerTimer);

    search.StopStatus = ...
        string(stopStatus);

    search.StopReason = ...
        string(stopReason);

    search.ExecutedIterations = ...
        executedIterations;

    search.Iterations = ...
        localRowsToTable( ...
            iterationRows);

    search.FinalAnalysis = ...
        finalAnalysis;

    search.FinalAnalysisOutputs = ...
        finalAnalysisOutputs;

    if options.DryRun || ...
            ~options.WriteSearchHistory

        search.SearchHistoryCsv = ...
            "";

        search.SearchHistoryMat = ...
            "";

    else

        search.SearchHistoryCsv = ...
            historyCsv;

        search.SearchHistoryMat = ...
            historyMat;
    end

    search.Configuration = ...
        options;

    search.ProjectOutputRoot = ...
        string(projectCfg.outputRoot);
end


function T = localRowsToTable(rows)

    if isempty(rows)

        T = ...
            struct2table( ...
                repmat( ...
                    localEmptyIterationRow(), ...
                    0, ...
                    1));

        return;
    end

    T = ...
        struct2table( ...
            rows);
end


function row = localEmptyIterationRow()

    row = struct;

    row.Iteration = ...
        NaN;

    row.ConfigId = ...
        "";

    row.MusclePercent = ...
        NaN;

    row.ActuatorPercent = ...
        NaN;

    row.ConfigFile = ...
        "";

    row.ExistingIncomplete = ...
        false;

    row.StartedAt = ...
        "";

    row.CompletedAt = ...
        "";

    row.DurationSeconds = ...
        NaN;

    row.Process3Succeeded = ...
        false;

    row.Process3FailedJobs = ...
        NaN;

    row.Process3SummaryCsv = ...
        "";

    row.Process4BatchSucceeded = ...
        false;

    row.Process4FailedJobs = ...
        NaN;

    row.Process4SummaryCsv = ...
        "";

    row.AssessmentComplete = ...
        false;

    row.IsFeasible = ...
        false;

    row.FeasibilityStatus = ...
        "";

    row.FeasibilityReason = ...
        "";

    row.ParetoConfigIdsAfter = ...
        "";

    row.NextProposalConfigId = ...
        "";

    row.Status = ...
        "not_started";

    row.ErrorIdentifier = ...
        "";

    row.ErrorMessage = ...
        "";
end


function localCloseParallelPool(closePoolAtEnd)

    if ~closePoolAtEnd

        return;
    end

    pool = ...
        gcp("nocreate");

    if ~isempty(pool)

        delete(pool);
    end
end
