function summary = summarizeStrengthConfigurations(projectCfg)
%SUMMARIZESTRENGTHCONFIGURATIONS Summarize discovered SO grid configurations.
%
% summary = soopt.summarizeStrengthConfigurations(projectCfg)
%
% This function discovers all canonical strength configurations beneath:
%
%   <outputRoot>/static_optimization_configs/
%
% and evaluates the Process-4 feasibility evidence for each configuration.
%
% The function is intentionally SIDE-EFFECT FREE. It does not create or
% modify files or directories.
%
% Feasibility is delegated to:
%
%   soopt.evaluateFeasibility
%
% so that incomplete evidence remains distinct from genuine infeasibility.
%
% RETURN TABLE
%
% Discovery identity / provenance:
%
%   ConfigId
%   MusclePercent
%   ActuatorPercent
%   ConfigRoot
%   BatchQcDirectory
%   Process4SummaryCsv
%   Process4SummaryCsvExists
%   Process4SummaryMat
%   Process4SummaryMatExists
%   AnalysisDirectory
%   AnalysisExists
%
% Feasibility summary:
%
%   AssessmentComplete
%   IsFeasible
%   FeasibilityStatus
%   FeasibilityReason
%   ExpectedTrials
%   SummaryRows
%   UniqueTrialRows
%   SucceededTrials
%   FailedTrials
%   OutputAuditPassedTrials
%   OutputAuditFailedTrials
%
% Trial-key diagnostics are stored as semicolon-delimited strings:
%
%   MissingTrialKeys
%   UnexpectedTrialKeys
%   DuplicateTrialKeys
%   FailedTrialKeys
%   OutputAuditFailedTrialKeys

    %% Discover canonical configurations

    configs = ...
        soopt.discoverStrengthConfigurations( ...
            projectCfg);

    if isempty(configs)

        summary = ...
            localEmptySummaryTable();

        return;
    end

    nConfigs = ...
        height(configs);

    %% Allocate feasibility columns

    AssessmentComplete = ...
        false(nConfigs,1);

    IsFeasible = ...
        false(nConfigs,1);

    FeasibilityStatus = ...
        strings(nConfigs,1);

    FeasibilityReason = ...
        strings(nConfigs,1);

    ExpectedTrials = ...
        zeros(nConfigs,1);

    SummaryRows = ...
        zeros(nConfigs,1);

    UniqueTrialRows = ...
        zeros(nConfigs,1);

    SucceededTrials = ...
        zeros(nConfigs,1);

    FailedTrials = ...
        zeros(nConfigs,1);

    OutputAuditPassedTrials = ...
        zeros(nConfigs,1);

    OutputAuditFailedTrials = ...
        zeros(nConfigs,1);

    MissingTrialKeys = ...
        strings(nConfigs,1);

    UnexpectedTrialKeys = ...
        strings(nConfigs,1);

    DuplicateTrialKeys = ...
        strings(nConfigs,1);

    FailedTrialKeys = ...
        strings(nConfigs,1);

    OutputAuditFailedTrialKeys = ...
        strings(nConfigs,1);

    %% Evaluate each configuration independently

    for iConfig = 1:nConfigs

        result = ...
            soopt.evaluateFeasibility( ...
                configs(iConfig,:), ...
                projectCfg);

        AssessmentComplete(iConfig) = ...
            result.AssessmentComplete;

        IsFeasible(iConfig) = ...
            result.IsFeasible;

        FeasibilityStatus(iConfig) = ...
            result.Status;

        FeasibilityReason(iConfig) = ...
            result.Reason;

        ExpectedTrials(iConfig) = ...
            result.ExpectedTrials;

        SummaryRows(iConfig) = ...
            result.SummaryRows;

        UniqueTrialRows(iConfig) = ...
            result.UniqueTrialRows;

        SucceededTrials(iConfig) = ...
            result.SucceededTrials;

        FailedTrials(iConfig) = ...
            result.FailedTrials;

        OutputAuditPassedTrials(iConfig) = ...
            result.OutputAuditPassedTrials;

        OutputAuditFailedTrials(iConfig) = ...
            result.OutputAuditFailedTrials;

        MissingTrialKeys(iConfig) = ...
            localJoinKeys( ...
                result.MissingTrialKeys);

        UnexpectedTrialKeys(iConfig) = ...
            localJoinKeys( ...
                result.UnexpectedTrialKeys);

        DuplicateTrialKeys(iConfig) = ...
            localJoinKeys( ...
                result.DuplicateTrialKeys);

        FailedTrialKeys(iConfig) = ...
            localJoinKeys( ...
                result.FailedTrialKeys);

        OutputAuditFailedTrialKeys(iConfig) = ...
            localJoinKeys( ...
                result.OutputAuditFailedTrialKeys);
    end

    %% Combine discovery and feasibility outputs

    feasibility = ...
        table( ...
            AssessmentComplete, ...
            IsFeasible, ...
            FeasibilityStatus, ...
            FeasibilityReason, ...
            ExpectedTrials, ...
            SummaryRows, ...
            UniqueTrialRows, ...
            SucceededTrials, ...
            FailedTrials, ...
            OutputAuditPassedTrials, ...
            OutputAuditFailedTrials, ...
            MissingTrialKeys, ...
            UnexpectedTrialKeys, ...
            DuplicateTrialKeys, ...
            FailedTrialKeys, ...
            OutputAuditFailedTrialKeys);

    summary = ...
        [configs feasibility];
end


function text = localJoinKeys(keys)

    keys = ...
        string(keys(:));

    keys = ...
        keys( ...
            ~ismissing(keys) & ...
            strlength(keys) > 0);

    if isempty(keys)

        text = "";

        return;
    end

    text = ...
        strjoin( ...
            keys, ...
            ";");
end


function T = localEmptySummaryTable()

    T = ...
        table( ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            strings(0,1), ...
            strings(0,1), ...
            strings(0,1), ...
            false(0,1), ...
            strings(0,1), ...
            false(0,1), ...
            strings(0,1), ...
            false(0,1), ...
            false(0,1), ...
            false(0,1), ...
            strings(0,1), ...
            strings(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            zeros(0,1), ...
            strings(0,1), ...
            strings(0,1), ...
            strings(0,1), ...
            strings(0,1), ...
            strings(0,1), ...
            'VariableNames', { ...
                'ConfigId', ...
                'MusclePercent', ...
                'ActuatorPercent', ...
                'ConfigRoot', ...
                'BatchQcDirectory', ...
                'Process4SummaryCsv', ...
                'Process4SummaryCsvExists', ...
                'Process4SummaryMat', ...
                'Process4SummaryMatExists', ...
                'AnalysisDirectory', ...
                'AnalysisExists', ...
                'AssessmentComplete', ...
                'IsFeasible', ...
                'FeasibilityStatus', ...
                'FeasibilityReason', ...
                'ExpectedTrials', ...
                'SummaryRows', ...
                'UniqueTrialRows', ...
                'SucceededTrials', ...
                'FailedTrials', ...
                'OutputAuditPassedTrials', ...
                'OutputAuditFailedTrials', ...
                'MissingTrialKeys', ...
                'UnexpectedTrialKeys', ...
                'DuplicateTrialKeys', ...
                'FailedTrialKeys', ...
                'OutputAuditFailedTrialKeys'});
end
