function result = writeStrengthConfiguration( ...
        projectCfg, musclePercent, actuatorPercent, varargin)
%WRITESTRENGTHCONFIGURATION Create or reuse a canonical strength JSON.
%
% result = soopt.writeStrengthConfiguration( ...
%     projectCfg, musclePercent, actuatorPercent)
%
% Creates a force-capacity JSON for one muscle/actuator strength coordinate
% by transforming a validated existing strength configuration.
%
% The template configuration supplies the authoritative ForceSet entry list,
% reference capacities, appliesForce states, and source-model metadata.
% This function changes only:
%
%   * muscle CapacityAction=="set" entries:
%         ScaleFactor = musclePercent / 100
%         TargetValue = ReferenceValue * ScaleFactor
%
%   * actuator CapacityAction=="set" entries:
%         ScaleFactor = actuatorPercent / 100
%         TargetValue = ReferenceValue * ScaleFactor
%
% All other entry fields are preserved.
%
% The output is validated through modelprep.loadForceCapacityConfig before
% it is accepted.
%
% DEFAULT OUTPUT LOCATION
%
% If ConfigDirectory is omitted, generated configs are written to:
%
%   <template-directory>/adaptive_generated/
%
% This deliberately keeps dynamically generated configs separate from the
% pre-generated complete-Cartesian pool used by the fixed-grid planner.
%
% NAME-VALUE OPTIONS
%
%   TemplateConfigFile
%       Existing validated strength JSON used as the reference template.
%       Default: projectCfg.forceCapacity.configFile.
%
%   ConfigDirectory
%       Destination directory. Default: adaptive_generated beside template.
%
%   ReuseExisting
%       If the canonical destination JSON already exists, validate that it
%       represents the requested coordinate and return it. Default true.
%
%   Description
%       Optional JSON Description. Default is generated automatically.
%
% RETURN STRUCT
%
%   SchemaVersion
%   ConfigId
%   MusclePercent
%   ActuatorPercent
%   FileName
%   ConfigFile
%   ConfigDirectory
%   TemplateConfigFile
%   Created
%   ReusedExisting
%   MuscleEntryCount
%   ActuatorEntryCount
%   ValidatedConfig
%
% Percentages must be positive integers. Search-resolution constraints such
% as 5% increments belong to the adaptive proposal layer, not this writer.
%
% This function never modifies the template JSON.

    parser = inputParser;
    parser.FunctionName = "soopt.writeStrengthConfiguration";

    addRequired(parser, "projectCfg", ...
        @(x) isstruct(x) && isscalar(x));

    addRequired(parser, "musclePercent", ...
        @(x) isnumeric(x) && isscalar(x));

    addRequired(parser, "actuatorPercent", ...
        @(x) isnumeric(x) && isscalar(x));

    defaultTemplate = localDefaultTemplateConfig(projectCfg);

    addParameter(parser, "TemplateConfigFile", defaultTemplate, ...
        @(x) ...
            (ischar(x) && (isrow(x) || isempty(x))) || ...
            (isstring(x) && isscalar(x) && ~ismissing(x)));

    addParameter(parser, "ConfigDirectory", "", ...
        @(x) ...
            (ischar(x) && (isrow(x) || isempty(x))) || ...
            (isstring(x) && isscalar(x) && ~ismissing(x)));

    addParameter(parser, "ReuseExisting", true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, "Description", "", ...
        @(x) ...
            (ischar(x) && (isrow(x) || isempty(x))) || ...
            (isstring(x) && isscalar(x) && ~ismissing(x)));

    parse(parser, ...
        projectCfg, ...
        musclePercent, ...
        actuatorPercent, ...
        varargin{:});

    musclePercent = double(parser.Results.musclePercent);
    actuatorPercent = double(parser.Results.actuatorPercent);
    templateConfigFile = string(parser.Results.TemplateConfigFile);
    requestedDirectory = string(parser.Results.ConfigDirectory);
    reuseExisting = logical(parser.Results.ReuseExisting);
    description = string(parser.Results.Description);

    localValidatePercent(musclePercent, "musclePercent");
    localValidatePercent(actuatorPercent, "actuatorPercent");

    assert( ...
        strlength(templateConfigFile) > 0 && ...
        isfile(templateConfigFile), ...
        "StrengthConfigWrite:TemplateMissing", ...
        "Template strength configuration was not found:\n%s", ...
        templateConfigFile);

    configId = localConfigId( ...
        musclePercent, ...
        actuatorPercent);

    fileName = configId + ".json";

    [templateDirectory, ~, ~] = fileparts(templateConfigFile);

    if strlength(requestedDirectory) > 0
        configDirectory = requestedDirectory;
    else
        configDirectory = string(fullfile( ...
            templateDirectory, ...
            "adaptive_generated"));
    end

    configFile = string(fullfile( ...
        configDirectory, ...
        fileName));

    parsedIdentity = ...
        pipeline.parseStrengthConfigName(fileName);

    assert( ...
        parsedIdentity.ConfigId == configId && ...
        parsedIdentity.MusclePercent == musclePercent && ...
        parsedIdentity.ActuatorPercent == actuatorPercent, ...
        "StrengthConfigWrite:CanonicalIdentityMismatch", ...
        "Generated filename did not round-trip through the canonical parser.");

    if isfile(configFile)

        if ~reuseExisting
            error( ...
                "StrengthConfigWrite:OutputExists", ...
                "Strength configuration already exists:\n%s", ...
                configFile);
        end

        existingLoaded = ...
            modelprep.loadForceCapacityConfig(configFile);

        [muscleEntryCount, actuatorEntryCount] = ...
            localValidateConfigCoordinate( ...
                existingLoaded.Config, ...
                musclePercent, ...
                actuatorPercent, ...
                configFile);

        result = localBuildResult( ...
            configId, ...
            musclePercent, ...
            actuatorPercent, ...
            fileName, ...
            configFile, ...
            configDirectory, ...
            templateConfigFile, ...
            false, ...
            true, ...
            muscleEntryCount, ...
            actuatorEntryCount, ...
            existingLoaded.Config);

        return;
    end

    templateLoaded = ...
        modelprep.loadForceCapacityConfig(templateConfigFile);

    config = templateLoaded.Config;
    originalEntryShape = size(config.Entries);
    entries = config.Entries(:);

    muscleEntryCount = 0;
    actuatorEntryCount = 0;

    for iEntry = 1:numel(entries)

        capacityAction = ...
            lower(string(entries(iEntry).CapacityAction));

        if capacityAction ~= "set"
            continue;
        end

        objectType = ...
            lower(string(entries(iEntry).ObjectType));

        referenceValue = ...
            double(entries(iEntry).ReferenceValue);

        assert( ...
            isfinite(referenceValue) && ...
            referenceValue > 0, ...
            "StrengthConfigWrite:InvalidReferenceValue", ...
            "Template entry '%s' [%s] has an invalid ReferenceValue.", ...
            string(entries(iEntry).Name), ...
            string(entries(iEntry).ObjectType));

        if endsWith(objectType, "muscle")

            scaleFactor = musclePercent / 100;
            muscleEntryCount = muscleEntryCount + 1;

        elseif contains(objectType, "actuator")

            scaleFactor = actuatorPercent / 100;
            actuatorEntryCount = actuatorEntryCount + 1;

        else
            continue;
        end

        entries(iEntry).ScaleFactor = scaleFactor;
        entries(iEntry).TargetValue = ...
            referenceValue * scaleFactor;
    end

    assert( ...
        muscleEntryCount > 0, ...
        "StrengthConfigWrite:NoMuscleEntries", ...
        "Template configuration contains no adjustable muscle entries.");

    assert( ...
        actuatorEntryCount > 0, ...
        "StrengthConfigWrite:NoActuatorEntries", ...
        "Template configuration contains no adjustable actuator entries.");

    config.Entries = reshape(entries, originalEntryShape);
    config.DefaultApplyMode = "target";

    config.CreatedAt = ...
        char(string(datetime( ...
            "now", ...
            "Format", ...
            "yyyy-MM-dd'T'HH:mm:ss")));

    if strlength(description) == 0
        description = ...
            "Adaptive strength-grid configuration: muscle " + ...
            string(musclePercent) + ...
            "%, actuator " + ...
            string(actuatorPercent) + ...
            "%.";
    end

    config.Description = char(description);

    if ~isfolder(configDirectory)
        mkdir(configDirectory);
    end

    temporaryFile = string(fullfile( ...
        configDirectory, ...
        "." + ...
        configId + ...
        "_tmp_" + ...
        string(java.util.UUID.randomUUID()) + ...
        ".json"));

    temporaryCleanup = ...
        onCleanup(@() localDeleteIfExists(temporaryFile));

    try
        jsonText = jsonencode( ...
            config, ...
            "PrettyPrint", ...
            true);
    catch
        jsonText = jsonencode(config);
    end

    fileId = fopen(temporaryFile, "w");

    assert(fileId >= 0, ...
        "StrengthConfigWrite:OpenFailed", ...
        "Could not open temporary config for writing:\n%s", ...
        temporaryFile);

    fileCleanup = onCleanup(@() fclose(fileId));

    fwrite(fileId, jsonText, "char");

    clear fileCleanup

    validated = ...
        modelprep.loadForceCapacityConfig(temporaryFile);

    [validatedMuscleCount, validatedActuatorCount] = ...
        localValidateConfigCoordinate( ...
            validated.Config, ...
            musclePercent, ...
            actuatorPercent, ...
            temporaryFile);

    assert( ...
        validatedMuscleCount == muscleEntryCount && ...
        validatedActuatorCount == actuatorEntryCount, ...
        "StrengthConfigWrite:ValidationCountMismatch", ...
        "Written strength-entry counts changed during JSON validation.");

    [movePassed, moveMessage] = ...
        movefile( ...
            temporaryFile, ...
            configFile);

    assert(movePassed, ...
        "StrengthConfigWrite:MoveFailed", ...
        "Could not finalize strength configuration:\n%s", ...
        string(moveMessage));

    finalLoaded = ...
        modelprep.loadForceCapacityConfig(configFile);

    result = localBuildResult( ...
        configId, ...
        musclePercent, ...
        actuatorPercent, ...
        fileName, ...
        configFile, ...
        configDirectory, ...
        templateConfigFile, ...
        true, ...
        false, ...
        muscleEntryCount, ...
        actuatorEntryCount, ...
        finalLoaded.Config);
end


function templateConfigFile = localDefaultTemplateConfig(projectCfg)

    templateConfigFile = "";

    if isfield(projectCfg, "forceCapacity") && ...
            isstruct(projectCfg.forceCapacity) && ...
            isscalar(projectCfg.forceCapacity) && ...
            isfield(projectCfg.forceCapacity, "configFile")

        templateConfigFile = ...
            string(projectCfg.forceCapacity.configFile);
    end
end


function localValidatePercent(value, argumentName)

    assert( ...
        isfinite(value) && ...
        value > 0 && ...
        value == fix(value), ...
        "StrengthConfigWrite:InvalidPercent", ...
        "%s must be a positive integer percentage.", ...
        argumentName);
end


function configId = localConfigId( ...
        musclePercent, ...
        actuatorPercent)

    configId = ...
        "m" + ...
        string(musclePercent) + ...
        "p_a" + ...
        compose("%02d", actuatorPercent) + ...
        "p";
end


function [muscleCount, actuatorCount] = ...
        localValidateConfigCoordinate( ...
            config, ...
            musclePercent, ...
            actuatorPercent, ...
            configFile)

    entries = config.Entries(:);

    muscleCount = 0;
    actuatorCount = 0;

    for iEntry = 1:numel(entries)

        if lower(string(entries(iEntry).CapacityAction)) ~= "set"
            continue;
        end

        objectType = ...
            lower(string(entries(iEntry).ObjectType));

        if endsWith(objectType, "muscle")

            expectedScale = musclePercent / 100;
            muscleCount = muscleCount + 1;

        elseif contains(objectType, "actuator")

            expectedScale = actuatorPercent / 100;
            actuatorCount = actuatorCount + 1;

        else
            continue;
        end

        referenceValue = double(entries(iEntry).ReferenceValue);
        actualTarget = double(entries(iEntry).TargetValue);
        actualScale = double(entries(iEntry).ScaleFactor);
        expectedTarget = referenceValue * expectedScale;

        scaleTolerance = ...
            max(1e-12, ...
                1e-10 * abs(expectedScale));

        targetTolerance = ...
            max(1e-12, ...
                1e-10 * abs(expectedTarget));

        if abs(actualScale - expectedScale) > ...
                scaleTolerance || ...
                abs(actualTarget - expectedTarget) > ...
                targetTolerance

            error( ...
                "StrengthConfigWrite:ExistingConfigMismatch", ...
                "Configuration %s does not represent the requested " + ...
                "strength coordinate. Entry '%s' [%s] has " + ...
                "TargetValue=%g and ScaleFactor=%g; expected %g and %g.", ...
                configFile, ...
                string(entries(iEntry).Name), ...
                string(entries(iEntry).ObjectType), ...
                actualTarget, ...
                actualScale, ...
                expectedTarget, ...
                expectedScale);
        end
    end

    assert( ...
        muscleCount > 0, ...
        "StrengthConfigWrite:NoMuscleEntries", ...
        "Configuration contains no adjustable muscle entries:\n%s", ...
        configFile);

    assert( ...
        actuatorCount > 0, ...
        "StrengthConfigWrite:NoActuatorEntries", ...
        "Configuration contains no adjustable actuator entries:\n%s", ...
        configFile);
end


function result = localBuildResult( ...
        configId, ...
        musclePercent, ...
        actuatorPercent, ...
        fileName, ...
        configFile, ...
        configDirectory, ...
        templateConfigFile, ...
        created, ...
        reusedExisting, ...
        muscleEntryCount, ...
        actuatorEntryCount, ...
        validatedConfig)

    result = struct;

    result.SchemaVersion = 1;
    result.ConfigId = configId;
    result.MusclePercent = musclePercent;
    result.ActuatorPercent = actuatorPercent;
    result.FileName = fileName;
    result.ConfigFile = configFile;
    result.ConfigDirectory = configDirectory;
    result.TemplateConfigFile = templateConfigFile;
    result.Created = logical(created);
    result.ReusedExisting = logical(reusedExisting);
    result.MuscleEntryCount = muscleEntryCount;
    result.ActuatorEntryCount = actuatorEntryCount;
    result.ValidatedConfig = validatedConfig;
end


function localDeleteIfExists(filePath)

    if isfile(filePath)
        delete(filePath);
    end
end
