function outputs = writeStrengthGridAnalysis(result, projectCfg, varargin)
%WRITESTRENGTHGRIDANALYSIS Persist a completed strength-grid analysis.
%
% outputs = soopt.writeStrengthGridAnalysis(result, projectCfg)
%
% This function is the persistence layer for the structure returned by:
%
%   soopt.analyzeStrengthGrid
%
% It does NOT recompute feasibility, Pareto optimality, monotonicity,
% inference, or proposal rankings.
%
% DEFAULT OUTPUT DIRECTORY
%
%   <projectCfg.outputRoot>/
%       static_optimization_configs/
%           grid_search_analysis/
%
% WRITTEN ARTIFACTS
%
%   strength_configuration_summary.csv
%   pareto_frontier.csv
%   strength_grid_plan.csv
%   next_configuration_proposals.csv
%   monotonicity_violations.csv
%   candidate_config_pool.csv
%   missing_config_combinations.csv
%   strength_feasibility_map.png       [when ExportFigure == true]
%   strength_grid_analysis.mat
%
% The MAT file contains:
%
%   analysisSnapshot
%
% Live graphics handles are removed before serialization. The snapshot also
% records projectCfg for provenance.
%
% NAME-VALUE OPTIONS
%
%   OutputDirectory
%       Optional explicit output directory. Default "" uses the canonical
%       grid_search_analysis location beneath projectCfg.outputRoot.
%
%   Overwrite
%       Logical scalar. Default false. When false, the function performs a
%       preflight check and refuses to modify the filesystem if any target
%       artifact already exists.
%
%   ExportFigure
%       Logical scalar. Default true.
%
%   FigureResolution
%       Positive finite scalar DPI. Default 200.
%
% FIGURE BEHAVIOR
%
% If result.Figure is a valid figure, that figure is exported without being
% closed or modified. Otherwise an invisible feasibility map is regenerated
% from result.Summary, exported, and closed.
%
% RETURN STRUCT
%
%   SchemaVersion
%   OutputDirectory
%   SummaryCsv
%   ParetoFrontierCsv
%   GridPlanCsv
%   ProposalsCsv
%   MonotonicityViolationsCsv
%   CandidateConfigPoolCsv
%   MissingConfigCombinationsCsv
%   FigurePng
%   AnalysisMat
%   FigureExported
%
% The function is intentionally NON-DESTRUCTIVE by default.

    %% Parse inputs

    parser = ...
        inputParser;

    parser.FunctionName = ...
        "soopt.writeStrengthGridAnalysis";

    addRequired(parser, ...
        "result", ...
        @(x) isstruct(x) && isscalar(x));

    addRequired(parser, ...
        "projectCfg", ...
        @(x) isstruct(x) && isscalar(x));

    addParameter(parser, ...
        "OutputDirectory", ...
        "", ...
        @(x) ...
            (ischar(x) && (isrow(x) || isempty(x))) || ...
            (isstring(x) && isscalar(x) && ~ismissing(x)));

    addParameter(parser, ...
        "Overwrite", ...
        false, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "ExportFigure", ...
        true, ...
        @(x) islogical(x) && isscalar(x));

    addParameter(parser, ...
        "FigureResolution", ...
        200, ...
        @(x) ...
            isnumeric(x) && ...
            isscalar(x) && ...
            isfinite(x) && ...
            x > 0);

    parse(parser, ...
        result, ...
        projectCfg, ...
        varargin{:});

    requestedOutputDirectory = ...
        string(parser.Results.OutputDirectory);

    overwrite = ...
        logical(parser.Results.Overwrite);

    exportFigure = ...
        logical(parser.Results.ExportFigure);

    figureResolution = ...
        double(parser.Results.FigureResolution);

    %% Validate result and project contract

    requiredResultFields = [
        "SchemaVersion"
        "ConfigPool"
        "Summary"
        "ParetoFrontier"
        "MonotonicityAudit"
        "PlanningAvailable"
        "PlanningStatus"
        "PlanningReason"
        "GridPlan"
        "Proposals"
        "Figure"
        "Axes"
        "PlotInfo"
    ];

    missingResultFields = ...
        requiredResultFields( ...
            ~isfield( ...
                result, ...
                cellstr(requiredResultFields)));

    assert(isempty(missingResultFields), ...
        "StrengthGridWrite:ResultFieldsMissing", ...
        "Analysis result is missing required fields: %s", ...
        strjoin(missingResultFields, ", "));

    assert(isfield(projectCfg, "outputRoot"), ...
        "StrengthGridWrite:OutputRootMissing", ...
        "projectCfg.outputRoot is required.");

    assert(istable(result.Summary), ...
        "StrengthGridWrite:InvalidSummary", ...
        "result.Summary must be a table.");

    assert(istable(result.ParetoFrontier), ...
        "StrengthGridWrite:InvalidParetoFrontier", ...
        "result.ParetoFrontier must be a table.");

    assert(istable(result.GridPlan), ...
        "StrengthGridWrite:InvalidGridPlan", ...
        "result.GridPlan must be a table.");

    assert(istable(result.Proposals), ...
        "StrengthGridWrite:InvalidProposals", ...
        "result.Proposals must be a table.");

    assert(isstruct(result.ConfigPool) && ...
            isscalar(result.ConfigPool) && ...
            isfield(result.ConfigPool, "Configurations") && ...
            isfield(result.ConfigPool, "MissingCombinations"), ...
        "StrengthGridWrite:InvalidConfigPool", ...
        "result.ConfigPool must contain Configurations and " + ...
        "MissingCombinations.");

    assert(istable(result.ConfigPool.Configurations), ...
        "StrengthGridWrite:InvalidConfigPool", ...
        "result.ConfigPool.Configurations must be a table.");

    assert(istable(result.ConfigPool.MissingCombinations), ...
        "StrengthGridWrite:InvalidConfigPool", ...
        "result.ConfigPool.MissingCombinations must be a table.");

    assert(isstruct(result.MonotonicityAudit) && ...
            isscalar(result.MonotonicityAudit) && ...
            isfield(result.MonotonicityAudit, "Violations") && ...
            istable(result.MonotonicityAudit.Violations), ...
        "StrengthGridWrite:InvalidMonotonicityAudit", ...
        "result.MonotonicityAudit.Violations must be a table.");

    %% Resolve output directory and artifact paths

    if strlength(requestedOutputDirectory) > 0

        outputDirectory = ...
            requestedOutputDirectory;

    else

        outputRoot = ...
            string(projectCfg.outputRoot);

        assert(isscalar(outputRoot) && ...
                ~ismissing(outputRoot) && ...
                strlength(outputRoot) > 0, ...
            "StrengthGridWrite:OutputRootMissing", ...
            "projectCfg.outputRoot must be nonempty.");

        outputDirectory = ...
            string(fullfile( ...
                outputRoot, ...
                "static_optimization_configs", ...
                "grid_search_analysis"));
    end

    summaryCsv = ...
        string(fullfile( ...
            outputDirectory, ...
            "strength_configuration_summary.csv"));

    paretoFrontierCsv = ...
        string(fullfile( ...
            outputDirectory, ...
            "pareto_frontier.csv"));

    gridPlanCsv = ...
        string(fullfile( ...
            outputDirectory, ...
            "strength_grid_plan.csv"));

    proposalsCsv = ...
        string(fullfile( ...
            outputDirectory, ...
            "next_configuration_proposals.csv"));

    monotonicityViolationsCsv = ...
        string(fullfile( ...
            outputDirectory, ...
            "monotonicity_violations.csv"));

    candidateConfigPoolCsv = ...
        string(fullfile( ...
            outputDirectory, ...
            "candidate_config_pool.csv"));

    missingConfigCombinationsCsv = ...
        string(fullfile( ...
            outputDirectory, ...
            "missing_config_combinations.csv"));

    figurePng = ...
        string(fullfile( ...
            outputDirectory, ...
            "strength_feasibility_map.png"));

    analysisMat = ...
        string(fullfile( ...
            outputDirectory, ...
            "strength_grid_analysis.mat"));

    requiredTargets = [
        summaryCsv
        paretoFrontierCsv
        gridPlanCsv
        proposalsCsv
        monotonicityViolationsCsv
        candidateConfigPoolCsv
        missingConfigCombinationsCsv
        analysisMat
    ];

    if exportFigure

        requiredTargets(end+1,1) = ...
            figurePng;
    end

    %% Non-destructive preflight

    if ~overwrite

        existingTargets = ...
            requiredTargets(isfile(requiredTargets));

        assert(isempty(existingTargets), ...
            "StrengthGridWrite:OutputExists", ...
            "One or more analysis artifacts already exist. " + ...
            "Use Overwrite=true to replace them:\n%s", ...
            strjoin(existingTargets, "\n"));
    end

    %% Create output directory only after successful preflight

    if ~isfolder(outputDirectory)

        mkdir(outputDirectory);
    end

    %% Write tabular artifacts

    writetable( ...
        result.Summary, ...
        summaryCsv);

    writetable( ...
        result.ParetoFrontier, ...
        paretoFrontierCsv);

    writetable( ...
        result.GridPlan, ...
        gridPlanCsv);

    writetable( ...
        result.Proposals, ...
        proposalsCsv);

    writetable( ...
        result.MonotonicityAudit.Violations, ...
        monotonicityViolationsCsv);

    writetable( ...
        result.ConfigPool.Configurations, ...
        candidateConfigPoolCsv);

    writetable( ...
        result.ConfigPool.MissingCombinations, ...
        missingConfigCombinationsCsv);

    %% Export figure

    figureExported = ...
        false;

    if exportFigure

        figureHandle = ...
            result.Figure;

        createdTemporaryFigure = ...
            false;

        if isempty(figureHandle) || ...
                ~isscalar(figureHandle) || ...
                ~isgraphics(figureHandle, "figure")

            [figureHandle, ~] = ...
                soopt.plotFeasibilityMap( ...
                    result.Summary, ...
                    "Visible", ...
                    "off");

            createdTemporaryFigure = ...
                true;
        end

        figureCleanup = ...
            onCleanup(@() ...
                localCloseTemporaryFigure( ...
                    figureHandle, ...
                    createdTemporaryFigure));

        exportgraphics( ...
            figureHandle, ...
            figurePng, ...
            "Resolution", ...
            figureResolution);

        figureExported = ...
            true;
    end

    %% Write serialization-safe MAT snapshot

    serializableResult = ...
        result;

    serializableResult.Figure = ...
        [];

    serializableResult.Axes = ...
        [];

    analysisSnapshot = struct;

    analysisSnapshot.SchemaVersion = ...
        1;

    analysisSnapshot.WrittenAt = ...
        string(datetime("now"));

    analysisSnapshot.OutputDirectory = ...
        outputDirectory;

    analysisSnapshot.Result = ...
        serializableResult;

    analysisSnapshot.ProjectConfig = ...
        projectCfg;

    save( ...
        analysisMat, ...
        "analysisSnapshot", ...
        "-v7.3");

    %% Return artifact paths

    outputs = struct;

    outputs.SchemaVersion = ...
        1;

    outputs.OutputDirectory = ...
        outputDirectory;

    outputs.SummaryCsv = ...
        summaryCsv;

    outputs.ParetoFrontierCsv = ...
        paretoFrontierCsv;

    outputs.GridPlanCsv = ...
        gridPlanCsv;

    outputs.ProposalsCsv = ...
        proposalsCsv;

    outputs.MonotonicityViolationsCsv = ...
        monotonicityViolationsCsv;

    outputs.CandidateConfigPoolCsv = ...
        candidateConfigPoolCsv;

    outputs.MissingConfigCombinationsCsv = ...
        missingConfigCombinationsCsv;

    if exportFigure

        outputs.FigurePng = ...
            figurePng;

    else

        outputs.FigurePng = ...
            "";
    end

    outputs.AnalysisMat = ...
        analysisMat;

    outputs.FigureExported = ...
        figureExported;
end


function localCloseTemporaryFigure(figureHandle, createdTemporaryFigure)

    if createdTemporaryFigure && ...
            isgraphics(figureHandle, "figure")

        close(figureHandle);
    end
end
