%% 0. Project setup

activeFile = string( ...
    matlab.desktop.editor.getActiveFilename);

examplesDirectory = ...
    string(fileparts(activeFile));

projectRoot = ...
    string(fileparts(examplesDirectory));

addpath(projectRoot);

projectCfg = load_project_config();

%% 1. Trial configuration

trialCfg = struct;

trialCfg.conditionDeg = 0;
trialCfg.trialNumber = 1;

trialCfg.lockWindow = ...
    [0.10, 0.35];

%% 2. Resolve Phase A motion

conditionTag = ...
    sprintf("%02ddeg", trialCfg.conditionDeg);

trialTag = ...
    sprintf("trial%02d", trialCfg.trialNumber);

phaseADirectory = fullfile( ...
    projectCfg.outputRoot, ...
    conditionTag, ...
    trialTag, ...
    "01_initialization_ik");

ikMotionFile = fullfile( ...
    phaseADirectory, ...
    sprintf( ...
        "%02ddeg_trial%02d_initialization_ik.mot", ...
        trialCfg.conditionDeg, ...
        trialCfg.trialNumber));

assert(isfile(ikMotionFile), ...
    "Initialization IK motion not found:\n%s", ...
    ikMotionFile);

qcDirectory = ...
    fullfile(phaseADirectory, "qc");

if ~isfolder(qcDirectory)
    mkdir(qcDirectory);
end

%% 3. Run filter sensitivity assessment

filterCfg = ...
    projectCfg.qc.lockExtractionFilter;

result = ...
    modelprep.assessCoordinateFilterSensitivity( ...
        ikMotionFile, ...
        filterCfg.assessmentCoordinates, ...
        trialCfg.lockWindow, ...
        "CandidateCutoffsHz", ...
            filterCfg.candidateCutoffsHz, ...
        "PrototypeOrder", ...
            filterCfg.prototypeOrder, ...
        "StabilityToleranceDeg", ...
            projectCfg.qc.lockExtraction.rotationToleranceDeg, ...
        "MinimumWindowSamples", ...
            projectCfg.qc.lockExtraction.minimumSamples);

disp(result.Summary);

%% 4. Save summary

summaryFile = fullfile( ...
    qcDirectory, ...
    "lock_filter_sensitivity_summary.csv");

writetable( ...
    result.Summary, ...
    summaryFile);

fprintf( ...
    "\nSaved filter sensitivity summary:\n%s\n", ...
    summaryFile);

%% 5. Plot candidate filters

plotWindow = ...
    filterCfg.plotWindow;

plotMask = ...
    result.Time >= plotWindow(1) & ...
    result.Time <= plotWindow(2);

for iCoordinate = ...
        1:numel(result.Coordinates)

    coordinate = ...
        result.Coordinates(iCoordinate);

    figure( ...
        "Name", ...
        "Filter sensitivity - " + coordinate, ...
        "Color", ...
        "w");

    hold on;

    plot( ...
        result.Time(plotMask), ...
        result.RawDataDeg( ...
            plotMask, ...
            iCoordinate), ...
        "LineWidth", ...
        1.0, ...
        "DisplayName", ...
        "Raw");

    for iCutoff = ...
            1:numel(result.CandidateCutoffsHz)

        cutoffHz = ...
            result.CandidateCutoffsHz(iCutoff);

        filtered = ...
            result.FilteredDataDeg( ...
                :, ...
                iCoordinate, ...
                iCutoff);

        plot( ...
            result.Time(plotMask), ...
            filtered(plotMask), ...
            "LineWidth", ...
            1.2, ...
            "DisplayName", ...
            sprintf("%.1f Hz", cutoffHz));

    end

    xline( ...
        trialCfg.lockWindow(1), ...
        "--", ...
        "Lock start", ...
        "HandleVisibility", ...
        "off");

    xline( ...
        trialCfg.lockWindow(2), ...
        "--", ...
        "Lock end", ...
        "HandleVisibility", ...
        "off");

    grid on;

    xlabel("Time (s)");
    ylabel("Angle (deg)");

    title( ...
        coordinate, ...
        "Interpreter", ...
        "none");

    legend( ...
        "Location", ...
        "best");

    hold off;

end