%% assess_initialization_ik_psd.m
% Diagnostic script for evaluating frequency content of selected
% initialization-IK coordinates before Model B lock extraction.
%
% This script does NOT modify pipeline data.
%
% Primary questions:
%   1. Are yaw1/yaw2 dominated by low-frequency physical motion or
%      higher-frequency IK noise?
%   2. How do yaw1/yaw2 compare with roll1/roll2?
%   3. What fraction of signal power lies above candidate/reporting
%      frequencies?
%
% Trial identity and pipeline paths are resolved through:
%
%   pipeline.resolveTrialContext
%
% Coordinates and production cutoff candidates are taken from:
%
%   projectCfg.qc.lockExtractionFilter
%
% Historical 5- and 10-Hz PSD reporting thresholds are retained as
% diagnostic-only frequencies. They are not production filter candidates.
%
% Outputs:
%   <trial>/01_initialization_ik/qc/initialization_ik_psd_summary.csv
%   <trial>/01_initialization_ik/qc/initialization_ik_psd_spectrum.csv
%   interactive raw-trajectory, PSD, and cumulative-power figures

clear;
clc;
dbstop if error

%% SECTION 0 — PROJECT CONFIGURATION

projectCfg = ...
    load_project_config();

fprintf( ...
    "Project root:\n%s\n", ...
    projectCfg.projectRoot);

%% SECTION 1 — SELECT TRIAL

conditionDeg = 0;
trialNumber = 1;

trial = ...
    pipeline.resolveTrialContext( ...
        projectCfg, ...
        conditionDeg, ...
        trialNumber);

fprintf( ...
    "Resolved %s.\n", ...
    trial.DisplayName);

%% SECTION 2 — RESOLVE PRODUCTION FILTER SETTINGS AND PATHS

filterCfg = ...
    projectCfg.qc.lockExtractionFilter;

coordinates = ...
    string(filterCfg.assessmentCoordinates(:));

productionCandidateCutoffsHz = ...
    double(filterCfg.candidateCutoffsHz(:));

productionCutoffHz = ...
    double(filterCfg.selectedCutoffHz);

% Retain the original exploratory 5- and 10-Hz PSD reporting thresholds.
% These remain diagnostic-only and are deliberately not added to the
% project-wide filter candidate configuration.
additionalPsdReportingCutoffsHz = [
    5
    10
];

reportingCutoffsHz = ...
    unique( ...
        [ ...
            productionCandidateCutoffsHz
            additionalPsdReportingCutoffsHz
        ], ...
        "stable");

ikMotionFile = ...
    trial.Paths.Initialization.IkMotionFile;

qcDirectory = ...
    trial.Paths.Initialization.QcDirectory;

assert(isfile(ikMotionFile), ...
    "IkPsdAssessment:InitializationIkMissing", ...
    "Initialization IK motion file was not found:\n%s", ...
    ikMotionFile);

if ~isfolder(qcDirectory)
    mkdir(qcDirectory);
end

fprintf( ...
    "Initialization IK file:\n%s\n\n", ...
    ikMotionFile);

fprintf( ...
    "Assessment coordinates: %s\n", ...
    strjoin( ...
        coordinates, ...
        ", "));

fprintf( ...
    "Production candidate cutoffs: %s Hz\n", ...
    strjoin( ...
        string(productionCandidateCutoffsHz), ...
        ", "));

fprintf( ...
    "Validated production cutoff: %.3f Hz\n", ...
    productionCutoffHz);

fprintf( ...
    "PSD-only reporting cutoffs: %s Hz\n\n", ...
    strjoin( ...
        string(reportingCutoffsHz), ...
        ", "));

%% SECTION 3 — READ INITIALIZATION IK MOTION

ikMotion = ...
    opensimio.readMot( ...
        ikMotionFile);

assert(isstruct(ikMotion), ...
    "IkPsdAssessment:UnexpectedMotionType", ...
    "opensimio.readMot did not return the expected struct.");

requiredFields = [
    "Labels"
    "Data"
    "Time"
    "InDegrees"
];

for iField = 1:numel(requiredFields)

    fieldName = ...
        requiredFields(iField);

    assert(isfield( ...
            ikMotion, ...
            fieldName), ...
        "IkPsdAssessment:MotionFieldMissing", ...
        "IK motion struct is missing required field '%s'.", ...
        fieldName);
end

labels = ...
    reshape( ...
        string(ikMotion.Labels), ...
        1, []);

data = ...
    ikMotion.Data;

time = ...
    ikMotion.Time;

assert(isnumeric(data) && ...
    ismatrix(data), ...
    "IkPsdAssessment:InvalidMotionData", ...
    "ikMotion.Data must be a two-dimensional numeric array.");

assert(size(data, 2) == ...
        numel(labels), ...
    "IkPsdAssessment:MotionLabelCountMismatch", ...
    "Number of columns in ikMotion.Data (%d) does not match " + ...
    "number of labels (%d).", ...
    size(data, 2), ...
    numel(labels));

assert(numel(time) == ...
        size(data, 1), ...
    "IkPsdAssessment:MotionTimeCountMismatch", ...
    "Length of ikMotion.Time does not match number of data rows.");

assert(all(isfinite(time)), ...
    "IkPsdAssessment:NonfiniteTime", ...
    "Time vector contains nonfinite values.");

assert(all(diff(time) > 0), ...
    "IkPsdAssessment:NonmonotonicTime", ...
    "Time vector must be strictly increasing.");

% These diagnostic coordinates are rotational, so report everything
% consistently in degrees.
if ~ikMotion.InDegrees

    warning( ...
        "IkPsdAssessment:RadiansConvertedToDegrees", ...
        "IK file reports InDegrees=false. Selected rotational " + ...
        "coordinates will be converted from radians to degrees " + ...
        "for the PSD assessment.");
end

%% SECTION 4 — DETERMINE SAMPLING FREQUENCY

dt = ...
    diff(time);

medianDt = ...
    median(dt);

Fs = ...
    1 / medianDt;

numSamples = ...
    size(data, 1);

fprintf( ...
    "Samples:              %d\n", ...
    numSamples);

fprintf( ...
    "Duration:             %.3f s\n", ...
    time(end) - time(1));

fprintf( ...
    "Median sample dt:     %.6f s\n", ...
    medianDt);

fprintf( ...
    "Estimated Fs:         %.3f Hz\n", ...
    Fs);

fprintf( ...
    "Maximum dt deviation: %.3e s\n\n", ...
    max(abs(dt - medianDt)));

% Require approximately uniform sampling for Welch PSD.
relativeDtVariation = ...
    max(abs(dt - medianDt)) / ...
    medianDt;

assert(relativeDtVariation < 1e-3, ...
    "IkPsdAssessment:NonuniformSampling", ...
    "Time samples are not sufficiently uniform for direct PSD analysis.");

%% SECTION 5 — VALIDATE REQUESTED COORDINATES

for iCoordinate = 1:numel(coordinates)

    coordinate = ...
        coordinates(iCoordinate);

    matches = ...
        find(labels == coordinate);

    assert(~isempty(matches), ...
        "IkPsdAssessment:CoordinateMissing", ...
        "Coordinate '%s' was not found in the IK motion file.", ...
        coordinate);

    assert(numel(matches) == 1, ...
        "IkPsdAssessment:CoordinateDuplicate", ...
        "Coordinate '%s' occurs more than once in the IK motion file.", ...
        coordinate);
end

%% SECTION 6 — CONFIGURE WELCH PSD

% Preserve the original diagnostic choice of approximately four-second
% Welch segments. This is a PSD implementation parameter rather than a
% production filter setting.
desiredSegmentDurationSec = ...
    4.0;

segmentSamples = ...
    round( ...
        desiredSegmentDurationSec * ...
        Fs);

% Do not allow the segment length to exceed the available trajectory.
segmentSamples = ...
    min( ...
        segmentSamples, ...
        numSamples);

% Preserve the original minimum segment length.
segmentSamples = ...
    max( ...
        segmentSamples, ...
        32);

window = ...
    hann( ...
        segmentSamples, ...
        "periodic");

noverlap = ...
    floor( ...
        segmentSamples / 2);

% Preserve the original zero-padding policy.
nfft = ...
    max( ...
        1024, ...
        2^nextpow2(segmentSamples));

fprintf( ...
    "Welch segment length: %d samples (%.2f s)\n", ...
    segmentSamples, ...
    segmentSamples / Fs);

fprintf( ...
    "Welch overlap:        %d samples\n", ...
    noverlap);

fprintf( ...
    "FFT length:           %d\n\n", ...
    nfft);

%% SECTION 7 — CALCULATE PSD AND SPECTRAL METRICS

summaryRows = ...
    table;

spectrumRows = ...
    table;

for iCoordinate = 1:numel(coordinates)

    coordinate = ...
        coordinates(iCoordinate);

    columnIndex = ...
        find( ...
            labels == coordinate, ...
            1);

    raw = ...
        data(:, columnIndex);

    assert(all(isfinite(raw)), ...
        "IkPsdAssessment:NonfiniteCoordinate", ...
        "Coordinate '%s' contains nonfinite values.", ...
        coordinate);

    % Convert rotational coordinate values to degrees if necessary.
    if ~ikMotion.InDegrees
        raw = rad2deg(raw);
    end

    % Remove mean and linear trend before PSD calculation.
    signal = ...
        detrend( ...
            raw, ...
            1);

    [pxx, frequency] = ...
        pwelch( ...
            signal, ...
            window, ...
            noverlap, ...
            nfft, ...
            Fs, ...
            "psd");

    totalPower = ...
        trapz( ...
            frequency, ...
            pxx);

    cumulativePower = ...
        cumtrapz( ...
            frequency, ...
            pxx);

    if totalPower > 0

        cumulativeFraction = ...
            cumulativePower ./ ...
            totalPower;

    else

        cumulativeFraction = ...
            zeros( ...
                size(cumulativePower));
    end

    % Frequency below which 95% of spectral power occurs.
    idx95 = ...
        find( ...
            cumulativeFraction >= 0.95, ...
            1, ...
            "first");

    if isempty(idx95)

        f95 = ...
            NaN;

    else

        f95 = ...
            frequency(idx95);
    end

    %% Time-domain metrics

    rawRangeDeg = ...
        range(raw);

    rawStdDeg = ...
        std(raw);

    detrendedStdDeg = ...
        std(signal);

    row = ...
        table( ...
            coordinate, ...
            rawRangeDeg, ...
            rawStdDeg, ...
            detrendedStdDeg, ...
            f95, ...
            'VariableNames', { ...
                'Coordinate', ...
                'RawRangeDeg', ...
                'RawStdDeg', ...
                'DetrendedStdDeg', ...
                'Frequency95PowerHz'});

    %% Spectral power above reporting thresholds

    for iCutoff = 1:numel(reportingCutoffsHz)

        cutoffHz = ...
            reportingCutoffsHz(iCutoff);

        highMask = ...
            frequency >= cutoffHz;

        highPower = ...
            trapz( ...
                frequency(highMask), ...
                pxx(highMask));

        if totalPower > 0

            fractionAbove = ...
                highPower / ...
                totalPower;

        else

            fractionAbove = ...
                NaN;
        end

        variableName = ...
            sprintf( ...
                "PowerAbove_%gpct", ...
                cutoffHz);

        variableName = ...
            matlab.lang.makeValidName( ...
                variableName);

        row.(variableName) = ...
            fractionAbove * 100;
    end

    summaryRows = [
        summaryRows
        row
    ]; %#ok<AGROW>

    %% Full PSD spectrum for later inspection

    spectrumTable = ...
        table( ...
            repmat( ...
                coordinate, ...
                numel(frequency), ...
                1), ...
            frequency, ...
            pxx, ...
            cumulativeFraction, ...
            'VariableNames', { ...
                'Coordinate', ...
                'FrequencyHz', ...
                'PSD', ...
                'CumulativePowerFraction'});

    spectrumRows = [
        spectrumRows
        spectrumTable
    ]; %#ok<AGROW>
end

%% SECTION 8 — DISPLAY SUMMARY

fprintf( ...
    "\nPSD summary:\n\n");

disp(summaryRows);

%% SECTION 9 — PLOT RAW COORDINATE TRAJECTORIES

figure( ...
    "Name", ...
        "Initialization IK - Out-of-plane coordinates", ...
    "Color", ...
        "w");

tiledlayout( ...
    2, ...
    2);

for iCoordinate = 1:numel(coordinates)

    coordinate = ...
        coordinates(iCoordinate);

    columnIndex = ...
        find( ...
            labels == coordinate, ...
            1);

    raw = ...
        data(:, columnIndex);

    if ~ikMotion.InDegrees
        raw = rad2deg(raw);
    end

    nexttile;

    plot( ...
        time, ...
        raw, ...
        "LineWidth", ...
            1);

    grid on;

    xlabel("Time (s)");
    ylabel("Angle (deg)");

    title( ...
        coordinate, ...
        "Interpreter", ...
            "none");
end

sgtitle( ...
    "Initialization IK coordinate trajectories");

%% SECTION 10 — PLOT POWER SPECTRAL DENSITIES

figure( ...
    "Name", ...
        "Initialization IK - Coordinate PSD", ...
    "Color", ...
        "w");

tiledlayout( ...
    2, ...
    2);

for iCoordinate = 1:numel(coordinates)

    coordinate = ...
        coordinates(iCoordinate);

    rows = ...
        spectrumRows.Coordinate == ...
        coordinate;

    frequency = ...
        spectrumRows.FrequencyHz(rows);

    pxx = ...
        spectrumRows.PSD(rows);

    nexttile;

    semilogy( ...
        frequency, ...
        pxx, ...
        "LineWidth", ...
            1);

    hold on;

    xline( ...
        productionCutoffHz, ...
        "--", ...
        "Production cutoff", ...
        "HandleVisibility", ...
            "off");

    hold off;

    grid on;

    xlabel("Frequency (Hz)");
    ylabel("PSD (deg^2/Hz)");

    title( ...
        coordinate, ...
        "Interpreter", ...
            "none");

    % Preserve the original display range.
    xlim([ ...
        0 ...
        min(20, Fs/2) ...
    ]);
end

sgtitle( ...
    "Welch PSD of detrended initialization IK coordinates");

%% SECTION 11 — PLOT CUMULATIVE SPECTRAL POWER

figure( ...
    "Name", ...
        "Initialization IK - Cumulative spectral power", ...
    "Color", ...
        "w");

tiledlayout( ...
    2, ...
    2);

for iCoordinate = 1:numel(coordinates)

    coordinate = ...
        coordinates(iCoordinate);

    rows = ...
        spectrumRows.Coordinate == ...
        coordinate;

    frequency = ...
        spectrumRows.FrequencyHz(rows);

    cumulativePower = ...
        spectrumRows. ...
            CumulativePowerFraction(rows);

    nexttile;

    plot( ...
        frequency, ...
        cumulativePower * 100, ...
        "LineWidth", ...
            1);

    hold on;

    yline( ...
        95, ...
        "--");

    xline( ...
        productionCutoffHz, ...
        "--", ...
        "Production cutoff", ...
        "HandleVisibility", ...
            "off");

    hold off;

    grid on;

    xlabel("Frequency (Hz)");
    ylabel("Cumulative power (%)");

    title( ...
        coordinate, ...
        "Interpreter", ...
            "none");

    ylim([0 100]);

    xlim([ ...
        0 ...
        min(20, Fs/2) ...
    ]);
end

sgtitle( ...
    "Cumulative spectral power");

%% SECTION 12 — SAVE DIAGNOSTIC TABLES

summaryFile = ...
    string(fullfile( ...
        qcDirectory, ...
        "initialization_ik_psd_summary.csv"));

spectrumFile = ...
    string(fullfile( ...
        qcDirectory, ...
        "initialization_ik_psd_spectrum.csv"));

writetable( ...
    summaryRows, ...
    summaryFile);

writetable( ...
    spectrumRows, ...
    spectrumFile);

fprintf( ...
    "\nSaved PSD summary:\n%s\n", ...
    summaryFile);

fprintf( ...
    "\nSaved full PSD spectrum:\n%s\n", ...
    spectrumFile);
