%% assess_single_trial_lock_filter.m
% Diagnostic assessment of lock-extraction filter sensitivity for one trial.
%
% This script is intentionally diagnostic rather than a pipeline stage. It
% uses the same canonical trial context and Model-B lock-window/configuration
% as the production Process-2 worker so the assessment cannot silently drift
% from the batch workflow.
%
% Outputs:
%   <trial>/01_initialization_ik/qc/lock_filter_sensitivity_summary.csv
%   interactive cutoff-comparison figures

clear;
clc;
dbstop if error

%% SECTION 0 — PROJECT CONFIGURATION

projectCfg = ...
    load_project_config();

fprintf( ...
    "Project root:\n%s\n", ...
    projectCfg.projectRoot);

%% SECTION 1 — SELECT TRIAL

conditionDeg = 0;
trialNumber = 1;

trial = ...
    pipeline.resolveTrialContext( ...
        projectCfg, ...
        conditionDeg, ...
        trialNumber);

fprintf( ...
    "Resolved %s.\n", ...
    trial.DisplayName);

%% SECTION 2 — RESOLVE PRODUCTION FILTER SETTINGS

lockWindowSec = ...
    projectCfg.pipeline.modelB.lockWindowSec;

filterCfg = ...
    projectCfg.qc.lockExtractionFilter;

lockExtractionCfg = ...
    projectCfg.qc.lockExtraction;

ikMotionFile = ...
    trial.Paths.Initialization.IkMotionFile;

qcDirectory = ...
    trial.Paths.Initialization.QcDirectory;

assert(isfile(ikMotionFile), ...
    "LockFilterAssessment:InitializationIkMissing", ...
    "Initialization IK motion was not found:\n%s", ...
    ikMotionFile);

if ~isfolder(qcDirectory)
    mkdir(qcDirectory);
end

fprintf( ...
    "Initialization IK motion:\n%s\n", ...
    ikMotionFile);

fprintf( ...
    "Lock-extraction window: %.3f to %.3f s\n", ...
    lockWindowSec(1), ...
    lockWindowSec(2));

fprintf( ...
    "Assessment coordinates: %s\n", ...
    strjoin( ...
        string(filterCfg.assessmentCoordinates(:)), ...
        ", "));

fprintf( ...
    "Candidate cutoffs: %s Hz\n", ...
    strjoin( ...
        string(filterCfg.candidateCutoffsHz(:)), ...
        ", "));

fprintf( ...
    "Production cutoff: %.3f Hz\n", ...
    filterCfg.selectedCutoffHz);

%% SECTION 3 — RUN FILTER-SENSITIVITY ASSESSMENT

result = ...
    modelprep.assessCoordinateFilterSensitivity( ...
        ikMotionFile, ...
        filterCfg.assessmentCoordinates, ...
        lockWindowSec, ...
        "CandidateCutoffsHz", ...
            filterCfg.candidateCutoffsHz, ...
        "PrototypeOrder", ...
            filterCfg.prototypeOrder, ...
        "StabilityToleranceDeg", ...
            lockExtractionCfg.rotationToleranceDeg, ...
        "MinimumWindowSamples", ...
            lockExtractionCfg.minimumSamples);

disp(result.Summary);

%% SECTION 4 — SAVE SUMMARY

summaryFile = ...
    string(fullfile( ...
        qcDirectory, ...
        "lock_filter_sensitivity_summary.csv"));

writetable( ...
    result.Summary, ...
    summaryFile);

fprintf( ...
    "\nSaved filter sensitivity summary:\n%s\n", ...
    summaryFile);

%% SECTION 5 — PLOT CANDIDATE FILTERS

plotWindowSec = ...
    filterCfg.plotWindow;

plotMask = ...
    result.Time >= plotWindowSec(1) & ...
    result.Time <= plotWindowSec(2);

assert(any(plotMask), ...
    "LockFilterAssessment:PlotWindowEmpty", ...
    "Configured diagnostic plot window [%.3f, %.3f] s contains " + ...
    "no samples in the initialization IK motion.", ...
    plotWindowSec(1), ...
    plotWindowSec(2));

for iCoordinate = 1:numel(result.Coordinates)

    coordinate = ...
        result.Coordinates(iCoordinate);

    figure( ...
        "Name", ...
            "Filter sensitivity - " + coordinate, ...
        "Color", ...
            "w");

    hold on;

    plot( ...
        result.Time(plotMask), ...
        result.RawDataDeg( ...
            plotMask, ...
            iCoordinate), ...
        "LineWidth", ...
            1.0, ...
        "DisplayName", ...
            "Raw");

    for iCutoff = 1:numel(result.CandidateCutoffsHz)

        cutoffHz = ...
            result.CandidateCutoffsHz(iCutoff);

        filtered = ...
            result.FilteredDataDeg( ...
                :, ...
                iCoordinate, ...
                iCutoff);

        displayName = ...
            sprintf("%.1f Hz", cutoffHz);

        if abs(cutoffHz - filterCfg.selectedCutoffHz) < ...
                10 * eps(max(1, abs(filterCfg.selectedCutoffHz)))

            displayName = ...
                displayName + ...
                " (production)";
        end

        plot( ...
            result.Time(plotMask), ...
            filtered(plotMask), ...
            "LineWidth", ...
                1.2, ...
            "DisplayName", ...
                displayName);
    end

    xline( ...
        lockWindowSec(1), ...
        "--", ...
        "Lock start", ...
        "HandleVisibility", ...
        "off");

    xline( ...
        lockWindowSec(2), ...
        "--", ...
        "Lock end", ...
        "HandleVisibility", ...
        "off");

    grid on;

    xlabel("Time (s)");
    ylabel("Angle (deg)");

    title( ...
        coordinate, ...
        "Interpreter", ...
        "none");

    legend( ...
        "Location", ...
        "best");

    hold off;
end
