%% example_audit_locked_coordinates.m

clear;
clc;

projectCfg = load_project_config();

finalIkMotionFile = ...
    "C:\path\to\final_ik.mot";

lockValuesFile = ...
    "C:\path\to\modelB_lock_values.csv";

lockValues = readtable( ...
    lockValuesFile, ...
    "TextType", "string");

qc = projectCfg.qc.lockAudit;

report = modelprep.auditLockedCoordinates( ...
    finalIkMotionFile, ...
    lockValues, ...
    "ModelInput", projectCfg.kinematicBaseModel, ...
    "Statistic", qc.statistic, ...
    "RotationRangeToleranceDeg", ...
        qc.rotationRangeToleranceDeg, ...
    "TranslationRangeToleranceM", ...
        qc.translationRangeToleranceM, ...
    "OtherRangeToleranceSI", ...
        qc.otherRangeToleranceSI, ...
    "RotationMatchToleranceDeg", ...
        qc.rotationMatchToleranceDeg, ...
    "TranslationMatchToleranceM", ...
        qc.translationMatchToleranceM, ...
    "OtherMatchToleranceSI", ...
        qc.otherMatchToleranceSI, ...
    "MinimumSamples", qc.minimumSamples, ...
    "RequirePass", qc.requirePass);

disp(report.Table);

writetable( ...
    report.Table, ...
    "locked_coordinate_audit.csv");
