%% example_hsf_trial.m
% Generate a head-support-force file for one corrected final-IK trial.

toolkitRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(toolkitRoot);

modelFile = ...
    "C:\path\to\trial01_static_optimization_model.osim";

ikMotionFile = ...
    "C:\path\to\trial01_final_ik.mot";

outputDirectory = ...
    "C:\path\to\trial01\04_hsf";

conditionAngleDeg = 30;

% Example lift-off interval. Replace with the verified trial interval.
offIntervals = [5.20, 14.75];

result = hsf.generateTrial( ...
    modelFile, ...
    ikMotionFile, ...
    outputDirectory, ...
    conditionAngleDeg, ...
    "BodyName", "skull", ...
    "SkullMassKg", 1.1704014720812095, ...
    "GravityY", -9.80665, ...
    "TargetRateHz", 1000, ...
    "OffIntervals", offIntervals, ...
    "RampDuration", 0.1, ...
    "RampShape", "halfcosine", ...
    "RadialSign", 1, ...
    "AzimuthConvention", "x_cos_z_sin", ...
    "ForcePrefix", "ground_force_1_v", ...
    "PointPrefix", "ground_force_1_p", ...
    "IncludeTorque", false);

disp(result.ForceComponents);
disp(result.Validation);

fprintf("HSF motion file:\n%s\n", result.OutputMotFile);
fprintf("Skull CoM position file:\n%s\n", ...
    result.BodyKinematics.PositionFile);
