%% example_modelprep_usage.m

toolkitRoot = fileparts(fileparts(mfilename("fullpath")));
addpath(toolkitRoot);

baseModel = "C:\path\to\infant_4mo_scaled_base.osim";
initializationModel = ...
    "C:\path\to\generated\trial01_initialization.osim";

%% Model A: all coordinates unlocked, constraints enabled

initializationResult = modelprep.buildInitializationModel( ...
    baseModel, initializationModel);

%% After initialization IK, extract locking values

initialIkMotion = ...
    "C:\path\to\results\trial01_initial_ik.mot";

groups = modelprep.coordinateGroups();

lockValues = modelprep.extractStableCoordinateValues( ...
    initialIkMotion, ...
    initializationModel, ...
    groups.FinalIkLocked, ...
    [0.00, 0.25], ...
    "Method", "median", ...
    "RequireStable", false);

disp(lockValues);

%% Model B: constrained final IK

lockedIkModel = ...
    "C:\path\to\generated\trial01_locked_ik.osim";

lockedResult = modelprep.buildLockedIkModel( ...
    baseModel, lockValues, lockedIkModel);

modelprep.validateModelConfiguration( ...
    lockedIkModel, ...
    "ExpectedLocked", groups.FinalIkLocked, ...
    "ExpectedUnlocked", groups.Sagittal, ...
    "ExpectedConstraintsEnforced", true);

%% Model C: constraints off, all out-of-plane values locked

finalIkMotion = ...
    "C:\path\to\results\trial01_final_ik.mot";

soModel = ...
    "C:\path\to\generated\trial01_static_optimization.osim";

soResult = modelprep.buildStaticOptimizationModel( ...
    lockedIkModel, finalIkMotion, soModel);

modelprep.validateModelConfiguration( ...
    soModel, ...
    "ExpectedLocked", groups.StaticOptimizationLocked, ...
    "ExpectedUnlocked", groups.Sagittal, ...
    "ExpectedConstraintsEnforced", false);
