%% example_modelprep_usage.m
% Focused demonstration of the low-level +modelprep API.
%
% This script is NOT an alternate production pipeline.
%
% It uses:
%   - a canonical trial resolved through pipeline.resolveTrialContext();
%   - existing Process-1 initialization-IK motion;
%   - existing Process-2 final-IK motion;
%   - the current project filtering/lock-extraction configuration.
%
% Demonstration Models A/B/C are written to a unique temporary directory so
% canonical project outputs are never modified.
%
% Prerequisites:
%   - Process 1 has completed for the selected trial.
%   - Process 2 has completed for the selected trial.

clear;
clc;
dbstop if error

%% SECTION 0 — PROJECT CONFIGURATION

projectCfg = ...
    load_project_config();

%% SECTION 1 — SELECT AND RESOLVE A TRIAL

conditionDeg = 0;
trialNumber = 1;

trial = ...
    pipeline.resolveTrialContext( ...
        projectCfg, ...
        conditionDeg, ...
        trialNumber);

groups = ...
    modelprep.coordinateGroups();

baseModelFile = ...
    trial.Inputs.KinematicBaseModel;

initialIkMotionFile = ...
    trial.Paths.Initialization.IkMotionFile;

finalIkMotionFile = ...
    trial.Paths.ModelB.FinalIkMotionFile;

assert(isfile(baseModelFile), ...
    "ModelprepExample:BaseModelMissing", ...
    "Kinematic base model was not found:\n%s", ...
    baseModelFile);

assert(isfile(initialIkMotionFile), ...
    "ModelprepExample:InitializationIkMissing", ...
    "Initialization IK motion was not found:\n%s\n" + ...
    "Run Process 1 for this trial first.", ...
    initialIkMotionFile);

assert(isfile(finalIkMotionFile), ...
    "ModelprepExample:FinalIkMissing", ...
    "Final IK motion was not found:\n%s\n" + ...
    "Run Process 2 for this trial first.", ...
    finalIkMotionFile);

fprintf( ...
    "Using %s.\n", ...
    trial.DisplayName);

%% SECTION 2 — CREATE AN ISOLATED DEMONSTRATION WORKSPACE

exampleDirectory = ...
    string(tempname);

mkdir(exampleDirectory);

modelAFile = ...
    string(fullfile( ...
        exampleDirectory, ...
        trial.TrialStem + ...
        "_example_modelA.osim"));

modelBFile = ...
    string(fullfile( ...
        exampleDirectory, ...
        trial.TrialStem + ...
        "_example_modelB.osim"));

modelCFile = ...
    string(fullfile( ...
        exampleDirectory, ...
        trial.TrialStem + ...
        "_example_modelC.osim"));

fprintf( ...
    "Example outputs will be written only to:\n%s\n", ...
    exampleDirectory);

%% SECTION 3 — MODEL A
% All coordinates unlocked; coordinate-coupler constraints enabled.

modelAResult = ...
    modelprep.buildInitializationModel( ...
        baseModelFile, ...
        modelAFile);

allModelACoordinates = ...
    string( ...
        modelAResult.Inspection. ...
        Coordinates.Coordinate);

modelAValidation = ...
    modelprep.validateModelConfiguration( ...
        modelAFile, ...
        "ExpectedUnlocked", ...
            allModelACoordinates, ...
        "ExpectedConstraintsEnforced", ...
            true);

assert(modelAValidation.Passed, ...
    "ModelprepExample:ModelAValidationFailed", ...
    "Model A did not satisfy the expected configuration.");

fprintf( ...
    "Model A created and validated:\n%s\n", ...
    modelAFile);

%% SECTION 4 — PREPARE THE LOCK-EXTRACTION MOTION
% Mirror the production Model-B filtering policy, but keep the filtered
% motion in memory rather than writing another pipeline artifact.

lockWindowSec = ...
    double( ...
        projectCfg.pipeline. ...
        modelB.lockWindowSec(:)).';

filterCfg = ...
    projectCfg.qc.lockExtractionFilter;

if filterCfg.enabled

    filterResult = ...
        modelprep.filterCoordinateMotion( ...
            initialIkMotionFile, ...
            filterCfg.filterCoordinates, ...
            "CutoffHz", ...
                filterCfg.selectedCutoffHz, ...
            "PrototypeOrder", ...
                filterCfg.prototypeOrder, ...
            "AuditWindow", ...
                lockWindowSec);

    lockExtractionMotion = ...
        filterResult.Motion;

    fprintf( ...
        "Applied the configured %.3f-Hz lock-extraction filter " + ...
        "to: %s\n", ...
        filterCfg.selectedCutoffHz, ...
        strjoin( ...
            string(filterCfg.filterCoordinates(:)), ...
            ", "));

else

    filterResult = ...
        struct;

    lockExtractionMotion = ...
        opensimio.readMot( ...
            initialIkMotionFile);

    fprintf( ...
        "Lock-extraction filtering is disabled in project configuration.\n");
end

%% SECTION 5 — EXTRACT MODEL-B LOCK VALUES

lockCfg = ...
    projectCfg.qc.lockExtraction;

lockValues = ...
    modelprep.extractStableCoordinateValues( ...
        lockExtractionMotion, ...
        modelAFile, ...
        groups.FinalIkLocked, ...
        lockWindowSec, ...
        "Method", ...
            lockCfg.statistic, ...
        "RotationToleranceDeg", ...
            lockCfg.rotationToleranceDeg, ...
        "TranslationToleranceM", ...
            lockCfg.translationToleranceM, ...
        "OtherTolerance", ...
            lockCfg.otherToleranceSI, ...
        "RequireStable", ...
            lockCfg.requireStable, ...
        "MinimumSamples", ...
            lockCfg.minimumSamples);

disp(lockValues);

%% SECTION 6 — MODEL B
% Root + independent out-of-plane coordinates locked.
% Dependent coordinates remain governed by enabled couplers.

modelBResult = ...
    modelprep.buildLockedIkModel( ...
        baseModelFile, ...
        lockValues, ...
        modelBFile, ...
        "CoordinateNames", ...
            groups.FinalIkLocked, ...
        "RequireStable", ...
            lockCfg.requireStable);

allModelBCoordinates = ...
    string( ...
        modelBResult.Inspection. ...
        Coordinates.Coordinate);

modelBUnlocked = ...
    setdiff( ...
        allModelBCoordinates, ...
        string(groups.FinalIkLocked), ...
        "stable");

modelBValidation = ...
    modelprep.validateModelConfiguration( ...
        modelBFile, ...
        "ExpectedLocked", ...
            groups.FinalIkLocked, ...
        "ExpectedUnlocked", ...
            modelBUnlocked, ...
        "ExpectedConstraintsEnforced", ...
            true);

assert(modelBValidation.Passed, ...
    "ModelprepExample:ModelBValidationFailed", ...
    "Model B did not satisfy the expected configuration.");

fprintf( ...
    "Model B created and validated:\n%s\n", ...
    modelBFile);

%% SECTION 7 — MODEL C
% Coordinate couplers disabled.
% Root + all out-of-plane coordinates locked.
% Sagittal coordinates remain unlocked.

finalIkMotion = ...
    opensimio.readMot( ...
        finalIkMotionFile);

configuredTimeRange = ...
    projectCfg.pipeline. ...
    staticOptimizationPrep.timeRangeSec;

if isempty(configuredTimeRange)

    modelCTimeWindow = [
        finalIkMotion.Time(1)
        finalIkMotion.Time(end)
    ].';

else

    modelCTimeWindow = ...
        double( ...
            configuredTimeRange(:)).';
end

lockAuditCfg = ...
    projectCfg.qc.lockAudit;

modelCResult = ...
    modelprep.buildStaticOptimizationModel( ...
        modelBFile, ...
        finalIkMotionFile, ...
        modelCFile, ...
        "TimeWindow", ...
            modelCTimeWindow, ...
        "RotationToleranceDeg", ...
            lockAuditCfg.rotationRangeToleranceDeg, ...
        "TranslationToleranceM", ...
            lockAuditCfg.translationRangeToleranceM, ...
        "RequireStable", ...
            true);

allModelCCoordinates = ...
    string( ...
        modelCResult.Inspection. ...
        Coordinates.Coordinate);

modelCUnlocked = ...
    setdiff( ...
        allModelCCoordinates, ...
        string(groups.StaticOptimizationLocked), ...
        "stable");

modelCValidation = ...
    modelprep.validateModelConfiguration( ...
        modelCFile, ...
        "ExpectedLocked", ...
            groups.StaticOptimizationLocked, ...
        "ExpectedUnlocked", ...
            modelCUnlocked, ...
        "ExpectedConstraintsEnforced", ...
            false);

assert(modelCValidation.Passed, ...
    "ModelprepExample:ModelCValidationFailed", ...
    "Model C did not satisfy the expected configuration.");

fprintf( ...
    "Model C created and validated:\n%s\n", ...
    modelCFile);

%% SECTION 8 — SUMMARY

fprintf( ...
    "\nModel-preparation API example completed successfully.\n");

fprintf( ...
    "Model A: %s\n", ...
    modelAFile);

fprintf( ...
    "Model B: %s\n", ...
    modelBFile);

fprintf( ...
    "Model C: %s\n", ...
    modelCFile);

fprintf( ...
    "\nThese are temporary demonstration files only.\n");

fprintf( ...
    "The production pipeline remains:\n" + ...
    "  pipeline.runInitializationIkTrial\n" + ...
    "  pipeline.runModelBTrial\n" + ...
    "  pipeline.prepareStaticOptimizationTrial\n");
