%% replot_static_optimization_condition_bands.m
% Lightweight plotting utility for pooled Static Optimization output.
%
% Select:
%   all_trials_time_normalized_so.csv
%
% The production analysis uses:
%   0-20%   = initial support
%   20-80%  = active/off-support motion
%   80-100% = final support
%
% This utility crops the selected source interval (default 20-80%) and
% linearly remaps it to 0-100%, where:
%   0%   = lift-off
%   100% = re-contact
%
% It then redraws condition mean +/- 1 SD bands without rerunning the
% production Static Optimization analysis.
%
% Intended location:
%   examples/replot_static_optimization_condition_bands.m

clear;
clc;

%% ========================================================================
% SECTION 0 — USER SETTINGS
% Adjust values in this section for iterative plotting/test cases.
% ========================================================================

plotCfg = struct;

% Source interval in the existing pooled normalized file.
% Production default: [20 80] = lift-off through re-contact.
plotCfg.sourceWindowPercent = [20 80];

% New display normalization after cropping sourceWindowPercent.
plotCfg.outputWindowPercent = [0 100];

% Preserve the production condition order and use a fixed color mapping:
%   0 deg  = blue
%   15 deg = red
%   30 deg = green
%   45 deg = magenta
plotCfg.conditionOrderDeg = [0 15 30 45];

lineColors = [ ...
    0   130 200; ...  % Blue
    230 25  75;  ...  % Red
    60  180 75;  ...  % Green
    240 50  230] / 255; % Magenta

plotCfg.conditionColors = lineColors;

% Plot appearance.
plotCfg.lineWidth = 2.0;
plotCfg.bandAlpha = 0.18;

% Use a slightly lighter band in the combined force plot because both
% flexor and extensor SD regions are shown in the same axes.
plotCfg.combinedBandAlpha = 0.10;

plotCfg.fontSize = 14;
plotCfg.fontName = "Cambria Math";
plotCfg.legendLocation = "best";
plotCfg.figurePosition = [100 100 900 550];
plotCfg.xTicks = 0:20:100;
plotCfg.showGrid = true;

% Optional fixed y-limits.
% Leave empty for automatic limits matching the production-style
% zero-based axis with 5% headroom above mean + SD.
plotCfg.flexorYLim = [];
plotCfg.extensorYLim = [];
plotCfg.reserveYLim = [];

% The current pooled SO CSV contains max_abs_reserve_activation.
% Set false if only force plots are desired.
plotCfg.plotReserve = true;

% Figure export.
% For fast iterative testing, figures remain open and exporting is off.
plotCfg.exportFigures = false;
plotCfg.exportResolution = 300;
plotCfg.outputSubfolder = "liftoff_recontact_replots";

%% ========================================================================
% SECTION 1 — SELECT POOLED NORMALIZED INPUT FILE
% ========================================================================

[fileName, filePath] = uigetfile( ...
    { ...
        '*.csv', 'Static Optimization pooled CSV (*.csv)'; ...
        '*.*',   'All files (*.*)' ...
    }, ...
    'Select all_trials_time_normalized_so.csv');

if isequal(fileName, 0)
    fprintf("File selection cancelled.\n");
    return;
end

inputFile = string(fullfile(filePath, fileName));

fprintf( ...
    "Selected pooled Static Optimization file:\n%s\n", ...
    inputFile);

T = readtable(inputFile);

%% ========================================================================
% SECTION 2 — VALIDATE REQUIRED COLUMNS
% ========================================================================

requiredVariables = [
    "condition_deg"
    "trial_num"
    "norm_percent"
    "flexor_force_N"
    "extensor_force_N"
];

availableVariables = ...
    string(T.Properties.VariableNames);

missingVariables = ...
    setdiff( ...
        requiredVariables, ...
        availableVariables, ...
        "stable");

assert(isempty(missingVariables), ...
    "SOReplot:MissingVariables", ...
    "Selected CSV is missing required variable(s): %s", ...
    strjoin(missingVariables, ", "));

assert( ...
    numel(plotCfg.sourceWindowPercent) == 2 && ...
    all(isfinite(plotCfg.sourceWindowPercent)) && ...
    plotCfg.sourceWindowPercent(2) > plotCfg.sourceWindowPercent(1), ...
    "SOReplot:InvalidSourceWindow", ...
    "plotCfg.sourceWindowPercent must contain two increasing finite values.");

assert( ...
    numel(plotCfg.outputWindowPercent) == 2 && ...
    all(isfinite(plotCfg.outputWindowPercent)) && ...
    plotCfg.outputWindowPercent(2) > plotCfg.outputWindowPercent(1), ...
    "SOReplot:InvalidOutputWindow", ...
    "plotCfg.outputWindowPercent must contain two increasing finite values.");

%% ========================================================================
% SECTION 3 — CROP LIFT-OFF TO RE-CONTACT AND RE-NORMALIZE TO 0-100%
% ========================================================================

sourceStart = plotCfg.sourceWindowPercent(1);
sourceEnd = plotCfg.sourceWindowPercent(2);

outputStart = plotCfg.outputWindowPercent(1);
outputEnd = plotCfg.outputWindowPercent(2);

sourcePercent = T.norm_percent;

cropMask = ...
    isfinite(sourcePercent) & ...
    sourcePercent >= sourceStart & ...
    sourcePercent <= sourceEnd;

T = T(cropMask, :);

assert(~isempty(T), ...
    "SOReplot:EmptySourceWindow", ...
    "No rows were found inside the requested source window %.3g-%.3g%%.", ...
    sourceStart, ...
    sourceEnd);

% Preserve the original production normalization for inspection.
T.source_norm_percent = T.norm_percent;

% Linear remapping:
%   sourceStart -> outputStart
%   sourceEnd   -> outputEnd
T.norm_percent = ...
    outputStart + ...
    (T.source_norm_percent - sourceStart) ./ ...
    (sourceEnd - sourceStart) .* ...
    (outputEnd - outputStart);

T = sortrows( ...
    T, ...
    ["condition_deg", "trial_num", "norm_percent"]);

fprintf( ...
    "\nRe-normalized %.3g-%.3g%% source data to %.3g-%.3g%%.\n", ...
    sourceStart, ...
    sourceEnd, ...
    outputStart, ...
    outputEnd);

availableConditions = ...
    unique(T.condition_deg(isfinite(T.condition_deg)));

fprintf("Available condition/trial counts:\n");

for conditionDeg = availableConditions(:).'
    trialCount = numel(unique( ...
        T.trial_num(T.condition_deg == conditionDeg)));

    fprintf( ...
        "  %g deg: %d trial(s)\n", ...
        conditionDeg, ...
        trialCount);
end

%% ========================================================================
% SECTION 4 — OPTIONAL EXPORT DIRECTORY
% ========================================================================

outputDirectory = "";

if plotCfg.exportFigures
    outputDirectory = string(fullfile( ...
        filePath, ...
        plotCfg.outputSubfolder));

    if ~isfolder(outputDirectory)
        mkdir(outputDirectory);
    end

    fprintf( ...
        "\nFigures will be exported to:\n%s\n", ...
        outputDirectory);
end

%% ========================================================================
% SECTION 5 — DRAW CONDITION MEAN +/- 1 SD PLOTS
% ========================================================================

localPlotConditionBands( ...
    T, ...
    "flexor_force_N", ...
    "Flexor force (N)", ...
    "Summed flexor force — lift-off to re-contact", ...
    plotCfg.flexorYLim, ...
    "flexor_force_liftoff_to_recontact.png", ...
    outputDirectory, ...
    plotCfg);

localPlotConditionBands( ...
    T, ...
    "extensor_force_N", ...
    "Extensor force (N)", ...
    "Summed extensor force — lift-off to re-contact", ...
    plotCfg.extensorYLim, ...
    "extensor_force_liftoff_to_recontact.png", ...
    outputDirectory, ...
    plotCfg);

% Fourth plot: flexor and extensor force together.
%   Flexor   = solid line
%   Extensor = dashed line
% Condition color is preserved across both muscle groups.
localPlotCombinedForceBands( ...
    T, ...
    "Summed flexor and extensor force — lift-off to re-contact", ...
    "flexor_extensor_force_liftoff_to_recontact.png", ...
    outputDirectory, ...
    plotCfg);

if plotCfg.plotReserve
    if ismember( ...
            "max_abs_reserve_activation", ...
            string(T.Properties.VariableNames))

        localPlotConditionBands( ...
            T, ...
            "max_abs_reserve_activation", ...
            "Maximum absolute reserve activation", ...
            "Reserve actuator demand — lift-off to re-contact", ...
            plotCfg.reserveYLim, ...
            "reserve_activation_liftoff_to_recontact.png", ...
            outputDirectory, ...
            plotCfg);
    else
        warning( ...
            "SOReplot:ReserveVariableMissing", ...
            "plotCfg.plotReserve is true, but max_abs_reserve_activation " + ...
            "is not present. Reserve plot skipped.");
    end
end

fprintf( ...
    "\nReplot complete. " + ...
    "0%% now represents lift-off and 100%% represents re-contact.\n");

%% ========================================================================
% LOCAL FUNCTIONS
% ========================================================================

function localPlotConditionBands( ...
        T, valueVariable, yLabelText, figureTitle, ...
        requestedYLim, outputFileName, outputDirectory, plotCfg)
%LOCALPLOTCONDITIONBANDS Plot condition mean +/- 1 SD.

    availableConditions = ...
        unique(T.condition_deg(isfinite(T.condition_deg)));

    orderedConditions = ...
        plotCfg.conditionOrderDeg( ...
            ismember( ...
                plotCfg.conditionOrderDeg, ...
                availableConditions));

    extraConditions = ...
        setdiff( ...
            availableConditions(:).', ...
            plotCfg.conditionOrderDeg, ...
            "stable");

    conditions = ...
        [orderedConditions(:); extraConditions(:)];

    assert(~isempty(conditions), ...
        "SOReplot:NoConditions", ...
        "No finite condition values are available for plotting.");

    fig = figure( ...
        "Color", "w", ...
        "Name", figureTitle, ...
        "Position", plotCfg.figurePosition);

    ax = axes(fig);
    hold(ax, "on");

    lineHandles = gobjects(numel(conditions), 1);
    maxUpperBand = 0;

    for iCondition = 1:numel(conditions)

        conditionDeg = ...
            conditions(iCondition);

        thisT = ...
            T(T.condition_deg == conditionDeg, :);

        [groupIndex, normValues] = ...
            findgroups(thisT.norm_percent);

        meanValue = splitapply( ...
            @(x) mean(x, "omitnan"), ...
            thisT.(valueVariable), ...
            groupIndex);

        sdValue = splitapply( ...
            @(x) std(x, "omitnan"), ...
            thisT.(valueVariable), ...
            groupIndex);

        [normValues, sortIndex] = ...
            sort(normValues);

        meanValue = ...
            meanValue(sortIndex);

        sdValue = ...
            sdValue(sortIndex);

        lowerBand = ...
            meanValue - sdValue;

        upperBand = ...
            meanValue + sdValue;

        finiteUpperBand = ...
            upperBand(isfinite(upperBand));

        if ~isempty(finiteUpperBand)
            maxUpperBand = max( ...
                maxUpperBand, ...
                max(finiteUpperBand));
        end

        colorIndex = ...
            localConditionColorIndex( ...
                conditionDeg, ...
                iCondition, ...
                plotCfg);

        lineColor = ...
            plotCfg.conditionColors(colorIndex, :);

        fill(ax, ...
            [normValues; flipud(normValues)], ...
            [lowerBand; flipud(upperBand)], ...
            lineColor, ...
            "FaceAlpha", plotCfg.bandAlpha, ...
            "EdgeColor", "none", ...
            "HandleVisibility", "off");

        lineHandles(iCondition) = plot(ax, ...
            normValues, ...
            meanValue, ...
            "Color", lineColor, ...
            "LineWidth", plotCfg.lineWidth, ...
            "LineStyle", "-", ...
            "DisplayName", sprintf("%g°", conditionDeg));
    end

    xlabel(ax, ...
        "Normalized lift-off to re-contact time (%)");

    ylabel(ax, ...
        yLabelText);

    title(ax, ...
        figureTitle, ...
        "Interpreter", "none");

    xlim(ax, ...
        plotCfg.outputWindowPercent);

    xticks(ax, ...
        plotCfg.xTicks);

    if isempty(requestedYLim)
        ylim(ax, ...
            [0, localUpperYLimit(maxUpperBand)]);
    else
        assert( ...
            isnumeric(requestedYLim) && ...
            numel(requestedYLim) == 2 && ...
            all(isfinite(requestedYLim)) && ...
            requestedYLim(2) > requestedYLim(1), ...
            "SOReplot:InvalidYLimits", ...
            "Requested y-limits for '%s' must contain two increasing values.", ...
            valueVariable);

        ylim(ax, ...
            requestedYLim);
    end

    legend(ax, ...
        lineHandles, ...
        "Location", plotCfg.legendLocation);

    if plotCfg.showGrid
        grid(ax, "on");
    else
        grid(ax, "off");
    end

    box(ax, "on");
    ax.FontSize = plotCfg.fontSize;
    ax.FontName = plotCfg.fontName;

    uistack(lineHandles, "top");

    if plotCfg.exportFigures
        outputFile = ...
            fullfile( ...
                outputDirectory, ...
                outputFileName);

        exportgraphics( ...
            fig, ...
            outputFile, ...
            "Resolution", plotCfg.exportResolution);

        fprintf( ...
            "Exported:\n%s\n", ...
            outputFile);
    end
end


function localPlotCombinedForceBands( ...
        T, figureTitle, outputFileName, outputDirectory, plotCfg)
%LOCALPLOTCOMBINEDFORCEBANDS Plot flexor and extensor mean +/- 1 SD together.
%
% Flexor mean lines are solid.
% Extensor mean lines are dashed.
% Both use the same condition-specific color mapping.

    availableConditions = ...
        unique(T.condition_deg(isfinite(T.condition_deg)));

    orderedConditions = ...
        plotCfg.conditionOrderDeg( ...
            ismember( ...
                plotCfg.conditionOrderDeg, ...
                availableConditions));

    extraConditions = ...
        setdiff( ...
            availableConditions(:).', ...
            plotCfg.conditionOrderDeg, ...
            "stable");

    conditions = ...
        [orderedConditions(:); extraConditions(:)];

    assert(~isempty(conditions), ...
        "SOReplot:NoConditions", ...
        "No finite condition values are available for plotting.");

    fig = figure( ...
        "Color", "w", ...
        "Name", figureTitle, ...
        "Position", plotCfg.figurePosition);

    ax = axes(fig);
    hold(ax, "on");

    flexorHandles = gobjects(numel(conditions), 1);
    extensorHandles = gobjects(numel(conditions), 1);
    maxUpperBand = 0;

    for iCondition = 1:numel(conditions)

        conditionDeg = ...
            conditions(iCondition);

        thisT = ...
            T(T.condition_deg == conditionDeg, :);

        [groupIndex, normValues] = ...
            findgroups(thisT.norm_percent);

        flexorMean = splitapply( ...
            @(x) mean(x, "omitnan"), ...
            thisT.flexor_force_N, ...
            groupIndex);

        flexorSd = splitapply( ...
            @(x) std(x, "omitnan"), ...
            thisT.flexor_force_N, ...
            groupIndex);

        extensorMean = splitapply( ...
            @(x) mean(x, "omitnan"), ...
            thisT.extensor_force_N, ...
            groupIndex);

        extensorSd = splitapply( ...
            @(x) std(x, "omitnan"), ...
            thisT.extensor_force_N, ...
            groupIndex);

        [normValues, sortIndex] = ...
            sort(normValues);

        flexorMean = flexorMean(sortIndex);
        flexorSd = flexorSd(sortIndex);
        extensorMean = extensorMean(sortIndex);
        extensorSd = extensorSd(sortIndex);

        flexorLower = flexorMean - flexorSd;
        flexorUpper = flexorMean + flexorSd;

        extensorLower = extensorMean - extensorSd;
        extensorUpper = extensorMean + extensorSd;

        finiteUpperBand = [ ...
            flexorUpper(isfinite(flexorUpper)); ...
            extensorUpper(isfinite(extensorUpper))];

        if ~isempty(finiteUpperBand)
            maxUpperBand = max( ...
                maxUpperBand, ...
                max(finiteUpperBand));
        end

        colorIndex = ...
            localConditionColorIndex( ...
                conditionDeg, ...
                iCondition, ...
                plotCfg);

        lineColor = ...
            plotCfg.conditionColors(colorIndex, :);

        % Flexor +/- 1 SD.
        fill(ax, ...
            [normValues; flipud(normValues)], ...
            [flexorLower; flipud(flexorUpper)], ...
            lineColor, ...
            "FaceAlpha", plotCfg.combinedBandAlpha, ...
            "EdgeColor", "none", ...
            "HandleVisibility", "off");

        % Extensor +/- 1 SD.
        fill(ax, ...
            [normValues; flipud(normValues)], ...
            [extensorLower; flipud(extensorUpper)], ...
            lineColor, ...
            "FaceAlpha", plotCfg.combinedBandAlpha, ...
            "EdgeColor", "none", ...
            "HandleVisibility", "off");

        flexorHandles(iCondition) = plot(ax, ...
            normValues, ...
            flexorMean, ...
            "Color", lineColor, ...
            "LineWidth", plotCfg.lineWidth, ...
            "LineStyle", "-", ...
            "DisplayName", sprintf("%g° flexor", conditionDeg));

        extensorHandles(iCondition) = plot(ax, ...
            normValues, ...
            extensorMean, ...
            "Color", lineColor, ...
            "LineWidth", plotCfg.lineWidth, ...
            "LineStyle", "--", ...
            "DisplayName", sprintf("%g° extensor", conditionDeg));
    end

    xlabel(ax, ...
        "Normalized lift-off to re-contact time (%)");

    ylabel(ax, ...
        "Summed muscle force (N)");

    title(ax, ...
        figureTitle, ...
        "Interpreter", "none");

    xlim(ax, ...
        plotCfg.outputWindowPercent);

    xticks(ax, ...
        plotCfg.xTicks);

    combinedYLim = [];

    if ~isempty(plotCfg.flexorYLim) && ~isempty(plotCfg.extensorYLim)
        combinedYLim = [ ...
            min(plotCfg.flexorYLim(1), plotCfg.extensorYLim(1)), ...
            max(plotCfg.flexorYLim(2), plotCfg.extensorYLim(2))];
    elseif ~isempty(plotCfg.flexorYLim)
        combinedYLim = plotCfg.flexorYLim;
    elseif ~isempty(plotCfg.extensorYLim)
        combinedYLim = plotCfg.extensorYLim;
    end

    if isempty(combinedYLim)
        ylim(ax, ...
            [0, localUpperYLimit(maxUpperBand)]);
    else
        ylim(ax, ...
            combinedYLim);
    end

    % Legend convention:
    %   - Solid colored lines identify incline condition.
    %   - Dashed gray line identifies extensor traces.
    
    extensorLegendHandle = plot(ax, ...
        nan, ...
        nan, ...
        "Color", [0.4 0.4 0.4], ...
        "LineWidth", plotCfg.lineWidth, ...
        "LineStyle", "--");
    
    legendHandles = [ ...
        flexorHandles(1); ...
        flexorHandles(2); ...
        flexorHandles(3); ...
        flexorHandles(4); ...
        extensorLegendHandle];
    
    legLabels = [ ...
        "0°"; ...
        "15°"; ...
        "30°"; ...
        "45°"; ...
        "Extensors"];
    
    legend(ax, ...
        legendHandles, ...
        legLabels, ...
        "Location", plotCfg.legendLocation);

    if plotCfg.showGrid
        grid(ax, "on");
    else
        grid(ax, "off");
    end

    box(ax, "on");
    ax.FontSize = plotCfg.fontSize;
    ax.FontName = plotCfg.fontName;

    uistack([flexorHandles; extensorHandles], "top");

    if plotCfg.exportFigures
        outputFile = ...
            fullfile( ...
                outputDirectory, ...
                outputFileName);

        exportgraphics( ...
            fig, ...
            outputFile, ...
            "Resolution", plotCfg.exportResolution);

        fprintf( ...
            "Exported:\n%s\n", ...
            outputFile);
    end
end


function colorIndex = localConditionColorIndex( ...
        conditionDeg, fallbackIndex, plotCfg)
%LOCALCONDITIONCOLORINDEX Preserve canonical condition-to-color mapping.

    canonicalIndex = find( ...
        plotCfg.conditionOrderDeg == conditionDeg, ...
        1, ...
        "first");

    if isempty(canonicalIndex)
        canonicalIndex = fallbackIndex;
    end

    numberOfColors = ...
        size(plotCfg.conditionColors, 1);

    colorIndex = ...
        mod(canonicalIndex - 1, numberOfColors) + 1;
end


function upperLimit = localUpperYLimit(values)
%LOCALUPPERYLIMIT Return a positive y-axis ceiling with 5% headroom.

    values = double(values(:));
    values = values(isfinite(values));

    if isempty(values)
        maximumValue = 0;
    else
        maximumValue = max(values);
    end

    if maximumValue > 0
        upperLimit = 1.05 * maximumValue;
    else
        upperLimit = 1;
    end
end
