%% run_static_optimization_plotting_pipeline.m
% Static Optimization diagnostic and batch plotting pipeline.
%
% This script can be used immediately with one completed SO trial. Missing
% trials are skipped. As additional SO trials are generated, the same script
% automatically creates condition-level summaries and mean +/- SD plots.
%
% Key features inherited from the previous analysis workflow:
%   - event-based piecewise time normalization;
%   - 0-20% initial support, 20-80% active/off-support,
%     80-100% final support;
%   - trial-level force metrics calculated only within the 20-80%
%     active-motion statistical ROI;
%   - condition-level mean +/- SD plots.
%
% Improvements for the rebuilt pipeline:
%   - event times come from the new CoM event detector;
%   - muscle columns are identified from Model C names, not fixed indices;
%   - reserve/non-muscle actuator activations are audited explicitly;
%   - raw and normalized plots show phase shading and event markers.
%
% Expected per-trial inputs:
%
% output/<condition>/<trial>/
%   03_static_optimization_prep/
%       <trial>_modelC_static_optimization.osim
%       head_support_force/qc/contact_event_detection_summary.csv
%
%   04_static_optimization/
%       results/
%           *StaticOptimization_force.sto
%           *StaticOptimization_activation.sto
%
% Per-trial plots:
%   04_static_optimization/qc/plots/
%
% Combined outputs:
%   output/static_optimization_analysis/

clear;
clc;
dbstop if error


%% SECTION 0 — PROJECT AND PLOTTING CONFIGURATION

activeFile = string( ...
    matlab.desktop.editor.getActiveFilename);

assert(strlength(activeFile) > 0 && isfile(activeFile), ...
    "SOPlotting:ActiveScriptUnknown", ...
    "Open and save this script in the MATLAB Editor before running.");

examplesDirectory = string(fileparts(activeFile));
projectRoot = string(fileparts(examplesDirectory));

addpath(projectRoot);

projectCfg = load_project_config();

plotCfg = struct;

plotCfg.conditionsDeg = 45;
plotCfg.trials = 1;

% Optional exclusions as [condition_deg trial_num].
plotCfg.excludedTrials = zeros(0,2);

% Event-normalized task phases.
plotCfg.normalizedBreaks = [0 20 80 100];
plotCfg.pointsPerPhase = [200 600 200];

% Statistical region of interest (ROI).
%
% IMPORTANT:
% All reported force/reserve summary metrics are calculated ONLY within
% this normalized interval. The complete 0-100% waveform is retained for
% plotting/QC, but the pre-lift-off and post-re-contact support phases are
% excluded from statistical reporting.
plotCfg.statisticsWindowPercent = [20 80];

% Functional muscle groups are read directly from Model C <ObjectGroup>
% definitions. The model currently lists only one lateral side in these
% groups; modelprep.getBilateralMuscleGroupMembers expands them to the
% contralateral side using the actual model muscle names.
plotCfg.flexionGroupName = "flexion";
plotCfg.extensionGroupName = "extension";

% Expected bilateral counts from the validated group definitions.
plotCfg.expectedFlexorCount = 16;
plotCfg.expectedExtensorCount = 36;

% Number of highest-demand reserves shown in the per-trial reserve plot.
plotCfg.topReserveCount = 10;

analysisDirectory = string(fullfile( ...
    projectCfg.outputRoot, ...
    "static_optimization_analysis"));

if ~isfolder(analysisDirectory)
    mkdir(analysisDirectory);
end


%% SECTION 1 — PROCESS ALL AVAILABLE SO TRIALS

allNormalized = table;
allStatsWindowNormalized = table;
allMetrics = table;
allReserveAudit = table;
allMuscleAudit = table;

processedTrials = strings(0,1);

for conditionDeg = plotCfg.conditionsDeg

    conditionFolderName = sprintf( ...
        "%02ddeg", round(conditionDeg));

    for trialNumber = plotCfg.trials

        if ~isempty(plotCfg.excludedTrials) && ...
                any( ...
                    plotCfg.excludedTrials(:,1) == conditionDeg & ...
                    plotCfg.excludedTrials(:,2) == trialNumber)

            fprintf( ...
                "Skipping excluded trial: %g deg trial %d\n", ...
                conditionDeg, trialNumber);
            continue;
        end

        trialFolderName = sprintf( ...
            "trial%02d", trialNumber);

        trialStem = sprintf( ...
            "%s_%s", ...
            conditionFolderName, ...
            trialFolderName);

        trialName = string(trialStem);

        trialRoot = string(fullfile( ...
            projectCfg.outputRoot, ...
            conditionFolderName, ...
            trialFolderName));

        prepDirectory = string(fullfile( ...
            trialRoot, ...
            "03_static_optimization_prep"));

        soDirectory = string(fullfile( ...
            trialRoot, ...
            "04_static_optimization"));

        resultsDirectory = string(fullfile( ...
            soDirectory, ...
            "results"));

        qcDirectory = string(fullfile( ...
            soDirectory, ...
            "qc"));

        plotDirectory = string(fullfile( ...
            qcDirectory, ...
            "plots"));

        if ~isfolder(plotDirectory)
            mkdir(plotDirectory);
        end

        modelFile = string(fullfile( ...
            prepDirectory, ...
            trialStem + ...
            "_modelC_static_optimization.osim"));

        eventSummaryFile = string(fullfile( ...
            prepDirectory, ...
            "head_support_force", ...
            "qc", ...
            "contact_event_detection_summary.csv"));

        if ~isfile(modelFile) || ...
                ~isfile(eventSummaryFile) || ...
                ~isfolder(resultsDirectory)

            fprintf( ...
                "Skipping %s: preparation or SO results incomplete.\n", ...
                trialName);
            continue;
        end

        forceFile = localFindSingleResultFile( ...
            resultsDirectory, ...
            "*StaticOptimization_force.sto");

        activationFile = localFindSingleResultFile( ...
            resultsDirectory, ...
            "*StaticOptimization_activation.sto");

        if strlength(forceFile) == 0 || ...
                strlength(activationFile) == 0

            fprintf( ...
                "Skipping %s: force/activation STO not found.\n", ...
                trialName);
            continue;
        end

        %% Load detected contact events

        eventSummary = readtable(eventSummaryFile);

        requiredEventColumns = [ ...
            "LiftOffTime"
            "RecontactTime"
        ];

        assert(all(ismember( ...
            requiredEventColumns, ...
            string(eventSummary.Properties.VariableNames))), ...
            "SOPlotting:EventColumnsMissing", ...
            "Event summary for %s must contain " + ...
            "LiftOffTime and RecontactTime.", ...
            trialName);

        assert(height(eventSummary) == 1, ...
            "SOPlotting:UnexpectedEventRows", ...
            "Expected one event-summary row for %s.", ...
            trialName);

        eventTimes = [ ...
            eventSummary.LiftOffTime, ...
            eventSummary.RecontactTime];

        fprintf("\nAnalyzing %s\n", trialName);

        %% Read SO outputs

        forceSto = opensimio.readSto(forceFile);
        activationSto = opensimio.readSto(activationFile);

        forceLabels = reshape( ...
            string(forceSto.Labels), 1, []);

        activationLabels = reshape( ...
            string(activationSto.Labels), 1, []);

        forceTimeColumn = ...
            localFindTimeColumn(forceLabels);

        activationTimeColumn = ...
            localFindTimeColumn(activationLabels);

        forceTime = ...
            forceSto.Data(:, forceTimeColumn);

        activationTime = ...
            activationSto.Data(:, activationTimeColumn);

        assert(all(diff(forceTime) > 0), ...
            "SOPlotting:NonmonotonicForceTime", ...
            "Force time is not strictly increasing for %s.", ...
            trialName);

        assert(all(diff(activationTime) > 0), ...
            "SOPlotting:NonmonotonicActivationTime", ...
            "Activation time is not strictly increasing for %s.", ...
            trialName);

        rawForceBreaks = [ ...
            forceTime(1), ...
            eventTimes(1), ...
            eventTimes(2), ...
            forceTime(end)];

        rawActivationBreaks = [ ...
            activationTime(1), ...
            eventTimes(1), ...
            eventTimes(2), ...
            activationTime(end)];

        localValidateBreaks( ...
            rawForceBreaks, trialName);

        localValidateBreaks( ...
            rawActivationBreaks, trialName);

        %% Read model muscle names

        import org.opensim.modeling.*

        model = Model(char(modelFile));
        model.finalizeConnections();

        muscleSet = model.getMuscles();
        numMuscles = muscleSet.getSize();

        modelMuscleNames = strings(numMuscles,1);

        for iMuscle = 0:(numMuscles-1)
            modelMuscleNames(iMuscle+1) = ...
                string(char( ...
                    muscleSet.get(iMuscle).getName()));
        end

        %% Verify SO muscle columns against Model C

        missingForceMuscles = setdiff( ...
            modelMuscleNames, ...
            forceLabels, ...
            "stable");

        missingActivationMuscles = setdiff( ...
            modelMuscleNames, ...
            activationLabels, ...
            "stable");

        assert(isempty(missingForceMuscles), ...
            "SOPlotting:MissingForceMuscles", ...
            "Force STO is missing model muscles for %s: %s", ...
            trialName, ...
            strjoin(missingForceMuscles, ", "));

        assert(isempty(missingActivationMuscles), ...
            "SOPlotting:MissingActivationMuscles", ...
            "Activation STO is missing model muscles for %s: %s", ...
            trialName, ...
            strjoin(missingActivationMuscles, ", "));

        %% Resolve authoritative flexion / extension ObjectGroups

        flexionGroup = ...
            modelprep.getBilateralMuscleGroupMembers( ...
                modelFile, ...
                plotCfg.flexionGroupName, ...
                "RequireBilateral", ...
                    true, ...
                "ExpectedResolvedCount", ...
                    plotCfg.expectedFlexorCount);

        extensionGroup = ...
            modelprep.getBilateralMuscleGroupMembers( ...
                modelFile, ...
                plotCfg.extensionGroupName, ...
                "RequireBilateral", ...
                    true, ...
                "ExpectedResolvedCount", ...
                    plotCfg.expectedExtensorCount);

        flexorNames = ...
            flexionGroup.ResolvedMembers;

        extensorNames = ...
            extensionGroup.ResolvedMembers;

        overlapMuscles = intersect( ...
            flexorNames, ...
            extensorNames, ...
            "stable");

        assert(isempty(overlapMuscles), ...
            "SOPlotting:FunctionalGroupOverlap", ...
            "One or more muscles occur in both flexion and extension " + ...
            "ObjectGroups for %s: %s", ...
            trialName, ...
            strjoin(overlapMuscles, ", "));

        excludedMuscleNames = setdiff( ...
            modelMuscleNames, ...
            [flexorNames; extensorNames], ...
            "stable");

        fprintf("  Flexion group:  %d muscles\n", ...
            numel(flexorNames));

        fprintf("  Extension group: %d muscles\n", ...
            numel(extensorNames));

        fprintf("  Excluded/other:  %d muscles\n", ...
            numel(excludedMuscleNames));

        % Only explicit flexion/extension group members contribute to these
        % sums. Hyoid-associated muscles, digastrics, and other unrelated
        % muscles remain model muscles but are excluded from both groups.
        flexorColumns = ...
            localFindColumns( ...
                forceLabels, ...
                flexorNames);

        extensorColumns = ...
            localFindColumns( ...
                forceLabels, ...
                extensorNames);

        flexorForce = sum( ...
            forceSto.Data(:, flexorColumns), ...
            2, ...
            "omitnan");

        extensorForce = sum( ...
            forceSto.Data(:, extensorColumns), ...
            2, ...
            "omitnan");

        netForce = ...
            flexorForce - extensorForce;

        %% Identify non-muscle / reserve activation columns

        activationNonTimeMask = ...
            true(size(activationLabels));

        activationNonTimeMask( ...
            activationTimeColumn) = false;

        reserveMask = ...
            activationNonTimeMask & ...
            ~ismember( ...
                activationLabels, ...
                modelMuscleNames);

        reserveLabels = ...
            activationLabels(reserveMask);

        reserveData = ...
            activationSto.Data(:, reserveMask);

        assert(~isempty(reserveLabels), ...
            "SOPlotting:NoReserveActivations", ...
            "No non-muscle activation columns were found for %s. " + ...
            "Inspect the activation STO labels.", ...
            trialName);

        maxAbsReserveByTime = ...
            max(abs(reserveData), [], 2);

        rmsReserveByTime = ...
            sqrt(mean( ...
                reserveData.^2, ...
                2, ...
                "omitnan"));

        peakAbsByReserve = ...
            max(abs(reserveData), [], 1);

        [sortedPeakReserve, reserveOrder] = ...
            sort(peakAbsByReserve, "descend");

        sortedReserveLabels = ...
            reserveLabels(reserveOrder);

        reserveAudit = table( ...
            repmat(trialName, numel(reserveLabels),1), ...
            repmat(conditionDeg, numel(reserveLabels),1), ...
            repmat(trialNumber, numel(reserveLabels),1), ...
            sortedReserveLabels(:), ...
            sortedPeakReserve(:), ...
            'VariableNames', { ...
                'trial', ...
                'condition_deg', ...
                'trial_num', ...
                'reserve_label', ...
                'peak_absolute_activation'});

        allReserveAudit = [ ...
            allReserveAudit
            reserveAudit]; %#ok<AGROW>

        %% Muscle-group audit table

        muscleGroupLabels = ...
            repmat("Excluded/other", numMuscles,1);

        muscleGroupLabels( ...
            ismember(modelMuscleNames, flexorNames)) = ...
            "Flexor";

        muscleGroupLabels( ...
            ismember(modelMuscleNames, extensorNames)) = ...
            "Extensor";

        muscleAudit = table( ...
            repmat(trialName, numMuscles,1), ...
            repmat(conditionDeg, numMuscles,1), ...
            modelMuscleNames, ...
            muscleGroupLabels, ...
            'VariableNames', { ...
                'trial', ...
                'condition_deg', ...
                'muscle_name', ...
                'group'});

        allMuscleAudit = [ ...
            allMuscleAudit
            muscleAudit]; %#ok<AGROW>

        % Per-trial source-to-bilateral expansion audit. This makes it
        % explicit which left-side muscle was inferred from each group
        % member stored in the .osim file.
        groupExpansionAudit = [ ...
            addvars( ...
                flexionGroup.Audit, ...
                repmat("Flexor", ...
                    height(flexionGroup.Audit),1), ...
                'Before', 1, ...
                'NewVariableNames', "FunctionalGroup")
            addvars( ...
                extensionGroup.Audit, ...
                repmat("Extensor", ...
                    height(extensionGroup.Audit),1), ...
                'Before', 1, ...
                'NewVariableNames', "FunctionalGroup")
        ];

        writetable( ...
            groupExpansionAudit, ...
            fullfile( ...
                qcDirectory, ...
                "muscle_group_bilateral_expansion_audit.csv"));

        %% Piecewise time normalization

        normPercent = ...
            localMakePiecewisePercentGrid( ...
                plotCfg.normalizedBreaks, ...
                plotCfg.pointsPerPhase);

        flexorNorm = ...
            localPiecewiseTimeNormalize( ...
                forceTime, ...
                flexorForce, ...
                rawForceBreaks, ...
                plotCfg.normalizedBreaks, ...
                normPercent);

        extensorNorm = ...
            localPiecewiseTimeNormalize( ...
                forceTime, ...
                extensorForce, ...
                rawForceBreaks, ...
                plotCfg.normalizedBreaks, ...
                normPercent);

        maxReserveNorm = ...
            localPiecewiseTimeNormalize( ...
                activationTime, ...
                maxAbsReserveByTime, ...
                rawActivationBreaks, ...
                plotCfg.normalizedBreaks, ...
                normPercent);

        rmsReserveNorm = ...
            localPiecewiseTimeNormalize( ...
                activationTime, ...
                rmsReserveByTime, ...
                rawActivationBreaks, ...
                plotCfg.normalizedBreaks, ...
                normPercent);

        normalizedTrial = table;
        normalizedTrial.trial = ...
            repmat(trialName, numel(normPercent),1);
        normalizedTrial.condition_deg = ...
            repmat(conditionDeg, numel(normPercent),1);
        normalizedTrial.trial_num = ...
            repmat(trialNumber, numel(normPercent),1);
        normalizedTrial.norm_percent = ...
            normPercent(:);

        normalizedTrial.flexor_force_N = ...
            flexorNorm(:);

        normalizedTrial.extensor_force_N = ...
            extensorNorm(:);

        normalizedTrial.net_flexor_minus_extensor_N = ...
            flexorNorm(:) - extensorNorm(:);

        normalizedTrial.max_abs_reserve_activation = ...
            maxReserveNorm(:);

        normalizedTrial.rms_reserve_activation = ...
            rmsReserveNorm(:);

        allNormalized = [ ...
            allNormalized
            normalizedTrial]; %#ok<AGROW>

        %% Statistical ROI and trial metrics
        %
        % The complete normalized waveform remains in allNormalized for
        % plotting/QC. Statistical reporting uses ONLY the configured
        % normalized ROI (default 20-80%), corresponding to lift-off
        % through re-contact.

        np = normalizedTrial.norm_percent;

        statsStartPercent = ...
            plotCfg.statisticsWindowPercent(1);

        statsEndPercent = ...
            plotCfg.statisticsWindowPercent(2);

        assert( ...
            statsStartPercent >= min(plotCfg.normalizedBreaks) && ...
            statsEndPercent <= max(plotCfg.normalizedBreaks) && ...
            statsEndPercent > statsStartPercent, ...
            "SOPlotting:InvalidStatisticsWindow", ...
            "Statistics window must be ordered and inside normalized range.");

        idxStats = ...
            np >= statsStartPercent & ...
            np <= statsEndPercent;

        assert(any(idxStats), ...
            "SOPlotting:EmptyStatisticsWindow", ...
            "Statistics ROI contains no normalized samples for %s.", ...
            trialName);

        statsWindowTrial = ...
            normalizedTrial(idxStats, :);

        allStatsWindowNormalized = [ ...
            allStatsWindowNormalized
            statsWindowTrial]; %#ok<AGROW>

        metrics = table;
        metrics.trial = trialName;
        metrics.condition_deg = conditionDeg;
        metrics.trial_num = trialNumber;

        metrics.statistics_window_start_percent = ...
            statsStartPercent;

        metrics.statistics_window_end_percent = ...
            statsEndPercent;

        metrics.lift_off_time_s = ...
            eventTimes(1);

        metrics.recontact_time_s = ...
            eventTimes(2);

        metrics.off_support_duration_s = ...
            eventTimes(2) - eventTimes(1);

        % -------------------------------------------------------------
        % Muscle-force metrics: STATISTICS ROI ONLY
        % -------------------------------------------------------------

        [metrics.peak_flexor_N, peakFlexorIndex] = ...
            max( ...
                normalizedTrial.flexor_force_N(idxStats), ...
                [], ...
                "omitnan");

        [metrics.peak_extensor_N, peakExtensorIndex] = ...
            max( ...
                normalizedTrial.extensor_force_N(idxStats), ...
                [], ...
                "omitnan");

        statsNormPercent = ...
            normalizedTrial.norm_percent(idxStats);

        metrics.peak_flexor_norm_percent = ...
            statsNormPercent(peakFlexorIndex);

        metrics.peak_extensor_norm_percent = ...
            statsNormPercent(peakExtensorIndex);

        metrics.mean_flexor_N = ...
            mean( ...
                normalizedTrial.flexor_force_N(idxStats), ...
                "omitnan");

        metrics.mean_extensor_N = ...
            mean( ...
                normalizedTrial.extensor_force_N(idxStats), ...
                "omitnan");

        metrics.mean_net_flexor_minus_extensor_N = ...
            mean( ...
                normalizedTrial. ...
                net_flexor_minus_extensor_N(idxStats), ...
                "omitnan");

        metrics.peak_net_flexor_minus_extensor_N = ...
            max( ...
                normalizedTrial. ...
                net_flexor_minus_extensor_N(idxStats), ...
                [], ...
                "omitnan");

        % -------------------------------------------------------------
        % Reserve metrics: STATISTICS ROI ONLY
        % -------------------------------------------------------------

        metrics.peak_abs_reserve_activation = ...
            max( ...
                normalizedTrial. ...
                max_abs_reserve_activation(idxStats), ...
                [], ...
                "omitnan");

        metrics.mean_max_abs_reserve_activation = ...
            mean( ...
                normalizedTrial. ...
                max_abs_reserve_activation(idxStats), ...
                "omitnan");

        metrics.mean_rms_reserve_activation = ...
            mean( ...
                normalizedTrial. ...
                rms_reserve_activation(idxStats), ...
                "omitnan");

        allMetrics = [ ...
            allMetrics
            metrics]; %#ok<AGROW>

        %% Per-trial plot A — raw summed muscle forces

        rawForceFile = string(fullfile( ...
            plotDirectory, ...
            "raw_force_diagnostics.png"));

        localPlotRawForces( ...
            forceTime, ...
            flexorForce, ...
            extensorForce, ...
            netForce, ...
            rawForceBreaks, ...
            trialName, ...
            rawForceFile);

        %% Per-trial plot B — reserve actuator activations

        reservePlotFile = string(fullfile( ...
            plotDirectory, ...
            "reserve_activation_diagnostics.png"));

        localPlotReserveActivations( ...
            activationTime, ...
            reserveData, ...
            reserveLabels, ...
            sortedReserveLabels, ...
            rawActivationBreaks, ...
            trialName, ...
            plotCfg.topReserveCount, ...
            metrics.peak_abs_reserve_activation, ...
            reservePlotFile);

        %% Per-trial plot C — normalized forces

        normalizedPlotFile = string(fullfile( ...
            plotDirectory, ...
            "normalized_force_diagnostics.png"));

        localPlotNormalizedTrial( ...
            normalizedTrial, ...
            trialName, ...
            normalizedPlotFile);

        fprintf("  Peak flexor force (%.0f-%.0f%% ROI): %.3f N\n", ...
            plotCfg.statisticsWindowPercent(1), ...
            plotCfg.statisticsWindowPercent(2), ...
            metrics.peak_flexor_N);

        fprintf("  Peak extensor force (%.0f-%.0f%% ROI): %.3f N\n", ...
            plotCfg.statisticsWindowPercent(1), ...
            plotCfg.statisticsWindowPercent(2), ...
            metrics.peak_extensor_N);

        fprintf("  Peak |reserve activation| (%.0f-%.0f%% ROI): %.6f\n", ...
            plotCfg.statisticsWindowPercent(1), ...
            plotCfg.statisticsWindowPercent(2), ...
            metrics.peak_abs_reserve_activation);

        processedTrials(end+1,1) = trialName; %#ok<SAGROW>
    end
end


%% SECTION 2 — REQUIRE AT LEAST ONE PROCESSED TRIAL

assert(~isempty(allNormalized), ...
    "SOPlotting:NoTrialsProcessed", ...
    "No completed SO trials were found. Check the per-trial " + ...
    "results directories and filenames.");

fprintf("\nProcessed %d trial(s):\n", ...
    numel(processedTrials));

disp(processedTrials);


%% SECTION 3 — WRITE COMBINED ANALYSIS TABLES

normalizedFile = string(fullfile( ...
    analysisDirectory, ...
    "all_trials_time_normalized_so.csv"));

statsWindowNormalizedFile = string(fullfile( ...
    analysisDirectory, ...
    "all_trials_stats_window_so.csv"));

metricsFile = string(fullfile( ...
    analysisDirectory, ...
    "all_trials_so_metrics.csv"));

reserveAuditFile = string(fullfile( ...
    analysisDirectory, ...
    "all_trials_reserve_audit.csv"));

muscleAuditFile = string(fullfile( ...
    analysisDirectory, ...
    "muscle_group_audit.csv"));

writetable(allNormalized, normalizedFile);
writetable(allStatsWindowNormalized, statsWindowNormalizedFile);
writetable(allMetrics, metricsFile);
writetable(allReserveAudit, reserveAuditFile);
writetable(allMuscleAudit, muscleAuditFile);

fprintf("\nWrote full normalized waveform table:\n%s\n", ...
    normalizedFile);

fprintf("Wrote statistics-window normalized table (%.0f-%.0f%%):\n%s\n", ...
    plotCfg.statisticsWindowPercent(1), ...
    plotCfg.statisticsWindowPercent(2), ...
    statsWindowNormalizedFile);

fprintf("%s\n", metricsFile);
fprintf("%s\n", reserveAuditFile);
fprintf("%s\n", muscleAuditFile);


%% SECTION 4 — CONDITION-LEVEL SUMMARY STATISTICS

% Every variable summarized here was calculated exclusively from the
% configured statistical ROI (default 20-80%). No support-phase values
% contribute to these condition-level statistics.
summaryVariables = [ ...
    "peak_flexor_N"
    "peak_extensor_N"
    "mean_flexor_N"
    "mean_extensor_N"
    "mean_net_flexor_minus_extensor_N"
    "peak_net_flexor_minus_extensor_N"
    "peak_abs_reserve_activation"
    "mean_max_abs_reserve_activation"
    "mean_rms_reserve_activation"
];

conditionSummary = groupsummary( ...
    allMetrics, ...
    "condition_deg", ...
    ["mean","std"], ...
    summaryVariables);

conditionSummaryFile = string(fullfile( ...
    analysisDirectory, ...
    "so_metrics_by_condition.csv"));

writetable( ...
    conditionSummary, ...
    conditionSummaryFile);

disp(conditionSummary);


%% SECTION 5 — CONDITION MEAN +/- SD PLOTS

localPlotConditionBands( ...
    allNormalized, ...
    "flexor_force_N", ...
    "Flexor force (N)", ...
    "Summed flexor force", ...
    fullfile( ...
        analysisDirectory, ...
        "flexor_force_time_normalized.png"), ...
    [0 15 30 45]);

localPlotConditionBands( ...
    allNormalized, ...
    "extensor_force_N", ...
    "Extensor force (N)", ...
    "Summed extensor force", ...
    fullfile( ...
        analysisDirectory, ...
        "extensor_force_time_normalized.png"));

localPlotConditionBands( ...
    allNormalized, ...
    "max_abs_reserve_activation", ...
    "Maximum absolute reserve activation", ...
    "Reserve actuator demand", ...
    fullfile( ...
        analysisDirectory, ...
        "reserve_activation_time_normalized.png"));

fprintf("\nSO plotting pipeline complete.\n");


%% ========================================================================
%% LOCAL FUNCTIONS
%% ========================================================================

function resultFile = localFindSingleResultFile( ...
        resultsDirectory, pattern)

    listing = dir(fullfile( ...
        resultsDirectory, ...
        pattern));

    if isempty(listing)
        resultFile = "";
        return;
    end

    assert(numel(listing) == 1, ...
        "SOPlotting:AmbiguousResultFiles", ...
        "Expected one file matching '%s' under:\n%s\n" + ...
        "Found %d.", ...
        pattern, ...
        resultsDirectory, ...
        numel(listing));

    resultFile = string(fullfile( ...
        listing(1).folder, ...
        listing(1).name));
end


function index = localFindTimeColumn(labels)

    index = find(strcmpi(labels, "time"));

    assert(numel(index) == 1, ...
        "SOPlotting:TimeLookupFailed", ...
        "Could not uniquely identify the time column.");
end


function columns = localFindColumns(labels, requestedNames)

    columns = zeros(numel(requestedNames),1);

    for iName = 1:numel(requestedNames)

        match = find( ...
            labels == requestedNames(iName));

        assert(numel(match) == 1, ...
            "SOPlotting:ColumnLookupFailed", ...
            "Could not uniquely locate '%s'.", ...
            requestedNames(iName));

        columns(iName) = match;
    end
end


function localValidateBreaks(breaks, trialName)

    assert(all(isfinite(breaks)), ...
        "SOPlotting:NonfiniteEvents", ...
        "Nonfinite event time found for %s.", ...
        trialName);

    assert(all(diff(breaks) > 0), ...
        "SOPlotting:InvalidEventOrder", ...
        "Event times are not strictly increasing for %s.", ...
        trialName);
end


function grid = localMakePiecewisePercentGrid( ...
        normBreaks, pointsPerPhase)

    assert(numel(pointsPerPhase) == ...
        numel(normBreaks)-1, ...
        "SOPlotting:NormalizationDefinitionMismatch", ...
        "pointsPerPhase must have one fewer element " + ...
        "than normBreaks.");

    grid = [];

    for iPhase = 1:numel(pointsPerPhase)

        thisGrid = linspace( ...
            normBreaks(iPhase), ...
            normBreaks(iPhase+1), ...
            pointsPerPhase(iPhase)+1);

        if iPhase > 1
            thisGrid = thisGrid(2:end);
        end

        grid = [grid, thisGrid]; %#ok<AGROW>
    end

    grid = grid(:);
end


function yNorm = localPiecewiseTimeNormalize( ...
        time, y, rawBreaks, normBreaks, normPercent)

    yNorm = nan(size(normPercent));

    for iPhase = 1:(numel(rawBreaks)-1)

        rawStart = rawBreaks(iPhase);
        rawEnd = rawBreaks(iPhase+1);

        normStart = normBreaks(iPhase);
        normEnd = normBreaks(iPhase+1);

        idxNorm = ...
            normPercent >= normStart & ...
            normPercent <= normEnd;

        if iPhase > 1
            idxNorm = ...
                normPercent > normStart & ...
                normPercent <= normEnd;
        end

        phaseFraction = ...
            (normPercent(idxNorm) - normStart) ./ ...
            (normEnd - normStart);

        queryTime = ...
            rawStart + ...
            phaseFraction .* ...
            (rawEnd - rawStart);

        yNorm(idxNorm) = interp1( ...
            time, ...
            y, ...
            queryTime, ...
            "linear");
    end
end


function localPlotRawForces( ...
        time, flexorForce, extensorForce, netForce, ...
        breaks, trialName, outFile)

    fig = figure( ...
        "Color", "w", ...
        "Name", trialName + " raw SO forces");

    ax = axes(fig);
    hold(ax, "on");

    hFlex = plot(ax, ...
        time, flexorForce, ...
        "LineWidth", 1.8, ...
        "DisplayName", "Flexors");

    hExt = plot(ax, ...
        time, extensorForce, ...
        "LineWidth", 1.8, ...
        "DisplayName", "Extensors");

    hNet = plot(ax, ...
        time, netForce, ...
        "LineWidth", 1.2, ...
        "LineStyle", "--", ...
        "DisplayName", "Flexor - extensor");

    localAddRawPhasePatches(ax, breaks);

    uistack([hFlex hExt hNet], "top");

    xline(ax, breaks(2), "--", ...
        "Lift-off", ...
        "HandleVisibility", "off");

    xline(ax, breaks(3), "--", ...
        "Re-contact", ...
        "HandleVisibility", "off");

    xlabel(ax, "Time (s)");
    ylabel(ax, "Summed muscle force (N)");

    title(ax, ...
        trialName + " — Static Optimization forces", ...
        "Interpreter", "none");

    legend(ax, "Location", "best");
    grid(ax, "on");
    box(ax, "on");

    ylim(ax, [ ...
        0, ...
        localUpperYLimit([ ...
            flexorForce(:); ...
            extensorForce(:); ...
            netForce(:)])]);

    exportgraphics(fig, outFile, ...
        "Resolution", 300);

    close(fig);
end


function localPlotReserveActivations( ...
        time, reserveData, reserveLabels, ...
        sortedReserveLabels, breaks, ...
        trialName, topCount, peakAbsoluteActivation, outFile)

    topCount = min( ...
        topCount, ...
        numel(sortedReserveLabels));

    topLabels = ...
        sortedReserveLabels(1:topCount);

    columns = zeros(topCount,1);

    for iLabel = 1:topCount

        match = find( ...
            reserveLabels == topLabels(iLabel));

        assert(numel(match) == 1, ...
            "SOPlotting:ReserveLookupFailed", ...
            "Could not locate reserve '%s'.", ...
            topLabels(iLabel));

        columns(iLabel) = match;
    end

    fig = figure( ...
        "Color", "w", ...
        "Name", trialName + " reserve activations");

    ax = axes(fig);
    hold(ax, "on");

    lineHandles = gobjects(topCount,1);

    for iColumn = 1:topCount

        lineHandles(iColumn) = plot(ax, ...
            time, ...
            reserveData(:, columns(iColumn)), ...
            "LineWidth", 1.1, ...
            "DisplayName", topLabels(iColumn));
    end

    localAddRawPhasePatches(ax, breaks);

    uistack(lineHandles, "top");

    xline(ax, breaks(2), "--", ...
        "Lift-off", ...
        "HandleVisibility", "off");

    xline(ax, breaks(3), "--", ...
        "Re-contact", ...
        "HandleVisibility", "off");

    yline(ax, 0, ":", ...
        "HandleVisibility", "off");

    xlabel(ax, "Time (s)");
    ylabel(ax, "Activation");

    title(ax, ...
        sprintf( ...
            "%s — top reserve actuators | peak |a| = %.5f", ...
            trialName, ...
            peakAbsoluteActivation), ...
        "Interpreter", "none");

    legend(ax, ...
        "Location", "eastoutside", ...
        "Interpreter", "none");

    grid(ax, "on");
    box(ax, "on");

    ylim(ax, [ ...
        0, ...
        localUpperYLimit( ...
            reserveData(:, columns))]);

    exportgraphics(fig, outFile, ...
        "Resolution", 300);

    close(fig);
end


function localPlotNormalizedTrial( ...
        normalizedTrial, trialName, outFile)

    fig = figure( ...
        "Color", "w", ...
        "Name", trialName + " normalized SO forces");

    ax = axes(fig);
    hold(ax, "on");

    hFlex = plot(ax, ...
        normalizedTrial.norm_percent, ...
        normalizedTrial.flexor_force_N, ...
        "LineWidth", 1.8, ...
        "DisplayName", "Flexors");

    hExt = plot(ax, ...
        normalizedTrial.norm_percent, ...
        normalizedTrial.extensor_force_N, ...
        "LineWidth", 1.8, ...
        "DisplayName", "Extensors");

    hNet = plot(ax, ...
        normalizedTrial.norm_percent, ...
        normalizedTrial.net_flexor_minus_extensor_N, ...
        "LineWidth", 1.2, ...
        "LineStyle", "--", ...
        "DisplayName", "Flexor - extensor");

    localAddNormalizedPhasePatches(ax);

    uistack([hFlex hExt hNet], "top");

    xline(ax, 20, "--", ...
        "Lift-off", ...
        "HandleVisibility", "off");

    xline(ax, 80, "--", ...
        "Re-contact", ...
        "HandleVisibility", "off");

    xlabel(ax, "Normalized task time (%)");
    ylabel(ax, "Summed muscle force (N)");

    title(ax, ...
        trialName + " — event-normalized SO forces", ...
        "Interpreter", "none");

    legend(ax, "Location", "best");
    grid(ax, "on");
    box(ax, "on");

    ylim(ax, [ ...
        0, ...
        localUpperYLimit([ ...
            normalizedTrial.flexor_force_N(:); ...
            normalizedTrial.extensor_force_N(:); ...
            normalizedTrial.net_flexor_minus_extensor_N(:)])]);

    exportgraphics(fig, outFile, ...
        "Resolution", 300);

    close(fig);
end


function localPlotConditionBands( ...
        T, valueVariable, yLabelText, ...
        figureTitle, outFile, legendConditionOrder)

    if nargin < 6
        legendConditionOrder = [];
    end

    conditions = unique(T.condition_deg);
    conditions = conditions(isfinite(conditions));

    fig = figure( ...
        "Color", "w", ...
        "Name", figureTitle);

    ax = axes(fig);
    hold(ax, "on");

    allLineHandles = gobjects(numel(conditions),1);
    maxPlottedValue = 0;

    for iCondition = 1:numel(conditions)

        conditionDeg = ...
            conditions(iCondition);

        thisT = T( ...
            T.condition_deg == conditionDeg, ...
            :);

        [groupIndex, normValues] = ...
            findgroups(thisT.norm_percent);

        meanValue = splitapply( ...
            @(x) mean(x, "omitnan"), ...
            thisT.(valueVariable), ...
            groupIndex);

        sdValue = splitapply( ...
            @(x) std(x, "omitnan"), ...
            thisT.(valueVariable), ...
            groupIndex);

        upperBand = meanValue + sdValue;
        finiteUpperBand = upperBand(isfinite(upperBand));

        if ~isempty(finiteUpperBand)
            maxPlottedValue = max( ...
                maxPlottedValue, ...
                max(finiteUpperBand));
        end

        allLineHandles(iCondition) = plot(ax, ...
            normValues, ...
            meanValue, ...
            "LineWidth", 2, ...
            "DisplayName", ...
            sprintf("%g°", conditionDeg));

        lineColor = ...
            allLineHandles(iCondition).Color;

        fill(ax, ...
            [normValues; flipud(normValues)], ...
            [ ...
                meanValue - sdValue
                flipud(meanValue + sdValue)
            ], ...
            lineColor, ...
            "FaceAlpha", 0.18, ...
            "EdgeColor", "none", ...
            "HandleVisibility", "off");
    end

    localAddNormalizedPhasePatches(ax);

    uistack(allLineHandles, "top");

    xline(ax, 20, "--", ...
        "Lift-off", ...
        "HandleVisibility", "off");

    xline(ax, 80, "--", ...
        "Re-contact", ...
        "HandleVisibility", "off");

    xlabel(ax, "Normalized task time (%)");
    ylabel(ax, yLabelText);
    title(ax, figureTitle);

    if isempty(legendConditionOrder)

        legend(ax, ...
            allLineHandles, ...
            arrayfun( ...
                @(x) sprintf("%g°", x), ...
                conditions, ...
                "UniformOutput", false), ...
            "Location", "best");

    else

        legendHandles = gobjects(0,1);
        legendLabels = strings(0,1);

        for requestedCondition = legendConditionOrder(:).'

            match = find( ...
                conditions == requestedCondition, ...
                1, ...
                "first");

            if isempty(match)
                continue;
            end

            legendHandles(end+1,1) = ...
                allLineHandles(match); %#ok<AGROW>

            legendLabels(end+1,1) = ...
                sprintf("%g°", requestedCondition); %#ok<AGROW>
        end

        legend(ax, ...
            legendHandles, ...
            cellstr(legendLabels), ...
            "Location", "best");
    end

    grid(ax, "on");
    box(ax, "on");

    ylim(ax, [ ...
        0, ...
        localUpperYLimit(maxPlottedValue)]);

    exportgraphics(fig, outFile, ...
        "Resolution", 300);

    close(fig);
end


function upperLimit = localUpperYLimit(values)
%LOCALUPPERYLIMIT Return an automatic positive y-axis ceiling.
%
% The caller fixes the lower limit at zero. The upper limit is 5% above
% the largest finite plotted value. If the plotted data contain no
% positive finite values, use 1 as a safe fallback.

    values = double(values(:));
    values = values(isfinite(values));

    if isempty(values)
        maximumValue = 0;
    else
        maximumValue = max(values);
    end

    if maximumValue > 0
        upperLimit = 1.05 * maximumValue;
    else
        upperLimit = 1;
    end
end


function localAddRawPhasePatches(ax, breaks)

    yLimits = ylim(ax);

    ranges = [ ...
        breaks(1) breaks(2)
        breaks(2) breaks(3)
        breaks(3) breaks(4)
    ];

    colors = [ ...
        0.88 0.93 1.00
        0.94 0.94 0.94
        1.00 0.93 0.88
    ];

    for iPhase = 1:3

        h = patch(ax, ...
            [ ...
                ranges(iPhase,1)
                ranges(iPhase,2)
                ranges(iPhase,2)
                ranges(iPhase,1)
            ], ...
            [ ...
                yLimits(1)
                yLimits(1)
                yLimits(2)
                yLimits(2)
            ], ...
            colors(iPhase,:), ...
            "FaceAlpha", 0.16, ...
            "EdgeColor", "none", ...
            "HandleVisibility", "off");

        uistack(h, "bottom");
    end

    ylim(ax, yLimits);
end


function localAddNormalizedPhasePatches(ax)

    yLimits = ylim(ax);

    ranges = [ ...
        0 20
        20 80
        80 100
    ];

    colors = [ ...
        0.88 0.93 1.00
        0.94 0.94 0.94
        1.00 0.93 0.88
    ];

    for iPhase = 1:3

        h = patch(ax, ...
            [ ...
                ranges(iPhase,1)
                ranges(iPhase,2)
                ranges(iPhase,2)
                ranges(iPhase,1)
            ], ...
            [ ...
                yLimits(1)
                yLimits(1)
                yLimits(2)
                yLimits(2)
            ], ...
            colors(iPhase,:), ...
            "FaceAlpha", 0.16, ...
            "EdgeColor", "none", ...
            "HandleVisibility", "off");

        uistack(h, "bottom");
    end

    ylim(ax, yLimits);
end