%% run_single_trial_static_optimization.m
% Thin single-trial driver for Process 4:
%   execute and audit Static Optimization.
%
% The pipeline implementation lives in:
%
%   pipeline.resolveTrialContext
%   pipeline.runStaticOptimizationTrial
%
% This script contains only orchestration and interactive review choices.
% Batch Process 4 calls the same worker.

%% SECTION 0 — PROJECT CONFIGURATION

clear;
clc;
dbstop if error

projectCfg = ...
    load_project_config();

fprintf( ...
    "Project root:\n%s\n", ...
    projectCfg.projectRoot);

%% SECTION 1 — SELECT TRIAL

conditionDeg = 45;
trialNumber = 1;

trial = ...
    pipeline.resolveTrialContext( ...
        projectCfg, ...
        conditionDeg, ...
        trialNumber);

fprintf( ...
    "Resolved %s.\n", ...
    trial.DisplayName);

fprintf( ...
    "Process-3 checkpoint:\n%s\n", ...
    trial.Paths.StaticOptimizationPrep.CheckpointFile);

fprintf( ...
    "Static Optimization setup:\n%s\n", ...
    trial.Paths.StaticOptimization.SetupFile);

%% SECTION 2 — RUN PROCESS 4

runCfg = struct;

runCfg.executeStaticOptimization = ...
    true;

runCfg.overwrite = ...
    projectCfg.overwriteExisting;

result = ...
    pipeline.runStaticOptimizationTrial( ...
        projectCfg, ...
        trial, ...
        "ExecuteStaticOptimization", ...
            runCfg.executeStaticOptimization, ...
        "Overwrite", ...
            runCfg.overwrite, ...
        "WriteQc", ...
            true, ...
        "SaveCheckpoint", ...
            true, ...
        "PrintProgress", ...
            true);

%% SECTION 3 — REVIEW

if result.Completed

    fprintf( ...
        "\nStatic Optimization Process 4 completed.\n");

    fprintf( ...
        "Force output:\n%s\n", ...
        result.ForceFile);

    fprintf( ...
        "Activation output:\n%s\n", ...
        result.ActivationFile);

    fprintf( ...
        "Output audit:\n%s\n", ...
        result.Paths.OutputAuditCsv);

    fprintf( ...
        "Checkpoint:\n%s\n", ...
        result.CheckpointFile);

    fprintf( ...
        "\nStatic Optimization output audit:\n");

    disp(result.OutputAudit);

    fprintf( ...
        "\nNEXT REVIEW STEPS\n");

    fprintf( ...
        "1. Run the aggregate SO plotting/statistics pipeline.\n");

    fprintf( ...
        "2. Confirm flexion/extension ObjectGroup membership.\n");

    fprintf( ...
        "3. Confirm reserve activation remains appropriately small.\n");

    fprintf( ...
        "4. Review force timing and magnitudes for expected behavior.\n");

else

    fprintf( ...
        "\nStatic Optimization execution was disabled. " + ...
        "Process-3 prerequisites and the SO setup passed validation.\n");
end
