%% run_single_trial_model_b.m
% Single-trial validation driver: lock extraction, Model B, and final IK.
%
% Run this script one section at a time. It resumes from the Phase A
% initialization-IK checkpoint and intentionally stops after final-IK QC.
%
% REQUIRED TOOLKIT COMPONENTS
%   load_project_config.m
%   +opensimio
%   +modelprep
%   +opensimrun
%
% REQUIRED PHASE A OUTPUT
%   initialization_ik_checkpoint.mat
%
% MODEL B CONFIGURATION
%   - Coordinate-coupler constraints enabled
%   - Root coordinates locked
%   - Independent roll/yaw coordinates locked
%   - Dependent auxiliary r1/r2 coordinates unlocked but constrained
%   - Sagittal coordinates unlocked

%% SECTION 0 — LOAD PROJECT AND TRIAL CONFIGURATION

clear;
clc;
dbstop if error

% Live Editor evaluates sections through a temporary helper file, so prefer
% the active Editor document when locating the repository.
activeFile = string(matlab.desktop.editor.getActiveFilename);

if strlength(activeFile) > 0 && isfile(activeFile)
    scriptFile = activeFile;
else
    scriptFile = string(mfilename("fullpath"));
end

assert(strlength(scriptFile) > 0 && isfile(scriptFile), ...
    "ModelBPipeline:ScriptLocationUnknown", ...
    ["Save and open this script in the MATLAB Editor before running " ...
     "its sections."]);

examplesDirectory = string(fileparts(scriptFile));
projectRoot = string(fileparts(examplesDirectory));

assert(isfolder(fullfile(projectRoot, "+modelprep")), ...
    "ModelBPipeline:ProjectRootNotFound", ...
    ["The inferred project root does not contain +modelprep:\n%s\n\n" ...
     "Save this script under the repository's examples folder."], ...
    projectRoot);

addpath(projectRoot);

projectCfg = load_project_config();

assert(string(projectCfg.projectRoot) == projectRoot, ...
    "ModelBPipeline:ProjectRootMismatch", ...
    ["Script-inferred project root:\n%s\n\n" ...
     "Configuration project root:\n%s"], ...
    projectRoot, projectCfg.projectRoot);

trialCfg = struct;

% Trial identity.
trialCfg.conditionDeg = 0;
trialCfg.trialNumber = 1;

% Initial support interval used to extract the Model B lock values.
% Review this interval for each trial before running Section 4.
trialCfg.lockWindow = [0.00, 0.25];

% Leave empty to use the Phase A checkpoint marker-file path.
% Set an explicit local path when the checkpoint was created elsewhere.
trialCfg.markerFile = "";

% Execution controls.
trialCfg.overwriteExisting = projectCfg.overwriteExisting;
trialCfg.executeFinalIk = false;

fprintf( ...
    "Machine: %s\nCondition: %g deg\nTrial: %d\n", ...
    projectCfg.machineName, ...
    trialCfg.conditionDeg, ...
    trialCfg.trialNumber);


%% SECTION 1 — RESOLVE PHASE A AND MODEL B PATHS

conditionFolderName = sprintf( ...
    "%02ddeg", round(trialCfg.conditionDeg));

trialFolderName = sprintf( ...
    "trial%02d", trialCfg.trialNumber);

trialRoot = string(fullfile( ...
    projectCfg.outputRoot, ...
    conditionFolderName, ...
    trialFolderName));

phaseADirectory = string(fullfile( ...
    trialRoot, ...
    "01_initialization_ik"));

phaseAQcDirectory = string(fullfile( ...
    phaseADirectory, ...
    "qc"));

phaseBDirectory = string(fullfile( ...
    trialRoot, ...
    "02_locked_final_ik"));

phaseBQcDirectory = string(fullfile( ...
    phaseBDirectory, ...
    "qc"));

if ~isfolder(phaseBDirectory)
    mkdir(phaseBDirectory);
end

if ~isfolder(phaseBQcDirectory)
    mkdir(phaseBQcDirectory);
end

paths = struct;

paths.trialRoot = trialRoot;
paths.phaseADirectory = phaseADirectory;
paths.phaseAQcDirectory = phaseAQcDirectory;
paths.phaseBDirectory = phaseBDirectory;
paths.phaseBQcDirectory = phaseBQcDirectory;

paths.initializationCheckpointFile = string(fullfile( ...
    phaseAQcDirectory, ...
    "initialization_ik_checkpoint.mat"));

paths.modelAFile = string(fullfile( ...
    phaseADirectory, ...
    sprintf("%s_%s_modelA_initialization.osim", ...
    conditionFolderName, trialFolderName)));

paths.initialIkMotionFile = string(fullfile( ...
    phaseADirectory, ...
    sprintf("%s_%s_initialization_ik.mot", ...
    conditionFolderName, trialFolderName)));

paths.modelBFile = string(fullfile( ...
    phaseBDirectory, ...
    sprintf("%s_%s_modelB_locked_ik.osim", ...
    conditionFolderName, trialFolderName)));

paths.finalIkSetupFile = string(fullfile( ...
    phaseBDirectory, ...
    sprintf("%s_%s_final_ik_setup.xml", ...
    conditionFolderName, trialFolderName)));

paths.finalIkMotionFile = string(fullfile( ...
    phaseBDirectory, ...
    sprintf("%s_%s_final_ik.mot", ...
    conditionFolderName, trialFolderName)));

paths.lockValuesCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "modelB_lock_values.csv"));

paths.modelBCoordinateConfigurationCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "modelB_coordinate_configuration.csv"));

paths.modelBConstraintConfigurationCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "modelB_constraint_configuration.csv"));

paths.modelBDependentCoordinateStateCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "modelB_dependent_coordinate_state.csv"));

paths.lockedCoordinateAuditCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "final_ik_locked_coordinate_audit.csv"));

paths.dependentCoordinateAuditCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "final_ik_dependent_coordinate_audit.csv"));

paths.sagittalCoordinateAuditCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "final_ik_sagittal_coordinate_audit.csv"));

paths.runSummaryMat = string(fullfile( ...
    phaseBQcDirectory, ...
    "model_b_final_ik_checkpoint.mat"));

disp(paths);


%% SECTION 2 — LOAD AND VALIDATE THE PHASE A CHECKPOINT

assert(isfile(paths.initializationCheckpointFile), ...
    "ModelBPipeline:CheckpointMissing", ...
    "Phase A checkpoint was not found:\n%s", ...
    paths.initializationCheckpointFile);

loadedCheckpoint = load( ...
    paths.initializationCheckpointFile, ...
    "checkpoint");

assert(isfield(loadedCheckpoint, "checkpoint"), ...
    "ModelBPipeline:CheckpointVariableMissing", ...
    "The MAT file does not contain a variable named checkpoint.");

checkpointA = loadedCheckpoint.checkpoint;

requiredCheckpointFields = [ ...
    "Configuration"
    "Paths"
    "ModelAValidation"
    "IkMotionSummary"
    "IkRunResult"
];

for fieldName = requiredCheckpointFields.'
    assert(isfield(checkpointA, fieldName), ...
        "ModelBPipeline:CheckpointFieldMissing", ...
        "Phase A checkpoint is missing field: %s", ...
        fieldName);
end

assert(logical(checkpointA.ModelAValidation.Passed), ...
    "ModelBPipeline:ModelAWasInvalid", ...
    "The Phase A checkpoint reports that Model A failed validation.");

assert(logical(checkpointA.IkRunResult.RunSucceeded), ...
    "ModelBPipeline:InitializationIkFailed", ...
    "The Phase A checkpoint reports that initialization IK failed.");

assert( ...
    checkpointA.Configuration.conditionDeg == ...
        trialCfg.conditionDeg, ...
    "ModelBPipeline:ConditionMismatch", ...
    ["Configured condition is %g deg, but the checkpoint is for " ...
     "%g deg."], ...
    trialCfg.conditionDeg, ...
    checkpointA.Configuration.conditionDeg);

assert( ...
    checkpointA.Configuration.trialNumber == ...
        trialCfg.trialNumber, ...
    "ModelBPipeline:TrialMismatch", ...
    ["Configured trial is %d, but the checkpoint is for trial %d."], ...
    trialCfg.trialNumber, ...
    checkpointA.Configuration.trialNumber);

assert(isfile(paths.modelAFile), ...
    "ModelBPipeline:ModelAMissing", ...
    "Model A was not found:\n%s", ...
    paths.modelAFile);

assert(isfile(paths.initialIkMotionFile), ...
    "ModelBPipeline:InitializationMotionMissing", ...
    "Initialization IK motion was not found:\n%s", ...
    paths.initialIkMotionFile);

assert(isfile(projectCfg.kinematicBaseModel), ...
    "ModelBPipeline:BaseModelMissing", ...
    "Configured kinematic base model was not found:\n%s", ...
    projectCfg.kinematicBaseModel);

assert(isfile(projectCfg.initializationIkTemplate), ...
    "ModelBPipeline:IkTemplateMissing", ...
    "Configured IK template was not found:\n%s", ...
    projectCfg.initializationIkTemplate);

if strlength(string(trialCfg.markerFile)) == 0
    markerFile = string(checkpointA.Configuration.markerFile);
else
    markerFile = string(trialCfg.markerFile);
end

assert(isfile(markerFile), ...
    "ModelBPipeline:MarkerFileMissing", ...
    ["Marker file was not found:\n%s\n\n" ...
     "If the checkpoint came from another computer, set " ...
     "trialCfg.markerFile to the local marker-file path."], ...
    markerFile);

trialTimeRange = [ ...
    checkpointA.IkMotionSummary.StartTime, ...
    checkpointA.IkMotionSummary.EndTime];

assert( ...
    trialCfg.lockWindow(1) >= trialTimeRange(1) && ...
    trialCfg.lockWindow(2) <= trialTimeRange(2) && ...
    trialCfg.lockWindow(2) > trialCfg.lockWindow(1), ...
    "ModelBPipeline:InvalidLockWindow", ...
    ["Lock window [%.9g, %.9g] must lie within the trial range " ...
     "[%.9g, %.9g]."], ...
    trialCfg.lockWindow(1), ...
    trialCfg.lockWindow(2), ...
    trialTimeRange(1), ...
    trialTimeRange(2));

fprintf( ...
    "Phase A checkpoint validated. Trial range: %.5f to %.5f s.\n", ...
    trialTimeRange(1), trialTimeRange(2));


%% SECTION 3 — LOAD SHARED QC SETTINGS

assert(isfield(projectCfg, "qc"), ...
    "ModelBPipeline:QcConfigMissing", ...
    "projectCfg.qc is not defined in project_defaults.m.");

assert(isfield(projectCfg.qc, "lockExtraction"), ...
    "ModelBPipeline:LockExtractionConfigMissing", ...
    ["projectCfg.qc.lockExtraction is not defined. Add the " ...
     "Model B QC block to config/project_defaults.m."]);

assert(isfield(projectCfg.qc, "lockAudit"), ...
    "ModelBPipeline:LockAuditConfigMissing", ...
    ["projectCfg.qc.lockAudit is not defined. Add the locked-coordinate " ...
     "audit block to config/project_defaults.m."]);

extractionQc = projectCfg.qc.lockExtraction;
auditQc = projectCfg.qc.lockAudit;

requiredExtractionFields = [ ...
    "method"
    "rotationToleranceDeg"
    "translationToleranceM"
    "otherToleranceSI"
    "minimumSamples"
    "requireStable"
];

for fieldName = requiredExtractionFields.'
    assert(isfield(extractionQc, fieldName), ...
        "ModelBPipeline:LockExtractionFieldMissing", ...
        "Missing projectCfg.qc.lockExtraction.%s", ...
        fieldName);
end

requiredAuditFields = [ ...
    "statistic"
    "rotationRangeToleranceDeg"
    "translationRangeToleranceM"
    "otherRangeToleranceSI"
    "rotationMatchToleranceDeg"
    "translationMatchToleranceM"
    "otherMatchToleranceSI"
    "minimumSamples"
    "requirePass"
];

for fieldName = requiredAuditFields.'
    assert(isfield(auditQc, fieldName), ...
        "ModelBPipeline:LockAuditFieldMissing", ...
        "Missing projectCfg.qc.lockAudit.%s", ...
        fieldName);
end

disp(extractionQc);
disp(auditQc);


%% SECTION 4 — EXTRACT TRIAL-SPECIFIC MODEL B LOCK VALUES

groups = modelprep.coordinateGroups();

lockValues = modelprep.extractStableCoordinateValues( ...
    paths.initialIkMotionFile, ...
    paths.modelAFile, ...
    groups.FinalIkLocked, ...
    trialCfg.lockWindow, ...
    "Method", extractionQc.method, ...
    "RotationToleranceDeg", ...
        extractionQc.rotationToleranceDeg, ...
    "TranslationToleranceM", ...
        extractionQc.translationToleranceM, ...
    "OtherTolerance", ...
        extractionQc.otherToleranceSI, ...
    "RequireStable", false, ...
    "MinimumSamples", ...
        extractionQc.minimumSamples);

writetable(lockValues, paths.lockValuesCsv);

disp(lockValues);

if any(~lockValues.IsStable)
    unstableCoordinates = ...
        lockValues.Coordinate(~lockValues.IsStable);

    fprintf( ...
        "\nCoordinates exceeding the extraction tolerance:\n%s\n", ...
        strjoin(unstableCoordinates, ", "));
end

if extractionQc.requireStable
    assert(all(lockValues.IsStable), ...
        "ModelBPipeline:UnstableLockValues", ...
        ["One or more coordinates are unstable in the selected window. " ...
         "Review modelB_lock_values.csv or choose another lock window."]);
end

fprintf( ...
    "Lock values extracted from [%.5f, %.5f] s and saved:\n%s\n", ...
    trialCfg.lockWindow(1), ...
    trialCfg.lockWindow(2), ...
    paths.lockValuesCsv);

% CHECKPOINT:
% Review modelB_lock_values.csv before running Section 5. The six root
% coordinates and four independent roll/yaw coordinates should represent
% the supported initial pose.


%% SECTION 5 — BUILD MODEL B

if isfile(paths.modelBFile) && ~trialCfg.overwriteExisting
    error("ModelBPipeline:OutputExists", ...
        "Model B already exists:\n%s", ...
        paths.modelBFile);
end

modelBResult = modelprep.buildLockedIkModel( ...
    projectCfg.kinematicBaseModel, ...
    lockValues, ...
    paths.modelBFile, ...
    "CoordinateNames", groups.FinalIkLocked, ...
    "RequireStable", extractionQc.requireStable);

writetable( ...
    modelBResult.Inspection.Coordinates, ...
    paths.modelBCoordinateConfigurationCsv);

writetable( ...
    modelBResult.Inspection.Constraints, ...
    paths.modelBConstraintConfigurationCsv);

fprintf("Model B written:\n%s\n", paths.modelBFile);


%% SECTION 6 — VALIDATE MODEL B CONFIGURATION

modelBInspection = modelprep.inspectModel(paths.modelBFile);

allCoordinateNames = ...
    modelBInspection.Coordinates.Coordinate;

expectedUnlocked = setdiff( ...
    allCoordinateNames, ...
    groups.FinalIkLocked, ...
    "stable");

modelBValidation = modelprep.validateModelConfiguration( ...
    paths.modelBFile, ...
    "ExpectedLocked", groups.FinalIkLocked, ...
    "ExpectedUnlocked", expectedUnlocked, ...
    "ExpectedConstraintsEnforced", true, ...
    "ThrowOnFailure", true);

assert(modelBValidation.Passed, ...
    "ModelBPipeline:ModelBValidationFailed", ...
    "Model B configuration validation failed.");

dependentRows = ismember( ...
    modelBInspection.Coordinates.Coordinate, ...
    groups.DependentOutOfPlane);

dependentCoordinateState = ...
    modelBInspection.Coordinates(dependentRows, { ...
        'Coordinate'
        'DefaultLocked'
        'StateLocked'
        'StateDependent'
        'StateConstrained'
    });

writetable( ...
    dependentCoordinateState, ...
    paths.modelBDependentCoordinateStateCsv);

disp(dependentCoordinateState);

assert(all(~dependentCoordinateState.DefaultLocked), ...
    "ModelBPipeline:DependentCoordinateLocked", ...
    ["One or more dependent auxiliary coordinates are default-locked. " ...
     "They should be governed by the enabled couplers."]);

assert(all(dependentCoordinateState.StateConstrained), ...
    "ModelBPipeline:DependentCoordinateUnconstrained", ...
    ["One or more dependent auxiliary coordinates are not constrained " ...
     "in Model B. Review the coupler configuration."]);

fprintf([ ...
    "Model B validation passed: requested coordinates locked, " ...
    "dependent coordinates constrained, and couplers enabled.\n"]);


%% SECTION 7 — CREATE THE FINAL-IK SETUP

if isfile(paths.finalIkSetupFile) && ...
        ~trialCfg.overwriteExisting
    error("ModelBPipeline:OutputExists", ...
        "Final-IK setup already exists:\n%s", ...
        paths.finalIkSetupFile);
end

finalIkSetupResult = ...
    opensimrun.prepareInverseKinematicsSetup( ...
    projectCfg.initializationIkTemplate, ...
    paths.finalIkSetupFile, ...
    "ModelFile", paths.modelBFile, ...
    "MarkerFile", markerFile, ...
    "OutputMotionFile", paths.finalIkMotionFile, ...
    "TimeRange", trialTimeRange, ...
    "ToolName", sprintf( ...
        "%s_%s_final_ik", ...
        conditionFolderName, trialFolderName), ...
    "Overwrite", trialCfg.overwriteExisting);

disp(finalIkSetupResult.PatchReport);

fprintf("Final-IK setup written:\n%s\n", ...
    paths.finalIkSetupFile);

% CHECKPOINT:
% Open the generated XML before running Section 8. Confirm the marker task
% set, weights, time range, output path, constraint weight, and accuracy.


%% SECTION 8 — RUN FINAL IK WITH MODEL B

if ~trialCfg.executeFinalIk
    fprintf([ ...
        "Final IK execution is disabled. Review the setup XML, then set " ...
        "trialCfg.executeFinalIk=true and rerun this section.\n"]);
else
    finalIkRunResult = ...
        opensimrun.runInverseKinematicsSetup( ...
        paths.finalIkSetupFile, ...
        "ModelInput", paths.modelBFile, ...
        "ExpectedOutputMotionFile", ...
            paths.finalIkMotionFile, ...
        "Overwrite", trialCfg.overwriteExisting);

    fprintf( ...
        "Final IK completed in %.3f seconds.\n", ...
        finalIkRunResult.DurationSeconds);

    fprintf("Final IK motion file:\n%s\n", ...
        finalIkRunResult.OutputMotionFile);
end


%% SECTION 9 — AUDIT LOCKED COORDINATES

assert(isfile(paths.finalIkMotionFile), ...
    "ModelBPipeline:FinalIkMotionMissing", ...
    "Final IK output was not found:\n%s", ...
    paths.finalIkMotionFile);

lockedCoordinateAudit = ...
    modelprep.auditLockedCoordinates( ...
    paths.finalIkMotionFile, ...
    lockValues, ...
    "ModelInput", paths.modelBFile, ...
    "TimeWindow", trialTimeRange, ...
    "Statistic", auditQc.statistic, ...
    "RotationRangeToleranceDeg", ...
        auditQc.rotationRangeToleranceDeg, ...
    "TranslationRangeToleranceM", ...
        auditQc.translationRangeToleranceM, ...
    "OtherRangeToleranceSI", ...
        auditQc.otherRangeToleranceSI, ...
    "RotationMatchToleranceDeg", ...
        auditQc.rotationMatchToleranceDeg, ...
    "TranslationMatchToleranceM", ...
        auditQc.translationMatchToleranceM, ...
    "OtherMatchToleranceSI", ...
        auditQc.otherMatchToleranceSI, ...
    "MinimumSamples", auditQc.minimumSamples, ...
    "RequirePass", false);

writetable( ...
    lockedCoordinateAudit.Table, ...
    paths.lockedCoordinateAuditCsv);

disp(lockedCoordinateAudit.Table);

fprintf( ...
    "Locked-coordinate audit: %d/%d passed.\n", ...
    lockedCoordinateAudit.NumPassed, ...
    lockedCoordinateAudit.NumCoordinates);

if auditQc.requirePass
    assert(lockedCoordinateAudit.Passed, ...
        "ModelBPipeline:LockedCoordinateAuditFailed", ...
        "Locked coordinates failed QC: %s", ...
        strjoin( ...
        lockedCoordinateAudit.FailedCoordinates, ...
        ", "));
end


%% SECTION 10 — AUDIT DEPENDENT AND SAGITTAL COORDINATES

dependentCoordinateAudit = ...
    modelprep.extractStableCoordinateValues( ...
    paths.finalIkMotionFile, ...
    paths.modelBFile, ...
    groups.DependentOutOfPlane, ...
    trialTimeRange, ...
    "Method", auditQc.statistic, ...
    "RotationToleranceDeg", ...
        auditQc.rotationRangeToleranceDeg, ...
    "TranslationToleranceM", ...
        auditQc.translationRangeToleranceM, ...
    "OtherTolerance", ...
        auditQc.otherRangeToleranceSI, ...
    "RequireStable", false, ...
    "MinimumSamples", auditQc.minimumSamples);

writetable( ...
    dependentCoordinateAudit, ...
    paths.dependentCoordinateAuditCsv);

disp(dependentCoordinateAudit);

if auditQc.requirePass
    assert(all(dependentCoordinateAudit.IsStable), ...
        "ModelBPipeline:DependentCoordinateAuditFailed", ...
        ["One or more coupler-dependent out-of-plane coordinates varied " ...
         "during final IK. Review final_ik_dependent_coordinate_audit.csv."]);
end

sagittalCoordinateAudit = ...
    modelprep.extractStableCoordinateValues( ...
    paths.finalIkMotionFile, ...
    paths.modelBFile, ...
    groups.Sagittal, ...
    trialTimeRange, ...
    "Method", "median", ...
    "RequireStable", false, ...
    "MinimumSamples", auditQc.minimumSamples);

writetable( ...
    sagittalCoordinateAudit, ...
    paths.sagittalCoordinateAuditCsv);

fprintf("\nSagittal coordinate ranges for visual review:\n");
disp(sagittalCoordinateAudit(:, { ...
    'Coordinate'
    'MinimumDisplay'
    'MaximumDisplay'
    'RangeDisplay'
    'DisplayUnit'
}));

% CHECKPOINT:
% Open Model B and the final IK motion in OpenSim. Review marker fit,
% C4-C5 sagittal motion, and the absence of out-of-plane excursions.


%% SECTION 11 — SAVE THE MODEL B CHECKPOINT

finalIkMotion = opensimio.readMot( ...
    paths.finalIkMotionFile);

modelBCheckpoint = struct;

modelBCheckpoint.Configuration = trialCfg;
modelBCheckpoint.ProjectRoot = ...
    string(projectCfg.projectRoot);
modelBCheckpoint.InitializationCheckpointFile = ...
    paths.initializationCheckpointFile;
modelBCheckpoint.Paths = paths;
modelBCheckpoint.MarkerFile = markerFile;
modelBCheckpoint.TrialTimeRange = trialTimeRange;
modelBCheckpoint.LockValues = lockValues;
modelBCheckpoint.ModelBResult = modelBResult;
modelBCheckpoint.ModelBValidation = modelBValidation;
modelBCheckpoint.FinalIkSetupResult = finalIkSetupResult;

modelBCheckpoint.FinalIkMotionSummary = struct( ...
    "NumRows", finalIkMotion.NumRows, ...
    "NumColumns", finalIkMotion.NumColumns, ...
    "StartTime", finalIkMotion.Time(1), ...
    "EndTime", finalIkMotion.Time(end), ...
    "InDegrees", finalIkMotion.InDegrees);

if exist("finalIkRunResult", "var")
    modelBCheckpoint.FinalIkRunSummary = struct( ...
        "SetupFile", finalIkRunResult.SetupFile, ...
        "OutputMotionFile", ...
            finalIkRunResult.OutputMotionFile, ...
        "ModelSource", finalIkRunResult.ModelSource, ...
        "RunSucceeded", ...
            finalIkRunResult.RunSucceeded, ...
        "DurationSeconds", ...
            finalIkRunResult.DurationSeconds);
end

modelBCheckpoint.LockedCoordinateAudit = ...
    lockedCoordinateAudit;
modelBCheckpoint.DependentCoordinateAudit = ...
    dependentCoordinateAudit;
modelBCheckpoint.SagittalCoordinateAudit = ...
    sagittalCoordinateAudit;

save( ...
    paths.runSummaryMat, ...
    "modelBCheckpoint", ...
    "-v7.3");

fprintf("\nModel B checkpoint saved:\n%s\n", ...
    paths.runSummaryMat);

fprintf("\nNEXT MANUAL CHECKS\n");
fprintf("1. Open Model B and the final IK motion in OpenSim.\n");
fprintf("2. Review marker RMS and maximum errors in the OpenSim log.\n");
fprintf("3. Confirm all ten locked coordinates remain constant.\n");
fprintf("4. Confirm dependent auxiliary r1/r2 coordinates remain constant.\n");
fprintf("5. Review C4-C5 and all sagittal coordinate trajectories.\n");
fprintf("6. If acceptable, proceed to Model C and HSF generation.\n");
