%% run_single_trial_model_b_filtered.m
% Thin single-trial driver for Process 2:
%   lock extraction + Model B + final inverse kinematics.
%
% The pipeline implementation lives in:
%
%   pipeline.resolveTrialContext
%   pipeline.runModelBTrial
%
% This script contains only orchestration and interactive review choices.
% Batch Process 2 calls the same worker.

%% SECTION 0 — PROJECT CONFIGURATION

clear;
clc;
dbstop if error

projectCfg = ...
    load_project_config();

fprintf( ...
    "Project root:\n%s\n", ...
    projectCfg.projectRoot);

%% SECTION 1 — SELECT TRIAL

conditionDeg = 45;
trialNumber = 1;

trial = ...
    pipeline.resolveTrialContext( ...
        projectCfg, ...
        conditionDeg, ...
        trialNumber);

fprintf( ...
    "Resolved %s.\n", ...
    trial.DisplayName);

fprintf( ...
    "Process-1 checkpoint:\n%s\n", ...
    trial.Paths.Initialization.CheckpointFile);

fprintf( ...
    "Process-2 output directory:\n%s\n", ...
    trial.Paths.ModelB.Directory);

%% SECTION 2 — RUN PROCESS 2

runCfg = struct;

runCfg.executeFinalIk = true;

runCfg.overwrite = ...
    projectCfg.overwriteExisting;

result = ...
    pipeline.runModelBTrial( ...
        projectCfg, ...
        trial, ...
        "ExecuteFinalIk", ...
            runCfg.executeFinalIk, ...
        "Overwrite", ...
            runCfg.overwrite, ...
        "WriteQc", ...
            true, ...
        "SaveCheckpoint", ...
            true, ...
        "PrintProgress", ...
            true);

%% SECTION 3 — REVIEW

if result.Completed

    fprintf( ...
        "\nModel-B / final-IK Process 2 completed.\n");

    fprintf( ...
        "Model B:\n%s\n", ...
        result.Paths.ModelBFile);

    fprintf( ...
        "Final IK motion:\n%s\n", ...
        result.Paths.FinalIkMotionFile);

    fprintf( ...
        "Checkpoint:\n%s\n", ...
        result.CheckpointFile);

    fprintf( ...
        "\nLocked-coordinate audit:\n");

    disp(result.LockedCoordinateAudit.Table);

    fprintf( ...
        "\nDependent out-of-plane behavior:\n");

    disp( ...
        result.DependentOutOfPlaneSummary.Summary(:, { ...
            'Coordinate'
            'BaselineValue'
            'Minimum'
            'Maximum'
            'Range'
            'PeakAbsoluteExcursionFromBaseline'
        }));

    fprintf( ...
        "\nIndependent sagittal driver motion:\n");

    disp( ...
        result.IndependentSagittalSummary.Summary(:, { ...
            'Coordinate'
            'BaselineValue'
            'Minimum'
            'Maximum'
            'Range'
            'PeakAbsoluteExcursionFromBaseline'
        }));

    fprintf( ...
        "\nDependent sagittal motion:\n");

    disp( ...
        result.DependentSagittalSummary.Summary(:, { ...
            'Coordinate'
            'BaselineValue'
            'Minimum'
            'Maximum'
            'Range'
            'PeakAbsoluteExcursionFromBaseline'
        }));

    fprintf( ...
        "\nNEXT MANUAL CHECKS\n");

    fprintf( ...
        "1. Open Model B with the final IK motion in OpenSim.\n");

    fprintf( ...
        "2. Confirm the ten requested root/out-of-plane locks.\n");

    fprintf( ...
        "3. Confirm dependent r1/r2 coordinates remain numerically " + ...
        "constant under their enabled couplers.\n");

    fprintf( ...
        "4. Review pitch1/pitch2 and dependent r3 motion through " + ...
        "the cervical chain.\n");

    fprintf( ...
        "5. Review marker RMS/max errors in the OpenSim log.\n");

    fprintf( ...
        "6. If acceptable, proceed to Model C / SO preparation.\n");

else

    fprintf( ...
        "\nModel B and the final-IK setup were prepared, " + ...
        "but final IK execution was disabled.\n");

    fprintf( ...
        "Final-IK setup XML:\n%s\n", ...
        result.Paths.FinalIkSetupFile);
end
