%% run_single_trial_static_optimization_prep.m
% Single-trial Model C + Body Kinematics + skull CoM preparation.
%
% CURRENT VALIDATION TARGET:
%   condition 0 deg, trial 1
%
% This script deliberately stops after a validated, resampled skull CoM
% trajectory. HSF force synthesis and ExternalLoads generation should be
% connected only after this real CoM stage is confirmed.
%
% INPUT FROM MODEL B
%   - Model B .osim
%   - validated final IK .mot
%   - Model B checkpoint
%
% OUTPUT
%   03_static_optimization_prep/
%       <trial>_modelC_static_optimization.osim
%       body_kinematics/
%           <trial>_body_kinematics_setup.xml
%           results/
%           qc/
%               skull_com_raw.csv
%               skull_com_resampled.csv
%               skull_com_summary.csv
%       qc/
%           modelC_coordinate_configuration.csv
%           modelC_constraint_configuration.csv
%           model_c_checkpoint.mat

clear;
clc;
dbstop if error

%% SECTION 0 — LOAD PROJECT CONFIGURATION AND TRIAL SETTINGS

activeFile = string( ...
    matlab.desktop.editor.getActiveFilename);

assert(strlength(activeFile) > 0 && isfile(activeFile), ...
    "ModelCPipeline:ActiveScriptUnknown", ...
    "Open and save this script in the MATLAB Editor " + ...
    "before running individual sections.");

examplesDirectory = ...
    string(fileparts(activeFile));

projectRoot = ...
    string(fileparts(examplesDirectory));

addpath(projectRoot);

projectCfg = load_project_config();

trialCfg = struct;

trialCfg.conditionDeg = 45;
trialCfg.trialNumber = 1;

trialCfg.overwriteExisting = ...
    projectCfg.overwriteExisting;

% Keep Body Kinematics disabled until Model C has been reviewed.
trialCfg.executeBodyKinematics = true;

% Body Kinematics should not add another filter here. The HSF point
% trajectory should be based on the validated final IK motion.
trialCfg.bodyKinematicsLowpassCutoffHz = -1;

% Default to full validated final-IK time range.
trialCfg.timeRange = [];

% Shared HSF contact-event detection settings.
assert(isfield(projectCfg, "qc") && ...
       isfield(projectCfg.qc, "hsfEventDetection"), ...
    "ModelCPipeline:HsfEventDetectionConfigMissing", ...
    "projectCfg.qc.hsfEventDetection is required.");

trialCfg.eventDetection = ...
    projectCfg.qc.hsfEventDetection;

fprintf( ...
    "Configured Model C/HSF preparation for %g deg, trial %d.\n", ...
    trialCfg.conditionDeg, ...
    trialCfg.trialNumber);


%% SECTION 1 — RESOLVE TRIAL PATHS

conditionFolderName = sprintf( ...
    "%02ddeg", ...
    round(trialCfg.conditionDeg));

trialFolderName = sprintf( ...
    "trial%02d", ...
    trialCfg.trialNumber);

trialStem = sprintf( ...
    "%s_%s", ...
    conditionFolderName, ...
    trialFolderName);

trialRoot = string(fullfile( ...
    projectCfg.outputRoot, ...
    conditionFolderName, ...
    trialFolderName));

phaseBDirectory = string(fullfile( ...
    trialRoot, ...
    "02_locked_final_ik"));

phaseBQcDirectory = string(fullfile( ...
    phaseBDirectory, ...
    "qc"));

phaseCDirectory = string(fullfile( ...
    trialRoot, ...
    "03_static_optimization_prep"));

phaseCQcDirectory = string(fullfile( ...
    phaseCDirectory, ...
    "qc"));

bodyKinematicsDirectory = string(fullfile( ...
    phaseCDirectory, ...
    "body_kinematics"));

bodyKinematicsResultsDirectory = string(fullfile( ...
    bodyKinematicsDirectory, ...
    "results"));

bodyKinematicsQcDirectory = string(fullfile( ...
    bodyKinematicsDirectory, ...
    "qc"));

hsfDirectory = string(fullfile( ...
    phaseCDirectory, ...
    "head_support_force"));

hsfQcDirectory = string(fullfile( ...
    hsfDirectory, ...
    "qc"));

staticOptimizationDirectory = string(fullfile( ...
    trialRoot, ...
    "04_static_optimization"));

staticOptimizationResultsDirectory = string(fullfile( ...
    staticOptimizationDirectory, ...
    "results"));

staticOptimizationQcDirectory = string(fullfile( ...
    staticOptimizationDirectory, ...
    "qc"));

for directory = [ ...
        phaseCDirectory
        phaseCQcDirectory
        bodyKinematicsDirectory
        bodyKinematicsResultsDirectory
        bodyKinematicsQcDirectory
        hsfDirectory
        hsfQcDirectory
        staticOptimizationDirectory
        staticOptimizationResultsDirectory
        staticOptimizationQcDirectory].'

    if ~isfolder(directory)
        mkdir(directory);
    end
end

paths = struct;

paths.modelBCheckpointFile = string(fullfile( ...
    phaseBQcDirectory, ...
    "model_b_final_ik_checkpoint.mat"));

paths.modelBFile = string(fullfile( ...
    phaseBDirectory, ...
    trialStem + "_modelB_locked_ik.osim"));

paths.finalIkMotionFile = string(fullfile( ...
    phaseBDirectory, ...
    trialStem + "_final_ik.mot"));

paths.modelCFile = string(fullfile( ...
    phaseCDirectory, ...
    trialStem + ...
    "_modelC_static_optimization.osim"));

paths.modelCCoordinateConfigurationCsv = ...
    string(fullfile( ...
        phaseCQcDirectory, ...
        "modelC_coordinate_configuration.csv"));

paths.modelCConstraintConfigurationCsv = ...
    string(fullfile( ...
        phaseCQcDirectory, ...
        "modelC_constraint_configuration.csv"));


paths.modelCForceConfigAuditCsv = ...
    string(fullfile( ...
        phaseCQcDirectory, ...
        "modelC_force_capacity_config_audit.csv"));

paths.bodyKinematicsSetupFile = ...
    string(fullfile( ...
        bodyKinematicsDirectory, ...
        trialStem + ...
        "_body_kinematics_setup.xml"));

paths.bodyKinematicsResultsDirectory = ...
    bodyKinematicsResultsDirectory;

paths.rawComCsv = string(fullfile( ...
    bodyKinematicsQcDirectory, ...
    "skull_com_raw.csv"));

paths.resampledComCsv = string(fullfile( ...
    bodyKinematicsQcDirectory, ...
    "skull_com_resampled.csv"));

paths.comSummaryCsv = string(fullfile( ...
    bodyKinematicsQcDirectory, ...
    "skull_com_summary.csv"));

paths.eventDetectionSummaryCsv = string(fullfile( ...
    hsfQcDirectory, ...
    "contact_event_detection_summary.csv"));

paths.eventDetectionPlot = string(fullfile( ...
    hsfQcDirectory, ...
    "contact_event_detection.png"));

paths.hsfMotionFile = string(fullfile( ...
    hsfDirectory, ...
    trialStem + "_head_support_force.mot"));

paths.hsfSummaryCsv = string(fullfile( ...
    hsfQcDirectory, ...
    "hsf_summary.csv"));

paths.hsfEnvelopeCsv = string(fullfile( ...
    hsfQcDirectory, ...
    "hsf_support_envelope.csv"));

paths.externalLoadsFile = string(fullfile( ...
    hsfDirectory, ...
    trialStem + "_external_loads.xml"));

if isfield(projectCfg, "externalLoadsTemplate")
    paths.externalLoadsTemplate = ...
        string(projectCfg.externalLoadsTemplate);
else
    paths.externalLoadsTemplate = "";
end

paths.staticOptimizationSetupFile = string(fullfile( ...
    staticOptimizationDirectory, ...
    trialStem + "_so_setup.xml"));

paths.staticOptimizationResultsDirectory = ...
    staticOptimizationResultsDirectory;

if isfield(projectCfg, "staticOptimizationTemplate")
    paths.staticOptimizationTemplate = ...
        string(projectCfg.staticOptimizationTemplate);
else
    paths.staticOptimizationTemplate = "";
end

paths.runSummaryMat = string(fullfile( ...
    phaseCQcDirectory, ...
    "model_c_checkpoint.mat"));

disp(paths);


%% SECTION 2 — LOAD AND VALIDATE MODEL B CHECKPOINT

assert(isfile(paths.modelBCheckpointFile), ...
    "ModelCPipeline:ModelBCheckpointMissing", ...
    "Model B checkpoint was not found:\n%s", ...
    paths.modelBCheckpointFile);

loadedCheckpoint = load( ...
    paths.modelBCheckpointFile);

assert(isfield( ...
        loadedCheckpoint, ...
        "modelBCheckpoint"), ...
    "ModelCPipeline:CheckpointVariableMissing", ...
    "Expected variable 'modelBCheckpoint' was not found in:\n%s", ...
    paths.modelBCheckpointFile);

checkpointB = ...
    loadedCheckpoint.modelBCheckpoint;

assert(isfield(checkpointB, "Configuration"), ...
    "ModelCPipeline:CheckpointConfigurationMissing", ...
    "Model B checkpoint is missing Configuration.");

assert( ...
    checkpointB.Configuration.conditionDeg == ...
        trialCfg.conditionDeg, ...
    "ModelCPipeline:ConditionMismatch", ...
    "Configured condition is %g deg but " + ...
    "Model B checkpoint contains %g deg.", ...
    trialCfg.conditionDeg, ...
    checkpointB.Configuration.conditionDeg);

assert( ...
    checkpointB.Configuration.trialNumber == ...
        trialCfg.trialNumber, ...
    "ModelCPipeline:TrialMismatch", ...
    "Configured trial is %d but Model " + ...
    "B checkpoint contains trial %d.", ...
    trialCfg.trialNumber, ...
    checkpointB.Configuration.trialNumber);

assert(isfile(paths.modelBFile), ...
    "ModelCPipeline:ModelBMissing", ...
    "Model B file was not found:\n%s", ...
    paths.modelBFile);

assert(isfile(paths.finalIkMotionFile), ...
    "ModelCPipeline:FinalIkMissing", ...
    "Validated final IK motion was not found:\n%s", ...
    paths.finalIkMotionFile);

assert(isfield(checkpointB, ...
        "LockedCoordinateAudit"), ...
    "ModelCPipeline:LockedAuditMissing", ...
    "Model B checkpoint does not contain the " + ...
    "final locked-coordinate audit.");

assert(logical( ...
        checkpointB.LockedCoordinateAudit.Passed), ...
    "ModelCPipeline:ModelBLockedAuditFailed", ...
    "Model B locked-coordinate audit did not pass. " + ...
    "Do not construct Model C from this trial.");

finalIkMotion = ...
    opensimio.readMot( ...
        paths.finalIkMotionFile);

if isempty(trialCfg.timeRange)
    trialTimeRange = [ ...
        finalIkMotion.Time(1), ...
        finalIkMotion.Time(end)];
else
    trialTimeRange = ...
        double(trialCfg.timeRange(:).');
end

fprintf( ...
    "Model B checkpoint validated. " + ...
    "Trial range: %.5f to %.5f s.\n", ...
    trialTimeRange(1), ...
    trialTimeRange(2));


%% SECTION 3 — BUILD MODEL C

assert(isfield(projectCfg, "qc") && ...
       isfield(projectCfg.qc, "lockAudit"), ...
    "ModelCPipeline:LockAuditConfigMissing", ...
    "projectCfg.qc.lockAudit is required.");

auditQc = projectCfg.qc.lockAudit;

groups = modelprep.coordinateGroups();

requiredGroupFields = [ ...
    "StaticOptimizationLocked"
    "Sagittal"
];

for iGroup = 1:numel(requiredGroupFields)

    groupName = requiredGroupFields(iGroup);

    assert(isfield(groups, groupName), ...
        "ModelCPipeline:CoordinateGroupMissing", ...
        "modelprep.coordinateGroups is missing groups.%s.", ...
        groupName);
end

if isfile(paths.modelCFile) && ...
        ~trialCfg.overwriteExisting

    error( ...
        "ModelCPipeline:ModelCExists", ...
        "Model C already exists:\n%s\n" + ...
        "Set overwriteExisting=true to rebuild it.", ...
        paths.modelCFile);
end

modelCResult = ...
    modelprep.buildStaticOptimizationModel( ...
        paths.modelBFile, ...
        paths.finalIkMotionFile, ...
        paths.modelCFile, ...
        "TimeWindow", ...
            trialTimeRange, ...
        "RotationToleranceDeg", ...
            auditQc.rotationRangeToleranceDeg, ...
        "TranslationToleranceM", ...
            auditQc.translationRangeToleranceM, ...
        "RequireStable", ...
            true);

assert(isfile(paths.modelCFile), ...
    "ModelCPipeline:ModelCWriteFailed", ...
    "Model C was not written:\n%s", ...
    paths.modelCFile);

writetable( ...
    modelCResult.Inspection.Coordinates, ...
    paths.modelCCoordinateConfigurationCsv);

writetable( ...
    modelCResult.Inspection.Constraints, ...
    paths.modelCConstraintConfigurationCsv);

fprintf("Model C written:\n%s\n", ...
    paths.modelCFile);


%% SECTION 4 — VALIDATE MODEL C CONFIGURATION

modelCInspection = ...
    modelprep.inspectModel( ...
        paths.modelCFile);

allCoordinateNames = ...
    modelCInspection.Coordinates.Coordinate;

expectedLocked = ...
    groups.StaticOptimizationLocked;

expectedUnlocked = ...
    setdiff( ...
        allCoordinateNames, ...
        expectedLocked, ...
        "stable");

modelCValidation = ...
    modelprep.validateModelConfiguration( ...
        paths.modelCFile, ...
        "ExpectedLocked", ...
            expectedLocked, ...
        "ExpectedUnlocked", ...
            expectedUnlocked, ...
        "ExpectedConstraintsEnforced", ...
            false, ...
        "ThrowOnFailure", ...
            true);

assert(modelCValidation.Passed, ...
    "ModelCPipeline:ModelCValidationFailed", ...
    "Model C configuration validation failed.");

% Sagittal coordinates must remain unlocked once the couplers are disabled.
sagittalRows = ismember( ...
    modelCInspection.Coordinates.Coordinate, ...
    groups.Sagittal);

sagittalState = ...
    modelCInspection.Coordinates( ...
        sagittalRows, ...
        { ...
            'Coordinate'
            'DefaultLocked'
            'StateLocked'
            'StateDependent'
            'StateConstrained'
        });

fprintf("\nModel C sagittal-coordinate state:\n");
disp(sagittalState);

assert(all(~sagittalState.StateLocked), ...
    "ModelCPipeline:SagittalCoordinateLocked", ...
    "One or more sagittal coordinates are locked in Model C. " + ...
    "Review Model C construction.");

fprintf( ...
    "Model C validation passed: out-of-plane/root coordinates locked, " + ...
    "sagittal coordinates unlocked, couplers disabled.\n");

% CHECKPOINT:
% Open Model C with the final IK motion in OpenSim before continuing.
% Confirm that the validated sagittal motion is reproduced and no new
% out-of-plane freedom has appeared.


%% SECTION 4B — OPTIONALLY APPLY SAVED FORCE-CAPACITY CONFIGURATION
%
% This is the preferred force-configuration hook for the current pipeline:
%   - IK/Body Kinematics do not depend on muscle/actuator capacities;
%   - Model C is the model ultimately consumed by Static Optimization;
%   - applying here avoids repeatedly editing Model A and Model B.
%
% Recommended pipeline behavior:
%   projectCfg.forceCapacity.applyMode = "target"
%
% "target" is idempotent. Re-running this section writes the same configured
% values. "scale" multiplies the CURRENT target-model values and therefore
% should only be used on a freshly regenerated Model C.

forceCapacityConfigResult = ...
    modelprep.applyConfiguredForceCapacitiesIfEnabled( ...
        paths.modelCFile, ...
        projectCfg, ...
        "StageName", ...
            "Model C", ...
        "AuditFile", ...
            paths.modelCForceConfigAuditCsv);

if forceCapacityConfigResult.Enabled

    assert(forceCapacityConfigResult.Applied, ...
        "ModelCPipeline:ForceConfigNotApplied", ...
        "Force-capacity configuration is enabled but was not applied " + ...
        "to Model C.");

    assert(forceCapacityConfigResult.VerificationPassed, ...
        "ModelCPipeline:ForceConfigVerificationFailed", ...
        "Applied Model C force-capacity configuration failed verification.");

    fprintf("\nForce-capacity configuration applied to Model C.\n");
    fprintf("Config:\n%s\n", ...
        forceCapacityConfigResult.ConfigFile);
    fprintf("Apply mode: %s\n", ...
        forceCapacityConfigResult.ApplyMode);
    fprintf("Audit:\n%s\n", ...
        forceCapacityConfigResult.AuditFile);

    if strcmpi( ...
            string(forceCapacityConfigResult.ApplyMode), ...
            "scale")

        warning( ...
            "ModelCPipeline:ScaleModeNonIdempotent", ...
            "Force-capacity config was applied in SCALE mode. " + ...
            "Do not rerun Section 4B on this same Model C unless " + ...
             "you intend to compound the scaling. Rebuild Model C first.");
    end

else

    fprintf( ...
        "\nForce-capacity configuration is disabled. " + ...
        "Model C ForceSet values were left unchanged.\n");
end


%% SECTION 5 — RUN BODY KINEMATICS FOR SKULL COM

if ~trialCfg.executeBodyKinematics

    fprintf( ...
        "\nBody Kinematics execution is disabled.\n" + ...
        "Review Model C first, then set " + ...
        "trialCfg.executeBodyKinematics=true and rerun Section 5.\n");

else

    bodyKinematicsResult = ...
        opensimrun.runBodyKinematicsForCom( ...
            paths.modelCFile, ...
            paths.finalIkMotionFile, ...
            paths.bodyKinematicsResultsDirectory, ...
            "BodyName", ...
                "skull", ...
            "TimeRange", ...
                trialTimeRange, ...
            "ToolName", ...
                trialStem + "_body_kinematics", ...
            "SetupFile", ...
                paths.bodyKinematicsSetupFile, ...
            "LowpassCutoffHz", ...
                trialCfg.bodyKinematicsLowpassCutoffHz, ...
            "Overwrite", ...
                trialCfg.overwriteExisting);

    fprintf( ...
        "Body Kinematics completed in %.3f seconds.\n", ...
        bodyKinematicsResult.DurationSeconds);

    fprintf( ...
        "Position output:\n%s\n", ...
        bodyKinematicsResult.PositionFile);

end


%% SECTION 6 — READ AND QC THE RAW SKULL COM TRAJECTORY

assert(exist("bodyKinematicsResult", "var") == 1, ...
    "ModelCPipeline:BodyKinematicsNotRun", ...
    "Run Section 5 with executeBodyKinematics=true before " + ...
    "running the CoM extraction section.");

assert(isfile(bodyKinematicsResult.PositionFile), ...
    "ModelCPipeline:BodyKinematicsOutputMissing", ...
    "Body Kinematics position file was not found:\n%s", ...
    bodyKinematicsResult.PositionFile);

% Existing HSF helper: Body Kinematics position STO -> body CoM trajectory.
rawCom = ...
    hsf.readBodyCom( ...
        bodyKinematicsResult.PositionFile, ...
        "skull");

rawComTable = ...
    localNormalizeComToTable(rawCom);

localValidateComTable( ...
    rawComTable, ...
    "raw Body Kinematics skull CoM");

writetable( ...
    rawComTable, ...
    paths.rawComCsv);

fprintf("\nRaw skull CoM summary:\n");
disp(localSummarizeCom(rawComTable, "raw"));

fprintf( ...
    "Raw skull CoM written:\n%s\n", ...
    paths.rawComCsv);


%% SECTION 7 — RESAMPLE SKULL COM TO HSF TARGET RATE

hsfParameters = ...
    hsf.defaultParameters();

targetRateHz = ...
    double(hsfParameters.TargetRateHz);

interpolationMethod = ...
    string(hsfParameters.InterpolationMethod);

% Existing HSF helper. resampleCom uses name-value options, so the
% interpolation method must be supplied explicitly as a parameter value.
resampledCom = ...
    hsf.resampleCom( ...
        rawCom, ...
        targetRateHz, ...
        "InterpolationMethod", ...
        interpolationMethod);

resampledComTable = ...
    localNormalizeComToTable( ...
        resampledCom);

localValidateComTable( ...
    resampledComTable, ...
    "resampled skull CoM");

dt = diff(resampledComTable.time);

expectedDt = 1 / targetRateHz;

assert(max(abs(dt - expectedDt)) < 1e-9, ...
    "ModelCPipeline:ResampledRateMismatch", ...
    "Resampled CoM spacing does not match TargetRateHz=%g. " + ...
    "Maximum |dt - 1/Fs| = %.9g s.", ...
    targetRateHz, ...
    max(abs(dt - expectedDt)));

writetable( ...
    resampledComTable, ...
    paths.resampledComCsv);

rawSummary = ...
    localSummarizeCom( ...
        rawComTable, ...
        "raw");

resampledSummary = ...
    localSummarizeCom( ...
        resampledComTable, ...
        "resampled");

comSummary = [ ...
    rawSummary
    resampledSummary
];

writetable( ...
    comSummary, ...
    paths.comSummaryCsv);

fprintf("\nSkull CoM QC summary:\n");
disp(comSummary);

fprintf( ...
    "Resampled skull CoM written:\n%s\n", ...
    paths.resampledComCsv);

fprintf( ...
    "\nCHECKPOINT: inspect skull_com_raw.csv and " + ...
    "skull_com_resampled.csv before connecting HSF force generation.\n");


%% SECTION 8 — DETECT LIFT-OFF AND RE-CONTACT FROM RAW SKULL COM

assert(exist("rawCom", "var") == 1, ...
    "ModelCPipeline:RawComMissing", ...
    "Run Section 6 before contact-event detection.");

eventCfg = trialCfg.eventDetection;

eventDetectionResult = ...
    hsf.detectContactEventsFromCom( ...
        rawCom, ...
        "BaselineWindow", eventCfg.baselineWindow, ...
        "LiftOffThresholdM", eventCfg.liftOffThresholdM, ...
        "RecontactThresholdM", eventCfg.recontactThresholdM, ...
        "MinimumAboveDurationSec", eventCfg.minimumAboveDurationSec, ...
        "MinimumBelowDurationSec", eventCfg.minimumBelowDurationSec, ...
        "SmoothingWindowSec", eventCfg.smoothingWindowSec, ...
        "SearchWindow", eventCfg.searchWindow, ...
        "Plot", true, ...
        "PlotFile", paths.eventDetectionPlot, ...
        "FigureVisible", "on");

writetable(eventDetectionResult.Summary, ...
    paths.eventDetectionSummaryCsv);

trialCfg.liftOffWindow = [ ...
    eventDetectionResult.LiftOffTime, ...
    eventDetectionResult.RecontactTime];

fprintf("\nDetected HSF contact events:\n");
fprintf("  Lift-off:    %.6f s\n", trialCfg.liftOffWindow(1));
fprintf("  Re-contact:  %.6f s\n", trialCfg.liftOffWindow(2));
fprintf("  Peak CoM excursion: %.3f mm\n", ...
    eventDetectionResult.PeakExcursionM * 1000);
fprintf("  Baseline P95 noise: %.3f mm\n", ...
    eventDetectionResult.BaselineNoise.P95M * 1000);
fprintf("Event-detection plot saved:\n%s\n", ...
    paths.eventDetectionPlot);

% CHECKPOINT:
% Inspect contact_event_detection.png before generating the HSF. The
% vertical event lines should coincide with the visually obvious departure
% from and return to the supported baseline.


%% SECTION 9 — GENERATE REAL HEAD-SUPPORT-FORCE MOT


assert(exist("resampledCom", "var") == 1, ...
    "ModelCPipeline:ResampledComMissing", ...
    "Run Section 7 before generating the HSF.");

assert(~isempty(trialCfg.liftOffWindow), ...
    "ModelCPipeline:LiftOffWindowMissing", ...
    "No detected lift-off/re-contact window is available. " + ...
    "Run Section 8 before generating the HSF.");

assert( ...
    isnumeric(trialCfg.liftOffWindow) && ...
    numel(trialCfg.liftOffWindow) == 2 && ...
    all(isfinite(trialCfg.liftOffWindow)) && ...
    trialCfg.liftOffWindow(2) > trialCfg.liftOffWindow(1), ...
    "ModelCPipeline:InvalidLiftOffWindow", ...
    "Detected liftOffWindow must be [lift_off recontact] in seconds.");

% Extract gndroll directly from the validated final IK. It is explicitly
% locked in Model B, so its range should be numerically negligible.
finalLabels = ...
    reshape(string(finalIkMotion.Labels), 1, []);

gndrollColumn = find( ...
    finalLabels == "gndroll");

assert(numel(gndrollColumn) == 1, ...
    "ModelCPipeline:GndrollLookupFailed", ...
    "Could not uniquely locate gndroll in the final IK motion.");

gndrollValuesDeg = ...
    finalIkMotion.Data(:, gndrollColumn);

assert(all(isfinite(gndrollValuesDeg)), ...
    "ModelCPipeline:NonfiniteGndroll", ...
    "Final IK gndroll contains nonfinite values.");

gndrollRangeDeg = ...
    max(gndrollValuesDeg) - ...
    min(gndrollValuesDeg);

assert(gndrollRangeDeg <= ...
        auditQc.rotationRangeToleranceDeg, ...
    "ModelCPipeline:GndrollNotConstant", ...
    "gndroll varies by %.9g deg in final IK; expected it to be locked " + ...
    "within %.9g deg.", ...
    gndrollRangeDeg, ...
    auditQc.rotationRangeToleranceDeg);

gndrollDeg = ...
    median(gndrollValuesDeg);

fprintf("\nHSF generation inputs:\n");
fprintf("  Condition:        %.6g deg\n", trialCfg.conditionDeg);
fprintf("  gndroll:          %.9g deg\n", gndrollDeg);
fprintf("  Lift-off:         %.9g s\n", trialCfg.liftOffWindow(1));
fprintf("  Re-contact:       %.9g s\n", trialCfg.liftOffWindow(2));
fprintf("  CoM samples:      %d\n", numel(resampledCom.Time));
fprintf("  CoM target rate:  %.6g Hz\n", hsfParameters.TargetRateHz);

hsfResult = ...
    hsf.generateFromResampledCom( ...
        resampledCom, ...
        trialCfg.conditionDeg, ...
        gndrollDeg, ...
        trialCfg.liftOffWindow, ...
        paths.hsfMotionFile, ...
        "Parameters", ...
            hsfParameters, ...
        "Overwrite", ...
            trialCfg.overwriteExisting, ...
        "MotionName", ...
            trialStem + "_head_support_force");

assert(hsfResult.Validation.Passed, ...
    "ModelCPipeline:HsfValidationFailed", ...
    "Generated HSF failed validation.");

writetable( ...
    hsfResult.Summary, ...
    paths.hsfSummaryCsv);

envelopeTable = table( ...
    hsfResult.Motion.Time(:), ...
    hsfResult.SupportEnvelope(:), ...
    'VariableNames', { ...
        'time', ...
        'support_envelope'});

writetable( ...
    envelopeTable, ...
    paths.hsfEnvelopeCsv);

fprintf("\nHSF summary:\n");
disp(hsfResult.Summary);

fprintf("HSF MOT written:\n%s\n", ...
    paths.hsfMotionFile);

fprintf("HSF envelope QC written:\n%s\n", ...
    paths.hsfEnvelopeCsv);

% CHECKPOINT:
% Plot force components, force magnitude, support envelope, and point
% coordinates. Confirm:
%   - full support before lift-off;
%   - 100 ms half-cosine ramp down;
%   - zero force during lift-off;
%   - 100 ms half-cosine ramp up after re-contact;
%   - point columns continue to follow skull CoM throughout.


%% SECTION 10 — GENERATE TRIAL-SPECIFIC EXTERNAL LOADS XML

assert(isfile(paths.hsfMotionFile), ...
    "ModelCPipeline:HsfMotionMissing", ...
    "HSF MOT was not found:\n%s", ...
    paths.hsfMotionFile);

assert(strlength(paths.externalLoadsTemplate) > 0 && ...
       isfile(paths.externalLoadsTemplate), ...
    "ModelCPipeline:ExternalLoadsTemplateMissing", ...
    "projectCfg.externalLoadsTemplate must point to the shared " + ...
    "ExternalLoads XML template.");

externalLoadsResult = ...
    opensimrun.prepareExternalLoadsSetup( ...
        paths.externalLoadsTemplate, ...
        paths.externalLoadsFile, ...
        "DataFile", ...
            paths.hsfMotionFile, ...
        "ExternalLoadsName", ...
            trialStem + "_external_loads", ...
        "Overwrite", ...
            trialCfg.overwriteExisting);

assert(externalLoadsResult.VerificationPassed, ...
    "ModelCPipeline:ExternalLoadsVerificationFailed", ...
    "Generated ExternalLoads XML failed verification.");

fprintf("\nExternalLoads patch report:\n");
disp(externalLoadsResult.PatchReport);

fprintf("ExternalLoads XML written:\n%s\n", ...
    paths.externalLoadsFile);


%% SECTION 11 — GENERATE TRIAL-SPECIFIC STATIC OPTIMIZATION SETUP

assert(isfile(paths.modelCFile), ...
    "ModelCPipeline:ModelCForSoMissing", ...
    "Model C was not found:\n%s", ...
    paths.modelCFile);

assert(isfile(paths.finalIkMotionFile), ...
    "ModelCPipeline:CoordinatesForSoMissing", ...
    "Final IK coordinates were not found:\n%s", ...
    paths.finalIkMotionFile);

assert(isfile(paths.externalLoadsFile), ...
    "ModelCPipeline:ExternalLoadsForSoMissing", ...
    "ExternalLoads XML was not found:\n%s", ...
    paths.externalLoadsFile);

assert(strlength(paths.staticOptimizationTemplate) > 0 && ...
       isfile(paths.staticOptimizationTemplate), ...
    "ModelCPipeline:StaticOptimizationTemplateMissing", ...
    "projectCfg.staticOptimizationTemplate must point to the shared " + ...
    "Static Optimization setup template.");

staticOptimizationSetupResult = ...
    opensimrun.prepareStaticOptimizationSetup( ...
        paths.staticOptimizationTemplate, ...
        paths.staticOptimizationSetupFile, ...
        "ModelFile", ...
            paths.modelCFile, ...
        "CoordinatesFile", ...
            paths.finalIkMotionFile, ...
        "ExternalLoadsFile", ...
            paths.externalLoadsFile, ...
        "ResultsDirectory", ...
            paths.staticOptimizationResultsDirectory, ...
        "TimeRange", ...
            trialTimeRange, ...
        "ToolName", ...
            "SO_" + trialStem, ...
        "Overwrite", ...
            trialCfg.overwriteExisting);

assert( ...
    staticOptimizationSetupResult.VerificationPassed, ...
    "ModelCPipeline:StaticOptimizationSetupVerificationFailed", ...
    "Generated Static Optimization setup failed verification.");

fprintf("\nStatic Optimization setup patch report:\n");
disp(staticOptimizationSetupResult.PatchReport);

fprintf("Static Optimization setup written:\n%s\n", ...
    paths.staticOptimizationSetupFile);

fprintf("Static Optimization results directory:\n%s\n", ...
    paths.staticOptimizationResultsDirectory);

% CHECKPOINT:
% Open the generated XML before running SO and verify:
%   - model_file -> trial-specific Model C;
%   - coordinates_file -> validated final IK;
%   - external_loads_file -> trial-specific HSF ExternalLoads XML;
%   - results_directory -> 04_static_optimization/results;
%   - initial/final and StaticOptimization start/end times match the trial;
%   - optimizer/scientific settings remain identical to the shared template.


%% SECTION 12 — SAVE MODEL C / HSF / SO SETUP PREPARATION CHECKPOINT

modelCCheckpoint = struct;

modelCCheckpoint.Configuration = ...
    trialCfg;

modelCCheckpoint.Paths = ...
    paths;

modelCCheckpoint.ModelBCheckpointFile = ...
    paths.modelBCheckpointFile;

modelCCheckpoint.TrialTimeRange = ...
    trialTimeRange;

modelCCheckpoint.ModelCResult = ...
    modelCResult;

modelCCheckpoint.ModelCValidation = ...
    modelCValidation;

if exist("forceCapacityConfigResult", "var")
    modelCCheckpoint.ForceCapacityConfigResult = ...
        forceCapacityConfigResult;
end

modelCCheckpoint.SagittalState = ...
    sagittalState;

if exist("bodyKinematicsResult", "var")
    modelCCheckpoint.BodyKinematicsResult = ...
        bodyKinematicsResult;
end

if exist("comSummary", "var")
    modelCCheckpoint.ComSummary = ...
        comSummary;
end

if exist("eventDetectionResult", "var")
    modelCCheckpoint.EventDetectionResult = ...
        eventDetectionResult;
end

if exist("hsfResult", "var")
    modelCCheckpoint.HsfResult = ...
        hsfResult;
end

if exist("externalLoadsResult", "var")
    modelCCheckpoint.ExternalLoadsResult = ...
        externalLoadsResult;
end

if exist("staticOptimizationSetupResult", "var")
    modelCCheckpoint.StaticOptimizationSetupResult = ...
        staticOptimizationSetupResult;
end

save( ...
    paths.runSummaryMat, ...
    "modelCCheckpoint", ...
    "-v7.3");

fprintf( ...
    "\nModel C / HSF checkpoint saved:\n%s\n", ...
    paths.runSummaryMat);

fprintf("\nNEXT MANUAL CHECKS\n");
fprintf("1. Plot all three HSF force components and total magnitude.\n");
fprintf("2. Plot support_envelope versus time.\n");
fprintf("3. Confirm zero force spans lift-off to re-contact.\n");
fprintf("4. Confirm point columns reproduce the validated skull CoM trajectory.\n");
fprintf("5. Preview the HSF MOT in OpenSim with Model C.\n");
fprintf("6. Verify ExternalLoads XML points to this exact HSF MOT.\n");
fprintf("7. Review the generated SO setup XML paths and time range.\n");
fprintf("8. Do not execute SO until the full preparation package is accepted.\n");


%% LOCAL FUNCTIONS

function comTable = localNormalizeComToTable(comInput)
%LOCALNORMALIZECOMTOTABLE Normalize common HSF CoM output schemas.

    if istable(comInput)

        names = string( ...
            comInput.Properties.VariableNames);

        timeName = localFindVariable( ...
            names, ...
            "time");

        xName = localFindVariable( ...
            names, ...
            ["x","posx","comx","centerofmassx"]);

        yName = localFindVariable( ...
            names, ...
            ["y","posy","comy","centerofmassy"]);

        zName = localFindVariable( ...
            names, ...
            ["z","posz","comz","centerofmassz"]);

        comTable = table( ...
            double(comInput.(timeName)), ...
            double(comInput.(xName)), ...
            double(comInput.(yName)), ...
            double(comInput.(zName)), ...
            'VariableNames', { ...
                'time','x','y','z'});

        return;
    end

    if isstruct(comInput)

        if all(isfield(comInput, ...
                {'Time','X','Y','Z'}))

            comTable = table( ...
                double(comInput.Time(:)), ...
                double(comInput.X(:)), ...
                double(comInput.Y(:)), ...
                double(comInput.Z(:)), ...
                'VariableNames', { ...
                    'time','x','y','z'});

            return;
        end

        if all(isfield(comInput, ...
                {'time','x','y','z'}))

            comTable = table( ...
                double(comInput.time(:)), ...
                double(comInput.x(:)), ...
                double(comInput.y(:)), ...
                double(comInput.z(:)), ...
                'VariableNames', { ...
                    'time','x','y','z'});

            return;
        end

        if isfield(comInput, "Time") && ...
                isfield(comInput, "Data")

            data = ...
                double(comInput.Data);

            assert(size(data,2) >= 4, ...
                "ModelCPipeline:ComStructDataShape", ...
                "CoM struct contains Time/Data but Data has fewer " + ...
                "than four columns.");

            if size(data,1) == numel(comInput.Time)

                % If Data includes time, discard it when it duplicates Time.
                if max(abs(data(:,1) - ...
                        double(comInput.Time(:)))) < 1e-10

                    xyz = data(:,2:4);
                else
                    xyz = data(:,1:3);
                end

                comTable = table( ...
                    double(comInput.Time(:)), ...
                    xyz(:,1), ...
                    xyz(:,2), ...
                    xyz(:,3), ...
                    'VariableNames', { ...
                        'time','x','y','z'});

                return;
            end
        end
    end

    error( ...
        "ModelCPipeline:UnsupportedComSchema", ...
        "Could not normalize the output returned by the HSF CoM " + ...
        "helper. Inspect class(rawCom) / fieldnames(rawCom) and add " + ...
        "that schema to localNormalizeComToTable.");
end


function name = localFindVariable(variableNames, candidates)

    normalizedNames = lower( ...
        regexprep(variableNames, "[^a-zA-Z0-9]", ""));

    normalizedCandidates = lower( ...
        regexprep(candidates, "[^a-zA-Z0-9]", ""));

    match = false(size(variableNames));

    for candidate = normalizedCandidates
        match = match | ...
            normalizedNames == candidate;
    end

    assert(nnz(match) == 1, ...
        "ModelCPipeline:ComVariableLookupFailed", ...
        "Could not uniquely identify a CoM variable. " + ...
        "Available variables: %s", ...
        strjoin(variableNames, ", "));

    name = ...
        variableNames(match);
end


function localValidateComTable(comTable, label)

    assert(height(comTable) >= 2, ...
        "ModelCPipeline:ComTooShort", ...
        "%s contains fewer than two samples.", ...
        label);

    values = [ ...
        comTable.time, ...
        comTable.x, ...
        comTable.y, ...
        comTable.z];

    assert(all(isfinite(values), "all"), ...
        "ModelCPipeline:ComNonfinite", ...
        "%s contains nonfinite values.", ...
        label);

    assert(all(diff(comTable.time) > 0), ...
        "ModelCPipeline:ComTimeNotIncreasing", ...
        "%s time is not strictly increasing.", ...
        label);
end


function summary = localSummarizeCom(comTable, stage)

    dt = diff(comTable.time);

    if isempty(dt)
        estimatedRateHz = NaN;
    else
        estimatedRateHz = ...
            1 / median(dt);
    end

    summary = table( ...
        string(stage), ...
        height(comTable), ...
        comTable.time(1), ...
        comTable.time(end), ...
        estimatedRateHz, ...
        min(comTable.x), ...
        max(comTable.x), ...
        min(comTable.y), ...
        max(comTable.y), ...
        min(comTable.z), ...
        max(comTable.z), ...
        'VariableNames', { ...
            'Stage', ...
            'NumSamples', ...
            'StartTime', ...
            'EndTime', ...
            'EstimatedRateHz', ...
            'MinimumX', ...
            'MaximumX', ...
            'MinimumY', ...
            'MaximumY', ...
            'MinimumZ', ...
            'MaximumZ'});
end