%% run_single_trial_static_optimization_test.m
% Short validation driver for programmatic Static Optimization execution.
%
% PURPOSE
%   Execute one already-generated and manually validated SO setup XML,
%   audit the generated force/activation outputs, and stop.
%
% This deliberately does NOT:
%   - regenerate Model C;
%   - regenerate HSF;
%   - regenerate ExternalLoads;
%   - regenerate the SO setup;
%   - batch multiple trials;
%   - run plotting automatically.
%
% Those stages have separate validation boundaries.
%
% Default target:
%   0 deg, trial 1

clear;
clc;
dbstop if error


%% SECTION 0 — CONFIGURATION

activeFile = string( ...
    matlab.desktop.editor.getActiveFilename);

assert(strlength(activeFile) > 0 && isfile(activeFile), ...
    "SOTest:ActiveScriptUnknown", ...
    "Open and save this script in the MATLAB Editor before running.");

examplesDirectory = ...
    string(fileparts(activeFile));

projectRoot = ...
    string(fileparts(examplesDirectory));

addpath(projectRoot);

projectCfg = ...
    load_project_config();

trialCfg = struct;

trialCfg.conditionDeg = 45;
trialCfg.trialNumber = 1;

% Set true only if you deliberately want to replace the current SO
% force/activation outputs.
trialCfg.overwriteExisting = projectCfg.overwriteExisting;


%% SECTION 1 — RESOLVE SETUP AND OUTPUT PATHS

conditionFolderName = sprintf( ...
    "%02ddeg", ...
    round(trialCfg.conditionDeg));

trialFolderName = sprintf( ...
    "trial%02d", ...
    trialCfg.trialNumber);

trialStem = sprintf( ...
    "%s_%s", ...
    conditionFolderName, ...
    trialFolderName);

trialRoot = string(fullfile( ...
    projectCfg.outputRoot, ...
    conditionFolderName, ...
    trialFolderName));

staticOptimizationDirectory = string(fullfile( ...
    trialRoot, ...
    "04_static_optimization"));

setupFile = string(fullfile( ...
    staticOptimizationDirectory, ...
    trialStem + "_so_setup.xml"));

qcDirectory = string(fullfile( ...
    staticOptimizationDirectory, ...
    "qc"));

if ~isfolder(qcDirectory)
    mkdir(qcDirectory);
end

auditFile = string(fullfile( ...
    qcDirectory, ...
    "static_optimization_output_audit.csv"));

checkpointFile = string(fullfile( ...
    qcDirectory, ...
    "static_optimization_run_checkpoint.mat"));

assert(isfile(setupFile), ...
    "SOTest:SetupMissing", ...
    "Trial-specific SO setup was not found:\n%s", ...
    setupFile);

fprintf( ...
    "Configured SO test: %g deg, trial %d\n", ...
    trialCfg.conditionDeg, ...
    trialCfg.trialNumber);

fprintf( ...
    "Setup:\n%s\n", ...
    setupFile);


%% SECTION 2 — RUN STATIC OPTIMIZATION

soRunResult = ...
    opensimrun.runStaticOptimizationSetup( ...
        setupFile, ...
        "Overwrite", ...
            trialCfg.overwriteExisting);

assert(soRunResult.RunSucceeded, ...
    "SOTest:RunFailed", ...
    "Static Optimization did not report success.");

assert(all(soRunResult.OutputAudit.Passed), ...
    "SOTest:OutputAuditFailed", ...
    "Static Optimization outputs failed QC.");


%% SECTION 3 — WRITE QC AND CHECKPOINT

writetable( ...
    soRunResult.OutputAudit, ...
    auditFile);

soTestCheckpoint = struct;

soTestCheckpoint.Configuration = ...
    trialCfg;

soTestCheckpoint.SetupFile = ...
    setupFile;

soTestCheckpoint.RunResult = ...
    soRunResult;

save( ...
    checkpointFile, ...
    "soTestCheckpoint", ...
    "-v7.3");

fprintf("\nSO test checkpoint complete.\n");
fprintf("Output audit:\n%s\n", ...
    auditFile);

fprintf("Checkpoint:\n%s\n", ...
    checkpointFile);


%% SECTION 4 — MANUAL VALIDATION GATE

fprintf("\nNEXT VALIDATION STEPS\n");
fprintf("1. Run the SO plotting pipeline on this output.\n");
fprintf("2. Confirm flexion/extension groups against Model C ObjectGroups.\n");
fprintf("3. Confirm excluded/hyoid muscles are not included in those sums.\n");
fprintf("4. Confirm reserve actuator activation remains negligible.\n");
fprintf("5. Confirm force magnitudes and timing match the manual GUI run.\n");
fprintf("6. If equivalent, treat programmatic SO execution as validated.\n");
fprintf("7. Then spot-check one trial from 15, 30, and 45 deg before batch execution.\n");
