%% run_single_trial_static_optimization_prep.m
% Thin single-trial driver for Process 3:
%   Model C + Body Kinematics + HSF + ExternalLoads + SO setup.
%
% The pipeline implementation lives in:
%
%   pipeline.resolveTrialContext
%   pipeline.prepareStaticOptimizationTrial
%
% This script contains only orchestration and interactive review choices.
% Batch Process 3 calls the same worker.

%% SECTION 0 — PROJECT CONFIGURATION

clear;
clc;
dbstop if error

projectCfg = ...
    load_project_config();

fprintf( ...
    "Project root:\n%s\n", ...
    projectCfg.projectRoot);

%% SECTION 1 — SELECT TRIAL

conditionDeg = 45;
trialNumber = 1;

trial = ...
    pipeline.resolveTrialContext( ...
        projectCfg, ...
        conditionDeg, ...
        trialNumber);

fprintf( ...
    "Resolved %s.\n", ...
    trial.DisplayName);

fprintf( ...
    "Process-2 checkpoint:\n%s\n", ...
    trial.Paths.ModelB.CheckpointFile);

fprintf( ...
    "Process-3 output directory:\n%s\n", ...
    trial.Paths.StaticOptimizationPrep.Directory);

%% SECTION 2 — RUN PROCESS 3

runCfg = struct;

runCfg.executeBodyKinematics = true;

runCfg.overwrite = ...
    projectCfg.overwriteExisting;

result = ...
    pipeline.prepareStaticOptimizationTrial( ...
        projectCfg, ...
        trial, ...
        "ExecuteBodyKinematics", ...
            runCfg.executeBodyKinematics, ...
        "Overwrite", ...
            runCfg.overwrite, ...
        "WriteQc", ...
            true, ...
        "SaveCheckpoint", ...
            true, ...
        "EventFigureVisible", ...
            "on", ...
        "PrintProgress", ...
            true);

%% SECTION 3 — REVIEW

if result.Completed

    fprintf( ...
        "\nStatic-Optimization preparation Process 3 completed.\n");

    fprintf( ...
        "Model C:\n%s\n", ...
        result.Paths.ModelCFile);

    fprintf( ...
        "Body Kinematics position file:\n%s\n", ...
        result.BodyKinematicsResult.PositionFile);

    fprintf( ...
        "HSF MOT:\n%s\n", ...
        result.Paths.HeadSupportForce.MotionFile);

    fprintf( ...
        "ExternalLoads XML:\n%s\n", ...
        result.Paths.HeadSupportForce.ExternalLoadsFile);

    fprintf( ...
        "SO setup XML:\n%s\n", ...
        result.StaticOptimizationPaths.SetupFile);

    fprintf( ...
        "Checkpoint:\n%s\n", ...
        result.CheckpointFile);

    fprintf( ...
        "\nModel C sagittal-coordinate state:\n");

    disp(result.SagittalState);

    fprintf( ...
        "\nSkull CoM summary:\n");

    disp(result.ComSummary);

    fprintf( ...
        "\nDetected contact events:\n");

    disp(result.EventDetectionResult.Summary);

    fprintf( ...
        "\nHSF summary:\n");

    disp(result.HsfResult.Summary);

    fprintf( ...
        "\nNEXT MANUAL CHECKS\n");

    fprintf( ...
        "1. Inspect the contact-event detection plot.\n");

    fprintf( ...
        "2. Plot HSF force components, magnitude, and support envelope.\n");

    fprintf( ...
        "3. Confirm zero force spans detected lift-off to re-contact.\n");

    fprintf( ...
        "4. Confirm HSF point columns track skull CoM throughout.\n");

    fprintf( ...
        "5. Preview the HSF ExternalLoads with Model C in OpenSim.\n");

    fprintf( ...
        "6. Verify the SO setup paths and time bounds.\n");

    fprintf( ...
        "7. If acceptable, proceed to Process 4 / Static Optimization.\n");

else

    fprintf( ...
        "\nModel C was prepared, but Body Kinematics execution " + ...
        "was disabled.\n");

    fprintf( ...
        "Model C:\n%s\n", ...
        result.Paths.ModelCFile);
end
