%% run_single_trial_initialization_ik.m
% Thin single-trial driver for Process 1:
%   Model A + initialization inverse kinematics.
%
% The pipeline implementation lives in:
%
%   pipeline.resolveTrialContext
%   pipeline.runInitializationIkTrial
%
% This script should contain only orchestration choices for an individual
% interactive trial. Batch Process 1 calls the same worker.

%% SECTION 0 — PROJECT CONFIGURATION

clear;
clc;
dbstop if error

projectCfg = ...
    load_project_config();

fprintf( ...
    "Project root:\n%s\n", ...
    projectCfg.projectRoot);

%% SECTION 1 — SELECT TRIAL

% Interactive example selection only.
% These values do not modify the version-controlled study design.
conditionDeg = 45;
trialNumber = 1;

trial = ...
    pipeline.resolveTrialContext( ...
        projectCfg, ...
        conditionDeg, ...
        trialNumber);

fprintf( ...
    "Resolved %s.\n", ...
    trial.DisplayName);

fprintf( ...
    "Marker file:\n%s\n", ...
    trial.Inputs.MarkerFile);

fprintf( ...
    "Process-1 output directory:\n%s\n", ...
    trial.Paths.Initialization.Directory);

%% SECTION 2 — RUN PROCESS 1

runCfg = struct;

runCfg.executeIk = true;

% Use the shared project overwrite policy unless intentionally overridden
% for this interactive run.
runCfg.overwrite = ...
    projectCfg.overwriteExisting;

result = ...
    pipeline.runInitializationIkTrial( ...
        projectCfg, ...
        trial, ...
        "ExecuteIk", ...
            runCfg.executeIk, ...
        "Overwrite", ...
            runCfg.overwrite, ...
        "WriteQc", ...
            true, ...
        "SaveCheckpoint", ...
            true, ...
        "PrintProgress", ...
            true);

%% SECTION 3 — REVIEW

if result.Completed

    fprintf( ...
        "\nInitialization-IK Process 1 completed.\n");

    fprintf( ...
        "Model A:\n%s\n", ...
        result.Paths.ModelAFile);

    fprintf( ...
        "IK motion:\n%s\n", ...
        result.Paths.IkMotionFile);

    fprintf( ...
        "Checkpoint:\n%s\n", ...
        result.CheckpointFile);

    fprintf( ...
        "\nCoordinates requiring immediate visual review:\n");

    disp(result.AttentionAudit);

    fprintf( ...
        "\nNEXT MANUAL CHECKS\n");

    fprintf( ...
        "1. Open Model A and the initialization IK motion in OpenSim.\n");

    fprintf( ...
        "2. Review marker fit and C4-C5 segmental rotations.\n");

    fprintf( ...
        "3. Confirm constraints prevented nonphysiological motion.\n");

    fprintf( ...
        "4. Review IK marker RMS and maximum errors in the OpenSim log.\n");

    fprintf( ...
        "5. If acceptable, proceed to Model B / final IK.\n");

else

    fprintf( ...
        ["\nModel A and the initialization IK setup were prepared, " ...
         "but IK execution was disabled.\n"]);

    fprintf( ...
        "Setup XML:\n%s\n", ...
        result.Paths.IkSetupFile);
end
