%% run_single_trial_static_optimization_prep.m
% Thin single-trial driver for Process 3:
%   Model C + Body Kinematics + HSF + ExternalLoads + SO setup.
%
% The pipeline implementation lives in:
%
%   pipeline.resolveTrialContext
%   pipeline.prepareStaticOptimizationTrial
%
% This script contains only orchestration and interactive review choices.
% Batch Process 3 calls the same worker.

%% SECTION 0 — PROJECT CONFIGURATION

clear;
clc;
dbstop if error

projectCfg = ...
    load_project_config();

fprintf( ...
    "Project root:\n%s\n", ...
    projectCfg.projectRoot);

%% SECTION 1 — SELECT TRIAL

conditionDeg = 45;
trialNumber = 1;

trial = ...
    pipeline.resolveTrialContext( ...
        projectCfg, ...
        conditionDeg, ...
        trialNumber);

fprintf( ...
    "Resolved %s.\n", ...
    trial.DisplayName);

fprintf( ...
    "Process-2 checkpoint:\n%s\n", ...
    trial.Paths.ModelB.CheckpointFile);

fprintf( ...
    "Process-3 output directory:\n%s\n", ...
    trial.Paths.StaticOptimizationPrep.Directory);

%% SECTION 2 — OPTIONAL MODEL C FORCE-CAPACITY CONFIGURATION
%
% The interactive example always asks whether a saved ForceSet JSON should
% be applied to Model C. This modifies only a local copy of projectCfg;
% project_local.m and the shared project configuration remain unchanged.
%
% Batch Process 3 remains non-interactive and continues to use the
% configured projectCfg.forceCapacity settings directly.

runProjectCfg = ...
    projectCfg;

% Start this interactive run with force-capacity application disabled.
% Selecting a JSON below explicitly enables it for Model C.
runProjectCfg.forceCapacity.enabled = false;
runProjectCfg.forceCapacity.configFile = "";

fprintf( ...
    "\n===================\n" + ...
    "USER INPUT REQUIRED\n" + ...
    "===================\n");

fprintf( ...
    "\nOPTIONAL MODEL C FORCE-CAPACITY CONFIGURATION\n");

fprintf( ...
    "  [1] Select a saved force-capacity JSON file\n");

fprintf( ...
    "  [2] Continue without applying a force-capacity configuration\n");

forceConfigChoice = ...
    localPromptForChoice( ...
        "Selection [1/2]: ", ...
        ["1","2"]);

if forceConfigChoice == "1"

    forceConfigResolved = false;

    while ~forceConfigResolved

        selectedConfigFile = ...
            localSelectForceCapacityConfig( ...
                projectCfg);

        if strlength(selectedConfigFile) == 0

            fprintf( ...
                "\nFile selection was cancelled. " + ...
                "Continuing without a force-capacity configuration.\n");

            forceConfigResolved = true;
            continue;
        end

        try

            loadedForceConfig = ...
                modelprep.loadForceCapacityConfig( ...
                    selectedConfigFile);

            runProjectCfg.forceCapacity.enabled = ...
                true;

            runProjectCfg.forceCapacity.configFile = ...
                selectedConfigFile;

            % Respect the apply mode saved in the JSON itself.
            runProjectCfg.forceCapacity.applyMode = ...
                lower(string( ...
                    loadedForceConfig.Config.DefaultApplyMode));

            if ~isfield( ...
                    runProjectCfg.forceCapacity, ...
                    "requireAllEntries")

                runProjectCfg.forceCapacity.requireAllEntries = ...
                    true;
            end

            runProjectCfg.forceCapacity.applyStages = ...
                "modelC";

            fprintf( ...
                "\nSelected force-capacity configuration:\n%s\n", ...
                selectedConfigFile);

            fprintf( ...
                "JSON entries: %d\n", ...
                double( ...
                    loadedForceConfig.Config.EntryCount));

            fprintf( ...
                "Apply mode: %s\n", ...
                runProjectCfg.forceCapacity.applyMode);

            fprintf( ...
                "The configuration will be applied to Model C only.\n");

            forceConfigResolved = true;

        catch exception

            fprintf( ...
                "\nThe selected JSON is not a valid " + ...
                "force-capacity configuration.\n");

            fprintf( ...
                "Validation error: %s\n", ...
                string(exception.message));

            fprintf( ...
                "\n  [1] Select another JSON file\n");

            fprintf( ...
                "  [2] Continue without a force-capacity configuration\n");

            invalidConfigChoice = ...
                localPromptForChoice( ...
                    "Selection [1/2]: ", ...
                    ["1","2"]);

            if invalidConfigChoice == "2"

                fprintf( ...
                    "\nContinuing without a " + ...
                    "force-capacity configuration.\n");

                forceConfigResolved = true;
            end
        end
    end

else

    fprintf( ...
        "\nContinuing without a force-capacity configuration.\n");
end

%% SECTION 3 — RUN PROCESS 3

runCfg = struct;

runCfg.executeBodyKinematics = true;

runCfg.overwrite = ...
    runProjectCfg.overwriteExisting;

result = ...
    pipeline.prepareStaticOptimizationTrial( ...
        runProjectCfg, ...
        trial, ...
        "ExecuteBodyKinematics", ...
            runCfg.executeBodyKinematics, ...
        "Overwrite", ...
            runCfg.overwrite, ...
        "WriteQc", ...
            true, ...
        "SaveCheckpoint", ...
            true, ...
        "EventFigureVisible", ...
            "on", ...
        "PrintProgress", ...
            true);

%% SECTION 4 — REVIEW

if result.Completed

    fprintf( ...
        "\nStatic-Optimization preparation Process 3 completed.\n");

    if result.ForceCapacityConfigResult.Applied

        fprintf( ...
            "Force-capacity configuration applied:\n%s\n", ...
            result.ForceCapacityConfigResult.ConfigFile);

        fprintf( ...
            "Force-capacity apply mode: %s\n", ...
            result.ForceCapacityConfigResult.ApplyMode);

    else

        fprintf( ...
            "Force-capacity configuration: not applied.\n");
    end

    fprintf( ...
        "Model C:\n%s\n", ...
        result.Paths.ModelCFile);

    fprintf( ...
        "Body Kinematics position file:\n%s\n", ...
        result.BodyKinematicsResult.PositionFile);

    fprintf( ...
        "HSF MOT:\n%s\n", ...
        result.Paths.HeadSupportForce.MotionFile);

    fprintf( ...
        "ExternalLoads XML:\n%s\n", ...
        result.Paths.HeadSupportForce.ExternalLoadsFile);

    fprintf( ...
        "SO setup XML:\n%s\n", ...
        result.StaticOptimizationPaths.SetupFile);

    fprintf( ...
        "Checkpoint:\n%s\n", ...
        result.CheckpointFile);

    fprintf( ...
        "\nModel C sagittal-coordinate state:\n");

    disp(result.SagittalState);

    fprintf( ...
        "\nSkull CoM summary:\n");

    disp(result.ComSummary);

    fprintf( ...
        "\nDetected contact events:\n");

    disp(result.EventDetectionResult.Summary);

    fprintf( ...
        "\nHSF summary:\n");

    disp(result.HsfResult.Summary);

    fprintf( ...
        "\nNEXT MANUAL CHECKS\n");

    fprintf( ...
        "1. Inspect the contact-event detection plot.\n");

    fprintf( ...
        "2. Plot HSF force components, magnitude, and support envelope.\n");

    fprintf( ...
        "3. Confirm zero force spans detected lift-off to re-contact.\n");

    fprintf( ...
        "4. Confirm HSF point columns track skull CoM throughout.\n");

    fprintf( ...
        "5. Preview the HSF ExternalLoads with Model C in OpenSim.\n");

    fprintf( ...
        "6. Verify the SO setup paths and time bounds.\n");

    fprintf( ...
        "7. If acceptable, proceed to Process 4 / Static Optimization.\n");

else

    fprintf( ...
        "\nModel C was prepared, but Body Kinematics execution " + ...
        "was disabled.\n");

    fprintf( ...
        "Model C:\n%s\n", ...
        result.Paths.ModelCFile);
end

function choice = localPromptForChoice(promptText, validChoices)
%LOCALPROMPTFORCHOICE Wait for a valid command-line selection.

    validChoices = ...
        string(validChoices(:));

    while true

        rawChoice = ...
            input( ...
                char(promptText), ...
                "s");

        choice = ...
            strtrim(string(rawChoice));

        if any(choice == validChoices)
            return;
        end

        fprintf( ...
            "Invalid selection. Enter one of: %s\\n", ...
            strjoin(validChoices, ", "));
    end
end


function configFile = localSelectForceCapacityConfig(projectCfg)
%LOCALSELECTFORCECAPACITYCONFIG Open a JSON file-selection window.
%
% Returns "" when the user cancels the file dialog.

    startDirectory = ...
        string(projectCfg.configDirectory);

    if isfield(projectCfg, "forceCapacity") && ...
            isfield( ...
                projectCfg.forceCapacity, ...
                "configFile")

        configuredFile = ...
            string( ...
                projectCfg.forceCapacity.configFile);

        if strlength(configuredFile) > 0

            configuredDirectory = ...
                string(fileparts(configuredFile));

            if isfolder(configuredDirectory)

                startDirectory = ...
                    configuredDirectory;
            end
        end
    end

    if ~isfolder(startDirectory)

        startDirectory = ...
            string(projectCfg.projectRoot);
    end

    [fileName, filePath] = ...
        uigetfile( ...
            {'*.json', ...
             'Force-capacity JSON (*.json)'}, ...
            'Select Model C force-capacity configuration', ...
            char(startDirectory));

    if isequal(fileName, 0) || ...
            isequal(filePath, 0)

        configFile = "";
        return;
    end

    configFile = ...
        string(fullfile( ...
            filePath, ...
            fileName));
end

