%% run_single_trial_model_b.m
% Single-trial validation driver: lock extraction, Model B, and final IK.
%
% Run this script one section at a time. It resumes from the Phase A
% initialization-IK checkpoint and intentionally stops after final-IK QC.
%
% REQUIRED TOOLKIT COMPONENTS
%   load_project_config.m
%   +opensimio
%   +modelprep
%   +opensimrun
%
% REQUIRED PHASE A OUTPUT
%   initialization_ik_checkpoint.mat
%
% MODEL B CONFIGURATION
%   - Coordinate-coupler constraints enabled
%   - Root coordinates locked
%   - Independent roll/yaw coordinates locked
%   - Independent sagittal coordinates unlocked
%   - All auxiliary coordinates remain unlocked, dependent, and constrained
%   - Dependent r1/r2 coordinates are expected to remain constant because
%     their independent out-of-plane drivers are locked
%   - Dependent r3 coordinates remain free to vary through their sagittal
%     coupler relationships
%
% FINAL-IK QC GOALS
%   - Verify the ten requested Model B locks
%   - Verify dependent-coordinate model state
%   - Describe dependent out-of-plane behavior without treating it as a
%     generic stability test
%   - Quantify independent and dependent sagittal motion for Model C design

%% SECTION 0 — LOAD PROJECT AND TRIAL CONFIGURATION

clear;
clc;
dbstop if error

% Live Editor evaluates sections through a temporary helper file, so prefer
% the active Editor document when locating the repository.
activeFile = string(matlab.desktop.editor.getActiveFilename);

if strlength(activeFile) > 0 && isfile(activeFile)
    scriptFile = activeFile;
else
    scriptFile = string(mfilename("fullpath"));
end

assert(strlength(scriptFile) > 0 && isfile(scriptFile), ...
    "ModelBPipeline:ScriptLocationUnknown", ...
    "Save and open this script in the MATLAB Editor before running its sections.");

examplesDirectory = string(fileparts(scriptFile));
projectRoot = string(fileparts(examplesDirectory));

assert(isfolder(fullfile(projectRoot, "+modelprep")), ...
    "ModelBPipeline:ProjectRootNotFound", ...
    "The inferred project root does not contain +modelprep:\n%s\n\nSave this script under the repository's examples folder.", ...
    projectRoot);

addpath(projectRoot);

projectCfg = load_project_config();

assert(string(projectCfg.projectRoot) == projectRoot, ...
    "ModelBPipeline:ProjectRootMismatch", ...
    "Script-inferred project root:\n%s\n\nConfiguration project root:\n%s", ...
    projectRoot, projectCfg.projectRoot);

trialCfg = struct;

% Trial identity.
trialCfg.conditionDeg = 45;
trialCfg.trialNumber = 1;

% Initial support interval used to assess filtering and extract the
% Model B lock values. The 0.10 s offset avoids the beginning-of-record
% endpoint while preserving the intended 0.25 s supported-pose duration.
trialCfg.lockWindow = [0.10, 0.15];

% Leave empty to use the Phase A checkpoint marker-file path.
% Set an explicit local path when the checkpoint was created elsewhere.
trialCfg.markerFile = "";

% Execution controls.
trialCfg.overwriteExisting = projectCfg.overwriteExisting;
trialCfg.executeFinalIk = true;

fprintf( ...
    "Machine: %s\nCondition: %g deg\nTrial: %d\n", ...
    projectCfg.machineName, ...
    trialCfg.conditionDeg, ...
    trialCfg.trialNumber);


%% SECTION 1 — RESOLVE PHASE A AND MODEL B PATHS

conditionFolderName = sprintf( ...
    "%02ddeg", round(trialCfg.conditionDeg));

trialFolderName = sprintf( ...
    "trial%02d", trialCfg.trialNumber);

trialRoot = string(fullfile( ...
    projectCfg.outputRoot, ...
    conditionFolderName, ...
    trialFolderName));

phaseADirectory = string(fullfile( ...
    trialRoot, ...
    "01_initialization_ik"));

phaseAQcDirectory = string(fullfile( ...
    phaseADirectory, ...
    "qc"));

phaseBDirectory = string(fullfile( ...
    trialRoot, ...
    "02_locked_final_ik"));

phaseBQcDirectory = string(fullfile( ...
    phaseBDirectory, ...
    "qc"));

if ~isfolder(phaseBDirectory)
    mkdir(phaseBDirectory);
end

if ~isfolder(phaseBQcDirectory)
    mkdir(phaseBQcDirectory);
end

paths = struct;

paths.trialRoot = trialRoot;
paths.phaseADirectory = phaseADirectory;
paths.phaseAQcDirectory = phaseAQcDirectory;
paths.phaseBDirectory = phaseBDirectory;
paths.phaseBQcDirectory = phaseBQcDirectory;

paths.initializationCheckpointFile = string(fullfile( ...
    phaseAQcDirectory, ...
    "initialization_ik_checkpoint.mat"));

paths.modelAFile = string(fullfile( ...
    phaseADirectory, ...
    sprintf("%s_%s_modelA_initialization.osim", ...
    conditionFolderName, trialFolderName)));

paths.initialIkMotionFile = string(fullfile( ...
    phaseADirectory, ...
    sprintf("%s_%s_initialization_ik.mot", ...
    conditionFolderName, trialFolderName)));

% Model-B-specific preprocessing artifact. The raw Phase A IK output is
% preserved unchanged.
paths.filteredInitialIkMotionFile = string(fullfile( ...
    phaseBDirectory, ...
    sprintf("%s_%s_initialization_ik_filtered_for_locks.mot", ...
    conditionFolderName, trialFolderName)));

paths.modelBFile = string(fullfile( ...
    phaseBDirectory, ...
    sprintf("%s_%s_modelB_locked_ik.osim", ...
    conditionFolderName, trialFolderName)));

paths.finalIkSetupFile = string(fullfile( ...
    phaseBDirectory, ...
    sprintf("%s_%s_final_ik_setup.xml", ...
    conditionFolderName, trialFolderName)));

paths.finalIkMotionFile = string(fullfile( ...
    phaseBDirectory, ...
    sprintf("%s_%s_final_ik.mot", ...
    conditionFolderName, trialFolderName)));

paths.lockFilterAuditCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "modelB_lock_filter_audit.csv"));

paths.lockValuesCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "modelB_lock_values.csv"));

paths.modelBCoordinateConfigurationCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "modelB_coordinate_configuration.csv"));

paths.modelBConstraintConfigurationCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "modelB_constraint_configuration.csv"));

paths.modelBDependentCoordinateStateCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "modelB_dependent_coordinate_state.csv"));

paths.lockedCoordinateAuditCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "final_ik_locked_coordinate_audit.csv"));

paths.independentSagittalStateCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "modelB_independent_sagittal_state.csv"));

paths.dependentOutOfPlaneSummaryCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "final_ik_dependent_out_of_plane_summary.csv"));

paths.independentSagittalSummaryCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "final_ik_independent_sagittal_summary.csv"));

paths.dependentSagittalSummaryCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "final_ik_dependent_sagittal_summary.csv"));

paths.sagittalSummaryCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "final_ik_sagittal_summary.csv"));

paths.sagittalTrajectoriesCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "final_ik_sagittal_trajectories.csv"));

paths.sagittalRelativeTrajectoriesCsv = string(fullfile( ...
    phaseBQcDirectory, ...
    "final_ik_sagittal_relative_trajectories.csv"));

paths.runSummaryMat = string(fullfile( ...
    phaseBQcDirectory, ...
    "model_b_final_ik_checkpoint.mat"));

disp(paths);


%% SECTION 2 — LOAD AND VALIDATE THE PHASE A CHECKPOINT

assert(isfile(paths.initializationCheckpointFile), ...
    "ModelBPipeline:CheckpointMissing", ...
    "Phase A checkpoint was not found:\n%s", ...
    paths.initializationCheckpointFile);

loadedCheckpoint = load( ...
    paths.initializationCheckpointFile, ...
    "checkpoint");

assert(isfield(loadedCheckpoint, "checkpoint"), ...
    "ModelBPipeline:CheckpointVariableMissing", ...
    "The MAT file does not contain a variable named checkpoint.");

checkpointA = loadedCheckpoint.checkpoint;

requiredCheckpointFields = [ ...
    "Configuration"
    "Paths"
    "ModelAValidation"
    "IkMotionSummary"
    "IkRunResult"
];

for fieldName = requiredCheckpointFields.'
    assert(isfield(checkpointA, fieldName), ...
        "ModelBPipeline:CheckpointFieldMissing", ...
        "Phase A checkpoint is missing field: %s", ...
        fieldName);
end

assert(logical(checkpointA.ModelAValidation.Passed), ...
    "ModelBPipeline:ModelAWasInvalid", ...
    "The Phase A checkpoint reports that Model A failed validation.");

assert(logical(checkpointA.IkRunResult.RunSucceeded), ...
    "ModelBPipeline:InitializationIkFailed", ...
    "The Phase A checkpoint reports that initialization IK failed.");

assert( ...
    checkpointA.Configuration.conditionDeg == ...
        trialCfg.conditionDeg, ...
    "ModelBPipeline:ConditionMismatch", ...
    ["Configured condition is %g deg, but the checkpoint is for " ...
     "%g deg."], ...
    trialCfg.conditionDeg, ...
    checkpointA.Configuration.conditionDeg);

assert( ...
    checkpointA.Configuration.trialNumber == ...
        trialCfg.trialNumber, ...
    "ModelBPipeline:TrialMismatch", ...
    "Configured trial is %d, but the checkpoint is for trial %d.", ...
    trialCfg.trialNumber, ...
    checkpointA.Configuration.trialNumber);

assert(isfile(paths.modelAFile), ...
    "ModelBPipeline:ModelAMissing", ...
    "Model A was not found:\n%s", ...
    paths.modelAFile);

assert(isfile(paths.initialIkMotionFile), ...
    "ModelBPipeline:InitializationMotionMissing", ...
    "Initialization IK motion was not found:\n%s", ...
    paths.initialIkMotionFile);

assert(isfile(projectCfg.kinematicBaseModel), ...
    "ModelBPipeline:BaseModelMissing", ...
    "Configured kinematic base model was not found:\n%s", ...
    projectCfg.kinematicBaseModel);

assert(isfile(projectCfg.initializationIkTemplate), ...
    "ModelBPipeline:IkTemplateMissing", ...
    "Configured IK template was not found:\n%s", ...
    projectCfg.initializationIkTemplate);

if strlength(string(trialCfg.markerFile)) == 0
    markerFile = string(checkpointA.Configuration.markerFile);
else
    markerFile = string(trialCfg.markerFile);
end

assert(isfile(markerFile), ...
    "ModelBPipeline:MarkerFileMissing", ...
    "Marker file was not found:\n%s\n\nIf the checkpoint came from another computer, set trialCfg.markerFile to the local marker-file path.", ...
    markerFile);

trialTimeRange = [ ...
    checkpointA.IkMotionSummary.StartTime, ...
    checkpointA.IkMotionSummary.EndTime];

assert( ...
    trialCfg.lockWindow(1) >= trialTimeRange(1) && ...
    trialCfg.lockWindow(2) <= trialTimeRange(2) && ...
    trialCfg.lockWindow(2) > trialCfg.lockWindow(1), ...
    "ModelBPipeline:InvalidLockWindow", ...
    "Lock window [%.9g, %.9g] must lie within the trial range [%.9g, %.9g].", ...
    trialCfg.lockWindow(1), ...
    trialCfg.lockWindow(2), ...
    trialTimeRange(1), ...
    trialTimeRange(2));

fprintf( ...
    "Phase A checkpoint validated. Trial range: %.5f to %.5f s.\n", ...
    trialTimeRange(1), trialTimeRange(2));


%% SECTION 3 — LOAD SHARED QC SETTINGS

assert(isfield(projectCfg, "qc"), ...
    "ModelBPipeline:QcConfigMissing", ...
    "projectCfg.qc is not defined in project_defaults.m.");

assert(isfield(projectCfg.qc, "lockExtraction"), ...
    "ModelBPipeline:LockExtractionConfigMissing", ...
    "projectCfg.qc.lockExtraction is not defined. Add the Model B QC block to config/project_defaults.m.");

assert(isfield(projectCfg.qc, "lockExtractionFilter"), ...
    "ModelBPipeline:LockFilterConfigMissing", ...
    "projectCfg.qc.lockExtractionFilter is not defined. Add the Model B filtering block to config/project_defaults.m.");

assert(isfield(projectCfg.qc, "lockAudit"), ...
    "ModelBPipeline:LockAuditConfigMissing", ...
    "projectCfg.qc.lockAudit is not defined. Add the locked-coordinate audit block to config/project_defaults.m.");

extractionQc = projectCfg.qc.lockExtraction;
filterQc = projectCfg.qc.lockExtractionFilter;
auditQc = projectCfg.qc.lockAudit;

requiredExtractionFields = [ ...
    "statistic"
    "rotationToleranceDeg"
    "translationToleranceM"
    "otherToleranceSI"
    "minimumSamples"
    "requireStable"
];

for fieldName = requiredExtractionFields.'
    assert(isfield(extractionQc, fieldName), ...
        "ModelBPipeline:LockExtractionFieldMissing", ...
        "Missing projectCfg.qc.lockExtraction.%s", ...
        fieldName);
end

requiredFilterFields = [ ...
    "enabled"
    "filterCoordinates"
    "prototypeOrder"
    "selectedCutoffHz"
];

for fieldName = requiredFilterFields.'
    assert(isfield(filterQc, fieldName), ...
        "ModelBPipeline:LockFilterFieldMissing", ...
        "Missing projectCfg.qc.lockExtractionFilter.%s", ...
        fieldName);
end

assert(islogical(filterQc.enabled) && isscalar(filterQc.enabled), ...
    "ModelBPipeline:InvalidLockFilterEnabled", ...
    "projectCfg.qc.lockExtractionFilter.enabled must be a logical scalar.");

if filterQc.enabled
    assert(~isempty(filterQc.filterCoordinates), ...
        "ModelBPipeline:NoFilterCoordinates", ...
        "Filtering is enabled but filterCoordinates is empty.");

    assert(isnumeric(filterQc.prototypeOrder) && ...
        isscalar(filterQc.prototypeOrder) && ...
        isfinite(filterQc.prototypeOrder) && ...
        filterQc.prototypeOrder >= 1 && ...
        mod(filterQc.prototypeOrder, 1) == 0, ...
        "ModelBPipeline:InvalidFilterOrder", ...
        "prototypeOrder must be a positive integer.");

    assert(isnumeric(filterQc.selectedCutoffHz) && ...
        isscalar(filterQc.selectedCutoffHz) && ...
        isfinite(filterQc.selectedCutoffHz) && ...
        filterQc.selectedCutoffHz > 0, ...
        "ModelBPipeline:InvalidFilterCutoff", ...
        "selectedCutoffHz must be a positive finite scalar when filtering is enabled.");
end

requiredAuditFields = [ ...
    "statistic"
    "rotationRangeToleranceDeg"
    "translationRangeToleranceM"
    "otherRangeToleranceSI"
    "rotationMatchToleranceDeg"
    "translationMatchToleranceM"
    "otherMatchToleranceSI"
    "minimumSamples"
    "requirePass"
];

for fieldName = requiredAuditFields.'
    assert(isfield(auditQc, fieldName), ...
        "ModelBPipeline:LockAuditFieldMissing", ...
        "Missing projectCfg.qc.lockAudit.%s", ...
        fieldName);
end

disp(extractionQc);
disp(filterQc);
disp(auditQc);


%% SECTION 4 — FILTER INITIALIZATION IK FOR LOCK EXTRACTION

groups = modelprep.coordinateGroups();

requiredGroupFields = [ ...
    "Root"
    "IndependentOutOfPlane"
    "DependentOutOfPlane"
    "IndependentSagittal"
    "DependentSagittal"
    "Sagittal"
    "AllDependent"
    "FinalIkLocked"
];

for iGroup = 1:numel(requiredGroupFields)
    groupName = requiredGroupFields(iGroup);

    assert(isfield(groups, groupName), ...
        "ModelBPipeline:CoordinateGroupMissing", ...
        "modelprep.coordinateGroups is missing groups.%s.", ...
        groupName);
end

% By default, use the raw Phase A initialization IK. When filtering is
% enabled, this variable is redirected to the filtered Phase B artifact.
lockExtractionMotionFile = paths.initialIkMotionFile;

lockFilterResult = struct;
lockFilterResult.Enabled = logical(filterQc.enabled);

if filterQc.enabled

    filterCoordinates = ...
        reshape(string(filterQc.filterCoordinates), 1, []);

    assert(all(ismember(filterCoordinates, groups.FinalIkLocked)), ...
        "ModelBPipeline:UnexpectedFilterCoordinate", ...
        "All lock-extraction filter coordinates must belong to groups.FinalIkLocked. Requested: %s", ...
        strjoin(filterCoordinates, ", "));

    if isfile(paths.filteredInitialIkMotionFile) && ...
            ~trialCfg.overwriteExisting
        error("ModelBPipeline:OutputExists", ...
            "Filtered initialization IK already exists:\n%s\n\nSet trialCfg.overwriteExisting=true to regenerate it.", ...
            paths.filteredInitialIkMotionFile);
    end

    filterResult = ...
        modelprep.filterCoordinateMotion( ...
        paths.initialIkMotionFile, ...
        filterCoordinates, ...
        "CutoffHz", filterQc.selectedCutoffHz, ...
        "PrototypeOrder", filterQc.prototypeOrder, ...
        "AuditWindow", trialCfg.lockWindow);

    opensimio.writeOpenSimTable( ...
        paths.filteredInitialIkMotionFile, ...
        filterResult.Motion);

    writetable( ...
        filterResult.Audit, ...
        paths.lockFilterAuditCsv);

    lockExtractionMotionFile = ...
        paths.filteredInitialIkMotionFile;

    lockFilterResult.Enabled = true;
    lockFilterResult.SourceMotionFile = ...
        paths.initialIkMotionFile;
    lockFilterResult.FilteredMotionFile = ...
        paths.filteredInitialIkMotionFile;
    lockFilterResult.AuditFile = ...
        paths.lockFilterAuditCsv;
    lockFilterResult.FilteredCoordinates = ...
        filterResult.FilteredCoordinates;
    lockFilterResult.SampleRateHz = ...
        filterResult.SampleRateHz;
    lockFilterResult.CutoffHz = ...
        filterResult.CutoffHz;
    lockFilterResult.PrototypeOrder = ...
        filterResult.PrototypeOrder;
    lockFilterResult.EffectiveZeroPhaseOrder = ...
        filterResult.EffectiveZeroPhaseOrder;
    lockFilterResult.AuditWindow = ...
        filterResult.AuditWindow;
    lockFilterResult.NumAuditSamples = ...
        filterResult.NumAuditSamples;
    lockFilterResult.Audit = ...
        filterResult.Audit;

    fprintf( ...
        "Filtered initialization IK for Model B lock extraction.\nCoordinates: %s\nCutoff: %.3f Hz\nPrototype order: %d (effective zero-phase order %d)\nFiltered motion:\n%s\n", ...
        strjoin(filterCoordinates, ", "), ...
        filterResult.CutoffHz, ...
        filterResult.PrototypeOrder, ...
        filterResult.EffectiveZeroPhaseOrder, ...
        paths.filteredInitialIkMotionFile);

    disp(filterResult.Audit);

else

    lockFilterResult.SourceMotionFile = ...
        paths.initialIkMotionFile;
    lockFilterResult.FilteredMotionFile = "";
    lockFilterResult.AuditFile = "";
    lockFilterResult.FilteredCoordinates = strings(1, 0);

    fprintf( ...
        "Lock-extraction filtering is disabled. Using the raw Phase A initialization IK.\n");

end

fprintf( ...
    "Motion used for Model B lock extraction:\n%s\n", ...
    lockExtractionMotionFile);

% CHECKPOINT:
% Review modelB_lock_filter_audit.csv before continuing. Confirm that the
% filtered yaw coordinates have acceptable range/standard deviation within
% trialCfg.lockWindow and that the median shifts remain reasonable.


%% SECTION 5 — EXTRACT TRIAL-SPECIFIC MODEL B LOCK VALUES

lockValues = modelprep.extractStableCoordinateValues( ...
    lockExtractionMotionFile, ...
    paths.modelAFile, ...
    groups.FinalIkLocked, ...
    trialCfg.lockWindow, ...
    "Method", extractionQc.statistic, ...
    "RotationToleranceDeg", ...
        extractionQc.rotationToleranceDeg, ...
    "TranslationToleranceM", ...
        extractionQc.translationToleranceM, ...
    "OtherTolerance", ...
        extractionQc.otherToleranceSI, ...
    "RequireStable", false, ...
    "MinimumSamples", ...
        extractionQc.minimumSamples);

writetable(lockValues, paths.lockValuesCsv);

disp(lockValues);

if any(~lockValues.IsStable)
    unstableCoordinates = ...
        lockValues.Coordinate(~lockValues.IsStable);

    fprintf( ...
        "\nCoordinates exceeding the extraction tolerance:\n%s\n", ...
        strjoin(unstableCoordinates, ", "));
end

if extractionQc.requireStable
    assert(all(lockValues.IsStable), ...
        "ModelBPipeline:UnstableLockValues", ...
        "One or more coordinates are unstable in the selected window. Review modelB_lock_values.csv and modelB_lock_filter_audit.csv.");
end

fprintf( ...
    "Lock values extracted from [%.5f, %.5f] s and saved:\n%s\n", ...
    trialCfg.lockWindow(1), ...
    trialCfg.lockWindow(2), ...
    paths.lockValuesCsv);

% CHECKPOINT:
% Review modelB_lock_values.csv before constructing Model B. The six root
% coordinates and four independent roll/yaw coordinates should represent
% the supported initial pose.


%% SECTION 6 — BUILD MODEL B

if isfile(paths.modelBFile) && ~trialCfg.overwriteExisting
    error("ModelBPipeline:OutputExists", ...
        "Model B already exists:\n%s", ...
        paths.modelBFile);
end

modelBResult = modelprep.buildLockedIkModel( ...
    projectCfg.kinematicBaseModel, ...
    lockValues, ...
    paths.modelBFile, ...
    "CoordinateNames", groups.FinalIkLocked, ...
    "RequireStable", extractionQc.requireStable);

writetable( ...
    modelBResult.Inspection.Coordinates, ...
    paths.modelBCoordinateConfigurationCsv);

writetable( ...
    modelBResult.Inspection.Constraints, ...
    paths.modelBConstraintConfigurationCsv);

fprintf("Model B written:\n%s\n", paths.modelBFile);


%% SECTION 7 — VALIDATE MODEL B CONFIGURATION

modelBInspection = modelprep.inspectModel(paths.modelBFile);

allCoordinateNames = ...
    modelBInspection.Coordinates.Coordinate;

expectedUnlocked = setdiff( ...
    allCoordinateNames, ...
    groups.FinalIkLocked, ...
    "stable");

modelBValidation = modelprep.validateModelConfiguration( ...
    paths.modelBFile, ...
    "ExpectedLocked", groups.FinalIkLocked, ...
    "ExpectedUnlocked", expectedUnlocked, ...
    "ExpectedConstraintsEnforced", true, ...
    "ThrowOnFailure", true);

assert(modelBValidation.Passed, ...
    "ModelBPipeline:ModelBValidationFailed", ...
    "Model B configuration validation failed.");

% Inspect all auxiliary coordinates that are dependent on couplers.
dependentRows = ismember( ...
    modelBInspection.Coordinates.Coordinate, ...
    groups.AllDependent);

dependentCoordinateState = ...
    modelBInspection.Coordinates(dependentRows, { ...
        'Coordinate'
        'DefaultLocked'
        'StateLocked'
        'StateDependent'
        'StateConstrained'
    });

writetable( ...
    dependentCoordinateState, ...
    paths.modelBDependentCoordinateStateCsv);

fprintf("\nAll dependent-coordinate Model B states:\n");
disp(dependentCoordinateState);

assert(all(~dependentCoordinateState.DefaultLocked), ...
    "ModelBPipeline:DependentCoordinateDefaultLocked", ...
    "One or more dependent auxiliary coordinates are default-locked.");

assert(all(~dependentCoordinateState.StateLocked), ...
    "ModelBPipeline:DependentCoordinateStateLocked", ...
    "One or more dependent auxiliary coordinates are state-locked.");

assert(all(dependentCoordinateState.StateDependent), ...
    "ModelBPipeline:DependentCoordinateNotDependent", ...
    "One or more expected auxiliary coordinates are not dependent.");

assert(all(dependentCoordinateState.StateConstrained), ...
    "ModelBPipeline:DependentCoordinateUnconstrained", ...
    "One or more expected auxiliary coordinates are not constrained.");

% Inspect the independent sagittal drivers separately. These should remain
% unlocked so final IK can solve the intended flexion/extension motion.
independentSagittalRows = ismember( ...
    modelBInspection.Coordinates.Coordinate, ...
    groups.IndependentSagittal);

independentSagittalState = ...
    modelBInspection.Coordinates(independentSagittalRows, { ...
        'Coordinate'
        'DefaultLocked'
        'StateLocked'
        'StateDependent'
        'StateConstrained'
    });

writetable( ...
    independentSagittalState, ...
    paths.independentSagittalStateCsv);

fprintf("\nIndependent sagittal-coordinate Model B states:\n");
disp(independentSagittalState);

assert(all(~independentSagittalState.DefaultLocked), ...
    "ModelBPipeline:IndependentSagittalDefaultLocked", ...
    "One or more independent sagittal coordinates are default-locked.");

assert(all(~independentSagittalState.StateLocked), ...
    "ModelBPipeline:IndependentSagittalStateLocked", ...
    "One or more independent sagittal coordinates are state-locked.");

assert(all(~independentSagittalState.StateDependent), ...
    "ModelBPipeline:IndependentSagittalUnexpectedlyDependent", ...
    "One or more expected independent sagittal coordinates are dependent.");

fprintf( ...
    "Model B validation passed: requested coordinates locked, all auxiliary coordinates dependent/constrained, and independent sagittal drivers unlocked.\n");


%% SECTION 8 — CREATE THE FINAL-IK SETUP

if isfile(paths.finalIkSetupFile) && ...
        ~trialCfg.overwriteExisting
    error("ModelBPipeline:OutputExists", ...
        "Final-IK setup already exists:\n%s", ...
        paths.finalIkSetupFile);
end

finalIkSetupResult = ...
    opensimrun.prepareInverseKinematicsSetup( ...
    projectCfg.initializationIkTemplate, ...
    paths.finalIkSetupFile, ...
    "ModelFile", paths.modelBFile, ...
    "MarkerFile", markerFile, ...
    "OutputMotionFile", paths.finalIkMotionFile, ...
    "TimeRange", trialTimeRange, ...
    "ToolName", sprintf( ...
        "%s_%s_final_ik", ...
        conditionFolderName, trialFolderName), ...
    "Overwrite", trialCfg.overwriteExisting);

disp(finalIkSetupResult.PatchReport);

fprintf("Final-IK setup written:\n%s\n", ...
    paths.finalIkSetupFile);

% CHECKPOINT:
% Open the generated XML before running Section 9. Confirm the marker task
% set, weights, time range, output path, constraint weight, and accuracy.


%% SECTION 9 — RUN FINAL IK WITH MODEL B

if ~trialCfg.executeFinalIk
    fprintf( ...
        "Final IK execution is disabled. Review the setup XML, then set trialCfg.executeFinalIk=true and rerun this section.\n");
else
    finalIkRunResult = ...
        opensimrun.runInverseKinematicsSetup( ...
        paths.finalIkSetupFile, ...
        "ModelInput", paths.modelBFile, ...
        "ExpectedOutputMotionFile", ...
            paths.finalIkMotionFile, ...
        "Overwrite", trialCfg.overwriteExisting);

    fprintf( ...
        "Final IK completed in %.3f seconds.\n", ...
        finalIkRunResult.DurationSeconds);

    fprintf("Final IK motion file:\n%s\n", ...
        finalIkRunResult.OutputMotionFile);
end


%% SECTION 10 — AUDIT LOCKED COORDINATES

assert(isfile(paths.finalIkMotionFile), ...
    "ModelBPipeline:FinalIkMotionMissing", ...
    "Final IK output was not found:\n%s", ...
    paths.finalIkMotionFile);

lockedCoordinateAudit = ...
    modelprep.auditLockedCoordinates( ...
    paths.finalIkMotionFile, ...
    lockValues, ...
    "ModelInput", paths.modelBFile, ...
    "TimeWindow", trialTimeRange, ...
    "Statistic", auditQc.statistic, ...
    "RotationRangeToleranceDeg", ...
        auditQc.rotationRangeToleranceDeg, ...
    "TranslationRangeToleranceM", ...
        auditQc.translationRangeToleranceM, ...
    "OtherRangeToleranceSI", ...
        auditQc.otherRangeToleranceSI, ...
    "RotationMatchToleranceDeg", ...
        auditQc.rotationMatchToleranceDeg, ...
    "TranslationMatchToleranceM", ...
        auditQc.translationMatchToleranceM, ...
    "OtherMatchToleranceSI", ...
        auditQc.otherMatchToleranceSI, ...
    "MinimumSamples", auditQc.minimumSamples, ...
    "RequirePass", false);

writetable( ...
    lockedCoordinateAudit.Table, ...
    paths.lockedCoordinateAuditCsv);

disp(lockedCoordinateAudit.Table);

fprintf( ...
    "Locked-coordinate audit: %d/%d passed.\n", ...
    lockedCoordinateAudit.NumPassed, ...
    lockedCoordinateAudit.NumCoordinates);

if auditQc.requirePass
    assert(lockedCoordinateAudit.Passed, ...
        "ModelBPipeline:LockedCoordinateAuditFailed", ...
        "Locked coordinates failed QC: %s", ...
        strjoin( ...
        lockedCoordinateAudit.FailedCoordinates, ...
        ", "));
end


%% SECTION 11 — SUMMARIZE FINAL-IK OUT-OF-PLANE AND SAGITTAL MOTION

% IMPORTANT FILE PROVENANCE:
%   The summaries below use Model B's final IK output. They do NOT use the
%   filtered Phase A initialization motion. The filtered motion is only a
%   preprocessing artifact used to determine Model B lock values.
fprintf("\nFinal-IK coordinate summaries use:\n%s\n", ...
    paths.finalIkMotionFile);

% --- 11A. Dependent out-of-plane coordinates ----------------------------
%
% These coordinates remain unlocked in Model B, but they are dependent on
% enabled couplers. Because the independent roll/yaw drivers are locked,
% these trajectories are expected to be constant or numerically constant.
% Report their behavior descriptively rather than reusing a generic
% stability test intended for lock extraction.

dependentOutOfPlaneSummary = ...
    modelprep.summarizeCoordinateMotion( ...
        paths.finalIkMotionFile, ...
        groups.DependentOutOfPlane, ...
        "TimeWindow", trialTimeRange, ...
        "BaselineWindow", trialCfg.lockWindow, ...
        "BaselineStatistic", auditQc.statistic);

writetable( ...
    dependentOutOfPlaneSummary.Summary, ...
    paths.dependentOutOfPlaneSummaryCsv);

fprintf("\nDependent out-of-plane coordinate behavior:\n");
disp(dependentOutOfPlaneSummary.Summary(:, { ...
    'Coordinate'
    'BaselineValue'
    'Minimum'
    'Maximum'
    'Range'
    'PeakAbsoluteExcursionFromBaseline'
}));

maxDependentOutOfPlaneRange = ...
    max(dependentOutOfPlaneSummary.Summary.Range);

fprintf( ...
    "Maximum dependent out-of-plane range in final IK: %.9g\n", ...
    maxDependentOutOfPlaneRange);

if maxDependentOutOfPlaneRange > ...
        auditQc.rotationRangeToleranceDeg

    warning( ...
        "ModelBPipeline:DependentOutOfPlaneVariation", ...
        "One or more dependent out-of-plane coordinates vary by more than the configured rotation range tolerance (%.9g deg). Review %s.", ...
        auditQc.rotationRangeToleranceDeg, ...
        paths.dependentOutOfPlaneSummaryCsv);
else
    fprintf( ...
        "Dependent out-of-plane coordinates are constant within the configured numerical tolerance.\n");
end


% --- 11B. Independent sagittal drivers ----------------------------------
%
% These are the free sagittal coordinates solved directly by final IK.

independentSagittalSummary = ...
    modelprep.summarizeCoordinateMotion( ...
        paths.finalIkMotionFile, ...
        groups.IndependentSagittal, ...
        "TimeWindow", trialTimeRange, ...
        "BaselineWindow", trialCfg.lockWindow, ...
        "BaselineStatistic", auditQc.statistic);

writetable( ...
    independentSagittalSummary.Summary, ...
    paths.independentSagittalSummaryCsv);

fprintf("\nIndependent sagittal driver motion:\n");
disp(independentSagittalSummary.Summary(:, { ...
    'Coordinate'
    'BaselineValue'
    'Minimum'
    'Maximum'
    'Range'
    'MinimumRelativeToBaseline'
    'MaximumRelativeToBaseline'
    'PeakAbsoluteExcursionFromBaseline'
}));


% --- 11C. Dependent sagittal coordinates --------------------------------
%
% These auxiliary r3 coordinates remain dependent on enabled couplers and
% distribute the sagittal motion through the cervical chain.

dependentSagittalSummary = ...
    modelprep.summarizeCoordinateMotion( ...
        paths.finalIkMotionFile, ...
        groups.DependentSagittal, ...
        "TimeWindow", trialTimeRange, ...
        "BaselineWindow", trialCfg.lockWindow, ...
        "BaselineStatistic", auditQc.statistic);

writetable( ...
    dependentSagittalSummary.Summary, ...
    paths.dependentSagittalSummaryCsv);

fprintf("\nDependent sagittal coordinate motion:\n");
disp(dependentSagittalSummary.Summary(:, { ...
    'Coordinate'
    'BaselineValue'
    'Minimum'
    'Maximum'
    'Range'
    'MinimumRelativeToBaseline'
    'MaximumRelativeToBaseline'
    'PeakAbsoluteExcursionFromBaseline'
}));


% --- 11D. Combined sagittal trajectories --------------------------------
%
% Save the complete sagittal trajectories and baseline-relative versions.
% These files provide the direct kinematic input for evaluating how Model C
% should preserve previously coupled sagittal motion.

sagittalMotionSummary = ...
    modelprep.summarizeCoordinateMotion( ...
        paths.finalIkMotionFile, ...
        groups.Sagittal, ...
        "TimeWindow", trialTimeRange, ...
        "BaselineWindow", trialCfg.lockWindow, ...
        "BaselineStatistic", auditQc.statistic);

writetable( ...
    sagittalMotionSummary.Summary, ...
    paths.sagittalSummaryCsv);

writetable( ...
    sagittalMotionSummary.Trajectories, ...
    paths.sagittalTrajectoriesCsv);

writetable( ...
    sagittalMotionSummary.RelativeTrajectories, ...
    paths.sagittalRelativeTrajectoriesCsv);

fprintf("\nCombined sagittal summary saved:\n%s\n", ...
    paths.sagittalSummaryCsv);

fprintf("Sagittal trajectories saved:\n%s\n", ...
    paths.sagittalTrajectoriesCsv);

fprintf("Baseline-relative sagittal trajectories saved:\n%s\n", ...
    paths.sagittalRelativeTrajectoriesCsv);

% CHECKPOINT:
% Review:
%   1. dependent out-of-plane ranges (expected ~constant),
%   2. pitch1/pitch2 motion,
%   3. segmental dependent r3 motion, especially aux5jnt_r3,
%   4. marker RMS/max errors in the OpenSim log,
%   5. the final motion visually in OpenSim.
%
% These outputs are intended to inform the Model C strategy after couplers
% are disabled.


%% SECTION 12 — SAVE THE MODEL B CHECKPOINT

finalIkMotion = opensimio.readMot( ...
    paths.finalIkMotionFile);

modelBCheckpoint = struct;

modelBCheckpoint.Configuration = trialCfg;
modelBCheckpoint.ProjectRoot = ...
    string(projectCfg.projectRoot);
modelBCheckpoint.InitializationCheckpointFile = ...
    paths.initializationCheckpointFile;
modelBCheckpoint.Paths = paths;
modelBCheckpoint.MarkerFile = markerFile;
modelBCheckpoint.TrialTimeRange = trialTimeRange;
modelBCheckpoint.LockExtractionMotionFile = ...
    lockExtractionMotionFile;
modelBCheckpoint.LockFilterConfiguration = ...
    filterQc;
modelBCheckpoint.LockFilterResult = ...
    lockFilterResult;
modelBCheckpoint.LockValues = lockValues;
modelBCheckpoint.ModelBResult = modelBResult;
modelBCheckpoint.ModelBValidation = modelBValidation;
modelBCheckpoint.FinalIkSetupResult = finalIkSetupResult;

modelBCheckpoint.FinalIkMotionSummary = struct( ...
    "NumRows", finalIkMotion.NumRows, ...
    "NumColumns", finalIkMotion.NumColumns, ...
    "StartTime", finalIkMotion.Time(1), ...
    "EndTime", finalIkMotion.Time(end), ...
    "InDegrees", finalIkMotion.InDegrees);

if exist("finalIkRunResult", "var")
    modelBCheckpoint.FinalIkRunSummary = struct( ...
        "SetupFile", finalIkRunResult.SetupFile, ...
        "OutputMotionFile", ...
            finalIkRunResult.OutputMotionFile, ...
        "ModelSource", finalIkRunResult.ModelSource, ...
        "RunSucceeded", ...
            finalIkRunResult.RunSucceeded, ...
        "DurationSeconds", ...
            finalIkRunResult.DurationSeconds);
end

modelBCheckpoint.LockedCoordinateAudit = ...
    lockedCoordinateAudit;
modelBCheckpoint.DependentCoordinateState = ...
    dependentCoordinateState;
modelBCheckpoint.IndependentSagittalState = ...
    independentSagittalState;
modelBCheckpoint.DependentOutOfPlaneSummary = ...
    dependentOutOfPlaneSummary;
modelBCheckpoint.IndependentSagittalSummary = ...
    independentSagittalSummary;
modelBCheckpoint.DependentSagittalSummary = ...
    dependentSagittalSummary;
modelBCheckpoint.SagittalMotionSummary = ...
    sagittalMotionSummary;

save( ...
    paths.runSummaryMat, ...
    "modelBCheckpoint", ...
    "-v7.3");

fprintf("\nModel B checkpoint saved:\n%s\n", ...
    paths.runSummaryMat);

fprintf("\nNEXT MANUAL CHECKS\n");
fprintf("1. Open Model B and 00deg_trial01_final_ik.mot in OpenSim.\n");
fprintf("2. Review marker RMS and maximum errors in the OpenSim log.\n");
fprintf("3. Confirm all ten explicitly locked coordinates remain constant.\n");
fprintf("4. Confirm dependent r1/r2 coordinates are numerically constant.\n");
fprintf("5. Review pitch1/pitch2 and dependent r3 sagittal trajectories.\n");
fprintf("6. Pay particular attention to aux5jnt_r3 (C4-C5).\n");
fprintf("7. Use the sagittal summaries/trajectories to design Model C.\n");
