%% smoke_test_external_loads_hsf.m
% Structural/mechanical smoke test for the HSF -> ExternalLoads interface.
%
% PURPOSE
%   1. Create a synthetic but mechanically consistent seven-column HSF MOT.
%   2. Read the MOT back through opensimio.readMot.
%   3. Verify the expected HSF labels and numeric content.
%   4. Generate a trial-style ExternalLoads XML using
%      opensimrun.prepareExternalLoadsSetup.
%   5. Verify the XML patch result.
%   6. Optionally ask OpenSim to parse the generated ExternalLoads XML.
%
% IMPORTANT
%   This is NOT a validation of the real trial HSF mechanics or event timing.
%   The synthetic CoM trajectory and support envelope exist only to exercise
%   the file and XML interfaces.

clear;
clc;
dbstop if error

%% SECTION 0 — PROJECT SETUP

activeFile = string(matlab.desktop.editor.getActiveFilename);

if strlength(activeFile) > 0 && isfile(activeFile)
    scriptFile = activeFile;
else
    scriptFile = string(mfilename("fullpath"));
end

assert(strlength(scriptFile) > 0 && isfile(scriptFile), ...
    "HsfSmokeTest:ScriptLocationUnknown", ...
    "Save and open this script in the MATLAB Editor before running it.");

examplesDirectory = string(fileparts(scriptFile));
projectRoot = string(fileparts(examplesDirectory)); % This script must be placed in ../examples to correctly identify root folder

assert(isfolder(fullfile(projectRoot, "+hsf")), ...
    "HsfSmokeTest:ProjectRootNotFound", ...
    "Could not locate the +hsf package under:\n%s", ...
    projectRoot);

assert(isfolder(fullfile(projectRoot, "+opensimio")), ...
    "HsfSmokeTest:OpenSimIoMissing", ...
    "Could not locate the +opensimio package.");

assert(isfolder(fullfile(projectRoot, "+opensimrun")), ...
    "HsfSmokeTest:OpenSimRunMissing", ...
    "Could not locate the +opensimrun package.");

addpath(projectRoot);

projectCfg = load_project_config();

%% SECTION 1 — RESOLVE SMOKE-TEST PATHS

smokeRoot = string(fullfile( ...
    projectCfg.outputRoot, ...
    "_smoke_tests", ...
    "external_loads_hsf"));

if ~isfolder(smokeRoot)
    mkdir(smokeRoot);
end

paths = struct;

paths.smokeRoot = smokeRoot;

paths.hsfMotionFile = string(fullfile( ...
    smokeRoot, ...
    "synthetic_hsf_smoke_test.mot"));

paths.externalLoadsFile = string(fullfile( ...
    smokeRoot, ...
    "synthetic_hsf_external_loads.xml"));

paths.qcSummaryFile = string(fullfile( ...
    smokeRoot, ...
    "synthetic_hsf_smoke_test_summary.csv"));

% Prefer the new tracked config field. Fall back to the current template
% names so the smoke test is convenient during repository transition.
if isfield(projectCfg, "externalLoadsTemplate") && ...
        isfile(projectCfg.externalLoadsTemplate)

    paths.externalLoadsTemplate = ...
        string(projectCfg.externalLoadsTemplate);

else

    candidateTemplates = [
        string(fullfile( ...
            projectCfg.templatesDirectory, ...
            "external_loads_template.xml"))
        string(fullfile( ...
            projectCfg.templatesDirectory, ...
            "hsf_setup_template.xml"))
    ];

    existingTemplate = ...
        candidateTemplates(isfile(candidateTemplates));

    assert(~isempty(existingTemplate), ...
        "HsfSmokeTest:ExternalLoadsTemplateMissing", ...
        "Could not find the ExternalLoads template. Expected either external_loads_template.xml or hsf_setup_template.xml under:\n%s", ...
        projectCfg.templatesDirectory);

    paths.externalLoadsTemplate = ...
        existingTemplate(1);
end

disp(paths);

%% SECTION 2 — LOAD HSF PARAMETERS

parameters = hsf.defaultParameters();

requiredParameterFields = [
    "BodyName"
    "SkullMassKg"
    "GravityY"
    "TargetRateHz"
    "RampDuration"
    "RampShape"
    "RadialSign"
    "AzimuthConvention"
    "InterpolationMethod"
    "ForcePrefix"
    "PointPrefix"
];

for iField = 1:numel(requiredParameterFields)

    fieldName = requiredParameterFields(iField);

    assert(isfield(parameters, fieldName), ...
        "HsfSmokeTest:MissingParameter", ...
        "hsf.defaultParameters is missing field '%s'.", ...
        fieldName);
end

assert(~isfield(parameters, "TorquePrefix"), ...
    "HsfSmokeTest:LegacyTorquePrefix", ...
    "Legacy TorquePrefix is still present in hsf.defaultParameters.");

assert(~isfield(parameters, "IncludeTorque"), ...
    "HsfSmokeTest:LegacyIncludeTorque", ...
    "Legacy IncludeTorque is still present in hsf.defaultParameters.");

assert(parameters.BodyName == "skull", ...
    "HsfSmokeTest:UnexpectedBody", ...
    "Expected HSF body name 'skull', found '%s'.", ...
    parameters.BodyName);

assert(parameters.ForcePrefix == "ground_force_1_v", ...
    "HsfSmokeTest:UnexpectedForcePrefix", ...
    "Unexpected force prefix: %s", ...
    parameters.ForcePrefix);

assert(parameters.PointPrefix == "ground_force_1_p", ...
    "HsfSmokeTest:UnexpectedPointPrefix", ...
    "Unexpected point prefix: %s", ...
    parameters.PointPrefix);

disp(parameters);

%% SECTION 3 — BUILD SYNTHETIC HSF DATA

% Use a nonzero inclination and nonzero roll so all three force-component
% columns are exercised. These values are for smoke testing only.
smokeCfg = struct;
smokeCfg.conditionDeg = 30;
smokeCfg.gndrollDeg = 25;
smokeCfg.durationSec = 2.0;

% Synthetic lift-off interval. Support is present before and after this
% interval, with the configured half-cosine ramps.
smokeCfg.liftOffWindow = [0.80, 1.20];

sampleRateHz = double(parameters.TargetRateHz);
dt = 1 / sampleRateHz;

time = (0:dt:smokeCfg.durationSec).';

numSamples = numel(time);

% Synthetic skull CoM trajectory in ground. It moves smoothly so the point
% columns are demonstrably time dependent.
comX = 0.020 + 0.003 * sin(2*pi*0.25*time);
comY = 0.300 + 0.002 * cos(2*pi*0.20*time);
comZ = -0.010 + 0.002 * sin(2*pi*0.15*time);

% Compute the intended supported-force vector using the same convention
% documented for the HSF pipeline.
weightMagnitudeN = ...
    double(parameters.SkullMassKg) * ...
    abs(double(parameters.GravityY));

radialMagnitudeN = ...
    weightMagnitudeN * tand(smokeCfg.conditionDeg);

switch string(parameters.AzimuthConvention)

    case "x_cos_z_sin"

        supportedFxN = ...
            double(parameters.RadialSign) * ...
            radialMagnitudeN * ...
            cosd(smokeCfg.gndrollDeg);

        supportedFzN = ...
            double(parameters.RadialSign) * ...
            radialMagnitudeN * ...
            sind(smokeCfg.gndrollDeg);

    otherwise

        error( ...
            "HsfSmokeTest:UnsupportedAzimuthConvention", ...
            "Smoke test currently implements only AzimuthConvention='x_cos_z_sin'. Found '%s'.", ...
            parameters.AzimuthConvention);
end

supportedFyN = weightMagnitudeN;

% Construct support envelope:
%   1 -> supported
%   0 -> head lifted away from support
%
% Ramp down immediately before lift-off and ramp up after re-contact.
envelope = ones(numSamples, 1);

liftStart = smokeCfg.liftOffWindow(1);
liftEnd = smokeCfg.liftOffWindow(2);
rampDuration = double(parameters.RampDuration);

assert(rampDuration > 0, ...
    "HsfSmokeTest:InvalidRampDuration", ...
    "RampDuration must be positive.");

assert(string(parameters.RampShape) == "halfcosine", ...
    "HsfSmokeTest:UnsupportedRampShape", ...
    "This smoke test currently implements RampShape='halfcosine'. Found '%s'.", ...
    parameters.RampShape);

% Zero-force lift-off plateau.
liftMask = time >= liftStart & time <= liftEnd;
envelope(liftMask) = 0;

% Pre-lift ramp: 1 -> 0.
preRampStart = liftStart - rampDuration;
preRampMask = time >= preRampStart & time < liftStart;

if any(preRampMask)

    alpha = ...
        (time(preRampMask) - preRampStart) / rampDuration;

    envelope(preRampMask) = ...
        0.5 * (1 + cos(pi * alpha));
end

% Post-contact ramp: 0 -> 1.
postRampEnd = liftEnd + rampDuration;
postRampMask = time > liftEnd & time <= postRampEnd;

if any(postRampMask)

    alpha = ...
        (time(postRampMask) - liftEnd) / rampDuration;

    envelope(postRampMask) = ...
        0.5 * (1 - cos(pi * alpha));
end

% Force time histories.
forceX = supportedFxN .* envelope;
forceY = supportedFyN .* envelope;
forceZ = supportedFzN .* envelope;

labels = [
    "time"
    parameters.ForcePrefix + "x"
    parameters.ForcePrefix + "y"
    parameters.ForcePrefix + "z"
    parameters.PointPrefix + "x"
    parameters.PointPrefix + "y"
    parameters.PointPrefix + "z"
].';

data = [ ...
    time, ...
    forceX, ...
    forceY, ...
    forceZ, ...
    comX, ...
    comY, ...
    comZ ...
];

assert(size(data, 2) == numel(labels), ...
    "HsfSmokeTest:ColumnMismatch", ...
    "Synthetic HSF data/label count mismatch.");

assert(all(isfinite(data), "all"), ...
    "HsfSmokeTest:NonfiniteSyntheticData", ...
    "Synthetic HSF contains nonfinite data.");

hsfMotion = struct;
hsfMotion.Labels = labels;
hsfMotion.Data = data;
hsfMotion.InDegrees = false;

fprintf("\nSynthetic supported force vector:\n");
fprintf("  Fx = %.9f N\n", supportedFxN);
fprintf("  Fy = %.9f N\n", supportedFyN);
fprintf("  Fz = %.9f N\n", supportedFzN);
fprintf("  |F| = %.9f N\n", ...
    norm([supportedFxN, supportedFyN, supportedFzN]));

%% SECTION 4 — WRITE AND READ BACK THE HSF MOT

if isfile(paths.hsfMotionFile)
    delete(paths.hsfMotionFile);
end

opensimio.writeOpenSimTable( ...
    paths.hsfMotionFile, ...
    hsfMotion, ...
    "Name", ...
    "synthetic_hsf_smoke_test", ...
    "InDegrees", ...
    false);

assert(isfile(paths.hsfMotionFile), ...
    "HsfSmokeTest:HsfWriteFailed", ...
    "Synthetic HSF MOT was not written:\n%s", ...
    paths.hsfMotionFile);

readBack = opensimio.readMot( ...
    paths.hsfMotionFile);

expectedLabels = labels;

assert(isequal( ...
        reshape(string(readBack.Labels), 1, []), ...
        reshape(expectedLabels, 1, [])), ...
    "HsfSmokeTest:LabelRoundTripFailed", ...
    "HSF labels changed after write/read round trip.");

assert(readBack.NumColumns == 7, ...
    "HsfSmokeTest:UnexpectedColumnCount", ...
    "Expected seven HSF columns; found %d.", ...
    readBack.NumColumns);

assert(readBack.NumRows == numSamples, ...
    "HsfSmokeTest:UnexpectedRowCount", ...
    "Expected %d HSF rows; found %d.", ...
    numSamples, ...
    readBack.NumRows);

assert(all(isfinite(readBack.Data), "all"), ...
    "HsfSmokeTest:NonfiniteReadBackData", ...
    "Read-back HSF contains nonfinite values.");

% Confirm exact zero force on the central lift-off plateau.
readLabels = reshape(string(readBack.Labels), 1, []);

fxIndex = find(readLabels == parameters.ForcePrefix + "x");
fyIndex = find(readLabels == parameters.ForcePrefix + "y");
fzIndex = find(readLabels == parameters.ForcePrefix + "z");

assert(numel(fxIndex) == 1 && ...
       numel(fyIndex) == 1 && ...
       numel(fzIndex) == 1, ...
    "HsfSmokeTest:ForceColumnLookupFailed", ...
    "Could not uniquely identify the three force columns.");

readTime = readBack.Time(:);

centralLiftMask = ...
    readTime >= (liftStart + 0.02) & ...
    readTime <= (liftEnd - 0.02);

centralLiftForce = ...
    readBack.Data(centralLiftMask, ...
    [fxIndex, fyIndex, fzIndex]);

assert(all(abs(centralLiftForce) < 1e-12, "all"), ...
    "HsfSmokeTest:LiftOffForceNotZero", ...
    "Force is not zero during the synthetic lift-off plateau.");

fprintf("\nHSF MOT round-trip validation passed:\n%s\n", ...
    paths.hsfMotionFile);

%% SECTION 5 — WRITE BASIC HSF SMOKE-TEST QC

forceMagnitude = sqrt( ...
    forceX.^2 + ...
    forceY.^2 + ...
    forceZ.^2);

summary = table( ...
    smokeCfg.conditionDeg, ...
    smokeCfg.gndrollDeg, ...
    sampleRateHz, ...
    numSamples, ...
    weightMagnitudeN, ...
    radialMagnitudeN, ...
    supportedFxN, ...
    supportedFyN, ...
    supportedFzN, ...
    norm([supportedFxN, supportedFyN, supportedFzN]), ...
    min(forceMagnitude), ...
    max(forceMagnitude), ...
    min(comX), ...
    max(comX), ...
    min(comY), ...
    max(comY), ...
    min(comZ), ...
    max(comZ), ...
    'VariableNames', { ...
        'ConditionDeg', ...
        'GndRollDeg', ...
        'SampleRateHz', ...
        'NumSamples', ...
        'WeightMagnitudeN', ...
        'RadialMagnitudeN', ...
        'SupportedFxN', ...
        'SupportedFyN', ...
        'SupportedFzN', ...
        'SupportedForceMagnitudeN', ...
        'MinimumForceMagnitudeN', ...
        'MaximumForceMagnitudeN', ...
        'MinimumComX', ...
        'MaximumComX', ...
        'MinimumComY', ...
        'MaximumComY', ...
        'MinimumComZ', ...
        'MaximumComZ'});

writetable( ...
    summary, ...
    paths.qcSummaryFile);

disp(summary);

%% SECTION 6 — GENERATE EXTERNAL LOADS XML

if isfile(paths.externalLoadsFile)
    delete(paths.externalLoadsFile);
end

externalLoadsResult = ...
    opensimrun.prepareExternalLoadsSetup( ...
        paths.externalLoadsTemplate, ...
        paths.externalLoadsFile, ...
        "DataFile", ...
            paths.hsfMotionFile, ...
        "ExternalLoadsName", ...
            "synthetic_hsf_smoke_test", ...
        "Overwrite", ...
            true);

disp(externalLoadsResult.TemplateValidation);
disp(externalLoadsResult.PatchReport);

assert(externalLoadsResult.VerificationPassed, ...
    "HsfSmokeTest:ExternalLoadsVerificationFailed", ...
    "prepareExternalLoadsSetup did not verify its output.");

fprintf("\nExternalLoads XML generation passed:\n%s\n", ...
    paths.externalLoadsFile);

%% SECTION 7 — OPTIONAL OPENSIM PARSE TEST

% This final check is useful when the OpenSim Java API is configured. It
% verifies that OpenSim itself can construct an ExternalLoads object from
% the generated XML. If the MATLAB/OpenSim environment is not configured,
% the earlier structural smoke test is still informative.

try
    import org.opensim.modeling.*

    externalLoads = ...
        ExternalLoads( ...
            char(paths.externalLoadsFile), ...
            true);

    fprintf( ...
        "\nOpenSim successfully parsed the generated ExternalLoads XML.\n");

    openSimParsePassed = true;

catch ME

    openSimParsePassed = false;

    warning( ...
        "HsfSmokeTest:OpenSimParseSkippedOrFailed", ...
        "OpenSim parse test did not complete successfully.\nThis may indicate either an XML compatibility problem or that the OpenSim Java API is not configured in this MATLAB session.\n\n%s", ...
        ME.message);
end

%% SECTION 8 — FINAL REPORT

fprintf("\nHSF / EXTERNAL LOADS SMOKE TEST COMPLETE\n");
fprintf("========================================\n");
fprintf("HSF MOT:             %s\n", paths.hsfMotionFile);
fprintf("ExternalLoads XML:   %s\n", paths.externalLoadsFile);
fprintf("QC summary:          %s\n", paths.qcSummaryFile);
fprintf("XML verification:    PASS\n");

if openSimParsePassed
    fprintf("OpenSim XML parse:   PASS\n");
else
    fprintf("OpenSim XML parse:   NOT CONFIRMED\n");
end

fprintf( ...
    "\nIf Sections 0-6 pass, the seven-column HSF MOT and the prepareExternalLoadsSetup XML interface are structurally compatible. The next step is to replace the synthetic CoM/envelope with the real Body Kinematics + HSF generation pipeline.\n");
